### ISSUE TITLE
[TW-974] Task edit can't correctly parse annotations with times

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1009]
_Cory Donnelly on 2010-07-15T19:25:18Z says:_ 

 Annotation times were introduced with 1.9.2 (see #390) but task edit has trouble parsing these.

<pre>$ task rc:minimal.rc add Foo
Using alternate .taskrc file minimal.rc
Created task 1
$ task rc:minimal.rc ann 1 Bar
Using alternate .taskrc file minimal.rc
Annotated 1 with 'Bar'
$ task rc:minimal.rc ls    
Using alternate .taskrc file minimal.rc

ID Project Pri Description         
 1             Foo
               2010-07-15 19:07 Bar

1 task</pre>

After editing this task with 'task edit 1' the following is displayed:

<pre>Editing complete.
Edits were detected.
Error: "2010-07-15" is not a valid date (DEFAULT).
Task couldn't handle your edits.  Would you like to try again? (y/n)</pre>

The minimal.rc is attached.  Note that #390 says that times in .dateformat are represented as H:N but I also tried H:M and experience the trouble with both.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-07-15T19:25:18Z
Modified: 2014-02-09T02:13:25Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-07-19T13:30:21Z says:_ 

 I believe this one could be as simple as using the right date format from .taskrc, if it's there, otherwise defaulting to rc.dateformat.

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2010-07-19T16:15:39Z says:_ 

 Paul Beckingham wrote:
> I believe this one could be as simple as using the right date format from .taskrc, if it's there, otherwise defaulting to rc.dateformat.

With dateformat.annotation=Y-M-D H:N task edit correctly writes the annotation datetime, but when it comes time to read it back in (unchanged) it fails.

Steps to reproduce:
1.  Set dateformat.annotation=Y-M-D H:N
1.  Create a task
1.  Add an annotation to the task
1.  Edit the task to change its name only (leaving the annotation unmodified)
1.  Note error message

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2010-07-19T16:46:11Z says:_ 

 The problem is in edit.cpp line 502:

<pre>
std::string::size_type gap = value.find (" ");
if (gap != std::string::npos)
{
  Date when (value.substr (0, gap), context.config.get ("dateformat.annotation"));
</pre>

The code checks for the first space that separates the date/time stamp from the annotation descriptions. As there are now spaces in the date/time stamp this will not work. The code is based on the old date stamps without spaces. This requires some thinking. One way would be to introduce a separator between the date/time stamps and the description, that can clearly be found and identified.

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2010-07-20T08:06:31Z says:_ 

 Fixed by introducing a separator (' -- ') in the text editor.

**Comment by pbeckingham** [comment]
[TW-974_minimal.rc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756275/TW-974_minimal.rc.txt)
