### ISSUE TITLE
[TW-975] Missing punctuation in some command output

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1010]
_Cory Donnelly on 2010-07-18T09:24:42Z says:_ 

 For example:<pre>Marked 1 task as done
Deleting task 1 'test'</pre>

This is such a minor issue it's ridiculous, but I wanted an excuse to play with git.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-07-18T09:24:42Z
Modified: 2014-02-09T02:13:25Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-07-18T09:32:25Z says:_ 

 It may seem minor, but these little imperfections add up.

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2010-07-18T13:21:12Z says:_ 

 Attachment 0001-Partially-addressed-bug-433-in-command.cpp-cleaning-.patch has been added with description: Patch to command.cpp -- other files still need patching

**Comment by pbeckingham** [comment]
[TW-975_0001-Addressed-bug-433-in-remaining-files-cleaning-up-pun.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755603/TW-975_0001-Addressed-bug-433-in-remaining-files-cleaning-up-pun.patch.txt)
[TW-975_0001-Addressing-bug-433-required-updating-a-few-tests.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755604/TW-975_0001-Addressing-bug-433-required-updating-a-few-tests.patch.txt)
[TW-975_0001-Partially-addressed-bug-433-in-command.cpp-cleaning-.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755605/TW-975_0001-Partially-addressed-bug-433-in-command.cpp-cleaning-.patch.txt)
