### ISSUE TITLE
[TW-978] Sorting by countdown doesn't work correctly for tasks with due dates less than 24h away

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1013]
_Cory Donnelly on 2010-07-17T19:06:32Z says:_ 

 (Originally reported by Michelle Crane (http://taskwarrior.org/boards/1/topics/show/554#message-555)

Here's the report definition:<pre># task long
report.long.description=Lists all task, all data, matching the specified criteria
report.long.columns=id,project,priority,entry,start,due,recur,countdown,age,tags,description  
report.long.labels=ID,Project,Pri,Added,Started,Due,Recur,Countdown,Age,Tags,Description
1. report.long.sort=countdown-,due+,priority-,project+
report.long.sort=countdown-                        
report.long.filter=status:pending
1. report.long.dateformat=m/d/Y
1. report.long.annotations=full</pre>Here's the report output -- note that tasks with IDs 1 and 10 seem swapped:<pre>$ task rc:minimal.rc long
Using alternate .taskrc file minimal.rc

ID Project Pri Added      Started Due       Recur Countdown Age    Tags Description                
 7             2010-07-17         8/15/2010          -4 wks  2 hrs      Four Weeks Away plus a day
 8             2010-07-17         8/8/2010           -3 wks  2 hrs      Three Weeks Away plus a day
 5             2010-07-17         8/14/2010          -3 wks  2 hrs      Four Weeks Away
 4             2010-07-17         8/7/2010           -2 wks  2 hrs      Three Weeks Away
 9             2010-07-17         8/1/2010           -2 wks  2 hrs      Two Weeks Away plus a day
 6             2010-07-17         7/25/2010         -7 days  2 hrs      Next Week plus a day
 3             2010-07-17         7/31/2010           -1 wk  2 hrs      Two Weeks Away
 2             2010-07-17         7/24/2010         -6 days  2 hrs      Next Week
10             2010-07-17         7/17/2010           2 hrs 8 mins      Today (later)              
 1             2010-07-17         7/17/2010          19 hrs  2 hrs      Today</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-07-17T19:06:32Z
Modified: 2014-02-09T02:13:25Z
```

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2010-07-20T16:49:22Z says:_ 

 This is not a bug -- sorting is working correctly, but the following two points contributed to the confusion:

* Tasks with no times associated with due dates are entered with due dates of 12:00 am so at 9am any tasks that are due on the current date would be listed with a countdown value of "9 hrs"
* The T-minus method of indicating past and future dates takes some getting used to

Here's a more illustrative example:<pre>ID Countdown Description                        
* - --------- -----------------------------------
 7   -3 days Due seventy-two hours in the future
 6    -1 day Due thirty-six hours in the future
 5   -12 hrs Due twelve hours in the future
 4    -7 hrs Due seven hours in the future
 3     -1 hr Due one hour in the future
 2         - Due now
 1      1 hr Due one hour ago</pre>I'm creating a unit test to ensure this continues to work.

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2010-07-20T16:59:59Z says:_ 

 With regards to

> The T-minus method of indicating past and future dates takes some getting used to

I have written about this in #392:

Countdowns have always been counted negative, for example http://www.nasa.gov/mission_pages/shuttle/launch/countdown101.html

It makes perfect sence to have them negative

Countdown is at -3
<pre>
* 3   -2   -1    0    1    2    3
* ---+----+----+----+----+----+----+----
  Now            Due
</pre>

Countdown (overdue) is at 2 (and correlates nicely with the age value which is alos positve for an event in the past)
<pre>
* 3   -2   -1    0    1    2    3
* ---+----+----+----+----+----+----+----
                 Due       Now
</pre>

The point of reference is the due date and becomes "0" on the time axis. To the left of zero we have negative numbers, to the right positive ones. The point of reference, the due date, is fixed. Only _now_, the current date, moves along the axis.

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2010-07-20T18:06:38Z says:_ 

 > Countdowns have always been counted negative, for example http://www.nasa.gov/mission_pages/shuttle/launch/countdown101.html
> 
> It makes perfect sence to have them negative

Agreed, I just haven't yet internalized the notation.

For me, the primary reason for confusion was that, when times are unspecified, Countdown uses 00:00 (midnight) -- I didn't expect countdown to report a positive number (indicating the due date had passed) before the day was over, and didn't notice the lack of a negative sign.

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2010-07-20T18:29:52Z says:_ 

 You are right about the point of time when a task becomes "overdue". It would make sense to include the day of the date that is given for due. At the moment it is exclusive. IIRC I have written something about it in the forum. Eventually one should be able to specify the "time" on a day when a task is due and becomes overdue. Either in general as Michelle pointed at 1600 or for every task individually.

**Comment by pbeckingham** [comment]
[TW-978_minimal.rc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756278/TW-978_minimal.rc.txt)
[TW-978_pending.data.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756279/TW-978_pending.data.txt)
