### ISSUE TITLE
[TW-980] Color.due.today depends on Midnight due time?

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1015]
_Michelle Crane on 2010-08-30T08:22:46Z says:_ 

 Background: I'm using (at)dateformat=Y-M-D.H:N@ as my date format.  When I create a due item, I add in the time, usually 16:00, i.e., the end of my work day.

I've also got settings for colouring my due items, e.g.,

<pre>
color.due.today=white on green
color.calendar.due.today=white on green
</pre>

I've turned off the settings for color.due and color.calendar.due for this description.

I noticed that things that are due *today* were not being highlighted - everything was taking on the colour of the color.due setting.  After a bit of experimenting, I noticed that the color.due.today colour only sticks if I haven't set the time on the due date.  For instance, an item with (at)due:today@ would show properly, but an item with (at)due:2010-08-30.16:00@ (where today = 2010-08-30) wouldn't.  

I'm attaching a couple of screenshots.  dueMidnight shows that the colours work fine for the item that is due:today, i.e., 2010-08-30.00:00.  I then changed the due time by 1 minute and looked at the calendar output again.  The colouring is gone - this is the dueMidnightPlusOne screenshot.

I would expect that anything due *today*, i.e., anytime on this particular date, would follow the color.due.today colouring.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-08-30T08:22:46Z
Modified: 2014-02-09T02:13:25Z
```

**Comment by taskwarrior** [comment]
_Michelle Crane on 2010-08-30T08:22:46Z says:_ 

 Attachment dueMidnight.png has been added with description: calendar and info output for due at midnight

**Comment by taskwarrior** [comment]
_Michelle Crane on 2010-08-30T08:22:46Z says:_ 

 Attachment dueMidnightPlusOne.png has been added with description: calendar and info output for due at 00:01

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-08-30T08:43:21Z says:_ 

 Thanks for the screenshots and detailed writeup.

**Comment by pbeckingham** [comment]
![tw-980_duemidnight](https://user-images.githubusercontent.com/7963/36642475-d3fc7bc0-1a0d-11e8-85df-d9f9a64d677e.png)
![tw-980_duemidnightplusone](https://user-images.githubusercontent.com/7963/36642476-d407e87a-1a0d-11e8-9e69-726f17cf7e67.png)
