### ISSUE TITLE
[TW-981] Priorities are sorted inconsistently (asc vs. desc)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1016]
_Johannes Schlatow on 2010-07-31T07:44:44Z says:_ 

 In descending AND ascending order, empty priorities are higher than non-empty priorities. This results in the following sorting:

for priority-:
> "" > "H" > "M" > "L"

for priority+:
> "" > "L" > "M" > "H"

I assume priority- should be inversely to priority+, hence:
> "H" > "M" > "L" > ""

I attached a patch to fix this.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-07-31T07:44:44Z
Modified: 2014-02-09T02:13:25Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-07-31T09:09:44Z says:_ 

 Thanks Johannes.

**Comment by pbeckingham** [comment]
[TW-981_descendingPriority.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756108/TW-981_descendingPriority.patch.txt)
