### ISSUE TITLE
[TW-986] User can specify due: dates that are before wait: dates

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1021]
_t charles yun on 2010-08-20T04:08:13Z says:_ 

 maybe this is a bug?  I am assuming that task should catch the fact that a due date should be after the wait date...  or is this a bad assumption? 

tcyun(at)macos ~/tcy-script/tbird-logtool 
$ t add due:tom "backwards" wait:2010/08/30
Created task 320

tcyun(at)macos ~/tcy-script/tbird-logtool 
$ t 320 info

Name          Value                               
ID            320
Description   backwards
Status        Waiting
Due           2010/08/21
Waiting until 2010/08/30
UUID          f06f5a9e-3559-4048-8ec9-e9d1b6dbba7d
Entered       2010/08/20 (3 secs)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-08-20T04:08:13Z
Modified: 2014-02-09T02:13:25Z
```

**Comment by taskwarrior** [comment]
_t charles yun on 2010-08-20T04:21:00Z says:_ 

 ahh, and it seems that you can not mark "done" a pending/waiting task but you can delete it.

not sure that i understand the thinking behind this.  but i also acknowledge that this is a really weird corner case.

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2010-08-20T08:08:16Z says:_ 

 Hi Charles,

You bring up two issues in this ticket:

1) Users can create a task that has a due date before a wait date. I personally don't like *preventing* users from doing things, but it definitely deserves discussion.

2) User can't complete a task currently set as waiting.  This will be addressed in the next minor release, see Issue #434.

**Comment by taskwarrior** [comment]
_t charles yun on 2010-08-20T08:46:11Z says:_ 

 Cory,

w/r/t your first point, some points for discussion.  I guess some of the options are:

0) leave as is

1) prevent user from creating task when wait is after due.  I agree that this is harsh.

2) throw a text warning stating that the user has done something odd.  this is prob the easiest solution but not quite perfect

3) create the task, force set both the wait and due dates to the earliest provided date, tell user what task has done "for their own good."  not clear this is the best option

4) pause flow and offer to do some action to correct the dates for the user (some complicated interactive menu of choices).

5) other options?
*  tcy

**Comment by taskwarrior** [comment]
_David Patrick on 2010-08-20T10:20:19Z says:_ 

 the wait:< date > feature is necessary and powerful but has the potential for confusion.

firstly, the status:waiting is scheduled for removal, and will leave the wait function resting on the wait: < value > attribute, so that it _will_ be possible to at least mark it done, or deleted, while still "waiting". 

secondly, I'm pushing for a more relaxed hiding behavior for waiting tasks, so that they will be listed in any query that intersects with them, and are suppressed only for a limited set of reports.

I think the users should almost never be prevented from doing something, even if it is illogical, but at the same time we should do our best to let the user know about the illogical condition, with a nice clear dialog, as it is being created. 

This is a perfect example of where the Review function will be a life-saver. The Review script should start with reports of tasks with errors, serious omissions and illogical conditions that will be brought to the forefront every time it is run. 

As new features come on line, like dependencies, the opportunity for creating illogical conditions will increase dramatically. Our response to that should be policy-driven, rather than trying to address the conflicts on a case-by-case basis. That is to say; task will allow users to create an illogical condition, but will give clear notice when the task is created, and will maintain Review reports of all such conditions. This is one thing that differentiates task from most Project Management applications, which will typically refuse to create the condition in the first place.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-08-23T15:22:06Z says:_ 

 I agree with Cory and David, in that I don't like to see task enforcing the notion that wait < due, but should certainly generate a warning.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-08-23T15:25:29Z says:_ 

 David, do you think if we relax the hiding of waiting tasks, that it then creates a need for a stricter version of wait as well?  Waiting was added as a way to get tasks out of the reports, for example with an annual recurring task, you may not want to stare at the next due instance for a year.

I think if waiting tasks start creeping back into reports, then we need a stronger version of wait.

OR

Leave wait as is it (as we are used to), and add a milder form of wait.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-09-01T23:06:59Z says:_ 

 Now generates warnings.

**Comment by zombiefungus** [comment]
I would like to point that these warnings don't include the involved task, so they become unclear when modifying more than one task
