### ISSUE TITLE
[TW-995] Text alignment in reports is broken when text contains utf8 characters

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1030]
_Johannes Schlatow on 2010-08-01T08:04:23Z says:_ 

 This is due to a miscalculation of the character length. String.length() returns the length of a string in bytes, which does not match the number of characters when there is a multi-byte utf8 sequence.
I attached a quick fix that solves this issue without any conversion to another string class (e.g. Glib:ustring).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-08-01T08:04:23Z
Modified: 2014-02-09T02:13:26Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-08-01T09:32:39Z says:_ 

 Thanks Johannes.

**Comment by pbeckingham** [comment]
[TW-995_utf8StringLength.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755536/TW-995_utf8StringLength.patch.txt)
