### ISSUE TITLE
[TW-1010] The log command doesn't provide any output on success

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1045]
_Cory Donnelly on 2010-07-17T17:25:03Z says:_ 

 The log command ought to provide some output.  Patch to 1.92 attached.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-07-17T17:25:03Z
Modified: 2014-02-09T02:13:26Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-07-17T19:37:59Z says:_ 

 Applied patch - thanks Cory.

**Comment by pbeckingham** [comment]
[TW-1010_command.cpp.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756107/TW-1010_command.cpp.patch.txt)
