### ISSUE TITLE
[TW-1040] Slight cosmetic change

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1075]
_ed neville on 2010-07-03T06:48:21Z says:_ 

 I've noticed that some of the help items don't include the ID in their listing.

Attached is a very minor patch file for this change.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-07-03T06:48:21Z
Modified: 2014-02-09T02:15:15Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-07-03T09:30:11Z says:_ 

 Patch applied to 1.9.2 branch.  Thank you Ed - you're in the 1.9.2 AUTHORS file.

**Comment by pbeckingham** [comment]
[TW-1040_report.cpp.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756281/TW-1040_report.cpp.patch.txt)
