### ISSUE TITLE
[TW-1054] Time stamp added to annotations

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1089]
_Cory Donnelly on 2010-03-02T13:07:06Z says:_ 

 In addition to dates, it would be nice to have timestamps added to annotations as well. For me, when I need to know the day something happened I nearly always want to know what time it happened, too. I've been faking it like this:

<pre>
$ task ann 104 -- 1356 Emailed John Doe about scheduled downtime
Annotated 104 with '1356 Emailed John Doe about scheduled downtime'
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-03-02T13:07:06Z
Modified: 2014-02-09T02:15:15Z
```

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2010-03-05T17:43:03Z says:_ 

 Associated with issue #189 -- if we implement #390 first, then #189 could directly follow:

<pre>
$ proposedtask info 95

Name        Value                                                               
ID          95
Description Install hotfix in kb 962351 to allow IE8 to view menu items correctly
            2010-02-24 11:33:49 Started
            2010-02-24 14:13:21 Stopped
Status      Pending
Tags        work-server www
UUID        c5099c40-671b-463e-bb95-3fba853110bb
Entered     2010-02-24 (9 days)
</pre>

**Comment by pbeckingham** [comment]
![tw-1054_screen_shot_2010-06-03_at_11 20 21_pm](https://user-images.githubusercontent.com/7963/36643287-54fd9fd4-1a17-11e8-9a70-e34afb66237b.png)
