### ISSUE TITLE
[TW-1057] Issues with task push/pull/merge

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1092]
_Andra Levstik on 2010-11-16T04:44:46Z says:_ 

 As per bugs: #547 #540

There are issues with pushing pulling and merging.

Pushing pulling either doesn't push all files(0 byte) or fails to complete if any of the files are missing(returns the rather useless
Could not run curl.  Is it installed, and available in $PATH?; even though the actual error might be curl: (78) RETR response: 550

I don't have any output of the push/pull around anymore but basically it was: not found completed.data not found pending.data found undo.data. And then: Could not run curl.  Is it installed, and available in $PATH?

task merge not working to ftp remote:
ruskie @ omikron 7:33:19 0 pts/6 
13286 0 % ~ > task merge
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3617  100  3617    0     0   1109      0  0:00:03  0:00:03 --:--:--  1117

Merge complete.
Would you like to push the merged changes to 'ftp://ftp.codemages.net/tasks/'? (y/n) y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
Local tasks transferred to ftp.codemages.net/tasks/

ruskie @ omikron 7:34:02 0 pts/6 
13288 0 % ~ > task merge
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3617  100  3617    0     0   1104      0  0:00:03  0:00:03 --:--:--  1109

Merge complete.
Would you like to push the merged changes to 'ftp://ftp.codemages.net/tasks/'? (y/n) y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
Local tasks transferred to ftp.codemages.net/tasks/

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-11-16T04:44:46Z
Modified: 2014-02-09T02:15:42Z
```

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2010-11-21T19:19:07Z says:_ 

 Please try the patch I attached.

**Comment by pbeckingham** [comment]
[TW-1057_0001-Bug-548.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756282/TW-1057_0001-Bug-548.patch.txt)
