### ISSUE TITLE
[TW-1062] Compile error on current archlinux

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1097]
_Johannes Schlatow on 2010-05-09T18:07:46Z says:_ 

 There is a compile error on archlinux. I figured out how to solve this, could you please verify my patch?

Maybe this is caused by the recent gcc update from 4.4 to 4.5

See the comments to the AUR package for more details:
http://aur.archlinux.org/packages.php?ID=22085

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-05-09T18:07:46Z
Modified: 2014-02-09T02:16:26Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-05-09T18:26:34Z says:_ 

 Patch applied, tests pass.  Thank you Johannes.

**Comment by pbeckingham** [comment]
[TW-1062_task_patch.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756283/TW-1062_task_patch.diff.txt)
