### ISSUE TITLE
[EX-7] task backup [ filename.tar [ .gz ] ]

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#11]
_David Patrick on 2011-09-11T16:41:19Z says:_ 

 "Back up your files before playing with alphas" says Frederico, and he's right!

so alls we have to do is to make a copy of pending.data and completed.data .. and the .taskrc of course.
and we want to keep our installed plugins.. and included themes.. and holiday files maybe.. and .. ?

This proposed new command would do all of that in one fell swoop. 
Without options supplied, the command would create a tar archive called task.backup.<date>.tar, 
and with options might be named task.backup.<date>.<filename>.tar.gz

this is obviously targeted at the lazy, error-prone linux users amongst us

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-09-11T16:41:19Z
Modified: 2014-02-09T02:43:22Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2011-09-11T16:48:02Z says:_ 

 this might also be a cryptographic opportunity

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-09-11T16:54:50Z says:_ 

 Excellent.  I think this should be an external script (as David noted by 'non-core').

By using the alias feature in 2.0, this script could be accessed as though it were a built-in command:

<pre>
task config alias.backup 'execute backup.sh'
</pre>

**Comment by taskwarrior** [comment]
_Štěpán Henek on 2012-07-16T23:49:21Z says:_ 

 Hello guys, I recently created a simple python script which performs such backups. (see attached file). It backups only ~/task and ~/.taskrc by default, but you can specify the backup files/dirs as a parameter.

You can try it using the alias:
> (at)task config alias.backup "execute path-to-script/backup.py -o path-to-backup/task.backup-%Y-%m-%d.tar.gz"@

I also think that it might be a good idea to create a git repository inside the ~/.task dir for making snapshot using normal git commit.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-07-17T02:59:06Z says:_ 

 Thank you Štěpán.  I added your script to the "External Scripts" page.  This feature is now closed!

**Comment by pbeckingham** [comment]
[EX-7_backup.py.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755305/EX-7_backup.py.txt)
