### ISSUE TITLE
[TW-1067] Users shouldn't be required to manually add the current date to annotations when editing a task

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1102]
_Cory Donnelly on 2010-04-12T18:03:52Z says:_ 

 I got tired of adding the current date to annotations created during task edit sessions and realized that I was very rarely adding annotations for dates other than the current date. I figured it might be worthwhile to include the current date automatically.

Sample edit window, before my patch:<pre># Annotations look like this: <date> <text>, and there can be any number
1.  of them.
  Annotation:        
  Annotation:        </pre>

Sample edit window, after my patch:<pre># Annotations look like this: <date> <text>, and there can be any number
1.  of them.
  Annotation:        2010-04-12
  Annotation:        2010-04-12</pre>The change in the patch accommodates context.config.get ("dateformat").

Patch to v1.9.0 edit.cpp is attached for your review -- if you'd rather not roll it into the trunk, that's fine!

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-04-12T18:03:52Z
Modified: 2014-02-09T02:16:26Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-04-12T18:22:25Z says:_ 

 Cory, that's a nice idea, and a nice clean patch.  Applied.  Thank you!

**Comment by pbeckingham** [comment]
[TW-1067_edit.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756284/TW-1067_edit.patch.txt)
