### ISSUE TITLE
[TW-49] Due dates cause tasks to be overdue too early

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#111]
_Jon S on 2010-11-17T10:12:44Z says:_ 

 In task 1.9.3, when you assign a due date of 'today', the task displays immediately as overdue, even at 1 minute past midnight.  It would be more useful if a task is due at 23:59 or something like that.  This would stop a task being overdue the moment its created.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-11-17T10:12:44Z
Modified: 2015-11-18T13:08:44Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-11-17T10:23:30Z says:_ 

 Related to: http://taskwarrior.org/issues/show/454

Thanks Jon.

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-01-25T17:24:57Z says:_ 

 Needs more thinking. It is more complicated than it looks.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-01-28T14:49:59Z says:_ 

 Deferring for now.

I believe the solution to this is to interpret "due friday" as "due:friday at 24:00:00", which is the ISO-8601:2004 suggested means of indicating end of day.  This will be addressed by kronisk, which will replace all date parsing and handling in taskwarrior.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-07-25T15:35:56Z says:_ 

 The following patch solves the issue for relative dates: each dates is interpreted as Paul suggested ("due friday" as "due:friday at 23:59:59").

**Comment by taskwarrior** [comment]
_Jim B on 2012-07-26T02:56:59Z says:_ 

 Maybe I'm unique in the way I use due dates, but I actually prefer the current behavior.  If I add something that's "due:today" that that means I'd better work on it before 23:59!  And if I add something due:tomorrow, then I want to know about it right away when I start using Taskwarrior the next day, so I can make sure the task is actually completed on or before the time it's due.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-07-26T03:45:11Z says:_ 

 Jim B wrote:
> Maybe I'm unique in the way I use due dates, but I actually prefer the current behavior.

I do too, but that is immaterial.  Taskwarrior needs to support different notions of concepts like "yesterday", "today", "end of week", and so on.  We need to support all viewpoints, and when you combine this issue with #454, the result is more flexibility.  In the meantime, instead of 'today', just set the explicit date and time for your due dates.

For example, these statements have different meanings:

"finish that report by Friday"
"I need that report by end of week"
"you have until Friday to finish that report"

Some would argue that the first one really means Thursday at 23:59:59.  We learned a long time ago that one size does not fit all regarding Taskwarrior, so we're just trying to make this flexible.  Don't consider #551 without #454.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-07-26T13:38:28Z says:_ 

 Thinking about this, there may even be situations when 'fri' means Friday at the end of the day (for deadlines) and situations when 'fri' means Friday at the start of the day (for scheduled tasks). Considering #454, there may be both an End of Day value and a Start of Day value. Then, I am not sure how to use them (with short-cuts 'frieod' and 'frisod' for example depending on what is expected).

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-11-18T13:08:44Z says:_ 

 Closing this issue.

Some arbitrary choices have been made, namely that `today` means the very beginning of the local day.  `now` is another one that means the current time, and a task created with `due:now` is also going to be immediately overdue.  There is also `eod` available, which means the very end of the day.

I think this is simply the terminology we use that is causing the problem.  If we think of the attribute 'due' meaning 'due before', then the above is clearer: 'due before today', 'due before now' and 'due before eod' all suddenly make sense.

We have a rich enough set of alternatives that we cover all the cases needed.

**Comment by pbeckingham** [comment]
[TW-49_0001-Bug-551.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755550/TW-49_0001-Bug-551.patch.txt)
