### ISSUE TITLE
[TW-1091] Autogenerated .taskrc should reference man taskrc

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1126]
_Cory Donnelly on 2009-12-05T11:05:26Z says:_ 

 I've been using various flavours of linux for years and have a mac now, but it never occurred to me to check to see if a man page had been created for .taskrc (or task itself) as Paul suggested in Issue #335 -- can I respectfully propose a minor change to the automatically-created .taskrc files?

Trivial patch attached -- please feel free to tweak/disregard.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-12-05T11:05:26Z
Modified: 2014-02-09T02:18:06Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2009-12-05T11:19:56Z says:_ 

 Thanks for the patch Cory.  I did tweak it a little, and also added similar to the "version" command output.

**Comment by pbeckingham** [comment]
[TW-1091_Config.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756285/TW-1091_Config.patch.txt)
