### ISSUE TITLE
[TW-1092] Countdown column in reports similar to Age

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1127]
_Federico Hernandez on 2010-02-12T12:09:09Z says:_ 

 Sobbie suggested to have a "Countdown" column in reports similar to the age column. The countdown column should show the days left until a task due or how many days a task has been overdue.

See http://taskwarrior.org/boards/6/topics/show/374

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-02-12T12:09:09Z
Modified: 2014-02-09T02:18:06Z
```

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2010-02-12T12:11:46Z says:_ 

 Done

**Comment by pbeckingham** [comment]
![tw-1092_taskcntdwn](https://user-images.githubusercontent.com/7963/36643307-952918e0-1a17-11e8-9629-185fba9659c8.png)
