### ISSUE TITLE
[TW-54] Reduce output for timesheet

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#115]
_Aikido Guy on 2011-09-14T02:26:51Z says:_ 

 I think that too much output is not helpful.

Consider the following output in TaskWarrior 1.9.4:
```
$ task timesheet +tag 10

2011/09/12_00:00 - 2011/09/18_00:00
  Completed (0 tasks)
  Started (0 tasks)

2011/09/05_00:00 - 2011/09/11_00:00
  Completed (0 tasks)
  Started (0 tasks)

2011/08/29_00:00 - 2011/09/04_00:00
  Completed (0 tasks)
  Started (0 tasks)

2011/08/22_00:00 - 2011/08/28_00:00
  Completed (0 tasks)
  Started (0 tasks)

2011/08/15_00:00 - 2011/08/21_00:00
  Completed (0 tasks)
  Started (0 tasks)

2011/08/08_00:00 - 2011/08/14_00:00
  Completed (0 tasks)
  Started (0 tasks)

2011/08/01_00:00 - 2011/08/07_00:00
  Completed (0 tasks)
  Started (0 tasks)

2011/07/25_00:00 - 2011/07/31_00:00
  Completed (0 tasks)
  Started (0 tasks)

2011/07/18_00:00 - 2011/07/24_00:00
  Completed (0 tasks)
  Started (0 tasks)

2011/07/11_00:00 - 2011/07/17_00:00
  Completed (0 tasks)
  Started (0 tasks)
```

I think the following would be sufficient:
```
$ task timesheet +tag 20

2011/09/12_00:00 - 2011/05/08_00:00
  Completed (0 tasks)
  Started (0 tasks)
```

That is, I'm suggesting that contiguous weeks be compressed into 1 output entry.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-09-14T02:26:51Z
Modified: 2017-01-16T15:41:28Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-09-14T02:39:55Z says:_ 

 Do you mean compression only for weeks that show zero activity?  If so, nice idea.

**Comment by taskwarrior** [comment]
_Aikido Guy on 2011-09-14T18:22:52Z says:_ 

 Yup, I meant that :)

If the number of weeks that are being compressed could also be output, that would be even nicer!
<pre>$ task timesheet +tag 20

2011/09/12_00:00 - 2011/05/08_00:00 (20 weeks)
  Completed (0 tasks)
  Started (0 tasks)</pre>

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-16T15:40:50Z says:_ 

 I think the `timesheet` command needs an overhaul.  It needs the following improvements:

* Start and end date filtering
* Report granularity (day, week, month, year)
* Skip periods that are empty (the whole point of this issue)
* Compact report output, not lots of short lines
* Observe weekstart

**Comment by pbeckingham** [comment]
Timesheet overhauled. Forgot to close this.
