### ISSUE TITLE
[TW-1118] Confirmation dialog response is case-sensitive, but shouldn't be

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1153]
_Cory Donnelly on 2009-12-07T11:41:24Z says:_ 

 This bug existed previously, but I only noticed it in 1.8.5 because of a change made when the 'quit' option was introduced.  Patch to util.cpp attached.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-12-07T11:41:24Z
Modified: 2014-02-09T02:32:03Z
```

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2009-12-07T18:30:08Z says:_ 

 The uppercase "Y" is used intentionally. As an extra step to confirm changes by having to use 2 keys. The bug would be the lowercase "a" in all.

**Comment by pbeckingham** [comment]
[TW-1118_util.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756290/TW-1118_util.patch.txt)
