### ISSUE TITLE
[TW-1124] Applying changes to one task affects another

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1159]
_Cory Donnelly on 2009-11-15T22:39:33Z says:_ 

 I experience this issue under v1.8.3.  Updating the description (specified by task ID) causes the description to be updated for another task as well. May be related to Bug #208.

Most data in the attached database were initially imported from todo.sh v2.4, although the affected tasks were entered by hand.

<pre>
$ t ls 79

ID Tags             Project             Description
79 home-online home Recurring_Pay_bills sanitized
</pre>

<pre>
$ t strangeness 79

Task 78 "sanitized"
*  description was changed from 'sanitized' to 'strangeness'
Are you sure? (yes/no/all) n

Task 79 "sanitized works"
*  description was changed from 'sanitized' to 'strangeness'
Are you sure? (yes/no/all) y
Modified 1 task
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-11-15T22:39:33Z
Modified: 2014-02-09T02:33:52Z
```

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2009-11-16T08:58:34Z says:_ 

 Please disregard the inconsistency in the description of task 79 in the above output of `t strangeness 79` -- in testing bug #208 I mangled this output. In the lines beginning 'Task [78|79],' the descriptions of both tasks were reported correctly -- the issue was that task 78 was incorrectly included.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2009-11-16T22:44:00Z says:_ 

 After puzzling over this one I realized that the two tasks are related.  78 is the parent task of 79.  This can be seen with:

    task info 78-79

This is therefore functioning as designed - edits to a recurring task are propagated to other instances of that same task, including the parent.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2009-11-16T23:02:03Z says:_ 

 No fix because this is intended functionality.

Added warning when modifying a recurring task that all instances of the recurring task may be modified.  Further identified all recurring tasks when asking the "Are you sure?" question.

**Comment by pbeckingham** [comment]
[TW-1124_pending.data.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756291/TW-1124_pending.data.txt)
