### ISSUE TITLE
[TW-1125] Edit command fails when data.location includes directories containing spaces

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1160]
_Cory Donnelly on 2009-11-16T11:11:28Z says:_ 

 Experienced under v1.8.3 running on cygwin, likely elsewhere as well. Trivial patch attached.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-11-16T11:11:28Z
Modified: 2014-02-09T02:33:52Z
```

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2009-11-16T11:11:28Z says:_ 

 Attachment edit.patch has been added with description: Patch file

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2009-11-16T22:02:41Z says:_ 

 Nice patch.  Thank you.

**Comment by pbeckingham** [comment]
[TW-1125_edit.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756292/TW-1125_edit.patch.txt)
