### ISSUE TITLE
[TW-1138] task stepping

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1173]
_Levent Dane on 2009-10-25T17:18:22Z says:_ 

 can i step tasks, or can i specify one task two another's conditional?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-10-25T17:18:22Z
Modified: 2014-02-09T02:36:31Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2009-10-25T17:27:43Z says:_ 

 Hello and welcome.

I'm not sure what you mean - are you asking whether task supports depedencies between tasks?  Perhaps you could elaborate with an example or two?

Thanks.

**Comment by taskwarrior** [comment]
_Levent Dane on 2009-10-25T17:32:47Z says:_ 

 Paul Beckingham wrote:
> Hello and welcome.
> 
> I'm not sure what you mean - are you asking whether task supports depedencies between tasks?  Perhaps you could elaborate with an example or two?
> 
> Thanks.

Hi :)
yes it's also callable like dependency.

1. go to car
2. after that go to shopping
3. don't forget buy milk

3. task depend to 2. one, then i don't want to see 3. task in list. When 2. task is over i can see 3. task.

Could i make myself clear?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2009-10-25T17:44:36Z says:_ 

 Thank you - I understand the question now.

We do not currently have the ability to create dependencies between tasks.  There are internal dependencies created for recurring tasks, but that is not what you are asking about.  The feature you are requesting remains unscheduled, and to some degree, still needing design.

We had detailed discussions on the topic of task dependencies early this year, and covered a lot of issues.  But we never completely solved all the issues surrounding this much-asked-for feature.  This issue (#305) will be now used to reflect that we wish to put those discussions up online so we can refine them and work toward a usable design.

If you have suggestions on how this feature would work, or rather, how *you* would want this feature to work, please post them in the forums.  We need  all the input and help we can get when working on big features like dependencies.

**Comment by taskwarrior** [comment]
_Levent Dane on 2009-10-25T17:54:34Z says:_ 

 ah i didn't see forum post. i find now. Can you change title to task dependency?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2009-10-25T17:59:06Z says:_ 

 No, I cannot change titles.  I wish I could!

**Comment by taskwarrior** [comment]
_David Patrick on 2009-10-26T07:57:34Z says:_ 

 this is a duplicate of feature #169 , which is the focus of version 2.6.. (quite a ways down the roadmap)

**Comment by sampablokuper** [comment]
Related (I think): [[TW-742] dependencies on recurring tasks](https://github.com/GothenburgBitFactory/taskwarrior/issues/777).
