### ISSUE TITLE
[TW-1139] taskrc.vim

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1174]
_David Patrick on 2009-11-04T21:00:29Z says:_ 

 the syntax highlighting file.
should happen, at some point

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-11-04T21:00:29Z
Modified: 2014-02-22T17:50:04Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2009-11-05T00:37:13Z says:_ 

 John is really good at making these...

**Comment by taskwarrior** [comment]
_John Florian on 2009-11-12T08:40:08Z says:_ 

 Are we talking about highlighting of ~/.taskrc itself or something else?  When I edit mine vim uses syntax=conf by default probably because of the comment style.  For me this is pretty normal as most conf files all look the same and I really only need comment vs. not-a-comment highlighting, but we could certainly do more quite easily.  For example, I could give us:

<color-1>keyword</color-1><color-2>=</color-2><color-3>value</color-3>

If I did this, we could then go two routes:
1.  taskrc.vim would have a list of all valid keywords (i.e., setting names) and highlight those one color and all other keywords (to the left of the equal sign) in another color to indicate an error.
1.  taskrc.vim would not have a list of any keywords and all keywords are highlighted the same color.

The former has the advantage of being more user-friendly and the latter the advantage of less maintenance.  I'm fine with either.

**Comment by taskwarrior** [comment]
_David Patrick on 2009-11-12T09:20:57Z says:_ 

 John Florian wrote:
> Are we talking about highlighting of ~/.taskrc itself ?
yes

When I edit mine vim uses syntax=conf by default probably because of the comment style.  For me this is pretty normal as most conf files all look the same and I really only need comment vs. not-a-comment highlighting, but we could certainly do more quite easily.

does the conf.vim highlight keywords and values and such ?


  For example, I could give us:
> 
> <color-1>keyword</color-1><color-2>=</color-2><color-3>value</color-3>
> 
> If I did this, we could then go two routes:
> 
> # taskrc.vim would have a list of all valid keywords (i.e., setting names) and highlight those one color and all other keywords (to the left of the equal sign) in another color to indicate an error.
> # taskrc.vim would not have a list of any keywords and all keywords are highlighted the same color.
> 
> The former has the advantage of being more user-friendly and the latter the advantage of less maintenance.  I'm fine with either.

yes, either way
the intent is to help users form correct syntax. There's a lot to be said for the low-maintenance approach though, but I would lean towards the list-of-keywords.
djp

**Comment by taskwarrior** [comment]
_John Florian on 2009-11-12T11:17:12Z says:_ 

 I'm leaning towards the first route.  How can I get a complete list of valid keywords?  Would just having task create a brand-new default ~/.taskrc be sufficient?

Even this route will have to be somewhat dynamic to handle "report.ANYTHING_HERE.{description,colums,labels,etc}".  Are there any other keywords besides "report.*" that would also need to be dynamic?

**Comment by taskwarrior** [comment]
_David Patrick on 2009-11-12T12:33:30Z says:_ 

 John Florian wrote:
> I'm leaning towards the first route.  How can I get a complete list of valid keywords?
If you know any really good programmers who are intimate with the inner workings of task, and who ALSO happen to live in the Boston area, ask them how hard it would be to code a "task keywords" function.


  Would just having task create a brand-new default ~/.taskrc be sufficient?
would it help ?
> 
> Even this route will have to be somewhat dynamic to handle "report.ANYTHING_HERE.{description,colums,labels,etc}".  Are there any other keywords besides "report.*" that would also need to be dynamic?

I can't think of any right now.. but then again, I haven't had a lot of sleep this week.
djp

**Comment by taskwarrior** [comment]
_John Florian on 2009-11-28T12:20:53Z says:_ 

 David,

Please give the attached files a try.  You should be able to just extract them in your home directory.

The highlighting generally tries to make things like "foo=bar" easy to read.  If foo is a known to be good, it gets highlighted differently than those that are not.

It even neatly handles things like color.tag.baz and report.baz.columns where baz is user-defined whereas the rest are a rigid part of the syntax.

I'd like to handle the report definitions better so that for columns, sort and filter valid names are dealt with similarly.  I'm already aware that the "due" name is handled oddly because it also happens to be a valid setting name.

Also, there's no folding at this time and I'm not sure where folding should even occur, maybe just on a per paragraph level?

**Comment by taskwarrior** [comment]
_John Florian on 2009-11-28T12:20:53Z says:_ 

 Attachment task-vim-support.tgz has been added with description: task support for vim -- extract in home dir

**Comment by taskwarrior** [comment]
_David Patrick on 2009-12-07T22:15:47Z says:_ 

 after botching the uber simple install instructions, I got this in place and it looks GREAT !
way better, thank you John !
there's already a ticket re: folding, but I think we need to firmly establish the rc file layout and heading styles.

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2014-02-20T13:16:29Z says:_ 

 I tested it. For me, it works as desired.

Why don't we ship this with the next version?

A.) Make it standard
B.) Provide it via --with-vim-theme

* It would make sense to extend it for Taskserver.
* Colors in vim ≠ colors in task ('task colors'). The same colors for different things may confuse the user. (_Mom, why have you washed my white T-Shirt with my new blue sweatshirt?! Now both are blue._)

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2014-02-20T17:32:12Z says:_ 

 Can someone link this with https://bug.tasktools.org/browse/TW-485, please?

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-02-21T00:28:38Z says:_ 

 Linked as "relates to"

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2014-02-22T17:50:04Z says:_ 

 Exactly.

**Comment by pbeckingham** [comment]
[TW-1139_task-vim-support.tar.gz](https://github.com/GothenburgBitFactory/taskwarrior/files/1756298/TW-1139_task-vim-support.tar.gz)
