### ISSUE TITLE
[TW-1171] bash_completion does not do projects

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1206]
_John Florian on 2009-06-20T18:29:01Z says:_ 

 In 1.7.1 I cannot use the tab here, like one would think:

task add Get requirements pro:<tab>

If this hasn't already been resolved, I'll be glad to do so.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-06-20T18:29:01Z
Modified: 2014-02-09T02:39:07Z
```

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2009-06-21T05:21:52Z says:_ 

 Great. Provide a patch an I will merge it with the changes I had ongoing.

**Comment by taskwarrior** [comment]
_John Florian on 2009-06-29T23:39:05Z says:_ 

 Federico, here's a patch that allows completion of project names so long as you've typed at least "pro:".  Of course, it's happy if you've given "project:" or anything in between.  In addition, I've also made tags more friendly as I found that I couldn't complete them for "task add".  Not sure that I formatted the commit message properly for git, but the patch looks sane enough that you should be able to apply it.

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2009-06-30T16:42:26Z says:_ 

 THX for the patch, John. Great work. I will apply and push it in the next few days.

**Comment by pbeckingham** [comment]
[TW-1171_0001--bash-completion-now-supports-project-names.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756301/TW-1171_0001--bash-completion-now-supports-project-names.patch.txt)
