### ISSUE TITLE
[TW-66] task start Add new task and start it

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#125]
_Steffen Uhlig on 2013-07-17T20:48:20Z says:_ 

 Sometimes a new task comes in and needs to be worked on right away, so I would like to suggest this syntax:

<pre>
$ task start Add new task and start it
Created task 2.
Starting task 2 'Add new task and start it'.
Started 1 task.</pre>

I recognise that this is similar to #566, but I think the presence of a task id could be the criteria for whether the passed argument is an annotation for the existing task or the description of a new one, so that this would still work:

<pre>
$ task 1 start Add an annotation to task 1 and start it
Starting task 1 'Do at least something'.
Started 1 task.</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-07-17T20:48:20Z
Modified: 2014-07-02T02:41:55Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-09-29T18:01:41Z says:_ 

 Sounds like an ideal tests case for hooks.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-07-02T02:41:55Z says:_ 

 Hooks.

**Comment by gudata** [comment]
Hey,
Reading the answers it is not clear to me how to self serve the auto start for the task.

Could you please give an example because I hit this scenario too often.

Thank you!
