### ISSUE TITLE
[TW-1245] encryption plug-in

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1280]
_David Patrick on 2009-07-07T01:07:28Z says:_ 

 that makes it easy to secure your data.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-07-07T01:07:28Z
Modified: 2015-09-25T06:14:58Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-14T04:15:20Z says:_ 

 Extension

**Comment by taskwarrior** [comment]
_Štěpán Henek on 2012-07-25T06:55:09Z says:_ 

 I'd like to implement this feature as a python plugin.

From my point of view there are two possible ways how to do it:
* Use standard pgp mechanism (gnugp)
* Design own file encrypting mechanism (using RSA, AES, ...)

Do you have any suggestions or ideas how to do it?

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2012-07-25T09:29:27Z says:_ 

 I can think of two approaches to implement this:
1.  One could encrypt the whole data files but this requires imo to hook into all file reads, which is not possible right know.
1.  The other approach is to encrypt each data field on its own (description, project, tags,...). I'm not sure whether there is an appropriate hook for this. One could possibly introduce a UDA which holds the corresponding GPG key(s), thus enabling a database to be shared partially.

**Comment by taskwarrior** [comment]
_David Patrick on 2012-07-25T16:53:55Z says:_ 

 Johannes Schlatow wrote:
> # The other approach is to encrypt each data field on its own (description, project, tags,...). I'm not sure whether there is an appropriate hook for this. One could possibly introduce a UDA which holds the corresponding GPG key(s), thus enabling a database to be shared partially.

recutils (a text database) handles encryption by declaring a field type as "confidential", marking the data as encrypted, and leaving the encryption/ decryption to whatever local apps. It's not super-secure, or anything, but it seems to be effective and easy to handle.
http://www.gnu.org/software/recutils/manual/html_node/_0025confidential.html#_0025confidential

**Comment by taskwarrior** [comment]
_Štěpán Henek on 2012-07-25T18:25:04Z says:_ 

 David Patrick wrote:
> Johannes Schlatow wrote:
> > # The other approach is to encrypt each data field on its own (description, project, tags,...). I'm not sure whether there is an appropriate hook for this. One could possibly introduce a UDA which holds the corresponding GPG key(s), thus enabling a database to be shared partially.
> 
> recutils (a text database) handles encryption by declaring a field type as "confidential", marking the data as encrypted, and leaving the encryption/ decryption to whatever local apps. It's not super-secure, or anything, but it seems to be effective and easy to handle.
> http://www.gnu.org/software/recutils/manual/html_node/_0025confidential.html#_0025confidential

This form of encryption seems interesting. The encrypted JSON records could look like this
@[description:encrypted-AAABBBCCDDDEEEFFF entry:"1337443748" status:"pending" uuid:encrypted-AAABBBCCDDDEEEFFF]@

But user may also want to encrypt entire particular record.
@[encrypted:AABBCCDDEEFF00112233445566778899..]@
would decrypt to
@[description:"Test" entry:"1337443748" status:"pending" uuid:"67439784-9145-4e2c-b2b5-1c0816977e97"]@

**Comment by taskwarrior** [comment]
_David Patrick on 2012-07-25T18:42:16Z says:_ 

 Štěpán Henek wrote:
> This form of encryption seems interesting. The encrypted JSON records could look like this
> @[description:encrypted-AAABBBCCDDDEEEFFF entry:"1337443748" status:"pending" uuid:encrypted-AAABBBCCDDDEEEFFF]@

or something like that, yeah. The External Script part would be the graceful handling of the password prompt that would be required any time a confidential field was decrypted, and the application of the password, any time an confidential field is written to. Some of the pain might be molified with per-session passwords, although the security purists would shudder.

**Comment by taskwarrior** [comment]
_David Patrick on 2012-07-25T18:56:23Z says:_ 

 David Patrick wrote:
> The External Script part would be the graceful handling of the password prompt

and the identification of the confidential fields, which could be as easy as 

 confidential_fields=uuid,description,myfield

and then the enforcement of the notion that a confidential field can contain ONLY password-encrypted string. If tw-crypto (coined) were installed, any non-encrypted contents in confidential fields would constitute a show-stopper error. Luckily, the option to immediately apply encryption to that content would fix it.

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2012-07-25T19:58:51Z says:_ 

 Before someone puts work into this:

Are there any use cases for which simply encrypting the contents of ~/.task and hence all of Taskwarrior's data files would not be sufficient? "EncFS":http://en.wikipedia.org/wiki/EncFS seems like a good fit - it is available in most (all?) Linux distros, there is an OSX and a Windows port. It would mean less work and less specialization, which is usually a good thing. If you need something EncFS would not allow for or feel like implementing an encryption extension for the fun of it though, then by all means go ahead! ;)

**Comment by taskwarrior** [comment]
_David Patrick on 2012-07-25T20:14:24Z says:_ 

 Wim Schuermann wrote:
> Before someone puts work into this:
> 
> Are there any use cases for which simply encrypting the contents of ~/.task and hence all of Taskwarrior's data files would not be sufficient?

yes, the case where a task.data files is synced or shared with others, or when 97% of the content DOESN'T need to be encrypted. Per-entry is way more portable.

**Comment by taskwarrior** [comment]
_Štěpán Henek on 2012-08-05T20:27:16Z says:_ 

 I played with the task and I managed to insert the encryption/decryption commands into the code. Unfortunately I had some trouble encrypting the undo history and I needed to create an extra class for that.

How is it done:
*Encryption*
1.  the (at)Task@ stuctures are searched for the encrypted field ((at)encryption.fields=description@ from the config)
1.  if the field is present the external (at)encryption.encryptcmd@ is executed
1.  the fields are converted to hex strings ("az09" to "617a3039") and passed to the external command via stdin
1.  the program reads the stdin and encrypts the elements, converts the result to the hex strings and passes them to stdout
1.  the fields are read by the task program and the original strings are replaced by "encrypted-" + result

*Decryption*
1.  the (at)Task@ stuctures are searched for the encrypted field
1.  if the field is present the external (at)encryption.decryptcmd@ is executed
1.  the "encrypted-" part of the strings is removed and the hex strings are passed to the external command via stdin
1.  the program reads the stdin and decrypts the elements, converts the result to the hex strings and passes them to stdout
1.  the fields are read by the task program and the original strings are replaced by the result

So far I managed to make the encryption working using RSA public/private key (without a pass phrase!!!).
To test it place the following lines inside your .taskrc
(at)encryption.decryptcmd=python -path-/rsa.py -d ~/.ssh/key@
(at)encryption.encryptcmd=python -path-/rsa.py -e ~/.ssh/key.pub@
The (at)key@ and (at)key.pub@ should be the files generated by the ssh-keygen without a pass phrase. (Decryption fails if the pass phrase is present!)
And also don't forget to back up your data. This is still a prototype ;-)

My next goal is to encrypt via a password. There are some nice libraries such http://pypi.python.org/pypi/keyring/ which can be used to store the passwords, but I didn't have time to look at it.

**Comment by taskwarrior** [comment]
_Štěpán Henek on 2012-08-05T20:27:16Z says:_ 

 Attachment encryption-4400a6f.patch.txt has been added with description: The patch

**Comment by taskwarrior** [comment]
_Štěpán Henek on 2012-08-05T20:27:16Z says:_ 

 Attachment rsa.py has been added with description: RSA encryption script

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-02-09T16:31:13Z says:_ 

 As this issue resided in the "extensions" project, I never saw it again.  Štěpán, my apologies.  I am relocating this to the taskwarrior project, where it can be properly reviewed and scheduled.

**Comment by taskwarrior** [comment]
_Jakub Wilk on 2014-02-23T18:57:37Z says:_ 

 The encryption script creates temporary file insecurely. (I suppose it's some leftover debugging code...)

As I understand it, the script uses unpadded RSA, which is known to be insecure. Even PyCrypto documentation warns against it:
```
:attention: this function performs the plain, primitive RSA encryption
  (*textbook*). In real applications, you always need to use proper
  cryptographic padding, and you should not directly encrypt data with
  this method. Failure to do so may lead to security vulnerabilities.
  It is recommended to use modules
  `Crypto.Cipher.PKCS1_OAEP` or `Crypto.Cipher.PKCS1_v1_5` instead.
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-09-01T23:59:00Z says:_ 

 I don't think we need this, it isn't secure.

**Comment by taskwarrior** [comment]
_Scott Mcdermott on 2015-09-05T04:22:05Z says:_ 

 (at)pbeckingham: you mean, because it's insecure? or because the patch isn't needed?

hosting a TW instance if one cares about privacy is a non-starter without encrypted data fields.  just securing the transit is not solving the whole problem.  The only place I should be able to see my private data is on the machine in my possession, not a potentially compromised TW server.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-09-05T06:46:14Z says:_ 

 I think Paul means this current implementation is insecure.

I also believe this is a important feature, however, I don't see it as a plugin, it's simply a too deep in a backend. Calling external python scripts to perform the encryption/decryption of the data files seems hackish and error prone.

If this is done, I'd say this should be done properly, in the core. However, I guess that will mean additional dependency. Furthermore, person implementing this will need to be a significant contributor to the project - dropping a patch and then disappearing will not work, this will need to be maintained.

So I don't see this happening, unless somebody's willing to step in and become a regular contributor in the process.

**Comment by pbeckingham** [comment]
[TW-1245_encryption-4400a6f.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756304/TW-1245_encryption-4400a6f.patch.txt)
[TW-1245_rsa.py.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756305/TW-1245_rsa.py.txt)
