### ISSUE TITLE
[TW-1246] GNU readline support for shell

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1281]
_Paul Beckingham on 2009-11-29T09:25:40Z says:_ 

 The task shell would greatly benefit from integrated readline support.  This would provide command line editing, history, searching and completion.

This would need to be an optional feature, thus not adding readline to the list ofdependencies.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-01-23T01:00:08Z says:_ 

 Too big a dependency change considering that we are switching build systems.  I would like to see 1.9.4 simply switch to cmake and drop ncurses, not pick up a new dependency.  Not that this also means readline doesn't need to be added to autoconf, which is a relief.

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-03-09T14:32:04Z says:_ 

 Is anybody working on this feature? If not, I can help with it.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-09T14:39:47Z says:_ 

 > Is anybody working on this feature? If not, I can help with it.

I don't think anyone is working on this.  Just to make things clear, here is what we want:

1) To remove/delete the current "shell" command from taskwarrior.
2) To create an external program/script that functions like the current "shell" command, but as an independent entity is free to follow its own path
3) Requested feature: readline support
4) Requested feature: configurable prompt

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-03-09T14:56:50Z says:_ 

 Got it. You want it to be a separate executable (say tasksh) built using readline, that supports all task commands that "task shell" currently supports (and to get rid of the task shell command). For the configurable prompt part, does this mean configuration options for the prompt text, color, etc.?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-09T15:05:13Z says:_ 

 > Got it. You want it to be a separate executable (say tasksh) built using readline, that supports all task commands that "task shell" currently supports (and to get rid of the task shell command).

Exactly.


> For the configurable prompt part, does this mean configuration options for the prompt text, color, etc.?

Oh, I don't know.  I just recall someone asking for it.  I would imagine someone might want the time, or a task count or something.  If you were to create a shell, then I think you would get a fair number of requests for it, so I would suggest starting small, and seeing what happens.  That would make configurable prompts something you could skip at first.  If there are missing features, people will let you know.

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-03-09T15:14:27Z says:_ 

 Ok, I guess I'll skip the configuration thing for now then. Thanks!

One final question: This should be done in the 2.2.0 git branch, right?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-09T15:33:07Z says:_ 

 > One final question: This should be done in the 2.2.0 git branch, right?

Your thinking is correct, but right now the answer is no.  We're trying to get 2.2.0 out the door, in fact it's in beta right now, so only priority bug fixes are going in to 2.2.0.  This change would go into the 2.3.0 branch.

Note that 2.3.0 does not yet have 2.2.0 merged in (it will on release), and that it contains task server changes, but that shouldn't get in your way at all.

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-03-09T15:36:53Z says:_ 

 Got it. Thanks!

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-03-10T15:43:33Z says:_ 

 Please find attached a patch for this feature (the only difference here from the one I sent by email is that I fixed some style issues).

Thanks,
Haitham

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-03-10T15:43:33Z says:_ 

 Attachment tasksh.patch has been added with description: tasksh patch

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-10T19:20:16Z says:_ 

 Thanks Haitham.

**Comment by taskwarrior** [comment]
_David Patrick on 2013-03-10T23:45:33Z says:_ 

 a working tasksh? that is BRILLIANT! yeah, thanks Haitham!
I understand it's slated for the 2.3 release, but I'm not sure I can wait that long ;-)

Is there a separate code repository? a home-page for the feature? an upcoming News item?

task shell has landed!

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-03-11T01:22:12Z says:_ 

 Thanks Paul & David, Glad to know it's been waited for :)

For the homepage/news, I guess there's nothing of this yet in place, but here's a summary of what's inside the patch:

The patch replaces the 'task shell' command with a new executable 'tasksh'. The new executable is an interactive shell that supports non-persistent history traversal through GNU Readline (this can be enhanced later by saving a history file in ~/.task). The executable also allows for batch processing of task commands. The commands file can be passed as an argument to tasksh or redirected through a unix pipe.

Hope it helps!

Thanks,
Haitham

**Comment by taskwarrior** [comment]
_David Patrick on 2013-03-11T16:11:36Z says:_ 

 Haitham Gad wrote:
> Thanks Paul & David, Glad to know it's been waited for :)

Only for a couple of years.. so you're right on time! ;-)

> The patch replaces the 'task shell' command with a new executable 'tasksh'. The new executable is an interactive shell that supports non-persistent history traversal through GNU Readline.

Yay! now, at least, the "up arrow" will do something!

> The commands file can be passed as an argument to tasksh or redirected through a unix pipe.

And there's brilliant bonus-feature #1! There's no telling what cleverness will come of that! you mean like

 $ tasksh < batch.tasks

or

 $ cat batch.tasks | tasksh

or

 $ tasksh batch.tasks

?

sounds templatelicious.

needs it own repo, and perhaps more importantly, where do I file feature requests? ;-)

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-03-11T16:47:57Z says:_ 

 Yes, all of these forms are supported. It's not a big change. After all, it's just a new interface to a great tool :-)

**Comment by taskwarrior** [comment]
_David Patrick on 2013-03-11T18:48:28Z says:_ 

 Haitham Gad wrote:
> Yes, all of these forms are supported. It's not a big change. After all, it's just a new interface to a great tool :-)

splendid!

Can we "enhance the prompt" ? I'm thinking it would be good to display some config info, like 

 .taskrc - pending.data - task >

where the config variables are one color for the defaults, and another color if !defaults. 
Any other rc.overrides could also be shown here.

**Comment by taskwarrior** [comment]
_David Patrick on 2013-03-11T18:57:41Z says:_ 

 You may have read about some of my more elaborate ideas for the shell, but the one I think will have the most impact on shell usage is a concept I (no doubt incorrectly) call "shell globbing". 

To summarize; a shell keyword "shell" is introduced, and is used to "collect" shell attributes. If the shell input is

 .taskrc - pending.data - task > add proj:foo shell

then the result would be

 .taskrc - pending.data - task add proj:foo >

which could be undone with

 .taskrc - pending.data - task add proj:foo > shell

what do you think of that sort of thing?

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-03-12T11:34:57Z says:_ 

 David Patrick wrote:
> Can we "enhance the prompt" ? I'm thinking it would be good to display some config info, like 
> 
>  .taskrc - pending.data - task >
> 
> where the config variables are one color for the defaults, and another color if !defaults. 
> Any other rc.overrides could also be shown here.

The prompt still reads the "shell.prompt" configuration option. I guess it can be enhanced to allow for this (if it doesn't already).

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-03-12T12:34:33Z says:_ 

 David Patrick wrote:
> You may have read about some of my more elaborate ideas for the shell.

Not really. I came across taskwarrior only last Friday, so you may assume I'm a complete noob :)

> To summarize; a shell keyword "shell" is introduced, and is used to "collect" shell attributes. If the shell input is
> 
>  .taskrc - pending.data - task > add proj:foo shell
> 
> then the result would be
> 
>  .taskrc - pending.data - task add proj:foo >
> 
> which could be undone with
> 
>  .taskrc - pending.data - task add proj:foo > shell
> 
> what do you think of that sort of thing?

Sounds like a cool idea! You want to set the context of subsequent add commands to project foo. But what if at this point, the user wanted to execute something that's not an "add" command (like modify or annotate)? He would have to go out of context to do it, right?

**Comment by taskwarrior** [comment]
_David Patrick on 2013-03-12T16:31:07Z says:_ 

 Haitham Gad wrote:
> David Patrick wrote:
> > You may have read about some of my more elaborate ideas for the shell.
> 
> Not really. I came across taskwarrior only last Friday, so you may assume I'm a complete noob :)

well then, welcome aboard!
> 
> Sounds like a cool idea! You want to set the context of subsequent add commands to project foo. But what if at this point, the user wanted to execute something that's not an "add" command (like modify or annotate)? He would have to go out of context to do it, right?

right! but "de-shelling" should just as easy as 

 .taskrc - pending.data - task add proj:foo > shell

nothing between ">" and "shell" drops the context (which might then be resumed with a couple quick "up arrows")

conversely, anything new between ">" and "shell" would be added to the context, like 

 .taskrc - pending.data - task add proj:foo > +bar shell

makes 

 .taskrc - pending.data - task add proj:foo +bar >

**Comment by taskwarrior** [comment]
_David Patrick on 2013-03-13T00:52:13Z says:_ 

 In thinking some more about the terms ">" and "shell" I realized a couple of things;

">" is no good in a taskwarrior query, unless it's to pipe something out at the end. If used as a "command character" it would have to be "\>" anyways, however, "shell" could be a perfectly usable alias. (more on this later)

"shell" might be somewhat problematic as a twshell "keyword" as you might have a taskto "shell the peanuts" or "shell-out for gas", and it's quite possible that you might want to pipe something out to a file, from tasksh, however, ">EOL" (end of line) should be entirely parseable, so we could use it!

I also looked a bit at the pre-prompt (context) part, and realized that it would be tighter and less confusing to squash it closer together, so, some previous examples above would now look like;

 ~/.taskrc|pending.data|task > add proj:foo >

then the result would be

 ~/.taskrc|pending.data|task add proj:foo >

which could be undone with

 ~/.taskrc|pending.data|task add proj:foo > >

imagine it with colors ;-)

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-13T01:30:19Z says:_ 

 By the way, you folks are discussing new features in a closed issue.  This ought to move to a forum thread, which would then result in issues being created from that discussion.

**Comment by taskwarrior** [comment]
_David Patrick on 2013-03-13T23:49:33Z says:_ 

 Paul Beckingham wrote:
> This ought to move to a forum thread, which would then result in issues being created from that discussion.

and so it shall! how about 
[http://taskwarrior.org/boards/6/topics/2830]
tasksh - the new and much improved task shell
?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-12T20:22:22Z says:_ 

 Reopened.  The tasksh command is not ready for release:  it is not portable and crashes on some systems.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-02-09T16:35:12Z says:_ 

 This was fixed in 2.3.0, but the issue was lurking in the extensions project and not spotted.

**Comment by pbeckingham** [comment]
[TW-1246_tasksh.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756306/TW-1246_tasksh.patch.txt)
