### ISSUE TITLE
[TW-1253] task actions

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1287]
_Peter De Poorter on 2010-11-28T10:37:54Z says:_ 

 Users often want to be able to connect actions to tasks.

The goal is:
*  to create the possibility to connect actions to a task
*  to develop predefined actions that can be used easily by users

More info see attachment. There's still work required to write out a good RFC. The attachment is just a start to launch the idea.

Till now only manual actions were described. One could expand it to automatic actions. This are conditional actions that are triggered by a certain value of a task attribute. For example send a mail when the task is overdue. 

Related discussions:

http://taskwarrior.org/boards/6/topics/show/908
http://taskwarrior.org/boards/6/topics/show/256#message-851

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-11-28T10:37:54Z
Modified: 2014-12-28T01:37:35Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-11-28T11:52:22Z says:_ 

 Let's hash this out in the forums.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-02-09T17:19:22Z says:_ 

 This is all about hooks, I believe.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-12-28T01:37:35Z says:_ 

 This kind of non-core feature is supported by hook scripts, in 2.4.0.

**Comment by pbeckingham** [comment]
[TW-1253_rfcxx-action.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756307/TW-1253_rfcxx-action.txt)
