### ISSUE TITLE
[TW-1254] Calc command can segfault on negative numbers

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1288]
_Paul Beckingham on 2014-02-09T19:19:02Z says:_ 

 This command segfaults:

    task calc 0*-1

This does not:

    task calc 0*1

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-02-09T19:19:02Z
Modified: 2014-04-06T04:33:50Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-03-06T21:41:11Z says:_ 

 Nice test.  Thank you.  Applied and pushed.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-04-06T04:33:50Z says:_ 

 The problem was that the expressions were simply lexed and evaluated, not lexed, parsed and evaluated.  The parsing step was not optional, as it has been in past versions of taskwarrior.

Now the unary minus is properly parsed and converted internally to '_neg_' to distinguish it from the arithmetic minus.

The parser can now be enhanced to spot syntax errors in expressions, but this has happened not yet.

**Comment by pbeckingham** [comment]
[TW-1254_bug.1254.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756308/TW-1254_bug.1254.t.txt)
