### ISSUE TITLE
[TW-1255] New testing framework

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1289]
_Renato Alves on 2014-02-09T23:44:57Z says:_ 

 Initial proposal for new testing framework.

The python TAP module was rewritten from scratch by me (simpletap).
Licensing is the same as Taskwarrior.

The attached patch provides "simpletap" module and "version.py" which includes the same as "version.t" and 3 more test cases to serve as example.

The "version.py" file was not renamed to "version.t" to avoid replacing the existing file until the patch is accepted.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-02-09T23:44:57Z
Modified: 2014-03-07T02:17:49Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-02-20T05:05:44Z says:_ 

 Reopening to assign fix version.

**Comment by pbeckingham** [comment]
[TW-1255_0001-Initial-unittest-skeleton-using-python-and-TAP.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756309/TW-1255_0001-Initial-unittest-skeleton-using-python-and-TAP.patch.txt)
