### ISSUE TITLE
[TW-1258] Portuguese Localization

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1292]
_Renato Alves on 2014-02-14T21:43:20Z says:_ 

 Portuguese localization for 2.4.0

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-02-14T21:43:20Z
Modified: 2014-02-15T03:55:09Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-02-15T03:55:09Z says:_ 

 Thank you.

**Comment by pbeckingham** [comment]
[TW-1258_0001-Portuguese-por-PRT-localization.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756310/TW-1258_0001-Portuguese-por-PRT-localization.patch.txt)
