### ISSUE TITLE
[TW-1261] Migrate test bug.360 to new unit testing framework

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1295]
_Renato Alves on 2014-02-17T01:57:38Z says:_ 

 Includes a BaseTestCase (in tests/basetest module) which if used automatically creates a temporary folder (currently in /tmp), ensures TASKRC and TASKDATA are unset and symlinks task from src/task.

BaseTestCase also provides "callTask", "callTaskError" and "callTaskSuccess", all of which invoke task (in /tmp/tmpfolder/task). The Error/Success variants also explicitly check the exit code and cause test to fail if result is not the expected.

TODOs present in original bug.360.t were transfered unchanged since I don't know the features they refer to.

A few NOTEs and TODOs were added to bug.360.t in locations where transference to the new unittesting framework was unclear or where I had doubts.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-02-17T01:57:38Z
Modified: 2014-02-20T04:37:29Z
```

**Comment by pbeckingham** [comment]
[TW-1261_0001-Unit-tests-Keep-a-template-as-example-for-the-new-un.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755606/TW-1261_0001-Unit-tests-Keep-a-template-as-example-for-the-new-un.patch.txt)
[TW-1261_0002-Unit-tests-Replace-old-version.t-with-the-new-python.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755607/TW-1261_0002-Unit-tests-Replace-old-version.t-with-the-new-python.patch.txt)
[TW-1261_0003-Unit-tests-Add-a-BaseTestCase-which-prepares-and-iso.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755608/TW-1261_0003-Unit-tests-Add-a-BaseTestCase-which-prepares-and-iso.patch.txt)
[TW-1261_0004-Unit-tests-version.t-now-uses-BaseTestCase.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755609/TW-1261_0004-Unit-tests-version.t-now-uses-BaseTestCase.patch.txt)
[TW-1261_0005-Unit-tests-Migrated-bug.360-to-python.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755610/TW-1261_0005-Unit-tests-Migrated-bug.360-to-python.patch.txt)
