### ISSUE TITLE
[TW-1263] Command Reference Redesign

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1297]
_Benjamin Weber on 2014-02-20T12:21:25Z says:_ 

 The command reference is the tool kit template from every-day-users to Greenhorns. It is key to understand Taskwarrior's (1) functions, (2) terminology and (3) grammar as well its limitations.

Why is it necessary?
 * To fulfil the balancing act between complexity of Taskwarrior and simplicity of use.
 * Increasing the user's time required to attain the desired level of prowess.
 * Summary of documentation: To compress the Documentation information on a single sheet of paper.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-02-20T12:21:25Z
Modified: 2014-05-26T20:21:39Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-04-12T17:48:16Z says:_ 

 Any recent progress?

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2014-04-13T19:34:34Z says:_ 

 5a9964fb6b7d29997a7e37a6d134a87c44b0822d

Second iteration of the above draft.

Feedback wished.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-04-14T23:33:38Z says:_ 

 Okay, let's stop this.  I can't use that - I don't understand it, and it doesn't make sense.  Let's not expend any more time on this.

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2014-04-15T09:48:05Z says:_ 

 Yes, you can't use it. Have I said so?
If you want to judge the path to a solution with the criteria of a solution, do it.
If you say you can't use it, it does not make sense: it is my very recent understanding of task. It's easy to say that it's this trial which is to blame. But it's harder to think not the reflection is to blame but the object itself. What is the object the command reference reflects?
I must not blame the object! No one must do that! No one will, most probably, do.
(I am not saying task is bad.) Remember, I've not touched task's code even once.

You have asked me for recent progress. I've uploaded the current state. I have not said anyone (including me) could use it.
No one is more dissatisfied with the state than me. Feel free to dump it.
I don't want to block any rapid (and probably better) approaches.
If you feel that I have slowed progress in this point, I deeply apologise this.

If you want to understand this step (≠ solution), this may help your understanding a bit:
It tries to depict the life of a task from 9 to 1.30 o'clock by linking it to the relevant attribute (second outer belt; like the water=tasks flow over a water wheel). The attribute (second inner belt) is linked to the value type (inner circle) via the black bridge which distinguishes whether the combination is a former <filter> (read) (now: selector) or a <modification> (write) over the type of operator (":" or "+ - ~ !~ etc.") 
STATUS (outer belt) -> COMMAND -> ATTRIBUTE -> OP (black bridge) -> VALUE TYPE (inner belt)

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-05-10T15:46:41Z says:_ 

 Now shows syntax, and groups information according to syntax.  Less text on the page.

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2014-05-21T18:56:45Z says:_ 

 The drawing of a child.

<filter presets> are former <reports>.
<filter presets>, <virtual tags> should disappear in favour of bumped up _status_ column, coined "Regular Expression based Virtual Tags
" TW-1268.
The user can define a status as per hers wishes.
<virtual tags> are automatic representations of the +STATUS, -STATUS.

This eliminates redundancies and simplifies the usability.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-05-21T21:26:11Z says:_ 

 You've seen this I trust: http://taskwarrior.org/news/news.20140510.html

**Comment by pbeckingham** [comment]
[TW-1263_2014-05-18-FLOW-hf.pdf.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756313/TW-1263_2014-05-18-FLOW-hf.pdf.txt)
[TW-1263_tw_cmd_ref.pdf.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756314/TW-1263_tw_cmd_ref.pdf.txt)
[TW-1263_tw_iris.pdf.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756315/TW-1263_tw_iris.pdf.txt)
