### ISSUE TITLE
[EX-9] twcron

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#13]
_David Patrick on 2012-09-01T00:57:57Z says:_ 

 This is an iteration of taskwarrior that interfaces with the cron sub-system of a *nix computer. 

From Wikipedia (http://en.wikipedia.org/wiki/Cron) _cron is the time-based job scheduler in Unix-like computer operating systems. cron enables users to schedule jobs (commands or shell scripts) to run periodically at certain times or dates._

there is actually surprising crossover between a task, and a cron event, although cron uses far fewer fields. 
Interfacing with cron events, the crontab file, and understanding what's going to happen when, is an interesting exercise requiring precise syntax and this feature seeks to make managing cron events as easy as using taskwarrior.

twcron would use cron-related system files as data files, would present cron, anacron, at and batch jobs as tasks, with the ability to perform complex queries, create custom reports and make modifications to cron events, just like taskwarrior tasks, but with a limited set of parameters, and within the constraints of those events.

Having twcron interface the cron sub-system would make it easier to understand and control *nix system events, and it introduces the possibility of "regular" taskwarrior triggering or being triggered by system events.

A most interesting question would be: how might this interface with *libtaskd* ?
http://tasktools.org/projects/taskd.html

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-09-01T00:57:57Z
Modified: 2014-02-09T02:43:22Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2012-09-01T02:24:21Z says:_ 

 twcron could be used to schedule taskwarrior push/pull/merge actions
and/ or bugwarrior actions (http://taskwarrior.org/projects/taskwarrior/wiki/ExternalScripts#bugwarrior)
and stuff like that, and might be useful with task notifications, as in http://taskwarrior.org/projects/taskwarrior/wiki/ExternalScripts#taskwarrior-notifications.

**Comment by pbeckingham** [comment]
Unclear.  No plans to implement.
