### ISSUE TITLE
[TW-1266] Redis support

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1300]
_Benjamin Weber on 2014-02-20T15:34:53Z says:_ 

 This is a renegate idea: Feel free to kill me!

_Let's change the storage._

* Task stores its data in a local redis setup. Alice has task and does not share anything.
* Alice decides to set up another task at work to sync with hers at home.
* Next she wants to use task on her smartphone, too.
* Bob has a local task setup. Bob decides to share a task with Alice.
* Bob connects to a taskd cluster, asks Alice to join.
* Taskd cluster's sole job is to keep Alice and Bob in sync.
* As the sync capacity needs to grow, nodes are added to the cluster.
* If one node fails, another node fulfils the sync role.

Example (replay it at http://try.redis.io):
```
1.  enter task
HMSET fff64fe2-8e2a-4edc-a2f0-54dd904afc02 id "1" description "Clean car including footmats" scheduled "2014-02-28" due "2014-03-07" tags "car clean sun"
1.  get due date
hget fff64fe2-8e2a-4edc-a2f0-54dd904afc02 due
"2014-03-07"
1.  set due date to 2014-03-03
hset fff64fe2-8e2a-4edc-a2f0-54dd904afc02 due "2014-03-03"
1.  confirm if due date is still correct
hget fff64fe2-8e2a-4edc-a2f0-54dd904afc02 due
"2014-03-07"
1.  get complete task
hgetall fff64fe2-8e2a-4edc-a2f0-54dd904afc02
1) "description"
2) "Clean car including footmats"
3) "due"
4) "2014-03-03"
5) "id"
6) "1"
7) "scheduled"
8) "2014-02-28"
9) "tags"
10) "car clean sun"
1.  get tags
hget fff64fe2-8e2a-4edc-a2f0-54dd904afc02 tags
"car clean sun"
```

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-02-20T15:34:53Z
Modified: 2014-03-04T21:10:19Z
```

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2014-02-20T15:37:05Z says:_ 

 b0bbb9056b6f807b5f42c75eeef2cc070fab1f00 Add user/node concept, add multiple cli
9997c366b63444d3a907f5427bed6e2ce1160a80 Add redis example text
9c8cb11e80eae8fe62a8cc10ba03a0863623d69b Add redis-db idea

**Comment by pbeckingham** [comment]
[TW-1266_redis-db.pdf.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756316/TW-1266_redis-db.pdf.txt)
