### ISSUE TITLE
[TW-1267] If default.project is defined it's not possible to add a task without a project

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1301]
_Renato Alves on 2014-02-20T15:47:36Z says:_ 

 As the summary describes if default.project is defined to anything other than the default, there is no way to add a task without a project.
The only way to workaround this is by creating a task and then modify the task and remove the project.

Reproducible with attached file.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-02-20T15:47:36Z
Modified: 2014-07-03T21:40:59Z
```

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-02-20T16:22:21Z says:_ 

 Tests added

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-02-21T05:55:59Z says:_ 

 Good catch, good test.

I'm not going to commit the new test yet, because doing so implies that this bug will be fixed in 2.4.0, because then we will be trying to release with broken tests.  It forces our hand.  If/when this is scheduled, the test will be committed.

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-02-21T14:05:44Z says:_ 

 No pressure. I merely added the test to make it easier to reproduce and develop a fix.
I also added a "hasTest" label which I've been using to filter issues that lack tests.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-05-24T15:08:58Z says:_ 

 Unit test added to 2.4.0.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-07-03T21:40:59Z says:_ 

 Complicated bug.  Default attributes, such as project, are applied when a task is validated, right before it is written to the database.  They are added if the attribute is blank.

The solution is multi-part:

[1] Never write a blank attribute value to the database
[2] If the command line contains "project:" then set a blank attribute on the task being added
[3] Make validation aware that an extant, but trivial value means no default should be applied

**Comment by pbeckingham** [comment]
[TW-1267_bug.1267.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756317/TW-1267_bug.1267.t.txt)
