### ISSUE TITLE
[TW-1278] Next report filters tasks with due date set until due date arrives

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1312]
_Renato Alves on 2014-03-01T15:15:39Z says:_ 

 Tasks that have a due date will not be displayed with the new "next" report unless the task is overdue.

This can be tested with:

task add due:tomorrow Tomorrow I'll know
task add due:today Don't forget today
task next

This will only display "Don't forget today".

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-03-01T15:15:39Z
Modified: 2014-04-16T03:21:43Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-03-07T03:49:00Z says:_ 

 This is because the next report has a filter of ```-DUE``` So while this is functioning correctly, the filter is clearly not right and needs modification.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-04-16T03:21:43Z says:_ 

 Filter restored, -DUE removed.  The next report is all about urgency, not filters.

**Comment by pbeckingham** [comment]
[TW-1278_bug.1278.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756318/TW-1278_bug.1278.t.txt)
