### ISSUE TITLE
[TW-1279] Recurring tasks acquire default attributes specified on the task "client" they are generated in

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1313]
_Renato Alves on 2014-03-01T15:36:34Z says:_ 

 This still requires further testing for confirmation.

I'm currently using the same task database in two machines and synced to the same taskd server.

One of the clients has _default.project_ set.

If a recurrent task is created on the client that *doesn't have* _default.project_ set. No project is assigned. So far so good.
Now if one of the recurrences is generated in the client that *has* _default.project_, that task will become part of that project.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-03-01T15:36:34Z
Modified: 2015-04-02T18:52:02Z
```

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-07-30T16:56:53Z says:_ 

 Two tests included. One requires "faketime", skipped if faketime is not available.

**Comment by taskwarrior** [comment]
_Renato Alves on 2015-03-03T01:23:35Z says:_ 

 Attachment is obsolete, testcases have been merged with feature.default.project.t

**Comment by pbeckingham** [comment]
[TW-1279_tw-1279.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756319/TW-1279_tw-1279.t.txt)
