### ISSUE TITLE
[TW-1287] default.project gets applied on a projectless task on sync

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1321]
_Renato Alves on 2014-03-10T06:49:18Z says:_ 

 I still need to reproduce this consistently but it just happened to me in two different clients.

The steps were approximately the following:
```
(client A) task rc.default.project: add Testing
(client A) task rc.default.project: sync
(client B) task rc.default.project:MeClientB sync
(client C) task rc.default.project:MeClientC sync
(client A) task 1 info
(client B) task 1 info (should include proj:MeClientB)
(client C) task 1 info (should include proj:MeClientC)
```
*NOTE*: in my case I had a different default.project set in the rc file of each client B and C and no default.project set in client A.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-03-10T06:49:18Z
Modified: 2015-04-02T18:54:37Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-04-16T03:25:31Z says:_ 

 This is not what we want.  Thanks.

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-07-30T16:45:29Z says:_ 

 Testcase attached. Not committed yet as it requires taskd setup and certificate updates (or workaround using "taskd.trust=ignore hostname" on clients).

**Comment by taskwarrior** [comment]
_Renato Alves on 2015-03-03T01:24:16Z says:_ 

 Attachment is obsolete, testcases have been merged with feature.default.project.t

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-04-02T18:54:37Z says:_ 

 Defaults are now no longer applied to tasks added by syncing.

**Comment by pbeckingham** [comment]
[TW-1287_tw-1287.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756320/TW-1287_tw-1287.t.txt)
