### ISSUE TITLE
[TW-1296] make test/run_all exit with non-zero code if a test fail

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1329]
_Jakub Wilk on 2014-04-01T20:44:24Z says:_ 

 Here's a patch to make the test runner exit with non-zero code if any of the tests fail. I also had to patch `test/test.cpp`, so that failing tests written in C have non-zero exit code, just like the Perl ones.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-04-01T20:44:24Z
Modified: 2014-04-05T14:40:29Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-04-05T14:40:29Z says:_ 

 Thank Jakub, great idea.  I will propagate this to other projects.

**Comment by pbeckingham** [comment]
[TW-1296_test-run_all-fail.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756323/TW-1296_test-run_all-fail.diff.txt)
