### ISSUE TITLE
[TW-1304] Minor build and install fix for NetBSD

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1337]
_atomicules on 2014-04-15T11:26:52Z says:_ 

 1. On NetBSD, `src/Directory.cpp` needs to reference `limits.h` in order to build.
2. On NetBSD, since `libreadline`, `libuuid` and `libncurses` are likely to be in `/usr/pkg/lib` and not a system library path, CMake's `make install` will remove the links meaning the installed executable won't launch (even though the one in `src/` will). Using CMAKE_INSTALL_RPATH_USE_LINK_PATH fixes this problem.

See attached patch against 00204e01912aeb9e39b94ac7ba16562fdd5b5f2c. I expanded the `ifdef` in `src/Directory.cpp` that included `limits.h` for Solaris to also include it for NetBSD. I added a conditional to `CMakeLists.txt` to set `CMAKE_INSTALL_RPATH_USE_LINK_PATH` for NetBSD.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-04-15T11:26:52Z
Modified: 2014-04-16T01:07:03Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-04-16T01:07:03Z says:_ 

 Thank you!  Your patch is much appreciated.  I was able to apply this patch to both Taskwarrior and Taskserver, and you are in the AUTHORS file of both, as thanks.

**Comment by pbeckingham** [comment]
[TW-1304_netbsd_build_install.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756330/TW-1304_netbsd_build_install.diff.txt)
