### ISSUE TITLE
[TW-1314] recurring tasks - repeat "after completion"

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1346]
_Alan Porter on 2014-05-03T14:48:11Z says:_ 

 Recurring tasks will repeat periodically.  Pay the gas bill every month on the 5th.  But some tasks recur after completion of the last task.  Two good examples: hair cuts and mowing the grass (very similar tasks, actually).

It should be possible to schedule the next hair cut six weeks after the current hair cut is actually completed (not six weeks from when it was scheduled to be due).

Under the current scheme, I have to mow my grass every 14 days.  If I get slack or it rains or I am on vacation or otherwise delayed, I finally get around to it a week late.  The next grass-mowing task will be scheduled 14 days from the last due date, or 7 days from when I last mowed the grass.

RememberTheMilk has pretty good support for this sort of recurring task.  They could be used as an example.  I imagine the grammar for this sort of task would be recurAfter:14days or recur:after14days or recur:+14days.  I dunno.

Thanks for an awesome tool!

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-05-03T14:48:11Z
Modified: 2015-10-19T04:48:14Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-05-05T03:41:55Z says:_ 

 Thank you.  We will be reworking recurrence support soon, and this will be included.

**Comment by taskwarrior** [comment]
_neingeist on 2014-09-02T19:46:52Z says:_ 

 I found this issue important enough to come up with this workaround:

https://github.com/neingeist/task-recurring-delete

**Comment by taskwarrior** [comment]
_Jens Erat on 2014-12-13T22:44:09Z says:_ 

 I wrote a small hook hack for dealing with this, available on GitHub. Not as beautiful as native support for relative recurrance, but it works.

https://github.com/JensErat/task-relative-recur

This feature request is actually reported at least three times, with TW-150 not linked yet:

https://bug.tasktools.org/browse/TW-150
https://bug.tasktools.org/browse/TW-235
https://bug.tasktools.org/browse/TW-1314

**Comment by OptimisticLock** [comment]
Bump. This feature hasn't been implemented yet, has it? For a todoist refugee like me, it's important.

**Comment by djmitche** [comment]
I think there was an effort to build a new recurrence framework a few years ago, but to my knowledge it's currently stalled.

**Comment by OptimisticLock** [comment]
I've heard of an effort, but I can't seem to find it. If it's in Rust, I'll be happy to contribute.

**Comment by djmitche** [comment]
It's not in Rust. What I know of the effort is in https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/doc/devel/rfcs/recurrence.md. I think this corresponds to Paul's comment above, in 2014.

If you would like to participate, this might be a good time to begin the redesign process. It would be great to define this within the context of Taskchampion, and in a way that is compatible with the TC sync model. Specifically, it would be ideal if users did not have to select one replica as the one to create the recurring tasks, with the risk of duplication if the users get that wrong. There were some vague notes in https://github.com/taskchampion/taskchampion/issues/81 and the linked issue.
