### ISSUE TITLE
[TW-1320] Provide output of malformed row if invalid Taskwarrior file format

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1352]
_Kosta Harlan on 2014-05-10T21:33:12Z says:_ 

 Many times I've encountered the dreaded "Unrecognized taskwarrior file format" error. While Taskwarrior will provide some information about why the row is malformed when encountering old TW database versions, it doesn't show any info if, for example, a task entry has extra commas thrown in.

With this patch, Taskwarrior will show the malformed row if `rc.debug=1` is passed.

This patch was invaluable to me in understanding why `task sync` was failing in some instances.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-05-10T21:33:12Z
Modified: 2014-05-12T16:25:23Z
```

**Comment by taskwarrior** [comment]
_Kosta Harlan on 2014-05-10T21:34:42Z says:_ 

 For example, this patch is very useful in tracking down problem rows for this type of bug https://bug.tasktools.org/browse/TW-380

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-05-11T14:19:14Z says:_ 

 Patch was applied 2014-04-22, but I don't remember where it came from.  But it matches this one.  Thanks!

**Comment by taskwarrior** [comment]
_Kosta Harlan on 2014-05-12T16:25:23Z says:_ 

 Thanks Paul, I had uploaded the patch to issue https://bug.tasktools.org/browse/TW-253 but without much context, so I created this new issue. Feel free to close out #253.

**Comment by pbeckingham** [comment]
[TW-1320_unrecognized-file-format-debug.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756331/TW-1320_unrecognized-file-format-debug.patch.txt)
