### ISSUE TITLE
[TW-1346] color.label erros

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1376]
_David Patrick on 2014-06-21T19:52:28Z says:_ 

 In applying color to the report labels, using .taskrc-setting color.label=, the space-characters miss out on the background color. Have a look at the attached screenshot, to see what I mean. My guess is that the underline directive of the label-line might have something to do with it.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-06-21T19:52:28Z
Modified: 2014-06-25T01:30:20Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-06-25T01:30:20Z says:_ 

 That's not a bug, that's deliberate.  There's no reason to have a continuous color stripe.

**Comment by pbeckingham** [comment]
![tw-1346_tw_label-error_screenshot](https://user-images.githubusercontent.com/7963/36643461-a67bac0a-1a19-11e8-9504-84b93530d45c.png)
