### ISSUE TITLE
[TW-1351] "on bright" not so bright

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1381]
_David Patrick on 2014-06-23T01:51:53Z says:_ 

 You can see what I'm talking about in the screenshot below. It is from a calendar-report, using a new 16-color theme. The undesired effect can be see on the dates Jun 15, 21, 22 and Jul 5 and 20. All of these are weekends, and the related weekend color directive (in this case) is

color.calendar.weekend=on bright black (there aren't a lot of options)

The problem arises when the other "on colorx" directive, like due, due.today and overdue, are affected with the "on bright" part of the weekend "on bright black". 

Looks like we have a color-leak!

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-06-23T01:51:53Z
Modified: 2014-12-28T04:02:15Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2014-06-23T01:54:48Z says:_ 

 the related calendar settings in this case are:

color.calendar.holiday=bold yellow
color.calendar.today=bold white
color.calendar.due.today=on yellow
color.calendar.due=on green
color.calendar.overdue=on red
color.calendar.weekend=on bright black
color.calendar.weeknumber=bold black

the worst offender here is Jun22 (today) where the weekend "on bright black" has turned the due.today color from "on yellow" to "on bright yellow", which doesn't work.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-11-29T22:33:11Z says:_ 

 This is a side-effect of the fact that Taskwarrior blends colors.  Therefore, any "bright" attribute remains after blending.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-12-28T04:02:15Z says:_ 

 Not a bug, just an expected side-effect of blending.

**Comment by pbeckingham** [comment]
![tw-1351_tw-theme_too-bold_screenshot-4](https://user-images.githubusercontent.com/7963/36643462-b08817c4-1a19-11e8-9ba3-24e96569d73e.png)
