### ISSUE TITLE
[TW-1354] urgency.uda.<name>.<value>.coefficient=

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1382]
_David Patrick on 2014-06-24T04:57:03Z says:_ 

 There is an rc-setting that allows users to set an urgency coefficient, based on the presence or absence of given uda data. In other words, if there a task  _any_ value of a certain uda, then the coefficient applies. This could be handy, and it could be improved.

As a use-case, I have a uda, "area:", that I use to assign Area of Responsibility to each task. I use areas like "family, self, admin, it, friend, work, community" sort of thing, and it really helps to break tasks into logical groups. This sort of thing would be _ideal_ as a driver of urgency, _if_ it were possible to assign an urgency coefficient to a specified value of a specified uda. 

maybe the current setting:
`urgency.uda.<name>.coefficient=`
could be extended with a value, like:
`urgency.uda.<name>.<value>.coefficient=`
leaving the current behavior, presence or absence coefficient, but allowing correlation of urgency with area-of-responsibility, for example.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-06-24T04:57:03Z
Modified: 2014-10-10T20:29:10Z
```

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2014-10-10T12:49:28Z says:_ 

 Hi djp,
nice idea (had the same actually ;)).

I attached a patch for this.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-10-10T20:29:10Z says:_ 

 Nice work Johannes, thank you.

**Comment by pbeckingham** [comment]
[TW-1354_0001-Urgency.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756336/TW-1354_0001-Urgency.patch.txt)
