### ISSUE TITLE
[TW-1364] sod, sowd, eowd, eod date (time) specifiers

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1392]
_David Patrick on 2014-07-01T23:12:10Z says:_ 

 Start-of-day, start-of-work-day, end-of-work-day, end-of-day specifiers would be very handy in specifying date/time more accurately, This follows on the heels of soy, som, sow, soww. Because different users keep different hours, having these date/time-specifiers user-definable would be ideal, but sane defaults of 7am, 9am, 5pm and 9pm (respectively) would be a good starting point.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-07-01T23:12:10Z
Modified: 2017-10-12T16:40:48Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2014-07-01T23:27:23Z says:_ 

 After defining these 4 specified times-of-day, there are four periods in between that could be corresponding named-periods; morning, day, evening and night.

**Comment by taskwarrior** [comment]
_David Patrick on 2014-07-01T23:45:29Z says:_ 

 Defining start-of-work-day and end-of-work-day also defines the two conditions "work hours" and "not work hours", Monday through Friday. This could be used (for example) for things like an "automatic-context-switcher" for work-related and not-work-related tasks, for those who don't bring work home.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-08-06T02:30:23Z says:_ 

 I'm closing all issues that request expanded date/time formats.  With ISO-8601 support, I don't think we need these.

**Comment by fuzzyweapon** [comment]
It'd be nice to still have this suggestion implemented, or at least allow users to create user aliases for time (which would put all future time issues to bed most likely).

People don't think in ISO-8601 formats for deadlines, and setting things to the end of the workday (most often what I want) or personal day (time of day I start getting ready for bed) are the most important times as eowd is most often used in workplaces.  Using ISO format is great if you need something to be very specific, but it doesn't grok and isn't efficient for putting in lots of tasks (which as a person with a chronic cognitive deficiency in memory and attention, I can tell you, there are users that use tw for more, not less tasks, out of necessity even if it's expected and recommended that users don't).
