### ISSUE TITLE
[TW-1373] taskrc.vim VIM syntax file updated

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1401]
_lolilolicon on 2014-07-11T01:06:16Z says:_ 

 taskrc.vim syntax file does not cover all the config keys. (e.g. regex, verbose, etc.) Let's fix that.
This also highlights the include keyword.
Based on John Florian's original taskrc.vim. keywords are generated from `task _config` plus some others mentioned in the man page.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-07-11T01:06:16Z
Modified: 2014-07-11T02:57:30Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-07-11T01:26:48Z says:_ 

 That's nice work, but the license should not have been removed.  This is an extensive rewrite, so the copyright removal is correct, but submitting under the MiT License is the only way I can accept it.

Can you confirm that, or re-upload?

**Comment by taskwarrior** [comment]
_lolilolicon on 2014-07-11T02:12:39Z says:_ 

 Updated with copyright statement. Is this OK?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-07-11T02:18:45Z says:_ 

 Ideal.  Thank you.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-07-11T02:57:30Z says:_ 

 Nice work!

**Comment by pbeckingham** [comment]
[TW-1373_taskrc.vim.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756337/TW-1373_taskrc.vim.txt)
