### ISSUE TITLE
[TW-1374] More taskrc.vim VIM syntax file updates

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1402]
_lolilolicon on 2014-07-11T08:22:53Z says:_ 

 This time for 2.4.0. Attached is a patch you can apply with `git am`.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-07-11T08:22:53Z
Modified: 2014-07-12T05:32:34Z
```

**Comment by taskwarrior** [comment]
_lolilolicon on 2014-07-11T11:54:14Z says:_ 

 Another 2 VIM file patches added.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-07-12T00:20:07Z says:_ 

 Patches applied and pushed.  No need to open a ticket to submit a patch - just email support(at)taskwarrior.org

**Comment by taskwarrior** [comment]
_lolilolicon on 2014-07-12T05:32:34Z says:_ 

 Oops, I didn't know patches are supposed to be sent to support(at)taskwarrior.org
This page ( http://taskwarrior.org/support/ ) says this is for help (as it sounds, "support"); maybe it should be updated?

**Comment by pbeckingham** [comment]
[TW-1374_0001-Update-taskrc-VIM-syntax-file-for-2.4.0.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756339/TW-1374_0001-Update-taskrc-VIM-syntax-file-for-2.4.0.patch.txt)
[TW-1374_0002-Update-taskedit.vim-for-multiline-values.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756340/TW-1374_0002-Update-taskedit.vim-for-multiline-values.patch.txt)
[TW-1374_0003-taskdata.vim-fixes-ftdetect-backlog.data-as-JSON.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756341/TW-1374_0003-taskdata.vim-fixes-ftdetect-backlog.data-as-JSON.patch.txt)
