### ISSUE TITLE
[TW-1377] Tags in default.command are treated as "operator text"

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1405]
_Renato Alves on 2014-07-15T01:46:08Z says:_ 

 If a user has tags in their default.command parameter, the parser will treat them as "- TAG" instead of "-TAG".

This only seems to affect settings in the rc file. Passing them in the command line doesn't generate errors.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-07-15T01:46:08Z
Modified: 2014-08-16T20:35:15Z
```

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-07-15T01:47:53Z says:_ 

 Test for described problem.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-08-16T20:35:15Z says:_ 

 This was caused by lexing the default.command value, which knows about expressions and not command line arguments.  A simple split on spaces works better.

Ultimately this may need to be upgraded to a proper quote- and escape-aware split.  But not yet.

**Comment by pbeckingham** [comment]
[TW-1377_tw-1377.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756342/TW-1377_tw-1377.t.txt)
