### ISSUE TITLE
[TW-1381] blocking report exits with "Unknown error" and exit code 3

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1409]
_Renato Alves on 2014-07-24T12:55:05Z says:_ 

 Running `task blocking` with some blocked tasks results in "Unknown error".

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-07-24T12:55:05Z
Modified: 2014-08-16T20:10:37Z
```

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-07-24T12:59:10Z says:_ 

 Testcase attached

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-08-16T20:10:37Z says:_ 

 Caused by an attempt at extracting a substring from a missing parent UUID - bounds violation.

Tests already added.

**Comment by pbeckingham** [comment]
[TW-1381_tw-1381.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756343/TW-1381_tw-1381.t.txt)
