### ISSUE TITLE
[TW-1383] Segmentation fault running import-yaml.pl with included example

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1411]
_Markus Beppler on 2014-07-26T09:25:21Z says:_ 

 The latest version of import-yaml.pl is producing old JSON format. E.g. the _tags entry_ is a _string_ and not an _array_. Importing this will crash tw.

```
echo '{"description":"chrash","tags":"a"}' > /tmp/task.json
task import /tmp/task.json
    Importing '/tmp/task.json'
    Segmentation fault
```

back trace

```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: 13 at address: 0x0000000000000000
0x00007fff86905162 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string ()
1. 0  0x00007fff86905162 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string ()
1. 1  0x0000000100004465 in __gnu_cxx::new_allocator<std::string>::construct (this=0x7fff5fbfe9f0, __p=0x1007328d0, __val=@0x2000c0d0a0069) at new_allocator.h:107
1. 2  0x00000001000049c2 in std::vector<std::string, std::allocator<std::string> >::_M_insert_aux (this=0x7fff5fbfe9f0, __position={_M_current = 0x0}, __x=@0x2000c0d0a0069) at vector.tcc:279
1. 3  0x0000000100004bf4 in std::vector<std::string, std::allocator<std::string> >::push_back (this=0x7fff5fbfe9f0, __x=@0x2000c0d0a0069) at stl_vector.h:608
1. 4  0x000000010005feb5 in Task::addTag (this=0x7fff5fbff150, tag=@0x2000c0d0a0069) at /Users/markus/git/task/src/Task.cpp:1122
1. 5  0x0000000100065677 in Task::parseJSON (this=0x7fff5fbff150, line=@0x7fff5fbff030) at /Users/markus/git/task/src/Task.cpp:570
1. 6  0x0000000100066ba0 in Task::parse (this=0x7fff5fbff150, input=@0x7fff5fbff2e0) at /Users/markus/git/task/src/Task.cpp:512
1. 7  0x0000000100066d6f in Task::Task (this=0x7fff5fbff150, input=@0x7fff5fbff2e0) at /Users/markus/git/task/src/Task.cpp:146
1. 8  0x00000001000f2388 in CmdImport::execute (this=0x1007245b0, output=@0x7fff5fbff7b0) at /Users/markus/git/task/src/commands/CmdImport.cpp:102
1. 9  0x000000010002467a in Context::dispatch (this=0x1001d3900, out=@0x7fff5fbff7b0) at /Users/markus/git/task/src/Context.cpp:383
1. 10 0x000000010002486a in Context::run (this=0x1001d3900) at /Users/markus/git/task/src/Context.cpp:259
1. 11 0x0000000100008c7e in main (argc=3, argv=0x7fff5fbff850) at /Users/markus/git/task/src/main.cpp:51
```

Attached is a patch for import-yaml.pl
*  tags are array of strings
*  annotations inside task object
*  annotations are objects with entry and description item
*  annotations use new date format (use YAML input as task entry)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-07-26T09:25:21Z
Modified: 2014-07-28T04:24:14Z
```

**Comment by taskwarrior** [comment]
_Markus Beppler on 2014-07-26T14:33:26Z says:_ 

 Attached test cases. Hope these are useful.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-07-26T14:36:07Z says:_ 

 That's great, thank you very much.  Testing now.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-07-26T15:16:24Z says:_ 

 There are three problems with the patches:

[1] I cannot replicate the crash on the 2.4.0 dev branch.
[2] The patches do not cleanly apply on the 2.4.0 dev branch.
[3] The coding style in the Perl differs from the surrounding code - needs to blend in.

I suspect you either wrote the patches based on the source tarball (which we never change) or the 'master' branch in the code repository (which we never change), and not the '2.4.0' branch, which is currently about 800 commits ahead of 2.3.0, which is why the patches don't apply.

**Comment by taskwarrior** [comment]
_Markus Beppler on 2014-07-27T10:33:44Z says:_ 

 Could not compile 2.4 in OS X. This is my problem. POSIX getline is not part of my old OS version. Still, I (believed) was using the actual GNU environment.

Switched to a linux machine and redid the test.
*  *2.3.0* : crash as described in bug report
*  *2.4.0* : like you, no crash (task was imported)

Attached the patches for 2.4.0 branch (in a hopefully better _blend_).

*import-yaml.pl.patch.2.4.0*
as described in bug report

*import.t.patch.2.4.0*
Not needed, as _array free tags_ are imported without a problem in 2.4.0.
Unless it is not supposed to be supported. 

*import.yaml.t.patch.2.4.0*
* added annotations and tags to default input data
* updated comment of task complete output to match UUID input
* removed ID from test of task complete output 
* added test selecting tasks by tag and verified import of annotations

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-07-28T04:24:14Z says:_ 

 Thank you Markus!  The patches are great.  I appreciate the work you put into this.

I held off on applying import.t, because I'm not sure it's necessary, as you pointed out.

I added you to the ChangeLog and AUTHORS file.

**Comment by pbeckingham** [comment]
[TW-1383_import-yaml.pl.patch.2.4.0.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755641/TW-1383_import-yaml.pl.patch.2.4.0.txt)
[TW-1383_import-yaml.pl.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755642/TW-1383_import-yaml.pl.patch.txt)
[TW-1383_import.t.patch.2.4.0.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755643/TW-1383_import.t.patch.2.4.0.txt)
[TW-1383_import.t.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755644/TW-1383_import.t.patch.txt)
[TW-1383_import.yaml.t.patch.2.4.0.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755645/TW-1383_import.yaml.t.patch.2.4.0.txt)
[TW-1383_import.yaml.t.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755646/TW-1383_import.yaml.t.patch.txt)
