### ISSUE TITLE
[TW-1384] "Client Sync Key not Found" if sync credentials are changed without running `task sync init`

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1412]
_Jack on 2014-07-27T04:11:26Z says:_ 

 To recreate:

* Set up to sync with your Taskserver and sync successfully
* Create new credentials with your Taskserver, and configure TaskWarrior to sync with them. Except call `task sync` instead of `task sync init` the first time you use the new credentials.

This is the error:
{code}
Sync failed.  The Taskserver returned error: 500 Client sync key not found.
{code}

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-07-27T04:11:26Z
Modified: 2017-03-01T18:48:50Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-16T18:56:03Z says:_ 

 Looks like we just need a better interpretation of the error code.

**Comment by taskwarrior** [comment]
_Antonio Huete Jimenez on 2017-03-01T18:48:50Z says:_ 

 Hi,

In my case I was trying to solve another issue and whilst implementing a solution proposed by Paul, at some point, I had to resync my TW clients and I got that message.

Deleting ~/.task/backlog.data and running 'task sync' again solved the issue for me.

PS: Backup your ~/.task before doing any change!

Cheers,
Antonio Huete

**Comment by djmitche** [comment]
This is regarding the old sync.
