### ISSUE TITLE
[TW-1390] task undo should not undo recurring tasks or should do so permanently

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1417]
_Renato Alves on 2014-08-06T18:15:11Z says:_ 

 This is a somewhat extreme case but it shows the underlying problem.

```
You create a daily recurring task due the following day.
You then spend a week without using task (holidays).
You return and run the default report to check on your todo list.
You will be presented with several due tasks that were generated moments ago.
You decide to use *undo* several times to revert the recurring tasks.
You run the default report again and all your undone tasks are re-generated.
```

In this situation "undo" is probably not the command one should be using. Though once it gets used, it may be confusing for the user to see that undo *doesn't work* given that all tasks are back on the list.

I suggest that *recurring* tasks are treated specially by `task undo` following one of two criteria:
* making *undo* act as *delete* or *done*
* not allow *undo* to act on changes that do not result from *write subcommands*.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-08-06T18:15:11Z
Modified: 2015-02-09T08:02:31Z
```

**Comment by djmitche** [comment]
This seems to be working as intended. In general I think `task undo` is kind of like CTRL-Z/CMD-Z -- meant to undo something that happened very recently, and subject to a lot of edge cases where maybe it's not quite what you expect. In this case, it's undoing a change (creation of the recurring tasks) but those recurring tasks are being re-created, as documented for recurrence, so I think it's working as intended.
