### ISSUE TITLE
[TW-1414] default.command doesn't work with execute anymore

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1441]
_Johannes Schlatow on 2014-09-16T08:30:03Z says:_ 

 In order to apply some location-based filters, I have set my default.command to something like this:

default.command=execute /path/to/external/script

Unfortunately, this happens to be broken in the upcoming 2.4.0

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-09-16T08:30:03Z
Modified: 2014-11-08T20:15:56Z
```

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2014-10-10T22:50:49Z says:_ 

 Attach patch with test case.

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2014-10-11T09:09:19Z says:_ 

 I did a git bisect. Apparently, commit 14a74fefdcf922d2406a5026136f786b428c53e3 breaks this.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-10-11T15:27:14Z says:_ 

 That commit is in code that is now gone.  Will investigate.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-10-13T03:37:21Z says:_ 

 Yeah, that's broken.  Test patch applied.  Thank you.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-11-08T20:15:56Z says:_ 

 Fixed with new parser.

**Comment by pbeckingham** [comment]
[TW-1414_0001-Test.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756346/TW-1414_0001-Test.patch.txt)
