### ISSUE TITLE
[TW-1418] Operators do not play nicely in filters

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1445]
_Ralph Bean on 2014-09-20T04:34:21Z says:_ 

 Running "task add foobar+" works just fine but trying to filter for the added task with "task foobar+" causes taskwarrior to segfault.

Similarly, "task add foo/bar" works, but trying to filter for it with "task foo/bar" causes taskwarrior to complain about dividing integers by strings.

"task add foo-" and later filtering for "task foo-" causes taskwarrior to complain about subtraction from a boolean.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-09-20T04:34:21Z
Modified: 2014-10-13T03:15:35Z
```

**Comment by taskwarrior** [comment]
_Ralph Bean on 2014-09-21T02:28:10Z says:_ 

 Here's a patch that just adds failing tests to the test suite for this issue.

**Comment by taskwarrior** [comment]
_Kosta Harlan on 2014-09-26T15:01:33Z says:_ 

 Similarly, `task project:blah-blah` results in "expression could not be evaluated" while adding "task add Test project:blah-blah" works fine.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-09-27T15:52:16Z says:_ 

 Thanks for the unit tests - applied and pushed.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-09-28T16:32:44Z says:_ 

 Okay, the segfault is hopefully eliminated now.

In general, to search for 'foo+', use 'task /foo+/'.  I think the automatic upgrade of bare words in a filter to search patterns is probably going to be deprecated.  There is simply too much ambiguity in the command line to keep allowing this.

Still working on this - more later.

**Comment by taskwarrior** [comment]
_Adam Coddington on 2014-09-29T16:27:50Z says:_ 

 Oh, neat. So, say that we had multiple search expressions -- like:

```
    (project:something) (description:"something else" or due.not:"")
```

Would that entire expression be surrounded by `/` signs, [~PBeckingham]?

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2014-09-29T17:47:41Z says:_ 

 No, that filter would continue to work as-is. What Paul is talking about is this scenario:

You have, amongst others, tasks with the descriptions "fooBar 1", "fooBar 2", hello fooBar 3", and "yet another fooBar". Now you want to use "fooBar" as a filter. Here is how that can be done right now:
```
task fooBar next
```
Here is how it would have to be done if bare words were no longer to be upgraded to search patterns:
```
task /fooBar/ next
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-09-29T20:55:07Z says:_ 

 Right, like this:

```
$ task /foo/ and (/bar/ or /baz/) list
```

**Comment by taskwarrior** [comment]
_Adam Coddington on 2014-09-30T05:28:59Z says:_ 

 Oh, cool, that makes sense; thanks Paul & Will.

**Comment by taskwarrior** [comment]
_Ralph Bean on 2014-10-07T18:55:49Z says:_ 

 Likely related - I found what I think is another segfault in the beta1 release.

```
task add description:"foobar-"
[1]    19509 segmentation fault (core dumped)  task add description:"foobar-"
```

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-10-10T09:45:52Z says:_ 

 I can't reproduce that last one. Was it fixed already?

On a similar example:

```
task add foo/
task /foo//       <- Error: Cannot divide Boolean values
task /foo\//      <- Works as expected
```

Is escaping mandatory in this case?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-10-11T15:36:11Z says:_ 

 This issue is going to be closed soon.  Here is why:

1. Bare word searching is both problematic and deprecated, mostly for the reasons found in this issue.  I have removed bare word search testing, it will not be fixed.
2. Putting expression operators in (some) command line arguments requires that they be escaped, for example: /foo\\/.  This is one of the downsides to having expression support everywhere, we now have to be more careful about quoting and escaping.  I have modified the tests accordingly.

**Comment by taskwarrior** [comment]
_Adam Coddington on 2014-10-13T02:28:20Z says:_ 

 Cool -- sounds good!  I don't think the python taskw library uses bare word searching at all, honestly, I think the thing we were bumping into problems with is that most of the unique identifiers we were using for bugwarrior are URLs, and are, as you'd guess, riddled with slashes.  Given that you promise escaping works, I'll get a patch sorted out for taskw right away.

Thanks for your time and attention, (at)paul!

(Relevant commit: https://git.tasktools.org/projects/TM/repos/task/commits/9325098b5cdca8212c7c247f74f6bb40c45e970e)

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-10-13T03:15:35Z says:_ 

 Fixed, more or less.

**Comment by pbeckingham** [comment]
[TW-1418_0001-Unit-Tests.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756347/TW-1418_0001-Unit-Tests.patch.txt)
