### ISSUE TITLE
[TW-1428] Introduce "color.uda.<name>.<value>" attribute

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1455]
_Johannes Schlatow on 2014-10-10T12:12:01Z says:_ 

 TW already supports the attribute "color.uda.<name>", which allows coloring of a task that has a particular UDA set.
However, there are certain cases where a user wants to color a task depending on the value of the UDA.
We therefore should add support for the attribute "color.uda.<name>.<value>".

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-10-10T12:12:01Z
Modified: 2014-10-15T11:20:37Z
```

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2014-10-10T12:15:59Z says:_ 

 I actually implemented this already but I cannot close the issue.

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2014-10-10T21:47:05Z says:_ 

 Attached patch.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-10-13T03:41:31Z says:_ 

 Jira privileges raised.  You should be able to close now.  However, closing it before I see it means it could get ignored.  Patch applied.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-10-13T03:47:41Z says:_ 

 Nice patch, thank you.

**Comment by pbeckingham** [comment]
[TW-1428_0001-Color.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756348/TW-1428_0001-Color.patch.txt)
