### ISSUE TITLE
[TW-1429] Filtering of tags containing special words does not work

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1456]
_Johannes Schlatow on 2014-10-11T10:27:40Z says:_ 

 Steps to reproduce:
*   Add a task with tags like +someday +later +eow that have a special meaning when used in another context.
*  Try to apply a filter for these tags:
    $> task list +someday
*  Result: Empty report.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-10-11T10:27:40Z
Modified: 2014-11-11T04:12:53Z
```

**Comment by fullstopslash** [comment]
I'm experiencing this again for the someday tag. It breaks filtering as well as timewarrior integration.
