### ISSUE TITLE
[TW-1430] Slashes in project names don't work

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1457]
_Richard Boß on 2014-10-13T18:40:17Z says:_ 

 Project names with slashes as separators don't yet work in Taskwarrior 2.4.0. For example:

$ task project:home/garden
Cannot divide real numbers by strings

This used to work without problems in Taskwarrior 2.3.0 and I would be really happy if it would work again. For me project names with slashes have one big advantage: they map without translation to a folder hierarchy in the file system. That's where I store additional info for projects.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-10-13T18:40:17Z
Modified: 2015-07-13T13:31:03Z
```

**Comment by taskwarrior** [comment]
_Richard Boß on 2014-10-13T20:22:26Z says:_ 

 I'd like to clarify that there is no problem *adding* a task which has a project name that has slashes in it. That seems to work now. But *filtering* for such projects doesn't work yet.

Attached is a somewhat hackish but working test case.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-10-13T22:29:05Z says:_ 

 Tests added.  Thank you Richard!

Let this be a lesson to all - if you want your bug fixed, providing tests will boost the chances.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-11-29T21:33:35Z says:_ 

 We have a workaround:

```
task project.is:home/garden list
```

**Comment by pbeckingham** [comment]
[TW-1430_tw-1430.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756350/TW-1430_tw-1430.t.txt)
