### ISSUE TITLE
[TW-1438] Configuration setting rc.confirmation=no no longer disables confirmation requests.

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1465]
_Adam Coddington on 2014-10-16T19:40:00Z says:_ 

 In a [recent pull request against the taskw library|https://github.com/ralphbean/taskw/pull/71], it became apparent that `rc.confirmation` was no longer working as expected.

Earlier this afternoon, I spoke with (at)Unode on the `#taskwarrior` IRC channel, and he confirmed that he is able to reproduce the issue.

{code}
[12:31:01] Unode coddingtonbear, have you ran into this issue during your experience with inthe.am ?
[12:31:40] coddingtonbear oh, no, somebody posted a PR against taskw --> https://github.com/ralphbean/taskw/pull/71
[12:31:45] coddingtonbear Unode -^
[12:33:28] Unode Yeah I've seen that one too.
[12:34:24] Unode Though I have confirmations on as I'm too clumsy with using the right order or arguments.
[12:35:10] Unode coddingtonbear, would it be too much to ask that you add a bug report on taskw's jira linking to that one?
[12:35:21] coddingtonbear oh, are you sure it's actually a bug, though?
[12:35:24] coddingtonbear if so, totally
[12:35:35] coddingtonbear I haven't tried verifying it quite yet
[12:36:52] Unode coddingtonbear, just confirmed.
[12:37:08] Unode This is a recurring task.  Do you want to modify all pending recurrences of this same task? (yes/no) is always shown.
[12:37:23] coddingtonbear awesome
[12:37:30] coddingtonbear I'll add it
{code}

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-10-16T19:40:00Z
Modified: 2014-12-26T15:07:44Z
```

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2014-10-16T20:11:54Z says:_ 

 There were a few more places where rc.confirmation was being ignored.

The attached patch fixes this. It also makes setting rc.confirmation to "no" a lot more dangerous. I have not put a lot of thought into this and will not be held accountable for lost data. :)

There is now only one place left where user confirmation is needed regardless of the state of rc.confirmation, and that is in the edit command. Since it is inherently interactive and the confirmation is for invalid data, I'm leaving this one in.

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-10-16T22:15:31Z says:_ 

 I'm not familiar with how the other confirmation=no actions work but looking at the patch, shouldn't the default be "no" on some of these?

For instance editing a children will now by default also affect the parent.
I'd consider it safer to default to no given the user can always edit the parent directly.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-10-17T00:58:47Z says:_ 

 I agree - system-wide rc.confirmation=on is dangerous, which is why it was never done.

I think a two-stage confirmation, with rc.confirmation and rc.confirmation.foo (where 'foo' is some better name) is better.  I would rather force the user to turn on both, before it gets dangerous.

I should add that the patch would need documentation updates and test changes.

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2014-10-17T05:30:10Z says:_ 

 Renato:
You are absolutely right, of course. As I said above, I definitely should have put some actual thought into this instead of blindly killing confirmation prompts left and right; I might be able to take a second look later on today, but I am actually busy right now. (Cue joke by Paul)

Paul:
Agreed. rc.confirmation.hide_dangerous (or something like it) would be better.
And yes, even just my changes above would need tests.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-11-10T03:49:57Z says:_ 

 I cannot reproduce this with 2.4.0 commit ec18c1b9d740d1729333c15e17613209f30b55ef or later.  Anyone?

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-11-10T11:05:56Z says:_ 

 Paul:
Can you elaborate what you cannot reproduce? The tw-1438.t testcase is still failing here when on ec18c1b9d740d1729333c15e17613209f30b55ef.

The problem is that taskwarrior always prompts for confirmation when changing recurring tasks even if rc.confirmation is off.
This is obviously a problem for taskwarrior wrappers that expect no prompts from taskwarrior.

I think that at least in the recurring case, if the task being edited is a children, instead of prompting for confirmation on also affecting the parent it could instead be replaced by an informative warning "This is a recurring task. If you also want to modify future occurrences of this task modify <ID or UUID of parent>".
This way we get rid of the prompt while providing user guidance.

Personally, I also find this prompt on recurring tasks a little bit annoying.
Most of the time I only want to change the wait: status or add annotations and that prompt always jumps to the screen.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-11-11T01:06:42Z says:_ 

 New rc.recurrence.confirmation setting can bypass the confirmation step when propagating changes to other recurring tasks.

rc.confirmation confirmed working.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-11-11T01:07:18Z says:_ 

 Renato: I was wrong.  I can reproduce this, and it works as designed.  The rc.confirmation setting was never meant for "dangerous" stuff, and propagating changes to other recurring tasks is that.

I have added support for rc.recurrence.confirmation, which defaults to "yes", and can be used to override this.

Adam's original observation may just have been a bad 2.4.0 commit, and the tests show that rc.confirmation is now working.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-12-26T15:07:27Z says:_ 

 Further update:  recurrence.confirmation is now a tri-state, supporting the values:

prompt - prompt every time
yes - always propagate changes
no - never propagate changes

**Comment by pbeckingham** [comment]
[TW-1438_2014-10-16_TW-1438.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756354/TW-1438_2014-10-16_TW-1438.patch.txt)
