### ISSUE TITLE
[TW-1440] task import from STDIN by specifying filename "-"

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1467]
_Renato Alves on 2014-10-17T21:48:52Z says:_ 

 In order to import tasks one must first export to a file and then use task import or use the convoluted <(echo ) syntax.

A simpler interface would be to use the dash "-" convention to indicate STDIN as the "file" to read from.

Example usage:
```
task export | task rc:/tmp/taskrc import -
```

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-10-17T21:48:52Z
Modified: 2015-05-25T14:56:58Z
```

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-10-17T22:08:44Z says:_ 

 Testcase attached

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-05-25T14:56:58Z says:_ 

 "task import" (without specifying filenames) and "task import -" now both read from STDIN.

**Comment by pbeckingham** [comment]
[TW-1440_tw-1440.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756356/TW-1440_tw-1440.t.txt)
