### ISSUE TITLE
[TW-1441] task import continues happily if filename doesn't exist

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1468]
_Renato Alves on 2014-10-17T21:53:11Z says:_ 

 The current behaviour is:
```
$ task import all bananas
Importing 'all'
Importing 'bananas'
Imported 0 tasks.

$ task import
You must specify a file to import.
```

In the first case it should display some error indicating that the file doesn't exist.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-10-17T21:53:11Z
Modified: 2014-10-19T10:34:02Z
```

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-10-17T22:00:32Z says:_ 

 Test case attached. Test will need adjustment depending on message used to inform of the error.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-10-18T18:43:05Z says:_ 

 Fixed, but the test generates this:

```
1..1
not ok 1 - import fails if file doesn't exist
1.  ERROR: TypeError on file ./tw-1441.t line 22 in test_import_filename: 'self.assertIn("File 'somefile' not found.", err)':
1.         argument of type 'NoneType' is not iterable
```

**Comment by pbeckingham** [comment]
[TW-1441_2014-10-19_TW-1441_test.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756357/TW-1441_2014-10-19_TW-1441_test.patch.txt)
[TW-1441_tw-1441.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756358/TW-1441_tw-1441.t.txt)
