### ISSUE TITLE
[TW-1476] The confirmation=no directive is not respected with bulk commands - documentation update

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1502]
_Tomas Babej on 2014-12-19T01:39:04Z says:_ 

 The man taskrc says about rc.confirmation:

```
May  be  "yes"  or  "no", and determines whether taskwarrior will ask for confirmation before deleting a task, performing bulk changes, or the undo command.
```

However, if running any command that modifies/deletes more entries than rc.bulk, I am prompted for confirmation no matter the value of rc.confirmation

Without rc.bulk=<more than number of affected tasks> I am prompted:

```
task rc:/ rc.confirmation=no rc.data.location=/home/tbabej/.task 0 modify prio:M
*  Priority will be changed from 'H' to 'M'.
Modify task 16f98680-86a5-474f-8f5e-440e8d2f5952 'text:ahaha'? (yes/no/all/quit)
```

With rc.bulk set to more than the number of affected tasks, confirmation is not required:

```
task rc:/ rc.confirmation=no rc.bulk=10 rc.data.location=/home/tbabej/.task 0 modify prio:H
Modifying task 16f98680-86a5-474f-8f5e-440e8d2f5952 'text:ahaha'.
Modifying task e8c8addf-8527-420f-9e02-b8457ffe5fb2 'random to delete'.
Modifying task 3e469af9-baa9-433e-a17c-63b511eea7c2 'Parent'.
Modifying task ee9dfa4f-1d71-4870-a4dc-a5a4da1b2f55 'random task in a subproject'.
Modifying task 94dfbc10-177e-421e-a6bd-887ae10d35b9 'Listen to that!'.
Modifying task 10033ec1-431d-4c2b-a7d4-3f7124604548 'Setup taskserver'.
Modified 6 tasks.
Using alternate .taskrc file /
Using alternate data.location /home/tbabej/.task
Configuration override rc.confirmation:no
Configuration override rc.bulk:10
Configuration override rc.data.location:/home/tbabej/.task
Project 'Test' is 0% complete (0 of 0 tasks remaining).
Project 'Test.Subtest' is 0% complete (0 of 0 tasks remaining).
```

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-12-19T01:39:04Z
Modified: 2015-01-24T15:10:10Z
```

**Comment by taskwarrior** [comment]
_Tomas Babej on 2014-12-19T01:46:19Z says:_ 

 Well, it seems that it is 3.am here, and I've mistaken ``` with {noprivate} when writing up the bug report. Sorry!

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-12-20T15:08:16Z says:_ 

 Fixed.  :)

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-12-24T04:15:40Z says:_ 

 This is deliberate, it's not supposed to honor the confirmation setting in this case.  The bulk setting is a trigger to prevent commands like this, or similar:

```
$ task modify foo
```

This is a write command with no filter, which would modify all tasks.  While this specific case is caught and handled separately, there is a class of bad commands that are almost as damaging.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-22T08:11:08Z says:_ 

 Attached patch for the man page is required then (reopening to attach).

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-22T12:46:27Z says:_ 

 I have closed this before, and stated the reasons.  A closed big is not a candidate for a fix.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-22T13:31:40Z says:_ 

 It's a *documentation* fix. A man page states the behaviour of options, and that statement does not describe how taskwarrior behaves.

You said in comment 3 that the behaviour of taskwarrior is deliberate. Therefore the *man page* is wrong, and *needs correction*.

How can this be not a candidate for a fix?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-24T15:10:10Z says:_ 

 Patch applied.  Thank you, and sorry for not reading beyond the fourth word.

**Comment by pbeckingham** [comment]
[TW-1476_tbabej-task-0012-Documentation-update-taskrc-man.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756360/TW-1476_tbabej-task-0012-Documentation-update-taskrc-man.patch.txt)
