### ISSUE TITLE
[TW-1477] Incompatibility with recurring tasks created with 2.3.0

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1503]
_David Costa on 2014-12-21T19:46:27Z says:_ 

 Taskwarrior compiled from git and launched as "task next" gives the following error instead of the next report:
`The recurrence value 'month' is not valid.` 
then quits with exit code 2.
The code compiled from the v2.3.0 tag works correctly.

I bisected the code between 2.3.0 and the head of the 2.4.0 branch obtaining that the commit 5170a842d61f927560a52d07b738b0aaaff61cd2 introduced this behavior.

*How to reproduce*
With task 2.3.0 and an empty data folder
`task add something recur:month due:18th`
With task 2.4.0rc3 of after that commit
`task next`

The only relevant part about the rc-file that differs from the default is:
`
dateformat=d/m/Y
dateformat.annotation=d/m/Y
dateformat.edit=d/m/Y H:N:S
dateformat.info=d/m/Y H:N:S
dateformat.report=d/m/Y
`

A minimal pending.data that causes troubles is attached.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-12-21T19:46:27Z
Modified: 2014-12-29T00:22:19Z
```

**Comment by taskwarrior** [comment]
_David Costa on 2014-12-21T20:10:06Z says:_ 

 If I call "task next" with 2.3.0 and then again with 2.4.0 it works correctly so it seems related to recurring tasks without any instance yet

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-12-24T05:18:54Z says:_ 

 Great data, thank you.  Will be addressed in 2.4.0.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-12-29T00:22:19Z says:_ 

 This was two problems.  First, 'month' was not considered a standalone unit value (and thus required a preceding number), and the logic only allowed for standalone or not-standalone, and this could be either: 1month, month.

**Comment by pbeckingham** [comment]
[TW-1477_pending.data.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756359/TW-1477_pending.data.txt)
