### ISSUE TITLE
[TW-1488] You have more urgent tasks.

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1514]
_Stefan Betz on 2015-01-03T14:35:55Z says:_ 

 Take a look at https://imgur.com/anWEIr8. There are no other tasks with an higher urgency.

Works fine in 2.3.*, first occurrence in 2.4.0.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-01-03T14:35:55Z
Modified: 2015-07-13T15:36:25Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-03T15:02:59Z says:_ 

 In the sample data, there is a task (UUID 025b69cc-d51b-be67-7af4-f1c9ab01eafe) that is waiting and has an urgency of 16.  Because it is a parent recurring task, it is not shown, but it exists, and the nag message is correct.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-03T15:13:43Z says:_ 

 The nag message is correct, although it is a little confusing when you can't find the task with higher urgency.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-03T15:18:56Z says:_ 

 Reopening.  This is more interesting than first glance.

It appears the urgency coefficients are not right - a waiting task has a coefficient of -3.0 by default, and that needs to be higher to compensate for due date.

**Comment by taskwarrior** [comment]
_Denis Kasak on 2015-06-07T16:26:24Z says:_ 

 Shouldn't the nagging ignore recurring parent tasks since those tasks will never get done directly, only their children?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-06-07T16:43:12Z says:_ 

 That's a good point.  Thanks!

**Comment by pbeckingham** [comment]
[TW-1488_task-data.tar.gz](https://github.com/GothenburgBitFactory/taskwarrior/files/1756363/TW-1488_task-data.tar.gz)
