### ISSUE TITLE
[TW-1491] Regression in deleting due dates

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1517]
_Jens Erat on 2015-01-03T17:48:15Z says:_ 

 Since I upgraded to the released 2.4.0 version, I cannot unset due dates any more. I'm rather sure the version of some time in december didn't have the issue.

If I run something like

    task 42 modify due:

the due date gets set to unixtime 0 instead (1970-01-01). An example from a task modification log:

    2015-01-03 18:42:19 Due changed from '2014-12-19 20:35:30' to '1970-01-01 01:00:00'.

Expected behavior: due date is removed.

I didn't test against the wait attribute yet.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-01-03T17:48:15Z
Modified: 2015-02-14T21:39:50Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-04T01:10:13Z says:_ 

 I cannot reproduce this.

```
$ echo 'data.location=.' > x
$ task rc:x add one due:tomorrow
$ task rc:x 1 modify due:
$ cat pending.data
[description:"one" entry:"1420333772" modified:"1420333772" status:"pending" uuid:"800f5752-c804-40ff-98ff-a0bea5c5d332"]
$```

**Comment by taskwarrior** [comment]
_Jens Erat on 2015-01-11T16:09:15Z says:_ 

 This patch modifies date import and export to match the behavior of other attributes:
*  If value is the empty string, import/export empty string
*  If value is something else, parse as date and im/portexport as ISO date

As far as I understood the code, taskwarrior will subsequently use these empty strings to actually delete an attribute. For exporting and importing, this was never an issue as the attribute already have been deleted, but for hooks, "unclean" task data with empty string attribute values can exist.

I did not break any new test cases.

I didn't provide any unit test. I could not find any similar test to replicate. The import-tests do not fit, as `task export` is not affected by this issue. Are there already any hook tests?

All that's needed to replicate this is an "identity-modify-hook", and deleting any date value, so it shouldn't be that hard to test.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-12T20:48:31Z says:_ 

 Thank you for the patch!  That's a perfect fix.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-02-14T20:54:14Z says:_ 

 Fix is incomplete, unfortunately. Consider the following scenario:

{code}
[tbabej ~] $ task add test due:2015-05-05
Created task 1.
The project 'Inbox' has changed.  Project 'Inbox' is 0% complete (1 task remaining).
[tbabej ~] $ task 1 mod due:
Modifying task 1 'test'.
Modified 1 task.
Project 'Inbox' is 0% complete (1 task remaining).
[tbabej ~] $ task 1 info

Name          Value                                     
ID            1
Description   test                                      
Status        Pending
Project       Inbox                                     
Entered       2015-02-14 21:52:59 (18 seconds)
Last modified 2015-02-14 21:52:59 (18 seconds)          
UUID          54e3d648-d962-435c-9ca4-d49a09d7c422
Urgency       1                                         
                           project     1  *    1 =     1

Date                Modification
2015-02-14 21:53:07 Due deleted.

[tbabej ~] $ task sync
Syncing with server.strom.sk:53589

Sync successful.  2 changes uploaded.
[tbabej ~] $ vim ~/.taskrc # Change the taskrc data_location to emulate new client
[tbabej ~] $ task sync
Syncing with server.strom.sk:53589
     add 54e3d648-d962-435c-9ca4-d49a09d7c422 'test'
  modify 54e3d648-d962-435c-9ca4-d49a09d7c422 'test'

Sync successful.  2 changes downloaded.
[tbabej ~] $ task 1 info

Name          Value                                     
ID            1
Description   test                                      
Status        Pending
Project       Inbox                                     
Entered       2015-02-14 21:52:59 (42 seconds)
Due           1970-01-01 01:00:00                       
Last modified 2015-02-14 21:52:59 (42 seconds)
UUID          54e3d648-d962-435c-9ca4-d49a09d7c422      
Urgency       13
                           project     1  *    1 =     1
                               due     1  *   12 =    12

Date                Modification                                                    
2015-02-14 21:53:37 Due changed from '2015-05-05 00:00:00' to '1970-01-01 01:00:00'.

{code}

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-02-14T20:56:40Z says:_ 

 On the second client, I can see in the pending.data:

{code}
[description:"test" due:"0" entry:"1423947179" modified:"1423947179" project:"Inbox" status:"pending" uuid:"54e3d648-d962-435c-9ca4-d49a09d7c422"]
{code}

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-02-14T21:39:50Z says:_ 

 328b7ec2604c66ed758692fe8e1577c96b56f7f7 fixes the issue.

**Comment by pbeckingham** [comment]
[TW-1491_0001-TW-1491-TW-1491-Regression-in-deleting-due-dates.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756365/TW-1491_0001-TW-1491-TW-1491-Regression-in-deleting-due-dates.patch.txt)
