### ISSUE TITLE
[TW-1492] compiling v2.4.0 using musl(libc)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1518]
_V.Krishn on 2015-01-04T11:58:24Z says:_ 

 compiling v2.4.0 using musl(libc)

Issues:
 had to change line 705 on ISO8601.cpp 
from:
_value = utc ? timegm (&t) : timelocal (&t);
to:
 _value = utc ? timegm (&t) : mktime (&t);

Ran tests (for problems, pls see attachments):
./export.yaml.t            22
./tw-1424.t                 1
./cal.t                         1
These failed tests may not be related to issues stated above.

Please have a look for possible fixes.
Thanks

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-01-04T11:58:24Z
Modified: 2015-01-04T16:44:35Z
```

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-04T13:06:32Z says:_ 

 tw-1424.t is failing on my build too, so it's unrelated, unlike other two

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-04T15:11:44Z says:_ 

 These test failure are fine, and expected at the moment.  The export.yaml.t ones are because of a missing Perl JSON module.  It looks like V.Krishn's suggested change is good.  Patched.  Pushed.

Thank you - you are now in the AUTHORS file.

**Comment by taskwarrior** [comment]
_V.Krishn on 2015-01-04T16:41:57Z says:_ 

 Tested ./export.yaml.t with perl-json pkg, all 1..22 passed(ok).
Looking forward for next stable release.
Thanks.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-04T16:44:35Z says:_ 

 Thanks for the bug report.  Next release will be SOON, a matter of a week or two, not months.  There are a lot of small issues that indicate we should release again.

**Comment by pbeckingham** [comment]
[TW-1492_cal.t.error.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756368/TW-1492_cal.t.error.txt)
[TW-1492_export.yaml.t.error.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756369/TW-1492_export.yaml.t.error.txt)
[TW-1492_tw-1424.t.error.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756370/TW-1492_tw-1424.t.error.txt)
