### ISSUE TITLE
[TW-1493] task timesheet doesn't work with localized builds of taskwarrior

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1519]
_Jens Erat on 2015-01-04T22:09:20Z says:_ 

 While translating taskwarrior to the German language, I'm trying out functions I was never aware of..

On of those is `task timesheet`. If `STRING_DATE_SUNDAY_LONG` is translated, this command will fail with a message `The 'weekstart' configuration variable may only contain 'Sunday' or 'Monday'.`

This option is not set in my `.taskrc`. I guess task falls back to the translated string instead of the bare value (which should be used). `task config weekstart Monday` (from a European point of view, starting the week on Sundays is a weird idea ;) ) resolves the issue.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-01-04T22:09:20Z
Modified: 2015-01-10T20:17:41Z
```

**Comment by taskwarrior** [comment]
_Jens Erat on 2015-01-04T22:22:51Z says:_ 

 Actually it does *not* resolve the issue to set `weekstart`.

Also applies to `task calendar`.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-05T03:32:51Z says:_ 

 Good catch.

**Comment by pbeckingham** [comment]
Lcoalizations are gone.  Using gettext in the future.
