### ISSUE TITLE
[TW-1494] Use gettext or similar l10n-library

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1520]
_Jens Erat on 2015-01-05T12:28:18Z says:_ 

 Taskwarrior's current localization-system is very inconvenient, and in the end requires building your own copy instead of using versions from distribution repositories (and also maintaining it!).

De-facto standard solution for localization is gettext, which would allow
*  more convenient translation, including solutions like Pontifex for translating the product without changing the code (also making changes easier, possibly addressing more users for new translations and fixes)
*  more reliable change management regarding new and modified strings
*  selecting the appropriate language based on the environment
*  does not require self-build maintenance-scripts, but already offers a broad variety of solutions

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-01-05T12:28:18Z
Modified: 2015-09-02T01:03:56Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-08T04:39:32Z says:_ 

 I understand that gettext is a standard, but converting is a massive amount of work, and there is no one who wants to do it.

There was an attempt in the past, but the person gave up before finishing, and it was rolled back.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-09-02T01:03:56Z says:_ 

 Copied from the duplicate TW-1614:

ribbon added a comment - 2015-05-12 10:08
This ticket is a request.
However, it is I have to understand that there are many problems with the improvement of I18N.
As you say, it is hard to internationalize the 718 string.
* ----------------------------------------------------------------------------
I have one proposal.
Internationalization only help message that is displayed in the "task help".
1) It will divide the lng-LNG.h file into two(lng-LNG.h and lng-LNG-help.h).
2) The STRING_CMD_HELP_TEXT of all languages minutes it will include.
3) It switches the help message by locale.
When the help message is localized, usability is the better.I think that a big 
effect is provided with a small work load.

**Comment by pbeckingham** [comment]
We will be using gettext in the future.

**Comment by tbabej** [comment]
Support for internationalization was removed in 2.6.0 due to overhead and limited usability of outdated translations, thus rendering this request invalid. If localization is re-introduced in the future, it should however use gettext or similar framework to make translations more seamless.
