### ISSUE TITLE
[TW-1495] German translation for taskwarrior

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1521]
_Jens Erat on 2015-01-05T12:31:50Z says:_ 

 Find a German translation of the current git 2.4.1 HEAD attached.

The language is already added to the configuration, only the language file was missing; here it is.

I did not translate the `task diag` output, I guess it's more reasonable to keep this in English language (as being primary goal providing ability to diagnose issues with developers, where common language should be English?).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-01-05T12:31:50Z
Modified: 2015-01-08T04:38:12Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-08T04:15:35Z says:_ 

 Thank you.

There are several areas of the code that are not localized.  We'll get there.

**Comment by pbeckingham** [comment]
[TW-1495_deu-DEU.h.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756372/TW-1495_deu-DEU.h.txt)
