### ISSUE TITLE
[TW-1497] Missing strings for localization

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1523]
_Jens Erat on 2015-01-05T12:40:53Z says:_ 

 Following strings seem to be missing for translation:
*  `task burndown`: "Add rate:", "Done/Delete rate:", "Estimated completion:"
*  `task reports`: A lot of report descriptions cannot be translated yet
*  `task show`: "These are highlighted in color above.", "color" cannot be translated yet

The table headers for reports are not translateable, either; I'm not sure if that's intended.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-01-05T12:40:53Z
Modified: 2015-01-10T20:17:02Z
```

**Comment by pbeckingham** [comment]
We will be using gettext in the future.
