### ISSUE TITLE
[TW-1504] On-modify hook does not accept correct JSON format

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1530]
_Tomas Babej on 2015-01-08T02:31:12Z says:_ 

 Note: I am running a identical hook for on-modify and on-add events (only difference is that the former eats up two lines of input):

https://gist.github.com/tbabej/e6c43b4e074d71abe3e5

When running command which triggers on-modify event, I am notified that I am using a old TW format and the modification is aborted.

However, outputs from both add and modify commands are the same, compare:

add:
```
Hooks: output
  {"status": "pending", "uuid": "db38d514-cb37-41b4-9207-130024dbb64c", "modified": "20150108T022612Z", "due": "20150109T210000Z", "entry": "20150108T022612Z", "description": "test2"}
  Default due time has been set.
```

modify:
```
Hooks: output
  {"status": "pending", "uuid": "386c9eb0-a6a4-4550-ad03-0731247f68fc", "modified": "20150108T022555Z", "due": "20150109T210000Z", "entry": "20150108T022555Z", "description": "test"}
  Default due time has been set.
```

Full commands:
add:
```
task rc.debug.hooks=3 add test2 due:tomorrow                                                                                                                                   
Timer Config::load (/usr/share/doc/task/rc/solarized-dark-256.theme) 0.000369 sec
Timer Config::load (/home/tbabej/.taskrc) 0.002945 sec
Found hook script /home/tbabej/.task/hooks/on-add-date-default-time
Found hook script /home/tbabej/.task/hooks/on-modify-date-default-time
Task::modify
  MODIFICATION due <-- '1420758000' <-- '2015-01-09T00:00:00' <-- 'tomorrow'
  MODIFICATION description <-- 'test2'
Hooks: Calling /home/tbabej/.task/hooks/on-add-date-default-time
Hooks: input
  {"description":"test2","due":"20150108T230000Z","entry":"20150108T022612Z","modified":"20150108T022612Z","status":"pending","uuid":"db38d514-cb37-41b4-9207-130024dbb64c"}
Hooks: output
  {"status": "pending", "uuid": "db38d514-cb37-41b4-9207-130024dbb64c", "modified": "20150108T022612Z", "due": "20150109T210000Z", "entry": "20150108T022612Z", "description": "test2"}
  Default due time has been set.
Hooks: Completed with status 0
 
  pending.data rw O T0002+001~000 L0001+000
completed.data rw - T0000+000~000 L0000+000
     undo.data rw O T0000+000~000 L0003+003
  backlog.data rw O T0000+000~000 L0001+001
 
Perf task 2.4.1 0f64c32 20150108T022613Z init:7247 load:276 gc:0 filter:0 commit:360 sort:0 render:0 hooks:164457 total:172340

Created task 2.
Configuration override rc.debug.hooks:3
Default due time has been set.

```

modify:
```
task rc.debug.hooks=3 1 modify due:tomorrow                                                                                                                                    
Modifying task 1 'test'.
Timer Config::load (/usr/share/doc/task/rc/solarized-dark-256.theme) 0.000719 sec
Timer Config::load (/home/tbabej/.taskrc) 0.004824 sec
Found hook script /home/tbabej/.task/hooks/on-add-date-default-time
Found hook script /home/tbabej/.task/hooks/on-modify-date-default-time
Filtered 2 tasks --> 1 tasks [all tasks]
Task::modify
  MODIFICATION due <-- '1420758000' <-- '2015-01-09T00:00:00' <-- 'tomorrow'
Hooks: Calling /home/tbabej/.task/hooks/on-modify-date-default-time
Hooks: input
  {"description":"test","entry":"20150108T022555Z","modified":"20150108T022555Z","status":"pending","uuid":"386c9eb0-a6a4-4550-ad03-0731247f68fc"}
  {"description":"test","due":"20150108T230000Z","entry":"20150108T022555Z","modified":"20150108T022555Z","status":"pending","uuid":"386c9eb0-a6a4-4550-ad03-0731247f68fc"}
Hooks: output
  {"status": "pending", "uuid": "386c9eb0-a6a4-4550-ad03-0731247f68fc", "modified": "20150108T022555Z", "due": "20150109T210000Z", "entry": "20150108T022555Z", "description": "test"}
  Default due time has been set.
Hooks: Completed with status 0
 
Configuration override rc.debug.hooks:3
Default due time has been set.
Taskwarrior no longer supports file format 1, originally used between 27 November 2006 and 31 December 2007.
```

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-01-08T02:31:12Z
Modified: 2015-01-25T18:18:30Z
```

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-08T03:05:56Z says:_ 

 The modify command works once you remove spaces from inside the JSON definiton of outputted task. I still consider this a bug, since:

a) It is inconsistent between on-add and on-modify hooks (add accepts spaces in JSON, modify does not)
b) Spaces in JSON definition of a task are perfectly fine.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-08T03:34:37Z says:_ 

 This is not a bug.  Taskwarrior does not accept arbitrarily formatted JSON.  It accepts JSON in the format defined here: http://taskwarrior.org/docs/design/task.html

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-08T10:55:44Z says:_ 

 That design page does not define usage of separators. It only says:

"The format is JSON, specifically a JSON object as a single line of text, terminated by a newline (U+000D). "

This needs to be improved then. Also, I don't see why behaviour of on-add and on-modify hooks should be inconsistent (one accepting separators with spaces, and the other not).

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-01-19T11:43:49Z says:_ 

 I'll have to agree with Tomas here. It is usually a good idea to conform to the [Robustness Principle|http://en.wikipedia.org/wiki/Robustness_principle]:
"Be conservative in what you send, be liberal in what you accept"

Even if you don't agree that Taskwarrior should accept ', ' as a seperator, the fact that on-add hooks are allowed to use them while on-modify hooks aren't is a major discrepancy. People using Python for their hooks will invariably run into this problem, because Python's JSON module uses the ', ' seperator by default.

Note: I realize that applying this very principle to the individual hooks themselves would mean strictly adhering to what Taskwarrior expects. It's probably a good idea to remove as many potential roadblocks as possible though, and the alternative to accepting JSON with ', ' as a seperator would be to include "Taskwarrior is giving me this weird error message when all I was trying to do was write an on-modify hook. I am already sending the JSON as one line and my on-add hook works fine with the same code, what the hell is happening?!" in the FAQ.

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-01-19T12:02:09Z says:_ 

 This is a small hook you can use for testing. It works as either on-modify.json.py or on-add.json.py, but will lead to the error message Tomas mentioned above when run as an on-modify hook. Note that you will need to be running the 2.4.1 branch with the TW-1516 fix.

```
1. !/usr/bin/env python
import json
import sys

for line in sys.stdin:
    t = json.loads(line)
print(json.dumps(t))
```

**Comment by taskwarrior** [comment]
_Renato Alves on 2015-01-19T13:10:57Z says:_ 

 Adding my 2 cents here while agreeing with Tomas and Wim.

I've always been a little uncomfortable with us claiming "we accept JSON but not any kind of JSON".
If we say we use JSON we should be as strict about it as the RFC that defines it (given its standard status).
If we use a JSON variant, then probably we shouldn't be calling it JSON as that confuses people.

Regarding the whitespace issue, according to [this information|http://stackoverflow.com/a/4150626] the standard is tolerant for whitespace.
In our case I guess only the carriage return would cause problems due to several assumptions in the code (something that could also be called a bug).

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-21T14:04:16Z says:_ 

 This is a valid bug, but does not happen in the JSON parser (as I hinted in the description).

Instead, it's a bug in the Hooks::onModify method, where we use a strict substring search to detect if we're processing the task being modified.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-21T14:10:06Z says:_ 

 Patch that fixes the issue and keeps the behaviour of the on-modify hooks the same.

However, I am not sure that the current behaviour is sound, since:
*  nothing is done if user does not return the modified version of the task, but returns something else instead
.. and I am not sure if that is the intention.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-21T16:53:17Z says:_ 

 I thought long and hard, about the issue I raised in the comment above, and I believe this (tbabej-task-10) additional patch is needed.

Consider this on-modify hook, which reads the input, but does not output anything:
```
1. !/usr/bin/python

import json
import sys

for line in sys.stdin:
    t = json.loads(line)
```

(any modify hook which does not output original task is a valid reproducer, but this is a smallest one)

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-01-22T02:09:00Z says:_ 

 Patch contains this:

|    we will remove the data in input[1] in case the current hook did not output a modified version of the current task.

There is no acceptable case where a hook script will fail to honor the interface.  I think you're trying  to change the Hook interface, and I don't want that.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-22T05:46:18Z says:_ 

 Paul, I think you misinterpreted the commit message. I am not trying to change the interface, that was simply describing the current behaviour and why it is wrong.

According to the design page: http://taskwarrior.org/docs/design/hooks.html
a hook is not required to output the task which is being modified. Hook is not even required to output anything.

However, such hook should not break any consequent hooks. And that will happen with the current implementation.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-22T05:53:54Z says:_ 

 Consider the smallest possible example of two hooks as it happens with the current implementation:

Hook 1:
{code}
INPUT: input[0] = original task; input[1] = modified task as changed by the user;
OUTPUT: <nothing>
{code}

Processing of hook 1:
{code}
1.) Placeholder is set in input[1], input[1] = "".
2.) Task with UUID of the original task is searched for to be put in input[1]. No such task is found. input[1] stays "".
{code}

This is where the things get bad.

Hook 2:
{code}
INPUT: input[0] = original verison of the task, input[1] = "" !!
OUTPUT: <hook breaks due to incorrect input>
{code}

So no, I am not trying to change the interface. Completely opposite, I am trying to preserve the hook interface for the second hook, as described in the design page.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-22T05:55:25Z says:_ 

 If hook1 did not output the task being modified, hook2 is still supposed to get that on the input. Therefore the obvious solution is to not replace the value in input[1] by a placeholder, as implemented by patch 10.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-25T18:18:15Z says:_ 

 Per updated hook design page, the second issue is not valid (hooks are always required to output the task being modified/added). Since patch 0009 is applied and pushed, closing the bug.

**Comment by pbeckingham** [comment]
[TW-1504_tbabej-task-0009-Hooks-Make-sure-that-original-task-is-properly-detec.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756373/TW-1504_tbabej-task-0009-Hooks-Make-sure-that-original-task-is-properly-detec.patch.txt)
[TW-1504_tbabej-task-0010-Hooks-Remove-the-placeholder-value-from-the-input-ve.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756375/TW-1504_tbabej-task-0010-Hooks-Remove-the-placeholder-value-from-the-input-ve.patch.txt)
