### ISSUE TITLE
[TW-1511] Project titles not properly parsed if they contain hyphens

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1537]
_Leon Feng on 2015-01-14T17:59:14Z says:_ 

 bq. The expression could not be evaluated.
Thus saith the warrior, when I enter 
`task pro:<any-project-title-with-hyphens-in-it>`.

The end.

(Related to TW-1479, I presume.)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-01-14T17:59:14Z
Modified: 2015-07-16T10:33:28Z
```

**Comment by taskwarrior** [comment]
_Blake Sweeney on 2015-02-18T14:00:57Z says:_ 

 This seems to have gotten worse in 2.4.1. See:

```
$ task add Some example project:an-example
Created task 96.
$ task list project:an-example
The expression could not be evaluated.
task(76975) malloc: error for object 0x7ff4c9c71658: incorrect checksum for freed object - object was probably modified after being freed. set a breakpoint in malloc_error_break to debug
zsh: abort      task list project:an-example
$ task --version
2.4.1
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-02-19T04:28:57Z says:_ 

 I cannot replicate the malloc error on OSX.

Workaround (also puts the filter before the command - good habit):

```
task project.is:an-example list
```

**Comment by taskwarrior** [comment]
_Blake Sweeney on 2015-02-19T14:12:03Z says:_ 

 I also have OSX. When I use `task project.is:an-example` it does work. But when I do:

`task project:an-example list`

I no longer get malloc errors, but now it just says `The expression could not be evaluated.`. I'll use .is for now. Thanks. I think there was something wrong with my machine because I can no longer get a malloc error. Odd.

**Comment by taskwarrior** [comment]
_Dylan Mikus on 2015-05-12T14:47:04Z says:_ 

 Just a note, in v2.4.3, if I have a project "foo-bar" and I type the command:

{code}
task project:foo-bar
{code}

It does nothing except error out and say "Cannot subtract strings".

This error also happens if I surround "foo-bar" in single- or double-quotes.

**Comment by nanangarsyad** [comment]
I got the same message 

> "Cannot subtract strings" 

after I built the latest commit https://github.com/GothenburgBitFactory/taskwarrior/commit/8e20c48df46840a1868fc4d34c4ca303f481d5f6
How to fix this?

Thank you
