### ISSUE TITLE
[TW-1518] Misbehaving hooks silently break task processing

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1544]
_Wim Schuermann on 2015-01-19T15:02:42Z says:_ 

 I'm creating this issue so we don't forget what we talked about on IRC.

\\

This hook:
```
1. !/bin/bash
exit 0
```
Leads to this behavior:
```
bf(at)id:~$ t add testing
Created task 0.
bf(at)id:~$
```
No task is added to the database.

\\

This hook:
```
1. !/bin/bash
exit 1
```
Leads to this behavior:
```
bf(at)id:~$ t add testing
bf(at)id:~$
```
With no task added to the database.

\\

The example hooks are on-add hooks, similar behavior probably exists for other hook variants.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-01-19T15:02:42Z
Modified: 2015-02-14T23:18:36Z
```

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-22T08:24:31Z says:_ 

 Partly duplicate of TW-1502.

The issue here (raised in TW-1504 too) is that according to the hook design page, these hooks are not misbehaving. They are not explicitly required to output the task being modified.

If they are, the design page should be updated.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-01-25T18:31:47Z says:_ 

 Above comment not valid per updated hook design page, this should be checked in the event handlers.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-02-14T23:18:15Z says:_ 

 Both cases verified (first in TW-1502)

{code}
$ task add test
Hook Error: Expected feedback from a failing hook script.
{code}

**Comment by pbeckingham** [comment]
[TW-1518_tbabej-task-0015-Hooks-Make-sure-processing-terminates-if-hooks-are-m.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756379/TW-1518_tbabej-task-0015-Hooks-Make-sure-processing-terminates-if-hooks-are-m.patch.txt)
