### ISSUE TITLE
[TW-1527] Extra spaces added around slashes

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1553]
_Renato Alves on 2015-01-27T16:09:58Z says:_ 

 Taskwarrior adds extra spaces around slashes when quoted.

```
> task add "Hello/there http://bug.tasktools.org"
Created task 1.
> task add Second/Hello http://bug.tasktools.org
Created task 2.

> task
ID Description
 1 Hello / there http: / / bug.tasktools.org
 2 Second / Hello http://bug.tasktools.org
```

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-01-27T16:09:58Z
Modified: 2015-07-13T12:36:38Z
```

**Comment by taskwarrior** [comment]
_Renato Alves on 2015-01-27T16:26:30Z says:_ 

 Test case with positive and negative checks.

Adding description after "--" works as expected.

**Comment by pbeckingham** [comment]
[TW-1527_tw-1527.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756380/TW-1527_tw-1527.t.txt)
