### ISSUE TITLE
[TW-1531] 'task export' should handle recurrence

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1557]
_Tomas Babej on 2015-02-01T12:16:44Z says:_ 

 The 'task export' command does not generate new recurrent tasks.

This complicates things, since any external library/tool using 'task export' to get data from taskwarrior (which is the recommended way) will not get the most current dataset.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-02-01T12:16:44Z
Modified: 2015-02-14T01:31:26Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-02-14T01:31:26Z says:_ 

 Good idea.

**Comment by pbeckingham** [comment]
[TW-1531_tbabej-task-0016-CmdExport-Generate-recurrent-tasks.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756381/TW-1531_tbabej-task-0016-CmdExport-Generate-recurrent-tasks.patch.txt)
