### ISSUE TITLE
[TW-1533] dateformat confusion, regress tests

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1559]
_Peter Rochen on 2015-02-02T09:29:52Z says:_ 

 Because date input is very confusing, i run some tests with dateformats come to mind.
It helped me a lot, maybe others too.
See attachement!
I tested version
2.2.0
2.3.0
2.4.0
2.4.1-dev
2.4.1-dev configured with date.iso=no.

"--" means failure.

Note to dateformats without y,Y: year is adjusted to current year.

I am courious why isn't there e.g. YYYY-MM-DDThh in ISO-8601?
Not declared the standard or not implemented in taskwarrior? I didn't find the answer.
Knows anybody the reason? It seems unambiguous.
If they would rely on letter "T" more, you can imagine more brave and short formats too.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-02-02T09:29:52Z
Modified: 2015-07-23T23:26:16Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-02-02T17:52:03Z says:_ 

 See this doc for full details:
http://taskwarrior.org/docs/dates.html

**Comment by taskwarrior** [comment]
_Peter Rochen on 2015-02-02T19:14:49Z says:_ 

 Sorry, maybe i was misunderstable.
I read that page multiple times, but for me wasn't clear the behaviour of the date input.
That is why i felt the need run some tests.
I wrote the tests, because i was very confused, what works, what not works.

I read this:
" you have full control over the format entered "
" You can specify date, or date + time, but whatever you specify must match your rc.dateformat setting. "
and didn't understand why dateformat=yMD-H didn't work with 2.4.

For me was very big satisfaction to see the results of tests like these in attachement.
Now, I'm happy to see what can i use and what not.

" The ISO-8601 standard defines an unambiguous format for specifying date and time around the world. "
I see.

" Future releases of taskwarrior will not need rc.dateformat for date/time input. "
I see, but i have mixed feelings.


TW-1522 quote: "Note that using dateformat is deprecated, and will one day not be supported. But not yet."
date.iso=no: "This is because some of you have 'dateformat' settings that conflict."
Again, until i didn't read the latter sentence, i was very confused. Some dateformat value was good, some not.
Maybe will come some reports from other people in future in this theme.

So a BIG thank you for the date.iso=no option!

Didn't wonder other people, that for example YYYY-MM-DDThh is missing from ISO-8601?

Otherwise, is there any interesting run the tests with plus dateformats too?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-07-19T22:21:47Z says:_ 

 At this point in the 2.4.5/2.5.0 development, the non-extended ISO date format support is removed, so we do not have `YYYYMMDD` but we retain `YYYY-MM-DD`, because the former looks too much like an integer, and our grammar is massively ambiguous.

Please note that 'deprecated' does not mean removed, it means discouraged, and it means that further enhancements are unlikely.

I am now looking to identify any issues that remain with TW-1533, and fix them, otherwise close the case.  Do you have outstanding issues?

**Comment by taskwarrior** [comment]
_Peter Rochen on 2015-07-20T01:27:30Z says:_ 

 I collected 140 dateformat variants (and there are more candidates) to test.
See new attachement.
In some cases worth using faketime (not yet done).

I surprised. 2.4.5-dev works with all of the dateformat without date.iso=no.
Are my test results correct?

I try to understand your comment, but i'm not sure.
It isn't clear for me, what is the future of the tweaked dateformats.

I see your aim an overall testing of taskwarrior.
Are my tests suit?
Maybe you want test dateformat variants, too?

People sometimes open issues in dateformat related area (eg: TW-1552).
So you could public results like this, anticipation recurring issues.
(I spotted some inconsistency between my two table, eg in YMD-HN, so be aware.)

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-07-23T22:42:56Z says:_ 

 Your test results are good, thanks for the data.

I am building unit tests that cover all the dateformat components (Y, y, M, m, ...) so that the parsing of each one can be tested.  I will not be doing combinatorics like your test, I'm not convinced it's necessary given how the date parsing is done.

When this is done, I'll close this issue, as there is no remaining problem that `rc.date.iso=off` does not solve.

**Comment by pbeckingham** [comment]
[TW-1533_dateformat-test-2015-07-20.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756382/TW-1533_dateformat-test-2015-07-20.txt)
[TW-1533_dateformat-test-2015.01.27.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756383/TW-1533_dateformat-test-2015.01.27.txt)
