### ISSUE TITLE
[TW-1534] Urgency coefficient for user project disables 'info' output

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1560]
_Martin Michel on 2015-02-03T23:07:30Z says:_ 

 I have some tasks belonging to a project:
{code}
task-2.4.0 rc:./testrc 
Using alternate .taskrc file /home/martin/tmp/task_bug/testrc

ID Age Deps    Project                          Tag     Recur Description                      Urg  
 2 4mo         033a19f3c2ca32c46349066324a4d804 Arduino       1bbbb20cbf22ca89db5c167c0eeb03ed  5.54
 3 4mo         033a19f3c2ca32c46349066324a4d804               2ddea87e28b499df9467940db6c79672  4.74
 5 4mo         033a19f3c2ca32c46349066324a4d804               0dc681bc887600010d5814afc8b3fbc6  4.74
 1 4mo 2 3 4 5 033a19f3c2ca32c46349066324a4d804               f52f679a4ea6277628e93f3d4268db4d -0.26
 4 4mo 5       033a19f3c2ca32c46349066324a4d804               3b4cc70016883bd0248f58fcf36d48ab -0.26
 6 4mo 1       033a19f3c2ca32c46349066324a4d804               0dc681bc887600010d5814afc8b3fbc6 -8.26

6 tasks

{code}

 I want to reduce urgency coefficient by setting the following rule in .taskrc (-->see testrc in attachement)

{code}
urgency.user.project.033a19f3c2ca32c46349066324a4d804.coefficient=-5.0
{code}
The *info* command fails in 2.4.0:
{code}
task-2.4.0 rc:./testrc 6 info
Using alternate .taskrc file /home/martin/tmp/task_bug/testrc
Unknown error.
{code}
but works in 2.3.0:
{code}
task rc:./testrc 6 info
Using alternate .taskrc file /home/martin/tmp/task_bug/testrc

Name                 Value                               
ID                   6
Description          0dc681bc887600010d5814afc8b3fbc6    
Status               Pending
Project              033a19f3c2ca32c46349066324a4d804    
This task blocked by 1 f52f679a4ea6277628e93f3d4268db4d
UUID                 c9d8f9fd-5dc4-463d-8c39-abcc71dc41eb
Entered              2014-09-21 21:58:38 (4 mths)
Urgency              -8.26                               
Last modified        2014-09-21 22:06:00 (4 mths)
{code}

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-02-03T23:07:30Z
Modified: 2015-02-14T17:47:13Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-02-07T19:43:59Z says:_ 

 Thanks for reporting this.  Great test case.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-02-14T17:40:06Z says:_ 

 This was an interesting bug.  When the project name length + len("PROJECT ") > 20, the text.cpp rightJustify() function hangs.  

I have reimplemented the urgency details as a separate table, which is independently justified, and avoids this problem.

**Comment by pbeckingham** [comment]
[TW-1534_pending.data.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756384/TW-1534_pending.data.txt)
[TW-1534_testrc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756385/TW-1534_testrc.txt)
