### ISSUE TITLE
[TW-1538] 'Scheduled' field in plain text and in JSON is differs

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1564]
_Eugene on 2015-02-13T13:50:32Z says:_ 

 Steps to reproduce this bug:
1) Create new task with "scheduled" field: `task add 'Test task' scheduled: 15.02.2015`
2) View newly created task as text: `task 107 information` (insert your task number instead of "107").

```Name          Value
* ------------ ------------------------------------
ID            107
Description   Test task                           
Status        Pending
Entered       13.02.2015 16:45:08 (34 seconds)    
Scheduled     15.02.2015 00:00:00
Last modified 13.02.2015 16:45:08 (34 seconds)    
UUID          a84f4c17-e600-47da-a200-ebc84f9bf078
Urgency       0```

3) View task as JSON: `task 107 export`.
```
\{"id":107,
"description":"Test task",
"entry":"20150213T134508Z",
"modified":"20150213T134508Z",
"scheduled":"20150214T210000Z",
"status":"pending",
"uuid":"a84f4c17-e600-47da-a200-ebc84f9bf078",
"urgency":"0"\}
```


Done! As you can see, "scheduled" field in step 2 is 15.02.2015 and same field in step 3 is 14.02.2015. =(

I'm attach my *.taskrc* file. Hope, it will be useful.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-02-13T13:50:32Z
Modified: 2015-02-13T15:18:57Z
```

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-02-13T15:16:12Z says:_ 

 This is not a bug. Exported value is a timestamp in UTC (note the trailing Z). Judging by the offset, you're probably in GMT+3 timezone.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-02-13T15:17:03Z says:_ 

 Not a bug.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-02-13T15:18:57Z says:_ 

 I closed the issue for now. Thanks for letting us know.

**Comment by pbeckingham** [comment]
[TW-1538_.taskrc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756387/TW-1538_.taskrc.txt)
