### ISSUE TITLE
[TW-1546] column type due.remaining breaks colors on due tasks

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1572]
_Renato Alves on 2015-02-17T15:43:09Z says:_ 

 Using the default theme and the next report, any overdue tasks will show nothing (text and color) in the due column.

```
% task add due:yesterday -- one
% task add due:today -- two
% task add due:tomorrow -- three
% task add -- four

% task next
ID Age Recur Due     Description Urg 
 1 2s        {empty} one         9.56
 2 2s        {empty} two          9.1
 3 2s        8 hours three       8.64
 4 1s                four           0
```

The line containing task "two" the alternating color pattern is also gone in the column.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-02-17T15:43:09Z
Modified: 2015-02-19T04:14:27Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-02-19T02:19:18Z says:_ 

 I see the blank spot.  Interesting...

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-02-19T04:06:25Z says:_ 

 An easy way to make this visible is:

```
$ task rc._forcecolor:on next | sed 's/31/31;44/g'
```

That sed command changes 'red' to 'red on blue'.

**Comment by pbeckingham** [comment]
![tw-1546_screenshot_2015-02-18_11-32-25_749921534](https://user-images.githubusercontent.com/7963/36643586-8981cf4c-1a1b-11e8-9e81-1254b069877c.png)
