### ISSUE TITLE
[TW-101] New description column format: Truncated WITH annotation count

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#158]
_Max Muller on 2012-12-15T17:01:06Z says:_ 

 For various reasons, I prefer in some circumstances to ensure that each task doesn't take more than one line in reports. 

Long task descriptions and the presence of annotations are the main (only?) reasons why tasks might take up more than one line, but fortunately, there are two description column formats that are useful for preventing that: 

* The 'truncated' format: It cuts of the task description with an elipse ("...") if the descriptions is too long for one line. However, this format gives no indication if a task has annotations.
* The 'count' format: Saves spaces by showing a count of the number of annotations in brackets ("[2]") instead of the annotations themselves. However if the task description is too long, tasks will still spill over onto more than one line. 

FEATURE REQUEST: I think it would be useful to create a new description column format contains BOTH the 'truncated' and 'count' features. 

That would enable users to create reports in which all the following are possible at the same time:

* Tasks would only take one line under all circumstances
* Users could tell at a glance if the description had been truncated
* Users could tell at a glance if a task had annotations.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-12-15T17:01:06Z
Modified: 2014-08-23T16:29:53Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-12-15T17:17:05Z says:_ 

 Very reasonable.  Thanks for the request.

**Comment by taskwarrior** [comment]
_atomicules on 2014-08-13T19:52:21Z says:_ 

 I'm attaching a small patch that provides this, based off the  2.3.0 master branch.

I actually also wanted this functionality and created a modification before seeing this issue; I was about to create a new issue, but thought I'd better check if there was anything similar already logged and found this.

**Comment by taskwarrior** [comment]
_atomicules on 2014-08-13T19:55:59Z says:_ 

 Patch as mentioned. Feedback welcome.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-08-14T22:24:34Z says:_ 

 Thank you for the patch, but this is not (yet) a good patch:

Patches should be based off the current development branch (2.4.0) in the repository, and should include:
*  A properly formatted git patch (patch is instead a diff)
*  Updated documentation, including man pages, ChangeLog, NEWS etc (patch contains none)
*  Updated or added unit tests (patch contains none)
*  Correct C++ (patch has missing braces)

**Comment by taskwarrior** [comment]
_atomicules on 2014-08-15T07:08:41Z says:_ 

 Hi Paul. Thanks very much for the response. I will redo the patch including all the requirements in your comment and then update here when complete in a few days time (hopefully; Figuring out unit testing might take be a bit longer).

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-08-16T14:21:41Z says:_ 

 Thanks!  Regarding unit tests, there is a 'template.t' file that is a good general starting point for writing a new test.  In this case, a test would probably do this:
*  define a custom report that uses the new format
*  create a task
*  annotate the task
*  run the custom report
*  verify that the displayed truncation and count are as expected

If Python is not your thing, then let us know, and we can create this test.

**Comment by taskwarrior** [comment]
_atomicules on 2014-08-17T21:30:45Z says:_ 

 Please review the attached and see if this is more along the lines of what is required. Note:
*  I could not find the issue with missing braces you mentioned. It compiles fine. I've also tried to check it with Syntastic in Vim. And I've stared at it for some time. So apologies if they are still missing, but I just couldn't spot this issue. Is it just a stylistic issue I've missed?
*  I've not amended the man files because as far as I can tell the column formats/styles are not mentioned in the man pages, just via the "task columns" command. I did change the other files you mentioned.
*  I have added a unit test (that passes) that tests the new format/style in various ways

Also, in order to redo this patch against the 2.4.0 development branch I obviously had to build the development branch. In doing so I found that TD-55 also applied to NetBSD so there is a separate commit (but same patch file) to fix that as well.

**Comment by taskwarrior** [comment]
_atomicules on 2014-08-21T21:33:18Z says:_ 

 Hi. Just to add that ran the file through cppcheck and found no issues with braces so as far as I can tell it should be ok.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-08-21T21:45:12Z says:_ 

 The indentation here:

```
    if (annos.size ())
      annos_count = " [" + format ((int) annos.size ()) + "]";
      int len_annos = utf8_width (annos_count);
      len += len_annos;
```

Looks like Python, implying there are braces needed:

```
    if (annos.size ())
    {
      annos_count = " [" + format ((int) annos.size ()) + "]";
      int len_annos = utf8_width (annos_count);
      len += len_annos;
    }
```

Also the 'len_annos' variable is only used once.

**Comment by taskwarrior** [comment]
_atomicules on 2014-08-21T22:30:57Z says:_ 

 Hi Paul,

```
The indentation here ... Looks like Python, implying there are braces needed
```

Thanks! It is obvious now you've pointed it out, but I just couldn't see that for looking.

```
Also the 'len_annos' variable is only used once
```

It's used on line 288:

{code}
    len += len_annos
{code}

and line 292:

{code}
    lines.push_back (color.colorize (description.substr (0, width - len_annos - 3) + "..." + annos_count));
{code}

I thought this was tidier, but I could change this and remove `len_annos` and just use `utf8_width (annos_count)` directly?

In the attached updated patch I have fixed the braces issue, but retained `len_annos` for now.

**Comment by taskwarrior** [comment]
_atomicules on 2014-08-23T11:14:27Z says:_ 

 Hi Paul,
*  Added "thanks to ..." into Changelog
*  I was already in the AUTHORS file
*  I have renamed the style as suggested (and updated the test, etc to match)

See latest attached patch.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-08-23T16:08:42Z says:_ 

 Thank you atomicules - that's a great patch.  Comitted and pushed to the 2.4.0 branch.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-08-23T16:10:14Z says:_ 

 Thank you for sticking with this, following our difficult process, and giving us a nice new feature.  Much appreciated.

**Comment by taskwarrior** [comment]
_Max Muller on 2014-08-23T16:29:53Z says:_ 

 Yes, Thank you for implementing this useful feature! It is so satisfying to watch such a vibrant project as Task Warrior get better and better by the day. I echo Paul's appreciation.

**Comment by pbeckingham** [comment]
[TW-101_truncated+count.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755537/TW-101_truncated.count.diff.txt)
[TW-101_tw101-2014-08-21.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755538/TW-101_tw101-2014-08-21.patch.txt)
[TW-101_tw101-2014-08-23.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755539/TW-101_tw101-2014-08-23.patch.txt)
[TW-101_tw101.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755540/TW-101_tw101.patch.txt)
