### ISSUE TITLE
[TW-1562] start and stop time offsets (start:now-30min)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1588]
_David Patrick on 2015-03-02T09:25:34Z says:_ 

 If you realize that you have been working on something for the last half an hour, and you wish you had "started" that task, it can be done retroactively with:

tw 142 mod start:now-30min

and the start-time will be set to half an hour ago. (caveat: this will fail if the task entry time is later (more recent) than that) 

This feature request is to enhance the "start" and "stop" commands to allow for offsets directly, In other words, to allow the command above to be represented as:

task 142 mod start:now-30min

and stopped with

task 142 mod stop:now-10min

allowing users to more accurately record task activity.

This may require task to perform some special magic: if the task-start-time is earlier than the task-entry-time (if you created the task five minutes ago, and you want to mark it as started an hour ago) then the entry time should be adjusted along with the start time.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-03-02T09:25:34Z
Modified: 2015-03-07T06:06:48Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2015-03-02T09:52:31Z says:_ 

 should be noted, unlike start:time, there is no actual stop:time attribute, so 'task 142 mod stop:now-30min' needs to be interpreted. 

If the "start" and "stop" commands can take < mods > (and they can) then the following commands should work:

task 142 start start:now-30min

starts the task, but doesn't offset it, unlike "mod"..

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-03-02T20:49:25Z says:_ 

 Right, there is no "stop" attribute, so that won't work.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-03-02T21:19:25Z says:_ 

 I think we should simply allow optional offset for start and stop commands:

{code}
$ task 2 start -30min
$ task 2 start +30min
$ task 2 stop -30min
$ task 2 stop +30min
{code}

To make things more simple, we may even support minutes only:

{code}
$ task 2 start -30
$ task 2 start +30
$ task 2 stop -30
$ task 2 stop +30
{code}

With this syntax, there's no need to parse the time units, and still the most useful use case is covered. If anybody needs to do a more complex modification, he can still use the task <id> mod command.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-03-02T21:24:41Z says:_ 

 Given that Taskwarrior does not track time, I'd say this is a non-problem.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-03-02T21:28:04Z says:_ 

 That's true, but there's still value in keeping the data correct, isn't it? Also, the functionality is supposed to be covered by hooks - which would get it wrong too.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-03-02T21:36:21Z says:_ 

 Well, start/stop is meant to put a task in, and remove it from, an active state.  Correcting the activation time is already possible.  There is no stop time, so there is nothing to correct - it's just the removal of the start time.  There is nothing to correct.

There is the annotation timestamp, if it was made, but that just represents the time when stop was run, and as such is correct, and doesn't need modification for a feature we don't support.

If a hook wants to modify any annotation timestamps, then it can but I don't see the point in adding new syntax for a feature we do not support.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-03-02T21:40:49Z says:_ 

 Sorry, I confused the behaviour of 'stop' and 'done' here (there's 'end' attribute which tracks the completion time).

What I wanted to propose was simply:

{code}
$ task 2 start -30
$ task 2 done -30
{code}

which would set the 'start' or 'end' time values 30 minutes back from now.

**Comment by taskwarrior** [comment]
_David Patrick on 2015-03-07T06:05:43Z says:_ 

 For my purposes (conveniently starting/ stopping/ logging active times, with offsets for convenience) this has been addressed neatly with the Ledger Time Tracking Hook (https://gist.github.com/wbsch/d977b0ac29aa1dfa4437) so I'm closing this issue.

**Comment by taskwarrior** [comment]
_David Patrick on 2015-03-07T06:06:48Z says:_ 

 fixed with https://gist.github.com/wbsch/d977b0ac29aa1dfa4437, bqf's Ledger Time Tracking Hook

**Comment by johnyoonh** [comment]
I know that the development of taskwarrior has slowed down a bit, but this was also how I expected the program to accept offsets. This syntax would help eliminate the need for additional time tracking app like timewarrior.
