### ISSUE TITLE
[TW-1571] Storing context in a environment variable

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1597]
_Tomas Babej on 2015-03-12T08:07:06Z says:_ 

 Currently, the context is stored in a configuration variable in .taskrc. This has the guarantee of only one context being set at a time on one machine.

However, there are use cases where storing context in a environment variable might be preferable:

* Allows running multiple shells along with each other with various contexts (i.e different tmux/screen sesssions would be able to have different contexts)
* Bash scripts that use context would not step on each other's toes if run concurrently in different shells (i.e. executed via cron)
* Context setting not persistent across reboot (some users might prefer that)
* Users that store .taskrc in .dotfiles git repo, wouldn't get false positive messages about .taskrc being modified

EIther storing context in .taskrc or in environment variable should be supported, not both. A configration setting, e.g rc.contextstore with possible values of "configuration" and "environment" (defaulting to current behaviour, that is "configuration") should set the context store being used.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-21T15:20:32Z says:_ 

 Ivan - I think your patch (above) needs either to be added as an attachment, or surrounded by "```" markers, to preserve the formatting.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-21T15:21:18Z says:_ 

 I meant "{ n o f o r m a t }" markers (remove the spaces)

**Comment by taskwarrior** [comment]
_Ivan Čukić on 2016-02-21T15:35:51Z says:_ 

 Thanks, I realized that formatting ruined it a bit late - and tried <code>, backticks.

I've also set up a temporary fork at evil github at https://github.com/ivan-cukic/taskwarrior-fork

```
diff --git a/src/CLI2.cpp b/src/CLI2.cpp
index 6e37b11..710dbb6 100644
* -- a/src/CLI2.cpp
+++ b/src/CLI2.cpp
@@ -35,6 +35,8 @@
1. include <util.h>
1. include <i18n.h>
 
+#include <CurrentContext.h>
+
 extern Context context;
 
 // Overridden by rc.abbreviation.minimum.
@@ -608,7 +610,7 @@ void CLI2::addContextFilter ()
     return;
 
   // Detect if any context is set, and bail out if not
*   std::string contextName = context.config.get ("context");
+  std::string contextName = getCurrentContext (context);
   if (contextName == "")
   {
     context.debug ("No context.");
diff --git a/src/CurrentContext.h b/src/CurrentContext.h
new file mode 100644
index 0000000..8dc7982
* -- /dev/null
+++ b/src/CurrentContext.h
@@ -0,0 +1,20 @@
+/*
+ * CurrentContext.h
+ * Copyright (C) 2016 Ivan Čukić <ivan.cukic(at)kde.org>
+ *
+ * Distributed under terms of the MIT license.
+ */
+
+#ifndef CURRENTCONTEXT_H
+#define CURRENTCONTEXT_H
+
+inline std::string getCurrentContext (Context &context)
+{
+    // If the currently set context was deleted, unset it
+    const char * currentContextOverride = getenv ("TASK_CONTEXT");
+
+    return currentContextOverride ? std::string (currentContextOverride)
+                                  : context.config.get ("context");
+}
+
+#endif /* !CURRENTCONTEXT_H */
diff --git a/src/commands/CmdContext.cpp b/src/commands/CmdContext.cpp
index ac168bd..a61b0b1 100644
* -- a/src/commands/CmdContext.cpp
+++ b/src/commands/CmdContext.cpp
@@ -35,6 +35,8 @@
1. include <CmdContext.h>
1. include <CmdConfig.h>
 
+#include <CurrentContext.h>
+
 extern Context context;
 
 ////////////////////////////////////////////////////////////////////////////////
@@ -201,6 +203,8 @@ int CmdContext::deleteContext (const std::vector <std::string>& words, std::stri
     rc = CmdConfig::unsetConfigVariable(name, confirmation);
 
     // If the currently set context was deleted, unset it
+    // We are not using the environment variable override here,
+    // but the actual configured value
     std::string currentContext = context.config.get ("context");
 
     if (currentContext == words[1])
@@ -247,7 +251,7 @@ int CmdContext::listContexts (std::stringstream& out)
     Color label (context.config.get ("color.label"));
     view.colorHeader (label);
*     std::string activeContext = context.config.get ("context");
+    std::string activeContext = getCurrentContext (context);
 
     for (auto& userContext : contexts)
     {
@@ -323,7 +327,7 @@ int CmdContext::setContext (const std::vector <std::string>& words, std::strings
 //
 int CmdContext::showContext (std::stringstream& out)
 {
*   std::string currentContext = context.config.get ("context");
+  std::string currentContext = getCurrentContext (context);
 
   if (currentContext == "")
     out << STRING_CMD_CONTEXT_SHOW_EMPT << "\n";
```

**Comment by taskwarrior** [comment]
_Tomas Babej on 2016-03-08T15:36:38Z says:_ 

 Thanks for taking the time to implement this, works quite nice. Finally I can incorporate context into my tmuxinator setup :)

**Comment by taskwarrior** [comment]
_Wael Nasreddine on 2017-06-27T17:11:41Z says:_ 

 (at)paul I'm trying to understand your reservation over this feature, can we agree on a middle ground? Perhaps allow overriding of context via the environment variable on top of setting it in the taskrc file?

My use case is that I use a concept of profiles for my shell, so when I switch to personal (or work), all my tools (Git, AWS, etc..) gets affected. I would like to be able to switch the context using an environment variable regardless of what is the persistent context is (which would be none for me)

**Comment by taskwarrior** [comment]
_Wael Nasreddine on 2017-06-27T18:11:40Z says:_ 

 For anyone using the patch, I've updated for Task 2.5.2 and hosted it in the AUR package (Arch Linux) task-context-env here https://aur.archlinux.org/cgit/aur.git/tree/env.patch?h=task-context-env

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-06-28T01:41:39Z says:_ 

 For any readers: There is no Taskwarrior 2.5.2 release, the patch is not merged, has not been tested and is not supported.

Wael Nasreddine, I would appreciate you not misrepresenting our work.  Please withdraw that package.

**Comment by taskwarrior** [comment]
_Wael Nasreddine on 2017-06-28T03:28:23Z says:_ 

 (at)paul that was a typo, I meant 2.5.1 release, and the package released on the open Arch Linux User Package repository, I'm not trying to hack anyone! Please see it here https://aur.archlinux.org/packages/task-context-env/

As for the patch itself, it's Ivan Čukić's patch rebased for 2.5.1 release.

Are you open to discuss possible implementation or should I not bother and maintain it myself?

**Comment by taskwarrior** [comment]
_Wael Nasreddine on 2017-06-28T05:40:18Z says:_ 

 This was discussed on IRC (see log [here|https://botbot.me/freenode/taskwarrior/2017-06-28/?msg=87870774&page=1]). The patch is really unnecessary as it can be easily achieved with a shell function like the one following.

{code}
function task() {
  command task rc.context=personal "$@"
}
{code}

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-06-30T00:03:53Z says:_ 

 Nice.  Thanks Wael!

**Comment by sdondley** [comment]
Just a little more on this to help others who may not be super proficient with bash (like me).

You can do:

```
function task() {
   command task rc.context=$TWCONTEXT "$@"
}
```
Then on the command line:

`TWCONTEXT=peronsal` or `TWCONTEXT=work`, etc.

**Comment by awilkins** [comment]
Version 2.6 makes progress here

Environment variables are supported in `.taskrc`, so you can do e.g.

```ini
context=$TW_CONTEXT
```

Alongside this, version 2.6 will write elements of your current context to tasks as discussed in #1955 ; 

Combined with a means of setting environment automatically per folder like `direnv` you can do `task add` in a folder and have it pick up the tags and attributes for a specific context linked to the folder.

Because of these new features it would still be nice if you could **override** context with an environment variable though ; this means you could switch context views in a task shell like `vit` which reconfigures the context variable in `.taskrc` but still have e.g. `task add` drop tasks into a context defined by the folder you are in, and `task next` do the same ; just report stuff relevant to a context you're in because of where your shell is.

Maybe a separate read and write context would be nice as well, now that context implies setting attributes and tags on tasks.
