### ISSUE TITLE
[EX-15] Support 'random' command

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#16]
_Paul Beckingham on 2009-05-25T21:35:41Z says:_ 

 Support random command to display a random task.  Like pulling a task out of a hat.

David J. Patrick

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-05-25T21:35:41Z
Modified: 2014-02-20T19:06:08Z
```

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2010-05-29T13:45:10Z says:_ 

 Seems to me this will be another good thing to be done with a hook.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-04-24T19:17:13Z says:_ 

 Perfect extension.

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2014-02-20T19:06:08Z says:_ 

 Suitable for Pomodoro Technique.

**Comment by pbeckingham** [comment]
No plans to implement.
