### ISSUE TITLE
[TW-1577] Add proxy support for task sync

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1603]
_ScrumpyJack on 2015-03-17T13:25:49Z says:_ 

 Would be nice to be able to use local proxy settings when syncing to taskserver when behind a cooporate proxy.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-03-17T13:25:49Z
Modified: 2017-12-02T18:58:50Z
```

**Comment by taskwarrior** [comment]
_Michele Vetturi on 2015-04-30T15:11:16Z says:_ 

 Yeah! It would be really useful to have SOCKS support!

**Comment by taskwarrior** [comment]
_Stefan Betz on 2015-05-02T17:59:09Z says:_ 

 SOCKS, the preferred dynamic proxy method of SSH would be real nice.

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-05-02T19:48:24Z says:_ 

 Have you tried using tsocks or ProxyChains? Those are two programs you can use to make any (dynamically linked) program send data over proxies by using Linux's LD_PRELOAD. Most Linux distros have them in their package repos. I'm sure there are similar ways to force proxy usage for OSX and Windows.

I'm mentioning this because it is pretty unlikely that Taskwarrior is going to gain direct support for SOCKS proxies unless someone submits a patch for it. And with the help of tools like the ones mentioned above, no code needs to be written at all. Less complexity, same result.

**Comment by taskwarrior** [comment]
_Michele Vetturi on 2015-05-04T09:27:57Z says:_ 

 I'm using Taskwarrior in a Cygwin environment which is not so friendly with tsocks and other similar tools I tried. Packages for Cygwin do not exist and sources do not compile at all on Cygwin).

Moreover, I'm using a business laptop behind a corporate firewall. Some tools cannot be installed without breaking corporate policies and enable support for task server protocol through a corporate firewall can be very hard.

I think to proxy connection support as a core feature, as for most applications around the world.

Thanks

**Comment by taskwarrior** [comment]
_Obed N Munoz on 2017-06-20T04:23:34Z says:_ 

 With the current implementation is there a solution for setting a proxy?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-06-20T12:24:05Z says:_ 

 No one has contributed this, and this ticket remains open.

**Comment by taskwarrior** [comment]
_Obed N Munoz on 2017-06-20T16:26:50Z says:_ 

 Ok, gotcha, I think this is a good opportunity to start collaborating with. Thanks

**Comment by taskwarrior** [comment]
_Tomas Babej on 2017-06-20T16:44:59Z says:_ 

 Please note that using proxychains / tsocks as Wim suggests is still a completely resonable option, as long as you have administrative control over your station. I.e. I can easily sync my tasks over TOR using:

```
torify task sync
```

Proxychains (after writing the relevant config) is just as easy:

```
proxychains4 task sync
```

**Comment by taskwarrior** [comment]
_Peter Cummuskey on 2017-11-23T21:33:05Z says:_ 

 It'd be nice to be able to set the external command or wrapper program used for sync, so the task command didn't need to be prefixed. e.g.

{code}task config sync.wrapper proxychains4{code}

Alternately, make the alias configuration more powerful by being able to reference internal commands such that you could configure command overrides like this:

{code}task config alias.sync "execute proxychains4 task &sync"{code}

The second option is probably a bit more generally useful.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-12-02T18:58:50Z says:_ 

 Thank you Peter, good suggestion.

**Comment by heliocarbex** [comment]
I would like some orientation to implement this feature. Does you give me the best way to solve this?

**Comment by djmitche** [comment]
Closed because taskserver/taskd is no longer supported.
