### ISSUE TITLE
[TW-1605] Japanese translation for Taskwarrior

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1629]
_ribbon on 2015-04-28T21:56:41Z says:_ 

 Japanese translation for taskwarrior.
This is not complete.
Japanese KANJI character (or some east asian language) uses wide character (2 or more bytes), sometimes side effects occur in the display.
So、I translated some part that side effect may not occur.
I

**Comment by pbeckingham** [comment]
[TW-1605_jpn-JPN.h.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756393/TW-1605_jpn-JPN.h.txt)
