### ISSUE TITLE
[TW-1615] Japanese translation for Taskwarrior(150513)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1639]
_ribbon on 2015-05-12T14:17:00Z says:_ 

 Japanese translation for taskwarrior (150513 version).
Some translation add/modified.

**Comment by pbeckingham** [comment]
[TW-1615_jpn-JPN.h.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756395/TW-1615_jpn-JPN.h.txt)
