### ISSUE TITLE
[TW-1617] Can't search for multi-word project

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1641]
_Audrey Easterday on 2015-05-13T20:07:46Z says:_ 

 I create a project called 'Mike Visit 2015'.  

However, when I try to search for tasks in the project by typing -   

task project:'Mike Visit 2015' 
* 
 I get an error that says "The expression could not be evaluated".

I was going to ask this on the question board and not post it as a bug, but I can't seem to log in to the question board even though it will let me log in to this part of Jira just fine.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-05-14T01:41:21Z says:_ 

 Thanks for the report.

Yes, the answers.tasktools.org site has lost it's authorization to get into the bug database system, and it's proving a pain to fix.  Apologies.

**Comment by tbabej** [comment]
Regression in 2.5.2, 2.6.0.

**Comment by tbabej** [comment]
Actually this is resolved on 2.6.0.

**Comment by mrossinek** [comment]
Ah yes. This was mainly about the clarifying the syntax which happened in https://github.com/GothenburgBitFactory/taskwarrior/commit/d85901e7ff0ce0aec8e6090dd601552b08f61007, right?
