### ISSUE TITLE
[TW-1619] fish completion contain backspaces in fish master version

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1643]
_Johannes Wienke on 2015-05-15T17:40:06Z says:_ 

 The fish shell completions are broken when using the master version of fish shell. The subcommand names are incorrectly separated from their respective description strings and everything contains backspaces:

```
languitar(at)miles ~> task ghistory.
ghistory.annualtShows\ a\ graphical\ report\ of\ task\ history,\ by\ year  ghistory.monthlytShows\ a\ graphical\ report\ of\ task\ history,\ by\ month
```

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-05-15T17:40:06Z
Modified: 2015-07-19T20:48:29Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-07-19T20:48:29Z says:_ 

 Thanks for the patch, it is applied and pushed.  You are now in AUTHORS file.

**Comment by pbeckingham** [comment]
[TW-1619_0001-fish-completion-use-literal-tabs-in-sed-calls.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756398/TW-1619_0001-fish-completion-use-literal-tabs-in-sed-calls.patch.txt)
