### ISSUE TITLE
[TW-1630] "Due" parsing behavior seems inconsistent

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1654]
_Jim B on 2015-07-08T07:48:02Z says:_ 

 This behavior occurs on my Cygwin install, as well as the online demo at wbsch.de.

I can't make sense of the way "due" modifiers are working here:

I am attempting to create a task which is due in 7 days (i.e., "now" + 7 days) and then searching for it using "due" modifiers -- in this example, I expect the output to show me all tasks which are due in 10 days or less.

demo(at)taskwarrior:~$ task add due:7d TEST TASK
Created task 1.
demo(at)taskwarrior:~$ task due.before:10d
[task next due < 10d]
No matches.
demo(at)taskwarrior:~$ task due.after:10d
[task next due > 10d]

ID Age Due    Description Urg 
 1 12s 6 days TEST TASK    5.6

1 task
demo(at)taskwarrior:~$ task 1 mod due:15d
Modifying task 1 'TEST TASK'.
Modified 1 task.
demo(at)taskwarrior:~$ task
[task next]

ID Age Due     Description Urg 
 1 57s 2 weeks TEST TASK    2.4

1 task

I think the example shows that when a task is created or modified, reasonable behavior occurs; but when searching/matching tasks, something completely different happens as though "due.before" and "due.after" are doing the opposite of what one would expect.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-07-08T07:48:02Z
Modified: 2015-08-05T21:47:32Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-08-05T21:01:54Z says:_ 

 Thanks!

**Comment by mrossinek** [comment]
There are some remaining issues with this meaning that this issues should be re-opened for now.

**Comment by timokau** [comment]
`due.before:3d` worked for me in 2.5.1 and now no longer works in 2.5.2. It is returning no results although there should be some. I'm not sure if that is the same problem that was described in this issue, since it worked in 2.5.1.

**Comment by timokau** [comment]
As a workaround: `due.before:now+3d` still works.

**Comment by tbabej** [comment]
This is currently describing same issue as #2390.
