### ISSUE TITLE
[TW-1632] Japanese translation for Taskwarrior(150713)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1656]
_ribbon on 2015-07-13T12:46:54Z says:_ 

 Japanese translation for taskwarrior (150713 version).
Some translation add/modified.
Please update jpn-JPN.h(TW-1615 version).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-07-13T12:46:54Z
Modified: 2015-07-13T13:39:04Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-07-13T13:39:04Z says:_ 

 Thank you!

**Comment by pbeckingham** [comment]
[TW-1632_jpn-JPN.h.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756402/TW-1632_jpn-JPN.h.txt)
