### ISSUE TITLE
[TW-1636] UUID with numeric-only first segment is not parsed properly

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1660]
_Tomas Babej on 2015-07-16T13:46:00Z says:_ 

 Taskwarrrior can identify valid UUID most of the time, however, it chokes up on UUID which is valid, but not contains only numbers in the first segment.

```
$ task --version
2.4.5

$ task 49504810-6698-4404-a945-80e3f76e6c91 export
Cannot subtract strings
```

```
$ task ef9504810-6698-4404-a945-80e3f76e6c91 export
[
]
```

Probability of this event occurring is 2.33%

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-07-16T13:46:00Z
Modified: 2015-08-08T04:47:31Z
```

**Comment by taskwarrior** [comment]
_Renato Alves on 2015-07-17T08:54:38Z says:_ 

 Test added in uuid.t

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-08-06T11:52:46Z says:_ 

 This still fails when using first-segment part only:

Short form does not:

```
$ task 60097069
No matches.
```

Long form works:

```
$ task 60097069-c43a-4d5d-bb35-986007c3151d

Name          Value                               
ID            1
Description   task1                               
Status        Pending
Project       Inbox                               
Entered       2015-08-06 13:28:50 (26 minutes)
Last modified 2015-08-06 13:28:50 (26 minutes)    
Virtual tags  PENDING READY UNBLOCKED
UUID          60097069-c43a-4d5d-bb35-986007c3151d
Urgency          1

    project      1 *    1 =      1
* -----
                                 1

```

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-08-06T12:00:11Z says:_ 

 Attaching patch with expanded tests.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-08-08T04:47:31Z says:_ 

 Two problems:
*  DOM was looking for complete UUIDs, not partials
*  DOM was looking for ID before UUID, so numeric UUIDs would match IDs first

**Comment by pbeckingham** [comment]
[TW-1636_1000-tests-Expand-tests-for-querying-by-UUIDS-with-short-.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756404/TW-1636_1000-tests-Expand-tests-for-querying-by-UUIDS-with-short-.patch.txt)
