### ISSUE TITLE
[TW-1639] Can't re-synchronize multiple hosts after taskd failure

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1663]
_Dustin J. Mitchell on 2015-07-24T01:31:48Z says:_ 

 I've been using freecinc, which recently had its cert expire.  When the service was re-established, I had to generate a new certificate and key, which I installed on my first host.  Running `task sync` on that gives `Sync failed. The Taskserver returned error: 500 Client sync key not found. `  Running `task sync init` works, and uploads all of the changes present on that system.

However, I have other systems that used to be in sync with this one, and in fact I had made some changes on one of those systems before becoming aware of the freecinc failure.

Running `task sync` on that second host (with the same, new, cert and key) gave the same error - `Sync failed. The Taskserver returned error: 500 Client sync key not found.`.  But running `task sync init` there gives

    Please confirm that you wish to upload all your pending tasks to the
    Taskserver (yes/no) yes
    Syncing with freecinc.com:53589

    Sync failed.  The Taskserver returned error: 500 ERROR: Could not find common ancestor for 791e7d23-dbdd-456e-a539-fed9acfd3860

So in the end I was reduced to rsync'ing the data from the first host and manually applying the contents of backlog.data.

Jack asked me to file a bug, and now I have :)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-07-24T01:31:48Z
Modified: 2015-07-24T11:13:53Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-07-24T11:13:53Z says:_ 

 Thanks.

We're going to extend the command set beyond the two (sync, sync init) so that this situation and others are handled smoothly.  This is good input.

**Comment by bradyt** [comment]
@djmitche It's my understanding that "Client sync key not found" occurs when tx.data no longer has the sync key from .task/backlog.data. Did your steps above of getting new PEM files, also include a new taskd.credentials value, which would imply a new tx.data file without the sync key?

**Comment by djmitche** [comment]
Oh heck, I don't know - that was seven years ago :)

In general, I think the focus right now should be on replacing the sync mechanism, rather than addressing bugs in the current mechanism.

**Comment by bradyt** [comment]
Fair enough, but I think an archeologist may be interested to know it's the first of a group.

By sync mechanism replacement, I'm guessing you are proposing taskchampion-sync-server at your TaskChampion repo? I'll start taking a look. I see a few items to read at the present org, with <https://github.com/search?q=org:GothenburgBitFactory+taskchampion>. I've written and distributed a mobile taskd client, maybe I can experiment with accessing your new API.

**Comment by djmitche** [comment]
Sounds good, thanks - the discussions on this repo are a good place to continue talking about TC and its sync model.
