### ISSUE TITLE
[TW-1643] Batch modifying tasks under context sets description to '( )'

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1667]
_Leon Feng on 2015-07-30T08:46:53Z says:_ 

 I executed `task pro:YDKJS mod pri:M` under the context `Work`, which is defined as `+work`. When prompted, I answered `a` without looking, and Taskwarrior changed the description of all matched tasks to '( )' in addition to setting priority. See screenshot.

When context is set to `none`, the same command behaves as expected.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-07-30T08:46:53Z
Modified: 2015-08-05T23:49:42Z
```

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-07-30T11:18:48Z says:_ 

 Thank you for reporting this. I added a failing test: https://git.tasktools.org/projects/tm/repos/task/commits/cd3029592269b55910996a350687750f87ec1876

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-08-05T23:49:42Z says:_ 

 Thanks!

**Comment by pbeckingham** [comment]
![tw-1643_screen shot 2015-07-30 at 4 36 18 pm](https://user-images.githubusercontent.com/7963/36643624-47b69fec-1a1c-11e8-9e71-a37f6f01789f.png)

**Comment by php-coder** [comment]
> Thank you for reporting this. I added a failing test: https://git.tasktools.org/projects/tm/repos/task/commits/cd3029592269b55910996a350687750f87ec1876

A working link is: https://github.com/GothenburgBitFactory/taskwarrior/commit/cd3029592269b55910996a350687750f87ec1876
