### ISSUE TITLE
[TW-1644] monthly recurrent task shift

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1668]
_Miguel de Val-Borro on 2015-08-01T14:40:06Z says:_ 

 I have a recurrent task as shown below that was initially set up on the 12th of the month with a monthly recurrence. Each succesive task has been shifting slowly so that now the task appears in the beginning of the month instead of the 12th.
1.  Name               Editable details
1.  -----------------  ----------------------------------------------------
1.  ID:                24
1.  UUID:              0c7a14e6-d0dc-4c75-a003-40e3d2eedf51
1.  Status:            Recurring
1.  Mask:              XXXXXXXXXXXXXXXXXXXXXXXXXX++-
1.  iMask:             
  Project:           bills
1.  Separate the tags with spaces, like this: tag1 tag2
  Tags:              
  Description:       pay bill
  Created:           2013-04-20 17:04:59
  Started:           
  Ended:             
  Scheduled:         
  Due:               2013-05-12 00:00:00
  Until:             
  Recur:             1months
  Wait until:        
1.  Modified:          2015-08-01 10:30:49
  Parent:            
1.  Annotations look like this: <date> -- <text> and there can be any number of them.
1.  The ' -- ' separator between the date and text field should not be removed.
1.  A "blank slot" for adding an annotation follows for your convenience.
  Annotation:        2015-08-01 10:41:37 -- 
1.  Dependencies should be a comma-separated list of task IDs/UUIDs or ID ranges, with no spaces.
  Dependencies:      
1.  User Defined Attributes
  UDA priority:      
1.  End

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-08-01T14:40:06Z
Modified: 2015-09-02T00:50:11Z
```

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-08-04T12:58:48Z says:_ 

 This is probably due to the fact that TW currently equates the monthly recurrence with 30 day recurrence cycle.

**Comment by taskwarrior** [comment]
_Miguel de Val-Borro on 2015-08-04T21:27:56Z says:_ 

 That makes sense. Is it possible to have a recurring task on the same day of the month?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-08-04T23:43:47Z says:_ 

 If you have a recurring task, and the recurrence is set to "monthly", it should not creep forwards in time.  If it does, that's a bug.

There are unit tests that verify this, but there are also reports of daylight savings affecting the time/date.

**Comment by djmitche** [comment]
Same as #1647.
