### ISSUE TITLE
[TW-1647] descriptions that are stringified ids

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1671]
_Daniel Shahaf on 2015-08-04T05:59:46Z says:_ 

 Consider:

`task add 2; task add 1;`

With this setup, `task 2 ls` should list just the task having id=2, and `task 2 done` should close just that task.

With d0d30b2 (older), `2 close` reports "No matches" and `2 ls` works as intended. With b61bf5b (newer), `2 close` DTRTs and `2 ls` lists both tasks (bug).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-08-04T05:59:46Z
Modified: 2015-08-05T03:41:14Z
```

**Comment by taskwarrior** [comment]
_Daniel Shahaf on 2015-08-04T06:01:19Z says:_ 

 Attached an _incomplete_ test for this bug. It's incomplete because it doesn't test the `task 2 ls` case.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-08-04T21:04:09Z says:_ 

 I updated the test and added it to ids.t.

**Comment by pbeckingham** [comment]
[TW-1647_task-2-close.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756406/TW-1647_task-2-close.diff.txt)
