### ISSUE TITLE
[TW-1650] Parser cannot identify two long uuids in a list

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1674]
_Tomas Babej on 2015-08-06T11:34:05Z says:_ 

 Following sequence of commands fails with "Cannot subtract strings".

```
task add first
task add second

LONG_UUID1=`task _get 1.uuid`
LONG_UUID2=`task _get 2.uuid`

task $LONG_UUID1,$LONG_UUID2
```

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-08-06T11:34:05Z
Modified: 2015-08-07T11:48:20Z
```

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-08-06T11:43:53Z says:_ 

 BashTAP test.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-08-06T13:30:29Z says:_ 

 The comma-separated list is no longer supported.  Replace the comma with a space, and all should be well.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-08-06T13:39:03Z says:_ 

 Thanks Paul. However, comma separated list of IDs still works fine, which introduces inconsistency (not a big issue, just a remark).

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-08-07T11:48:07Z says:_ 

 Switch to comma separated lists now properly documented. Closing.

**Comment by pbeckingham** [comment]
[TW-1650_0999-tests-Add-test-for-TW-1650.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756408/TW-1650_0999-tests-Add-test-for-TW-1650.patch.txt)
