### ISSUE TITLE
[TW-1653] info report regression; shouldn't be context sensitive

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1677]
_David Patrick on 2015-08-12T22:28:22Z says:_ 

 Using a fresh 2.4.5, 'task 123 info' is context sensitive, where it shouldn't be. According to tbabej, on IRC, this is a regression from 2.4.4 and tasks called by ID/UUID should always be context insensitive.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-08-12T22:28:22Z
Modified: 2015-08-13T01:34:52Z
```

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-08-12T22:38:02Z says:_ 

 Yes, but I used some filter magic to determine that, so I do not wonder it no longer works. Patches that cover the issue (passing on 2.4.4, failing on 2.4.5) attached.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-08-13T01:34:52Z says:_ 

 Tests applied, pushed.  Good catch! Thanks.

**Comment by pbeckingham** [comment]
[TW-1653_0069-tests-Add-tests-for-context-ignored-with-explicit-id.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756409/TW-1653_0069-tests-Add-tests-for-context-ignored-with-explicit-id.patch.txt)
