### ISSUE TITLE
[TW-1674] Monthly recurrence can slip from 29-31 to 28th day in the month

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1698]
_Tomas Babej on 2015-08-27T14:35:44Z says:_ 

 Monthly recurrence set to 29-31th slips to 28th in February and stays on 28th for the following months too.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-08-27T14:35:44Z
Modified: 2015-09-02T00:56:06Z
```

**Comment by owenh000** [comment]
I noticed this with taskwarrior 2.5.1. The parent task is:

```
Due:               2017-11-07 00:00:00
Recur:             monthly
Wait until:        2017-11-01 00:00:00
```

Child tasks have been spawned on the first day of the month as expected until one was spawned 2019-02-28 (two tasks spawned in the same month).

Unfortunately, I think Taskwarrior's recurrence system may be too complex to be reliable (including its user interface).

**Comment by djmitche** [comment]
I think this is the same as #1647.
