### ISSUE TITLE
[TW-1688] task fails to import

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1712]
_Rainer Müller on 2015-09-08T15:31:39Z says:_ 

 task fails to import a previously exported set of tasks into a new TASKDATA directory.

```
$ task 80f0596c-a47f-4be8-a4b8-2aec4ae00137 8c9359bd-1770-4cba-94f4-68840a393b2d export > tasks.json
$ TASKDATA=/tmp/task task import tasks.json
Importing 'tasks.json'
TASKDATA override: /tmp/task
Error: missing ']' at position 1
$ echo $?
2
```

I am attaching an obfuscated version of tasks.json, with which I am still able to reproduce the bug.

This was produced with task 2.5.0.beta1 (f60b77e).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-09-08T15:31:39Z
Modified: 2015-09-11T15:40:19Z
```

**Comment by pbeckingham** [comment]
[TW-1688_tasks.json.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756410/TW-1688_tasks.json.txt)
