### ISSUE TITLE
[TW-1695] edit: Concurrent edits

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1719]
_Daniel Shahaf on 2015-09-16T10:33:54Z says:_ 

 Run `task 1 edit` in two terminals concurrently. If modifications are made in each window, the modifications made in the first-to-exit editor would be lost. To avoid silently overwriting the first-to-exit editor's changes, the second-to-start `task edit` instance could warn the user that another edit is in progress.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-09-16T10:33:54Z
Modified: 2015-09-19T12:14:34Z
```

**Comment by taskwarrior** [comment]
_Daniel Shahaf on 2015-09-16T10:42:08Z says:_ 

 After two concurrent edits, the results of edit that "lost the race" are available in undo.data, but cannot be recovered to using `task undo`. Specifically, undo.data contains the sequence "Change <original-state> to <post-first-edit>" followed by "Change <original-state> to <post-second-edit>", so `task undo` can _show_ the <post-first-edit> state but cannot restore to it.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-09-16T19:40:07Z says:_ 

 Patches submitted.

**Comment by taskwarrior** [comment]
_Daniel Shahaf on 2015-09-17T15:22:58Z says:_ 

 ... and committed. Thanks Tomas.

Could the error message state the id of the task that's already being edited?

That would be useful if the filter matches more than one task (`task 1-15 edit` while `task 10 edit` is running in another terminal).

**Comment by taskwarrior** [comment]
_Tomas Babej on 2015-09-17T15:33:41Z says:_ 

 Sure, feel free to improve that. Just make sure to use task.get ("uuid") for tasks that are already completed, otherwise you'd display ID 0.

**Comment by taskwarrior** [comment]
_Daniel Shahaf on 2015-09-17T17:42:27Z says:_ 

 Patch attached.

**Comment by pbeckingham** [comment]
[TW-1695_tw1507-expando-in-error-message-v1.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756411/TW-1695_tw1507-expando-in-error-message-v1.diff.txt)
