### ISSUE TITLE
[TW-1698] tests: 'make test' should exit non-zero if tests failed

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1722]
_Daniel Shahaf on 2015-09-17T18:05:21Z says:_ 

 'make test' should exit non-zero if tests failed.

Currently, that only happens when the --verbose flag is not passed, but make test does pass --verbose.  The attached patch makes --verbose take the exit-code-setting codepath (and also print the summary at the end, which the incumbent code prints only in _non_-verbose mode).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-09-17T18:05:21Z
Modified: 2015-11-07T22:46:50Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-11-07T22:46:50Z says:_ 

 Thanks!

**Comment by pbeckingham** [comment]
[TW-1698_make-test-exit-code-v3.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756419/TW-1698_make-test-exit-code-v3.diff.txt)
