### ISSUE TITLE
[TW-1709] Parsing bug when doing "task undo"

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1733]
_Scott Kostyshak on 2015-09-28T03:41:57Z says:_ 

 I might have run into a parsing bug. I was experimenting with some scripts that need to handle weird paths.

Warning: before trying to reproduce, save all important projects and expect your computer to run out of RAM and grind to a halt.

Attached is a small example task database. I can reproduce every time on 2.4.4 and 2.5dev, and I get the output

"Last task created ..."

and then RAM increases. I ctrl + c out of it.

Note that to create this evil task, I only used bash. That is, I did not do "task edit" and insert the weird characters. It will be time-consuming for me to reproduce exactly how I did it, but let me know if this is needed.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-09-28T03:41:57Z
Modified: 2016-02-24T03:59:13Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-11-10T22:02:40Z says:_ 

 I can no longer reproduce this.  I'd be happier if I knew what the problem was though.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-02T06:16:40Z says:_ 

 Tried again, cannot reproduce.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2016-02-02T16:24:35Z says:_ 

 Thanks for checking. I cannot reproduce either on 2.5.1git. If you were really curious I could do a git bisect to figure out which commit fixed this bug for me (although I'm still not sure I could reproduce it on an older version of Task. It could have been something specific to my system at the time). If not, I will skip it.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-02T17:36:08Z says:_ 

 Let's skip it and move on.  Thanks for checking!

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2016-02-15T05:03:20Z says:_ 

 I can reproduce this now on 2.4.4 and 2.5.1beta1. Not sure what I did differently. Here are the steps I do now to reproduce: first, download example.tar.gz and extract the examples folder. Then, with the terminal in the working directory containing the examples directory, run the following commands:

{code}
export TASKRC="$(mktemp)"
export TASKDATA=./example
task undo
{code}

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2016-02-15T08:38:30Z says:_ 

 Note that the completed.data file is missing. Perhaps this causes the problem?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-15T15:09:11Z says:_ 

 Okay, this is all about left-justifying long strings in an inadequate space.  Replicated, added a failing test.  Just need to fix it.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2016-02-15T17:47:10Z says:_ 

 Thanks for taking a look, Paul. Now that I can reproduce my offer to bisect is back on the table.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-15T17:58:17Z says:_ 

 Thanks Scott, but I have pinpointed it.  It happened as part of a UTF8 support change, and I can't undo the change, it's actually needed, so instead I need to actually fix it.  Won't be long.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-24T02:12:51Z says:_ 

 Please test if you get a chance.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2016-02-24T03:15:34Z says:_ 

 Tested and works well. Thanks for the fix.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-24T03:59:13Z says:_ 

 Thanks Scott.  I think we're good to go with 2.5.1.

**Comment by pbeckingham** [comment]
[TW-1709_example.tar.gz](https://github.com/GothenburgBitFactory/taskwarrior/files/1756420/TW-1709_example.tar.gz)
