### ISSUE TITLE
[TW-118] Introduce "time of day" for wait and due

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#175]
_Dirk Deimeke on 2012-02-13T10:57:56Z says:_ 

 I would like to have "time of day" subcommands for time related config options.

<pre>
task xyz mod wait:today.afternoon
task abc mod due:tomorrow.noon
</pre>

I suggest mapping something like this:

<pre>
midnight -> 00:00 hrs
early -> 03:00 # don't like "early", maybe there is a better name
morning -> 06:00
noon -> 12:00
afternoon -> 15:00
evening -> 18:00
late -> 21:00 # don't like "late", maybe there is a better name
</pre>

Even having "0300" as subcommand would be helpful.

<pre>
task due:tom.0300
task wait:sat.1200
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-02-13T10:57:56Z
Modified: 2015-03-14T16:16:49Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2012-02-13T17:52:36Z says:_ 

 I agree that we all use words to describe times of day, and aliases for those time would work linguistically.. 
I'm still not even sure about the syntax for indicating time numerically!

Obviously, between us night-owls and you early-birds, we are going to want different things, maybe it's time we thought about;

*User Defined Modifiers*

Sure, there are lots of existing modifiers, but what if we could define our own? like;

 usermod.time.morning=9:30am
usermod.time.noon=12:01pm
usermod.time.midday=3pm
usermod.time.night=9pm
usermod.attmod.lessthan=before #these define new aliases for existing attmods
usermod.attmod.morethan=after
usermod.attmod.with=has

Let's agree that we'll never agree on what time is "morning" and allow usermods.

**Comment by taskwarrior** [comment]
_Dirk Deimeke on 2012-02-13T18:11:23Z says:_ 

 David Patrick wrote:
> Let's agree that we'll never agree on what time is "morning" and allow usermods.

I am fine with usermods and I agree that it has to be configurable.

My important point is to use them when defining wait- and due-dates.

**Comment by taskwarrior** [comment]
_David Patrick on 2012-02-13T20:19:13Z says:_ 

 Dirk Deimeke wrote:
> My important point is to use them when defining wait- and due-dates.

absolutely! we all want to be able to do things like

 % task 142 mod due:tomorrow.eve
% task +print mod wait:thurs.aft

and I know that Paul has been in Deep Thought about these very things for some time.
This sort of thing is getting easier to do with taskwarrior core, and it's not unlike other feature-requests in progress, but we're all going to have to take a deep breath, and think "reductionist" for the next while, so that Paul, Fredde and the "band of coders", strip things out and fix things in preparation of a taskwarrior 2.0 release. 

All of our feature requests are well and good and recorded in the RedMine for future generations, but for right now, it's all about bugs. We need to see the essence of 2.x, close up the last of the leaks, bolt on the parts that work, and push that version out!

And after that? Game on!
So let's keep logging our feature requests like always, but don't expect immediate action on it.. and if you're a core developer reading this, move along, move along, it's back to http://taskwarrior.org/projects/taskwarrior/issues?query_id=22 for you!

**Comment by taskwarrior** [comment]
_Dirk Deimeke on 2012-02-14T04:38:04Z says:_ 

 David Patrick wrote:
> All of our feature requests are well and good and recorded in the RedMine for future generations, but for right now, it's all about bugs. We need to see the essence of 2.x, close up the last of the leaks, bolt on the parts that work, and push that version out!

This is my intent and this is why the target version is set to 2.1.0

**Comment by taskwarrior** [comment]
_Jostein Berntsen on 2013-10-31T10:42:07Z says:_ 

 Was going to suggest this, and then found it here. Would be very useful to be able to define an end time for a due task. This goes especially for preparation for meetings, phone calls a.o.

**Comment by taskwarrior** [comment]
_Jostein Berntsen on 2013-11-05T12:02:22Z says:_ 

 A preliminary way to get some functionality for time of day might be to add a time tag(like 11:00) to the relevant tasks. The tasks can then be looked up as f.ex. 

<pre>
task tag.has:[0-9][0-9]:
</pre> 

You can then make aliases for settings like these above:

<pre>
midnight -> 00:00 hrs
early -> 03:00 # don't like "early", maybe there is a better name
morning -> 06:00
noon -> 12:00
afternoon -> 15:00
evening -> 18:00
late -> 21:00 # don't like "late", maybe there is a better name
</pre>

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-12-27T18:35:22Z says:_ 

 It might be unambiguous and straightforward to recognize this:

```
<date>@<time>
```

This would allow a combination of any recognized date, with any recognized time.  Allowing user-defined time aliases (morning=09:30:00) would help.

**Comment by taskwarrior** [comment]
_Dirk Deimeke on 2014-12-27T20:38:53Z says:_ 

 This sounds pretty good.

Defining aliases would be best.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-03-14T16:16:49Z says:_ 

 Closing this.  In the interest of keeping the Taskwarrior core lean, there are improvements that can and should be achieved using hook scripts.  This is one.

**Comment by dbogdanov** [comment]
Anybody has implemented a hook for that?

**Comment by JonasDralle** [comment]
Can custom dates & times be defined?
I would really like to be able to have some sort of `tombirthday` and then

> task add until:tombirthday-1w due:tombirthday "Buy present for Tom"
