### ISSUE TITLE
[TW-1728] Fresh sync fails with most recent repository versions

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1752]
_Johannes Wienke on 2015-11-22T20:12:28Z says:_ 

 With the most recent version of taskd from the git repo, syncing my existing tasks to a fresh client (so no data existing on the client side) fails with the following client-side error message:

Sync failed.  The Taskserver returned error: 500 '3600' is not a valid date in the '' format.

I tried task in version 2.4.5 and also the most recent version from git.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-11-22T20:12:28Z
Modified: 2017-01-16T18:18:09Z
```

**Comment by taskwarrior** [comment]
_Johannes Wienke on 2015-11-23T21:45:05Z says:_ 

 This was caused by having the example "First task" entries in the tx.data on the server. These tasks have an entry date of 1/1/1970 and it seems the ISOxxx code can't handle these dates.

**Comment by djmitche** [comment]
New sync does not have this issue.
