### ISSUE TITLE
[TW-1729] zsh completion: zregexparse:4: not enough regex arguments

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1753]
_Daniel Shahaf on 2015-11-24T04:01:19Z says:_ 

 `task add +<TAB>` sometimes yields an error:

```
$ rm -rf .task 
$ zsh -f
% autoload -Uz compinit && compinit
% task add +<TAB><TAB>
_task_attributes:zregexparse:4: not enough regex arguments
% exit
$ task add foo >/dev/null 
$ zsh -f 
% autoload -Uz compinit && compinit
% task add +<TAB><TAB>
ACTIVE     COMPLETED  next       OVERDUE    TAGGED     UNTIL               
ANNOTATED  DELETED    nocal      PARENT     TODAY      WAITING             
BLOCKED    DUE        nocolor    PENDING    TOMORROW   WEEK                
BLOCKING   DUETODAY   nonag      READY      UDA        YEAR                
CHILD      MONTH      ORPHAN     SCHEDULED  UNBLOCKED  YESTERDAY           
```

The error is ultimately because the first element of `$task_attributes` is an opening parenthesis that doesn't have a matching closing parenthesis.

I'm attaching two patches.

The first patch is a drive-by cleanup that may speed the completion up a little bit.  The second patch fixes this error.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-11-24T04:01:19Z
Modified: 2015-11-25T02:21:18Z
```

**Comment by taskwarrior** [comment]
_Daniel Shahaf on 2015-11-24T04:10:12Z says:_ 

 This is arguably a bug in _regex_words; I'll report that to zsh upstream, but the above patch would still be needed for the completion to work under old versions of zsh.

_Update:_ reported http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=37215

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-11-24T12:47:38Z says:_ 

 Patches applied, thank you.  Should we now close this issue?

**Comment by taskwarrior** [comment]
_Daniel Shahaf on 2015-11-25T02:21:18Z says:_ 

 Done

**Comment by pbeckingham** [comment]
[TW-1729_0001-zsh-completion-Remove-unused-variable.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756421/TW-1729_0001-zsh-completion-Remove-unused-variable.patch.txt)
[TW-1729_0002-TW-1729-zsh-completion-Fix-edge-case-with-empty-data.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756422/TW-1729_0002-TW-1729-zsh-completion-Fix-edge-case-with-empty-data.patch.txt)
