### ISSUE TITLE
[TW-1734] calendar gives an error when context is set

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1758]
_Simon Michael on 2015-12-09T14:13:07Z says:_ 

 ~$ task context define test a
Are you sure you want to add 'context.test' with a value of 'a'? (yes/no) y
Context 'test' defined. Use 'task context test' to activate.
~$ task rc.context=test calendar
Configuration override rc.context:test
Could not recognize argument '('.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-12-09T14:13:07Z
Modified: 2016-01-12T03:42:17Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-12-11T15:46:43Z says:_ 

 Good catch, thank you.

**Comment by blaisegarant** [comment]
This bug seem to have returned.
