### ISSUE TITLE
[TW-1742] Indian Holiday Calendar (Master HolidayFile)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1766]
_Sunil Joshi on 2015-12-26T16:00:51Z says:_ 

 Need to create a Holiday master sheet for country India.

Note: This is going to contain almost all the holidays we have in India.
We have holidays region wise as well, so that individual needs to take care who needs to use this file.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-12-26T16:00:51Z
Modified: 2015-12-26T17:49:00Z
```

**Comment by taskwarrior** [comment]
_Sunil Joshi on 2015-12-26T17:47:04Z says:_ 

 [~paul] I have attached the Holiday file for India.

List has been created for 2016.
These are the major and important  holidays.

We have many more like that which depends upon the culture/location and preferences.

**Comment by taskwarrior** [comment]
_Sunil Joshi on 2015-12-26T17:49:00Z says:_ 

 Please review and let me know your comments.

Thanks!

**Comment by pbeckingham** [comment]
[TW-1742_holidays.en-IN.rc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756424/TW-1742_holidays.en-IN.rc.txt)
