### ISSUE TITLE
[TW-1743] Urgency Coeffieients Documentation Incorrect

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1767]
_Brian (bex) Exelbierd on 2015-12-30T14:25:47Z says:_ 

 The coefficients, as listed in the documentation, are incorrect.  Several have had name changes.

The attached patch is a suggested fix.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-12-30T14:25:47Z
Modified: 2016-01-11T20:16:16Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-01-11T20:16:16Z says:_ 

 Thank you

**Comment by pbeckingham** [comment]
[TW-1743_0001-Updates-to-the-Urgency-Coefficients-listing.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756426/TW-1743_0001-Updates-to-the-Urgency-Coefficients-listing.patch.txt)
