### ISSUE TITLE
[TW-121] "Canceled" status for all task records.

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#177]
_Eric Fluger on 2011-06-22T00:26:52Z says:_ 

 The "canceled" status currently applies only to recurring task records.  This change would make it an attribute of all task records.  Also add "cancel" command.  If command line assignment of vales to the status attribute becomes generally supported it "caneled" would be a valid value. 

Objectives: 

1. To facilitate accurate recording of cancelations in settings where that data has value. 

2. To faclitate close approximation of current recurring task behavior using a different system that is based on a copy on write approach and does not require the imask system that currently supports the "canceled" status for recurring tasks.  If the "canceled" status is recorded in the records they can just be counted up.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-06-22T00:26:52Z
Modified: 2014-04-23T15:36:57Z
```

**Comment by taskwarrior** [comment]
_Eric Fluger on 2011-06-22T00:28:39Z says:_ 

 OOPS!!! 

I accidentally submitted this as bug report instead of a feature request.  Can somebody tweak this?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-04-23T15:36:57Z says:_ 

 I think the difference between a "cancelled" task and a "deleted" task with an explanatory annotations is so small that this is not valuable.

I'm happier with the notion of status being a crude indicator, rather than some nuanced hint, leaving such subtlety to the annotations and tags.

**Comment by stephane-klein** [comment]
I'm also interested in this cancellation feature.
