### ISSUE TITLE
[TW-1748] CMakeLists shouldn't hardcode libc++ on Darwin

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1772]
_Misty De Meo on 2015-12-31T02:18:13Z says:_ 

 Taskwarrior's CMakeLists hardcodes the `-stdlib=libc++` flag whenever building on Darwin; this breaks the build for users using non-Clang compilers. For example, this is used by some users on older versions of OS X whose Xcodes don't include a suitably new Clang, as well as some OS X users who just prefer building with GCC.

Proposed patch is attached.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-12-31T02:18:13Z
Modified: 2016-01-14T18:36:43Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-12-31T22:23:12Z says:_ 

 Thank you.

**Comment by taskwarrior** [comment]
_Daniel Shahaf on 2016-01-14T18:36:43Z says:_ 

 The build error I reported in https://bug.tasktools.org/browse/TW-1737?focusedCommentId=16435 (clang, linux) bisects to this patch.  Reverting this patch allows my build to proceed.

**Comment by pbeckingham** [comment]
[TW-1748_0001-CMakeLists-don-t-hardcode-libc-on-Darwin.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756429/TW-1748_0001-CMakeLists-don-t-hardcode-libc-on-Darwin.patch.txt)
