### ISSUE TITLE
[TW-1749] PATH_MAX isn't defined in FS.cpp in some versions of OS X

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1773]
_Misty De Meo on 2015-12-31T02:41:22Z says:_ 

 In OS X 10.6.8, the PATH_MAX constant used in FS.cpp won't be defined unless sys/syslimits.h is included. Proposed patch is attached.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-12-31T02:41:22Z
Modified: 2015-12-31T22:15:15Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-12-31T22:15:15Z says:_ 

 Thank you.  You are added to the AUTHORS file.

**Comment by pbeckingham** [comment]
[TW-1749_0001-FS-include-sys-syslimits.h-on-OS-X.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756430/TW-1749_0001-FS-include-sys-syslimits.h-on-OS-X.patch.txt)
