### ISSUE TITLE
[TW-1750] REG_ENHANCED, used in RX.cpp, isn't defined in all versions of Darwin

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1774]
_Misty De Meo on 2015-12-31T02:43:54Z says:_ 

 RX.cpp uses the REG_ENHANCED flag on Darwin. This flag isn't defined on all versions of OS X, however. Proposed patch is attached, which checks whether that constant is defined instead of checking whether the OS is Darwin.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-12-31T02:43:54Z
Modified: 2015-12-31T22:18:32Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-12-31T22:18:32Z says:_ 

 Thank you.

**Comment by pbeckingham** [comment]
[TW-1750_0001-RX-test-for-presence-of-REG_ENHANCED.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756431/TW-1750_0001-RX-test-for-presence-of-REG_ENHANCED.patch.txt)
