### ISSUE TITLE
[TW-1758] Add option for calc to return epoch seconds

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1782]
_Alan Young on 2016-01-16T06:02:57Z says:_ 

 Make

task calc eow

return the epoch second.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-01-16T06:02:57Z
Modified: 2016-01-31T19:50:33Z
```

**Comment by pbeckingham** [comment]
This is not useful to taskwarrior, only to people wanting to piggyback off taskwarrior to do difficult date math.
