### ISSUE TITLE
[TW-1765] Warning when adding dependency to started task

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1789]
_Robin Green on 2016-02-03T11:09:51Z says:_ 

 If you modify a started task to add a dependency, I think taskwarrior should warn you, but it doesn't. (It actually _does_ warn/inform you when you then _do_ stop the task, but I think that's the wrong way round - I think it should warn you when you add the dependency, but not when you stop the task.)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-02-03T11:09:51Z
Modified: 2016-02-04T20:06:12Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-04T20:06:12Z says:_ 

 This is a good idea, but not an enhancement that we'll put in core.

I have attached a hook script which implements this functionality. One of the nice benefits of hook scripts is that they may be used to implement policy such as this, and don't require a change to the core, in order to do so.

This hook script is also something that can be extended to implement other such warnings, take a look at the implementation, it's simple and documented.

So as a rule, if some functionality can be implemented well with hooks, it's not going in the core.

**Comment by pbeckingham** [comment]
[TW-1765_on-modify-warn-active.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756432/TW-1765_on-modify-warn-active.txt)
