### ISSUE TITLE
[TW-123] Need a configurable default end-of-day time for new tasks that isn't 00:00

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#179]
_Cory Donnelly on 2010-07-31T10:28:49Z says:_ 

 Now that getDueState() considers times and the overdue report uses the relative date value of 'now', newly-created tasks need to either have user-specified due times or have default times applied other than 00:00.

Feature #437 and forum thread "Finetune Hour Used for Countdown":http://taskwarrior.org/boards/6/topics/show/562 by Michelle spawned this issue.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-07-31T10:28:49Z
Modified: 2014-07-01T23:51:57Z
```

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-01-25T17:23:12Z says:_ 

 Needs more thinking. It is more complicated than it looks.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-02-19T20:44:26Z says:_ 

 To be addressed in the kronisk date/time library, and integrated later.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-08-01T19:20:58Z says:_ 

 I propose a mechanism for using both start and end of day values with dates by appending an optional '-' or '+' sign, respectively. For example, "8/1/2012+" would expand as 8/1/2012 at 23:59:59 (given that 'dayend=23:59:59'). See the following patch for precision (as it depends on other modifications that are not directly related with this issue, it is probably not applicable).

**Comment by taskwarrior** [comment]
_David Patrick on 2012-08-15T21:01:20Z says:_ 

 Don't forget to add *sod* and *eod* to the "Start of and End of" big list of date specifiers.

**Comment by taskwarrior** [comment]
_Michele Santullo on 2013-08-29T09:06:00Z says:_ 

 I have the same request. "overdue" command is always off by one day, so the workaround is to set the due date one day after, but it gets confusing when you list tasks (ie: a task that must be completed within today must be added as due:tomorrow or it will be reported as overdue, effectively making due:today useless).
After discussing on IRC, one solution would be to automatically make up a timestamp depending on the context: "due" for example should set the time to 23:59, giving you time to finish your task; wait should set it to 00:00 as it does now, as wait:today makes no sense and wait:tomorrow means I want it to be visible asap when the day digit changes.

**Comment by taskwarrior** [comment]
_Profpatsch - on 2013-10-08T10:13:34Z says:_ 

 +1 for Michele’s idea. That’s what I’d expect it to behave like, too.

E.g. I want to do `task add sometask due:3d wait:3d` and have it appear at the beginning of the third day from now, marked with the due.today color.

**Comment by taskwarrior** [comment]
_David Patrick on 2013-10-08T17:26:33Z says:_ 

 If date aliases ( #1326 ) were implemented, then a user could easily re-define eod, eow, etc to mean whatever floats yer boat, including;

   date-alias.eobd=eod -7 hours  ## end of business day

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-10-10T00:07:54Z says:_ 

 > If date aliases ( #1326 ) were implemented ...

Yes, I like this.  Allowing aliases for this seems to me to be the best approach.  I have a problem with the notion of redefining what "end of day" means - it's midnight.  It's not mutable.  I think there's a big difference between end-of-day, and end-of-work-day.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-07-01T23:51:57Z says:_ 

 eod == end of day == midnight.  I don't see any reason to make that absolute value configurable.

Other values, used-defined values would be good, but eod should be fixed.

**Comment by pbeckingham** [comment]
[TW-123_0001-Feature-454.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755551/TW-123_0001-Feature-454.patch.txt)

**Comment by rudolfschmidt** [comment]
I need that feature too. I would say eowd = end of work day that is customizable like 6pm, 5pm whatever.

**Comment by Andonome** [comment]
I need this feature too. My day goes from 11am to 4am. My 'end of day' and all recurring tasks act unexpectedly, because after finishing most tasks, tomorrow's tasks appear while I'm still active.

Some configuration to say my day ends and starts at 4am would be great.

**Comment by paride** [comment]
I'm also missing why this was closed. Maybe the status was inherited from the previous bug tracker, but the explanation didn't get carried over?

Cc: @tbabej
