### ISSUE TITLE
[TW-1766] Add on-sync event to hook triggers

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1790]
_David Costa on 2016-02-06T17:31:09Z says:_ 

 It would be nice to have events triggered before and after sync so that it's possible to customize the way the sync behaves.

Some ideas:
*  notify user with a custom report of how the sync went
*  prevent syncing for some reason
*  plug in some kind of external syncing system via hook scripts

This last point in particular would let people build bridges between taskwarrior and other things that could even work offline (like a list of things in a spreadsheet) keeping the semantics (this is always a type of sync) and without implementing things in the core.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-02-06T17:31:09Z
Modified: 2017-01-16T18:39:13Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-24T02:21:17Z says:_ 

 In order to do this, we need to identify what the event hook looks like.  They all have different I/O, what should this one look like?  Let's explore it...

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-16T18:39:13Z says:_ 

 Closing: 11 months, no response.

**Comment by goodevilgenius** [comment]
I'd like this to be reopened. This is also mentioned in #2142. It's clear that there is a desire by some to have some kind of hook to be run for synced tasks. Hooks aren't necessarily the same on each replica, so this makes sense.

As for implementation, I'd suggest that the `on-sync` hook work the same as `on-modify`. It should run once for every task that was synced, giving previous version (or a blank line, perhaps, for new tasks) on first line, and new version on the second.

Alternately, we could add `on-syncadd` and `on-syncmodify`, which would mirror `on-add` and `on-modify` exactly.

**Comment by djmitche** [comment]
I think this is a duplicate of #2142, which remains open.
