### ISSUE TITLE
[TW-1773] one task eaten all my RAM 

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1797]
_Yaroslav Molochko on 2016-02-20T16:01:10Z says:_ 

 Example execution result
{code}
 top - 23:44:50 up  7:45,  6 users,  load average: 7.93, 2.40, 1.08
Tasks: 213 total,  11 running, 202 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.3 us, 41.6 sy,  0.0 ni,  2.1 id, 52.1 wa,  0.0 hi,  3.0 si,  0.0 st
KiB Mem :  7820840 total,    49672 free,  7514368 used,   256800 buff/cache
KiB Swap: 15622140 total, 13138408 free,  2483732 used.    27800 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND               
  657 root      20   0       0      0      0 R  41.6  0.0   0:21.76 kswapd0               
  750 onorua    20   0 14.042g 6.174g      8 R  32.5 82.8   0:17.03 task        
{code}

bugwarriror created a task, which I can't actually see due to this problem. I've attached strace, I have only 8GB of ram, and my system can't survive gdb run without control over interruption :(
Please, if I can help to debug - just let me know, I'll do my best

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-02-20T16:01:10Z
Modified: 2016-02-24T02:12:40Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-20T23:40:42Z says:_ 

 Thanks for reporting this.  We're going to need some help debugging, because so far we don't know much.  Can you describe the bugwarrior and taskwarrior versions, the initial trigger for the new task, and maybe before/after diff on the data files, if possible.  Basically anything we can get.

**Comment by taskwarrior** [comment]
_Yaroslav Molochko on 2016-02-21T05:41:45Z says:_ 

 Sure:
bugwarriror version is 1.3.0 installed from pip. 
task version is 2.5.0

it looks like the issue is happen to one task, I can check others task created from bugwarrior with no issues. 

I could check the pending file, and found the issue description - working.txt
which looks pretty much the same way as others, except maybe it has more annotations in descriptions.
The issue created from jira plugin of bugwarrior, the other issue created by the same tools in the same way but I can open it with no issues - working.txt 

I'll be happy to debug more, just tell me what else can I do?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-21T13:22:48Z says:_ 

 Confirmed, replicated with your data.  Thank you!

**Comment by taskwarrior** [comment]
_Yaroslav Molochko on 2016-02-21T14:18:48Z says:_ 

 Thank you for the prompt response even on the weekend!

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-21T14:31:34Z says:_ 

 Just so it's clear: Bugwarrior is not the problem.  This is a Taskwarrior bug, and probably the same issue as tw-1709.

Weekends are where all the free time is - this is all-volunteer.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-02-24T02:12:40Z says:_ 

 Please test if you get a chance.

**Comment by pbeckingham** [comment]
[TW-1773_non-working.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755617/TW-1773_non-working.txt)
[TW-1773_task23.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755618/TW-1773_task23.txt)
[TW-1773_working.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755619/TW-1773_working.txt)
