### ISSUE TITLE
[TW-1776] Multi-sync support

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1800]
_Matthias Beyer on 2016-03-02T15:50:57Z says:_ 

 Feature request: I would like to have the possibility to have several taskservers configured in my .taskrc, so I can sync to several servers.

My use-case is that I do not have a taskserver on the web, as I like to keep as much data as possible "offline". So I have 3 machines (two notebooks and one desktop machine) and I'm not sure which one should run the taskserver now. Having a taskserver on each machine gives me the possibility to sync tasks between the notebooks if I'm not at home, and whenever I am at home, I do not have to switch notebooks to sync to my workstation.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-03-02T15:50:57Z
Modified: 2016-03-03T17:46:43Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-03-03T17:46:33Z says:_ 

 Above all, this needs a viable algorithm for alternating between servers until quiescent, or something like that.  Will think about it.

**Comment by pbeckingham** [comment]
I fear this will lead to race conditions or looping.
