### ISSUE TITLE
[TW-1778] Unicode strings are truncated in task description

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1802]
_Andrew on 2016-03-07T13:40:04Z says:_ 

 task 2.5.1 truncates UTF-8 descriptions of task in the output, e.g.:

 $ task сковорода
[task next ( сковорода )]

ID Age Project      Tag Description         Urg 
 1 8w  home.kitchen buy сков�                2.94
                          2016-01-05 800 р.     

1 task

It looks like output is truncated by the number of bytes equal to number characters in the string, but Unicode characters can be multibyte.

File 1.out contains output of `task 1` command.
File 1.data contains appropriate ~/.task/pending.data record.

This bug is a regression in 2.5.1: 2.5.0 works fine.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-03-07T13:40:04Z
Modified: 2018-01-28T20:09:57Z
```

**Comment by taskwarrior** [comment]
_Andrew on 2016-04-10T08:54:03Z says:_ 

 Ping here :)

**Comment by taskwarrior** [comment]
_Max Brown on 2016-05-01T11:54:47Z says:_ 

 Is there actual data loss??

I have the same problem!!

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-05-01T12:04:10Z says:_ 

 No data loss, just a word-wrapping problem.

**Comment by taskwarrior** [comment]
_Andrew on 2016-05-03T08:20:27Z says:_ 

 Paul, git bisect shows that this problem was introduced in commit 029f3af578e6b9f4d13977b04f9a1239b8a58542 :

Author: Paul Beckingham <paul(at)beckingham.net>
Date:   Tue Feb 23 21:05:53 2016 -0500

    TW-1709: Parsing bug when doing "task undo"
*  Thanks to Scott Kostyshak.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-05-03T10:29:22Z says:_ 

 Yes, that's the change I was referring to.

**Comment by taskwarrior** [comment]
_Andrew on 2016-05-04T01:50:59Z says:_ 

 debugging shows that problem is on text.cpp:263 (for current git HEAD):
{code}
    line_length += mk_wcwidth (character);
{code}

For some unknown reason mk_wcwidth() returns 1 for cyrillic unicode character for given example, while it should return 2.

Frankly, I don't understand mk_wcwidth() implementation and its messing with hardcode unicode range tables, and I can't understand why standard library wcwidth() can't be used instead. Apparently mk_wcwidth() handles control characters differently from wcwidth(), because when I replace mk_wcwidth() with wcwidth() at the given line, I get correct text output (not truncated), but extra line break between Description and Urg fields.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-05-04T11:57:50Z says:_ 

 bq. I can't understand why standard library wcwidth() can't be used instead

That's because you're only looking at one test case, you're ignoring the bad result (extra line break) for some reason, and haven't run the test suite and seen the dozens of failures there.

**Comment by taskwarrior** [comment]
_bjonnh on 2016-06-27T16:09:13Z says:_ 

 I don't know if it is related but:
(on a fresh install, actually a patched dev version so it uses its own ~/.taskrc-dev)

$ task add "Test unicode é."
$ task 1 
1.  It displays the right description
$ task 1 annotate "Something"
$ task 1 
1.  The description is now "Test unicode é" so the dot has been removed.

This bug makes a data loss!

**Comment by taskwarrior** [comment]
_Andrew on 2016-06-27T16:24:28Z says:_ 

 > This bug makes a data loss!

Not really, ~/.task/*.data files still contain full strings. So only representation is truncated, not the data itself.

What really worries me, that queries are also truncated, so it is possible to search full-text UTF-8 descriptions no longer; e.g. if I have task desription "кухня" and will enter `task кухня` it will return me "No matches." This renders task > 2.5.0 completely unusable for my needs.

**Comment by taskwarrior** [comment]
_bjonnh on 2016-06-27T16:34:13Z says:_ 

 This is really annoying for me too as most of my descriptions are using UTF-8 characters.

**Comment by taskwarrior** [comment]
_OKOMPer on 2016-06-28T23:53:49Z says:_ 

 I have the same problem. I am a chinese user. 

For example，
the task is 洗澡, and output will be 洗�
But if I change the task to 洗澡aa, the output will change to 洗澡。

Chinses fonts are double-byte characters, and English fonts are single-byte characters, Taskwarrior must think chinese fonts are also single-byte characters. 
So, it think 洗澡 are 2 bytes, but 洗澡  are 4 bytes, output will ignore 2 bytes and become  洗�. I change it to 洗澡aa, it think 洗澡aa is 4 byte and output become 洗澡.
 I try Japanes, it also have the problem, and japanese fonts are double-type characters too.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-06-28T23:59:32Z says:_ 

 Just to address all the commenters:

I believe this is fixed in 2.6.0, in a private branch.  Once I have tested this sufficiently, and added unit tests, it will be pushed and will eventually be released with 2.6.0.

The problem concerns the difference between characters and bytes in a UTF-8 string.

**Comment by taskwarrior** [comment]
_Vladimir on 2016-08-31T19:21:24Z says:_ 

 I have same bug. As I see it is in 2.5.1, 2.5.2 and 2.6.0 versions.

This is patch for it.
task/src/text.cpp (on line 251)
{code:title=patch.diff}
251c251
<       line = text.substr (offset, line_length);
* --
>       line = text.substr (offset, prior_cursor - offset);
{code}

**Comment by taskwarrior** [comment]
_Vladimir on 2016-08-31T19:37:45Z says:_ 

 resolve for issue #TW-1778

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-08-31T21:45:20Z says:_ 

 Yes, that's the fix I made in libshared.

**Comment by taskwarrior** [comment]
_Vladimir on 2016-08-31T21:50:48Z says:_ 

 Will you backport it to 2.5.1?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-08-31T21:53:06Z says:_ 

 That would require time travel.  :-)

This will in 2.6.0, see the "Fix Version" field above.

**Comment by pbeckingham** [comment]
[TW-1778_1.data.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755620/TW-1778_1.data.txt)
[TW-1778_1.out.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755621/TW-1778_1.out.txt)
[TW-1778_patch.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755622/TW-1778_patch.diff.txt)
