### ISSUE TITLE
[TW-1782] Allow commands that display meta program info to export in json format.

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1805]
_Alan Young on 2016-03-14T17:52:24Z says:_ 

 Allow commands that display meta information about the task program itself be exported in json format.

The 'commands', 'show', 'columns' and 'udas' commands are what I am referring to specifically. I'm not sure if there are any other commands this makes sense with.

For example, the output of 'task commands' is a tabular format that includes categories, whether or not the command accepts a filter and a short description.

I use the category to filter out certain groups of commands (e.g., the graphs don't make sense for what I'm trying to do and I don't want to allow internal commands). I determine how to handle data validation based on whether or not the command accepts a filter. And I display the short message as a description of what the command does.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-03-14T17:52:24Z
Modified: 2017-01-16T21:20:13Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-03-14T21:30:29Z says:_ 

 This is exactly what the `_show`, `_udas` and `_commands` helper commands are for.  JSON is overkill.

You can check capabilities using the equivalent of:

```
$ task commands | grep ^info | grep Filt
$ echo $?
0
```

Or just hard-code it in a table, by version.  The command descriptions can be queried using the `_zshcommands` helper.

Is this a front end you have that does this?  Is it doing proper version checking?

**Comment by taskwarrior** [comment]
_Alan Young on 2016-03-14T22:21:19Z says:_ 

 It's a library for a front-end I'm working on. The first thing it does is check the version. If it's earlier than 2.5.1 then I don't support it.

I did not examine the _zshcommands option. Having done that, it doesn't output the same information as commands. It doesn't display info about whether the command is rw/ro or if the command accepts a filter.

_udas, _columns and _commands are extremely limited ... they only display the names. As stated in the docs, they are for completion purposes, and useless for metadata discovery.

I didn't do full due diligence on the show and _show commands. You are, of course, right about the '_show' command having much -- if not most -- of what I need. With one minor exception being that the 'show' command shows default values for changed settings and unknown variables while the '_show' command does not. But I don't need that information, at least at the moment.

The 'columns' command is the only place I can find information on the known columns; the type, whether the value is modifiable and formatting. Parsing this table is a headache.

Finally, the 'commands' command tells me what commands are affected by context and accept a filter. I can't find this info anywhere else, am I missing something? I am currently parsing this with the following perl regex:

```
qr{^
     (.*?)
     \s+
     (.*?)
     \s+
     (R[OW])
     \s+
     (?:(ID)\s+)?
     (?:(GC)\s+)?
     (?:(Ctxt)\s+)?
     (?:(Filt)\s+)?
     (?:(Mods)\s+)?
     (?:(Misc)\s+)?
     (.*)
   $}x;
```

which is brittle and clumsy. But I'm having a hard time converting this to a node regex (which is probably due more to my inexperience with javascript regexes).

**Comment by pbeckingham** [comment]
This is a case of a request to make Taskwarrior bigger so that an extension script can be shorter.  We want it the other way round.
