### ISSUE TITLE
[TW-1791] taskrc(5) manpage: spurious "pri." in rule.precedence.color

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1813]
_Sebastien Badia on 2016-04-02T18:29:27Z says:_ 

 The taskrc(5) manpage gives the following example for 
rule.precedence.color:

due.today,active,blocking,blocked,overdue,due,scheduled,keyword.,project.,tag.,uda.,recurring,pri.,tagged,completed,deleted

The "pri." item is incorrect, because there is no color rule named 
"color.pri.X" in this version of Taskwarrior.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-04-02T18:29:27Z
Modified: 2016-04-04T14:57:45Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-04-02T19:04:58Z says:_ 

 Good catch.  Patch applied, thank you.

**Comment by taskwarrior** [comment]
_Sebastien Badia on 2016-04-04T14:57:45Z says:_ 

 thanks!

**Comment by pbeckingham** [comment]
[TW-1791_TW-1791.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756433/TW-1791_TW-1791.patch.txt)
