### ISSUE TITLE
[TW-1795] Calendar underline on Day padding

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1817]
_Renato Alves on 2016-04-12T16:01:01Z says:_ 

 The calendar underline style used for days is also applied to the padding on the left of the days.

This was not visible on 2.5.0 so I guess it was introduced in 2.5.1.

The first screenshot is from 2.5.1, the second from 2.5.0.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-04-12T16:01:01Z
Modified: 2016-04-15T11:49:19Z
```

**Comment by pbeckingham** [comment]
![tw-1795_screenshot_2016-04-12_18-04-40_348949348](https://user-images.githubusercontent.com/7963/36643687-3b6cdff2-1a1d-11e8-8089-3300d34fe13d.png)
![tw-1795_screenshot_2016-04-12_18-04-52_287075330](https://user-images.githubusercontent.com/7963/36643688-3b800dca-1a1d-11e8-81ff-ba4bfb556065.png)
