### ISSUE TITLE
[TW-1798] task gets deleted if until < due

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1820]
_slaven ʙanovic on 2016-04-30T22:18:02Z says:_ 

 
Adding a task with a until date earlier than the due date results in immediate deletion. TW assumes the task to be already expired.

{code:none}
$ t add test 3 +test prio:H due:thursday recur:weekly wait:due-20h until:due-2
Created task 49 (recurrence template).
$ t +test
Creating recurring task instance 'test 3'
No matches.
There are local changes.  Sync required.
$ t +test
Task 49 'test 3' expired and was deleted.
No matches.
There are local changes.  Sync required.
$ t info 49

Name          Value
ID            49
Description   test 3
Status        Deleted
Recurrence    weekly
Mask          W
Entered       2016-05-01 00:04:06 (1min)
Waiting until 2016-05-04 04:00:00
Due           2016-05-05 00:00:00
End           2016-05-01 00:04:12
Until         2016-05-04 23:59:58
Last modified 2016-05-01 00:04:12 (1min)
Tags          test
Virtual tags  DELETED PARENT TAGGED UDA UNBLOCKED UNTIL PRIORITY
UUID          a331c441-c07a-4721-b529-ff74166ca77c
Urgency       13.77
Priority      H
{code}

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-04-30T22:18:02Z
Modified: 2017-01-16T21:12:21Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-16T21:12:13Z says:_ 

 This is true.  Why does your task have an `until` date before the `due` date?  What was expected to happen?  Was this caused by the `until` date not being properly advanced for child tasks?

**Comment by pbeckingham** [comment]
This is not a bug.
