### ISSUE TITLE
[TW-1805] project:ide is not allowed

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1826]
_slaven ʙanovic on 2016-05-16T21:28:50Z says:_ 

 You can't choose a project name starting with "ide". task fails with "The expression could not be evaluated."

{code}
$ task rc.debug=1 add project:ide one
Timer Config::load (/var/inst/task/doc/rc/light-16.theme) 0.010428 sec
Timer Config::load (/home/user/.taskrc) 0.011665 sec
Found hook script /home/user/.task/hooks/on-add-pirate
Found hook script /home/user/.task/hooks/on-modify-pirate
Found misnamed hook script /home/user/.task/hooks/pirate_add_shift_recurrence.py
Parse Tree (before command-specifіc processing)
  _original_args
    task rc.debug=1 add project:ide one
  _args
    word basename='task' raw='task' BINARY 
    pair modifier='debug' name='rc' raw='rc.debug=1' separator='=' value='1' CONFIG ORIGINAL 
    identifier canonical='add' raw='add' ORIGINAL CMD ALLOWSMODIFICATIONS 
    pair canonical='project' modifier='' name='project' raw='project:ide' separator=':' value='ide' ORIGINAL MODIFICATION 
    identifier raw='one' ORIGINAL MODIFICATION 

Task::modify
Configuration override rc.debug:1
The expression could not be evaluated.
{code}

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-05-16T21:28:50Z
Modified: 2016-05-20T16:07:27Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-05-20T16:07:27Z says:_ 

 This was caused by some missing logic - if an expression fails to evaluate for certain reasons (in this case, unrecognized DOM reference and no operators), then the value should be stored as-is.

**Comment by dwarfmaster** [comment]
It seems the prefix `project` cause the same bug too. Furthermore, doing `task 1 modify project:project` doesn't do anything.
