### ISSUE TITLE
[TW-1825] "show report" -- realign blank lines

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1841]
_Eric Hymowitz on 2016-07-04T16:40:29Z says:_ 

 I changed the "next" report in `.taskrc` .  When I issue a `task show report.next`, the placement of blank lines seems odd to me.  I essentially see

```
changed option 1

        default option 1
changed option 2 with no default

unchanged option 3
changed option 4

     default option 4
unchanged option 5
```

The placement of blank lines tends to indicate (to me, anyway) that  items between the blank lines are related to each other.  But that is not the case here.  Each item is related to the blank line and (possibly) the next line after it.

It's just confusing to me, and I'm hoping you might consider adjusting it.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-07-04T16:40:29Z
Modified: 2017-01-16T20:57:22Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-16T20:57:22Z says:_ 

 Those aren't blank lines, just very long lines that wrap.  It's not ideal.  Got a suggestion?

**Comment by pbeckingham** [comment]
No solution.

**Comment by pbeckingham** [comment]
![tw-1825_reportnext](https://user-images.githubusercontent.com/7963/36643697-706bed38-1a1d-11e8-964a-75013b77fb67.png)
