### ISSUE TITLE
[TW-1826] Add is_active, is_overdue, is_blocking and is_blocked to the JSON export

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1842]
_Sheda on 2016-07-06T19:40:08Z says:_ 

 The JSON export lack some computed task properties to help external programs. I suggest adding the following:
*  is_overdue;
*  is_blocking;
*  and is_blocked.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-07-06T19:40:08Z
Modified: 2016-08-25T07:06:58Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-07-06T23:29:52Z says:_ 

 Those are not attributes of a task, and in fact are all derived form the real attributes of a task.  Adding it to the JSON would be redundant.

**Comment by taskwarrior** [comment]
_Sheda on 2016-07-11T12:09:20Z says:_ 

 To know if a task is overdue I need to match its "due" property against today's date, right ? For the is_blocked predicate, it seems to be against its "depends" property, right? BTW, can the depends property be an array, e.g., if the task depend on more than one other task?

I can't figure how to answer the is_blocked predicate. How should I do?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-07-12T12:03:43Z says:_ 

 A task is considered blocked if any of the tasks it depends on are blocked.  It's recursive, so you need to scan the chains.

**Comment by taskwarrior** [comment]
_Tomas Babej on 2016-07-12T16:24:59Z says:_ 

 While I think we should't be adding redundant information to the JSON export by default (which would affect performance), maybe what this issue (and others) calls for is a new export mode/setting, that would. This will prevent the need to duplicate the logic (which can be non-trivial, such as in this case) in the third party extensions.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-07-12T17:42:34Z says:_ 

 I hear you.  I'm in favor of making improvements to the way tasks are managed.  But this is not one of them.

Consider the `is_overdue` above - this is a request to compare a (provided) date field to the current time.  It is effectively a request to save a developer a single `if` statement.  That is ridiculous.

Flattening the data by adding `is_blocking` misrepresents the relationships between tasks.  It also means that `import` would not be able to ingest the output of `export`, if modified.

The right answer is to state that tasks are part of an interconnected graph, and treating a task as a single isolated record is wrong. Any extension/script/wrapper that doesn't treat the data as a graph is broken by design.

**Comment by taskwarrior** [comment]
_Daniel Shahaf on 2016-07-13T03:35:47Z says:_ 

 There is a difference between the data model that's useful to taskwarrior internally and the one that's useful to users: internally "overdue" is a derived concept; however, someone who's writing a custom taskwarrior UI does not want to know the details of the derivation.  This is similar to the ideological difference in TW-301.

Why wouldn't `import` be able to ingest the output of `export`?  Whatever implementation of `export` you had in mind when you wrote this, I'm sure there is an alternative implementation that does not have the problem you identified.

By the way, I don't have a 2.6 handy, but everything requested so far could be implemented by including virtual tags in the export.

**Comment by taskwarrior** [comment]
_Sheda on 2016-07-15T13:33:46Z says:_ 

 Having the virtual tags exported would be great. That was my first idea but, from an external program point of view, I though it would be more comfortable (and more efficient?) to just test for a boolean.

For `is_overdue`, you're wrong, that's not just an `if` but a data+time comparison. It can probably be considered trivial but why waste resources re-computing something that was efficiently done by Task Warrior? I'm only half kidding here :p

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-07-15T20:57:45Z says:_ 

 It's still only one "if" condition, even if you have to add two terms on one side of the relational operator.

Taskwarrior evaluates virtual tags on demand, so no, resources are not wasted re-computing anything.

**Comment by taskwarrior** [comment]
_Daniel Shahaf on 2016-07-17T10:24:15Z says:_ 

 I don't think the forward compatibility consideration has been mentioned yet: what happens if taskwarrior 2.7 changes the "is overdue" notion and replaces the single "if now() > task.due()" condition by something more complicated?  (Say, also consider a task overdue if the current time is on a weekend and the due date is before Monday morning.)

**Comment by taskwarrior** [comment]
_Sheda on 2016-08-25T07:06:58Z says:_ 

 ```Taskwarrior evaluates virtual tags on demand, so no, resources are not wasted re-computing anything.```

I was saying that if both Task Warrior and an external program do some comparisons on date+time, computing resources are wasted. This resources would not have been wasted if TW was kind enough to just provide the information (is_overdue) to the external program.

But re-reading https://bug.tasktools.org/browse/TW-1830, I think I understand: you make a clear difference between UI (task info) and raw data access (task export). My problem seems to be that the U in UI is only for user (i.e., a human being) and not for user agent (a program acting on the behalf of the user and needing the same level of information).

**Comment by pbeckingham** [comment]
[TW-1826_da30db5.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756439/TW-1826_da30db5.patch.txt)
