### ISSUE TITLE
[TW-1840] Reopened task is not immediately assigned an ID

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1856]
_Robin Green on 2016-08-07T20:05:51Z says:_ 

 When I reopened a deleted task, it initially had an ID of `-`, as shown by `task unblocked limit:page`.

Workaround was to run `task` with no arguments.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-08-07T20:05:51Z
Modified: 2017-10-12T02:58:32Z
```

**Comment by pbeckingham** [comment]
Not a bug.  Running a report should cause a GC and relocate the task back to pending.data, thus giving it an ID.
