### ISSUE TITLE
[TW-1852] Add ability to set line-height for each row

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1867]
_eio on 2016-09-15T21:40:17Z says:_ 

 In .taskrc you have "column.padding" and "row.padding" but how about padding for top and bottom for better readability

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-09-15T21:40:17Z
Modified: 2017-10-12T03:03:49Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-10-12T03:03:49Z says:_ 

 Do you mean that a minimum setting of 1 should show every other line in the output a blank?

**Comment by pbeckingham** [comment]
No response.
