### ISSUE TITLE
[TW-1862] Editing failed with exit code 256

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1875]
_Christiaan on 2016-10-19T11:59:29Z says:_ 

 When I edit any task with vim, e.g. `task 1 edit`, I get `Editing failed with exit code 256` when I try to save it.

task 2.5.1
   Platform: Darwin

Compiler
    Version: 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)
       Caps: +stdc +stdc_hosted +200112 +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Mar 13 2016 13:24:01
      CMake: 3.5.0
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.4.10
 Build type: Release

Configuration
       File: /Users/mozey/.taskrc (found), 1768 bytes, mode 100755
       Data: /Users/mozey/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /Users/mozey/.task/hooks
             (-none-)

Tests
      $TERM: ansi (236x46)
       Dups: Scanned 3 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 3 tasks for broken references:
             No broken references found

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-10-19T11:59:29Z
Modified: 2016-10-20T14:45:55Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-10-19T12:04:38Z says:_ 

 In this case Taskwarrior is reporting the exit code of vim, which it expects to be zero if the file was saved.  The question is now why does your vim exit with 256?  Can you try this please:

```
$ date > foo
$ vim foo
(make a change, then :wq)
$ echo $?
```

This will tell us whether vim will save that file, and whether vim's own configuration is good.

**Comment by taskwarrior** [comment]
_Christiaan on 2016-10-19T12:10:24Z says:_ 

 echo $?
0

**Comment by taskwarrior** [comment]
_Christiaan on 2016-10-19T12:14:20Z says:_ 

 How does vim talk to task in the background, maybe I can manually run that?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-10-19T12:29:46Z says:_ 

 They don't talk at all.  Task writes a file and launches vim.  Vim reads and writes a file (via you) and quits.  Tasks reads the file.

When vim returns an error, task captures it and shows it - can you paste it here?  It might be just that "exit 256" error you already posted, but please check.

**Comment by taskwarrior** [comment]
_Christiaan on 2016-10-19T12:46:55Z says:_ 

 Could it have something to do with file permissions?

> task add testing 4
Created task 4.
> task 4 edit
Launching 'vi "task.a0215a10.task"' now...
(saved with :wq)
"task.a0215a10.task" 45L, 1858C written
Editing failed with exit code 256.
> echo $?
0
> task 4 edit
Task is already being edited.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-10-19T12:49:29Z says:_ 

 That `$?` in the last example is the exit code form task, not vim.  Shouldn't be permisisions, unless your umask is something strange.  What are the permissions on that file in ~/.task?

**Comment by taskwarrior** [comment]
_Christiaan on 2016-10-20T10:15:14Z says:_ 

 I found an issue. Vi exits with code 1 when a relative path is used, probably because of a plugin

```
$ date > foo
$ vi ./foo 
(:wq)
$ echo $?
1
```

**Comment by taskwarrior** [comment]
_Christiaan on 2016-10-20T11:03:01Z says:_ 

 It's actually the plugin manager vim-plug causing the non-zero exit code. I upgraded vim from 7.3 to 8.0 using homebrew and that solved the issue.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-10-20T14:45:55Z says:_ 

 Alright, thank you for the data, this will help diagnose other problems.  Closing the issue.

**Comment by pbeckingham** [comment]
[TW-1862_taskrc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756440/TW-1862_taskrc.txt)

**Comment by izaakm** [comment]
I'm getting this same error.

Disabling vundle plugin manager resolves the issue.
Is there anyway to get taskwarrior to work around this?

**Comment by izaakm** [comment]
Adding `editor=vim --noplugin` to my .taskrc solved this problem for me.

```
$ vim -version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2018 12:07:57)
```
