### ISSUE TITLE
[TW-1865] Print number of tasks which will be modified when modifying many tasks

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1878]
_Sujeevan Vijayakumaran on 2016-11-01T09:05:25Z says:_ 

 When modifying more than one task with a filter it might be good to know how many tasks will be modified in a batch.

right now:
$ task due:today status:pending count
> 12
$ task due:today status:pending mod due:tomorrow
>   - Due will be changed from '2016-11-01' to '2016-11-02'.
> Modify task XX (yes/no/all/quit)

The output could be something similar like this:
$ task due:today status:pending mod due:tomorrow
>   - Due will be changed from '2016-11-01' to '2016-11-02' for *12 tasks*.
> ...

This is mostly useful, when you for example forget to specify "status:pending" and modify a lot more tasks (including completed task) than you might expect.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-11-01T09:05:25Z
Modified: 2017-01-16T21:22:51Z
```

**Comment by drehak** [comment]
It looks like this was implemented in https://github.com/GothenburgBitFactory/taskwarrior/pull/2538.

```
$ task due:today status:pending mod due:tomorrow
This command will alter 3 tasks.
  - Due will be changed from '2022-03-09' to '2022-03-10'.
Modify task 42 'Revise trig'? (yes/no/all/quit) 
```

**Comment by drehak** [comment]
@tbabej Could this be closed as well?

**Comment by sebu06** [comment]
That should have been included in my pull request - I'm closing this one.
