### ISSUE TITLE
[TW-1874] Replacing task description with empty brackets with optional "or"s in them.

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1887]
_Andras Novoszath on 2016-12-16T11:22:23Z says:_ 

 Time-to-time, some of my tasks' description is replaced by a combination of brackets, empty spaces and "or"s.

Sometimes I just see the result, but below is a recent example:

```
$ tw pro:xmas mod due:today
  \- Description will be changed from 'search books for Csilla' to '( )'.
  \- Due will be changed from '2016-12-18' to '2016-12-16'.
Modify task 96 '( )'? (yes/no/all/quit) no
Task not modified.
```

Another case I noticed only later, that there are tasks with the description:
bq. '( or or or or )'

Sometimes, the same move also alters the labels.

I could revert the changes by undo (if they were recent), or manually (if I noticed them only later).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-12-16T11:22:23Z
Modified: 2017-01-16T21:30:21Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2016-12-16T12:35:11Z says:_ 

 I haven't seen this one before.  Is your 'tw' an alias, bash function, symlink or rename?  Was any additional white space entered on that command line?

Note: 2.4.4 is two releases old, and the latest (2.5.1) was a focus on bug fixes only, so if at all possible, please upgrade.

**Comment by taskwarrior** [comment]
_Andras Novoszath on 2016-12-17T18:26:02Z says:_ 

 tw is simply an alias for 'task', there was no additional white space (as far as I can tell).

**Comment by tbabej** [comment]
Closing due to old age (and for being reported on an old release). If somebody encounteres this issue on modern TW version, please let us know!
