### ISSUE TITLE
[TW-1879] Does not work with Google Drive

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1892]
_Tri Nguyen on 2016-12-25T05:58:55Z says:_ 

 If I set the `data.location` property to a local Google Drive path (i.e. `~/Google\ Drive/Notes/Task`, it doesn't work.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-12-25T05:58:55Z
Modified: 2017-01-11T13:06:15Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2016-12-25T07:23:32Z says:_ 

 Hi, can you please give more details? What do you mean by "it"? What do you mean by "doesn't work"? Do you get an error? If so, what is the error?

**Comment by taskwarrior** [comment]
_Dirk Deimeke on 2016-12-25T13:45:35Z says:_ 

 What happens when you run task? Please post the output.

**Comment by taskwarrior** [comment]
_Tri Nguyen on 2017-01-03T17:35:13Z says:_ 

 Hi, apologies for the late response. For some reason the comments did not send out a notification in my email, so I wasn't aware of it.

What I mean is, if I set the Google Drive path as the location, the tasks do not show up (i.e. `task` says `No matches`).

Here are some more debugging info:

{code}
:; cat ~/Google\ Drive/Notes/Task/pending.data
[description:"Get passport photo" entry:"1482107818" modified:"1482107818" status:"pending" uuid:"90fd09c2-9eca-48d2-87f1-051b02c02396"]
[description:"Book hotel in Saigon" entry:"1482107818" modified:"1482107818" status:"pending" uuid:"2a5e2f42-f271-4078-9a97-5f567f245cee"]
[description:"Example Task" entry:"1482107818" modified:"1482107818" status:"pending" uuid:"d39f925c-758f-4cc3-b103-0bbcb8489397"]
{code}

{code}
:; task rc.debug=1
Timer Config::load (/usr/local/share/doc/task/rc/dark-256.theme) 0.000212 sec
Timer Config::load (/Users/tri.nguyen/.taskrc) 0.001381 sec
No context.
Hook directory not readable: /Users/tri.nguyen/Google\ Drive/Notes/Task/hooks
Parse Tree (before command-specifіc processing)
  _original_args
    task next rc.debug=1
  _args
    word basename='task' raw='task' BINARY
    identifier canonical='next' raw='next' DEFAULT CMD READONLY SHOWSID RUNSGC USESCONTEXT ALLOWSFILTER
    pair modifier='debug' name='rc' raw='rc.debug=1' separator='=' value='1' CONFIG ORIGINAL

No context.
Filtered 0 tasks --> 0 tasks [pending only]
  pending.data -- - T0000+000~000 L0000+000
completed.data -- - T0000+000~000 L0000+000
     undo.data -- - T0000+000~000 L0000+000
  backlog.data -- - T0000+000~000 L0000+000

Perf task 2.5.1 - 20161225T024229Z init:3356 load:13 gc:1 filter:166 commit:3 sort:0 render:0 hooks:1 other:299 total:3839

[task next rc.debug=1]
Configuration override rc.debug:1
No matches.
{code}

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-07T14:47:30Z says:_ 

 Can you show the *exact* line in the rc file please?

```
$ grep data.location ~/.taskrc | od -c
```

**Comment by taskwarrior** [comment]
_Tri Nguyen on 2017-01-09T15:49:16Z says:_ 

 Hi, it is
{code}
data.location=~/Google\ Drive/Notes/Task
{code}

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-09T16:31:25Z says:_ 

 That's not the output I was looking for.  Meanwhile try removing the \.

**Comment by taskwarrior** [comment]
_Tri Nguyen on 2017-01-10T03:36:07Z says:_ 

 Thanks. Removing the \ seems to have fixed it.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-11T13:06:15Z says:_ 

 Not a bug.  Thanks for investigating.

**Comment by jcrben** [comment]
@taskwarrior is it possible to mark these types of things as `invalid` or `user-error` or something rather than `bug` and `wontfix`? 

it's a bit misleading - and further someone reading the issue archive might think that taskwarrior is not interested in fixing bugs!

Perhaps also avoid tagging reported issues with `bug` until it is confirmed...

**Comment by jcrben** [comment]
I'd be happy to help lend a hand in triaging (adding/removing labels and such), altho I'm still testing out taskwarrior to see if it works for me. It looks like there is an existing tag that fits - `not a bug`. These issues end up forming a knowledgebase and I often end up reading a bunch of them when I'm learning about a tool.

**Comment by pbeckingham** [comment]
I understand your use case here, and it's a good one.  But this requires additional effort.  So we're looking for help, but not looking for more stuff to do.  If you're willing to commit, let's talk.
