### ISSUE TITLE
[TW-1884] color theme locations inconsistent

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1897]
_John Florian on 2017-01-08T16:44:25Z says:_ 

 One of my favorite features of task is the ubiquity of the tool since most all of my work occurs in a shell though from a variety of hosts; not just my primary workstation.  My $HOME is mounted from NFS.  Upgrading my workstation to F25 required that I revise my taskrc to have `include /usr/share/task/solarized-dark-256.theme` but that means that running `task` from CentOS 7 now fails:
```
Could not read include file '/usr/share/task/solarized-dark-256.theme'.
```

Here's why, on CentOS:
```
$ rpm -ql task | grep solarized-dark
/usr/share/doc/task/rc/solarized-dark-256.theme
```

vs Fedora 25:
```
$ rpm -ql task | grep solarized-dark
/usr/share/task/solarized-dark-256.theme
```

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-01-08T16:44:25Z
Modified: 2017-02-03T23:05:20Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-08T21:08:53Z says:_ 

 So you have multiple OSes that use different paths for stuff.  My initial reaction is that it's not something that can be handled by task.

It's possible you could set up host-specific symlinks, and then "`include \~/redirect/solarized-dark-256.theme`".  The "`\~/`" is handled by task.  It might even be nice to support something like "`include $JOHNS_THEME_LOCATION/solarized-dark-256.theme`" where env vars are expanded.

Got any better suggestions?  I think this should probably morph into a feature request.

**Comment by taskwarrior** [comment]
_John Florian on 2017-02-03T22:57:15Z says:_ 

 I think it's nothing more than a packaging issue.  I don't recall having the problem in the past, but something must have changed.  I simply can't imagine that I'd not run task only in one OS all this time.  If [~fredde] still does the packaging, perhaps he can comment.

For a work around I'll simply copy the theme into ~/.task/ and use that.

**Comment by taskwarrior** [comment]
_John Florian on 2017-02-03T23:05:20Z says:_ 

 BTW, sorry for the slow response.  I'm still not getting email notifications from Jira.  I can't even figure out where the related settings are.  I browse my profile, but it must be not be very obvious... or I'm overly dense ATM.

**Comment by tbabej** [comment]
Agreed about this being a packaging issue. Symlinks could help unifying the taskrc config across different distributions,
