### ISSUE TITLE
[TW-1892] task list truncated without informing user of truncation.

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1905]
_masukomi on 2017-02-10T17:36:20Z says:_ 

 small terminal windows result in a truncation of tasks displayed BUT without the "truncated to..." message.  The attached output and screenshots were created on a terminal with `echo $COLUMNS " x " $LINES` saying `166  x  25`

Note that in the screenshot that `[task next] and a blank link` was output, but it is scrolled off the top.

```
 $ task _get rc.verbose
blank,header,footnote,label,new-id,new-uuid,affected,edit,special,project,sync,unwait,recur 
```

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-02-10T17:36:20Z
Modified: 2017-02-10T17:57:22Z
```

**Comment by taskwarrior** [comment]
_masukomi on 2017-02-10T17:42:54Z says:_ 

 additional notes: yesterday resizing did eventually cause it to produce the "truncated to..." message. Today i can't seem to find a size that does that. Making the terminal window large enough does result in it showing all my tasks (as expected with only 21)

**Comment by pbeckingham** [comment]
I think this is a terminal problem.

**Comment by pbeckingham** [comment]
![tw-1892_1____w_vmm__fish_](https://user-images.githubusercontent.com/7963/36643720-ae7278f4-1a1d-11e8-968c-964a7c38548c.png)

**Comment by FernandoNobel** [comment]
I am having this bug of not showing the truncated message. Is there any fix for this?

**Comment by tbabej** [comment]
@FernandoNobel we no longer have a reproducer here (the attachments seems not to have been migrated from Jira). That makes it hard for me to understand what the issue is. Maybe you can help?

**Comment by ghost** [comment]
I'm consistently getting the "{} tasks, truncated to {} lines" when executing it from neovim: `:!task`
