### ISSUE TITLE
[TW-1897] recurrence does not work with scheduled

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1910]
_Richard Brinkman on 2017-02-28T12:13:23Z says:_ 

 With recurring tasks only the wait and due dates are adjusted when child tasks are create. The scheduled date/time is not effected.

Scenario: I daily receive a news paper at 8:00. In my daily schedule I will read this after 18:00. I would like to enter this as:

<pre>
task add Read news paper wait:08:00 scheduled:18:00 recur:weekdays
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-02-28T12:13:23Z
Modified: 2017-06-06T23:33:37Z
```

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2017-06-01T10:54:45Z says:_ 

 Duplicate of TW-1508?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-06-06T23:33:37Z says:_ 

 Duplicate of TW-1508.

**Comment by meonkeys** [comment]
TW-1508 is #1534
