### ISSUE TITLE
[TW-1901] Non-cumulative burndown report

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1914]
_Joel Ostblom on 2017-03-11T22:08:34Z says:_ 

 As per https://answers.tasktools.org/questions/4915614/non-cumulative-burndown-report, I think it would be useful to display non-cumulative burndown charts.

I mostly use `burndown.daily` and while the current report is already very useful, it would be well complemented by a non-cumulative report, which would facilitate identifying peaks and trends in the amount of tasks created and completed each day or week. With the cumulative report it becomes difficult to notice when here is just a few additions/completions since they are contrasted with all the tasks ever added/completed. E.g. with around 50 tasks done and pending, it is difficult to see the impact I get from completing 1 extra task today, but that extra task would seem more important if I was only comparing it with what I did yesterday.

The new cumulative behavior would still be the default and the non-cumulative version could be added by appending `.nc` to the existing burndown reports, e.g. `burndown.daily.nc`.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-03-11T22:08:34Z
Modified: 2017-10-12T03:11:05Z
```

**Comment by DanielMowitz** [comment]
I'd like to work on this issue, given there is no reason not to do that.

**Comment by tbabej** [comment]
@DanielMowitz thanks for taking this on, I assigned you the issue :slightly_smiling_face: 

I think there is a slight design discussion to be had. Is this better implemented as a new report (as the issue sugests), or a perhaps a configuration option?

**Comment by DanielMowitz** [comment]
Well now that I'm presented with it, I personally think the version with it being a config option makes for a cleaner user interface.
