### ISSUE TITLE
[TW-1906] sync sub-command is missing from task(1) manual page

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1919]
_rjc on 2017-04-08T06:18:43Z says:_ 

 `task sync init` and `task sync` are described [here](https://taskwarrior.org/docs/taskserver/sync.html) but are not described in task(1) manual page.

The aforementioned manual page only mentions task-sync(5) manual page as a reference at the very end. task-sync(5) itself is still *not* a dedicated documentation of the sub-command but merely mentions it as one of three options to sync the task list.

It would be useful to have the `sync` sub-command documented in task(1) leaving the two other options - VCS or file hosting - as alternative ways of syncing.

This way you kill two birds with one stone: document the missing sub-command and promote your other project - taskd(1) :^)

You can even get rid of the task-sync(5) manual page altogether afterwards as it feels like it belongs in other forms of documentation, i.e. online tutorial, FAQ, etc. - not the manual pages of the software proper.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-04-08T06:18:43Z
Modified: 2017-04-08T11:57:59Z
```

**Comment by pbeckingham** [comment]
Thank you.
