### ISSUE TITLE
[TW-1909] Summary misses one character

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1922]
_Matthias Beyer on 2017-05-02T08:14:08Z says:_ 

 When displaying a task, the last character is not displayed in the description. This does _not_ apply to all my tasks but only a single one. I don't know how to reproduce this and how it is triggered. Just wanted to make sure this is recorded.

See screenshot "Description" field and the modification log.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-05-02T08:14:08Z
Modified: 2017-05-19T11:12:13Z
```

**Comment by taskwarrior** [comment]
_Dirk Deimeke on 2017-05-02T08:22:50Z says:_ 

 Hi Matthias!

Thank you for your report.

The reason for this behaviour is the Umlaut "ü". This is already fixed in 2.6.0.

Cheers

Dirk

**Comment by taskwarrior** [comment]
_Dirk Deimeke on 2017-05-02T08:23:26Z says:_ 

 Already fixed in 2.6.0 (development)

**Comment by taskwarrior** [comment]
_Matthias Beyer on 2017-05-19T11:12:13Z says:_ 

 Thanks. And thank you for your awesome work, too!

**Comment by pbeckingham** [comment]
![tw-1909_2017-05-02-100725_605x386_scrot](https://user-images.githubusercontent.com/7963/36643727-bd1db530-1a1d-11e8-914a-d82ee63a8db2.png)
