### ISSUE TITLE
[TW-1918] Russian l10n

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1931]
_ilmarranen on 2017-07-12T10:54:44Z says:_ 

 I made the Russian localization for Taskwarrior and in accordance with recommendations for submitting a patch I want to ask: does the project need this?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-07-12T10:54:44Z
Modified: 2017-10-12T06:40:01Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-10-12T03:18:34Z says:_ 

 In general Taskwarrior will probably migrate to Gettext in the future, if someone takes on the task.  Meanwhile yes please, provided the translation is against the 2.6.0 branch.

**Comment by taskwarrior** [comment]
_ilmarranen on 2017-10-12T06:40:01Z says:_ 

 Thanks for your reply. 
When translating, I was faced with the fact that following the instructions I receive 100% of translated phrases, but the application as a result does not have a full translation (without those phrases that can not be translated according to the instructions). Is this a disadvantage in coding?
For example - cli autocompletion help message (task + tab_key) in screenshot. !Screenshot_20171012_093738.png|thumbnail!

**Comment by php-coder** [comment]
> !Screenshot_20171012_093738.png|thumbnail!

@ddeimeke Are the images will be migrated too? At least links to the original images would be helpful.

**Comment by ddeimeke** [comment]
@php-coder Attachments are a manually added as well. That will take time, unfortunately that can not be done with a script.

**Comment by pbeckingham** [comment]
L10N has been dropped, in favor of future gettext implementation.

**Comment by pbeckingham** [comment]
![tw-1918_screenshot_20171012_093738](https://user-images.githubusercontent.com/7963/36643737-d9da14e8-1a1d-11e8-9926-17f7955f7499.png)
