### ISSUE TITLE
[TW-1920] Using due on an old date fails

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1933]
_Jean P. on 2017-07-17T20:47:46Z says:_ 

 $ task add dummy due:1988-01-01

'315529200' is not a valid date in the '' format.

and all previous dates fail too.

However, it succeeds starting january 2nd of the same year.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-07-17T20:47:46Z
Modified: 2017-10-12T03:19:36Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-10-12T03:19:36Z says:_ 

 Could you provide your dateformat settings please?

 
```
$ task show dateformat```

**Comment by pbeckingham** [comment]
Cannot reproduce with 2.6.0:

```
$ task calc 1988-01-01
1988-01-01T00:00:00
$ task calc 1988-01-02
1988-01-02T00:00:00
$ task calc 1987-12-31
1987-12-31T00:00:00
```
