### ISSUE TITLE
[TW-1923] If 'PS1' variable contain newline character TaskWarrior will not render labels correctly

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1936]
_Alexey Matyushin on 2017-08-08T18:50:41Z says:_ 

 Hi there,

 

*The issue:* If 'PS1' variable contain newline character ('\n') TaskWarrior will not render labels correctly.

 

`Works well: export PS1='[\[\033[33m\]\u\[\e[0m\]@\[\033[1;31m\]\h\[\e[0m\]]\[\033[0m\] \{\W} \{\D\{%F %T`\[\033[1;34m\]\[\033[0m\]$ '`

`Doesn't work well: export PS1='[\[\033[33m\]\u\[\e[0m\]@\[\033[1;31m\]\h\[\e[0m\]]\[\033[0m\] \{\W} \{\D\{%F %T`{color:#f79232}*\n*{color}\[\033[1;34m\]\[\033[0m\]$ '`

 

Two screenshot attached (filename: Without_newline_in_bash_profile.png | With_newline_in_bash_profile.png)

Could you please have a look? I guess it will be very easy to fix.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-08-08T18:50:41Z
Modified: 2017-08-12T20:07:38Z
```

**Comment by taskwarrior** [comment]
_Alexey Matyushin on 2017-08-11T11:22:05Z says:_ 

 (at)Paul,

I've seen that you updated '*Fix Version/s*' field, and I have few questions, appreciate if you could answer them,

A) Will this issue be fixed in 2.6.0 release?

B) If yes, then do you have any information on when it is planned to be released?

 

Thanks a lot in advance!

Alexey

**Comment by taskwarrior** [comment]
_Tomas Babej on 2017-08-11T20:10:38Z says:_ 

 Fix Version field indicates the target version to fix the issue. However, this is always subject to change.

We have no estimate on when 2.6.0 will be released, it depends on many factors (and its final scope). My estimate is that we're talking about months here.

However, once this specific issue is fixed, the state of this bug will be changed to 'Fixed' and at that point, you can build the development branch.

As usually, the fastest way to get an issue fix is to contribute a patch :)

**Comment by taskwarrior** [comment]
_Alexey Matyushin on 2017-08-12T20:07:38Z says:_ 

 (at)Tomas,

Thanks for the answer!

Q. As usually, the fastest way to get an issue fix is to contribute a patch  ![Imported image](https://bug.tasktools.org/images/icons/emoticons/smile.png|width=16,height=16)

A. Yep, totally agree, but my skills are very limited here (C++) as I don't know that language. Glad to help in any other (possible) way.

 

Thanks a lot!

**Comment by pbeckingham** [comment]
Read the man pages please.  This is already supported via the `rc.reserved.lines` setting.
