### ISSUE TITLE
[TW-1924] No way to gracefully reset secondary client state after taskd reset

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1937]
_benthor on 2017-08-10T17:28:32Z says:_ 

 Today, I was bitten by  --TD-104--. After successfully following the fix recommended in --TD-104--, I was again able to sync my primary workstation task client with my taskd server.

 

However, I am also using TaskwarriorAndroid on my phone. When trying to sync this secondary client, I got the error

_Client sync key not found_

Googling this error was not helpful, I was unanimously told to do "task sync init" to sync my local changes to the server. I wanted the opposite thing.

After a lot of fruitless googling, I decided to make a bunch of backups and try "task sync init" on the secondary client anyway.

It failed. The error I got was:

_ERROR: Could not find common ancestor for ...._

So, at least the server state did not get corrupted by the stale data from the secondary client.

Imagine my surprise when before giving up, I did a last, desperate "task sync" on the secondary client and suddenly it was back in perfect working condition, including all the recent changes that had been made by my primary client.

Apparently the "task sync init" did not completely fail but in fact reset _something_ into a state where I could afterwards restore the server state again.

Thought I'd share.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-08-10T17:28:32Z
Modified: 2017-10-12T03:20:36Z
```

**Comment by taskwarrior** [comment]
_benthor on 2017-08-10T17:33:43Z says:_ 

 JIRA fucked up the formatting and I can't find a way to edit the first line. (Just ignore the strike through)

**Comment by djmitche** [comment]
Closed because taskserver/taskd is no longer supported.
