### ISSUE TITLE
[TW-1932] Support user certificates with encrypted keys for sync

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1944]
_Nick Bastin on 2017-10-29T15:22:03Z says:_ 

 If the keys for your user certs are encrypted, `task sync` just fails with:

`Bad CERT file. Decryption has failed.`
`Sync failed. Could not connect to the Taskserver.`

You can work around this with a wrapper script to task sync that temporarily decrypts the key first and adds its location to .taskrc and then deletes it on exit, but that's a bit cumbersome.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-10-29T15:22:03Z
Modified: 2017-10-29T16:13:12Z
```

**Comment by taskwarrior** [comment]
_Nick Bastin on 2017-10-29T16:08:34Z says:_ 

 This should be filed against TW, not TD.  I don't see a way to move it and it doesn't seem like I can close it myself.

**Comment by troubas** [comment]
Not sure if I should open a new ticket for this. In my opinion an encrypted server certificate should also be supported. Currently taskd just segfaults with last messages in log:
```
2018-08-12 19:10:55 CA          /var/lib/taskd/ca.cert.pem
2018-08-12 19:10:55 Certificate /var/lib/taskd/server.cert.pem
2018-08-12 19:10:55 Private Key /var/lib/taskd/server.key.pem
2018-08-12 19:10:55 CRL         /var/lib/taskd/server.crl.pem
2018-08-12 19:10:55 Server starting
```

**Comment by sstallion** [comment]
I just stumbled on to this issue as well using OpenSSL generated keys with taskd. Given that user keys are usually subjected to less strenuous security precautions, I think it would be prudent to permit use of encrypted client keys.

**Comment by felixschurk** [comment]
@djmitche 

I think this issue should be moved to https://github.com/GothenburgBitFactory/taskserver, I can not do it however.

**Comment by djmitche** [comment]
That repo is archived, so I don't think we can move the issue. But this is a client-side bug regarding the old sync system, so probably belongs here anyway. And, as that system is no longer used and the new system does not use client keys, I think we can close this.
