### ISSUE TITLE
[TW-1934] "sync needed" display line causes display to scroll

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1946]
_Hal Wine on 2017-11-17T17:48:31Z says:_ 

 (a) The default task report adjusts the number of tasks displayed base on screen size.

(b) When configured to sync to a server, any report will also print a message if a sync is needed: "There are local changes.  Sync required." at the end of the report.

When a report needs to limit the report to fit the screen (a) and there are local changes (b), the number of "lines available for report body" is off by one, and the headers scroll off the screen.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-11-17T17:48:31Z
Modified: 2018-01-10T22:20:04Z
```

**Comment by taskwarrior** [comment]
_Hal Wine on 2018-01-10T22:20:04Z says:_ 

 Found workaround:  add to your `taskrc` file:
``` `I often need to sync`
 reserved.lines = 3 ```

This leaves room for 2 messages, which works for me.

**Comment by pbeckingham** [comment]
Thanks for posting the workaround.
