### ISSUE TITLE
[TW-1935] Separate verbosity category for rc overrides

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1947]
_Paul Fenwick on 2017-11-23T21:13:52Z says:_ 

 ## Summary

"Configuration override..." messages would be even better with their own verbosity category.
## User Story

I have TaskWarrior integrated into my shell-prompt, to let me know when I have important tasks (over-)due. I turn off hooks when TaskWarrior runs as part of my prompt by using `rc.hooks=off`, however this means I get messages for every prompt telling me I've done this:

{code}
Configuration override rc.hooks:off
{code}

I can override this by using `rc.verbose=nothing rc.hooks=off`, but then I don't get messages when tasks un-wait themselves, and I _really_ want these as they're a primary way that I start doing things.

I could use `rc.verbose=unwait`, but that implies `rc.verbose=footnote`, which means I get the configuration override messages again. So I have to choose between missing tasks unwaiting themselves, or getting extra config messages I'm not after.

Having hooks off by default and turning them on in my `t` alias doesn't help here either, because I don't want to see the config override messages then, either.

This ticket is me wish-listing that config override messages had their own verbosity category, so I can have footnotes turned on, but override messages turned off. :)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-11-23T21:13:52Z
Modified: 2017-12-02T18:08:28Z
```

**Comment by taskwarrior** [comment]
_Paul Fenwick on 2017-11-24T17:45:16Z says:_ 

 Update: I have a patch, but my day is filled with many hours of flights, so it may take ~24hrs before I can send in a PR. :)

**Comment by taskwarrior** [comment]
_Paul Fenwick on 2017-11-26T23:14:04Z says:_ 

 Patches attached!
*  The first just adds some in-line documentation, with no code changes. I wrote it for myself while figuring out how things work. Totally optional.
*  The second adds an `override` verbosity, which implies `footnote`. This controls whether `Configuration override rc...`messages get displayed. It's enabled by default, and has no impact on overrides from environment variables, as they happen while the context is being constructed.
*  The third just adds some vim hints. Again, totally optional.

I'm running this locally and it's working great, but happy to take requests for adjustments if desired.

~ Paul

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-12-02T18:08:28Z says:_ 

 Patches applied and pushed.  Thank you.  Nice improvement.

**Comment by pbeckingham** [comment]
[TW-1935_0001-Docs-CLI2-Additional-dev-docs-for-applyOverrides.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755354/TW-1935_0001-Docs-CLI2-Additional-dev-docs-for-applyOverrides.patch.txt)
[TW-1935_0002-CLI2-Config-Add-override-verbosity-option.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755355/TW-1935_0002-CLI2-Config-Add-override-verbosity-option.patch.txt)
[TW-1935_0003-CLI2-Context-Add-vim-hints.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755356/TW-1935_0003-CLI2-Context-Add-vim-hints.patch.txt)
