### ISSUE TITLE
[TW-1940] Pure numerical tags not recogniced 

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1952]
_Peter Vitt on 2017-12-08T10:55:20Z says:_ 

 I recently started to tag some tasks with +2017 to clearly indicate what needs to be done before new year's eve. But this tag behaves a little strange:

`$ task add +2017 +work Testtask`
`Created task 82.`
`$ task add +work +2017 Testtask`
`Created task 83.`
`$ task 82 83 list`

`ID Age Tags Description        Urg`
`82 15s work +2017 Testtask      0.8`
`83 6s  work +2017 Testtask      0.8`

`2 tasks`

When I edit the task, it looks like this:

`$ task 83 edit`
`Launching 'vi "task.f9e5cba1.task"' now...`
`Editing complete.`
`Edits were detected.`
`Description modified.`
`$ task 82 83 list`

`ID Age  Tags      Description        Urg`
`83 6min 2017 work Testtask            0.9`
`82 7min work      +2017 Testtask      0.8`

`2 tasks`

The documentation says:
```Tags are simply one-word alpha-numeric labels, and a task may have any number of them.```
So it seems that pure numerical tags are possible, but somehow the command line parser doesn't like them!?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2017-12-08T10:55:20Z
Modified: 2017-12-10T05:30:08Z
```

**Comment by taskwarrior** [comment]
_Peter Vitt on 2017-12-08T10:59:01Z says:_ 

 Hmm, unfortunately, the description doesn't really show the problem. Look at this:

`$ task 82 info`

`Name          Value`
`ID            82`
`Description   +2017 Testtask`
`Status        Pending`
`Entered       2017-12-08 11:34:29 (22min)`
`Last modified 2017-12-08 11:34:29 (22min)`
`Tags          work`
`Virtual tags  PENDING READY TAGGED UNBLOCKED`
`UUID          30ccbbd4-e2d1-4176-b6a8-aec40408fc3a`
`Urgency        0.8`

`    tags    0.8 *    1 =    0.8`
`                         ------`
`                            0.8`

The tag +2017 isn't recognized as tag, but is added to the description. Even when defining as

`$ task add +2017 +work Testtask`

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-12-10T05:30:00Z says:_ 

 It doesn't lie numeric tags that look like dates or math.  Let's leave this open, and wee what 2.6.0+ bring...

**Comment by pbeckingham** [comment]
I think we need to keep tags as alpha-numeric.

**Comment by php-coder** [comment]
> The documentation says:
> Tags are simply one-word alpha-numeric labels, and a task may have any number of them.

Seems like documentation should be updated then. It's not obvious that "alpha-numeric" implies "should start from a letter".
