### ISSUE TITLE
[TW-1943] Brute force edit uses Nano despite setting EDITOR=vim

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1954]
_Jeremiah Goerdt on 2018-01-09T17:14:47Z says:_ 

 When I attempt to brute force edit a task (eg 'task 7 edit') I am sent to the Nano editor. My .zshrc exports EDITOR to vim, my env shows that EDITOR=vim, and when I use 'EDITOR=vim task 7 edit' I get the same results. This is consistent when using bash as well as my default zsh.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2018-01-09T17:14:47Z
Modified: 2018-01-09T17:14:47Z
```

**Comment by pbeckingham** [comment]
I would like to know if `task diag` shows the correct value for EDITOR.

**Comment by pbeckingham** [comment]
The code uses `rc.editor`, and if not provided uses `$VISUAL`, and it not provided uses `$EDITOR`, and if not provided uses `vi`.
