### ISSUE TITLE
[TW-1950] Trailing \ in annotations or UDAs corrupts data file, sometimes crashes TW

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#1960]
_Ben Kelly on 2018-02-01T15:26:26Z says:_ 

 When editing a string UDA (with `task edit`) or the annotations (with `task edit` or `task annotate`) so that the line ends with \ (a literal backslash), the entry for the task is destroyed, becoming partially merged with the entry for the following task in the pending.data or complete.data file. This not only destroys the task, but can cause TW to assert.

I first ran into this while trying to enter a multiline value for a string UDA, but it's not neccessary that there be additional field text on the following line; just ending the line with a backslash is sufficient. While I initially thought this only affects UDAs, it appears to also affect annotations. It does *not* affect descriptions.

A shell script that demonstrates this, along with the results of running it on my machine, are attached.

An earlier repro, using a string UDA, is available at https://gist.github.com/ToxicFrog/0619365058f3a6e18bb6d7f341856a32

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2018-02-01T15:26:26Z
Modified: 2018-02-01T15:26:26Z
```

**Comment by aljelly** [comment]
I just encountered this. You don't even have to end the line with a trailing \\.

`task 1 annotate "Might\'ve already done this"`

I tried adding this annotation to a task and it ate up the rest of the task entry, exactly the same as reported.

What showed up in undo.data:
```
time 1525195319
old [description:"Report annotation (and others) escaping bug happens not just at the end of line" entry:"1525194633" modified:"1525194679" project:"Meta" status:"pending" uuid:"dbe74d7c-1d03-4d38-b9b8-f0343a8c86ad"]
new [annotation_1525195319:"Might\\---
```

(I was able to fix the task by manually editing pending.data and restoring the task from undo.data, so I didn't lose anything)

**Comment by ThomasAdam** [comment]
This problem is the same as #2018 -- the problem is that `\'` ends up being escaped twice, and the parser breaks itself.  I'll be uploading a patch to fix this next week, once I'm sure the test cases and my changes to the parser haven't broken anything else.

**Comment by tbabej** [comment]
Reproduced on 2.6.0.
