### ISSUE TITLE
Calendar error when no tasks are present

### ISSUE THREAD

**Issue by incaseoftrouble** [GothenburgBitFactory/taskwarrior#1970]
The `calendar` command shows an error when running with no tasks available. 

 * Reproduce: Create an empty context, e.g., `+next and -next`, and type `task calendar`.
 * Expected: An empty calendar, or, even better, something like "no tasks available".
 * Actual output: `Could not recognize argument '('.`. 

If run with a year as argument, e.g. `task calendar 2018`, a calendar is displayed. I guess the error lies within the function determining the range to be displayed?

Side Note: In this case ("false" context), the calendar still displayed recurrent due tasks, marking the days as "due" (even though `task all` is empty!)

`task diag` (running on Linux Mint 18.3)
```
task 2.5.0
   Platform: Linux

Compiler
    Version: 5.3.1 20160216
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.2.2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.4.9
 Build type: None

Configuration
       File: /home/###/.taskrc (found), 2625 bytes, mode 100644
       Data: /home/###/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: ###:###
         CA: /home/###/.task/taskd.ca, readable, 2260 bytes
      Trust: strict
Certificate: /home/###/.task/taskd.cert, readable, 3714 bytes
        Key: /home/###/.task/taskd.key, readable, 6254 bytes
    Ciphers: NORMAL
      Creds: ###

Hooks
    Scripts: Enabled
             (-none-)

Tests
      $TERM: xterm-256color (221x42)
       Dups: Scanned 100 tasks for duplicate UUIDs:
             No duplicates found
```

**Comment by tbabej** [comment]
Not reproducible in `2.5.1` or `2.6.0`.
