### ISSUE TITLE
Cannot bind to v4 & v6

### ISSUE THREAD

**Issue by madduck** [GothenburgBitFactory/taskwarrior#1972]
taskd honours the `family` setting in its config file, even defaults
to "any". However, only one `server` setting will ever be read, so
unless sys.net.ipv6.ip_nonlocal_bind is on, there is no way to make
it listen on IPv4 and IPv6.

It'd be best to let the config specify any number of `server` lines,
and then to bind them all.

**Comment by pbeckingham** [comment]
Taskwarrior doesn't bind to anything.  This is a Taskserver issue.  Take a look and see if this is already solved.

**Comment by madduck** [comment]
Oh gosh, I am so sorry, wrong project ;)
