### ISSUE TITLE
Please support all "smart dates" of libshared

### ISSUE THREAD

**Issue by madduck** [GothenburgBitFactory/taskwarrior#1977]
libshared defines a myriad of "smart dates" or aliases for relative dates: https://github.com/GothenburgBitFactory/libshared/blob/master/src/Datetime.cpp#L566

Unfortunately, taskwarrior only supports a subset thereof. For instance, using `due:eond` yields:

```
'eond' is not a valid date in the 'Y-M-D' format.
```

It would be nice if this limitation were lifted. Especially `eond` and `eonw` are very useful due dates.

**Comment by pbeckingham** [comment]
Already does.

```
$ task calc eond
2018-03-09T00:00:00
```
