### ISSUE TITLE
[feature] Task details and extra description

### ISSUE THREAD

**Issue by omtcvxyz** [GothenburgBitFactory/taskwarrior#1982]
For some tasks, it makes sense to attach a longer description and some details. For example, attaching a link would make it easier to get to the task completion faster. Whenever there is an assignment available on some website or some MOOC, application page, etc it is way easier to follow a link in task's details instead of actually remembering the link details. Also, details might include some thoughts/ideas on how to complete the task. E.g. I'd like to fix a bug and I need to remember few specific lines which cause an issue. Remembering these lines is hard, but writing these down in the task description seems reasonable enough.

**Comment by adeverteuil** [comment]
Hi @omtcvxyz,

Have a look at _annotations_ (the `annotate` subcommand in `man 1 task`) and [taskopen](https://github.com/ValiValpas/taskopen) 3rd party script.

**Comment by omtcvxyz** [comment]
Hi @adeverteuil,

Thank you very much for the reference! It looks exactly what I wanted it to be, but I was unable to find it myself.
