### ISSUE TITLE
Continuous integration, test coverage and other neat improvements

### ISSUE THREAD

**Issue by omtcvxyz** [GothenburgBitFactory/taskwarrior#1984]
I think it would be very beneficial for the project to take advantage of the CI. I have found [Travis CI](https://travis-ci.org/) to be very convenient for my personal projects: it's free, has amazing integration, provides a fancy way to display the build results. Setting up Travis would also allow running checks on each Pull Request to automatically see if it breaks anything or not, which is very useful almost all the time.

As a good example, https://github.com/GothenburgBitFactory/taskwarrior/issues/1979 would most likely not have happened if there was a CI build after each commit.

One more enhancement would be setting up the test coverage measurement along with Travis CI buildbots: [Coveralls](https://coveralls.io/) would generate useful reports and allow seeing coverage improvements/regressions, which would potentially benefit the project. There's [llvm-cov](https://llvm.org/docs/CommandGuide/llvm-cov.html) for the actual coverage information emission, this would have to run during the Travis CI build process.

**Comment by recollir** [comment]
We use flod for CI and is just needs to be reconfigured after the move to GH. Flod normally runs after each commit. See https://central.tasktools.org

**Comment by omtcvxyz** [comment]
@recollir Ah, okay, I didn't know that. I didn't find any "Reconfigure Flod after Github migrations" issue, so I guess this one could serve this purpose.

Though, the point about coverage stands.

**Comment by pbeckingham** [comment]
Coverage is something we're building into Flod.  Right now it's manual, and I run it only occasionally.  Soon we'll have automated coverage on all the clean builds.

All your points are valid, and we agree, it's just that our solution is in mid-migration, and offline.

**Comment by omtcvxyz** [comment]
@pbeckingham ah, okay, I see! Thank you very much for the explanation.
