### ISSUE TITLE
Taskwarrior Qt front end

### ISSUE THREAD

**Issue by omtcvxyz** [GothenburgBitFactory/taskwarrior#1985]
Even though I'm fairly new to Taskwarrior and don't know whether it's an issue for the other users, but since I have over few hundreds of tasks I constantly encounter the problem of efficient navigation. A good front end would solve this issue. [vim-taskwarrior](https://github.com/blindFS/vim-taskwarrior) and few other terminal-based frontends are not much better in terms of navigation. There is also [taskwarrior-web](https://github.com/theunraveler/taskwarrior-web) project, it's really nice, but I think it's still not very intuitive and does not provide fancy reports, neat visualizations and other things people love existing task managers for. A decent desktop application would also greatly improve usability: currently Taskwarrior is probably mostly used by the programmers because of the CLI interface and learning curve; creating a Desktop application would attract way more users, think of some great examples of open-source projects useful not only for the programmers and hence pretty popular (e.g. [transmission](https://transmissionbt.com/)).

I understand that a good desktop application is a significant effort, but since there is no mailing list for discussing such issues, I decided to create an issue to see what the developers think. There's nothing about front ends and desktop applications in 2018 roadmap, so I thought bringing it up might be useful for the long-term future.

Taskwarrior is already implemented in C++, so the choice of the Qt-based tool would be natural.

There are few very nice examples of pretty good GUI task managers out there:

* [Things 3](https://culturedcode.com/things/)
* [Trello](https://trello.com/)
* [Todoist](https://todoist.com/)

All of them miss some features I'd really want to have and also are not open-source. Creating some sort of competition in the form of Taskwarrior makes sense to me.

**Comment by recollir** [comment]
A GUI/desktop app is out of scope for this project. But we don't discourage it being developed outside of taskwarrior.
