### ISSUE TITLE
Enforce styleguide, possibly revisit code style and improve code health

### ISSUE THREAD

**Issue by kirillbobyrev** [GothenburgBitFactory/taskwarrior#1987]
[Taskwarrior Coding Style](https://taskwarrior.org/docs/coding_style.html) is honestly pretty vague in terms of describing what good code really looks like. Despite being slightly biased, I think the following actions make sense.

## Adopt an established coding style

As mentioned earlier, currently the coding style is pretty vague and probably somewhat strange. E.g. I find it strange to have both

> Indent code using two spaces, no tabs
> Stick to 80 columns where possible, although exceptions are fine

and

> Surround operators and expression terms with a space

First points make sense, but the latter is not only pretty uncommon (on how it's used: in general spases around operators and expressions are fine, but the project seems to have a convention of using a space before any opening brace e.g. before argument lists, etc: see https://github.com/GothenburgBitFactory/taskwarrior/blob/2.6.0/src/CLI2.h#L39), but takes up a lot of space, which is worth saving because of the 80 column-width limit.

Also, even this completely vague coding style is constantly violated (e.g. https://github.com/GothenburgBitFactory/taskwarrior/blob/2.6.0/src/CLI2.cpp#L592 and in many places in this file, which is the first one I simply took as an example).

My point is that the style generally used in Taskwarrior codebase is very similar to the [Google C++ Codestyle](https://google.github.io/styleguide/cppguide.html). Why not adopt it? It would also greatly decrease the cost of maintaining the codebase and enforcing this codestyle (due to the existence of a great number of tools for its enforcement).

## Use [Clang-Format](https://clang.llvm.org/docs/ClangFormat.html)

Upon fixing a code style it would make sense to start using Clang-Format, which is a very popular tool for enforcing proper formatting. It has a number of plugins for most common text editors, IDEs, tools and useful scripts (e.g. patch formatting [script](https://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting)). It supports a number of popular styles (and [configurable options](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)) including Google and LLVM styleguides out of the box.

## Use [Clang-Tidy](http://clang.llvm.org/extra/clang-tidy/)

Clang-Tidy provides a convinient way of ensuring codebase health through a number of [checks](https://clang.llvm.org/extra/clang-tidy/checks/list.html). Frequently running Clang-Tidy over the codebase makes sense to me, continuously generating reports is even better.

Personally, I like Neovim's approach - it provides analysis of the current codebase snapshot after each build in an [accessible form](https://neovim.io/doc/reports/clang/).

Along with https://github.com/GothenburgBitFactory/taskwarrior/issues/1984 it would probably greatly increase the codebase quality.

**Comment by pbeckingham** [comment]
First, #1984 is a separate issue, and one that we're desperately needing to address soon.  Assume that will be done.

The 80-column limit is really obsolete, and has been removed from the online docs, thank you for pointing that out.  I really only care about consistency and readability.  Whitespace is a big part of this for me.

The rules are deliberately vague, because I don't want to waste any time trying to describe a style, when I can just say "use the existing style for everything", which is one I'm happy with.  Run `git shortlog -s` and you'll see why the code formatting follows my style.

I'm not a big fan of automated formatting, there are always exceptions, and there are always cases where I don't like the result, especially when it undoes some carefully-aligned comment.  I don't think there is a good code formatter to cover all languages involved (CPP, C, Bash, Python, nroff, md, HTML ...), and I don't believe code formatting has anything to do with code quality.

**Comment by omtcvxyz** [comment]
Okay, I can get your point. Though in my humble opinion autoformatting got significantly better over time and can be freely used nowadays. My suggestion is that a more-or-less established guidelines improve readability and while this is obviously a cosmetic change I think it would be benefitial for some new contributions and overall project health.

Also, clang-tidy usage and reports are very helpful IMO.

Again, if you feel like the project doesn't need it - feel free to close the issue, I was just sharing my input which might not be applicable in terms of the project's scope and course, which is totally fine from my point of view.

**Comment by pbeckingham** [comment]
As stated, I don't like auto formatting, but I've looked at the clang-tidy checks, and those look very useful, and I want to use them.  Thank you for suggesting and persisting.

Leaving the ticket open until this is implemented in flod.

**Comment by jcrben** [comment]
> I don't think there is a good code formatter to cover all languages involved (CPP, C, Bash, Python, nroff, md, HTML ...)

If there's a specific language where you might be more open to it, I'd be interested. I'm mostly writing autoformatted code these days - it's less about readability for me and more about not having to break my flow to rearrange whitespace and such.
