### ISSUE TITLE
Unexpected spaces added to task with hyphen

### ISSUE THREAD

**Issue by KyleWJohnston** [GothenburgBitFactory/taskwarrior#1988]
Adding a task with a hyphen next to letters adds spaces on either side of the hyphen.

Example:
```
$ task add foo-bar
Created task 1.
$ task 1 info
...
Description   foo - bar
...
```

I am using Cygwin on Windows 10 and do not have this issue on another computer running Linux. Using quotes doesn't help. If multiple hyphens are used, it happens to each one. If there are already spaces next to the hyphen, nothing unexpected happens.

**Comment by pbeckingham** [comment]
This is already fixed in 2.5.1.  Note: There are no longer any releases made to Cygwin.
