### ISSUE TITLE
https://taskwarrior.org - "Your connection is not secure"

### ISSUE THREAD

**Issue by arkban** [GothenburgBitFactory/taskwarrior#1989]
I went to https://taskwarrior.org this morning and got this (from Firefox):

```
taskwarrior.org uses an invalid security certificate. 

The certificate is only valid for the following names: *.netlify.com, netlify.com 

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by recollir** [comment]
In the process of moving site to Netlify and re-issuing certificate. You caught us in the middle of DNS propagation. It is fixed for me at least. ;-)

**Comment by arkban** [comment]
Confirmed :)
