### ISSUE TITLE
Can't find export scripts

### ISSUE THREAD

**Issue by tom-doerr** [GothenburgBitFactory/taskwarrior#1992]
Taken from the man page:

>        task <filter> export
>               Exports all tasks in the JSON format.  Redirect the output to a file, if you wish to save it, or pipe
>               it to another command or script to convert it to another format. The standard task release comes 
>               with a few example scripts, such as:
> 
>                 export-csv.pl
>                 export-sql.py
>                 export-xml.py
>                 export-yaml.pl
>                 export-html.pl
>                 export-tsv.pl
>                 export-xml.rb
>                 export-ical.pl
>                 export-xml.pl
>                 export-yad.pl 
> 

I can't find those scripts anywhere, neither on my computer nor in the Github-Repository.
Could it be clarified in the man page where the scripts are?

**Comment by pbeckingham** [comment]
These are listed on the web site in the tools tab.

**Comment by pbeckingham** [comment]
Fixed.  Thanks.
