### ISSUE TITLE
color.overdue should be applied if task.due<now not task.due<today

### ISSUE THREAD

**Issue by xorbug** [GothenburgBitFactory/taskwarrior#1998]
Hi,
giving a look at https://github.com/GothenburgBitFactory/taskwarrior/blob/a8446f7f855292bad455835ee59962e6e2e5fde3/src/rules.cpp#L257 *colorizeOverdue()* checks the due date to be earlier than *today*. As consequence the task starts getting the overdue color only the day after the due date (you won't see the task colored as *color.overdue* during the same day as its *due* date). It should just check that the due date has been passed instead, i.e. *due* earlier than *now*.

As a reminder, @pbeckingham noticed on IRC that the function should have not passed its unit test.
If i'm understanding it right, the test for the overdue color rule is https://github.com/GothenburgBitFactory/taskwarrior/blob/a8446f7f855292bad455835ee59962e6e2e5fde3/test/color.rules.t#L120 which gets passed because the test case is a task due *yesterday*.  Maybe the test should be more stringent specifying a due time within the same day.

Thanks.

**Comment by pbeckingham** [comment]
Good bug report.  Thanks.
