### ISSUE TITLE
[EX-21] ledger integration

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#20]
_David Patrick on 2009-07-07T00:58:43Z says:_ 

 Tight integration will ledger (http://wiki.github.com/jwiegley/ledger) exposing all features to the interactive shell and allowing cross referencing ledger entries with tasks and contacts. While this is deep integration, we should do it without forking ledger, and while leaving ledger CLI usage unchanged.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-07-07T00:58:43Z
Modified: 2014-02-09T02:43:22Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-14T04:15:11Z says:_ 

 Extension

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-07-29T21:13:05Z says:_ 

 To test for not being tied to ledger, it should work with hledger[1] (which uses the same ledger format) as well.

[1]http://hledger.org

**Comment by taskwarrior** [comment]
_David Patrick on 2011-07-29T23:22:45Z says:_ 

 as an hledger user, I'd have to say "hell yeah!"

I'm even now scheming about how to integrate hledger and roundup-tracker, and the idea is quite straight forward (compared to some of my more convoluted ones) ;

add a "cost" field to the issue schema, that will contain a link to the associated .journal file

add back-links to specific issues within transaction metadata, in the *ledger file, like "  ; issue;243

make a template that looks up correlated transaction date in associated file, and display those transactions with the issues

$CDN 0.02

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2012-03-14T14:24:04Z says:_ 

 Best implemented as an extension.

**Comment by taskwarrior** [comment]
_David Patrick on 2012-12-29T07:06:59Z says:_ 

 hledger add plugin;

If you have tasks that are related to financial transactions, like "pay this" or "buy that" (and you know you do) this plugin serves to make completion of such a task launch *hledger add*, which is an interactive command for recording financial transactions.

This plugin is triggered by a description that startswith buy, pay, sell, deposit, withdraw (user-definable list) or with the use of a specialtag +ledger. It should also use two UDAs; account:name and amount:number. When this task is completed, the related hook, seeing pay, buy or +ledger, triggers a script that launches *hledger add* and provides arguments in-line. 

For example, let's create a task

 task add pay cel phone bill due:eom account:expenses.phone amount:62.53

on completion of this task, hledger add is called, and details are re-formatted as arguments, as in

 hledger add cel phone bill expenses:phone 62.53

and hledger add starts up interactively, and populates the defaults using these task details. 
The keywords "pay" and "buy" would be omitted, and that +ledger tag would not be conveyed. 
If you have entered a phone bill before, hledger will use that previous transaction to provide the "matching" account default (think double-entry) with "description" translating to "payee".
The upshot is that marking the task done AND entering the details into your accounting system, 
could be as easy as

 tw 142 do < enter >< enter >< enter >< enter >< enter >< enter >.< ctrl-c >

caveats; 
1) this in-line behavior of *hledger add* is not yet implemented, just (another) feature request at hledger.org.
2) the above <enter><enter> simplicity presumes that you don't want to change, or add to the defaults.
3) there is other compatible task data that might be desirable to convey to the transaction, like tags and annotations, 
and these, while also possible, are not detailed here.

Tracking finances is important and task-related, this (simple?) plugin could get that ball rolling.
While handy for taskwarrior users who want to track finances, this plugin would answer a very real need among *ledger users.  Scheduling, tracking and anticipating transactions, especially recurring ones, is a feature that *ledger is sorely lacking in, taskwarrior to the rescue. 
(*ledger indicates both ledger-cli.org and hledger.org)

**Comment by taskwarrior** [comment]
_David Patrick on 2013-04-03T00:17:14Z says:_ 

 UPDATE: After some hints, suggestions, pleading and eventually cash, *hledger add* can now use CLI arguments to populate a transaction record. So if your task was "pay phone company", and you wanted to record that in a ledger, then the task record could become a transaction record. A post-completion hook might drive this with the help of a simple +txn tag, outputting something like;

 hledger add 2013-14-01 'phone company' expenses:telco:phone 52.78 assets:ABank:chequing

The date would be the completion date, the "payee" = task description, the < account > and < amount > fields could be stored as UDAs or as "properties" (annotation = account: expenses:telco:phone, annotation = amount: 52.78, etc) and if fewer than these 5 fields are provided, the hledger-add goes interactive. 

see: http://hledger.org/MANUAL.html#add although the [arguments] behavior is not yet documented

**Comment by pbeckingham** [comment]
No plans to implement.
