### ISSUE TITLE
Add more hints on how to reset the current context

### ISSUE THREAD

**Issue by php-coder** [GothenburgBitFactory/taskwarrior#2002]
When I need to look at the tasks outside of the project, I have to reset/change the current context. As I do this not so frequently and I'm relatively new user, I can't remember how exactly to reset the context.

**What command(s) did you run?**
- `task context reset`
- `task context default`
- `task context help`
- `task context -h`

**What did you expect to happen?**
`task context` should give me advice on how to remove the current context, like `task context <name>` does.

So, I suggest to modify an output of the `task context` to also show the following:
```
Use 'task context none' to remove active context.
```

**Comment by pbeckingham** [comment]
Good suggestion.
