### ISSUE TITLE
task shell not launching

### ISSUE THREAD

**Issue by Whyglobaleyes** [GothenburgBitFactory/taskwarrior#2003]
Hi All, 
Newbie here usual apologies,

First of all ... **Thank You**. I loved TW as soon as I found it (tho I'm too indisciplined to stick to it for long) ... the best bit was that it gave me a good reason to get my head round how to store data in human readable files, using json and what a clever data model it uses! 

So I'm making a fresh effort to organise myself and TW is central to it. Previously I had version 1.** but I've got a fresh (xubuntu) system so I just downloaded version 2.5.1. Problem is that I can't access the shell and just get the message " `sh: 1: tasksh: not found` "

Solutions Tried:
[1] Remove & purge then re-install (sudo apt-get install taskwarrior)  ==> no change, same response
[2] Remove & purge then sudo apt-get install task ==> wouldn't install :: error mesasge = " `task : Depends: taskwarrior (= 2.5.0+dfsg-1build1) but 2.5.1+dfsg-6 is to be installed`  " ==> back to installing TW
[3] Tried installing " https://github.com/GothenburgBitFactory/taskshell " ==> failed :: this might be a bug-report of it's own - or maybe an admission of incompetence [a] I couldn't clone the repo using git, it would hang in the middle of the src folder, tried a few times then downloaded the zip [b] maybe i'm stupid but I got errors on the cmake command onwards " `CMake Error at src/CMakeLists.txt:26 (add_library):  Cannot find source file:   libshared/src/Color.cpp`  "

Anyone got any ideas that will help me please?
BW
ygii

* What command(s) did you run?
task shell

* What did you expect to happen?
launch the shell environment

* What actually happened?
error message as follows;
sh: 1: tasksh: not found

* Paste the output of the ```task diag``` command.
=== start task diag ===
task 2.5.1
   Platform: Linux

Compiler
    Version: 7.2.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.9.5
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.16
 Build type: None

Configuration
       File: /home/###/.taskrc (found), 1682 bytes, mode 100664
       Data: /home/###/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: taskwarrior.inthe.am:##### 
         CA: /home/###/.task/###/ca.cert.pem, readable, 2405 bytes
      Trust: ignore hostname
Certificate: /home/###/.task/###/private.certificate.pem, readable, 2462 bytes
        Key: /home/###/.task/###/private.key.pem, readable, 3664 bytes
    Ciphers: NORMAL
      Creds: inthe_am/###/************************************

Hooks
     System: Enabled
   Location: /home/###/.task/hooks
             (-none-)

Tests
      $TERM: xterm (120x30)
       Dups: Scanned 2 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 2 tasks for broken references:
             No broken references found

=== end task diag ===

**Comment by pbeckingham** [comment]
Hi,

Tasksh is not part of the taskwarrior package, it’s a separate product.  Download the stable 1.2.0 tarball from this page:

https://taskwarrior.org <https://taskwarrior.org/>

And follow the instructions in there.

Paul

**Comment by pbeckingham** [comment]
Thank you, that's kind.  Do this:

1. Go to https://taskwarrior.org
2. Click on this
<img width="444" alt="screen shot 2018-03-29 at 6 30 55 pm" src="https://user-images.githubusercontent.com/7963/38117958-e1359326-3385-11e8-82ed-e497d4feab1d.png">
3. Run these commands:

```$ tar xzf tasksh-1.2.0.tar.gz```
```$ cd tasksh-1.2.0```
```$ cmake .```
```$ make```
```$ sudo make install```

**Comment by Whyglobaleyes** [comment]
Perfect! Happy days.
Thank you. 
BW 
ygii
