### ISSUE TITLE
"shell" should not be expand to "exec tasksh"

### ISSUE THREAD

**Issue by Arvedui** [GothenburgBitFactory/taskwarrior#2004]
I ran the command ```task add shell``` I expected a task with the description "shell" would be added, instead I got a task with the description "exec tasksh"

Output of ```task diag```(parts related to sync removed):
```
task 2.5.1
   Platform: Linux

Compiler
    Version: 5.3.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Mar  9 2016 20:12:54
      CMake: 3.4.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.4.10
 Build type: 

Configuration
       File: /home/marcel/.taskrc (found), 2873 bytes, mode 100644
       Data: /home/marcel/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: vim

Hooks
     System: Enabled
   Location: /home/marcel/.task/hooks
             (-none-)

Tests
      $TERM: xterm-termite (266x55)
       Dups: Scanned 460 tasks for duplicate UUIDs:
             Found duplicate 0ae4d299-995a-4478-bff4-650ea4443cce
 Broken ref: Scanned 460 tasks for broken references:
             No broken references found

```

**Comment by pbeckingham** [comment]
Do you have an alias that does that expansion?  If so, remove it.

**Comment by Arvedui** [comment]
I have no alias configured in my taskrc

**Comment by pbeckingham** [comment]
Really?  Does this command not show it?

```
$ task help | grep Aliased
```

**Comment by Arvedui** [comment]
It does indeed show it, but as I said it is not in my configuration, nor is it any of the files that are accessed according to strace before the help message is printed.

**Comment by pbeckingham** [comment]
Add this:

```
alias.shell=shell
```

**Comment by Jens0512** [comment]
> I ran the command task add shell I expected a task with the description "shell" would be added, instead I got a task with the description "exec tasksh"

Exactly the same happens to me.

**Comment by pbeckingham** [comment]
Fixed.
