### ISSUE TITLE
Show task ID when a task is un-waited

### ISSUE THREAD

**Issue by KarlMW** [GothenburgBitFactory/taskwarrior#2012]
When a task is un-waited, it says:  
   `Un-waiting task 'task description here'`

It would be helpful if this showed the relevant task ID so that I could immediately interact with the task, without an intermediate step of looking up the ID.

eg. there are often times when a task is unwaited and I know straight away that the task is either complete, or I can't do it when I planned and want to wait it again.  In those instances I want to be able to modify the task without needing to first lookup the task ID.

Ideally, as an extra thing, the information displayed/order would be fully configurable (in the same manner as a report).  I favour having the Task ID at the start of the line for all my tasks (for me it is easier to see the ID associated with a description when it is right next to the description, rather than scanning across multiple columns and potentially jumping a row).

**Comment by pbeckingham** [comment]
Good suggestion.

**Comment by tbabej** [comment]
Indeed, this was fixed by #2033.
