### ISSUE TITLE
Unrecognized archive format

### ISSUE THREAD

**Issue by DMor1** [GothenburgBitFactory/taskwarrior#2014]
Following the installation instructions under `Download the tarball, and expand it` the file seems malformed (I successfully built and installed from source instead).

1. Download file `curl -O https://taskwarrior.org/download/task-2.6.0.tar.gz`

2. Extract `tar xzf task-2.6.0.tar.gz`
```
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

I grabbed the download link from the website and was able to download and extract https://taskwarrior.org/download/task-2.5.1.tar.gz successfully. Further analysis of the original file reveals it's actually a `Page Not Found` html file rather than a `.tar.gz` archive.

**Comment by pbeckingham** [comment]
There is no `task-2.6.0.tar.gz` file, that version has not been released.  You downloaded a missing link, which means `curl` put a 404 page into your file named `task-2.6.0.tar.gz`, and you're wondering why it's not a zip file.

**Comment by kaushikgopal** [comment]
worth mentioning, a reason most folks might run into this issue is because the `README` for branch `2.6.0` has this version in the instructions; and github defaults to showing the active development branch.

Paul is right though, and this doesn't exist yet as of this date.

**Comment by tbabej** [comment]
Good point @kaushikgopal, we should perhaps change the link to use some sort of latest release permalink in order to avoid this problem.

**Comment by markjballard** [comment]
Why is this issue closed when it is not fixed?

It is essentially a documentation bug, leading new users into a swamp on their very first step with TaskWarrior. The result is that the install instructions do not work; the user then wastes time trying to make it work, learning eventually that it is a bug in the documentation. I've got half an hour to have a quick look at this productivity app, and my first experience was a waste of time.

Step 1 of the install instructions is this broken command: 

`$ curl -O https://taskwarrior.org/download/task-2.6.0.tar.gz
`
The correct download url is: https://taskwarrior.org/download/task-2.5.3.tar.gz

**Comment by tbabej** [comment]
Originally, the 2.6.0 was actually not the default branch set on this repo, so in order to hit this, you'd have to consciously change branches to the unreleased version (hence the link being broken).

Given we made the 2.6.0 the default branch (the one that gets shown when the person visits the repo), I agree we should fix this. And the best way to fix this would be to actually release 2.6.0 and make that archive available, which I am hoping to do today :slightly_smiling_face:

**Comment by markjballard** [comment]
Ha ha. Well, I'm very pleased then to eat my hat.

**Comment by tbabej** [comment]
@markjballard with 50 seconds to spare, the `2.6.0` release tarball was made available on `taskwarrior.org` in https://github.com/GothenburgBitFactory/tw.org/commit/9ce965bf0aa2eda904d45fb0b956cdb079e7d7fc I hope the hat is made out of edible materials :cowboy_hat_face:

**Comment by markjballard** [comment]
@tbabej, I don't know what was in my hat, but it was quite chewy, and before I knew it, I'd feverishly deleted all the comments by which I'd complained here about your version 6 links not working. Now I find I cannot undelete them, and I have a cold head as well as cold feet. At least, I see an opportunity for salvation in your Getting Things Done app. I wonder if it has an anti-vacillation mechanism? Congratulations on version 2.6.
