### ISSUE TITLE
[feature request] blocks: add dependency when creating the sub task

### ISSUE THREAD

**Issue by sclo** [GothenburgBitFactory/taskwarrior#2019]
Feature request: blocks sub command

Actually, we have to add/manage the dependencies on the parent task, in a second setp : 
```
# task add feature XY 
Created task 1.
# task add Code X
Created task 2,
# task add Code Y
Created task 3.
task add Review
Created task 4.
```
Next we need to modify parent tasks 4 and 1 to add dependencies
```
# task modify 1 depends:2,3,4
# task modify 4 depends:2,3
```

Resulting in the following output
```
ID Age  D     Project Description      Urg
 2 1h                          Code X             9
 3 1h                          Code Y             9
 4 1h   2 3                  Review            4.8
 1 1h   2 3 4               feature XY       -4
```

I would be great if we could add dependency in single command on the sub task :  
```
# task add feature XY
Created task 1.
# task add blocks:1 Code X
Created task 2.
# task add blocks:1 Code Y
Created task 3.
```
Each sub task command updates 'Dependencies:" field of the parent task like it's done with 'depends:' sub command actually.

More complicated example : 
```
# task add feature XY
Created task 1.
# task add blocks:1 Review
Created task 2.
# task add blocks:1,2 Code X
Created task 3.
# task add blocks:1,2 Code Y
Created task 4.
```

I could simply add another sub task with correct depedencies in a single command
```
# task add blocks:1,2 Patch Z
```

The resulting output should be something like this : 
```
ID Age  D     Project Description      Urg
 2 1h                          Code X              9
 3 1h                          Code Y              9
 5 1h                          Patch Z              9       
 4 1h   2 3 5              Review             4.8
 1 1h   2 3 4 5           feature XY       -4
```

Thanks for reading, regards

**Comment by pbeckingham** [comment]
Using the phrase "A block B" is identical to saying "B depends on A".

The reason I'm not implementing a `blocks` command is that (a) we already have the `depends` attribute, and (b) when we us this command:

```bash
$ task <id> modify depends:<other>
```

We are directly modifying `<id>`, and not `<other>`.  A `blocks` command would require that we refer to `<other>` but modify `<id>`.  I'm not happy with that hidden modification.

Taskwarrior has virtual tags `BLOCKED` and `BLOCKING` to describe either side of the link.

**Comment by JonasDralle** [comment]
Don't want to ghost this issue but since this ticket is easily searchable for some queries I might add that this behaviour can be archievend via this script: [on-modify.blocks_attr.py](https://gist.github.com/wbsch/a2f7264c6302918dfb30)

- found via https://taskwarrior.org/tools/

**Comment by ellcs** [comment]
Any chance that this get's merged when a pull request is made?

**Comment by djmitche** [comment]
Depends on the implementation of course, but I understand dependencies well enough to review such a thing, so yes -  good chance

**Comment by adriangalilea** [comment]
I too find this is the proper UX, and would `blocks` to be a command.
