### ISSUE TITLE
Add filter to export active context tasks

### ISSUE THREAD

**Issue by lasers** [GothenburgBitFactory/taskwarrior#2028]
Hi, I'm suggesting a feature enhancement.

A context filter for users to export active context tasks instead of all tasks without running command `task` twice repeatedly. First to run `task context show` to find the context filter, second to run `task export` with the context filter.

The use case is to offer more leeway with third-party customization where users can specify what tasks to display using `filter` config that would be passed on to `task export <filter>` instead of creating additional config for users. I also can't find a clean filter option to only export active context tasks.

TW-1566 removed the context from `task export` to avoid issues with third-party tools integration. I make this issue to see if it is sensible for users to be able to export active tasks via a context filter.

Thank you.

**Comment by pbeckingham** [comment]
No, there should be no context filter used with export.  Export is used by extensions, changing its behavior would be wrong.

Export already allows a filter.
