### ISSUE TITLE
Fix vim's ftdetect

### ISSUE THREAD

**Issue by aleprovencio** [GothenburgBitFactory/taskwarrior#2032]
The detection of a taskrc filetype only considers if the filename is '.taskrc' (with a prepended dot), when I think it should be just 'taskrc' (without the dot).  I like to follow XDG standards so I set a `TASKRC` environment var like this `export TASKRC="$XDG_CONFIG_HOME"/task/taskrc`. 

Changing the detection to this way suggested would make happy both the ones who do and don't follow XDG standards.

**Comment by jcrben** [comment]
Code is at https://github.com/GothenburgBitFactory/taskwarrior/blob/4a42364775197499b0298eaf59374032433f2c6a/scripts/vim/ftdetect/task.vim#L18

I do the same type of export. You could do `export TASKRC="$XDG_CONFIG_HOME"/task/.taskrc` right?

To make everyone happy, shouldn't it check for both `.taskrc` and `taskrc`?

**Comment by aleprovencio** [comment]
Exactly @jcrben, that's what I'm talking about.
I could do the suggested export though is very weird to put a single hidden (dot) file alone within a dir right :P

**Comment by jcrben** [comment]
You could make a PR to add another line: 
`au BufRead,BufNewFile taskrc				set filetype=taskrc`

I also don't like using dots in my dotfiles.

**Comment by aleprovencio** [comment]
Sure, there you go: https://github.com/GothenburgBitFactory/taskwarrior/pull/2041

**Comment by jcrben** [comment]
Closing since PR was merged
