### ISSUE TITLE
[feature-request] alias of 'p' for project

### ISSUE THREAD

**Issue by simbalion** [GothenburgBitFactory/taskwarrior#2043]
I see a value in both projects and tags, especially for heavy project management. I would like to use p:Name as an alias for project:Name, it's a small difference but as all developers know it adds up.

**Comment by pbeckingham** [comment]
'p' is ambiguous, so we can't do that.

**Comment by defterade** [comment]
pro:Name works in case you didn't know.

**Comment by pbeckingham** [comment]
Request is counter to existing features.
