### ISSUE TITLE
Feature Request: TAG for task number of LATEST

### ISSUE THREAD

**Issue by brp-pdpl** [GothenburgBitFactory/taskwarrior#2048]
I would like to suggest a tag which refers to the *number* of the most recently added task. This could be called "PREVIOUS". Alternatively, the tag LATEST could be extended to work well with "depends:".

The application would be in creating "project" templates, which include dependencies, using a shell script.

For example:

```
echo "task add Decide on mood pro:party"  >> make_party_project.sh
echo "task add Seach for venues pro:party depends:PREVIOUS"  >> make_party_project.sh
echo "task add Book venue pro:party depends:PREVIOUS"  >> make_party_project.sh
...
make_party_project.sh

```
The present behavior (using "depends:LATEST") is an error.

(Note that this is not an essential feature: the output of task can be processed and assigned to a shell variable.)

If this use case (project templating) is already covered by another feature, please feel free to delete this bug.

**Comment by philip-iv** [comment]
You could use 
```
task add Book venue pro:party depends:`task +LATEST ids`
```
The subcommand `task +LATEST ids` will evaluate to the id of the latest command, and wouldn't require storing it in a variable as you mentioned.

**Comment by brp-pdpl** [comment]
Thank you, that solves my problem well.

**Comment by pbeckingham** [comment]
Feature already exists.
