### ISSUE TITLE
https://taskwarrior.org/docs returns corrupted content error

### ISSUE THREAD

**Issue by riazarbi** [GothenburgBitFactory/taskwarrior#2055]
Visiting https://taskwarrior.org/docs returns the following message. 
```
Corrupted Content Error

An error occurred during a connection to taskwarrior.org.

The page you are trying to view cannot be shown because an error in the data transmission was detected.

Please contact the website owners to inform them of this problem.

```

I am running firefox on Lubuntu 18.04.

**Comment by ddeimeke** [comment]
No issue here.
Can you please disable all plugins and report back, if you see the error again?

**Comment by riazarbi** [comment]
Disabled all add-ons and plugins on Firefox; issue persists.

Fired up Chromium; page loads fine. So must be a firefox issue. Will test
another machine.

**Comment by svijee** [comment]
Works fine on firefox for me.

**Comment by riazarbi** [comment]
Works fine on firefox on another machine. Must be a gremlin on my install.
