### ISSUE TITLE
task calendar not working on any context but not none

### ISSUE THREAD

**Issue by WalnerM** [GothenburgBitFactory/taskwarrior#2057]
When I run something like "task context work" and then "task calendar", I get the following message:

> Could not recognize argument '('.

And the calendar is not shown. 

On the other hand, when I run "task context none" and then "task calendar", everything works fine and I see the calendar. Is that only with me or is someone else getting the same?

**Comment by WalnerM** [comment]
Hi @tbabej . That was a long time ago and I changed my computer now. it seams I don't have that problem anymore. Sorry :(

**Comment by tbabej** [comment]
Good to hear that. Feel free to reopen if you encounter this again.

**Comment by nightsdark** [comment]
Hi @WalnerM  I had exact same problem and didn't know what to do; but, the clue you gave "task context none" fixed the calendar report. Hi @tbabej this info may help I'm just running Ubuntu 16.04 and taskwarrior is the repo version 2.50. The commands i ran where `task context work` and that was a setting that I left like that while exploring other things. Every time I had run `task calendar` I would be disappointed getting ` Could not recognize argument '('.` ERROR MESSAGE: But this clue is enough to spur me to compile a working binary that will do the calendar with context if possible. Seems like it worked for you. Example context definitions in ~/.taskrc
```bash
regex=on
confimation=off
context.work=+freelance
context.study=+practice or +lab
context.home=-work -school -homework -lab
context.delegate=+crew or +family
```
