### ISSUE TITLE
Command task sync will only sync after other network activity in shell

### ISSUE THREAD

**Issue by rolandog** [GothenburgBitFactory/taskwarrior#2058]
* What command(s) did you run?
`task sync`

* What did you expect to happen?
Synchronization of tasks with task server on the first try

* What actually happened?
 Sync doesn't occur until I do some other sort of web activity:
```shell
user@host:~$ task sync
Syncing with taskwarrior.inthe.am:53589

Could not connect to taskwarrior.inthe.am 53589
Sync failed.  Could not connect to the Taskserver.
user@host:~$ task sync
Syncing with taskwarrior.inthe.am:53589

Could not connect to taskwarrior.inthe.am 53589
Sync failed.  Could not connect to the Taskserver.
user@host:~$ task sync
Syncing with taskwarrior.inthe.am:53589

Could not connect to taskwarrior.inthe.am 53589
Sync failed.  Could not connect to the Taskserver.
user@host:~$ task sync
Syncing with taskwarrior.inthe.am:53589

Could not connect to taskwarrior.inthe.am 53589
Sync failed.  Could not connect to the Taskserver.
user@host:~$ task sync
Syncing with taskwarrior.inthe.am:53589

Could not connect to taskwarrior.inthe.am 53589
Sync failed.  Could not connect to the Taskserver.
user@host:~$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=121 time=51.1 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=121 time=51.5 ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=121 time=51.3 ms
64 bytes from 8.8.8.8: icmp_seq=4 ttl=121 time=51.6 ms
64 bytes from 8.8.8.8: icmp_seq=5 ttl=121 time=51.7 ms
^C
--- 8.8.8.8 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4006ms
rtt min/avg/max/mdev = 51.173/51.487/51.741/0.328 ms
user@host:~$ task sync
Syncing with taskwarrior.inthe.am:53589

Sync successful.  No changes.
```

* Paste the output of the ```task diag``` command.
```shell
user@host:~$ task diag

task 2.5.1
   Platform: Linux

Compiler
    Version: 7.2.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.9.5
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.8
 Build type: None

Configuration
       File: /home/user/.taskrc (found), 1836 bytes, mode 100644
       Data: /home/user/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: taskwarrior.inthe.am:53589
         CA: /home/user/.taskd/certs/inthe_am/ca.cert.pem, readable, 2405 bytes
      Trust: ignore hostname
Certificate: /home/user/.taskd/certs/inthe_am/private.certificate.pem, readable, 2462 bytes
        Key: /home/user/.taskd/certs/inthe_am/private.key.pem, readable, 3660 bytes
    Ciphers: NORMAL
      Creds: inthe_am/user/************************************

Hooks
     System: Enabled
   Location: /home/user/.task/hooks
     Active: on-add.blocks_attr.py    (executable) (symlink)
             on-launch.blocks_attr.py (executable) (symlink)
             on-modify.blocks_attr.py (executable)
   Inactive: 

Tests
      $TERM: xterm-256color (323x67)
       Dups: Scanned 499 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 499 tasks for broken references:
             No broken references found
```

I am using a VPN, but don't have any issues (that I know of) with other programs.

**Comment by ddeimeke** [comment]
Did you check with the maker of inthe.am? @coddingtonbear

**Comment by coddingtonbear** [comment]
I can't think of a reason why network activity in their local shell might impede synchronization with inthe.am, honestly, can you, @ddeimeke? It's all just using a normal taskserver, and even that is on the other side of this exchange.

**Comment by ddeimeke** [comment]
@coddingtonbear I absolutely agree, but maybe you had a short outage and coincidentally it worked for the user after some shell action.
@rolandog It looks like you have to "wake up" your internet connection.

**Comment by mosiman** [comment]
Just thought I'd pop in here with some of my own experiences. I just had trouble syncing with inthe.am, but pinging an address happened to get it to work. Perhaps it's coincidence. 
My setup is not exactly vanilla. In the process of building taskwarrior, it couldn't find GnuTLS, and I'm running taskwarrior on my school's servers. I've also had the issue mentioned in https://github.com/coddingtonbear/inthe.am/issues/301 (and the manual .task syncing worked for me). 

I'm happy to try and provide more info, I'd just need some guidance on what to provide. Cheers.

**Comment by rolandog** [comment]
Hi @mosiman, I just posted over there with some logs because I just started having this issue today; I'll message you in a while (currently busy at work) inquiring more information regarding the manual .task sync ... but I'm wondering as to what exactly needs to be reported here in order to keep track of the issue:

"task server incompatibility with SSL 3.3"?

**Comment by djmitche** [comment]
Closed because taskserver/taskd is no longer supported.
