### ISSUE TITLE
update_holidays script doesn't fetch the data

### ISSUE THREAD

**Issue by akegalj** [GothenburgBitFactory/taskwarrior#2064]
I am trying to use update-holidays.pl script at my local taskwarrior installation /usr/share/doc/task/scripts/add-ons but seems like this  https://github.com/GothenburgBitFactory/taskwarrior/blob/2.6.0/scripts/add-ons/update-holidays.pl#L137 doesn't fetch any data for `$url_current=https://holidata.net/hr-HR/2018.json` . I am confused whats the deal. I have installed https://www.archlinux.org/packages/extra/any/perl-libwww/ and docs for the package seem to describe exact implementation as un update script https://metacpan.org/pod/LWP::Simple 

```bash
[akegalj@notebook add-ons]$ pwd
/usr/share/doc/task/scripts/add-ons

[akegalj@notebook add-ons]$ ./update-holidays.pl --file holidays.hr-HR.rc 

Data for hr-HR, for 2018 could not be downloaded.  This could
mean that you do not have an internet connection, or that
Holidata.net does not support this locale and/or year.


Data for hr-HR, for 2019 could not be downloaded.  This could
mean that you do not have an internet connection, or that
Holidata.net does not support this locale and/or year.
```
I would expect update to be successfull on this command. 

```bash
[akegalj@notebook add-ons]$ pacman -Qs perl-libwww
local/perl-libwww 6.33-2
    The World-Wide Web library for Perl
```

**Comment by pbeckingham** [comment]
There is a lack of data, and a lack of volunteers to maintain that data.
