### ISSUE TITLE
Unable to edit task

### ISSUE THREAD

**Issue by kevinly24** [GothenburgBitFactory/taskwarrior#2066]
#### To report a bug...

* What command(s) did you run?
task 1 edit
* What did you expect to happen?
open task in editor
* What actually happened?
error prompt: task is already being edited.
* Paste the output of the ```task diag``` command.

**Comment by scottkosty** [comment]
Does this happen every time you try to edit a task? What OS are you on? What is your taskwarrior version?

**Comment by pbeckingham** [comment]
Your editor was quit unexpectedly in the past.  Remove the temp edit file in ``~/.task``.

**Comment by tbabej** [comment]
Please reopen if @pbeckingham suggestion does not solve the issue.
