### ISSUE TITLE
Getting ids ignores context 

### ISSUE THREAD

**Issue by akegalj** [GothenburgBitFactory/taskwarrior#2067]
I have few contexts defined:
```
[akegalj@notebook ~]$ task context

Name   Definition                                      Active
active project:sport or +active                        no
home   project.not:company.clients                     no
work   project:company.clients or +OVERDUE and -active yes
```

and I can filter overdue tasks in currently active context by:
```
[akegalj@notebook ~]$ task +OVERDUE

ID Age Project              Due Description                          Urg 
 9 21h company.clients.<?> -7h Study quickcheck state machines      17.9
52 15h company.clients.<?> -7h Reply to <?> email about vacation 9.94

2 tasks
```

I can count them correctly as well using count with preapplied filter and context:
```
[akegalj@notebook ~]$ task +OVERDUE count
2
```

Good so far. But when I ask for `ids`, it gives me additional 2 overdue tasks from other context that is not active:
```
[akegalj@notebook ~]$ task +OVERDUE ids
4 9 11 52
```

Its intuative and I would expect `task +OVERDUE ids` to return 2 items, not 4.

EDIT:
seems like applying <filter> +OVERDUE doesn't matter:
```
[akegalj@notebook ~]$ task count
4
[akegalj@notebook ~]$ task ids
1-60
```
it just seems that `task ids` ignores active context, where `task count` takes it into account - which is confusing 

task diagnostic:
```
[akegalj@notebook ~]$ task diagnostics

task 2.5.1
   Platform: Linux

Compiler
    Version: 5.3.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Mar  9 2016 20:12:54
      CMake: 3.4.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.4.10
 Build type: 

Configuration
       File: /home/akegalj/.taskrc (found), 1608 bytes, mode 100644
       Data: /home/akegalj/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: vim
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/akegalj/.task/hooks
             (-none-)

Tests
      $TERM: rxvt-unicode-256color (237x57)
       Dups: Scanned 76 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 76 tasks for broken references:
             No broken references found

```

**Comment by akegalj** [comment]
It might be the case the problem is in `-active` applied to `work` context:
```project:company.clients or +OVERDUE and -active
```

two additional tasks that god collected with `task +OVERDUE ids` do have `+active` - and seems like context filter didn't apply `-active` in `task +OVERDUE ids`.

On another hand `task ids` returns 1-60 which also seems to calculate wrong answer for `+OVERDUE and -active`.

**Comment by akegalj** [comment]
> It might be the case the problem is in `-active` applied to `work` context:
> 
> two additional tasks that god collected with `task +OVERDUE ids` do have `+active` - and seems like context filter didn't apply `-active` in `task +OVERDUE ids`.
> 
> On another hand `task ids` returns 1-60 which also seems to calculate wrong answer for `+OVERDUE and -active`.

**Comment by akegalj** [comment]
Same happens if I try with `tags.not:active` instead of `-active`. 

One of the included tasks (that I didn't expect to be included is):
```
[akegalj@notebook ~]$ task 4
No command specified - assuming 'information'.

Name                 Value                                                             
ID                   4
Description          Take new doctor proscription for <?>                         
Status               Pending
This task blocked by 11 Call doctor for urinolog proscription                          
Entered              2018-09-20 08:53:11 (22h)
Due                  2018-09-21 00:00:00                                               
Last modified        2018-09-20 12:50:55 (18h)
Tags                 active                                                            
Virtual tags         BLOCKED DUE DUETODAY MONTH OVERDUE PENDING TAGGED TODAY WEEK YEAR
UUID                 144de385-920e-4b43-ab80-71521c6c36e2                              
Urgency              4.747

    blocked      1 *   -5 =     -5
    tags       0.8 *    1 =    0.8
    due      0.746 *   12 =   8.95
                            ------
                             4.747

```

so it has `+OVERDUE` flag and it has `+active` flag so `+OVERDUE and -active` == `true and false` == `false` should evalueta to false. This task isn't part of any project so `project:company.clients` should evaluate to false as well. The whole work context should evaluate to false in this case:
```
project:company.clients or +OVERDUE and -active == false or true and false == false or false == false
```

so something is not right with `task ids`, ignoring the context filter (or doing it wrong)

**Comment by akegalj** [comment]
If this looks strange and if it would be useful for debugging - I can anonimize the data and upload.

**Comment by pbeckingham** [comment]
The ``ids`` command is not intended to obey context.

**Comment by tbabej** [comment]
@akegalj Indeed, as @pbeckingham says, `ids` are not affected by context since they are meant to be used in scripts.
