### ISSUE TITLE
Integer overflow bug on dates? Large date -> `{negative number} is not a valid date in the " format`

### ISSUE THREAD

**Issue by salgadobreno** [GothenburgBitFactory/taskwarrior#2068]
I'm learning the tool and one thing I thought of doing was to add a wait:future for some task so it would be "hidden" and I noticed it doesn't accept far off years. See:

```
# task add teste due:2099-01-01
'-224051296' is not a valid date in the '' format.
# task add teste due:2050-01-01
'-1770352096' is not a valid date in the '' format.
# task add teste due:2030-01-01
Created task 52.
```

When I noticed this, I created a task to work on it and do a PR, I'd like to but I'll probably be too busy and end up delaying it forever so I decided to inform of it already :)

**Comment by tbabej** [comment]
Thank you for the report. This is duplicate of #2017, which currently targets 2.6.0.
