### ISSUE TITLE
Snapcraft Package?

### ISSUE THREAD

**Issue by benyanke** [GothenburgBitFactory/taskwarrior#2074]
It would be great to be able to use a snapcraft package for TaskWarrior, allowing not only rolling updates across distros, but allowing easy running of the pre-release builds automatically (if connected to a CI env), allowing bugs to be found more quickly. I know I'd run it with `--edge` (ie, the master branch auto building) if it was stable enough, and reporting issues as they arise.

A few notable links:

https://docs.snapcraft.io/creating-a-snap/6799
https://docs.snapcraft.io/c-c-applications/7817

**Comment by pbeckingham** [comment]
Make one.  We don't do packaging, we just release source tarballs.  The community builds packages.
