### ISSUE TITLE
Fit available terminal width if larger than needed

### ISSUE THREAD

**Issue by bmarcote** [GothenburgBitFactory/taskwarrior#2075]
I think that it would be great to introduce an option to allow TaskWarrior to fit the maximum width of the current terminal window.

Currently, either when it checks the available width or this is set by defaultwidth, if the value is larger than the required by the columns then it is never reached, and part of the window remains unused on the right (see next screen capture).

![1](https://user-images.githubusercontent.com/5698957/48302547-4d080f00-e4fe-11e8-9e70-ef1040110f80.jpg)

An option to fit the maximum width would be great, e.g. by adding empty spaces on each column until reaching the maximum possible:

![2](https://user-images.githubusercontent.com/5698957/48302540-47aac480-e4fe-11e8-9dc6-4c2893eabd8f.jpg)

**Comment by pbeckingham** [comment]
While I understand the request, I don't see that it's useful.
