### ISSUE TITLE
Task all does not distinguish between deleted and done tasks

### ISSUE THREAD

**Issue by Blackjack92** [GothenburgBitFactory/taskwarrior#2079]
Hello,

I want to be able to distinguish between deleted and done tasks, when I list all tasks (see image, some of the entries with status D are deleted and the others are done).
Furthermore, a `task deleted` command would be helpful, where all deleted tasks could be shown.

![image](https://user-images.githubusercontent.com/11227428/49436302-15b51700-f7b9-11e8-8e14-2d60ca4b9521.png)

**Comment by ddeimeke** [comment]
What about

    task status:completed all
    task status:deleted all
