### ISSUE TITLE
Cannot add dependency to a task by using short UUID of the blocking task

### ISSUE THREAD

**Issue by ghost** [GothenburgBitFactory/taskwarrior#2082]
#### To report a bug...

* What command(s) did you run?

```
$ task a3b2d753 modify depends:ab52a631
```

* What did you expect to happen?

```
Modifying task a3b2d753 'Submit report'.
Modified 1 task.
Project 'work.assignment004' is 0% complete (2 of 2 tasks remaining).
```

or (because task a3b2d753 currently has ID 217):

```
Modifying task 217 'Submit report'.
Modified 1 task.
Project 'work.assignment004' is 0% complete (2 of 2 tasks remaining).
```

* What actually happened?

```
Could not create a dependency on task 0 - not found.
```

* Paste the output of the ```task diag``` command.
```
task 2.5.1
   Platform: Linux

Compiler
    Version: 6.3.0 20170516
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Nov 28 2018 20:17:42
     Commit: 493bbadb1
      CMake: 3.7.2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: n/a
 Build type: 

Configuration
       File: /home/sampablokuper/.taskrc (found), 4524 bytes, mode 100644
       Data: /home/sampablokuper/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/sampablokuper/.task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (251x54)
       Dups: Scanned 1207 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 1207 tasks for broken references:
             No broken references found
```

**Comment by ddeimeke** [comment]
What happens if you use the complete UUID for the dependancy?

**Comment by sampablokuper** [comment]
@ddeimeke wrote:
> What happens if you use the complete UUID for the dependancy?

Ah, that does work. I have now modified the title of this bug report accordingly. Thank you.

**Comment by ddeimeke** [comment]
I do not think this is an issue. The UUID is guarenteed to work and the UUID is unique as whole, not as part.

**Comment by pbeckingham** [comment]
Is that a hexadecimal UUID with a “g” in it?

Paul

**Comment by sampablokuper** [comment]
@pbeckingham wrote:
> Is that a hexadecimal UUID with a “g” in it?

Sorry, typo. Fixed.

**Comment by sampablokuper** [comment]
@ddeimeke wrote:
> I do not think this is an issue. The UUID is guarenteed to work and the UUID is unique as whole, not as part.

It is an issue. Full UUIDs are too long to be feasible in reports on typical terminals; IDs [change](https://taskwarrior.org/docs/ids.html) and this is a barrier to usability (for some people, at least) and to scripting. Short UUIDs, like abbrev hashes in Git, are the happy medium. So, short UUIDs should work wherever IDs and UUIDs do.

As for the possibility of collisions: given a reference, TaskWarrior should probably do something like this:

- Check all UIDs for matching heads; and
- If the reference is an integer, then also check all IDs for full matches.
- Then, if the number of matches is 0, print an error that no matching task was found;
- else if the number of matches is 1, then use that referent;
- else print an error along the lines `Ambiguous reference: 12345678. Did you mean task ID 12345678 'Buy groceries', or did you mean task UUID 12345678-6d26-4d38-bbb8-7bee275834c7 'Telephone grandma'?`

I don't know how Git handles collisions, but one technique to reduce the likelihood of their occurrence is to [set a minimum length for short UUIDs/hashes](https://lkml.org/lkml/2010/10/28/264). TaskWarrior already sets this to 8 characters, AFAICT, which is probably sufficient for most users.

**Comment by ddeimeke** [comment]
> Sorry, typo. Fixed.

So, it works now?

**Comment by sampablokuper** [comment]
@ddeimeke wrote:
> > Sorry, typo. Fixed.
> 
> So, it works now?

No. The typo was in my transcription into GitHub. The typo was not present at the command prompt and was not the source of TaskWarrior's failure to find the task referred to by the short UUID.

**Comment by ddeimeke** [comment]
I checked the docs, especially https://taskwarrior.org/docs/ids.html

There is no abbreviation to use the UUID, it works as designed.

You can use the sort ID if the task is pending.

**Comment by ddeimeke** [comment]
> What do you mean by the "sort ID"?

Sorry, typo, I meant „short“ ID.

**Comment by sampablokuper** [comment]
@ddeimeke wrote:
> Sorry, typo, I meant „short“ ID.

OK, but then what is a "short ID"?

**Comment by ddeimeke** [comment]
This is the ID you see in nearly any report with an ID column, for example the irst column of `task ls`

**Comment by sampablokuper** [comment]
@ddeimeke wrote:
> This is the ID you see in nearly any report with an ID column, for example the irst column of `task ls`

Ah, so by "short ID", you just meant "ID"?

**Comment by ddeimeke** [comment]
> Ah, so by "short ID", you just meant "ID"?

An UUID is an ID as well, to distinguish those types I used "short ID".

**Comment by sampablokuper** [comment]
@ddeimeke wrote:
> An UUID is an ID as well, to distinguish those types I used "short ID".

Thanks for clarifying. So, in other words, there are three ways to refer to any single task:

* ID (i.e. what the [docs](https://taskwarrior.org/docs/ids.html) call "ID number", and what you, above, call "short ID"). Always works, but only for pending tasks.
* UUID. Always works.
* Short UUID. IMO, this *should* always work unless ambiguous. The fact that currently it does not always work, even if unambiguous, is what this thread is designed to address.

With any luck, we now have a shared understanding :)

**Comment by ddeimeke** [comment]
> With any luck, we now have a shared understanding :)

Little correction, you made a feature request to get Short UUIDs working. That means the „should“ is your opinion of how you expect Taskwarrior to work.

**Comment by sampablokuper** [comment]
@ddeimeke wrote:
> That means the „should“ is your opinion of how you expect Taskwarrior to work.

Yes, that is what the "IMO" meant in [this](https://github.com/GothenburgBitFactory/taskwarrior/issues/2082#issuecomment-446944144) comment: "**i**n **m**y **o**pinion". Apologies for using an initialism instead of writing it in full.

**Comment by ddeimeke** [comment]
> Yes. That is why I used "IMO" in [this](https://github.com/GothenburgBitFactory/taskwarrior/issues/2082#issuecomment-446944144) comment. It stands for "**i**n **m**y **o**pinion". Apologies for using an initialism instead of writing it in full.

Sorry to be a bit picky about that one, I know what IMO means, but "So, in other words, there are three ways to refer to any single task:" leaves no room for interpretation.

**Comment by pawamoy** [comment]
My use-case to support @sampablokuper request for being able to use partial UUID:

I periodically run `task list` or equivalent in Conky. It means the garbage collection is ran periodically. It also means that, in a terminal, I can't rely on the last IDs displayed by a `task list` command, because garbage collection might have happened in between. So to avoid any mistake, I **must** run `task list` after each `task done` or similar command, to make sure I'm reading at the updated IDs. Now this could be solved easily if I displayed the UUIDs instead of the IDs, but as @sampablokuper wrote, the UUID string is often too long to be displayed nicely in reports. Therefore, a partial UUID, made of the first  non-hash-colliding characters (8? less?) would be greatly appreciated!

**Comment by sdondley** [comment]
I vote for this.

**Comment by sdondley** [comment]
By the way, the shortened UUID, aka 8 character UUID, works with:

`task info 23d5fd0e`

Seems inconsistent that it should work with that subcommand but not in other places.

**Comment by tbabej** [comment]
I agree. I actually touched this code recently, perhaps we can get this into 2.6.2.
