### ISSUE TITLE
Jira issues missing from GitHub bug tracker

### ISSUE THREAD

**Issue by sampablokuper** [GothenburgBitFactory/taskwarrior#2087]
IIUC, around 14 February 2018, the TaskWarrior maintainers migrated the contents of TaskWarrior's previous bug tracker (a [Jira instance hosted free of charge by Atlassian](https://taskwarrior.org/news/news.20140303.html)) into the present GitHub bug tracker.

Unfortunately, there was some data loss/breakage in the process. For example:

- Tickets and comments that were imported from Jira into GitHub are shown as having been authored by @taskwarrior , preventing GitHub's [author searching](https://help.github.com/articles/searching-issues-and-pull-requests/#search-by-author) from being able to identify the actual author.
- The Jira ticket numbers ["TW-XXX"] do not match the GitHub ticket numbers.
- Some Jira tickets seem to be missing entirely from the GitHub bug tracker.

I want to focus, here, on the third issue.

So far, I have not been able to find these tickets (I will update the list as appropriate):

- [[TW-9]](https://github.com/GothenburgBitFactory/taskwarrior/issues?utf8=%E2%9C%93&q=is%3Aissue+%22TW-9%22+in%3Atitle+)
- [[TW-169]](https://github.com/GothenburgBitFactory/taskwarrior/issues?utf8=%E2%9C%93&q=is%3Aissue+in%3Atitle+%22%5Btw-169%5D%22)

Does anyone know what happened to them?

**Comment by JonasDralle** [comment]
thanks for having an eye on this

**Comment by pbeckingham** [comment]
Short answer: I don't know, but I'm not surprised.

Long answer: It took a herculean effort spread over a week, by Tomáš, if I recall, to migrate the issues while not exceeding some speed threshold that kept getting us cut off from the GH API, followed by manual reattachment of files.  All over a flaky net connection.  If we've lost data, that's a shame, but there's nothing we can do at this point.
