### ISSUE TITLE
Strange behavior with +ACTIVE

### ISSUE THREAD

**Issue by gms8994** [GothenburgBitFactory/taskwarrior#2089]
I'm not sure if this is a bug or not, but the behavior is definitely "odd":

`task +ACTIVE` lists only the currently "started" task (`task start`) correctly. If I then do `task +ACTIVE info`, I get a very long list of tasks, that include some that look like this:

```
Name          Value                               
ID            -
Description   Notify me email box @mpl            
Status        Deleted
Entered       2017-10-30 16:13:50 (1.1y)          
Start         2017-10-26 00:00:00
Due           2017-10-30 00:00:00                 
End           2017-10-30 00:00:00
Last modified 2017-11-11 15:22:37 (1.1y)          
Tags          ump
Virtual tags  ACTIVE DELETED TAGGED UNBLOCKED     
UUID          6e1f71c5-c830-44b4-a983-379384a6bedb
Urgency       18.8                                

    active      1 *    4 =      4
    tags      0.8 *    1 =    0.8
    due         1 *   12 =     12
    age         1 *    2 =      2
                           ------
                             18.8
```

`task 6e1f71c5 export` shows the following:

```
[
{"id":0,"description":"Notify me email box @mpl","due":"20171030T040000Z","end":"20171030T040000Z","entry":"20171030T201350Z","modified":"20171111T202237Z","start":"20171026T040000Z","status":"deleted","tags":["ump"],"uuid":"6e1f71c5-c830-44b4-a983-379384a6bedb","urgency":18.8}
]
```

Is this task listed as `ACTIVE` because it has a `start` but no `stop` (or end, I'm unsure of the key that should be there)?

As an aside, this started as me trying to figure out how to get the uuid of the currently ACTIVE task, which eventually became `task +ACTIVE -DELETED -COMPLETED export | jq`. If there's a better way of getting that, I'd be a very happy camper :)

**Comment by tbabej** [comment]
A better way of doing this might be `task +ACTIVE +PENDING`. This is due to the default command `next` having the `+PENDING` default filter, whereas `info` does not have any default filter at all.
