### ISSUE TITLE
is taskwarrior stagnant?

### ISSUE THREAD

**Issue by seniorivn** [GothenburgBitFactory/taskwarrior#2092]
[topic on reddit](https://old.reddit.com/r/taskwarrior/comments/a9dv3l/is_taskwarrior_stagnant/)

The lack of commits from @pbeckingham is obvious, he probably has his reasons, but the problem is that no one seams to be ready to replace him.
- Is it the end of taskwarrior development?
- What should we do?

**Comment by gour** [comment]
> What should we do?

Few times I was jumping between Taskwarrior and org-mode and always find the former much better suited for my workflow, but I was always bitten by TW's poor recurring support which "simply works" within org-mode, so, personally, I'll simply switch (back) to org-mode and stop worrying...If I'd have more free time or, even better, required C++ skills to help, I'd try to contribute to the project, but lacking both. :-(

**Comment by tbabej** [comment]
@seniorivn There are only two things that can be done when a project you want to progress does not progress at a pace you like: either donate your time (and skills) to the cause, or donate money to the cause.

While crowdfunding TW is unlikely to support a full-time engineer's salary, it could be sufficient to generate couple of student grants, who could then grow to be longer-term contributors.

**Comment by tbabej** [comment]
Note that skills is not only "C++ coding skills", these can also be other maintenance tasks, such as:

* helping users on the #taskwarrior IRC channel
* maintaining the bug tracker (i.e. trying to reproduce old bugs or linking related issues)
* improving the documentation

**Comment by tbabej** [comment]
@crocket are there particular PRs you have in mind here?

**Comment by crocket** [comment]
@tbabej Nothing in particular. I was talking about merging pull requests quickly in general. I recommend merging them all if they don't break public API.

If you want to learn about zeromq community process in details, I suggest reading

* http://hintjens.com/blog:106
* http://hintjens.com/blog:117#toc29
* https://rfc.zeromq.org/spec:42/C4/

**Comment by meonkeys** [comment]
This is a helpful and answered discussion. I vote we resolve it!

**Comment by tbabej** [comment]
@crocket I don't think this has been true for the lifetime of TW development at all - quite the opposite, in fact. New enhancements tend to get scrutinized in order to ensure the simplicity of the software and reasonable maintenance burden on the maintenance team.

**Comment by crocket** [comment]
Although it'd be better for you to have direct experience of C4 in some way, direct experience will guide your decisions in any case.

**Comment by pbeckingham** [comment]
> [topic on reddit](https://old.reddit.com/r/taskwarrior/comments/a9dv3l/is_taskwarrior_stagnant/)
> 
> The lack of commits from @pbeckingham is obvious, he probably has his reasons, but the problem is that no one seams to be ready to replace him.
> 
> * Is it the end of taskwarrior development?
> * What should we do?

You could have just asked me.
