### ISSUE TITLE
[EX-22] shell mode extension and enhancement

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#21]
_David Patrick on 2009-07-14T00:05:40Z says:_ 

 if I type 

   task add

I get an error message "Cannot add a task that is blank, or contains <CR> or <LF> characters."
Considering the stealthy new shell mode, wouldn't it be swell if what actually happened was that task went into "shell add" mode.

task add>

so that I could just type

 make pizza +na
mow lawn du:weekend
bay bills pri:h
get a haircut +grooming

until I tire of rapid-fire data entry, and type "quit"

the shell command could be extended to include other commands such as

   task shell ls 

task ls>         - in this mode, just hit enter to see the output of "task ls" 
and anything typed in is used as filter upon hitting <enter>, allowing a rapid series of filtered lists with almost no syntax construction. just <filter><enter> <filter><enter> <filter><enter>

or, to restrict the focus to just one project, for example; 

   task shell long proj:foo

Enter filter string
Use "quit" or ctrl-c to leave shell mode
task long project:foo>

or if you have a lot of appending to do;

   task append     

(which could, depending on user preference, trigger auto-shell, due to absence of required attributes)
resulting in; 

Enter ID and text to append
Use "quit" to leave shell mode
task append>  

or when working up a longish list of closely related tasks, this is rapid-fire entry mode;

   task shell add due:07/21/2010 wait:06/21/2010 proj:camping +gear pre:pack

Use "quit" to leave shell mode
task add project:camping +gear due:07/21/2010 wait:06/21.2010 pack>

so that you can just type

 tent [enter] sleeping bags [enter] stove [enter] food [enter] bug stuff [enter] tools [enter] radio [enter]

and a 

 pack tent due:07/21/2010 wait:06/21.2010 project:camping +gear

will be created for each item

this will save more keystrokes than ANYTHING!

This behavior should be considered as (optional) default whenever a command that expects attributes, doesn't get them. It brings the CLI behavior closer to planned interactive usage, too.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-07-14T00:05:40Z
Modified: 2014-02-09T16:46:42Z
```

**Comment by taskwarrior** [comment]
_John Florian on 2009-07-14T09:41:16Z says:_ 

 That's clever.

I think we'd want an rc option that enabled/disabled this feature though.  I can envision a day when I'll have other scripts creating tasks for me and I wouldn't want a scripting error to freeze because it was blocked on input.

Otherwise, I like it.

**Comment by taskwarrior** [comment]
_David Patrick on 2009-07-14T10:51:08Z says:_ 

 John Florian wrote:
> I think we'd want an rc option that enabled/disabled this feature though.

perhaps
autoshell=on/off
and a CLI override (noautoshell) so that you can stay in autoshell mode and your scripts can still behave nicely.

**Comment by taskwarrior** [comment]
_David Patrick on 2009-07-21T09:29:00Z says:_ 

 shell-mode-style input will also be used extensively in interactive mode.

for example, while in the interactive shell, if you hit (a)dd, the prompt-bar should display a shell-mode input prompt, like
<pre>
   Enter task details [tags] [attrs]
   Type "q" when done
   task add>
</pre>
The behavior changes depending on whether or not there are selected items. If items have been selected, the shell-mode action is presumed to act only on those selections, otherwise the prompt will ask for task ID, too.
Another example; hit ann(o)te, with nothing selected
<pre>
   Enter task IDs and annotation text [tags] [attrs]
   Type "q" when done
   task annotate>
</pre>
but with items selected
<pre>
   Enter annotation text [tags] [attrs]
   to tasks 123,45,214
   Type "q" when done
   task annotate>
</pre>

**Comment by taskwarrior** [comment]
_David Patrick on 2012-08-11T15:56:37Z says:_ 

 An enhanced shell mode could allow you to collect up a set of command elements and attributes as a sort of working default set, and it could do the same thing for session variables. Just as a regular (bash, zsh) shell prompt can tell you about your host-name and working directory, the future taskwarrior shell could also keep track of a working set of environment variables. If you regularly change your target task files, or use alternate configuration files, the enhanced shell mode could hold that change for the session (or until cleared) and display the active data/rc file as part of the shell prompt, as in 

 ~/.task/djp_pending.data - task add proj:home>

**Comment by taskwarrior** [comment]
_David Patrick on 2012-08-16T18:26:03Z says:_ 

 The central idea in shell mode is that everything left of the ">" marker is "sticky", it will be used for following commands and all input happens to the right of the ">". This allows you to instantly short-circuit a repetitive action, by including it in the shell "stack". A set of attributes can be "shelled" right from the cli with 

 % tw proj:foo due.before:eom shell

which lands you in the twshell with a prompt that looks like 

 task proj:foo due.before:eom >

at which you can enter "next", "+biz ls", "count", "stats", whatever, and it will all remain focused on proj:foo due.before:eom. Adding a term to the shell stack is easy, as the command *shell* should do that, like

 % task proj:foo due.before:eom > +biz shell

should result in

 % task proj:foo due.before:eom +biz >

and so on, narrowing the focus.
Within the shell, ">" should be used a short-hand for the shell command, enabling stack extension with a single character (+<enter>) ready for refined reports and modifications. Having adopted ">" to say "extend the stack", then "<" logically means "reduce the stack" and so it should! 
"<" input as the last character to the right, upon hitting < enter >, should move the shell marker >  one element to the left, while leaving elements now on the right of the > and editable. 

What I'm trying to get at here is that with a single character input, you could walk up and down the set of arguments.

**Comment by taskwarrior** [comment]
_David Patrick on 2012-08-17T03:09:09Z says:_ 

 twshell will also make taskwarrior an excellent choice for event logging and taking minutes. Imagine

 % tw add take meeting notes proj:baz.mgmt +minutes
Created task 123

and then

 % tw 123 annotate

instead of "Additional text must be provided" because task is expecting parameters, and because autoshell is enabled as a default command, you land in twshell with

 task 123 annotate >

allowing you to enter annotation text and hit enter, time-stamped and one after another. 
A similar feat could be achieved using *task log* and twshell, with a prompt like

 task proj:weirdowatch +safety prepend:'weirdo sighting: ' log -- >

and you're ready make repeated entries and to keep an accurate and consistent watch on the weirdos. (somebody has to ;-)

**Comment by pbeckingham** [comment]
No plans to implement.
