### ISSUE TITLE
[TW-158] JSON export should model dependencies as array

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#210]
_Nicholas E. Rabenau on 2012-06-29T23:21:43Z says:_ 

 I followed the "tutorial":http://taskwarrior.org/projects/taskwarrior/wiki/Tutorial2#DEPENDENCIES and created a task that depends on two other tasks. These two dependencies are being JSON exported as comma-separated list within a String (see attached sample party.json). 

As JSON allows arrays, I suggest to export dependencies as native JSON arrays instead (see attached sample party2.json).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-06-29T23:21:43Z
Modified: 2015-07-29T04:32:38Z
```

**Comment by taskwarrior** [comment]
_Nicholas E. Rabenau on 2012-06-29T23:21:43Z says:_ 

 Attachment party.json has been added with description: dependencies separated with comma (TaskWarrior 2.0)

**Comment by taskwarrior** [comment]
_Nicholas E. Rabenau on 2012-06-29T23:21:43Z says:_ 

 Attachment party2.json has been added with description: dependencies modeled as JSON array

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-06-30T00:25:59Z says:_ 

 That's a good idea, thank you.

This needs to be coordinated with 3rd party tools, so it is scheduled for 2.1 - 2.0.1 is too soon.

**Comment by taskwarrior** [comment]
_Nicholas E. Rabenau on 2012-07-01T13:05:05Z says:_ 

 Thanks. I just realized that tags are already exported as JSON arrays, so it's good that the export will become even more consistent once dependencies are an array, too.

**Comment by pbeckingham** [comment]
[TW-158_party.json.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755552/TW-158_party.json.txt)
[TW-158_party2.json.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755553/TW-158_party2.json.txt)
