### ISSUE TITLE
Simpler sync key management

### ISSUE THREAD

**Issue by voidus** [GothenburgBitFactory/taskwarrior#2115]
Context: I'm using taskserver to synchronize my tasks between three devices. I am the server administrator and only user.

I feel like Client certificates and Signatures introduce a lot of non-essential complexity for my use case, and I'd like to suggest something simpler. This is inspired by the way wireguard handles this.[1]

* The client holds a private key
* The client's public key is stored at the server
* When communicating, the server verifies that the client holds the private key for the stored public key

Advantages:

* Simpler configuration and key generation
* Private Keys can be generated on the client and don't need to be transferred over the network

Disadvantages

* Adding Keys requires access to the server?
* [I'm not sure what primary use-case the taskserver aims for, so there are probably more]

I'd love to look into this myself, but I don't think I'll have time in the near future. I still wanted to introduce the idea though. What do you think?

[1] See for example https://www.wireguard.com/#cryptokey-routing

**Comment by gordon-quad** [comment]
Managing a CA is quite PITA, especially if you are the only user of personal taskd instance or taskd for small group of people. Default expiration date will require regeneration of whole CA every year and redistribution of new keys to client devices, providing strong security where it could be excessive.

I have no objections to above proposal, wireguard key is quite simpler alternative to full CA, but it would be wonderful to have even more simple solution like static API key per user for deployments over the VPN or other type of trusted network or trusted unix socket accessible w/ ssh tunnel for example.

**Comment by ngortheone** [comment]
I want to point out another couple of painful aspects of the current authentication approach. Currently a server administrator has to provision a key for a client and hand it over somehow to the user. The user has to install the key somehow(put it in the right place, permission it, etc) That presents a couple of problems:

1. The actual distribution. As an example - I am working on an android client, and it needs to have CA cert, and clients private and public key. An advanced user can probably put files over android debug bridge, or sync files over some 3rd party solution like Dropbox, but it is still a non-trivial operation. For a less tech-savvy person it is too difficult and  not always clear why it is so difficult to get started.
Summarizing: Distribution of keys is very hard for non-desktop systems.

2. Administrator has unrestricted access to user's data and credentials. This is probably a non-issue for small installations, when there is 1 user, or a small group of people that trust each other. It is a problem for larger installations, especially in situations where server is not controlled by the end user(think of taskwarrior server as service). Usually, in overwhelming majority of systems an administrator knows only the initial password, that user has to change upon first login. Task server does not present a way of changing users "password".  Key rotation is hard - see problem above.

The solution I want to propose is sign-up flow. There could be some variations but roughly it looks like this: An administrator of the server provisions only CA and keys of the server itself. For each new user a one-time password is generated and give to the user (as a variation, one-time password is sent to user's email address). User configures taskwarrior to talk to the server and upon first sync one time password is requested). Server automatically generates public and private keys for the user and sends it back to the user as a reply to the first sync. 

Effectively this should be no-different from regular user/password communication over SSL.

**Comment by tbabej** [comment]
These are all valid points. The plan is to address this with server synchronization protocol 2.0.

**Comment by djmitche** [comment]
..and that eventually ended up being TaskChampion, in Taskwarrior 3.0.0. I hope it addresses many of the issues raised here!

**Comment by voidus** [comment]
Hell yeah! Great to hear ❤️

**Comment by djmitche** [comment]
Awesome! We also just split out the sync server into its own repo, and it can definitely use some love in terms of making it more production-ready - https://github.com/GothenburgBitFactory/taskchampion-sync-server
