### ISSUE TITLE
[Feature request] Allow annotating projects

### ISSUE THREAD

**Issue by Pastafarianist** [GothenburgBitFactory/taskwarrior#2120]
Projects are, per GTD, anything that comprises at least two tasks. Often, you would want to keep some extra info that is applicable to all of these tasks, such as relevant links or information you find while researching how the tasks can be done. Currently there are two obvious ways to do this:

1. Keep a special task assigned to the project called essentially "get it done" and keep all info in its annotations. Example:
  * `project:personal.finance.taxes`
  * meta-task: `Pay taxes`, annotation: URL to instructions for paying taxes
  * Regular tasks:
    1. `Get data for the last year`
    2. `Fill xxx form`
    3. `Mail form to Task Service`
2. Keep extra info somewhere outside of Taskwarrior.

Neither of the options feels convenient, as for (1) there is a task-that-is-not-actually-a-task, and for (2) you have to keep your information separately in multiple places. Therefore I am suggesting adding support for project annotations.

**Comment by MartyLake** [comment]
I stumbled upon this issue when I started using taswarrior, in the aim of implementing GTD. What I ended up is (2) keeping tracks in a vim-wiki of everybit of information related to any project, and use taswarrior on the side to tracks tasks and contexts

**Comment by pbeckingham** [comment]
Projects are not first-class objects, merely an attribute of a task.

**Comment by Pastafarianist** [comment]
The issue template suggested to propose features, not a specific implementation. Yet your objection, @pbeckingham, is related to the data model used in Taskwarrior, i.e. an implementation detail. Perhaps we could discuss the benefits and drawbacks of having such feature and how it could be integrated with the current data model?
