### ISSUE TITLE
Cannot add a task with more than 2 tags if one of them is the word "project"

### ISSUE THREAD

**Issue by jvanz** [GothenburgBitFactory/taskwarrior#2123]
* What command(s) did you run?
```task add test tags:"project,bla"```

* What did you expect to happen?
Add a new task

* What actually happened?

The following error: 
`The expression could not be evaluated.`

* Paste the output of the ```task diag``` command.
jvanz@earth:~> task diag

task 2.5.1
   Platform: Linux

Compiler
    Version: 7.3.1 20180323 [gcc-7-branch revision 258812]
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Mar 5 2016 08:39:16
      CMake: 3.10.2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.2
 Build type: RelWithDebInfo

Configuration
       File: /home/jvanz/.taskrc (found), 1533 bytes, mode 100644
       Data: /home/jvanz/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: vim
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/jvanz/.task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (323x65)
       Dups: Scanned 93 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 93 tasks for broken references:
             No broken references found

**Comment by jvanz** [comment]
The same issue happens when you try to add a task with a UDA and try to add a string in the field which is the of the UDA name. For example:

`task add Blablabla sg:sg#1`

The command above fails with the same error message of the first comment. The UDA have been added using these commands:

```
task config uda.sg.type string
task config uda.sg.label SG
```

**Comment by heiderich** [comment]
This might be a workaround:
   
`task add test +project +bla`

**Comment by pbeckingham** [comment]
Tags is not intended to be directly addressed like that.
