### ISSUE TITLE
Update release tarballs for 2.6.0

### ISSUE THREAD

**Issue by lfos** [GothenburgBitFactory/taskwarrior#2126]
Looking at the GitHub release page, it seems like 2.6.0 is current stable. Could you update the release tarballs on the website as well, please? Or is that no longer maintained?

**Comment by pbeckingham** [comment]
No.  The 2.6.0 development branch is a work in progress, the code on that branch is buggy, contains two implementations of recurrence, and debug statements.  Do not use it.  Use the 2.5.2 branch which is approaching a release and is more stable, if you want a development copy at all, that is.

Better yet use the master branch, which is the only released version, and is stable.

**Comment by lfos** [comment]
Sorry, my fault. I got confused by the GitHub release page.
