### ISSUE TITLE
task list tag:<TagName> not returning desired results

### ISSUE THREAD

**Issue by gmdjango** [GothenburgBitFactory/taskwarrior#2130]
#### To report a bug...
i have a task that has 2 tags: MyTag_1 and MyTag_2 (set in this order) and appear in this order inside the task, viewable by task edit 

##

* What command(s) did you run?
task list tag:MyTag_2
* What did you expect to happen?
the task with MyTag_2 should appear in the list
(note: if i run task list +MyTag_2; it works as expected)
* What actually happened?
this task did not appear in the list
* Paste the output of the ```task diag``` command.
task 2.5.1
   Platform: Linux

Compiler
    Version: 7.2.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.9.5
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.8
 Build type: None

Configuration
       File: /home/george/.taskrc (found), 1743 bytes, mode 100644
       Data: /home/george/.task/ (found), dir, mode 40775
    Locking: Enabled
         GC: Enabled
    $EDITOR: /usr/bin/vim
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/george/.task//hooks
             (-none-)

Tests
      $TERM: screen-256color (411x101)
       Dups: Scanned 161 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 161 tasks for broken references:
             No broken references found

#### To request a feature...

* Clearly describe the feature.
* Clearly state the use case. We are only interested in use cases, do not waste time with implementation details or suggested syntax.
* Please see our notes on [How to request a feature](https://taskwarrior.org/docs/features.html)

**Comment by pbeckingham** [comment]
The `tags` attribute is not intended to be directly addressed, as you found out.  Use `+MyTag1` and `-MyTag1`.
