### ISSUE TITLE
Tasksh dead demo

### ISSUE THREAD

**Issue by Fandekasp** [GothenburgBitFactory/taskwarrior#2134]
Reading the [Best practices](https://taskwarrior.org/docs/best-practices.html) > Review your tasks documentation, I found a link to tasksh which doesn't show the demo it should show.

https://taskwarrior.org/news/news.20160905.2.html

![](https://i.imgur.com/LyJeeKD.png)

In case other peoples can actually see the demo, my browser is Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by Fandekasp** [comment]
Found this other url which contains a proper demo, you might want to link there instead: https://taskwarrior.org/docs/review.html

**Comment by pbeckingham** [comment]
The demo works for me.  Chrome 73.0.3683.103.

**Comment by Fandekasp** [comment]
Checked again, and the video now appears. Sorry about that, closing
