### ISSUE TITLE
Using brackets as task name break the script

### ISSUE THREAD

**Issue by MerzDaniel** [GothenburgBitFactory/taskwarrior#2139]
#### To report a bug...

* What command(s) did you run?
task add Take care of toString()ability of stuff

* What did you expect to happen?
task with the name "Take care of toString()ability of stuff" is created

* What actually happened?
error messages every time I use the "task" command:
`able is not a function`

* Paste the output of the ```task diag``` command.
Every call to the task command produces the error

* Additional Information
Error only exists in the current terminal and is not persisted. Restarting the terminal gets rid of the problem. I'm using zsh

**Comment by pbeckingham** [comment]
This is a shell error.  This is expected, parentheses have meaning to both the shell, and taskwarrior as a precedence operator.  Both of the following alternatives work:

    task add 'Take care of toString()ability of stuff'
    task add Take care of toString\(\)ability of stuff
