### ISSUE TITLE
newlines and backslashes are not correctly encoded

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#2140]
#### To report a bug...

* What command(s) did you run?
```sh
export TASKDATA=`mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir'`
trap 'rm -rf $TASKDATA' EXIT

$TASK add abc $'githubbody:"newline=\n, backslash=\\, escaped newline=\\n"'
$TASK 1 export
```
* What did you expect to happen?
```
{..., "githubbody":"newline=\n, backslash=\\, escaped newline=\\n", ...}
```
* What actually happened?
```
{..., "githubbody":"newline=\n, backslash=\\, escaped newline=\n", ...}
```
Note that newline and escaped newline are both encoded the same way, meaning that inserting data containing backslash-n into taskwarrior and then exporting it produces different data.  This is problematic for automated tools which might then try to "rectify" that difference, as for example with [bugwarrior](ralphbean/bugwarrior/issues/527).

* Paste the output of the ```task diag``` command.
(not relevant; this is a fresh TASKDATA and confirmed with both 2.5.1 and the latest git `2.6.0`)

**Comment by tbabej** [comment]
Reproduced on 2.6.0.

**Comment by tbabej** [comment]
Thanks @djmitche for bringing this to my attention in #2375!

**Comment by djmitche** [comment]
It's great to see so much action on this project!
