### ISSUE TITLE
Modification of recrurring event ignores the rc.confirmation flag

### ISSUE THREAD

**Issue by bergercookie** [GothenburgBitFactory/taskwarrior#2141]
I'm trying to modify a *recurring* task as in the example below:

`task modify eaefd85d-db45-43e6-87d0-ad7951cb02d7 description:"Read vinh article" due:"20190407T225900Z" end:"20190409T101744Z" entry:"20190406T230258Z"`

In this case one would expect a message of this type:

`This is a recurring task.  Do you want to modify all pending recurrences of this same task? (yes/no)`

That's to be expected. However, the prompt continues to be there even when I pass `rc.confirmation=no`

`task modify eaefd85d-db45-43e6-87d0-ad7951cb02d7 description:"Read vinh article" due:"20190407T225900Z" end:"20190409T101744Z" entry:"20190406T230258Z" rc.confirmation=no`

I can sidestep this problem by piping with something like `yes no | task ... ` but I think this is an issue with task itself.

**Comment by bergercookie** [comment]
UPDATE: Checking the source, I can see that this prompt is controlled by the `rc.recurrence.confirmation` flag. It feels kind of counter-intuitive to have two config vars for confirmation of events but if this is indeed the expected behavior feel free to close this issue.

**Comment by pbeckingham** [comment]
Thanks.
