### ISSUE TITLE
How to end a recurring task?

### ISSUE THREAD

**Issue by Mebus** [GothenburgBitFactory/taskwarrior#2150]
Hallo,

how can I end a recurring task to have no new tasks in the future?

Thanks

Mebus

**Comment by skbolton** [comment]
The recurring task you create becomes a template from which the instances are created. You can either run `task all` and find the task id so that you can delete it. Or you could do `task /[some text thats insde the task]/` to delete the template

**Comment by pbeckingham** [comment]
task recurring

(Pick an <id>)

task <id> modify until:now

That shuts off recurrence starting now.
