### ISSUE TITLE
relative dates, feature request

### ISSUE THREAD

**Issue by jpritikin** [GothenburgBitFactory/taskwarrior#2158]
Current [named dates](https://taskwarrior.org/docs/named_dates.html) mostly ignore the current day and month.

I'd like

- "next month" or "+30 days" (interpreted as +30 from today)
- "next year" or "+12 months" or "+52 weeks" (interpreted as a year from today)

**Comment by scottkosty** [comment]
Just to make sure I understand, if your suggestion is implemented and we put

```
task add due:"next month" some task
```

this would be equivalent to the following?

```
task add due:30days some task
```

Did I understand correctly?

**Comment by jpritikin** [comment]
Oh! I didn't realize I could say "30days". I don't think that is documented. Maybe to follow the pattern I suggest 1month and 1year. Oh! These are already implemented. Just document them.

**Comment by scottkosty** [comment]
Ah, makes sense. Glad we got that figured out!

> These are already implemented. Just document them.

In `man task` there is currently:

```
              Day number with ordinal
                     task ... due:23rd
                     task ... due:3wks
                     task ... due:1day
                     task ... due:9hrs
```

Do you think that is sufficient for the documentation?

**Comment by pbeckingham** [comment]
The man pages are just meant to be a brief overview of features, there are too many.  The online documentation covers all this.

Paul

**Comment by jpritikin** [comment]
Yeah, looks great!

**Comment by scottkosty** [comment]
Sounds good, let's close this then.
