### ISSUE TITLE
rc.verbose:nothing can show footer on 2.5.2

### ISSUE THREAD

**Issue by scottkosty** [GothenburgBitFactory/taskwarrior#2161]
* What command(s) did you run?

```
task rc.report.next.columns=uuid rc.report.next.labels=UUID rc.verbose:nothing limit:1
```

* What did you expect to happen?

No footer.

* What actually happened?

Footer was shown: "10 tasks, 1 shown".

I think this might be a regression on the 2.5.2 branch. A bisect leads to ec31b934. I cannot reproduce this behavior on the 2.6.0 branch or on 2.5.0.

**Comment by scottkosty** [comment]
@pjf can you reproduce?

**Comment by tbabej** [comment]
Reproduced on 2.5.2, fixed on 2.6.0.

Note that on 2.5.2 this does not happen if the verbosity setting is passed first, i.e.:
`task rc.verbose:nothing rc.report.next.columns=uuid rc.report.next.labels=UUID limit:1`
behaves as expected.

**Comment by tbabej** [comment]
Closing as this is fixed on current development branch.

**Comment by tbabej** [comment]
Just for the record, I believe this is the same issue as #2247.
