### ISSUE TITLE
Compilation broken with -std=c++11

### ISSUE THREAD

**Issue by scottkosty** [GothenburgBitFactory/taskwarrior#2162]
* What command(s) did you run?

```
export CXXFLAGS="-std=c++11"
cmake . &&
make
```

* What did you expect to happen?

Build without error.

* What actually happened?

Received the following error from `make`:

```
[ 24%] Building CXX object src/CMakeFiles/task.dir/CLI2.cpp.o
/home/scott/IndependentInstalls/taskbuilds/bisect/repo/src/CLI2.cpp: In function ‘const char* getValue(int, const char**, std::__cxx11::string)’:
/home/scott/IndependentInstalls/taskbuilds/bisect/repo/src/CLI2.cpp:227:20: error: ‘make_reverse_iterator’ is not a member of ‘std’
   auto last = std::make_reverse_iterator (argv);
                    ^~~~~~~~~~~~~~~~~~~~~
/home/scott/IndependentInstalls/taskbuilds/bisect/repo/src/CLI2.cpp:227:20: note: suggested alternative: ‘make_move_iterator’
   auto last = std::make_reverse_iterator (argv);
                    ^~~~~~~~~~~~~~~~~~~~~
                    make_move_iterator
/home/scott/IndependentInstalls/taskbuilds/bisect/repo/src/CLI2.cpp:228:21: error: ‘make_reverse_iterator’ is not a member of ‘std’
   auto first = std::make_reverse_iterator (
                     ^~~~~~~~~~~~~~~~~~~~~
/home/scott/IndependentInstalls/taskbuilds/bisect/repo/src/CLI2.cpp:228:21: note: suggested alternative: ‘make_move_iterator’
   auto first = std::make_reverse_iterator (
                     ^~~~~~~~~~~~~~~~~~~~~
                     make_move_iterator
make[2]: *** [src/CMakeFiles/task.dir/build.make:63: src/CMakeFiles/task.dir/CLI2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:179: src/CMakeFiles/task.dir/all] Error 2
make: *** [Makefile:152: all] Error 2 
```

Here is version information on gcc:
```
$ gcc --version
gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
```

A bisect leads to d2b1662a.

I don't actually remember why I set this extra flag in my "taskwarrior build script". Probably I was just experimenting a long time ago.

**Comment by grantbow** [comment]
Could [this be related](https://stackoverflow.com/questions/50161210/error-make-reverse-iterator-is-not-a-member-of-std)? Looks like a work around is available.

**Comment by scottkosty** [comment]
@taiyu-len can you reproduce the build error?

**Comment by taiyu-len** [comment]
`std::make_reverse_iterator` was introduced in c++14 and isnt available in c++11
the INSTALL file does mention c++14 as a minimum, but if c++11 compatibility is desired, it could easily be fixed by replacing it with `std::reverse_iterator<const char**>(...)`, or recreating the function which does the same.

**Comment by pbeckingham** [comment]
Which branch?

**Comment by scottkosty** [comment]
@pbeckingham it is on branch 2.6.0.

**Comment by tbabej** [comment]
Taskwarrior now requires C++17 compatibility on 2.6.0, which is documented in DEVELOPER, INSTALL and README.md (see c223b0694c501f62d45743a43c140abff5f3a589 and 54cfc6cab95f87ca3acfb2fafc491e62bebc0816).
