### ISSUE TITLE
Incorrect nagging when completing a task

### ISSUE THREAD

**Issue by korrat** [GothenburgBitFactory/taskwarrior#2163]
## Context

I have a list of tasks like the following:

| ID | Active | Age | Description | Urg |
|----:|----------|-------|-----------------|-------|
| 1 | 2d | 5d | Do something | 14 |
| 2 | 1d | 6d | Do another thing | 13 |

Please note that the above are not actual values but represent the situation for my tasks.

## Steps to reproduce

When running `task next` task 1 is shown as most urgent as one would expect.
When I then run `task 1 done` I get the message "You have more urgent tasks.".

## Expected output

Since task 1 is the most urgent task, my understanding is that this warning should not be shown.

## `task diag`

The output of `task diag` is

```
task 2.5.1
   Platform: Linux

Compiler
    Version: 8.2.1 20180831
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Nov  9 2018 23:33:36
      CMake: 3.12.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.19
 Build type:

Configuration
       File: ~/.taskrc (found), 1432 bytes, mode 100644
       Data: ~/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: vim
     Server:
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: ~/.task/hooks
             (-none-)

Tests
      $TERM: alacritty (277x66)
       Dups: Scanned 86 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 86 tasks for broken references:
             No broken references found
```

## My theory

The following is my personal theory for what is happening behind the scenes. I did not do any
debugging so this is in no way verified. Feel free to ignore it.

The completed task has a start date. When completing the task this start date is removed. My theory is that removing the start date causes the urgency to drop. Therefore task 2 is more urgent when evaluating if the above message should be shown.

**Comment by ddeimeke** [comment]
Do you maybe have tasks in wait state that are more urgent?

Check with "task waiting".

**Comment by korrat** [comment]
`task waiting` shows no tasks

**Comment by pbeckingham** [comment]
Is task ID 1 the highest urgency?  Run `task next` and see if it's first?  Are you using contexts?

**Comment by korrat** [comment]
Yes, task ID 1 was the highest urgency. And all that happened in the default context.

**Comment by tbabej** [comment]
Reproduced on 2.6.0. The theory by @korrat is indeed correct, the crucial part to this is that urgency drops due to the task no longer being in the active state.
