### ISSUE TITLE
Add editor configuration option

### ISSUE THREAD

**Issue by eirnym** [GothenburgBitFactory/taskwarrior#2165]
#### To request a feature...

* Clearly describe the feature.
Add an `editor` configuration option to open with `EDITOR` environment variable as a default.

Some examples for various OSes:

`$ task config editor 'Notepad++'`
`$ task config editor 'gvim -f'`
`$ task config editor "/Applications/MacVim.app/Contents/MacOS/Vim -g -f"`

then call the edit of a task to edit contents in given editor:

`$ task edit 1`

* Clearly state the use case. We are only interested in use cases, do not waste time with implementation details or suggested syntax.

I have a few tools for my edits and want to select tool specific for Task Warrior. E.g. for git/hg I use a different editor than set in my `EDITOR` environment variable as text is more structured than general text. 

* Please see our notes on [How to request a feature](https://taskwarrior.org/docs/features.html)

**Comment by pbeckingham** [comment]
You are describing the feature as it currently is.  It uses `editor` from the configuration, otherwise falls back to `$VISUAL`, then `$EDITOR`, and finally uses `vi` as a last resort.

Please read the documentation `man taskrc`.

**Comment by eirnym** [comment]
thanks, I've missed it.
