### ISSUE TITLE
task-2.5.1 armv8 build 

### ISSUE THREAD

**Issue by grantbow** [GothenburgBitFactory/taskwarrior#2170]
I asked [this question](https://stackoverflow.com/questions/56202329/undefined-reference-compiling-taskwarrior-on-arm-chromebook) on stackoverflow and am also asking here in case others have the same problem.

I tried to build task-2.5.1 on my armv81 chromebook inside a termux session. It didn't work due build dependencies so I installed them then uncompressed and started in a fresh new directory. When I ran `make VERBOSE=1` I got an `undefined reference to __atomic_fetch_add_4` when linking.

```
[ 98%] Linking CXX executable lex
cd /data/data/com.termux/files/home/src/task-2.5.1/src && /data/data/com.termux/files/usr/bin/cmake -E cmake_link_script CMakeFiles/lex_executable.dir/link.txt --verbose=1
/data/data/com.termux/files/usr/bin/c++  -Wall -Wsign-compare -Wreturn-type -std=c++11 -stdlib=libc++  -O3 -DNDEBUG  -rdynamic CMakeFiles/lex_executable.dir/lex.cpp.o  -o lex libtask.a commands/libcommands.a columns/libcolumns.a libtask.a -lgnutls -luuid
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: libtask.a(Nibbler.cpp.o): in function `Nibbler::Nibbler(Nibbler const&)':
Nibbler.cpp:(.text+0x8c): undefined reference to `__atomic_fetch_add_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: libtask.a(Nibbler.cpp.o): in function `Nibbler::operator=(Nibbler const&)':
Nibbler.cpp:(.text+0xe0): undefined reference to `__atomic_fetch_add_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: Nibbler.cpp:(.text+0x104): undefined reference to `__atomic_fetch_add_4'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: libtask.a(Nibbler.cpp.o): in function `Nibbler::~Nibbler()':
Nibbler.cpp:(.text+0x174): undefined reference to `__atomic_fetch_add_4'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/CMakeFiles/lex_executable.dir/build.make:90: src/lex] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/src/task-2.5.1'
make[1]: *** [CMakeFiles/Makefile2:175: src/CMakeFiles/lex_executable.dir/all] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/src/task-2.5.1'
make: *** [Makefile:152: all] Error 2
```

I found [this discussion](https://github.com/riscv/riscv-gnu-toolchain/issues/183) about undefined references in arm builds. I tried adding a -latomic to CMakeFiles/task_executable.dir/link.txt but it didn't change the output.

Any ideas how to fix this?

**Comment by grantbow** [comment]
I read a bit from the stackoverflow comments which seem helpful but still haven't found an answer. Any ideas would be greatly appreciated.

**Comment by wbsch** [comment]
Have you taken a look at the way Termux builds its Taskwarrior package? There's a patch and build config. Also, why not just use the one Termux offers?

Anyway, here's the package info:
https://github.com/termux/termux-packages/tree/master/packages/taskwarrior

**Comment by grantbow** [comment]
Thanks!
