### ISSUE TITLE
Exporting custom reports as JSON

### ISSUE THREAD

**Issue by offray** [GothenburgBitFactory/taskwarrior#2177]
I would like to export reports as JSON. I imagined that it was an already present feature, but if that the case I'm missing something.

The use case is like this:

  * We have a custom report for our hackerspace finances that runs like:

    `task project:Ingresos status:completed finanzas` 

    and produces this kind of output:

    ![](https://i.imgur.com/ByUv3d1.png)

  * Then I would like to run something like:

    `task project:Ingresos status:completed finanzas export`

    and get the JSON export for the previous report, to use it in 3rd part programs and custom scripts.

**Comment by jeffka11** [comment]
This shell command can export any report by extracting the filter criteria and running it as an export command:
`report_export() {
    \task $(\grep "$1.filter" ~/.taskrc | \cut -d '=' -f 2) "${@:2}" export
}`


the just run report_export finanzas. It's a little different than what you have in that you'd run report_export <report> <any search criteria> as opposed to what you have, which is report_export <any search criteria> <report>, but I think it's close enough to be useful.

**Comment by pbeckingham** [comment]
This is already supported via the `export` command, augmented as @jeffka11 indicates above.
