### ISSUE TITLE
Context does not apply with annotate (nor modify)

### ISSUE THREAD

**Issue by zombiefungus** [GothenburgBitFactory/taskwarrior#2180]
#### To report a bug...

* What command(s) did you run?
```bash
task context define active status:pending
task add test
task add another test
task add yet another test
task context active
task 1 done
task test status:pending annotate annotation here
task test annotate how many annotated tasks
```
* What did you expect to happen?
the last command is executed with a context that filters only pending tasks, searching for the word `test` should yield just two tasks (as the previous command) but it prompts the three of them
* What actually happened?
Got prompted to annotate 3 tasks (1 completed) this is unexpected since the active context should make the `status:pending` filter apply
* Paste the output of the ```task diag``` command.
```bash
task 2.5.1
   Platform: Linux

Compiler
    Version: 8.2.1 20180831
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Nov  9 2018 23:33:36
      CMake: 3.12.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.19
 Build type: 

Configuration
       File: /home/freyja/.taskrc (found), 1322 bytes, mode 100644
       Data: /home/freyja/.tasktest (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: nano
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/freyja/.tasktest/hooks
             (-none-)

Tests
      $TERM: xterm-256color (252x61)
       Dups: Scanned 3 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 3 tasks for broken references:
             No broken references found
```
As you can see I'm using a clean task data & hooks for this test

I tried this using not words inside the task description bus tags and the behavior is the same: completed tasks get annotated too

**Comment by pbeckingham** [comment]
Write commands are exempt from context filters, as designed.

**Comment by tbabej** [comment]
@divagant-martian This was implemented on the current development branch with the writeable contexts (see #2402).

**Comment by divagant-martian** [comment]
Hey thanks! It's nice that someone paid more than attention that what the closing comment suggested
