### ISSUE TITLE
Attempting to Build TaskServer Fails with Cannot Determine Link Language

### ISSUE THREAD

**Issue by jessebett** [GothenburgBitFactory/taskwarrior#2183]
I am trying to follow the documentation to start my own task server on a google cloud vm instance. This is a completely new instance (Ubuntu 18.04 LTS) so I need to install the dependencies listed here: https://taskwarrior.org/docs/taskserver/git.html
```
    git
    GnuTLS (likely libgnutls-dev, ideally version 3.2 or newer)
    libuuid
    CMake (2.8 or newer)
    make
    A C++ Compiler (GCC 4.7 or Clang 3.0 or newer)
```

Many of these, as written, are simply not available through `apt` or `apt-get` so it would be appreciated if either the docs were updated to indicate what linux distro these dependency names are written for (I can instantiate the appropriate VM) or otherwise make it obvious for Ubuntu.
Through googling I believe I installed all the correct dependencies. However when I go to the build step I get the following error:

```
cmake -DCMAKE_BUILD_TYPE=release .
-- Configuring C++11
-- System: Linux
-- Looking for SHA1 references
-- Found SHA1 reference: 1d822c2
-- Looking for GnuTLS
-- Looking for libuuid
-- Found libuuid
-- Configuring cmake.h
-- Configuring man pages
-- Configuring done
CMake Error at src/CMakeLists.txt:23 (add_library):
  Cannot find source file:
    libshared/src/Color.cpp
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error: Cannot determine link language for target "libshared".
CMake Error: CMake can not determine linker language for target: libshared
-- Generating done
-- Build files have been written to: /home/jessebett/taskserver.git
```

Can someone point me to what is happening here?

```
CMake Error: Cannot determine link language for target "libshared".
CMake Error: CMake can not determine linker language for target: libshared
```

**Comment by jeffka11** [comment]
Can you share what packages you installed? I tried running 18.04 in Docker to see if it works and with these packages for building:
`build-essential
ca-certificates
cmake
git
gnutls-bin
libssl-dev
libgnutls28-dev
libgnutlsxx28
uuid-dev`

and these packages for running taskserver:
`ca-certificates
gnutls-bin
libgnutls30
libssl1.1
libuuid1
uuid`

and it works for me. I'm not the author of the wiki page, but I think the reason they didn't put specific packages is the names change. For example, the next release of gnutls's development files could be 32, which would change that package name from `libgnutls28-dev` above. Since taskserver is a package in Ubuntu already, you can get a lot of hints on what it needs by looking [here](https://packages.ubuntu.com/bionic/taskd).

As for that exact error, I wonder if when you're cloning, it doesn't pull in libshared's submodule. It worked with a `git clone` for me though. You can check if that's true by going to your taskserver.git/src/libshared and showing what that directory's contents are.

**Comment by jessebett** [comment]
I don't think I realized that `taskserver` was a package under `taskd`. I suspect that I installed the wrong required packages. When I feel the courage to attempt to start another taskserver I will definitely try the package.

It would be really nice if a taskserver docker image existed so that I could just deploy it on a google cloud and then worry about breaking the credentials process (which is how far I got last time before giving up).

When I attempt this next I will try to diagnose what packages I installed that got me this error.

**Comment by jeffka11** [comment]
There's a bunch of docker images [here](https://hub.docker.com/search?q=taskd&type=image). I run based off of Debian so it might be a bit different than yours, but my Dockerfile looks like this:

```
FROM debian:stable as taskd_build

##########################################################
# Install dependencies
##########################################################
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get --assume-yes upgrade && \
    apt-get --assume-yes --no-install-recommends install \
        build-essential \
        ca-certificates \
        cmake \
        gnutls-bin \
        libssl-dev \
        libgnutls28-dev \
        libgnutlsxx28 \
        uuid-dev && \
    apt-get -y clean autoclean && \
    apt-get -y autoremove && \
    rm --recursive --force /var/lib/apt && \
    rm --recursive --force /var/lib/cache && \
    rm --recursive --force /var/lib/log


# Create build, source and dist directories
RUN mkdir /build && mkdir -p /opt/taskd && mkdir -p /usr/src
WORKDIR /build

# Copy source code to build image
COPY subtrees/taskserver /usr/src/taskserver


# Perform build
RUN cmake -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/opt/taskd /usr/src/taskserver && \
    make && make install






FROM debian:stable

##########################################################
# Set environment variables
##########################################################
ENV TASKDDATA /var/taskd
ARG DEBIAN_FRONTEND=noninteractive
ARG TIMEZONE=America/New_York



##########################################################
# Base Config
##########################################################
RUN ln -snf /usr/share/zoneinfo/$TIMEZONE /etc/localtime && echo $TIMEZONE > /etc/timezone
RUN echo 'deb http://deb.debian.org/debian stable-backports main' > /etc/apt/sources.list.d/backports.list




##########################################################
# Users
##########################################################
RUN addgroup --gid 53589 taskd && \
    adduser --uid 53589 --gid 53589 --disabled-password --gecos "taskd" taskd && \
    usermod --lock taskd



##########################################################
# Install dependencies
##########################################################
RUN apt-get update && \
    apt-get --assume-yes upgrade && \
    apt-get --assume-yes --no-install-recommends install \
        ca-certificates \
        gnutls-bin \
        libgnutls30 \
        libssl1.1 \
        libuuid1 \
        uuid && \
    apt-get -y clean autoclean && \
    apt-get -y autoremove && \
    rm --recursive --force /var/lib/apt && \
    rm --recursive --force /var/lib/cache && \
    rm --recursive --force /var/lib/log


WORKDIR /usr/bin
COPY --from=taskd_build /opt/taskd/bin/taskd .
COPY --from=taskd_build /opt/taskd/bin/taskdctl .



##########################################################
# Cleanup
##########################################################
RUN apt-get --assume-yes clean autoclean && \
        apt-get --assume-yes autoremove && \
    rm --recursive --force /var/lib/apt && \
    rm --recursive --force /var/lib/cache && \
    rm --recursive --force /var/lib/log


##########################################################
# Logging
##########################################################
RUN ln -sf /dev/stdout /var/log/taskd.log


##########################################################
# Expose to host
##########################################################
EXPOSE 53589
USER taskd
ENTRYPOINT ["taskd", "server", "--data", "/var/taskd", "--debug"]
```

where subtrees/taskserver is a git subtree in my repo of the taskserver repo and /var/taskd is a volume so data persists.

**Comment by pbeckingham** [comment]
The dependencies as documented are not intended to be operating-system-specific, because that would yield and endless list and infinite maintainence burden. The task is for you to decide the package name for CMake for your system.

Closing because this is more of a "wouldn't it be nice if someone else created an unrelated thing" request.
