### ISSUE TITLE
[Feature request] Allow blocks: relationship (reverse of depends:)

### ISSUE THREAD

**Issue by mooskagh** [GothenburgBitFactory/taskwarrior#2184]
It's quite frequent that I start working on particular task, and realize that there is another one.
Currently it looks like that:
```sh
$ task 100 start   # Task is e.g. "Repair a mouse".
#  Starting doing the task and realize I need to buy a torx screwdriver
$ task add Buy a torx screwdriver
Created task 155.
$ task 100 mod depends:155   # Task 100 is now blocked.
```

It would save some typing in this typical case if it would be possible to write:
```sh
$ task add Buy a torx screwdriver blocks:100  # Adds new-task as a dependency to task 100
```

**Comment by heiderich** [comment]
I think there was such a request already, but could not quickly find it. I seems like the following hook aims to realize this feature:

https://gist.github.com/wbsch/a2f7264c6302918dfb30

Did you test it?

**Comment by mooskagh** [comment]
I didn't know about that script, thanks! I've just installed it and from the first look it does what I need (modulo rough edges like need to run `task undo` twice if I made a mistake while using it).

I'll test it for a few days and then update here whether I find any other inconveniences.

**Comment by mooskagh** [comment]
After a week of testing, it works good enough for me, so closing this issue.
Thanks again for the hook!

**Comment by mhalano** [comment]
I think the hook script is nice, but wouldn't better to create a native, integrated option? I saw the script has some bugs related to edition of the task. Would you mind if I open a new issue to talk about this?

**Comment by tbabej** [comment]
@mhalano Not at all, a new issue to discuss native `blocks:` would be welcome :slightly_smiling_face:
