### ISSUE TITLE
Task crashes with SIGABRT after editing a task using vim

### ISSUE THREAD

**Issue by ccaneke** [GothenburgBitFactory/taskwarrior#2187]
* What command(s) did you run?
I executed the command `EDITOR=vim task 79 edit`
* What did you expect to happen?
I wanted to brute-force change the description of task 79 using the following vim command 
```
:'<,'>s/\%V/What does <cr> mean?
<cr> means carriage return (i.e. the carriage return key) not control + r. Ctrl-r means control+r [5]./
```

to change the task description in vim from:
`Description:              What does <cr> mean?`

to:

```
Description: What does <cr> mean?
<cr> means carriage return (i.e. the carriage return key) not control + r. Ctrl-r means control+r [5]. 
```

* What actually happened?
After executing the search and replace I saved the edited task with (`:w`) then quit vim. Since then Taskwarrior crashes when ever I launch it from the command line and I get a crash report from `gnome-abrt` showing that the reason Taskwarrior crashed is because `task killed by SIGABRT`. I tried reverting the edit using `task undo` but that didn't fix the problem. 

The first command I ran after changing the task description in vim was `task 79 list` and it initially showed "No Matches" even though I have dozens of tasks. However since then
`task list`, `task diagnostics` or `task next`, or any other read subcommand prints the following and causes a core dump:
```
$ task diagnostics
/usr/include/c++/9/bits/basic_string.h:1048: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)
```
I have edited a task description in vim multiple times before so I don't know what went wrong this time.
I noticed that when executing the substitution (i.e. search and replace), vim inserted a highlighted "^@" after the line "What does <cr> mean?" in the description. May be this has something to do with Taskwarrior crashing.
* Paste the output of the ```task diag``` command.
```
$ task diagnostics
/usr/include/c++/9/bits/basic_string.h:1048: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)
```

**Comment by fdcds** [comment]
Could this be related to #2024?

**Comment by tbabej** [comment]
I think @fdcds is correct here. I cannot reproduce this on 2.5.3, and given high similarity to #2024 I'd strongly suspect this is because it's has the same underlying cause as #2024 and is therefore fixed.
