### ISSUE TITLE
Encrypt data

### ISSUE THREAD

**Issue by jvanz** [GothenburgBitFactory/taskwarrior#2191]
I think it would be nice if taskwarrior encrypt the data written in the files. Thus, the user do not need to add external mechanims to do that. Imagine that the user would like to backup the files generated by taskwarrior. He/She can just copy the file some else without worry about data leak.

**Comment by JonasDralle** [comment]
Personally I am in favour of task being a small program writing a simple plain text file, if need be, can be fixed manually via an editor.

**Comment by jvanz** [comment]
> Personally I am in favour of task being a small program writing a simple plain text file, if need be, can be fixed manually via an editor.

This feature does not have to be mandatory. It can be configurable.
Sorry, but what do you mean about editor? An text editor?

**Comment by mooskagh** [comment]
You can setup a private ecryptfs directory (no root required) where taskwarrior files will be located.

**Comment by jvanz** [comment]
Yes, I can. I already encrypted my file system. But I think it would be nice have something built in. Anyway, it just a feature suggestion.

**Comment by JonasDralle** [comment]
> This feature does not have to be mandatory. It can be configurable.
> Sorry, but what do you mean about editor? An text editor?

TaskWarrior write a [flat-file database](https://en.wikipedia.org/wiki/Flat_file_database) to the folder `.task`. Your data is stored inside a JSON-esque format which can easily be edited via a text editor.

[In the past](https://github.com/GothenburgBitFactory/taskwarrior/issues/2063) I already pulled TaskWarrior out of the dirt by using a text editor.

Having the `.task` folder encrypted makes no sense in my _personal_ [threat model](https://en.wikipedia.org/wiki/Threat_model). Maybe you can elaborate why it makes sense in your threat model?
My harddrive is encrypted, giving data protection in case of it getting stolen.
Someone wiretapping the internals of my computer while I am using it is not partof my threat model.

**Comment by pbeckingham** [comment]
The Taskwarrior data is kept plaintext for a reason, which is to always allow the user full access to data, it's a transparency feature.  I don't consider encrypting individual files on a client to be useful. 

Workarounds: encrypt your whole hard drive,  restrict file permissions.
