### ISSUE TITLE
weekstart doesn't apply to +WEEK virtual tag

### ISSUE THREAD

**Issue by matt-snider** [GothenburgBitFactory/taskwarrior#2194]
* What command(s) did you run?
> 
> task rc.weekstart=monday list +WEEK
> 

* What did you expect to happen? 
>
> A task on sunday should be included
> 

* What actually happened?
>
> The task isn't listed, but also viewing the details of the task, it's apparent that the `WEEK` virtual tag isn't set
>

I'm using task 2.5.1 on Linux and I've worked around this by changing the query from `+WEEK` to `(+WEEK or due:sunday)` which is a fine workaround

**Comment by matt-snider** [comment]
I see that this actually caused by #1562 since `WEEK` is applied when [`Task::is_dueweek()`](https://github.com/GothenburgBitFactory/taskwarrior/blob/cad8bec8b630c3a257f6b876bb21f30a84321d06/src/Task.cpp#L439).

**Comment by pbeckingham** [comment]
Duplicates #1899, #1562.
