### ISSUE TITLE
[Feature Request] collaboration

### ISSUE THREAD

**Issue by choman** [GothenburgBitFactory/taskwarrior#2195]
Started using task warrior a couple weeks ago and love it, but I'm finding myself in dire need of task collaboration.   I found TaskArena, but the project is in "broken" status.

Is there anyone else doing this? and with what tool?

Otherwise, I propose a feature request

**Comment by pbeckingham** [comment]
This doesn't tell me anything. Please provide a use case, and justification for this being implemented as a core feature. In general, if something can be implemented outside the core, then it should.
