### ISSUE TITLE
Git integration for backups

### ISSUE THREAD

**Issue by choman** [GothenburgBitFactory/taskwarrior#2196]
Saw the task-giut.sh tool, but not entirely a fan.  I think this would be better if it was directly integrated into task.  So I thought I'd share my thoughts.

Keep up the great work!!!

**Comment by pbeckingham** [comment]
As a feature request, this needs more information, specifically the use case, and a reason why this needs to be integrated into the core.  It doesn't appear to need that.

**Comment by Kevin-Mok** [comment]
I think managing a git repository in the data directory is better than integrating it into the app.

**Comment by JonasDralle** [comment]
The largest reasons for this would be backing up and syncing I think.

I don't think git is the best-ever solution for keeping single user backups. Use your favorite backup solution instead.
Git is also not the best-ever solution for syncing a tasklist between multiple computers.
Consider using taskserver for both backup and sync requirements. See _[Why Do I Need a Taskserver?](https://taskwarrior.org/docs/taskserver/why.html)_

**Comment by xingheng** [comment]
Share my git deployment solution: https://github.com/xingheng/taskwarrior-data
