### ISSUE TITLE
task add rc.uda.jirasummary.type=string jirasummary:"id": The expression could not be evaluated.

### ISSUE THREAD

**Issue by fdcds** [GothenburgBitFactory/taskwarrior#2197]
#### To report a bug...

* What command(s) did you run?
  - `task add 'rc.uda.jirasummary.type=string' 'jirasummary:"id"`'
* What did you expect to happen?
  - A task with the tag `jirasummary:id` should have been created.
* What actually happened?
  - Output: `The expression could not be evaluated.`
* Paste the output of the ```task diag``` command.

```
task 2.5.1
   Platform: Linux

Compiler
    Version: 7.2.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.9.5
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.8
 Build type: None

Configuration
       File: $HOME/.taskrc (found), 4834 bytes, mode 100664
       Data: $HOME/.task (found), dir, mode 40775
    Locking: Enabled
         GC: Enabled
    $VISUAL: /bin/nano
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: $HOME/.task/hooks
     Active: on-modify.timewarrior     (executable)
   Inactive: bkp.on-modify.timewarrior (not executable) (unrecognized hook name)

Tests
      $TERM: screen (655x111)
       Dups: Scanned 66 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 66 tasks for broken references:
             No broken references found
```

Might be reincarnation of #1826 / TW-1805?
Is related to #1720 / TW-1696 and #2124.

**Comment by pbeckingham** [comment]
The UDA needs to be configured beforehand, not provided on the CLI. Also a task without a description is not a task. So first configure the UDA:

    $ task config uda.jirasummary.type string
    ... plus the other necessary settings, see the documentation

Then once the UDA is defined, create a task:

    $ task add <description> jirasummary:id

**Comment by fdcds** [comment]
The same issue happens, even if the UDA is configured:
```
uda.jirasummary.type=string
uda.jirasummary.label=Jira Summary
```

It also happens if a description is present.

Please reopen.
