### ISSUE TITLE
[EX-23] helper command _colors

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#22]
_David Patrick on 2012-09-07T17:50:54Z says:_ 

 Yes, there are brilliant reports to be had under *task colors*, and before you ready ANY further, run the following in a terminal.. 

<pre>
 $ task color

 $ task color legend

 $ task color red on white
</pre>

no.. seriously, if you haven't seen the output of these commands, run them now.. I'll wait..

As you can see, a lot or work has already been been done in the color department, and this feature request seeks to extend that fine work with a couple of tools that will make a complex color themes easier to make and understand. 

The special helper command should be dead-simple, similar to *task color legend* but displaying the available colors (all 256 or 16) monochromatic bands (no this-on-that), with columns for names and numeric values, in the style of other _helper commands, but way more colorful and a bit wider. This is a clear candidate for some external perl script, or something (see the attached file) but looking more like "color legend".

 [  colorA   ]  =  rgb###  =  color###  =  name (if any) 
[  colorB   ]  =  rgb###  =  color###  =  name (if any) 

this handy color reference chart could be used to "hold up next to" other things on your screen, and with a quick grepping for a certain name or number would display just a band of just that color, and all of it's names.

 % tw _colors |grep color123

The attached perl-script, colortest, is sort of the idea (the -r option is no longer working for me) but the sort of thing, available colors in order, not taskwarrior-specific, but showing all of the color-names/codes that taskwarrior can use.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-09-07T17:50:54Z
Modified: 2014-02-09T02:43:22Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2012-09-07T20:14:51Z says:_ 

 not entirely unlike the output of this little script; colortest, but matching our color parameters.

As a bonus, the listing should have indicators for those colors that are ALSO in reduced-palette sets.

**Comment by pbeckingham** [comment]
Color escape sequences are well documented.  No plans to implement.

**Comment by pbeckingham** [comment]
[EX-23_colortest.sh.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755301/EX-23_colortest.sh.txt)
[EX-23_colortest.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755302/EX-23_colortest.txt)
