### ISSUE TITLE
backlog.data universal date

### ISSUE THREAD

**Issue by MHSevgi** [GothenburgBitFactory/taskwarrior#2200]
#### The times of data in the backlog.data
 

* The times of data in the ```backlog.data``` file are recorded as ```universal dates```. Why not register as ```local date```?

`{"description":"new","entry":"20190804T150257Z","modified":"20190804T150257Z","status":"pending","uuid":"5e6dfb3f-4c80-406f-919d-65400724984d"}
`

**Comment by MHSevgi** [comment]
{"description":"new","entry":"**20190804T150257Z**","modified":"**20190804T150257Z**","status":"pending","uuid":"5e6dfb3f-4c80-406f-919d-65400724984d"}

**Comment by pbeckingham** [comment]
That would have been a bad design decision, requiring conversion before every comparison.
