### ISSUE TITLE
Coloring dates with scheduled tasks in calendar report

### ISSUE THREAD

**Issue by justf0rfun** [GothenburgBitFactory/taskwarrior#2208]
#### To request an improvement...

Taskwarrior can be used to manage appointments, like meetings, dates etc. by scheduling tasks. Unfortunately dates with scheduled tasks are not highlighted by coloring in the calendar report.

I would like to see dates where tasks has been scheduled to be colored in the calendar report. As far as I can see (I only use them rarely) due dates are already colored in the calendar report. Scheduled dates should be colored, too, maybe in a different color. 

With scheduled dates highlighted in the calendar report, taskwarrior gets a better tool for all users managing scheduled tasks like appointments with taskwarrior.

As far as I can see, this improvement does not break any existing functionality and does not interfere or only slightly with existing installations. When deployed, either this coloring could be activated for all users by default or users would have to change their configuration to enable the new coloring.

**Comment by pbeckingham** [comment]
Godo suggestion, thanks.

**Comment by sebu06** [comment]
implemented with PR #2539
