### ISSUE TITLE
Clarify nag message

### ISSUE THREAD

**Issue by enricoschumann** [GothenburgBitFactory/taskwarrior#2212]
(I admit this is a very minor issue :-)

The "nag" message "You have more urgent tasks" is
ambiguous: it could also mean there are other
tasks that are urgent as well. Better would be to use a
hyphen: "You have more-urgent tasks" (i.e. there is at
least one task that is more urgent than the one you
just completed).

**Comment by JonasDralle** [comment]
I'm not sure weather the hyphen variant is more clear.
You can change the nag via the `nag config`.

```
ask config nag 'The computer to do list software does not agree with you.'
```

**Comment by enricoschumann** [comment]
Hi Jonas, thank you; yes, I know I can change it.

As I said, it's a very minor issue, so feel free to close it.


-- 
Enrico Schumann
Lucerne, Switzerland
http://enricoschumann.net

**Comment by tbabej** [comment]
Thanks Jonas for pointing the configurability. Closing this for now
