### ISSUE TITLE
Add support for Git backend

### ISSUE THREAD

**Issue by lewisdiamond** [GothenburgBitFactory/taskwarrior#2216]
## Git as the backend storage / sync layer

Instead of using a Taskwarrior server,  I'd like to keep the state in a git repository.
If you're managing a single repository, use something like `refs/tw/...`, if you're managing multiple repositories, maybe have a master git repo for taskwarrior alone and each project specific tasks can be stored in their respective repository.

This way, you would not need to host a server, the storage could be plaintext files following a strict structure, making it easy for people to build on top of taskwarrior as long as the format remains backwards compatible, similar to `pass`, `gopass`, and tools around it. (I can use pass or gopass interchangeably, I can read my passwords by just decrypting it with `gpg`)

**Comment by pbeckingham** [comment]
You can do this already using hook scripts.  There is an example out there, someone did it.

**Comment by lewisdiamond** [comment]
Maybe this should be documented, this link states (https://taskwarrior.org/docs/taskserver/why.html)
`But if you wish to share tasks between several clients, the Taskserver is the only option that properly syncs data.`

**Comment by ngortheone** [comment]
@lewisdiamond 
Yeah, I think that deserves some clarification. Key words there are _"properly syncs"_.  I guess the author meant that Taskserver is doing conflict-free data loss-free merging of the concurrently modified copies of the data. Think of a slightly simplified(or rather domain-specific) version of [JSON CDRT](https://arxiv.org/abs/1608.03960).

With Taskserver clients never face a problem of a merge conflict, when with Git back-end you will either force user to do conflict resolution, or lose data in case automatic merge overwrites some important piece of the data. Both situations are not very user friendly. And while manual merging is probably fine for some desktop power-users, it is not acceptable for mobile clients (I am currently working on android library)

**Comment by pbeckingham** [comment]
"properly syncs"

This refers to sub-line merging, i.e. merging whole attributes, instead of whole-lines or just characters.
