### ISSUE TITLE
Native GTD "someday" report

### ISSUE THREAD

**Issue by JonasDralle** [GothenburgBitFactory/taskwarrior#2220]
Hi. I'm doing GTD with TaskWarrior and I move things to the "Someday" list by changing the `wait` attribute to `someday` (2038-01-18 00:00:00).

It's easy to do but hard to review as a coherent list. Grepping the `waiting` report is something which can be done, but it's not elegant.

Can you add a default `someday` report to the default available reports? It should be fairly trivially doable I think. This is something which GTD users would enjoy and Non-GTD users could ignore easily.
Thanks!

**Comment by svijee** [comment]
If I understand correctly, you just want `task waiting wait:someday`?

**Comment by JonasDralle** [comment]
Whoops. Didn't occur to me that filtering by date comparison is a working thing. I'll just do that instead!
This ticket can tagged and closed as _question_. Thanks!

By the way there's a sister ticket regarding GTD "wait for" list: #2221
