### ISSUE TITLE
Create Recurring Task Daily without Sundays Only

### ISSUE THREAD

**Issue by rudolfschmidt** [GothenburgBitFactory/taskwarrior#2229]
Hi, I tried to use task add recur:daily bla but it includes saturdays and sundays like expected. I could use recur:weekdays but it does not include saturdays. Is there a middle way?

**Comment by hammerheadlemon** [comment]
Can you set separate but identically-named weekly recurring tasks with a due date for each day of the current week, except Sunday? Not ideal but a workaround?

**Comment by rudolfschmidt** [comment]
is the feature implemented?

**Comment by djmitche** [comment]
Just the workaround mentioned by yulqen. We're trying to reduce the number of open, stale issues.
