### ISSUE TITLE
A hook for adding tags so that new tasks appears in the context

### ISSUE THREAD

**Issue by thomasrebele** [GothenburgBitFactory/taskwarrior#2230]
Scenario: I use a "job" tag for work related tasks and a context with filter +job to only display job-related tasks. When I add a task I often forget to define a tag, so it does not appear on the list. Then I have to search the new task, and add the job task. This process is quite tedious.

Today I discovered the hook API. So I wrote a hook to automatically add the job tag on every new task when I'm in the job context. You can find the script [here](https://github.com/thomasrebele/dotfiles/blob/master/config/terminal/taskwarrior.install/.task.dir/hooks.dir/on-add-set-context.symlink).

Is it worth to make a PR with the script as an example in scripts/hooks/?

**Comment by tbabej** [comment]
@thomasrebele Nice example how hooks can be used to provide custom functionality! The ability to add tasks in context is getting native implementation in #2402, so we might not be adding this into the repo at this point, but looking at the number of upvotes, it found its users in the meantime :)

**Comment by thomasrebele** [comment]
Thanks for updating the ticket with the new feature of #2402. Great that this feature has been included directly in taskwarrior.

**Comment by tbabej** [comment]
It's still to be merged and then released, but we're working on it :)
