### ISSUE TITLE
A more formal spec for the backlog format

### ISSUE THREAD

**Issue by suhr** [GothenburgBitFactory/taskwarrior#2231]
Since formal specifications are always better than informal one, I wrote this [CUE](https://cuelang.org/) spec for the [Taskwarrior JSON Format](https://taskwarrior.org/docs/design/task.html): https://gist.github.com/suhr/39dcf9ef042e07a80fe288ed76f2aca8

It is still WIP (~~UDA is not supported yet,~~ some fields are stringly typed), but it looks already nice. Also, `cue vet backlog.json ~/task.cue` works for my backlog.

**UPDATE:** UDA is now supported

**Comment by tbabej** [comment]
Thanks @suhr !

**Comment by djmitche** [comment]
We never intended for that format to be used outside of TW, and in fact at this point it is not used by TW anymore.
