### ISSUE TITLE
Tasksh prompt sometimes appears twice when backspacing

### ISSUE THREAD

**Issue by MrVulcan** [GothenburgBitFactory/taskwarrior#2236]
#### To report a bug...

* What command(s) did you run?
It happens when I backspace after starting to type any command inside tasksh. 

* What did you expect to happen?
I expected to just see the characters to the left of the cursor disappear.

* What actually happened?
The tasksh prompt appeared twice in a row, like this:

```tasksh> tasksh>```

* Paste the output of the ```task diag``` command.

task 2.5.1
   Platform: Darwin

Compiler
    Version: 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Oct 16 2019 19:08:34
      CMake: 3.15.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.10
 Build type: Release

Configuration
       File: /Users/bertvisscher/.taskrc (found), 2034 bytes, mode 100644
       Data: /Users/bertvisscher/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /Users/bertvisscher/.task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (120x30)
       Dups: Scanned 154 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 154 tasks for broken references:
             No broken references found

**Comment by tom-doerr** [comment]
Taskshell is a separate project, you should open an issue over here: https://github.com/GothenburgBitFactory/taskshell

Since Taskshell is separate project, you need to run the `diagnostics` command in `tasksh` to get the diagnostic information.

**Comment by MrVulcan** [comment]
I'll report it there next time I see that bug.
