### ISSUE TITLE
Question: Open files via system "open"

### ISSUE THREAD

**Issue by ChrisGitIt** [GothenburgBitFactory/taskwarrior#2238]
Hi everybody,

I'm more and more into taskwarrior, but there is one thing that is nagging me as a developer!

Is it possible to add a file (or better URI?) reference and use this reference for the system "open" call? In my case, its often a file and http URI.

To explain this a little further: I would like to add one or more file references to a task. For example: "Finish Main Page" is my task, and for this task, i would like to add "file:/path/to/index.html" [and "http://www.test.com" [and "file:/path/to/layout.pdf"]].

So, within my task view, these references should be visible, AND if i click on them, the "open" call should be executed, so my editor will be opened and my browser loads the specified domain.

I'm googling now for about and hour and found "annotate" or "hooks", but these seem to be very complicated to setup for this idea.

Isn't something like this not included out of the box? It seems to be a very basic feature to ease everybodies live.

So, thanks in advance for any feedback or pointing to directions that look promising to explore. Right now, I'm thinking about writing a plugin for this ...

Greets,

Chris

**Comment by duckunix** [comment]
I see two options to try:
1) use a terminal which understands URI
2) I simply pipe task output to urlview : **task <filter> | urlview**  Works for anything I have trained urlview to understand.

**Comment by ChrisGitIt** [comment]
Thanks @duckunix, I think the terminal which understands URI is a simple way to go.
