### ISSUE TITLE
task sync

### ISSUE THREAD

**Issue by cridemichel** [GothenburgBitFactory/taskwarrior#2242]
#### To report a bug...

* What command(s) did you run?
I usually do tasks syncronization through a vpn connection to my university,
anyway if I issue the command: 
```zsh
> task sync
```
with the vpn connection down I can not stop the above
command with CTRL-C or sending a TERM signal.
The only way to stop task syncing is to send a KILL signal (kill -9 ...).

* What did you expect to happen?

CTRL-C should stop syncing

* What actually happened?

I need to send a KILL signal

* Paste the output of the ```task diag``` command.

#### To request a feature...

* Clearly describe the feature.
* Clearly state the use case. We are only interested in use cases, do not waste time with implementation details or suggested syntax.
* Please see our notes on [How to request a feature](https://taskwarrior.org/docs/features.html)

**Comment by cridemichel** [comment]
update: I noticed that after a while taskwarrior exits with an error but still I think it could be more practical if one can stop it by hitting CTRL-C...

**Comment by pbeckingham** [comment]
You want to be able to hit Ctrl-C during a sync, and have no data corruption? Please provide a patch and tests.

**Comment by wfraser** [comment]
In the common case where the network is down, or taskd isn't running, or for whatever reason it simply can't connect to the other end, it's pretty bad to have to wait *over a minute* for it to time out and not be able to even Ctrl-C out. There's no risk of data corruption when the sync itself can't even be started 😉.

If the program is catching SIGTERM, it should at least wait until after the connection is established to do it. Of course catching signals as a way to prevent data corruption is just a huge hack in the first place, and if that's all that's protecting against it that's really insufficient.

**Comment by tbabej** [comment]
Any possible data corruption with interrupted sync would be covered under our recent effort to move to atomic file modifications in #152. Might be easier for that work to wind down and after that is done, we can safely correctly respond to SIGTERM :slightly_smiling_face:

**Comment by djmitche** [comment]
#2860 was filed to reduce the timeout, but I think the new sync in 3.0 doesn't have this issue.
