### ISSUE TITLE
accented letters not rendered

### ISSUE THREAD

**Issue by cridemichel** [GothenburgBitFactory/taskwarrior#2244]
#### To report a bug...

* What command(s) did you run?
```zsh
> task <tasknumber> all  
```
but it is the same if I use "long" and "newest" reports.

* What did you expect to happen?
I would expect proprer rendering of unicode glyphs such as accented letter (e.g. è)

* What actually happened?

this:
![Schermata 2020-03-05 alle 19 54 11](https://user-images.githubusercontent.com/15322138/76015318-58fdb880-5f1b-11ea-99ef-8ac17caa653b.png)
where the question mark symbol should be the accented letter "è"

* Paste the output of the ```task diag``` command.
```text

task 2.5.1
   Platform: Darwin

Compiler
    Version: 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Oct 16 2019 19:08:34
      CMake: 3.15.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.10
 Build type: Release

Configuration
       File: /Users/demichel/.taskrc (found), 3700 bytes, mode 100600
       Data: /Users/demichel/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $VISUAL: vim
     Server: cridesk.phys.uniroma1.it:53589
         CA: /Users/demichel/.task/ca.cert.pem, readable, 4001 bytes
      Trust: strict
Certificate: /Users/demichel/.task//Cristiano_De_Michele.cert.pem, readable, 4011 bytes
        Key: /Users/demichel/.task/Cristiano_De_Michele.key.pem, readable, 24742 bytes
    Ciphers: NORMAL
      Creds: Sapienza/Cristiano De Michele/************************************

Hooks
     System: Enabled
   Location: /Users/demichel/.task/hooks
     Active: on-modify.timewarrior (executable)
   Inactive:

Tests
      $TERM: xterm-256color (201x44)
       Dups: Scanned 48 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 48 tasks for broken references:
             No broken references found

```
#### To request a feature...

* Clearly describe the feature.
* Clearly state the use case. We are only interested in use cases, do not waste time with implementation details or suggested syntax.
* Please see our notes on [How to request a feature](https://taskwarrior.org/docs/features.html)

**Comment by laurence6** [comment]
I have encountered a similar problem before and it seems to have been fixed in the 2.6.0 branch.

**Comment by cridemichel** [comment]
thank you very much for the information

best Cristiano

Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by tbabej** [comment]
Indeed, as @laurence6, this works on 2.6.0.
