### ISSUE TITLE
Configuration override rc.verbose:off

### ISSUE THREAD

**Issue by vigneshprabhud** [GothenburgBitFactory/taskwarrior#2247]
#### To report a bug...

* What command(s) did you run? start
* What did you expect to happen? no verbose output
* What actually happened?

Post starting the task via task <id> start, I am seeing the below output. 

Configuration override rc.verbose:off
Configuration override rc.verbose:off

These 2 are from 2 hooks that I have. Happens only for start command.

* Paste the output of the ```task diag``` command.
task 2.5.1
   Platform: Linux

Compiler
    Version: 7.2.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.9.5
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.8
 Build type: None

Configuration
       File: /windows/work/tasks/.task/.taskrc (found), 2066 bytes, mode 100664
       Data: /windows/work/tasks/.task (found), dir, mode 40777
     TASKRC: /windows/work/tasks/.task/.taskrc
   TASKDATA: /windows/work/tasks/.task
    Locking: Enabled
         GC: Disabled
     Server:
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /windows/work/tasks/.task/hooks
     Active: on-add-v1                 (executable) (symlink)
             on-modify-00-v1           (executable) (symlink)
             on-modify-01.timewarrior  (executable) (symlink)
             on-modify-02.timetracking (executable) (symlink)
   Inactive: v1.ini                    (executable) (symlink) (unrecognized hook name)

Tests
      $TERM: xterm-256color (206x50)
       Dups: Scanned 13 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 13 tasks for broken references:
             No broken references found

**Comment by tbabej** [comment]
Hi @vigneshprabhud,

if you're still encountering this problem, for a fix, we'd need:
* source code of the hooks
* a short example in bash showing how the bug manifests

**Comment by djmitche** [comment]
I suspect this may have nothing to do with hooks.  It appears that the "Configuration override" output occurs during command-line parsing, so order matters:

```
dustin.mitchell@bell ~ $ task rc.verbose=nothing rc.obfuscate=1 rc.color=0 rc.detection=0 rc.defaultwidth=80 rc.gc=no rc.indent.report=4 /system/
     68  3w   x xxxxxxx  xxxx 3d   xxxxxx xxxxxx x xxxx                12.1
     69  3w   x xxxxxxx  xxxx 3d   xxxxxx xxxxxx x xxxxxx              12.1
    135  8d   x xxxxxxx  xxxx 3w   xxxxxx xxxxxx x xxxxxxxxxxxxxx      7.14
    136  8d   x xxxxxxx  xxxx 3w   xxxxxx xxxxxx x xxxx                7.14
    125 13d   x xxxxxxx            xxxx xxxx xxxxx xx xxxxxxxxxxxxxxxx 2.67
```
vs.
```
dustin.mitchell@bell ~ $ task rc.color=0 rc.detection=0 rc.defaultwidth=80 rc.gc=no rc.indent.report=4 rc.verbose=nothing rc.obfuscate=1 /system/
TASKRC override: /Users/dustin.mitchell/tmp/task/.taskrc
[task next rc.color=0 rc.detection=0 rc.defaultwidth=80 rc.gc=no rc.indent.report=4 rc.verbose=nothing rc.obfuscate=1 ( /system/ )]

    ID  Age   P Tag     Recur Due  Description                         Urg
    --- ----- - ------- ----- ---- ----------------------------------- ----
     68  3w   x xxxxxxx  xxxx 3d   xxxxxx xxxxxx x xxxx                12.1
     69  3w   x xxxxxxx  xxxx 3d   xxxxxx xxxxxx x xxxxxx              12.1
    135  8d   x xxxxxxx  xxxx 3w   xxxxxx xxxxxx x xxxxxxxxxxxxxx      7.14
    136  8d   x xxxxxxx  xxxx 3w   xxxxxx xxxxxx x xxxx                7.14
    125 13d   x xxxxxxx            xxxx xxxx xxxxx xx xxxxxxxxxxxxxxxx 2.67

5 tasks
Configuration override rc.color:0
Configuration override rc.detection:0
Configuration override rc.defaultwidth:80
Configuration override rc.gc:no
Configuration override rc.indent.report:4
Configuration override rc.verbose:nothing
Configuration override rc.obfuscate:1
```

I don't know if the best fix there is to document that order matters, or to delay that output until the entire command-line is handled.

**Comment by djmitche** [comment]
(above is with a default .taskrc but with my existing task db)

**Comment by tbabej** [comment]
I see, thanks for following up here @djmitche ! I was able to reproduce this on 2.5.3 release:

```
[warrior@tw-v2.5.3 ~]$ task rc.verbose=nothing rc.obfuscate=1 rc.color=0 rc.detection=0 rc.defaultwidth=80 rc.gc=no rc.indent.report=4 /system/
[warrior@tw-v2.5.3 ~]$ task rc.obfuscate=1 rc.color=0 rc.detection=0 rc.defaultwidth=80 rc.gc=no rc.indent.report=4 rc.verbose=nothing /system/
[task next rc.obfuscate=1 rc.color=0 rc.detection=0 rc.defaultwidth=80 rc.gc=no rc.indent.report=4 rc.verbose=nothing ( /system/ )]
Configuration override rc.obfuscate:1
Configuration override rc.color:0
Configuration override rc.detection:0
Configuration override rc.defaultwidth:80
Configuration override rc.gc:no
Configuration override rc.indent.report:4
Configuration override rc.verbose:nothing
No matches.
```

Fortunately, the issue does not seem to be present on the current development branch:
```
[warrior@tw-2.6.0 ~]$ task rc.verbose=nothing rc.obfuscate=1 rc.color=0 rc.detection=0 rc.defaultwidth=80 rc.gc=no rc.indent.report=4 /system/
[warrior@tw-2.6.0 ~]$ task rc.obfuscate=1 rc.color=0 rc.detection=0 rc.defaultwidth=80 rc.gc=no rc.indent.report=4 rc.verbose=nothing /system/
[warrior@tw-2.6.0 ~]$ 
```

Dustin, is it correct that you were _not_ using development build to reproduce this? If that's the case, it looks like this will be resolved upon our next release :slightly_smiling_face:

**Comment by djmitche** [comment]
Yes, my repro was with 2.5.3 release.

Dustin

**Comment by tbabej** [comment]
This was a regression introduced in 2.5.2.
