### ISSUE TITLE
Support custom virtual tags

### ISSUE THREAD

**Issue by xeruf** [GothenburgBitFactory/taskwarrior#2250]
#### To request a feature...

I know that I can have custom reports and context, but to my knowledge they can't be nested. So if there was a possibility to define custom virtual tags, we could actually reuse filters within filters.

A use case would be having a WORK virtual tag that matches multiple other tags (e.g. dev, uni, study) and then filter the contents of that using other tags or time info. This example could also be satisfied with contexts, but only to a limited degree.

Since all existing virtual tags are mere filters anyways, I see no architectural reason why this would be a challenge.

**Comment by ahillio** [comment]
I would like this feature too!  I haven't used virtual tags yet, but I wonder if or how "custom virtual tags" would be different than an on-modify hook that automotically adds an actual tag based on the criteria?

I have some logic like if client1/client2/client3/etc then apply tag "client" as well... I'm currently doing this manually but it'd be nice to script it or have it supported by virtual tags or something.

**Comment by xerus2000** [comment]
You are right, actually an on-modify hook might solve this for me...

**Comment by Arwalk** [comment]
As noted by @ahillio , on-modify hooks could help.

You could also make a UDA to hide this information behind tag system itself, like a "category" UDA. To take the example mentioned earlier, using a on-modify hook, you could have some basic logic such as "if any tag on  this task is a client_related task, set category to 'clients'".

Filtering all client-related task is then about using `task list category:clients`.

More than virtual tags, it could be interesting to have the same nested-logic on tags than on projects. Projects can already be "nested" with subprojects. If you create a task with "task add project:pro_a.subpro1 test", you can reach this tag with "task list project:pro_a" or "task list project:pro_a.subpro1".

Some kind of subtag management could be very interesting to have.

**Comment by xerus2000** [comment]
What would be an application of subtags? I have two tags `+dev` and `+pc`, where dev could be considered a subtag of pc since everything that is about development needs the computer, but how would that help me?

yeah UDA or tag doesn't make much difference towards the implementation

**Comment by Arwalk** [comment]
Subtags could be used like subprojects.

You could have +pc.dev and +pc.game tasks. Running "task list +pc" would return both, where "task list +pc.dev" would filter precisely +pc.dev tasks.

This would answer the use case you are asking for:

>A use case would be having a WORK virtual tag that matches multiple other tags (e.g. dev, uni, study) and then filter the contents of that using other tags or time info.

**Comment by xerus2000** [comment]
Fair point, but as soon as a tag is a subtag to multiple others this stops working. 
However, if you tag one task with `+pc +game` and the other with `+pc +dev` you can still run +pc to show both and use the other tags to get something more specific - what's the point of the hierarchy? If you add another tag +business with could combine with two other tags +dev and +support you have a problem if you would try a hierarchy - you would need to add +business.dev and +pc.dev, which is nonsense - this is why tags aren't hierarchical, you can simply add +businnes +dev +pc and everything works perfectly.

**Comment by tbabej** [comment]
I think this feature request is actually covered by #1302, which has some future syntax/solutions outlined.
