### ISSUE TITLE
tag filter doesn't work when task has multiple tags

### ISSUE THREAD

**Issue by ahillio** [GothenburgBitFactory/taskwarrior#2251]
When I run the command `task list project:"my cli tools" tag.not:test` it will exclude a task with `tags:"test"` but a task with `tags:"client,test"` gets displayed in the report.  The task with `tags:"client,test"` does have the "test" tag so I would expect it to also be excluded from the report, I want that to be how it works but that's not what's happening here in my testing.

My `task diag` output looks like this:
```
task 2.5.1
   Platform: Linux

Compiler
    Version: 8.3.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.13.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.5
 Build type: None

Configuration
       File: /home/alec/.taskrc (found), 2585 bytes, mode 100664
       Data: /home/alec/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $VISUAL: /usr/bin/vim
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/alec/.task/hooks
     Active: on-modify-watson.py   (executable)
             on-modify.timewarrior (executable)
   Inactive: 

Tests
      $TERM: screen-256color (120x30)
       Dups: Scanned 27 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 27 tasks for broken references:
             No broken references found

```

**Comment by xerus2000** [comment]
The tags should be space-separated and for the projects it is good practice to not include any spaces in the name.

Does it have both tags? I never filtered for tags like this, I would add a task with `task add bla +test +client` and then filter with `task list -test`

**Comment by ahillio** [comment]
Yes I just discovered that.  The shorthand way `task list +tagname` is not only easier to type than `task list tags:tagname` but it actually works as expected :)
I don't know why the other way doesn't work but I guess I won't try to figure it out since the working way is easier to type.  Thanks for chiming in here @xerus2000 !
