### ISSUE TITLE
issue #711 / tw-676 still exists in 2.5.1

### ISSUE THREAD

**Issue by marcusatiliusregulus** [GothenburgBitFactory/taskwarrior#2252]
weekly burndown report numbers weeks from 02 to 53 instead of the expected 01 to 52. this issue was already reported once, then closed but still exists

to reproduce just run `task burndown` and youll see `... 52 53 02 03 ...` at the start of 2020

**Comment by laurence6** [comment]
Seems it has been fixed in the 2.6.0 branch.

**Comment by marcusatiliusregulus** [comment]
ok. in this case ill close this again...
