### ISSUE TITLE
UDA string fields can't start with certain keywords

### ISSUE THREAD

**Issue by Crazybus** [GothenburgBitFactory/taskwarrior#2257]
* What command(s) did you run?

```
task 'rc.uda.test.type=string' add 'test:"start doing the thing"' hello world
```

* What did you expect to happen?

Taskwarrior to add a UDA field "test" with the contents "start doing the thing".

* What actually happened?

Taskwarrior gave the following error
```
The expression could not be evaluated.
```

This issue originally surfaced when BugWarrior ran into an error trying to add a new task for a GitHub Pull request that had a title starting with "start". A minimal example of the command it was running is:

```
task 'rc.uda.githubtitle.type=string' 'rc.uda.githubtitle.label="Github Title"' 'githubtitle:"start documenting x"' add test task
```

After some investigation I found out that any UDA fields starting with certain keywords like "start" and "end" result in the same error. Another example:

```
# Error
task 'rc.uda.test.type=string' add 'test:"end the world"' hello world

# Works
task 'rc.uda.test.type=string' add 'test:"this is fine"' hello world
```

Another interesting bit of information from some testing is that it only errors when the string field starts with a keyword and there is non white space text after the keyword.

```
# Works
task 'rc.uda.test.type=string' add 'test:"start"' hello world
task 'rc.uda.test.type=string' add 'test:"start "' hello world

# Errors
task 'rc.uda.test.type=string' add 'test:"starta"' hello world
task 'rc.uda.test.type=string' add 'test:"start a"' hello world

```

* Paste the output of the ```task diag``` command.

Note: I spun up a docker container with `docker run --rm -ti ubuntu bash` to make sure my local environment wasn't causing the issue

```
root@84635bcc72d0:/# task diag

task 2.5.1
   Platform: Linux

Compiler
    Version: 9.2.1 20200306
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.16.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.11
 Build type: None

Configuration
       File: /root/.taskrc (found), 1381 bytes, mode 100644
       Data: /root/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /root/.task/hooks
             (-none-)

Tests
      $TERM: xterm (237x24)
       Dups: Scanned 2 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 2 tasks for broken references:
             No broken references found
```

**Comment by xerus2000** [comment]
Might be related to https://github.com/GothenburgBitFactory/taskwarrior/issues/2069

**Comment by tbabej** [comment]
Actually I think this is the same issue as #1908.
