### ISSUE TITLE
Use GitHub Issue Templates

### ISSUE THREAD

**Issue by xeruf** [GothenburgBitFactory/taskwarrior#2259]
The current template contains a lot of noise and fits multiple things at once - GitHub now allows you to define multiple issue templates for different types of issues, so it would help to make use of them.

**Comment by pbeckingham** [comment]
Good idea. Please contribute to the project.

**Comment by kwoot** [comment]
Check.

**Comment by djmitche** [comment]
We did recently remove the PR template, as it was often ignored, but the issue template is frequently useful in structuring bug reports, so we will keep it.
