### ISSUE TITLE
sync fails on recur:1m

### ISSUE THREAD

**Issue by szigetva** [GothenburgBitFactory/taskwarrior#2268]
I added some recurring tasks with `recur:1m` (I expected this to mean 'one month').  Everything worked fine, `task recurring` lists the new tasks with Recur value P30D.  When I sync I get `Sync failed.  The Taskserver returned error: 500 The recurrence value '1m' is not valid.` I deleted the recurring tasks, but it did not help (because it still wants to sync first creation, then deletion with the "invalid" value `1m`).  Eventually I partly solved the problem by manually deleting all entries with `recur:1m` from `.task/backlog.data`, I have readded the tasks with `recur:1mo`.  Now syncing works, but interestingly `task recurring` does not show these tasks.  `task ID` (where ID is their number) does say `Status Recurring` and `Recurrence 1mo`.

<code>
$ task diag

task 2.5.1
   Platform: Linux

Compiler
    Version: 8.2.1 20180831
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Nov  9 2018 23:33:36
      CMake: 3.12.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.19
 Build type: 

Configuration
       File: /home/szigetva/.taskrc (found), 1882 bytes, mode 100644
       Data: /home/szigetva/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $VISUAL: nvim
     Server: xxxxx.xxxx.xx:53589
         CA: /home/szigetva/.task/ca.cert.pem, readable, 3765 bytes
      Trust: ignore hostname
Certificate: /home/szigetva/.task/szigetva.cert.pem, readable, 3765 bytes
        Key: /home/szigetva/.task/szigetva.key.pem, readable, 24745 bytes
    Ciphers: NORMAL
      Creds: Public/szigetva/************************************

Hooks
     System: Enabled
   Location: /home/szigetva/.task/hooks
             (-none-)

Tests
      $TERM: xterm-termite (133x37)
       Dups: Scanned 710 tasks for duplicate UUIDs:
             Found duplicate b682a43d-6eda-4cdb-8361-95c73b55a97c
             Found duplicate f8f27865-2b4f-4728-b3d1-94cbb85d7671
 Broken ref: Scanned 710 tasks for broken references:
             No broken references found

</code>

**Comment by bentwitthold** [comment]
I got this problem too.
My hacky workaround was to set the recurrence to "monthly":
`task x mod recur:monthly`
and replacing all "recur":"1m" with "recur":"monthly" in the backlog.data.

Now it seems everything is working as expected again.

**Comment by coaxial** [comment]
Ran into this as well, but had to delete my backlog.data to make it work as it wouldn't sync anymore and editing the file to change `1m` to `1mo` would yield a key error when syncing.

I have a hook that syncs with the server after every task modification so I didn't lose that much data, but it would be nice if it didn't happen in the first place.

There seems to be a missing check somewhere that lets users `recur:1m` when that's not a valid value.

```
$ task --version
2.6.1
```

**Comment by djmitche** [comment]
The new sync server doesn't have any special handling of recurrence, so this won't be an issue in 3.0. The workaround of re-initializing sync is a good fix.
