### ISSUE TITLE
Add ability to add shorthand for attributes

### ISSUE THREAD

**Issue by xerus2000** [GothenburgBitFactory/taskwarrior#2270]
## To request a feature...

One of my main problems with the current CLI and why I am considering writing my own little script is the verboseness. What I would love is if I could specify a shorthand for any attribute, whether default or user-defined, in the rc. Especially things such as project I would alias to p and priority to prio. Typing these things out all the time when cleaning up or adding things to the task list is quite tedious.

**Comment by tbabej** [comment]
Attribute names can be abbreviated to their unique prefixes, i.e. the following works out of the box:

```
task add Test pro:myproject pri:H
Created task 6.
```

This also works out of the box for user-defined attributes (here I have an UDA called "component"):
```
task add Test with UDA com:myudavalue
Created task 7.
```

**Comment by xerus2000** [comment]
thanks, wasn't fully aware of that. Is it in the documentation?

**Comment by tbabej** [comment]
Looking into the manpage, it only lists command abbreviation, but not attribute abbreviations, so that would be something to add:

    COMMAND ABBREVIATION
       All Taskwarrior commands may be abbreviated as long as a unique prefix is used, for example:

              $ task li

       is an unambiguous abbreviation for

              $ task list

       but

              $ task l

       could be list, ls or long.

       Note that you can restrict the minimum abbreviation size using the configuration setting:

              abbreviation.minimum=3
