### ISSUE TITLE
Manually adjusting urgency coefficient does not update existing tasks

### ISSUE THREAD

**Issue by xerus2000** [GothenburgBitFactory/taskwarrior#2271]
#### What happens:
`export TASKDATA=~/.test && task add test due:today && task _get 1.urgency` reports 9.2
I set urgency.due.coefficient in the taskrc to 5 by editing it
`task _get 1.urgency` still reports 9.2
`task config urgency.due.coefficient 5 && task _get 1.urgency` reports 3.8

#### Expected

After an urgency coefficient is changed, regardless of how, all urgencies should be recalculated.

**Comment by tbabej** [comment]
Could not reproduce on 2.6.0. I strongly suspect this is an typo in the `~/.taskrc` file when setting the urgency coefficient the first time. The `task config` command just writes into the configuration file, so those two "ways" of setting the config value are actually undistiguishable to task (see the message coming out of task config).

```
$ task add test due:today
Created task 1.
$ task _get 1.urgency
8.89967
$ vi ~/.taskrc
$ grep urgency ~/.taskrc
urgency.due.coefficient=5
$ task _get 1.urgency
3.70837
$ task config urgency.due.coefficient 5 && task _get 1.urgency
Are you sure you want to change the value of 'urgency.due.coefficient' from '5' to '5'? (yes/no) yes
Config file /root/.taskrc modified.
3.70881
```
