### ISSUE TITLE
report filtering on tags incorrect

### ISSUE THREAD

**Issue by slmeyer** [GothenburgBitFactory/taskwarrior#2276]
I created a report like the simple report from the documentation, but created filtering and sorting on custom tags like:
task config report.weekly.filter 'tags:tagname'
I have from one to four tags on each task
When I run task +tagname I get 21 tasks all with the tagname tag
When I run the report I only get 10 tasks listed

**Comment by tbabej** [comment]
@slmeyer With `tags:tagname` you are testing for equality - which means the report won't list the tasks that contain `tagname` and possibly some other tags. You should be able to use `tags.contains:tagmane` or even '+tagname' as the filter directly.

**Comment by slmeyer** [comment]
Thanks for the clarification :)
