### ISSUE TITLE
[TW-179] Incorporate a pager

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#228]
_Paul Beckingham on 2009-05-25T21:50:41Z says:_ 

 Incorporate a pager for long report output

Bruce Dillahunty

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-05-25T21:50:41Z
Modified: 2014-07-01T22:43:51Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2009-11-07T13:25:55Z says:_ 

 The upcoming version of "ledger-cli":http://wiki.github.com/jwiegley/ledger (which is going to be flat-out awesome) has moved to a pager for output, and it is very likeable. 

An interesting adjunct to the pager might be the option to allow a re-draw on change of source data. One could keep several such paged queries open, and watch them update as task data is changed elsewhere. (I think UltraFredde suggested this long ago, and now I see where he was going with that)

**Comment by taskwarrior** [comment]
_David Patrick on 2009-11-07T18:55:39Z says:_ 

 the pager means another color option;

 color.pager.bg=nicecolor

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2009-11-08T14:10:25Z says:_ 

 Need some clarification here.  The original request from Bruce was to use a pager for long output, or in other words, when there is more than a screenful of output.  The pager in this case is any piece of software that does what "less" and "more" do.

Could you tie these together a bit more?  I don't understand how

    color.pager.bg=nicecolor

would be used.

**Comment by taskwarrior** [comment]
_David Patrick on 2009-11-08T16:12:56Z says:_ 

 Paul Beckingham wrote:
> Need some clarification here.  The original request from Bruce was to use a pager for long output, or in other words, when there is more than a screenful of output.  The pager in this case is any piece of software that does what "less" and "more" do.

More like less, I hope! ;-)
> 
> Could you tie these together a bit more?

I see three possible conditions for the pager;

off
iflongerthan
on

If "on" then task always outputs to a pager. The pager can be updated externaly, or at least, triggered to re-run command, so that if Fredde has 10 windows open, and makes a change, it will be reflected in each window in real-time. 
The pager function is the logical place for Xterm title-bar output, too, (feature #309) and this would effectively label each live windows purpose.

 I don't understand how
> 
>     color.pager.bg=nicecolor
> 
> would be used.
 
just because you're a super-hacker, doesn't mean things can't look nice, Paul.

ForrestGreen, anyone ?
djp

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2009-11-08T16:30:53Z says:_ 

 I'm still confused by:

    color.pager.bg=nicecolor

The output from task is generally already colored by various rules.  Does this new color:

a) add a background color to whatever task is already using, for all output?
b) replace whatever color task is already using, for all output?
c) specify the color of the pager prompt?
d) something that I'm too dim to spot?

**Comment by taskwarrior** [comment]
_David Patrick on 2009-11-08T20:37:31Z says:_ 

 Paul Beckingham wrote:
> I'm still confused by:
> 
>     color.pager.bg=nicecolor

I'm sorry, I should have prefaced it with suggestion that the above line might be a new .taskrc setting, not a new function.
> 
> The output from task is generally already colored by various rules.  Does this new color:
> 
> a) add a background color to whatever task is already using, for all output?
no, just the pager bg

> b) replace whatever color task is already using, for all output?
no, just the, y'know, pager

> c) specify the color of the pager prompt?
no, that would be "color.pager.prompt="   # as another new color setting for .taskrc

> d) something that I'm too dim to spot?
nope, something I'm too dim to illuminate, I hope this context clarifies,
djp

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2010-05-29T13:50:06Z says:_ 

 We might look at (at)git log@ or (at)git whatchangend" for this.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-06-27T17:55:52Z says:_ 

 Needs Table.cpp work.  Lots of it.  If we wait until 2.0, we'll hav a new View, and this might be much simpler.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-06-25T17:22:44Z says:_ 

 The 'limit:page' feature is reducing the need for this one.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-07-04T22:03:57Z says:_ 

 No longer required.

**Comment by taskwarrior** [comment]
_Justin Forest on 2012-12-29T04:12:30Z says:_ 

 Paul Beckingham wrote:
> The 'limit:page' feature is reducing the need for this one.

This is different.  With a pager you can easily search a long list of tasks quicker than issuing several task /re/ searches.  With a pager you quickly see top of the list, without having to scroll back, but can easily access the rest by hitting PgDn, without having to run task rc.limit:page=1000, etc.

The solution proposed in the forums (http://taskwarrior.org/boards/1/topics/1013), which involves piping the output to less, doesn't work, because some commands require input, which less breaks (e.g., "task edit" or mass modification, which requires a confirmation).

Here's a patch that uses the PAGER environment variable, like one'd expect in UNIX.  I'm willing to further work on this patch to make it acceptable, if there are problems.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-12-30T20:21:52Z says:_ 

 > I'm willing to further work on this patch to make it acceptable, if there are problems.

Thanks Justin, this is very good, it does the trick nicely, and I would like to have this in the product.  But I can't apply the patch without a fair amount of additional work.  Here are the issues that must be addressed to make this a complete patch:
1.  Uses non-localized output strings.  It's okay to not provide translated es-ES strings, but these should at least be stubbed.  Unless you speak Spanish, that is.
1.  Documentation not updated (man pages (task.1.in, taskrc.5.in), ChangeLog, NEWS)
1.  Coding style differs from the codebase (cuddled braces, declarations at top)
1.  No unit tests.
1.  Redundancy: uses "std::cout << output" five times.
1.  Should the "system(pager_command)" be an exec instead?  The system call is just going to fork again.
1.  Should be controlled by a tw setting as well.  I might want to use $PAGER for one app, but not all apps.
1.  Signature should use "const std::string&".

http://taskwarrior.org/projects/taskwarrior/wiki/What_makes_a_good_patch

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-01-13T21:51:48Z says:_ 

 Moving from 2.2.0 to 2.3.0 - I don't think we're going to close this with Justin in time for 2.2.0.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-06-09T20:04:57Z says:_ 

 Moving to 2.x - Justin, if you're able to fix this in time, it might be moved back to version 2.3.0, otherwise this is heading for permanent rejection.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-07-01T22:43:51Z says:_ 

 Never heard back.

**Comment by pbeckingham** [comment]
[TW-179_pager.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755555/TW-179_pager.patch.txt)

**Comment by soraxas** [comment]
Hi @pbeckingham will this pager patch get merged in the repo's source?
