### ISSUE TITLE
how could list task that have done?

### ISSUE THREAD

**Issue by iysheng** [GothenburgBitFactory/taskwarrior#2284]
#### To request a feature...
When a period of time has passed, I want to know what tasks have been completed, how do I list them?

**Comment by Arwalk** [comment]
There are multiple ways to do that:

- Use the "completed" report.  `task completed`
- Filter the "all" report with the +COMPLETED virtual tag `all +COMPLETED`

Both can be filtered by the "last modified" value, meaning if you want to know which task you completed today, you can use `task completed modified:today`

Refer to the documentation for more details.

**Comment by iysheng** [comment]
> There are multiple ways to do that:
> 
>     * Use the "completed" report.  `task completed`
> 
>     * Filter the "all" report with the +COMPLETED virtual tag `task all +COMPLETED`
> 
> 
> Both can be filtered by the "last modified" value, meaning if you want to know which task you completed today, you can use `task completed modified:today`
> 
> Refer to the documentation for more details.

thanks for your reply, i get it.
