### ISSUE TITLE
question: status of improvements for recurrence?

### ISSUE THREAD

**Issue by ahillio** [GothenburgBitFactory/taskwarrior#2286]
I see at https://github.com/GothenburgBitFactory/taskwarrior/issues/1835#issuecomment-365710315 that the improvements outlined at https://taskwarrior.org/docs/design/recurrence.html were slated for the 2.6 branch, which is now the default branch.

I looked through the commits a bit but didn't see any mention of "recurrence" or "rtype" in the last 12-18 months.

I'm currently using 2.5.1 and don't compile programs often so it's cumbersome for me to try and testdrive to see if features have been added.  So my question....

Is there any progress towards the improvements described on the tw design/recurrence page?

Thanks for the great software :)

**Comment by xerus2000** [comment]
No, and there is no need to look that deep to find that out: Development has stalled recently. 
You have 3 options:
- continue using taskwarrior, using extensions to amend missing functionality (https://github.com/JensErat/task-relative-recur and https://github.com/tbabej/task.shift-recurrence come to mind for recurrence)
- look into forking
- try alternatives such as [pydo](https://github.com/lyz-code/pydo)

**Comment by gour** [comment]
> You have 3 options:

Let me add another option which I have pursued: [etm](https://github.com/dagraham/etm-dgraham) - it does everything what taskwarrior-3.0 was supposed and even more. :smiley:

**Comment by xerus2000** [comment]
Oh wow, etm looks neat, definitely need to look into that. CC @lyz-code

**Comment by tbabej** [comment]
Recurrence overhaul is one of the target features for 2.6 (which also might be called 3.0, since we will make some breaking changes in that release). The actual date of the release is unclear, right now we have to restart the development and, well, clear up the issue backlog, which is what I'm doing right now :) one step at a time.
