### ISSUE TITLE
execute task taskID info cause core dump

### ISSUE THREAD

**Issue by iysheng** [GothenburgBitFactory/taskwarrior#2289]
#### To report a bug...

* What command(s) did you run?
task 11 info
* What did you expect to happen?
show information about task 11
* What actually happened?
```
▸ task 11 info
/usr/include/c++/10/bits/basic_string.h:1019: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)
```

**Comment by scottkosty** [comment]
Thanks for the report. Please always give your Taskwarrior version (run `task --version`). Also, can you paste the output of the command `task diagnostics`? Are you familiar with how to compile Taskwarrior and how to use GDB to get a backtrace?

**Comment by tbabej** [comment]
Please reopen if necessary information is provided.

**Comment by iysheng** [comment]
after i update to 2.5.2, it's ok now.
