### ISSUE TITLE
[TW-180] Standard time functions

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#229]
_Frédéric Mangano on 2013-06-08T09:01:10Z says:_ 

 strftime and strptime provide powerful formatting and parsing functions, and people are used to them.
I have no idea why taskwarrior doesn’t use them.

In its current state, the date parser makes assumptions that doesn’t apply to all languages. For instance, it expects that the first three characters of a month’s name are enough to make it unambiguous. In French however, “Juin” and “Juillet” both start with “Jui”.

The attached patches enable the use of standard format strings (with %), while being compatible with the format strings Taskwarrior current uses.

It would be easy to allow only the latter, but I’d strongly suggest deprecating the current format.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-06-08T09:01:10Z
Modified: 2015-05-09T09:35:39Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-06-08T21:55:41Z says:_ 

 Missing unit tests.

**Comment by taskwarrior** [comment]
_Frédéric Mangano on 2013-06-09T10:19:56Z says:_ 

 They already exist. If you trust them, they prove these patches don’t break anything.

I’d like your opinion concerning the %-notation. Are you considering deprecating the current format?

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-05-09T09:35:39Z says:_ 

 I'm closing this issue because a lot of time has passed, and current Taskwarrior versions use ISO dates everywhere.

Frédéric, if you think that your needs are not fulfilled by ISO dates and your patches is still needed in one way or another, please speak up.

Sorry for the long feedback delay here, your patch appears to have gone below the radar for some reason.

**Comment by pbeckingham** [comment]
[TW-180_0006-date-parsing-using-strptime.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755558/TW-180_0006-date-parsing-using-strptime.patch.txt)
[TW-180_0007-date-formatting-using-strftime.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755559/TW-180_0007-date-formatting-using-strftime.patch.txt)
