### ISSUE TITLE
Have docs of pdf be supported download?

### ISSUE THREAD

**Issue by agent-kimbley** [GothenburgBitFactory/taskwarrior#2297]
I prefer to read pdf in iPad,I try download all doc,but that’s timehole.

**Comment by Trial-In-Error** [comment]
Wait, what exactly is this issue for? I don't understand.

**Comment by xdhmoore** [comment]
I think OP wants to be able to read the documentation as a PDF.

**Comment by pbeckingham** [comment]
Are you willing to provide an automated converter so we can produce these PDFs on release?

**Comment by kwoot** [comment]
I propose to convert current doc to asciidoc and use asciidoctor to convert to both html and pdf.
I have written several books this way, so I can do this (if there's not a deadline).
