### ISSUE TITLE
How set up  neovim to be editor of Taskwarrior 

### ISSUE THREAD

**Issue by agent-kimbley** [GothenburgBitFactory/taskwarrior#2298]

**Comment by agent-kimbley** [comment]
When I use `task edit `open that.

**Comment by Arwalk** [comment]
You need to set up the "editor" configuration variable in your taskrc file. Or set the $EDITOR environment variable.

See https://linux.die.net/man/5/taskrc with a quick search on "editor".

**Comment by pbeckingham** [comment]
This is is docoumented.
