### ISSUE TITLE
Project-specific limit: feature

### ISSUE THREAD

**Issue by OmarElAshkar** [GothenburgBitFactory/taskwarrior#2304]
I want to display only one task in every project I have. So If I have 5 projects and in each of them I have 10 tasks, my 'task next' report is not stuck with only one project.

**Comment by Trial-In-Error** [comment]
Hmm. I'm not sure there's a way to do this. You could use a report that sorts by priority and keep the most important / up next task in each project marked as `priority:H` or `+next`. For instance, the default `task list` report sorts by project first, but `task next` sorts by priority first.

**Comment by tbabej** [comment]
There is no way to do that directly right now, one would have to write a bash script to loop over all active projects, and use a separate `task limit:2 project:<project>` command for each `<project>`.

**Comment by tbabej** [comment]
Closing for now, but happy to re-open and discuss if there is more interest.
