### ISSUE TITLE
Documentation feedback: gap between introductory and advanced material is big

### ISSUE THREAD

**Issue by Zimamazim** [GothenburgBitFactory/taskwarrior#2307]
# Background

I was searching for todo list manager and I found Taskwarrior. So the first thing I did was to read the doc to see if it is any good, how to get started and to get an overall idea if this is the project I wanna go with. And after a while reading through doc I realized it is quite awesome. However as a newbie I think I could give you some useful feedback to your doc.

# Description

Your Getting started is amazing. It is really convenient for a quick start. However before I decide for a project I'd like to know if it will suit me even in the intermediate tasks. And so I tried to read more. And this is the point where I found your documentation lacking. There is an enormous gap between basic four command and understanding more.

The Getting started guide points you to the doc index and section Best practices. However in this phase I'd like to know what basic features are available. Instead the index of documentation contains links to comprehensive site for every topic. Which is great but I don't know the topics yet and I don't understand terms you are using. Best practices just briefly mentions some features in the section tips and terminology is again quite comprehensive and filled with terms beginner doesn't really need.

For example finding what attributes are available is really hard task. The best thing I found was [Columns page](https://taskwarrior.org/docs/commands/columns.html) which is dug deep down in the documentation

# Idea how to fix it

I'd love to see a doc page in between Getting started and what you call Basic usage. I'd argue that the Basic usage is more intermediate than basic. I'd love to see a page where basic principles are explained and shown with links where one can find more. Topics such as tags, priority, basic dates (Using dates effectively) followed by searching, filters and maybe reports without IMHO intermediate/advanced topics such as Unicode and Date & Time (the comprehensive one).

I hope I helped

**Comment by tbabej** [comment]
Thanks for the time to write this up, we're writing this down for future doc improvements!
