### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by prcmt** [GothenburgBitFactory/taskwarrior#2311]
Don't know a better way of asking this - what is the status of taskwarrior?

It hasn't had a release for more than 4 years. Is it considered mature and stable, lacking contributors, abandoned?

**Comment by cpgw** [comment]
Good question! I'm wondering about the same thing. If I look at the insights I see some single commits over the last months, but an active projects looks different.
I thinking about moving to a different todo application. The status of taskwarrior is one important argument for go or no go...

**Comment by prcmt** [comment]
I am not unsatisfied with the current state of taskwarrior. I would consider it pretty stable, I'm mostly curious about what the maintainers' views are.

**Comment by Trial-In-Error** [comment]
As a user of taskwarrior, I'm looking forwards to 2.6.0 (better recurrence?), but also don't have confidence it'll ever arrive. But that's alright with me because I've been heavily using taskwarrior for 3 years now, and it still very much meets all my needs & is very stable.

**Comment by kloczek** [comment]
Yep it is a bit unhealthy as in repo is now more than 900 commits since last 2.5.1 release ..

**Comment by pbeckingham** [comment]
Project is alive and heading towards a 2.5.2 release.

**Comment by tbabej** [comment]
:slightly_smiling_face: Closing this for now, more info can be found in #2338.
