### ISSUE TITLE
Delete all recurring tasks permanently 

### ISSUE THREAD

**Issue by rudolfschmidt** [GothenburgBitFactory/taskwarrior#2312]
Hi,
I have used the recurring feature to recreate certain tasks. I had to notice that the recurring template has not used all parameters I have put like wait etc, I have done it one year ago and stopped using recurring because it has unpredictable behavior. I want to delete all tasks that are related into recurring, most of them were not important or useful anyway, to get clear stats. What would be the best way to delete all recurring and its created tasks from history permanently?

**Comment by Trial-In-Error** [comment]
You'll want to write a filter that finds them all (for instance, `task recur all`). Then run `task <filter> purge`. Purge is different than delete in that it removes all record of that task ever existing.

**Comment by rudolfschmidt** [comment]
> You'll want to write a filter that finds them all (for instance, `task recur all`). Then run `task <filter> purge`. Purge is different than delete in that it removes all record of that task ever existing.

task recur all gives me zero matches

**Comment by Trial-In-Error** [comment]
Hmm. I can find all the instances generated from a recurring task with `task recur all` (or `task recur.any: all`). I can find all the parent recurring tasks with `task status:recurring all`.  Do you have some default filters or context preventing you from seeing them? How do you normally find the recurring tasks you want to purge?

**Comment by rudolfschmidt** [comment]
`task status:recurring all` shows me the tasks but I have many of them, what is the command to purge all of them?

**Comment by rudolfschmidt** [comment]
nobody who knows what is going on?

**Comment by tbabej** [comment]
Hi  @rudolfschmidt, to successfully purge a task, it first must be deleted (I have an open PR that makes this more obvious, see #2358). So in this particular case, you need to delete the child, purge it, then purge the recurrence template.

Please reopen this issue if this does not help!
