### ISSUE TITLE
virtual tags part of `task export`

### ISSUE THREAD

**Issue by kdheepak** [GothenburgBitFactory/taskwarrior#2313]
### Description

I'm interested in having `task export` contain information about virtual tags.

Currently running `task export` gives the following:

```
$ task export
[
{"id":28,"description":"Refactor taskwarrior-tui for multi threading support","entry":"20200802T221045Z","estimate":"30","modified":"20200802T221045Z","status":"pending","uuid":"791af4ca-8711-43af-98e9-e3213c4de3fa","urgency":1.8}
]
```

I'm interested in `task export` giving something like this:

```
$ task export
[
{"id":28,"description":"Refactor taskwarrior-tui for multi threading support","entry":"20200802T221045Z","estimate":"30","modified":"20200802T221045Z","status":"pending","uuid":"791af4ca-8711-43af-98e9-e3213c4de3fa","urgency":1.8,"vtags":["PENDING","READY","UDA","UNBLOCKED","LATEST"]}
]
```

The use of `vtags` as a key here is just an example. I'm interested in having the data as part of the json export and don't feel strongly about whether it is part of `tags` or in a new field called `vtags`.

### Use case

I'm currently building a terminal user interface for taskwarrior. Here's an example of what this looks like:

![https://github.com/kdheepak/taskwarrior-tui](https://user-images.githubusercontent.com/1813121/88654924-40896880-d08b-11ea-8709-b29cc970da4c.gif)

I would like so show `ACTIVE`, `BLOCKED`, `BLOCKING`, `DUE` tasks in a different color.

Currently, I think the only way to get this information is to run `task {id}`, get the output string and parse it for virtual tags (please correct me if I'm wrong about this). This results in a large number of sub-processes spawned to get that information for all tasks.

### Implementation

It is probably fairly easy to add something like the following:

```
    ⋮997 │
    ⋮998 │  out << ",\"vtags\":[";
    ⋮999 │
    ⋮1000│  if (hasTag ("ACTIVE"))    out << ",\"ACTIVE\"";
    ⋮1001│  if (hasTag ("PENDING"))   out << ",\"PENDING\"";
    ⋮1002│  ...
    ⋮    │  ...
    ⋮    │  ...
    ⋮1023│  out << "]";
```

at around this line: https://github.com/GothenburgBitFactory/taskwarrior/blob/8b4ae3b54b44dfbd00b96cdd6dceb8dfe7cc1ea0/src/Task.cpp#L996

Is there some reason this feature has not been considered? This is the only related discussion I could find on the topic: https://github.com/GothenburgBitFactory/taskwarrior/issues/1842. It seems like this would be a feature appreciated by people building tooling on top of taskwarrior.

### How to request a feature: https://taskwarrior.org/docs/features.html

I've read the notes on requesting a feature and I've tried to follow the guidelines. Let me know if you'd like any more information.

Thank you all for building and maintaining taskwarrior! It is a tool I use everyday and it is awesome!

**Comment by tbabej** [comment]
> Currently, I think the only way to get this information is to run task {id}, get the output string and parse it for virtual tags (please correct me if I'm wrong about this).

Not necessarily, technically all the information in the virtual tags can be reconstructed using the data that is already in the export.

That said, I can see that this would simplify things for the downstream tools integrating with TW. If this is added to TW, I'd say it should not be the default, but a behaviour hidden away behind a configuration option (that defaults to off), for two reasons:
* Exporting virtual tags is going to introduce performance penalty
* Other downstream tools might explicitly _not_ expect virtual tags in the output

**Comment by kdheepak** [comment]
How can you figure out if a task is active or not from the export? Maybe I am missing something?

**Comment by tbabej** [comment]
ACTIVE virtual tag task is simply defined as "task has an start attribute":

```
$ git grep ACTIVE | grep Task.cpp
src/Task.cpp:    if (tag == "ACTIVE")    return has ("start");
```

I'd recommend browsing through Task.cpp for the definitions of the virtual tags or [looking at the list here](https://taskwarrior.org/docs/tags.html).

**Comment by kdheepak** [comment]
Okay thanks! I will look through them all!

**Comment by djmitche** [comment]
Now that we have taskchampion, which exposes virtual tags in the API, I think that's a better way to access this information, rather than `task export`.
