### ISSUE TITLE
Cannot output my task list

### ISSUE THREAD

**Issue by MadHatter122312** [GothenburgBitFactory/taskwarrior#2314]
#### To report a bug...

* What command(s) did you run?
$ task
* What did you expect to happen?
List my tasks
* What actually happened?
Every other task was redacted - it was blacked out
* Paste the output of the ```task diag``` command.
task 2.5.1
   Platform: Darwin

Compiler
    Version: 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Oct 16 2019 19:08:34
      CMake: 3.15.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.10
 Build type: Release

Is blacking out/redacting every other task on the list default behavior?

**Comment by Trial-In-Error** [comment]
This might be a terminal background color issue. Can you include a screenshot of running `task colors`? For reference, here's my `task colors` result running taskwarrior in WSL through conemu on windows with a solarized-dark color scheme:
![image](https://user-images.githubusercontent.com/759892/89698435-0e230b00-d8d6-11ea-8269-4e4aa03af3c3.png)

**Comment by MadHatter122312** [comment]
@Trial-In-Error 
I ran the `$task` and `$task color `commands and got the following: 

![Screen Shot 2020-08-10 at 2 38 11 PM](https://user-images.githubusercontent.com/15638558/89818111-3ea5b780-db17-11ea-983e-b5a6bc93c5ba.png)

I did not set any custom colors for my terminal.

**Comment by Trial-In-Error** [comment]
Hm. [This page might have some answers for you](https://taskwarrior.org/docs/themes.html). I expect you're using the default dark-256 color scheme; given that your terminal background is white, you might have better luck with light-256 or solarized-light-256.

Additionally, my monitor is currently set to way too high of a contrast, and I noticed that your blacked out lines do have different text and background colors (they're just _**really**_ similar).

**Comment by pbeckingham** [comment]
You are using a 256 color theme in a 15 color terminal. Choose another theme.
