### ISSUE TITLE
[TW-183] autocalculated uda

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#232]
_Zed Jorarard on 2013-04-12T23:33:58Z says:_ 

 as stated in #1225 i wanted to have a task rating measurement of = importance / estimated time. so with that feature done we have the math functions to do that. but how do we generate 

there are 2 possibilites to achieve that imho:

1. advanced urgency as proposed by david #1076
2. extension to udas, so they can be autogenerated by hooks or similar. my idea would be to be able to specify in the config like:
  uda.utilcoef.value=importance / estimate
  

i dont know much about the codebase so i cant say where a hook for this would be appropriate

if 1 is preferred, this bug can be closed i think

sorry if this is a bit redundant to #1225

atm i have a small script do to that externally, attached

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-04-12T23:33:58Z
Modified: 2015-03-14T16:49:08Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-09-29T18:21:40Z says:_ 

 This sounds like an ideal application for a hook script.  Setting to 2.4.0, which is where hooks might make their long awaited entrance.

Thanks.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-02-01T13:42:30Z says:_ 

 Hooks are not scheduled for 2.4.0.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-03-14T16:49:08Z says:_ 

 Closing this. In the interest of keeping the Taskwarrior core lean, there are improvements that can and should be achieved using hook scripts. This is one.

**Comment by pbeckingham** [comment]
[TW-183_task_coef.py.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755560/TW-183_task_coef.py.txt)
