### ISSUE TITLE
Automatically remove wait date when completing a task

### ISSUE THREAD

**Issue by xerus2000** [GothenburgBitFactory/taskwarrior#2322]
Sometimes, I complete a task right off my someday-list. In that case, the wait date should be automatically deleted - keeping it doesn't make much sense.

**Comment by skbolton** [comment]
This is a good use case for a hook if this is the behavior you want.

**Comment by tbabej** [comment]
I think @xerus2000 is right about this one. At first I was considering we might want to keep it for historical purposes, but the information would be preserved by the change history.

**Comment by tbabej** [comment]
Reproduced on 2.6.0.

**Comment by mrossinek** [comment]
I opened #2371 to implement this :+1:

**Comment by tbabej** [comment]
Implemented by @mrossinek.
