### ISSUE TITLE
How to filter by date range

### ISSUE THREAD

**Issue by xerus2000** [GothenburgBitFactory/taskwarrior#2323]
I would like to see all tasks that are due or scheduled within the next week, or overdue. I don't know how to filter for a date range, the documentation basically only mentions how to filter for a specific date.

**Comment by xerus2000** [comment]
Ah, this seems to work:

   task "due<2020-09-20"

Though now I need to embed the `date` shell command since `due<week` and similar don't seem to work.

**Comment by duckunix** [comment]
Hello!
you can try `task next +DUE +WEEK or +OVERDUE` to get what you are looking for.

Also, I have found the crowd over at https://www.reddit.com/r/taskwarrior/ to be very helpful for things like this.  The issue tracker is more for defects in the code or new feature requests.  The subreddit will answer things like your question, or other tips & tricks.

Hope this helps

**Comment by xerus2000** [comment]
Thanks! This does what I am looking for:

    task +DUE or +SCHEDULED
