### ISSUE TITLE
A way to Pin Projects even when no task are attach?

### ISSUE THREAD

**Issue by annata83** [GothenburgBitFactory/taskwarrior#2327]
#### Feature request.

A way to Pin projects meaning a way to create or define a project even if no task is attach to it.
  * Having to remember how I name my projects after finishing the last task attach to one is in my opinion something that can be     improve by adding pin projects.

**Comment by maln0ir** [comment]
Project in taskwarrior is just a label, so you can't have project without any tasks. However, you can list _all_ projects you ever defined by setting `list.all.projects` and/or `summary.all.projects` option to `yes`. First setting causes `task projects` report to list all projects, second do the same to `task summary` report.

**Comment by annata83** [comment]
Interesting. Thanks
