### ISSUE TITLE
[Feature request] Project tag

### ISSUE THREAD

**Issue by davidoskky** [GothenburgBitFactory/taskwarrior#2328]
Good morning,
I would like to have the possibility to assign a tag to one project, in this way all tasks assigned to such project would also be assigned to the tag of the project.
The only need for this is to simplify the input I have to insert every time: assigning a tag to a project I will not have to type every time the associated tag.
This is useful to me as I have various project who are always part of the same tag: all the tasks who are part of such a project are always associated to the same tag.
For example I might create various projects for various different jobs I am doing, since all of these projects concern my work they would always be part of the tag WORK. Therefore I want all the tasks I add to these project to be tagged for WORK.
I could then have an housecleaning project who would always be associated with the tag HOUSE.
Assigning the tag to the project once would save me the time to specify the tag each and every time I add a new task.
`task add new task project:newjob`
Instead of
`task add new task project:newjob +WORK`

This is not a feature that would modify anything significant in the use of taskwarrior, it would just make things easier for me as I often forget to add the tags. Moreover it's frustrating to keep adding the same tag over and over knowing that it could easily be set beforehand.

**Comment by tbabej** [comment]
Hi @davidoskky , have you looked into the [hooks documentation](https://taskwarrior.org/docs/hooks.html)? This would be relatively easy to achieve i.e. using the [taskpirate hook framework](https://github.com/tbabej/taskpirate).
