### ISSUE TITLE
Default dark color theme hard to read for specific task

### ISSUE THREAD

**Issue by jlquinn** [GothenburgBitFactory/taskwarrior#2329]
#### To report a bug...

I have a task that shows up in the default view with almost unreadable colors.  The colors used are yellow on white.

This is Ubuntu 18.04, default dark theme in the gnome terminal.
If I explicitly enable dark-256 theme I get the same output, so that is likely what is being used.

From what I've read about taskwarrior color themes, this appears to be an unfortunate layering of color rules in the default theme.

I've attached an image to show what it looks like.
![Screenshot from 2020-09-25 13-34-42](https://user-images.githubusercontent.com/826841/94299227-5bfedb80-ff35-11ea-8fce-312faca8d4b5.png)

This is the task that is poorly colorized:

jlquinn@smaug:~$ task 141
No command specified - assuming 'information'.

Name                  Value                                                
ID                    141
Description           create test case for re2 searchdfa error             
Status                Pending
This task is blocking 140 depends                                          
Entered               2020-09-24 12:14:41 (1d)
Last modified         2020-09-25 13:19:38 (13min)                          
Tags                  engine next
Virtual tags          BLOCKING PENDING READY TAGGED UDA UNBLOCKED PRIORITY 
UUID                  11db33d8-1607-4938-9739-1ffdb7ede1d2
Urgency               25.71                                                
Priority              L

    blocking            1 *    8 =      8
    tags              0.9 *    1 =    0.9
    age             0.003 *    2 =  0.005
    UDA priority.L      1 *  1.8 =    1.8
    TAG next            1 *   15 =     15
                                   ------
                                    25.71

Date                Modification        
2020-09-25 13:19:38 Priority set to 'L'.

* Paste the output of the ```task diag``` command.
jlquinn@smaug:~$ task diag

task 2.5.1
   Platform: Linux

Compiler
    Version: 7.2.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.9.5
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.8
 Build type: None

Configuration
       File: /space/jlquinn/.taskrc (found), 2297 bytes, mode 100644
       Data: /space/jlquinn/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: emacs
     Server: smaug.watson.ibm.com:55555
         CA: /space/jlquinn/.task/ca.cert.pem, readable, 3751 bytes
      Trust: strict
Certificate: /space/jlquinn/.task/jlquinn.cert.pem, readable, 3741 bytes
        Key: /space/jlquinn/.task/jlquinn.key.pem, readable, 24742 bytes
    Ciphers: NORMAL
      Creds: IKM/jlquinn/************************************

Hooks
     System: Enabled
   Location: /space/jlquinn/.task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (302x74)
       Dups: Scanned 368 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 368 tasks for broken references:
             No broken references found

#### To request a feature...

* Clearly describe the feature.
* Clearly state the use case. We are only interested in use cases, do not waste time with implementation details or suggested syntax.
* Please see our notes on [How to request a feature](https://taskwarrior.org/docs/features.html)

**Comment by pbeckingham** [comment]
Taskwarrior themes are switchable and overrideable. Terminal themes can be changed. One does not know about the other. What would you propose that works in all cases?

**Comment by tbabej** [comment]
@jlquinn Paul is correct here, basically there is no way for taskwarrior to auto-configure this. Taskwarrior ships with [multiple color schemes](https://taskwarrior.org/docs/themes.html), I'd recommend cycling them and sticking with the one that works best for your terminal color scheme :) or create your own one!
