### ISSUE TITLE
[TW-184] Inverted countdown

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#233]
_Frédéric Mangano on 2013-06-08T09:56:21Z says:_ 

 I suggest introducing a <i>due.left</i> which displays the remaining time.

The patch provides the feature but wouldn’t work for localized builds, and isn’t documented. Tell me if you want me to do that.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-06-08T09:56:21Z
Modified: 2014-04-13T14:57:02Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2013-06-08T21:26:49Z says:_ 

 +1

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-06-08T21:53:06Z says:_ 

 Yes, this is nice.  It should be named "remaining" instead of "left", which is ambiguous particularly when it applies to a format.  Unit tests and documentation updates are missing from the patch.

**Comment by taskwarrior** [comment]
_Frédéric Mangano on 2013-06-09T10:14:12Z says:_ 

 Here you go.

As for tests, I’m a bit confused. All the countdown.t test seems to do is make sure sorting according to the due date works. Also, the up/upc reports are exactly the same.

**Comment by taskwarrior** [comment]
_Frédéric Mangano on 2013-06-09T10:16:49Z says:_ 

 Here are the squashed commits for convenience. Merging this patch is equivalent to merging the three above.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-04-13T14:57:02Z says:_ 

 The "remaining" format has been implemented via these (and other) patches for a while now.

**Comment by pbeckingham** [comment]
[TW-184_0009-left-inverted-countdown-style-for-dates.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755561/TW-184_0009-left-inverted-countdown-style-for-dates.patch.txt)
[TW-184_0033-due.remaining-instead-of-due.left.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755562/TW-184_0033-due.remaining-instead-of-due.left.patch.txt)
[TW-184_0034-due.remaining-bit-of-doc.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755563/TW-184_0034-due.remaining-bit-of-doc.patch.txt)
[TW-184_0035-due.remaining-column.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755564/TW-184_0035-due.remaining-column.patch.txt)
