### ISSUE TITLE
Task numbers change after completion of another task

### ISSUE THREAD

**Issue by mgiugliano** [GothenburgBitFactory/taskwarrior#2335]
I would like to report a systematic bug, which prevents me from quickly "completing" tasks without every time getting their task number. 

* I ran "task 40 done"
* I expected task n. 40 to disappear from the list and all other tasks to retain their own original number.
* Other two tasks changed their numbers from 116 to 115 and from 117 to 116, in an completely unrelated manner.
* Below I paste the output of the ```task diag``` command.

task 2.5.1
   Platform: Darwin

Compiler
    Version: 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Oct 16 2019 19:08:34
      CMake: 3.15.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.10
 Build type: Release

Configuration
       File: /Users/####/.taskrc (found), 3945 bytes, mode 100644
       Data: /Users/####/Dropbox/task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: /usr/local/bin/vim
     Server: taskwarrior.inthe.am:53589
         CA: ~/.dotfiles/task/ca.cert.pem, readable, 2405 bytes
      Trust: ignore hostname
Certificate: ~/.dotfiles/task/private.certificate.pem, readable, 2650 bytes
        Key: ~/.dotfiles/task/private.key.pem, readable, 20127 bytes
    Ciphers: NORMAL
      Creds: inthe_am/####/************************************

Hooks
     System: Enabled
   Location: /Users/####/Dropbox/task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (240x60)
       Dups: Scanned 275 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 275 tasks for broken references:
             No broken references found

**Comment by kwoot** [comment]
Hi Michele,
I am NOT one of the developers of taskwarrior but just a regular user.
The way I see it, if a task get's done then the list of "current" tasks get reassigned.
All tasks have also a unique and permanent ID, see "task info" to see it.
I hope this helps you.
Regards,
Jeroen

**Comment by mgiugliano** [comment]
Thank you, @kwoot . If this is the intended behaviour, a similar reassignment is inconvenient and annoying and prevents quick completion of several tasks at once.

**Comment by duckunix** [comment]
@mgiugliano I think you might want to go read https://taskwarrior.org/docs/ids.html .  Basically, if you mark a task done or deleted, and you do not run a report, you can keep the numbers from before.  However, if you run a report, then the garbage collector run and the tasks are renumbered.  

The docs has a way to override that.

**Comment by kdheepak** [comment]
For what it is worth, this is one of the primary reasons I built a terminal user interface for taskwarrior: https://github.com/kdheepak/taskwarrior-tui. I wanted to perform a sequence of multiple actions without running `task {report}` between each step.

**Comment by mgiugliano** [comment]
@duckunix
Thank you. However I first became aware of this issue precisely as I was not invoking "task" to get a report printed on screen. And yet I inadvertently flagged other tasks as competed.

**Comment by dixius99** [comment]
> For what it is worth, this is one of the primary reasons I built a terminal user interface for taskwarrior: https://github.com/kdheepak/taskwarrior-tui. I wanted to perform a sequence of multiple actions without running `task {report}` between each step.

That TUI makes me want to get back into using Taskwarrior more regularly. (currently using Org Mode because I like it a little better in relation to how recurring tasks work)

**Comment by kdheepak** [comment]
I am always envious of org mode and it's features!

**Comment by gour** [comment]
> I am always envious of org mode and its features!

Ex-tw user here - just try [etm-dgraham](https://github.com/dagraham/etm-dgraham) - all org-mode recurring stuff is there. ;)

**Comment by tbabej** [comment]
The IDs are indeed not meant to be persistent, as they represent just the row number in the `pending.data` file. For persistent references to a given task, check out UUIDs. More info can be found [on this page in the docs](https://taskwarrior.org/docs/ids.html).

**Comment by jaker-dotcom** [comment]
Currently I run entr -c task next on a terminal so that I can interact on the one side and it reloads all the IDs on the other window.
