### ISSUE TITLE
We need someone to manage the issues list

### ISSUE THREAD

**Issue by pbeckingham** [GothenburgBitFactory/taskwarrior#2342]
We are in need of someone to curate the Taskwarrior issues list. We are looking for someone to take on sole authority to organize, trim, dump, ditch, expound, improve, rewrite and tag the entire issues list.

It has grown too large, we would like someone to take ownership of the list, make it good, and keep us honest.

Any volunteers?

**Comment by kwoot** [comment]
I offer to do this. If you will forgive me when I screw up :-).
I have done this before. 383 open issues is a lot less than the 1283 of the last time I did this :-)

**Comment by corbolais** [comment]
> I offer to do this. If you will forgive me when I screw up :-).
> I have done this before. 383 open issues is a lot less than the 1283 of the last time I did this :-)

Thank you.

Maybe there's more work involved handling 400 issues than 1300 others? The numbers can hide complexity.

**Comment by kwoot** [comment]
Time will tell....

**Comment by corbolais** [comment]
There's no such issue as to handle PRs. I offer to help out inspecting PRs, merge and generally handle input on that part of the project.

**Comment by kwoot** [comment]
$ task add Project:TW Manage GitHub Issues
Created task 54.
:-)

**Comment by pbeckingham** [comment]
@corbolais - there will be other roles identified, I'll get back to you.

@kwoot, the job is yours. Do you already have sufficient privileges to do the following?

Here's what we need:
- make the tag list make sense
- apply all appropriate tags to all issues
- close out duplicates, or those that cannot be reproduced
- close out issues that are just questions in disguise, preferably with answers, but not necessarily
- consolidate similar issues
- get clarification from reporter if necessary, and reproduce if possible. We might need a 'reproduced' tag
- otherwise, I defer to you to keep the issues list current, relevant and correct, however you wish.

To your question: mistakes are expected and okay, just look at how many PRs I've merged to master by mistake, plus the fact that I put most of the bugs into the code. Or just look at Tomas.

**Comment by tbabej** [comment]
> mistakes are expected and okay, just look at.... Or just look at Tomas.

:cry: 
![image](https://user-images.githubusercontent.com/2123868/99883893-2e15da80-2bf8-11eb-824c-8f388b321f00.png)

On a more serious note @kwoot , this is not an easy role and some of the decision making does require significant insight into the project. I'm willing to help in my available capacity with setting up the correct framework.

**Comment by kwoot** [comment]
@pbeckingham , I have not checked yet if I have the necessary privileges. Will let you know if I stumble upon something.

@tbabej. I once was head of a software development department.  I do not intend to become a raging mad man here now. :smile:  

Is this the main discussion channel also? Or is there a slack? Or a mattermosrt? or a discord? or a matrix/riot? or a whatever?

**Comment by tbabej** [comment]
Main discussion channel is currently on IRC, #taskwarrior on Freenode. I'm also currently looking into setting up a mailing list.

**Comment by scottkosty** [comment]
@kwoot thank you for accepting this responsibility! I don't have much time these days, but I'd be happy to be a sounding board if you want to discuss any ideas on the best way to organize things. I don't have much experience with different workflows for handling issues for projects of this complexity, but I'm happy to try to give thoughts (just `@` me). If I do ever have time in the future, I'd be happy to accept some issue-organizing tasks you wish to delegate.

**Comment by kwoot** [comment]
Update; Despite all my best intentions to be quick about this, life seems to get in the way. If nobody else steps up I will keep this in my task list (which means that eventually it will have the highest urgency :smiley: ). It's currently the best I can do.
