### ISSUE TITLE
CI matrix needs to be updated to support newer distro releases

### ISSUE THREAD

**Issue by tbabej** [GothenburgBitFactory/taskwarrior#2344]
Our Travis-based CI is relatively exhaustive, but contains outdated versions of popular distros (i.e. Fedora 28, 29, CentOS 7, Ubuntu 18.04 or Arch 2018). All of these have newer releases and some of the currently tested releases are no longer supported.

We should update the test matrix and the associated Dockerfiles to be based on a set of current distro releases.

**Comment by kwoot** [comment]
How can I help?

**Comment by 8-bit-fox** [comment]
They reside in [`test/docker`](https://github.com/GothenburgBitFactory/taskwarrior/tree/2.5.2/test/docker)

**Comment by tbabej** [comment]
@kwoot For most of the Dockerfiles, I think this comes down to:
1. updating the base image to more recent tag (i.e. from `fedora:29` to `fedora:33`) and
2. checking if the build still works (dependency package names could have changed, etc.)

As for what distros to test, I think we should keep testing the ones that are still supported, so that would mean:
* Replacing F28 and F29 with F32 and F33 (where F=Fedora)
* Keeping Centos 7, but adding Centos 8
* Updating Arch to a newer tag (maybe just a generic one like @8-bit-fox suggests)
* Replacing Ubuntu 16.04 with Ubuntu 20.04, keeping Ubuntu 18.04
... and similar for the other distros (according to their versions and support schedules)

**Comment by 8-bit-fox** [comment]
@tbabej, as I have pointed out in #2339 I think the Docker images themselves would need some refactoring as well. Currently, they contain state (the actual project-state), which requires to build the whole OS over and over again. Instead the project should be mounted as volume, which would remove the need for rebuilding the image. Except for important changes in the underlying OS, of course.

IMO, OS changes should also be tested against, but in a separate pipeline. This allows to distinguish between issues introduced by changes on the project and changes introduced by the underlying system.

For sure this can be done in multiple steps (1. Fixing current pipeline, 2. Improving CI).

**Comment by sruffell** [comment]
> @tbabej, as I have pointed out in #2339 I think the Docker images themselves would need some refactoring as well. Currently, they contain state (the actual project-state), which requires to build the whole OS over and over again. Instead the project should be mounted as volume, which would remove the need for rebuilding the image. Except for important changes in the underlying OS, of course.

I'll second this point. I too believe the Docker images should be refactored so that they do not need to be rebuilt in order to to run the tests against the source in the current directory.

**Comment by 8-bit-fox** [comment]
As stated in #2339 I tried a bit this and that. The result I just put for reference here in a Draft PR.

**Comment by tbabej** [comment]
Support for F31-F33, CentOS, Ubuntu 20.04 and rolling version of Arch has been added in the 2.6.0 branch.
