### ISSUE TITLE
taskwarrior inconsistencies

### ISSUE THREAD

**Issue by corbolais** [GothenburgBitFactory/taskwarrior#2356]
Hi,

Over time, there have been many inconsistencies (sometimes plain bugs) creeping up and keeping track of them was something I didn't do so far, too far apart they happen, no time etc.. are some of the reasons.

I'd like to have this issue giving them home. A place to meet and find them easily. One could also use a GH tag but that's nothing a mere reporter may do.

One example of a (big bunch) of inconsistencies is commandline parsing in any flavor, be it task add, task project or whatever. You need to develop a strategy to circumnavigate these issue. There are already a couple of issues addressing this. One only needed to find and add them here.

cheers

**Comment by tbabej** [comment]
Hey @corbolais , thanks for opening up this issue. I believe this is what one could call an "umbrella" or a meta-issue. Currently I'm a bit torn as to how to track those and whether to use issues themselves for tracking issues (though I've done that in #2353).

Currently I'm thinking of leveraging the "Projects" tab in Github to do some topic-based categorization of the issues.

**Comment by corbolais** [comment]
@tbabej Projects might be a start. It somehow feels not too appropriate, though. Time will tell.

I like having a single place where I can easily find all related issues. And if you search for a specific behavioural anomaly you could easily miss some with keywords mismatching.

So whether or not Projects reveal themselves as a feasible way to tackle that kind of issue I as a reporter would be happy to find a meta-issue in that regard.

It's maybe just because it's in a single place instead of having to look it up in Issues **and** in Projects. Most people would expect to find that kind of information in the Issues category, I guess.

Linking to a Project from a meta-issue is perfectly fine, though, IMO.

**Comment by corbolais** [comment]
#1908

**Comment by tbabej** [comment]
Closing umbrella issues to help declutte the issue list. Inconsistencies could really be just another word for bug. Parsing-related issues can be found in the "Parsing issues" project. I will open other projects as need arises.

**Comment by corbolais** [comment]
Closing this issue is dumb and counterproductive. There's no reason to close this one to reduce the issue count.

**Comment by jschlatow** [comment]
@tbabej Great idea to use the projects feature of github as an umbrella for managing multiple related issues.  I was wondering, though, why the project does not mention the issues referenced by @corbolais.

@corbolais I'm sorry, but I don't think that the tone of your last comment is very productive either. There is imo a valid point of @tbabej to convert this issue into a project. If you think maintaining an umbrella issue has benefits over this, I'd kindly ask you to state your arguments instead of just calling it 'dumb'.

**Comment by tbabej** [comment]
Hi Corbo, I'm sorry you feel that way. I'm in a process of clearing up the issue list and, as I mentioned up in the thread couple of days, had to make a call in what form to support issue grouping. Umbrella tickets are one way, grouping using labels another, and yet another is using projects.

Right now we decided to use projects for that purpose. I closed #2353, which is an umbrella ticket that I opened myself, as well, so nothing really against this particular issue.

**Comment by tbabej** [comment]
@jschlatow Happy to put some of the ones into appropriate projects, not all of the issues mentioned here belong to a unified theme though. There are issues related to recurrence, undo, and parsing, and both issues that appear to be open and closed (and presumably fixed). Issue list needs a bit more work before we can confidently sort them out and assess how (or if) to categorize them, and I see that happening somewhat organically over the course of the next couple of weeks.

**Comment by corbolais** [comment]
Stop whining. Not taken.

What is happening here is hampering other contributors actual efforts on active issues. Very sensitive and far-sighted.

Reasons already given, see first post.

Do as you wish, this is clearly no project I want to continue to contribute. There are many other projects showing much more tactfulness and abiltiy of integration towards potential contributors. Over the years, the PO has proven his inability to find the right tone, some others here seem to fall in league. Years long de-facto inactivity then a flurry of action with questionable results. SW dev is all about the human being, before it is about coding. The TW project just doesn't seem to get it right, communication- and handling-wise.

Closing organizational issues that are actively worked on to reduce the issue count is just plain **dumb**, as already mentioned. This _tone_ is reflecting frustration over what I wrote in the paragraph above and a result thereof. May you make the best of it.
