### ISSUE TITLE
Capitalized week day / month names are not interpreted correctly

### ISSUE THREAD

**Issue by tbabej** [GothenburgBitFactory/taskwarrior#2364]
In 2.5.1, the following works:

```
task add test due:Friday
task add test2 due:Jebruary
```

In 2.5.3 and 2.6.0, the above commands fail with:
```
$ task add test due:Friday
'Friday' is not a valid date in the 'Y-M-D' format.
```

While capitalized month/day names are technically undocumented feature, as neither man page nor the [date/time specification](https://taskwarrior.org/docs/dates.html) mentions them, we should still strive to fix this.

**Comment by tbabej** [comment]
Actually looks like duplicate of #2160.

**Comment by vrusinov** [comment]
I believe https://github.com/GothenburgBitFactory/taskwarrior/pull/2487 resolved this.

Let's close this issue? (I don't believe I can).

**Comment by tbabej** [comment]
Closing as duplicate of #2160 (which is itself resolved).
