### ISSUE TITLE
Support for combining time with relative wording

### ISSUE THREAD

**Issue by guludo** [GothenburgBitFactory/taskwarrior#2366]
Hi there. I really like the fact that we can use "relative wording" for setting dates. I think one thing that is missing is the ability to combine time with it. For example, I would like to be able to create a task that is due tomorrow at 5pm. For that, I would like to be able to issue a command like `task add due:"tomorrow 17:00" Description of my task`.

I apologize if this is a feature that is already supported. I could not find a way to do that though.

**Comment by tbabej** [comment]
Hi @guludo, you can achieve that using the following syntax:
```
$ task add due:tomorrow+17h Description of my task
```

I'd recommend reading the "Dates" section on the following page to get more idea about the syntax: https://taskwarrior.org/docs/commands/calc.html

**Comment by guludo** [comment]
Hi @tbabej!

Oh, nice! Thank you :slightly_smiling_face: 

... and sorry about the noise.

I think it would be nice to have a link to https://taskwarrior.org/docs/commands/calc.html#dates in https://taskwarrior.org/docs/dates.html . The latter was the one I looked at when search for this feature.

I'm closing this now.
