### ISSUE TITLE
Include test suite in release

### ISSUE THREAD

**Issue by janko-j1** [GothenburgBitFactory/taskwarrior#2368]
Can you include the test suite in the release tarball? That would help with maintaining the package on Gentoo Linux and report bugs.

**Comment by pbeckingham** [comment]
No, the release tarball is intended for users. The test suite is intended for developers, which requires the full copy.

**Comment by tbabej** [comment]
@janko-j1 If you go to the release page, there are three assets, the release tarball (which as Paul says is stripped-down version of the repo), but there is also a snapshot of the repo at the time of release (see source code):

![image](https://user-images.githubusercontent.com/2123868/101825691-f796f580-3afb-11eb-8134-272408d0aebc.png)

i.e. the bottom link leads to a tarball: https://github.com/GothenburgBitFactory/taskwarrior/archive/v2.5.2.tar.gz

I believe that fixes your problem :)

**Comment by heirecka** [comment]
> No, the release tarball is intended for users. The test suite is intended for developers, which requires the full copy.

Most distros usually want to run tests suites themselves.

> If you go to the release page, there are three assets, the release tarball (which as Paul says is stripped-down version of the repo), but there is also a snapshot of the repo at the time of release (see source code):

That includes the tests, but not the libshared submodule, so you have still a part which needs to put into place manually.

**Comment by janko-j1** [comment]
> That includes the tests, but not the libshared submodule, so you have still a part which needs to put into place manually.

Yes, that is the starting point of my request, as the libshared module is not to be packaged independently.

**Comment by tbabej** [comment]
@heirecka @janko-j1 I just released 2.5.3 with a separate tarball containing the test suite. Hope that format helps!

**Comment by heirecka** [comment]
Yes, it does, thanks.
