### ISSUE TITLE
2.5.2 tarball contains multiple task-2.5.2.tar.gz archives recursively

### ISSUE THREAD

**Issue by heirecka** [GothenburgBitFactory/taskwarrior#2369]
The tarball from https://github.com/GothenburgBitFactory/taskwarrior/releases/download/v2.5.2/task-2.5.2.tar.gz
contains a task-2.5.2.tar.gz archive, which contains a task-2.5.2.tar.gz archive, which ... seems to go on for 7 levels

Admittedly not a big problem, but a bit odd and needlessly blows up the tarball size.

**Comment by tbabej** [comment]
You're exactly right, the nested tarballs were a mistakenly included during the release process. Thanks for reporting!

**Comment by tbabej** [comment]
I also updated the release assets, the tarball size decreased form 7MB to 0.7MB.

**Comment by heirecka** [comment]
Thanks!
