### ISSUE TITLE
Task warrior cannot read certificate on wsl

### ISSUE THREAD

**Issue by Xorpio** [GothenburgBitFactory/taskwarrior#2370]
I'm trying to setup task warrior to sync with taskserver. it cannot find the certificates.

This is the output of `task diag`:
```
task 2.5.1
   Platform: Linux

Compiler
    Version: 9.2.1 20200306
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.16.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.11
 Build type: None

Configuration
       File: /home/xorpio/.taskrc (found), 324 bytes, mode 100777
       Data: /home/xorpio/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: taskwarrior.inthe.am:53589
, not readable, 0 bytesio/.ssh/taskwarrior/ca.cert.pem
      Trust: Bad value - see 'man taskrc'
, not readable, 0 bytesio/.ssh/taskwarrior/private.certificate.pem
, not readable, 0 bytesio/.ssh/taskwarrior/private.key.pem
    Ciphers: NORMAL
      Creds: inthe_am/xorpio/*************************************

Hooks
     System: Enabled
   Location: /home/xorpio/.task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (321x124)
       Dups: Scanned 0 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 0 tasks for broken references:
             No broken references found
```

My .taskrc contains:
```
taskd.certificate=/home/xorpio/.ssh/taskwarrior/private.certificate.pem
taskd.key=/home/xorpio/.ssh/taskwarrior/private.key.pem
taskd.ca=/home/xorpio/.ssh/taskwarrior/ca.cert.pem
```
I have already tried to validate my certificates with the following command:
`certtool -i --infile /home/xorpio/.ssh/taskwarrior/ca.cert.pem`

Certtool seems to validat without troubles.

**Comment by mrossinek** [comment]
The line `, not readable, 0 bytesio/.ssh/taskwarrior/ca.cert.pem` seems to suggest that you have some incorrect file permissions. I remember also having a problem with that in the past. Maybe you could try ensuring the owner, group and permissions are correct In particular, the permissions must only provide `rw` access to the owner and no permissions to the group and others.

**Comment by Xorpio** [comment]
Changing the permissions seems to have no effect: The permissions where 
```
-rwxrwxrwx 1 xorpio xorpio 1285 Jul 18 11:33 ca.cert.pem
-rwxrwxrwx 1 xorpio xorpio 1448 Jul 18 11:33 private.certificate.pem
-rwxrwxrwx 1 xorpio xorpio 8282 Jul 18 11:33 private.key.pem
```
Changed them to:
```
-rwx------ 1 xorpio xorpio 1285 Jan  5 08:00 ca.cert.pem
-rwx------ 1 xorpio xorpio 1448 Jan  5 08:00 private.certificate.pem
-rwx------ 1 xorpio xorpio 8282 Jan  5 08:00 private.key.pem
```

End result is still the same.

**Comment by mrossinek** [comment]
Try changing them to the following:
```
-rw------- 1 xorpio xorpio 1285 Jan  5 08:00 ca.cert.pem
-rw------- 1 xorpio xorpio 1448 Jan  5 08:00 private.certificate.pem
-r-------- 1 xorpio xorpio 8282 Jan  5 08:00 private.key.pem
```
The key being read-only could be the important aspect here. And there is no reason for any of these files to be executable.

**Comment by bepolymathe** [comment]
Did you a find a solution ?

**Comment by Xorpio** [comment]
sadly no. Problem still happens. Sadly don't have the time to investigated further at this moment.

**Comment by bepolymathe** [comment]
Ok. Thanks for reply.

**Comment by tbabej** [comment]
@bepolymathe Do you have this issue too?

**Comment by skannamalai** [comment]
I also have this issue, despite my files being set to chmod 666, aka -rw-rw-rw-.  Ubuntu 20.04 within WSL2. Happy to give notes as requested.

**Comment by djmitche** [comment]
Closed because taskserver/taskd is no longer supported.
