### ISSUE TITLE
Get tags and projects for all tasks, not only next ones

### ISSUE THREAD

**Issue by mdouchin** [GothenburgBitFactory/taskwarrior#2372]
I would like to list all the present and past projects and tags, in order to use them in some bash script I created to export task/timew data into PostgreSQL and run some aggregate queries. See: https://gist.github.com/mdouchin/44c92b0c1061131c3bfb5d28c1e9204d

I use the tags and projects commands `task projects` and `task tags` which list only the current active projects and tags. Do you think a new options to these commands could allow to get them all, even for "done" tasks" ?

NB: here is the kind of view printed by the bash script

* Grouped spent time of today

|      project       |   tag   |        task         | duration |
|--------------------|---------|---------------------|----------|
| someclient | dev     | Gestion des erreurs | 02:40:44|
| other_client               | dev     | Revue de code       | 02:07:51|
| other_client               | reunion | Réunion             | 01:43:43|
| project_x               | email   | Email & web         | 00:33:18|

* Grouped spent time of week by tag

|   tag   | duration |
|---------|----------|
| dev     | 04:48:35|
| reunion | 01:43:43|
| email   | 00:33:18|

**Comment by mrossinek** [comment]
Have a look at the `HELPER SUBCOMMANDS` listed in the man page.
I think you may be looking for things like `_projects` or `_tags`.

**Comment by mdouchin** [comment]
Thanks ! it helps !

**Comment by mrossinek** [comment]
Please close this issue if it resolved now. I don't have the rights to do so myself.
