### ISSUE TITLE
Year 2038 Problem

### ISSUE THREAD

**Issue by tasksoldier** [GothenburgBitFactory/taskwarrior#2373]
Hello,

I tried to add a task with a due date after 2038:

_task add "Retirement" due:2048-06-01
'-1820392096' is not a valid date in the '' format._

I expected that a new task is added (at least on the 64 Bit system I am using).

Is there already (I know some time is left) a strategy for the taskwarrior how to cope with the year 2038 problem?

Thank you in advance

**Comment by kwoot** [comment]
Funny. And, also, you must be extremely busy, to already have work to do 18.5 years from now. :smile:

**Comment by tbabej** [comment]
@tasksoldier Thanks for bringing this issue up! We are aware of this problem with TW somehow using 32-bit timestamp values. The mechanism is currently unclear but the problem is tracked in #2017. I'd recommend watching that issue if you're interested in support of 64-bit timestamp values.

**Comment by tasksoldier** [comment]
I debugged the source code and I developed a patch that resolves my problem at least on my 64 Bit system. The regression test passes with my patch. How should I proceed? (I am a new to github)

**Comment by tbabej** [comment]
You could either fork the repository to make a pull request, i.e. (see [the following guide](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/)) or alternatively format your patch using `git format-patch` and post the patch here.

**Comment by tbabej** [comment]
@tasksoldier See the instructions above. Let us know if we can help!

**Comment by tasksoldier** [comment]
Thank you very much for your kind support. I attached two patches. One for libshared. The other for taskwarrior itself. Both are required to resolve the problem. If you think the patches need improvement, then please let me know.


[0001-Bug-Patch-for-libshared-to-resolve-issue-2373.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/5705108/0001-Bug-Patch-for-libshared-to-resolve-issue-2373.patch.txt)
[0001-Bug-Patch-for-taskwarrior-to-resolve-issue-2373.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/5705109/0001-Bug-Patch-for-taskwarrior-to-resolve-issue-2373.patch.txt)

**Comment by tasksoldier** [comment]
@tbabej I did both. I made two pull requests. And as a fallback I posted the patches here.

**Comment by tbabej** [comment]
Thank you @tasksoldier, I incorporated your changes in 2.6.0.
