### ISSUE TITLE
task 2.5.2 hangs then dies when certain tasks are present in a report

### ISSUE THREAD

**Issue by thehunmonkgroup** [GothenburgBitFactory/taskwarrior#2375]
I had previously been using the packaged Taskwarrior 2.5.1 that came with Ubuntu 20.04 LTS, but recently compiled 2.5.2 from source and now am facing this bug.

* What command(s) did you run? ```task next```
* What did you expect to happen? Pending tasks would be listed
* What actually happened? Taskwarrior hung for about 30 seconds, then exited with a ```Killed``` message
* Paste the output of the ```task diag``` command.
```
task diag

task 2.5.2
   Platform: Linux

Compiler
    Version: 9.3.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      Built: Dec 28 2020 21:41:09
     Commit: 2dd21de67
      CMake: 3.16.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.13
 Build type: release

Configuration
       File: /home/hunmonk/.taskrc (found), 1057 bytes, mode 100664
       Data: /home/hunmonk/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: vim
     Server: xylil.apartmentlines.com:53589
         CA: /home/hunmonk/.task/ca.cert.pem, readable, 3741 bytes
Certificate: /home/hunmonk/.task/hunmonk.cert.pem, readable, 3745 bytes
        Key: /home/hunmonk/.task/hunmonk.key.pem, readable, 24754 bytes
      Trust: strict
    Ciphers: NORMAL
      Creds: Public/hunmonk/************************************

Hooks
     System: Enabled
   Location: /home/hunmonk/.task/hooks
     Active: on-add-onenote-manage-notes-annotation.py    (executable) (symlink)
             on-exit-sync.sh                              (executable)
             on-modify-onenote-manage-notes-annotation.py (executable) (symlink)
   Inactive: 

Tests
   Terminal: 167x56
       Dups: Scanned 2428 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 2428 tasks for broken references:
             No broken references found

```
I also tried starting with a default ```.taskrc``` file, and removed all my hook scripts, but those didn't help, either.

The issue seems to be tied to data in particular tasks. For my ```task next``` report, I found the following task and marked it done, then ```task next``` started working again:

```json
[
  {
    "id": 0,
    "description": "talk w/ daniel for plan, recommendations",
    "due": "20210113T080000Z",
    "end": "20201229T081107Z",
    "entry": "20201227T024313Z",
    "modified": "20201229T081107Z",
    "notes": "# vi: ft=votl\n\nventilation while heat is on",
    "project": "art.mcg.camping.tent",
    "scheduled": "20210106T080000Z",
    "status": "completed",
    "tags": [
      "home",
      "easy"
    ],
    "uuid": "20ed4d90-d942-4eef-9967-065d687c71d3",
    "annotations": [
      {
        "entry": "20201229T063027Z",
        "description": "[Notes]"
      }
    ],
    "urgency": 3.41096
  }
]
```

However, setting that task's status back to pending so that it would appear in ```task next``` again caused ```task``` to hang again.

I played with deleting as many tasks as possible that were in my ```task next``` report, and got it down to the attached ```pending.data``` file, that has only three tasks in it. Using this ```pending.data``` file causes Taskwarrior to hang on my system. However, removing *any one* of those tasks from ```pending.data``` results in ```task next``` working properly again.

Happy to build a debug version and try troubleshooting some more, but I would need a little guidance on how to generate useful data in this case where the program is hanging.

[pending.data.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/5750051/pending.data.txt)

**Comment by djmitche** [comment]
This may be related to #2140, since I see newlines in the "notes" property.

**Comment by tbabej** [comment]
@thehunmonkgroup Interesting report! I successfully reproduced this locally using the same commit (current HEAD of `master`). It seems to be some sort of a runaway mechanism that accumulates memory, as that is the cause of eventual demise of the `task` process.

The bug is not present on 2.6.0, however. I'll bisect the issue down.

**Comment by tbabej** [comment]
@thehunmonkgroup I believe this issue is already fixed on 2.5.3 (see #2362), could you rebuild and confirm?

**Comment by thehunmonkgroup** [comment]
You are correct, the issue does not happen on 2.5.3

Should there be a 2.5.2.1 release, since this bug is pretty bad?

**Comment by tbabej** [comment]
The purpose of the 2.5.3 branch is exactly that, it's going to be bugfix-only release of critical issues :) aiming to be released maybe in a week or so, which should be roughly 1 month since the release.

**Comment by thehunmonkgroup** [comment]
Great! Guess we can close this one then.
