### ISSUE TITLE
What are TDB2 and TF2 classes in the source code?

### ISSUE THREAD

**Issue by sucrecacao** [GothenburgBitFactory/taskwarrior#2380]
`// TDB2 Class represents all the files in the task database.`
`// TF2 Class represents a single file in the task database.`
( TDB2.cpp )

Is TF2 basicaly just work on the `completed.data` and `pending.data` and TDB2 an abstraction for both of them ?

**Comment by tbabej** [comment]
Correct, the TDB2 is an abstraction over all the data files in the data folder (so not only completed.data / pending.data but also undo.data or backlog.data).
