### ISSUE TITLE
'task X edit' with VIM modeline in string UDA throws VIM error

### ISSUE THREAD

**Issue by thehunmonkgroup** [GothenburgBitFactory/taskwarrior#2384]
Posting this as a fix I've found, in case other people get bitten by it

I have a string UDA that contains a VIM modeline in it, and when running ```task X edit```, which opens the VIM editor for me, VIM is incorrectly interpreting the UDA string as a modeline and throwing an error as seen here:

![2021-01-05_18-20](https://user-images.githubusercontent.com/43772/103722094-14500d00-4f84-11eb-9788-0201e34b712c.png)

Given that Taskwarrior opens these files for editing with a ```.task``` extension, it was easy enough to add a simple configuration to my ```.vimrc``` to override the default modelines for the ```.task``` filetype, like so:

```vim
  if has("autocmd")
     autocmd BufNewFile,BufReadPost *.task set modelines=0
  endif
```
```modelines=0``` disables modelines, which makes sense in this case

**Comment by tbabej** [comment]
I thought this is a pretty niche use case, but I see - notes. I guess this is another silent vote for some sort of integrated `task <id> note` command :slightly_smiling_face: I'll think about whether this can be squeezed on the roadmap in the near future.

I assume (a) you have another command to pipe/edit this in a vim window and (b) synchronization is important for notes too.

**Comment by thehunmonkgroup** [comment]
> I assume (a) you have another command to pipe/edit this in a vim window and (b) synchronization is important for notes too.

I wrote a whole suite to elegantly handle embedding notes in a Taskwarrior UDA, and I'll be providing the first official release to the community in the next few weeks: https://github.com/thehunmonkgroup/onenote

For me, that project is the secret sauce that makes TaskWarrior a joy to use :)

And yep, for me synchronization is very important for my notes.
