### ISSUE TITLE
Filtering for attribute values with spaces is broken

### ISSUE THREAD

**Issue by angelus2014** [GothenburgBitFactory/taskwarrior#2388]
#### To report a bug...

* What command(s) did you run? task project:(project name)
* What did you expect to happen? show me the tasks associated with the project (as was the case with 2.5.1)
* What actually happened? It just shows 'no matches'.
* Paste the output of the ```task diag``` command.

➜  ~ t diag

task 2.5.3
   Platform: Linux

Compiler
    Version: 9.3.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      Built: Jan 12 2021 03:18:12
      CMake: 3.19.2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.15
 Build type: Release

Configuration
       File: /home/angelo/.taskrc (found), 2141 bytes, mode 100644
       Data: /home/angelo/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server:
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /home/angelo/.task/hooks
             (-none-)

Tests
   Terminal: 324x67
       Dups: Scanned 396 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 396 tasks for broken references:
             Task d3eb38fc-c0fc-44eb-bb2a-c76b0219e293 depends on nonexistent task: 5e4d5e55-a6a8-4a9f-95f5-beb7515ca826

I copied over the same .task directory to another system that is still using 2.5.1 and there the output is as expected. At first I thought it only happened with project that had a 'wait:later', but I see it with all of my projects. Even t project:(project name) all doesn't work anymore and shows just 'no matches'.

---
Regards,
Angelo

**Comment by angelus2014** [comment]
It seems that the issue is with project that have several words with spaces:

* In version 2.5.1 one could: t project:Set\ up\ MSI\ laptop and one would get the tasks associated with that project. In 2.5.3 I see 'no matches'. But if I just type: t project:Set, then I see the tasks. Problem here of course is if one has multiple projects starting with the same word......

---
Regards,

Angelo

**Comment by tbabej** [comment]
Reproduced on 2.5.3 and 2.6.0. What is happening here is that the `CLI2::prepareFilter insertJunctions` step is injecting implicit "and" in between the words:

```
CLI2::prepareFilter insertJunctions
  _original_args
    task ( status:pending limit:page ) next rc.debug:1 rc.debug.parser:3 project:Test with spaces
  _args
    word basename='task' raw='task' BINARY 
    op raw='(' QUOTED FILTER 
    dom canonical='status' modifier='' raw='status' FILTER 
    op raw='=' FILTER 
    identifier raw='pending' FILTER 
    op raw='and' FILTER 
    word canonical='limit' modifier='' name='limit' raw='limit:page' separator=':' value='page' FILTER 
    op raw=')' QUOTED FILTER 
    identifier canonical='next' raw='next' CMD READONLY SHOWSID RUNSGC USESCONTEXT ALLOWSFILTER 
    pair modifier='debug' name='rc' raw='rc.debug:1' separator=':' value='1' CONFIG ORIGINAL 
    pair modifier='debug.parser' name='rc' raw='rc.debug.parser:3' separator=':' value='3' CONFIG ORIGINAL 
    op raw='and' FILTER 
    op raw='(' ORIGINAL FILTER 
    dom canonical='project' modifier='' raw='project' FILTER 
    op raw='=' FILTER 
    op raw='(' FILTER 
    identifier raw='Test' FILTER 
    op raw='and' FILTER 
    identifier raw='with' FILTER 
    op raw='and' FILTER 
    identifier raw='spaces' FILTER 
    op raw=')' FILTER 
    op raw=')' ORIGINAL FILTER 

FILTER Infix        ( status = pending and limit ) and ( project = ( Test and with and spaces ) )
```

**Comment by tbabej** [comment]
This problem generalizes to any string attribute, not just project.

```
[warrior@tw-v2.5.3 ~]$ task _get 2.estimate
very large
[warrior@tw-v2.5.3 ~]$ task estimate:"very large"
[task next ( estimate:very large )]
No matches.
[warrior@tw-v2.5.3 ~]$ task show | grep estimate
uda.estimate.label                 Size Estimate
uda.estimate.type                  string
```

**Comment by tbabej** [comment]
Inserting ANDs is handled by `CLI2::insertJunctions ()`.
