### ISSUE TITLE
Filtering for project-names containing hyphen and number

### ISSUE THREAD

**Issue by nchiapol** [GothenburgBitFactory/taskwarrior#2392]
I use Debian Testing, upgraded taskwarrior a few days ago and run into the following problem (Debian bug: https://bugs.debian.org/980263): 

I use taskwarrior since several years and have a large number of projects. One common pattern looks like 'c.vs.2021-01'. After updating from 2.5.1+dfsg-11 to 2.5.3+dfsg-1, searches for such projects (`task project:c.vs.2021-01`) fail with error 'Cannot subtract strings'. Downgrading fixes the problem.

(I do not have 2.5.3 installed at the moment, so I can not run `task diag` right now. Let me know if your really need the output, so I can do the up- and downgrade dance.)

**Comment by nchiapol** [comment]
As mentioned in the Reply to the Debian Bug, possibly related:
https://github.com/GothenburgBitFactory/taskwarrior/issues/2124

**Comment by nchiapol** [comment]
Thanks a lot for the fix. The change landed in Debian already but unfortunately, the problem is still partially there. In my pattern mentioned the "numerical" part is 'YYYY-MM', so 'c.vs.2021-11' exists as well. Since Oct, Nov and Dec do not contain a leading 0, the Lexer still detects these expressions as numbers. 

(In my case, things following 'project:' should always be treated as strings, but I don't know who's use-cases this would break. )

**Comment by tbabej** [comment]
@nchiapol Thanks for letting us know. The 'c.vs.2021-11' case now works as well on the 2.6.0 branch, see #2405 and a5eee5fcc622b1e07a07e0ede01d343d8006b5a2.
