### ISSUE TITLE
Unable to edit task

### ISSUE THREAD

**Issue by mgiugliano** [GothenburgBitFactory/taskwarrior#2394]
I would like to report a bug for TaskWarrior under macOs. I have the impression TaskWarrior broke after my "brew" upgrade/update command.

* I run: ```task edit 130```
* ```vim``` should have been called, allowing me to edit the task
* The following error was returned instead:
```
Launching '/usr/local/bin/vim "task.1483b6b4.task"' now...
dyld: Library not loaded: /usr/local/opt/ruby/lib/libruby.2.7.dylib
  Referenced from: /usr/local/bin/vim
  Reason: image not found
Editing failed with exit code 6.
```

I note that there is no such file as /usr/local/opt/ruby/lib/libruby.2.7.dylib. Instead there is /usr/local/opt/ruby/lib/libruby.3.0.dylib

I further add that deleting the(temporary) file in my task folder, /Users/XXXXX/Dropbox/task/task.1483b6b4.task does not solve the issue. 

I finally note that I am also using Taskwarrior-Web, which however gave me a lot of headache for its installation, due to some ruby library version problem.

* Below, you find the output of the ```task diag``` command.

```
task 2.5.1
   Platform: Darwin

Compiler
    Version: Apple LLVM 12.0.0 (clang-1200.0.32.27)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Nov 15 2020 20:22:09
      CMake: 3.18.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.15
 Build type: Release

Configuration
       File: /Users/XXXXX/.taskrc (found), 4214 bytes, mode 100644
       Data: /Users/XXXXX/Dropbox/task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: /usr/local/bin/vim
     Server: taskwarrior.inthe.am:53589
         CA: ~/.dotfiles/task/ca.cert.pem, readable, 2405 bytes
      Trust: ignore hostname
Certificate: ~/.dotfiles/task/private.certificate.pem, readable, 2650 bytes
        Key: ~/.dotfiles/task/private.key.pem, readable, 20127 bytes
    Ciphers: NORMAL
      Creds: inthe_am/XXXXX/************************************

Hooks
     System: Enabled
   Location: /Users/XXXXX/Dropbox/task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (224x62)
       Dups: Scanned 465 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 465 tasks for broken references:
             No broken references found
```

**Comment by tbabej** [comment]
Taskwarrior does not link with `libruby`, it looks like this error is coming from `vim`, possibly due to some vim plugin?

**Comment by mgiugliano** [comment]
Thank you. I will investigate it further disabling all vim plug-in modules.

I think, after your explanation, that this issue can be closed as it is not depending on task warrior.

**Comment by tbabej** [comment]
@mgiugliano Yep, I'd agree. Thanks for bringing this up! Abundance of caution never hurts.
