### ISSUE TITLE
How to contribute to the website?

### ISSUE THREAD

**Issue by Shadow53** [GothenburgBitFactory/taskwarrior#2397]
GitHub releases shows that the current stable release is 2.5.3, but https://taskwarrior.org shows latest as 2.5.1.

Can this be updated? Is there a way a random contributer (myself) can help with that?

**Comment by tbabej** [comment]
@Shadow53 The repo for the website is https://github.com/GothenburgBitFactory/tw.org, where you can contribute a pull request for the sidebar.

**Comment by Shadow53** [comment]
Pull request got accepted at GothenburgBitFactory/tw.org#94, so I'll close this issue.
