### ISSUE TITLE
Wrong weeknumber

### ISSUE THREAD

**Issue by richardbrinkman** [GothenburgBitFactory/taskwarrior#2399]
#### To report a bug...

* What command(s) did you run?
  > task calendar 2021

* What did you expect to happen?
 > A weeknumbering starting with 53

* What actually happened?
 > First weeknumber shown is 1. But according to ISO 8601, week 1 is the week of the first Thursday

* Paste the output of the ```task diag``` command.
```
task 2.5.1
   Platform: Linux

Compiler
    Version: 9.2.1 20200306
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.16.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.11
 Build type: None

Configuration
       File: /home/brinkman/.taskrc (found), 1807 bytes, mode 100664
       Data: /home/brinkman/Dropbox/Private/taskwarrior (found), dir, mode 40775
    Locking: Enabled
         GC: Enabled
  rc.editor: vim
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/brinkman/Dropbox/Private/taskwarrior/hooks
     Active: on-modify.timewarrior (executable)
   Inactive: 

Tests
      $TERM: xterm-256color (313x65)
       Dups: Scanned 2143 tasks for duplicate UUIDs:
             Found duplicate 4cbd6f66-50b2-48e3-9dff-837852b7c4f6
             Found duplicate b30867fd-c04f-430f-a2c4-31d7149c2d04
             Found duplicate d08dbba0-256a-4aae-84d2-581705d9b171
             Found duplicate d5a7aef7-b965-496f-b3c4-8a0d20a24fe5
             Found duplicate d3f62e61-076a-442a-af28-a2ac35416964
 Broken ref: Scanned 2143 tasks for broken references:
             No broken references found
```

**Comment by tbabej** [comment]
A nice find! Reproduced on 2.5.1. However, it looks like this is already fixed on the latest 2.5.3 release:

![image](https://user-images.githubusercontent.com/2123868/105837865-4b22ad00-5f9d-11eb-9707-4f5f37f1a8de.png)

**Comment by tbabej** [comment]
@richardbrinkman Let us know if update to 2.5.3 resolves the issue for you :slightly_smiling_face:

**Comment by richardbrinkman** [comment]
Unfortunately I was unable to upgrade to version 2.5.3. I tried apt-get in both ubuntu and debian and dnf on fedora. But all 3 linux destribution only ship the 5 year old version 2.5.1. Maybe you should inform the package managers to update taskwarrior to the newest version in their repositories.

Next, I tried to compile it from source but did not manage because of the numerous compile errors due to missing packages. Some I could resolve but some others, such as libuuid, I could not. 
Since I don't want my system clobbered with all kind of development tools and libraries, I performed the compilation[attempt] on a clean ubuntu docker container.

**Comment by tbabej** [comment]
@richardbrinkman For compilation in a container, you can get the list of packages you need from the [dockerfiles used for tests](https://github.com/GothenburgBitFactory/taskwarrior/tree/2.6.0/test/docker), i.e. for Fedora 33, the packages required would be:

> dnf install gcc gcc-c++ cmake make gnutls-devel libuuid-devel -y

**Comment by tbabej** [comment]
> Maybe you should inform the package managers to update taskwarrior to the newest version in their repositories.

Good point. Efforts to upgrade the package versions in distributions are underway.

**Comment by richardbrinkman** [comment]
I've managed to compile and indeed is the weeknumbering correct in version 2.5.3

**Comment by tbabej** [comment]
Thanks for the confirmation!
