### ISSUE TITLE
[EX-26] journal

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#24]
_David Patrick on 2009-07-15T14:49:29Z says:_ 

 Somewhere between log-file and personal diary, the journal will become an essential tool.
From the command line, you will be able to jump right into editing the journal with your fave text editor, just by entering "task -j" (same as "task journal" same as "vi ~/.task/files/journal.task) and at any time you will be able to append text with "task journal mytext".

see: [[journal]]

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-07-15T14:49:29Z
Modified: 2014-02-09T02:43:22Z
```

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2011-01-21T17:08:30Z says:_ 

 Per-task journaling would fit here.  Ala, "task 5 journal".

I tend to like to jot down thoughts about some of my tasks sometimes... implementation ideas, notes, complaints...  They tend to be too verbose and irrelevant to use annotations.

One of the other feature requests (see https://github.com/ValiValpas/taskopen) suggests a "note" command which can be done with a file in the filesystem.  I think that feature and this one may be different facets of the same feature, and could be implemented together in one feature.

**Comment by taskwarrior** [comment]
_David Patrick on 2011-01-23T01:23:20Z says:_ 

 I disagree Bryce, I think that while taskopen and the proposed journal could both be used for keeping notes, the taskopen functionality is for attaching things to specific tasks, while the journal (or whatever we end up calling it) will be more like a combination of a personal diary and a log file, that automatically records all pertinent actions into a single text file that can then be freely edited and enhanced. The automatically generated entries should be entirely human readable, even approached with a typographical eye. There is no reason that other programs might be invited to play too, appending details when appropriate, aggregating any information that you would like to track. As it gets bigger, tools to search, summarize fold and trim could be added.

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2011-01-24T01:40:12Z says:_ 

 Oh, I see...  Yeah you're right, that sounds way more sophisticated than just a notes function (which is all I need, myself).

Curious how you're going to deal with locking though...

**Comment by taskwarrior** [comment]
_David Patrick on 2011-01-24T09:18:54Z says:_ 

 Bryce Harrington wrote:
> Curious how you're going to deal with locking though...

easy; don't do it!
It's a personal document that is appended to by taskwarrior, and can be freely edited. There is no return trip.

**Comment by taskwarrior** [comment]
_David Patrick on 2011-06-15T18:04:28Z says:_ 

 a nice feature that will have to wait

**Comment by taskwarrior** [comment]
_Eric Fluger on 2011-06-16T20:49:13Z says:_ 

 the notion of "record type" mentioned elsewhere may apply here.

**Comment by taskwarrior** [comment]
_David Patrick on 2011-06-17T05:08:58Z says:_ 

 Eric Fluger wrote:
> the notion of "record type" mentioned elsewhere may apply here.

please elaborate, Eric, it seems to me that this journal file should be a human readable and editable text file. 
Entries made automatically, to record task completions, should be pretty-printed for easy readability.
This automated part is one-way, written to the file, and further modifications and additions must be made with your favorite text editor.

**Comment by taskwarrior** [comment]
_David Patrick on 2012-03-22T21:35:33Z says:_ 

 After some time to reflect, an interesting application has been developed for those of us who decidedly like to use vim, but who secretly wish they had something as cool as orgmode;

VimOrganizer, an orgmode clone for vim. It's a branch off of the vimoutliner tree, grafted onto emacs, and it is proving comfortable and convenient. If the *journal* feature described here, was implemented as an external script, using record-write hooks to tee off to a task-journal.org file, then not only would it result in a useful, flexible personal history file, but users of orgmode and VimOrganizer could do a lot of interesting things with the data.

see: https://github.com/hsitz/VimOrganizer
and: https://github.com/hsitz/VimOrganizer/issues/37
and: http://vimeo.com/31531308

(from intro.txt)

<pre>
VimOrganizer version 0.30, November 2, 2011. Requires Vim version that
is compiled with support for folding and tabs. Conceal will
be taken advantage of if working with Vim73 supporting conceal.
(Also, I STRONGLY suggest that you apply a patch to Vim so that
folded headings can have level-dependent highlighting,
patch for Vim73 is in contrib directory of the download. If you're on
Windows contact me and I should be able to provide you with an
executable. If I hadn't been able to make Vim do this I would have
bitten the bullet and moved to Emacs, as much as I hate editing in Emacs.)

VimOrganizer is a Vim filetype plugin that attempts to clone Emacs' Org-mode.
It is currently (November 2011) in an alpha-stage, both in terms of (1) the
breadth and depth of Org-mode features it clones and (2) the stability of its
operation. It is nevertheless very usable.
</pre>

**Comment by pbeckingham** [comment]
No plans to implement.
