### ISSUE TITLE
Taskserver documentation going away

### ISSUE THREAD

**Issue by rouilj** [GothenburgBitFactory/taskwarrior#2400]
The taskserver documentation links to a GitPitch page.

I clicked on https://taskwarrior.org/docs/#taskd and the Taskserver Setup Guide link points to https://gitpitch.com/GothenburgBitFactory/taskserver-setup#/

When I went there the following is displayed as the first slide in the deck:
```
GitPitch.com is shutting down.
This slide deck will no longer
be available from March 1, 2021. 
```

Given that the future of taskserver is in question #2341, this may be easily handled by deleting the entire taskserver documentation.

-- rouilj

**Comment by djmitche** [comment]
We should try to rescue that somehow -- that is basically the *only* documentation of taskserver

**Comment by tbabej** [comment]
We might need to self-host gitpitch (the repository is available at https://github.com/gitpitch/gitpitch), but the actual content is being served from https://github.com/GothenburgBitFactory/taskserver-setup. So the data itself will not be lost.

I will look into making sure this is available before the service gets shut down. The guide itself will likely be need in some updates / polishing as well.

**Comment by thetayloredman** [comment]
There is only 21 days left so we should get to work

**Comment by mrossinek** [comment]
Just as an FYI to put out here: since I was always a fan of the previous documentation compared to gitpitch, I kept this bookmark around which is still valid: https://taskwarrior.org/docs/taskserver/setup.html
It is just not reachable via a direkt link on the website afaict..

**Comment by thetayloredman** [comment]
> Just as an FYI to put out here: since I was always a fan of the previous documentation compared to gitpitch, I kept this bookmark around which is still valid: https://taskwarrior.org/docs/taskserver/setup.html
> It is just not reachable via a direkt link on the website afaict..

We could change the taskserver doc link to that URL..?

**Comment by tbabej** [comment]
Correct. The repository for taskwarrior.org is here: https://github.com/GothenburgBitFactory/tw.org

**Comment by thetayloredman** [comment]
> Correct. The repository for taskwarrior.org is here, if anybody feels like giving it a try: https://github.com/GothenburgBitFactory/tw.org

https://github.com/GothenburgBitFactory/tw.org/blob/a5a9a19e82b1c9c7403680481d3d43df37402585/html/docs/index.html#L143-L149

**Comment by tbabej** [comment]
Closing, as this was addressed in https://github.com/GothenburgBitFactory/tw.org/commit/98ffa83393c951eb879add3b91a4b7c43bb9f6e3 by @lauft 23 days ago.
