### ISSUE TITLE
ftruncate error

### ISSUE THREAD

**Issue by ghistes** [GothenburgBitFactory/taskwarrior#2408]
Hi,

I would like to run taskwarrior on my phone in a debian-environment within termux (see https://github.com/sp4rkie/debian-on-termux)..

I can install version 2.5.3 from the debian-repository and I can create tasks, however I cannot mark tasks as done.

Everytime I try e.g. "task 1 done" I get the following error:

             ftruncate error 38: function not implemented

What is this? Is this a problem with taskwarrior, or with a library or where does this come from and is there a way around it?

Many thanks!

**Comment by tbabej** [comment]
Hi @ghistes,

`ftruncate` method is a function to truncate a file to zero size [1], it's part of the POSIX C API. On Linux systems, it is usually provided by `glibc` or `musl`. Possibly a version mismatch (i.e. task being compiled against a different version of glibc/musl)?

I'd try installing the build toolchain in termux and building taskwarrior from source.

[1] https://linux.die.net/man/3/ftruncate
[2] https://en.wikipedia.org/wiki/Unistd.h

**Comment by ghistes** [comment]
The thing is that is not really running on a Linux-system as such, but in termux on an android-system.

And I don't really want to install everything that is need to compile taskwarrior on my phone.

My idea was to run a taskserver on my always-on router and sync my PC and my phone via that but I am also having problems compiling taskserver for my router so I have to figure that out first, otherwise it won't make much sense.

Anyway it probably is not really a taskwarrior issue, so feel free to close this issue.
