### ISSUE TITLE
test tarball includes hardcoded paths to `/home/tbabej/Projects/taskwarrior`

### ISSUE THREAD

**Issue by nicknovitski** [GothenburgBitFactory/taskwarrior#2416]
While setting up the tests to run for the nix package, I noticed that the `Makefile` in the [released tests tarball](https://github.com/GothenburgBitFactory/taskwarrior/releases/download/v2.5.3/tests-2.5.3.tar.gz) contains a lot of references to this path.

For example:
```
# The main all target
all: cmake_check_build_system
	cd /home/tbabej/Projects/taskwarrior && $(CMAKE_COMMAND) -E cmake_progress_start /home/tbabej/Projects/taskwarrior/CMakeFiles /home/tbabej/Projects/taskwarrior/test//CMakeFiles/progress.marks
	cd /home/tbabej/Projects/taskwarrior && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tbabej/Projects/taskwarrior/CMakeFiles 0
.PHONY : all
```

This makes it unclear to me how to use the test tarball by itself: the commands listed in its readme cannot succeed.  Instead I'm putting the test directory into the source directory and and running `make test` at that level.

**Comment by tbabej** [comment]
Sorry about that generated `Makefile` sneaking in. Your process is correct though, the `tests` directory should be put inside of the source directory and `Makefile` generated from there using `cmake`.

**Comment by tbabej** [comment]
The release process amended to avoid this in the future releases. Thanks for reportiing!
