### ISSUE TITLE
"eow" and "eonw" seem to use different week day as reference, which may results in 2 week difference between the two

### ISSUE THREAD

**Issue by bgravato** [GothenburgBitFactory/taskwarrior#2422]
I'm running taskwarrior 2.5.3.

Today is Sunday and I was trying to change a task due date using "eow" and "eonw" date keywords and I got some unexpected results... Seems like eow  and eonw are using a different week day as reference to calculate what is this week and next week...

When the week day is Sunday, there's a 2 week difference between eow and eonw as you can see on my tests results (using faketime):

When current day is Saturday:
```
$ faketime "yesterday" date 
Sat 06 Mar 2021 12:36:31 PM WET

$ faketime "yesterday" task 22 mod due:eow
$ task 22 info |grep ^Due
Due           2021-03-08 00:00:00

$ faketime "yesterday" task 22 mod due:eonw
$ task 22 info |grep ^Due
Due           2021-03-15 00:00:00
```

When current day is Sunday:
```
$ faketime "today" date 
Sun 07 Mar 2021 12:37:09 PM WET

$ faketime "today" task 22 mod due:eow
$ task 22 info |grep ^Due
Due           2021-03-08 00:00:00

$ faketime "today" task 22 mod due:eonw
$ task 22 info |grep ^Due
Due           2021-03-22 00:00:00
```

When current day is Monday:
```
$ faketime "tomorrow" date 
Mon 08 Mar 2021 12:37:51 PM WET

$ faketime "tomorrow" task 22 mod due:eow
$ task 22 info |grep ^Due
Due           2021-03-15 00:00:00

$ faketime "tomorrow" task 22 mod due:eonw
$ task 22 info |grep ^Due
Due           2021-03-22 00:00:00
```

So it seems that for eow it considers that the week starts on Monday and for eonw it considers that the week starts on Sunday, which is not very consistent...

Not sure if my regional settings play any role on this, but it should be consistent regardless.

Some more debugging info:

```
$ task diag

task 2.5.3
   Platform: Linux

Compiler
    Version: 8.3.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.16.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.7
 Build type: None

Configuration
       File: /home/bruno/.taskrc (found), 1928 bytes, mode 100644
       Data: /home/bruno/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: 
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/bruno/.task/hooks
     Active: on-modify.timewarrior (executable)
   Inactive: 

Tests
   Terminal: 202x43
       Dups: Scanned 78 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 78 tasks for broken references:
             No broken references found
```

**Comment by tbabej** [comment]
Reproduced on 2.6.0. Nice find @bgravato! This bug seems to have been introduced exactly three years ago in 18106890f2af3735476da008c8499e29471b1235.

**Comment by bgravato** [comment]
Wow! That was fast! Thanks!

I wish all bugs were solved this quick!

BTW, the [online documentation](https://taskwarrior.org/docs/dates.html#names) seems to be a bit outdated in regards to this... "eocw" is still referenced even though it's no longer supported... and there's no reference to "eonw" (maybe that's why it went under the radar for 3 years? or maybe no one updates their task lists on a Sunday! hehe).
