### ISSUE TITLE
how to find task that just became un-waiting

### ISSUE THREAD

**Issue by kwoot** [GothenburgBitFactory/taskwarrior#2424]
The more I use TW, the more I love it. This is not a bug, nor a feature request ( yet :-) ). More of a question

I added some lines to my bashrc which means task is run with every prompt. Loving it.
Every morning, my first <Return> will show me a list of tasks that became un-waiting.
Nice. But I can see I need to modify a few and increase the wait-date.
I know I can list tasks waiting, but can I list tasks that became un-waiting?

**Comment by tbabej** [comment]
Hi there @kwoot,

queries involving past states of attributes of any given task are not supported. The closest thing you can do is query for tasks that were recently modified, i.e. (from the top of my head): `task modified.after:now-1h list`

**Comment by kwoot** [comment]
Works for me! Thanks!

**Comment by kwoot** [comment]
At this is why I  :heart: TW! 

$ task config report.unwaited.description 'Show tasks who became un-waiting'
$ task config report.unwaited.columns     'id,project,description.desc'
$ task config report.unwaited.filter            'modified.after:now-4h status:pending'
$ task unwaited

**Comment by kwoot** [comment]
Hm works except for created child tasks. Will research.
