### ISSUE TITLE
General question about storage back-end

### ISSUE THREAD

**Issue by kwoot** [GothenburgBitFactory/taskwarrior#2426]
Hi,
Maybe this has been asked before (I did not find it here).
I'm no C++ expert, but does the TW code use a central storage layer for writing the data files?
If so, would it be an option to add an alternative based on SQL? SQLite would be fine.
I think it would increase the search and retrieval options immensely.
OTOH, if storage is throughout the code that idea would be a real PITA to build.
Just wondering.

**Comment by tbabej** [comment]
Moving to discussions.
