### ISSUE TITLE
The "edit" command should respect "bulk" configuration option

### ISSUE THREAD

**Issue by Craskermasker** [GothenburgBitFactory/taskwarrior#2428]
#### To report a bug...

* What command(s) did you run?
`task edi`

* What did you expect to happen?
Search for a task containing edi

* What actually happened?
text editor opening to edit every task (including completed)

Suggestion:
- If more than e.g. 100 tasks queued for edit, prompt user if they really want to edit that many tasks.

* Paste the output of the ```task diag``` command.

task 2.5.1
   Platform: Linux

Compiler
    Version: 9.2.1 20200306
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.16.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.11
 Build type: None

Configuration
       File: /home/evan/.taskrc (found), 1827 bytes, mode 100644
       Data: /home/evan/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/evan/.task/hooks
     Active: on-modify.timewarrior (executable)
   Inactive: 

Tests
      $TERM: xterm-256color (276x145)
       Dups: Scanned 1854 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 1854 tasks for broken references:
             No broken references found

**Comment by tbabej** [comment]
We already have a configuration option for this, called `bulk`, however, `task edit` does not seem to respect that.
