### ISSUE TITLE
How can I enter a due date like Monday at 8:15 ?

### ISSUE THREAD

**Issue by kwoot** [GothenburgBitFactory/taskwarrior#2434]
Can I enter a due date like Monday at 8:15 ?

I can do a due:monday, and a due:2021-03-28T08:00

But due:monday-08:00 equals date entered - 08:00.

**Comment by tbabej** [comment]
Hi @kwoot ,

you can use the expression evaluation, i.e. following: `due:monday+8h+15m`

P.S: This is really more of a question / discussion, than an issue. For those, we now have a separate "Discussions" tab that you can use.

**Comment by kwoot** [comment]
Ah, thank you for feedback and I will use discussion next time.
