### ISSUE TITLE
Readme says build requires C++14 but build actually requires C++17

### ISSUE THREAD

**Issue by ryandesign** [GothenburgBitFactory/taskwarrior#2437]
The readme says building from source requires:

> C++ compiler, currently gcc 5.0+ or clang 3.4+ for full C++14 support

In fact, it requires C++17. If I don't have a C++17 compiler then this error occurs:

```
-- Configuring C++17
-- System: Darwin
-- Performing Test _HAS_CXX17
-- Performing Test _HAS_CXX17 - Failed
CMake Error at cmake/CXXSniffer.cmake:11 (message):
  C++17 support missing.  Try upgrading your C++ compiler.  If you have a
  good reason for using an outdated compiler, please let us know at
  support@gothenburgbitfactory.org.
Call Stack (most recent call first):
  CMakeLists.txt:11 (include)
```

Please update the readme.

**Comment by tbabej** [comment]
The source in question is the latest release tarball?

**Comment by tbabej** [comment]
I believe this is already fixed on the current development branch.

**Comment by ryandesign** [comment]
Thanks. I was looking at your master branch, where this change has not yet been made. You should make the change there as well.
