### ISSUE TITLE
Command `task $month` doesn't behave correctly

### ISSUE THREAD

**Issue by Petemir** [GothenburgBitFactory/taskwarrior#2451]
#### To report a bug...

* What command(s) did you run?
`task mar`, `task marc`, `task march`

This actually happens with other months (`task feb`, `task febr`, etc.)

* What did you expect to happen?
1) For the first two commands, I would expect that tasks with either "mar", or "marc" on their description would appear, but all tasks appear. 
2) For `task march` I don't know what I would expect (as `march` can be considered a `special word`, but perhaps tasks done on march, due on march, or something like that?), but I wouldn't expect all tasks to appear.

* What actually happened?
All tasks (i.e., the same as executing just `task`) appear with any combination of the previous commands (`task + substring larger than 2 characters of a month`)

* Paste the output of the ```task diag``` command.
(issue also happens with 2.6, and on 2.5.1 also with 2-letters month subtring, e.g. `task ma`, and also with the first letter capitalized, e.g. `task Ma`, `task Mar`, etc.)
```
task 2.5.3
   Platform: Linux

Compiler
    Version: 10.2.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      Built: Apr 13 2021 17:28:09
      CMake: 3.16.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.15
 Build type: release

Configuration
       File: /home/petemir/.taskrc (found), 1868 bytes, mode 100664
       Data: /home/petemir/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: inthe.am:53589
         CA: /home/petemir/Projects/automation/computer/twarrior/inthe.am/ca.cert.pem, readable, 2405 bytes
Certificate: /home/petemir/Projects/automation/computer/twarrior/inthe.am/private.certificate.pem, readable, 2710 bytes
        Key: /home/petemir/Projects/automation/computer/twarrior/inthe.am/private.key.pem, readable, 17764 bytes
      Trust: ignore hostname
    Ciphers: NORMAL
      Creds: inthe_am/matiaslaporte/************************************

Hooks
     System: Enabled
   Location: /home/petemir/.task/hooks
     Active: on-modify.timewarrior (executable)
   Inactive: 

Tests
   Terminal: 322x67
       Dups: Scanned 131 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 131 tasks for broken references:
             No broken references found
```

This issue is "migrated" from [taskwarrior-tui#187](https://github.com/kdheepak/taskwarrior-tui/issues/187#issuecomment-818837384), as I first thought it was a problem there, but @kdheepak made me realize it wasn't :) .

**Comment by tbabej** [comment]
Reproduced on 2.6.0. Good find!

**Comment by tbabej** [comment]
The underlying issue is that the token is interpreted as date and ignored (has no effect on filtering)
![image](https://user-images.githubusercontent.com/2123868/114637866-516d1f00-9c98-11eb-8c80-8206b124a2eb.png)

**Comment by kdheepak** [comment]
Thanks for looking into it so quickly @tbabej!

**Comment by tbabej** [comment]
Diagnosing the issue is one thing, fixing it another :sweat_smile:

**Comment by kdheepak** [comment]
One step at a time I guess!

**Comment by Petemir** [comment]
That was quick, thanks! Finally I'll be able to search tasks with my supervisor's name on them :smile:
