### ISSUE TITLE
[TW-204] read-only mode

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#249]
_David Patrick on 2010-07-07T16:57:54Z says:_ 

 for scripted execution, many queries don't require write access to the files, and shouldn't have it. Would it be possible (is it already possible) to have a read-only mode that doesn't require write access to the core files?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-07-07T16:57:54Z
Modified: 2017-01-16T17:03:20Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-07-07T23:38:24Z says:_ 

 Currently this is not possible.  This is because most commands perform a gc (garbage collect) before displaying the tasks.  The gc is run because there are tasks that need to be moved to the pending.data file, there are waiting tasks that need to be woken up, and there are recurring tasks that may need to be created.

But this is a very good idea.  Task could check on startup, whether it has write permission to the pending.data and completed.data files.  If it does not have write permission, then certain commands could be disabled (add, done ...) and a warning could be issued.  But not all commands would need to be disabled, despite the fact that gc would definitely be disabled.

If I wanted to allow someone to view my tasks, I could certainly make the files readable using file permissions, and if task then played nicely with this, it would allow interesting sharing scenarios.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-08-24T03:44:24Z says:_ 

 This is almost done.  It's going to be a good feature.  Just wanted folks to know it isn't going to get deferred.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-01-28T21:54:51Z says:_ 

 Support is there, but it has not been completed and tested.

**Comment by taskwarrior** [comment]
_David Patrick on 2013-05-04T19:41:59Z says:_ 

 As more external scripts are written, all of them have access core task-write functions, but many of them don't need that capability. Things like scripts to generate output, or calendars, there's no reason for that script to write pending.data, but still no clear way to mark the data ready-only.

Maybe the solution is again hook-based, and any write-hook has to check rc.readonly:yes

yes?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-05-04T19:58:28Z says:_ 

 David Patrick wrote:
> Maybe the solution is again hook-based, and any write-hook has to check rc.readonly:yes
> 
> yes?

Good point.  There is no mechanism to convey this currently.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2013-05-05T19:56:17Z says:_ 

 It's not a real solution, but an external script could copy the files to a directory where you do have write permissions and then just run the command on that task directory.

**Comment by taskwarrior** [comment]
_David Patrick on 2013-05-06T16:33:51Z says:_ 

 Scott Kostyshak wrote:
> It's not a real solution, but an external script could copy the files to a directory where you do have write permissions and then just run the command on that task directory.

That's an interesting idea! I would then be worried about how that copied data is reconciled with the primary data..

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2013-05-07T00:49:59Z says:_ 

 David Patrick wrote:
> Scott Kostyshak wrote:
> > It's not a real solution, but an external script could copy the files to a directory where you do have write permissions and then just run the command on that task directory.
> 
> That's an interesting idea! I would then be worried about how that copied data is reconciled with the primary data..

I might be misunderstanding the original request. Why would the copied data be reconciled with the primary data? I thought the point was that the user does not have write access to the primary data and they just want to run a command on the data but not modify it. Thus, the copied data would be deleted after the command was run.

**Comment by taskwarrior** [comment]
_David Patrick on 2013-05-07T04:26:52Z says:_ 

 Scott Kostyshak wrote:
> I might be misunderstanding the original request. Why would the copied data be reconciled with the primary data? I thought the point was that the user does not have write access to the primary data and they just want to run a command on the data but not modify it. Thus, the copied data would be deleted after the command was run.

uhh.. yes, that makes sense Scott, and "export" is not a write command.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-12-27T23:00:11Z says:_ 

 This is already supported in the lower layers.  It needs to be completed, with front end feedback.

**Comment by djmitche** [comment]
Duping forward to #3418.
