### ISSUE TITLE
Error SIGABRT

### ISSUE THREAD

**Issue by tjapro** [GothenburgBitFactory/taskwarrior#2490]
#### To report a bug...

* What command(s) did you run? 
tk modify ... in a recurring task, and answer "n", instead of "no"
Then, run tk

* What did you expect to happen?
The list of next things.

* What actually happened?
```
/usr/include/c++/11/bits/basic_string.h:1026: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.
fish: Job 1, 'task $argv' terminated by signal SIGABRT (Abort)
```

* Paste the output of the ```task diag``` command.
```
task 2.5.1
   Platform: Linux

Compiler
    Version: 11.0.0 20210123 (Red Hat 11.0.0-0)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Jan 27 2021 00:00:00
      CMake: 3.19.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.15
 Build type: 

Configuration
       File: /home/.../.config/taskwarrior/taskrc (found), 1355 bytes, mode 100644
       Data: /home/.../.config/taskwarrior/task (found), dir, mode 40755
     TASKRC: /home/.../.config/taskwarrior/taskrc
    Locking: Enabled
         GC: Enabled
    $EDITOR: /usr/bin/nano
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/.../.config/taskwarrior/task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (156x50)
       Dups: Scanned 100 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 100 tasks for broken references:
             No broken references found
```

**Comment by tjapro** [comment]
`sudo dnf reinstall task` do not resolve.

**Comment by tjapro** [comment]
Resolved by running `tasksh` and removing the taks if error.
> I'll maintain this issue open for code correction, maybe ...

**Comment by tbabej** [comment]
I think there must be something more than just the task being recurrent going on. Trying to reproduce on 2.5.1, I fail both with trying to modify the recurrence template itself, or the instance:

```
[warrior@tw-v2.5.1 ~]$ task add pay the bills recur:monthly due:today
Created task 1 (recurrence template).
[warrior@tw-v2.5.1 ~]$ task
[task next]

ID Age Recur Due Description   Urg 
 2 -    P30D -3h pay the bills 8.86
 3 -    P30D 4w  pay the bills  2.4

2 tasks
Creating recurring task instance 'pay the bills'
# Trying the modify the latest instance
[warrior@tw-v2.5.1 ~]$ task 3 mod +test
Modifying task 3 'pay the bills'.
This is a recurring task.  Do you want to modify all pending recurrences of this same task? (yes/no) n
Modified 1 task.
# Trying to modify the template
[warrior@tw-v2.5.1 ~]$ task 1 mod +test
Modifying task 1 'pay the bills'.
Modifying recurring task 2 'pay the bills'.
Modifying recurring task 3 'pay the bills'.
Modified 3 tasks.
```

**Comment by tjapro** [comment]
> I think there must be something more than just the task being recurrent going on. Trying to reproduce on 2.5.1, I fail both with trying to modify the recurrence template itself, or the instance:
> 
> 
> ```
> [warrior@tw-v2.5.1 ~]$ task add pay the bills recur:monthly due:today
> Created task 1 (recurrence template).
> [warrior@tw-v2.5.1 ~]$ task
> [task next]
> 
> ID Age Recur Due Description   Urg 
>  2 -    P30D -3h pay the bills 8.86
>  3 -    P30D 4w  pay the bills  2.4
> 
> 2 tasks
> Creating recurring task instance 'pay the bills'
> # Trying the modify the latest instance
> [warrior@tw-v2.5.1 ~]$ task 3 mod +test
> Modifying task 3 'pay the bills'.
> This is a recurring task.  Do you want to modify all pending recurrences of this same task? (yes/no) n
> Modified 1 task.
> # Trying to modify the template
> [warrior@tw-v2.5.1 ~]$ task 1 mod +test
> Modifying task 1 'pay the bills'.
> Modifying recurring task 2 'pay the bills'.
> Modifying recurring task 3 'pay the bills'.
> Modified 3 tasks.
> ```

But can you list the tasks? `task next` after the modifications?

**Comment by tbabej** [comment]
Correct, listing task works as expected. Also, it could be worth exploring if upgrading to 2.5.3 fixes your issue.

**Comment by tjapro** [comment]
Meanwhile, my problem is fixed via `tasksh`.  
My `task` is upgraded according to the system itself.  
If some bug occurs again, in this version or in the next, I'll issue it.  
Thanks.

**Comment by tbabej** [comment]
Sounds good. I'll close this for now, as it's currently unclear how to get to this error state. If anybody hits this problem, please chime in, we'll reopen the issue and try to tackle this.

**Comment by tbabej** [comment]
I actually suspect this is already fixed on 2.5.2 or later, see #2024 for reference.

**Comment by tjapro** [comment]
Sorry for commenting here again, but I remember that ABRT records all errors.
So there is the report: https://retrace.fedoraproject.org/faf/reports/170729/
I hope this help you to see if this issue is already fixed or not.

**Comment by tbabej** [comment]
@tjapro Thanks, it does! Given the stack trace, I believe this is already fixed. Also, I'm noticing you're on Fedora - we released new Fedora packages couple of days ago and they should be hitting stable soon. If you want to test it, consider giving karma on Bodhi :slightly_smiling_face: 

* F33: https://bodhi.fedoraproject.org/updates/FEDORA-2021-507713b4d3
* F34: https://bodhi.fedoraproject.org/updates/FEDORA-2021-bf4368bb80
