### ISSUE TITLE
Segmentation Fault when try to sync with server

### ISSUE THREAD

**Issue by BANOnotIT** [GothenburgBitFactory/taskwarrior#2498]
* What command(s) did you run?
`task sync`
* What did you expect to happen?
I expect client to sync with server
* What actually happened?
Program fails with `segmentation fault (core dumped)`
* Paste the output of the ```task diag``` command.
```
task 2.5.1
   Platform: Linux

Compiler
    Version: 7.2.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.9.5
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.8
 Build type: None

Configuration
       File: /home/banonotit/.taskrc (found), 2717 bytes, mode 100664
       Data: /home/banonotit/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: inthe.am:53589
         CA: /home/banonotit/.task/ca.cert.pem, readable, 2405 bytes
      Trust: ignore hostname
Certificate: /home/banonotit/.task/private.cert, readable, 2710 bytes
        Key: /home/banonotit/.task/private.key, readable, 17764 bytes
    Ciphers: NORMAL
      Creds: inthe_am/bano.notit/************************************

Hooks
     System: Enabled
   Location: /home/banonotit/.task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (120x30)
       Dups: Scanned 187 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 187 tasks for broken references:
             No broken references found
```

**Comment by tbabej** [comment]
Hi @BANOnotIT, could you share that core dump with me? I'm afraid we won't be able to debug this without it. Email is in the profile.

**Comment by tbabej** [comment]
Closing as there is unfortunately nothing we can do here without the data or the coredump.

@BANOnotIT if you'd be able to help with crafting a reproducer by providing the above, we can definitely reopen and address this

**Comment by BANOnotIT** [comment]
@tbabej the problem is that I couldn't send you a letter on email in your profile.

And the other problem is I don't know where to find the coredump. So if you direct me I can share it with you on keebase for example.

And now I have no unhandled fails when I try to sync, it just says it can't find some ancestor uuid

**Comment by tbabej** [comment]
@BANOnotIT my keybase username is `tbabej` - I'd be happy to chat to you there :slightly_smiling_face:
