### ISSUE TITLE
Explore an OT-based sync approach

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#2507]
[Operational Transformation](https://en.wikipedia.org/wiki/Operational_transformation) is an approach for synchronizing multiple replicas of the same data in an eventually-consistent model, suitable for cases where there is a central location that all replicas can refer to, and where most modifications do not conflict with one another.  Personal task data fits these conditions perfectly.

This issue is an early exploration of applying OT to synchronize taskwarrior instances, as a wholesale replacement for the current taskd-based synchronization mechanism, which has a number of problems.

TaskChampion has already shown that OT can be successful. The remaining exploration is to determine what changes are required to the TW data model to support this, and to consider approaches for garbage collection, data security, etc.

## Subtasks

* https://github.com/GothenburgBitFactory/tw.org/pull/196
* #2553
* #2554 
* #2569 
* https://github.com/GothenburgBitFactory/tw.org/issues/212
* #2596 (issue was somehow deleted..)
* #2681

**Comment by djmitche** [comment]
I'll be working on this.

**Comment by tbabej** [comment]
According to the linked Wikipedia page, the OT approach could be implemented using various OT control algorithms with slightly different tradeoffs. What is your current thinking on the proper choice there?

**Comment by djmitche** [comment]
(would you mind assigning this to me so that it shows up in my TaskWarrior? :) )

**Comment by tbabej** [comment]
Done!

**Comment by djmitche** [comment]
The [models](https://en.wikipedia.org/wiki/Operational_transformation#Consistency_models) are basically restrictions on the design of the transformation functions.  CC is the most basic, and CCI adds "Intention", which becomes relevant for edge cases like transforming a change which deletes an entire paragraph with a change that inserts a new sentence into that paragraph.  Happily, with a well-defined task model (and this might require some changes to the TW data model), CC is plenty.

First, most operations do not conflict, either because they apply to different tasks, or because they apply to different properties of the same task (e.g., adding a tag and marking a task as started).  So, transposing those operations is simply a matter of swapping them without change.

For operations that do apply to the same property of the same task, we have a timestamp on the operation.  We also make the general presumption that operations are created by one person who intended them to occur in the order they were created.  So we can simply select the later of the two operations and discard the other.  When the timestamps are identical, any total ordering is a good fallback.

Getting back to that well-defined task model, that means picking operations that transpose well.  So for example, creating a task (`Create(taskId)`) adds an empty task record to the database, with no properties.  The properties are created in separate, subsequent `Update(taskId, property, value)` operations.  The tricky bit that I haven't figured out is task deletion, since it implicitly drops all properties associated with a task.  So how does `Delete(taskId)` transpose with `Update(taskId, property, value)` for the same task?  In practice, I think this is solvable by only deleting tasks that have been hidden from the user for a long time, and are thus unlikely to be modified concurrently with deletion.

**Comment by djmitche** [comment]
So one tricky thing I see here is that TDB2::modify is just given the updated task, with no indication of what has changed.  Applying a diff to determine the operation in that case seems error-prone.

Also, the function (or at least TDB2::update) appears to be called for synchronized changes as well.

I wonder if it's best to write a TDB3 that interfaces differently with the rest of the code.  My preference would be to treat add/modify/delete as as sequences of "operations" that get applied to the DB and added to the backlog.  Then synchronization involves some transposition of the backlog and application of the transposed operations.  That would mean changing the implementation of all of the Task methods to generate operations instead of just calling `db.modify` and so on.

Building a TDB3 would also allow refactoring the data format to a strict string:string key/value store, disallowing lists as values.  That will mean a change to dependencies and tags, at least.  The idea is to convert tags to a key:value pair of `("tag.<tagname>", "")` so that it can be added with `Update(taskId, "tag.foo", "")` and removed with `Update(taskId, "tag.foo", None)` to delete the property.

Overall, I'm not sure how to limit the scope of this change.  Advice?

**Comment by djmitche** [comment]
That's not quite true: one way I see of limiting the scope is to "hide" the OT, using approaches like the diff-calculation I mentioned above, and special-casing modifications as to whether they are applying a "new" operation or one from the sync server.  I feel like this approach would be very error-prone, and lead to a great deal more complexity as well.

**Comment by tbabej** [comment]
Why would the special casing be required? I agree with diffing being error-prone, but if we could get away with for now, it would allow us to move forward without having to split off the development branch too much :thinking:

Once the work on the 3.0 release starts (after 2.6 is out), I would be open to doing more drastic data model changes, as well as changing how tasks are internally modified.

**Comment by djmitche** [comment]
The special-casing is required to distinguish the application of a new operation (which must later be sent to the sync server) witht he application of an operation from another replica (which came from the sync server).

**Comment by djmitche** [comment]
I don't think this is going to work if we try to shoe-horn it into the existing API.  The ultimate goal is to get a reliable sync system, and if we take "best-effort" shortcuts like diffing tasks, rather than making the operations the fundamental data structure, I think we'll be chasing an endless series of bugs.

Here's my thinking, with top-level bullets corresponding to things landing in the integration branch:
* Rewrite all commands that modify tasks to call purpose-specific task-modification commands like `task.setDescription` or `task.start` or `task.setAnnotation`.  Each such modification can write to the tdb2 directly.  Commands no longer interact with `tdb2` at all, nor have any notion of how the data is stored.
  * Optionally, we could introduce a "transaction" here that contains all of the modifications, and commits them together using either an RAII approach or an explicit `commit` method.
  * This will make the `permission` function a little bit tricky, so we'll need to find a way around that
  * This idea looks forward to making `Task` a public API that is exported in language bindings, so it must become a much more robust API surface.
* Redefine storage of non-string or compound task attributes as single attributes.  The `annotation_..` attributes reflect the ideal here, but `dependencies`, `tags`, the recurrence mask, and anything else which might be partially modified must be broken out.  Also, anything with a numeric value should be adjusted to use a string, but that's pretty easy.  All of this should be done with backward-compatibility shims (so, I guess this means a temporary F5?).
* Define a TDB3 format which has as its API a bunch of read-only methods and, as the sole way to make a modification, a method to add an operation to the DB.  Tasks will be returned in the form of `std::map<std::string, std::string>`.  It will store a sequence of un-synchronized operations, as well as the equivalent of a `map<uuid, map<string, string>>` containing all tasks and a `map<int, uuid>` containing the working set (tasks that have id's).
  * There was some discussion of how to handle undo in the context of synchronization in [TaskChampion](https://github.com/taskchampion/taskchampion/issues/92), without a really satisfying answer.  The best choice is probably to implement something simple -- perhaps dropping undo support completely to begin with -- and then improve the situation later. 
  * I don't think text is a good format for this sort of DB, and would prefer some kind of off-the-shelf key-value storage engine, or even sqlite.  That gets away from issues of quoting and unicode, and makes it clear that hand-editing the files is a _bad idea_ and will almost certainly result in data corruption.
  * Migration from TDB2 to TDB3 (and from TW 2.x to TW 3.x) would involve `task export` from v2 and `task import` into v3.  As with any write operation, `import` will generate a sequence of operations that are fed into an initially-empty DB.
* Once the operations-and-current-state model is in place, we can start working on synchronization.  I'd suggest using the same model as https://taskchampion.github.io/taskchampion/sync-model.html, and if we keep close enough to that model then we can actually use the existing rust sync server -- but the server is by far the simplest piece of the puzzle, so this isn't necessary.
* There's some additional clean-up work to support constant-space storage for replicas:
  * Support expiration of tasks by deleting them some (long) time after they are marked `status: deleted`
  * Support uploading snapshots of the DB state to the server so that the server can discard operations represented in those snapshots
  * Support downloading backups of the sync server's data to the client, so that a sync server can be re-populated in the event of data loss (this is important in the "free sync server" model a la freecinc).

This will be a major change, and is definitely not possible in 2.x.  I think the current sync model will be broken as of the second bullet point, and certainly at the third.  At a guess, if I'm working on it alone, it's a few years' work.

**Comment by djmitche** [comment]
For the first bullet point, maybe Task can continue to have no interaction with DB, but its methods can return an Operation which is then fed to the DB.  I've gotten a start on this [here](https://github.com/GothenburgBitFactory/taskwarrior/compare/2.6.0...djmitche:issue2507).

**Comment by djmitche** [comment]
OK, I'm stuck.  In the changes linked above,
```
  std::ostream &operator<<(std::ostream &os, std::optional<Operation> const &op) { 
      if (op.has_value()) {
          os << "here\n";
          return os << *op;                                                                                                                                                                                                                                                                       
      } else {
          return os << "nullopt";
      }   
  }
```
seems to recurse, and I can't figure out why.  `*op` has type `Operation`, not `optional<Operation>`.  And there's an `operator<<` defined for `Operation` in `Operation.cpp`.  What's going on?

**Comment by tbabej** [comment]
Looking into this now.

**Comment by tbabej** [comment]
@djmitche OK, I believe what is happening here is that the compiler is performing implicit conversion from `Operation` to `Optional<Operation>` becuase the

```c++
std::ostream &operator<<(std::ostream &os, Operation const &op);
```

defined in `Operation.cpp` is actually not found during linking. Once I copy the declaration of that method into `Operation.h`, like this:

```c++
...
  // only used for op_update
  std::optional<std::string> _property     {std::nullopt};
  std::optional<std::string> _value        {std::nullopt};
  time_t                     _timestamp    {0};

  void throw_if_not_update() const;
};

std::ostream &operator<<(std::ostream &os, Operation const &op);

#endif
...
```

the test no longer recurses:

```bash
./test/operation.t 
1..14
ok 1 - different ops not equal
ok 2 - same ops equal
ok 3 - create has correct type
ok 4 - op has correct uuid
ok 5 - delete has correct type
ok 6 - update has correct type
ok 7 - update get_property
ok 8 - update get_value
ok 9 - update get_timestamp is within a few seconds
ok 10 - update with remove has correct type
ok 11 - update get_value for remove
ok 12 - non-update get_property should fail
ok 13 - non-update get_value should fail
ok 14 - non-update get_timestamp should fail
ok 15 - create/create
not ok 16 - create/delete
# expected: (nullopt, here
there
)
ok 17 - hi
# 17 tests were run, but only 14 were planned.
# 16 passed, 1 failed, 0 skipped. 94.1% passed.
```

**Comment by djmitche** [comment]
As expected, it seems obvious now that you say it.  This declare / define distinction is taking me a while to remember :)

**Comment by tbabej** [comment]
No worries, happy to help! It definitely was not obvious at first sight :slightly_smiling_face: also, I'll get back to the thoughts above - I just need to ponder it properly, and free hacking time was rather scarce last couple of days.

**Comment by djmitche** [comment]
I think that the second point ("Redefine storage of non-string or compound task attributes") will need to come first.  That will need to address non-scalar properties like `tags` and `depends`.  It will also mean that everything is effectively string-typed, but I see that in practical terms that's already the case ("numeric", "date", and "duration" fields are all expressed as strings in F4).

[This](https://github.com/GothenburgBitFactory/taskserver/blob/1aaa22452c2c656c5cdb8e017368e0848e54555d/src/api.cpp#L305-L306) suggests that the task server will assume any unknown properties are strings, so no changes should be required to the sync server.  And, during a transition period, we could maintain both string-typed and non-scalar properties in parallel, to support different versions of taskwarrior sync'ing with each other.

**Comment by djmitche** [comment]
OK, that's done, next up would be dependencies.

As for the recurrence mask -- I think the current recurrence model already requires that recurrence only be calculated on one replica, which means that only one replica is writing to the mask property.  So we can probably leave that as-is.  Later, we can replace that with a recurrence model that is idempotent, so that all replicas can apply it and get the same results, and those results will merge naturally in the sync process.

**Comment by djmitche** [comment]
The currently-open issues here are about documentation, and sort of blocked on https://github.com/GothenburgBitFactory/tw.org/issues/282 -- which I'm happy to help with if pointed in the right direction :)

I think the other next step is to start to factor the Task struct into one where the `data` map is private, and access is made through methods similar to those in https://docs.rs/taskchampion/0.4.1/taskchampion/struct.Task.html / https://docs.rs/taskchampion/0.4.1/taskchampion/struct.TaskMut.html (the methods don't have to match exactly; the links are just illustrative of the API level).

I can get a start on that.

**Comment by djmitche** [comment]
I'm moving tracking for this project over to https://github.com/orgs/GothenburgBitFactory/projects/2.

**Comment by smemsh** [comment]
@djmitche I'm getting a 404 on that URL? Looks like there are "no public projects," is that by design?

**Comment by djmitche** [comment]
Ah, I didn't realize they could be private!  Fixed :)
