### ISSUE TITLE
Duration values can be mis-reported in the task info output

### ISSUE THREAD

**Issue by tbabej** [GothenburgBitFactory/taskwarrior#2514]
The following report is by @reportaman in #2512, Github UI unfortunately won't allow us to continue the conversation there (after I converted the issue to the discussion thread):

I have a task that I recently completed but forgot to change its status to start before starting to work on it. Given task was complete by the time I realized, I directly set the status to "complete". Then after reading the docs on task log, I wonder if I could log work for the completed task? I tried following two commands in sequence:

```
    task <uuid> start:21:00 rc.dateformat:hh:mm
    task <uuid> end:22:30 rc.dateformat:hh:mm
```

But when I look at the information of task, it shows start deleted (duration:0:00:53). Does this mean it logged only 53 seconds? Shouldn't the duration be from last start to last end?

```
Thu 24 Jun 2021 22:30:15 Start set to 'Fri 25 Jun 2021 21:00:00'.
Thu 24 Jun 2021 22:30:41 End changed from 'Thu 24 Jun 2021 22:23:50' to 'Fri 25 Jun 2021 22:30:00'.
Thu 24 Jun 2021 22:31:08 Start deleted (duration: 0:00:53).
```

**Comment by reportaman** [comment]
@tbabej Thanks! I tried steps in your test file. While the problem is fixed, the information printed in stdout is still incorrect. Check the times printed under "Tracking", and "Recorded" to stdout in teal blue color in screenshot below. The "Started", "Ended" times, and resultant duration are all based on ``current_timestamp``.

![Screen Shot 2021-06-26 at 2 34 59 PM](https://user-images.githubusercontent.com/71736629/123526379-4f5a1000-d68c-11eb-801e-4a85518afb88.png)

> As a sidenote, I guess the field "Entered" in task info mentions the first time the task was created right? I wonder if "Created" is more appropriate then?

**Comment by tbabej** [comment]
@reportaman As far as I can tell, that information is not generated by Taskwarrior. If I guess correctly, it looks like you're using Taskwarrior <> Timewarrior integration provided by [this Python hook](https://github.com/GothenburgBitFactory/timewarrior/blob/dev/ext/on-modify.timewarrior)?

In this case, the hook itself would need to be improved to correctly start the beginnings / ends of the inverval according to the `start:` and `end:` attributes, when provided.

**Comment by reportaman** [comment]
@tbabej Yep, I am using taskwarrior-timewarrior hook.

**Comment by tbabej** [comment]
Cool! [These lines](https://github.com/GothenburgBitFactory/timewarrior/blob/51d90114aa05be8f83ff24e838e3815f33e9aac1/ext/on-modify.timewarrior#L95) here are responsible for tagging and untagging the interval in timewarrior, so they would need to be slightly changed to take the starting time / ending time from the `old` and `new` dictionaries (which contain information about the state of the task before the modification and after the modification, see this part of the [hook API docs](https://taskwarrior.org/docs/hooks.html)).

I'd argue this actually would make a good default behaviour :slightly_smiling_face: if you'd like to contribute that!

**Comment by tbabej** [comment]
I guess the line 94 would also need to be changed to re-tag the interval not only when tags changed, but also when the `start` / `end` attributes changed? :thinking:

**Comment by reportaman** [comment]
@tbabej Can't commit at the moment to contribute code because I like to take things to the end, and understand them well to maintain. In job hunting mode right now...

**Comment by tbabej** [comment]
No worries :slightly_smiling_face: we'll see what we can do to improve this on our end. Thanks for opening the issue to track it - it's a relatively easy one, so I'm sure it won't gather dust for too long.
