### ISSUE TITLE
Taskwarrior / Taskserver file formats: Taskwarrior no longer supports file format 1

### ISSUE THREAD

**Issue by dgrabla** [GothenburgBitFactory/taskwarrior#2545]
Taskwarrior: 2.6.0 and/or 2.5.3 and 2.5.1

Taskserver: 1.1.0

* What command(s) did you run?

task sync

* What did you expect to happen?

It should sync the databases 

* What actually happened?

It returns an error:
Sync failed.  The Taskserver returned error: 500 Taskwarrior no longer supports file format 1, originally used between 27 November 2006 and 31 December 2007. at line 19881

Logs on the taskserver side:
```
2021-07-23 09:59:00 [234] 'sync' from 'dgrabla/dgrabla' using 'task 2.5.3' at XX.XX.XX.XX:9021
2021-07-23 09:59:00 [234] Client key '01a8c1d5-0900-43c7-b0db-xxxxxxxxxxx' + 155 txns
2021-07-23 09:59:00 [234] Loaded 19882 records
2021-07-23 09:59:00 [234] Branch point: 01a8c1d5-0900-43c7-b0db-xxxxxxxxx --> 19866
2021-07-23 09:59:00 [234] Taskwarrior no longer supports file format 1, originally used between 27 November 2006 and 31 December 2007. at line 19881
2021-07-23 09:59:00 [234] Serviced in 0.514830s
```

Restarting taskserver doesn't fix anything.

Was there a format change? Is there a way to update the database file to the new format?

* Paste the output of the ```task diag``` command.

```
task 2.5.3
   Platform: Linux

Compiler
    Version: 8.3.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      Built: Jul 23 2021 11:54:49
     Commit: 2f47226f9
      CMake: 3.13.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.7
 Build type: 

Configuration
       File: /home/dgrabla/.taskrc (found), 6344 bytes, mode 100644
       Data: /home/dgrabla/.task (found), dir, mode 40755
   TASKDATA: /home/dgrabla/.task
    Locking: Enabled
         GC: Enabled
    $VISUAL: nvim
     Server: XX.XXX.XXX:53589
         CA: /home/dgrabla/.task/ca.cert.pem, readable, 3654 bytes
Certificate: /home/dgrabla/.task/dgrabla.cert.pem, readable, 3660 bytes
        Key: /home/dgrabla/.task/dgrabla.key.pem, readable, 25300 bytes
      Trust: strict
    Ciphers: NORMAL
      Creds: dgrabla/dgrabla/************************************

Hooks
     System: Enabled
   Location: /home/dgrabla/.task/hooks
     Active: on-modify.timewarrior (executable)
   Inactive: 

Tests
   Terminal: 222x43
       Dups: Scanned 6361 tasks for duplicate UUIDs:
             Found duplicate 2a7834bc-97e5-4158-90f1-d9d605c8e80d
             Found duplicate e750ac3e-b693-4dd4-b0c1-443137fcc83e
             Found duplicate a47096d9-05d9-4b47-81bb-684536373837
             Found duplicate 577ff47c-eb20-409d-8ea8-a383fb86e425
             Found duplicate 624ad17f-90c4-488d-a1f7-b59a87b185a8
 Broken ref: Scanned 6361 tasks for broken references:
             No broken references found
```

**Comment by tbabej** [comment]
I think this must be a case of malformed data. The version 1 data file was used more than a decade ago and looked like this:

```
   [tags] [attributes] description\n
   X [tags] [attributes] description\n
```

for pending and completed tasks respectively. Without trying to dig down what exactly in the `backlog.data` is malformed, assuming you're local `task` works OK on one of the instnaces, I think the fastest way to fix this current situation would be to re-initialize the sync from scratch :thinking:

**Comment by dgrabla** [comment]
Thanks for your help @tbabej

As you suggested, I tried to do a 
```
> task sync init
```

but it still fails:
```
Sync failed.  The Taskserver returned error: 500 Taskwarrior no longer supports file format 1, originally used between 27 November 2006 and 31 December 2007. at line 19881
```

on the taskserver logs I get a
```
2021-08-02 19:36:14 [3] 'sync' from 'dgrabla/dgrabla' using 'task 2.5.3' at XX.XX.XX.XX:47770
2021-08-02 19:36:14 [3] Client key '' + 6371 txns
2021-08-02 19:36:14 [3] Loaded 19882 records
2021-08-02 19:36:16 [3] Taskwarrior no longer supports file format 1, originally used between 27 November 2006 and 31 December 2007. at line 19881
2021-08-02 19:36:16 [3] Serviced in 62.099143s
```

My `backlog.data` (on the client machine) is empty. 

```
[~/.task]> du backlog.data 
0	backlog.data
```

**Comment by dgrabla** [comment]
Also I have no clue why it detects file format 1, because I don't think I submit something that triggers that condition
```
[~/.task]> cat backlog.data pending.data completed.data undo.data | grep 'X \['
(Nothing)
```

![image](https://user-images.githubusercontent.com/1942073/127918909-53bcfa29-969a-4632-bea5-f73e09551557.png)

**Comment by sebu06** [comment]
Hi,
one reason could be an incomplete write command to the pending.data file. If one of the lines contains only [ but no ] at the end of the line, it will detect this as a version one entry - at least that's how I understand the code. You can check that by executing

```
grep -v "^\[.*\]$" pending.data
```

Best,
Sebastian

**Comment by dgrabla** [comment]
thx @sebu06 

I tried your idea:
```
> grep -v "^\[.*\]$" pending.data
(nothing)
> cat pending.data |  wc -l  
449
> cat pending.data | grep  "^\[.*\]$" | wc -l
449
```

They all seem to be ok.

**Comment by sebu06** [comment]
Hi,
yes - the pending data looks good - can you maybe check the completed.data as well? (same command) I forgot that that is synced with init as well. The backlog format looks good to me. If the completed.data also shows no problematic lines, I would move that file temporarily to a new folder and retry a task sync init with only the pending.data present. (at least that would help us locate the problem a little bit)

Best,
Sebastian

**Comment by tbabej** [comment]
Looking into this more I suspect the problem is not in the local copy of the data, but in the data file on the server.

**Comment by dgrabla** [comment]
@tbabej is right. The problem was on the server, on the `taskd-data/orgs/XXX/users/UUID/tx.data` file. This file was truncated for some reason, and the JSON of the last line could not be parsed. Once I deleted the tx.data file on the server, and I did a task sync init on the client, everything started to work again. 

Thanks.

**Comment by tbabej** [comment]
Glad you were able to work it out!
