### ISSUE TITLE
[TW-211] add possibility to assign a color.default value

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#255]
_Peter De Poorter on 2010-10-30T14:44:08Z says:_ 

 Goal: add a counterpart for the color.alternate value, called color.default, that allows following coloring setup: 

task 1 <== color.default
task 2 <== color.alternate
task 3 <== color.default
task 4 <== color.alternate
task 5 <== color.default

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-10-30T14:44:08Z
Modified: 2017-01-16T17:02:20Z
```

**Comment by pbeckingham** [comment]
Terminal settings will be the default color.
