### ISSUE TITLE
Create "task news" / "task tutorial" subcommand(s)

### ISSUE THREAD

**Issue by tbabej** [GothenburgBitFactory/taskwarrior#2551]
As evidenced in #2549, change in default behavior of `task` can meet users by surprise. While we keep ChangeLog / NEWS files in the repo, most users upgrade through their distribution packages and might not be aware of new features or caveats that come with upgrading.

Creating a `task news` subcommand would help us highlight new features in an interactive way.

**Comment by initBasti** [comment]
@tbabej That sounds great ! :+1:

**Comment by djmitche** [comment]
Maybe TW could have a "To see what's new in version x.y.z, run 'task news'" message?

**Comment by tbabej** [comment]
Good idea. We could make this a footnote that would appear i.e. on every Nth command. If you run the `task news` command, a configuration setting would be bumped to reflect the latest release notes that were displayed to the user, preventing the footnote to be displayed until the client is upgraded again.

**Comment by tbabej** [comment]
Implemented and released on 2.6.0 :slightly_smiling_face:

**Comment by initBasti** [comment]
Wow @tbabej ,
this is really awesome, the description is so detailed, with multiple examples and guidelines for migrating the old setup. :+1: 

Thank you all!

**Comment by tbabej** [comment]
Glad you like it @initBasti! Getting those descriptions readable (i.e. not too long) was more work than I'd like to admit :sweat_smile: !
