### ISSUE TITLE
Store `tags` and `depends` as distinct attributes

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#2553]
Pursuant to #2507, let's store `tags` and `depends` as distinct attributes, rather than `,`-separated strings.  This will allow merging of changes to these sets without overwriting.  The change is similar to how annotations are currently stored.

* `tags: "foo,bar"` becomes `tags_foo: "", tags_bar: ""`.
* `depends:uuid1,uuid2` becomes `depends_uuid1: "", depends_uuid2: ""`.

**Comment by tbabej** [comment]
Sounds good! I think we should do this internally in the TDB, while keeping the same `task export` format, which would result in keeping compatibility with other third-party tools in the TW ecosystem.

**Comment by djmitche** [comment]
Do you think this will break taskserver?

**Comment by tbabej** [comment]
The current implementation, yes, I believe so. Would there be another way how to achieve this? For example, could we introduce `addToSet` and `removeFromSet` operations? I guess in order to guarantee the same resulting attribute value (which is an array) no matter the order of the operations, we'd have to sort the elements in the array (i.e. tags sorted alphabetically).

**Comment by djmitche** [comment]
They're fundamentally sets, so if we just ignore order then there's no need to sort them.  Adding those operations makes the OT more complex, and leads to some strange questions like, how do you reconcile `Update(uuid, "tags", "foo")` and `AddToSet(uuid, "tags", "bar")`?  Or how do you apply `AddToSet` when the property is a string?  Those "shouldn't" happen, but OT is a lot easier to implement when every operation can commute smoothly with every other, and can be applied to any task state, and that any task state is valid -- then there are no error conditions to handle.  Adding those operations seems like polluting the future with a relic of the past.  And, I'm not sure how it would help here?  Would it just avoid having to solve this GH issue at all?

**Comment by tbabej** [comment]
I see. I was indeed under the impression that there is some validation of what operations can be applied on what attribute types, i.e. only set-related operations could be applied on set-related attributes. But I do see how that makes the whole system more complex.

I was coming from the direction of not breaking the current implementation of taskserver as we implement this, but perhaps another solution would be to setup a feature branch that we keep rebasing.

**Comment by djmitche** [comment]
I'm not totally sure it would break the taskserver -- it just gets some properties it doesn't recognize, right? (`tag_foo`, `depends_someuuid`)

**Comment by tbabej** [comment]
I think you're right. Though, the sync between a client that implements this feature and does not implement will be broken in the sense that updates to `tags` and `depends` would be mutually invisible for these two clients, unless `taskserver` does some reconciliation.

**Comment by djmitche** [comment]
I was thinking of maintaining `tags` for now, in `task` itself -- so, no need for a taskserver change.  On read, it would take the set of tags to be the union of all `tags_..` and the content of `tags`.  The result would be that removing a tag on an old TW version would not show that tag as removed on a new version.  But adding tags would sync properly.
