### ISSUE TITLE
Remove the `waiting` state, and consider any task with wait>now to be waiting

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#2554]
This would mean that all waiting task have status:pending, but are treated the same way by the filters.

The advantage to this is that the task need not be modified when its waiting time completes (which appears to happen in `gc`?) -- it just begins being included in filters.

**Comment by djmitche** [comment]
@tbabej do you mind assigning this and #2553 to me?

**Comment by tbabej** [comment]
Ugh, sorry for messing this up originally, I thought this already works :slightly_smiling_face: now you should be able to assign yourself

**Comment by djmitche** [comment]
Thanks!

Yeah, I was confused in another issue or discussion when I said that the +WAITING tag wasn't virtual.  It is virtual, but `status:waiting` is not.  It means that a tool displaying tasks without running `gc` doesn't show waiting tasks when their wait time arrives, until you happen to run `gc` for some other reason.

**Comment by tbabej** [comment]
Yep, that sounds all correct to me. I think we can squeeze this change even into the next release, it's a net improvement over current state of things.

**Comment by djmitche** [comment]
That's assuming I can implement it in a reasonable amount of time :)

**Comment by tbabej** [comment]
True! :slightly_smiling_face: I think this one could be relatively self contained, off the cuff, it _should_ be just extending the `Task::getStatus` to dynamically determine if the task is in the waiting status and getting rid of "wait removal" in `TF2::load_gc`. Hopefully I'm not too optimistic :sweat_smile: 

Feel free to ping me on the unlikely event you get stuck with something!

**Comment by djmitche** [comment]
Hm, #1918 is actually going to be more broken by this change, since a task is not "modified' when its wait time arrives.

In general, I think hooks are going to be difficult to square with synchronization.

**Comment by djmitche** [comment]
On reflection, I take that back.  As long as hooks execute on the replica where the action takes place, I think it's fine. This issue will be the last "automatic" change to a task that might occur in several replicas.

So this won't break #1918, but the resulting behavior may not be what users want, in the sense that there's no way to hook on a task losing the +WAITING tag.  But then, there's no hook for +MONTH either, so maybe that's OK.
