### ISSUE TITLE
Add `report.<name>.context` configuration variable

### ISSUE THREAD

**Issue by jakec-dev** [GothenburgBitFactory/taskwarrior#2560]
#### To request a feature...

* Clearly describe the feature.

Add the ability to ignore the currently active context when displaying reports.

For example, in .taskrc:

```
report.inbox.description=Inbox
report.inbox.columns=id,description
report.inbox.filter=status:pending (+inbox)
report.inbox.label=ID,Description

report.inbox.ignoreContext=true
```

* Clearly state the use case. We are only interested in use cases, do not waste time with implementation details or suggested syntax.

Regardless of what context I'm in, I want to be able to run my Inbox report and have it display every task. It doesn't matter if I'm in the office, at home, running errands - if I run the Inbox report then it should display ALL tasks.

For example, if I'm at \@home and have a task "review inbox items", then I can't just simply run `task inbox` to see my inbox. I first need to run `task context none` to exit out of my \@home context, then run `task inbox`, then when I'm finished I need to remember to switch back to my existing context with `task context home`. I don't want to add +inbox to my \@home context (e.g. `context.home=project.Personal or +home or +inbox` because I tend to have a lot of tasks with the +inbox tag and it would just pollute task list whenever I'm the \@home context.

Another use case is if you simply want to confirm that you've added something to your inbox before adding another +inbox task to avoid duplication. Having to switch out of your current context, check the inbox, then switch back to your context is quite time consuming and very annoying.

I don't want to add the +inbox tag to every context (i.e. a potential workaround that would display ALL tasks regardless of context) as it means it would pollute all my other reports. For example, if I run `task next` it would always display my inbox, which I don't want. I only want to ignore my current context for the Inbox report, and no others.

I understand that an easy option is to just run `task inbox rc.context:none` however having it as a report attribute instead has a few advantages:

1. You don't need to add `rc.context:none` every time you run the report or create shell aliases
2. It allows for easy integration with other tools, such as Taskwarrior-tui. These tools don't allow for adding `rc.context:none` as a parameter so there is currently no workaround for these tools. If this were handled in the reports themselves then these tools wouldn't need to adjust their code at all - it would work perfectly.

* Please see our notes on [How to request a feature](https://taskwarrior.org/docs/features.html)

Very nice article

**Comment by tbabej** [comment]
@jakec-dev I think this is a well-justified, great idea. This will be shipped as part of 2.6.0 (as I've now seen other people mention this use case as well - cc @mrossinek ).

**Comment by tbabej** [comment]
Added @jakec-dev among AUTHORS in d515326fbaf069dc975524b6db4dffd55e0c219f.

**Comment by tbabej** [comment]
Added @jakec-dev among AUTHORS in d515326fbaf069dc975524b6db4dffd55e0c219f.
