### ISSUE TITLE
report limit attribute removed without suitable replacement

### ISSUE THREAD

**Issue by smemsh** [GothenburgBitFactory/taskwarrior#2574]
while trying to understand why these show a different number of lines:
```
task next
task next | cat
```
I came across `limit:` so it's always possible to get the full count by adding `limit:0`, but that's apparently not available as a report attribute.  What if I always want a certain report to show all entries? There's no way to do this without *always* adding `limit:0` to the report invocation command line?!?

Then I found this commit (fa58c24) which removes this useful feature! This doesn't make much sense to me.  I want to configure the report, by adding a limit attribute, like all the other ways a report can be configured.  Why force the user to write a shell wrapper for each report they want to generate (or worse, type "limit:0" every time)? Is there some other way to do this?

Would a patch be accepted to add this back? Don't see any reason why it's not useful to have both a command line override, and a configured default for a certain report.  (For that matter, a global limit = 0 config option would be useful too, but at least it could be settable per-report like it was before)

**Comment by smemsh** [comment]
and btw, why does:
```task list | cat```
have a different default limit than:
```task next | cat```
??
where is this limit accessible to be set?

**Comment by tbabej** [comment]
There is a suitable replacement - the very commit you reference ( fa58c24 ) includes this change in the NEWS file, which explains how to replace the removed `report.X.limit` setting:

    - Removed support for 'report.X.limit', which can now be set in the report
      filter 'limit:N'.

This means you can just modify the `report.X.filter` variable to include the `limit:N` clause, for example my current definition of `report.list.filter` is

    report.list.filter=status:pending -WAITING

which needs to be changed to

    report.list.filter=status:pending -WAITING limit:0

**Comment by tbabej** [comment]
> and btw, why does:
> `task list | cat`
> have a different default limit than:
> `task next | cat`
> ??
> where is this limit accessible to be set?

This is exactly due to mechanism I am pointing out above. Try running the following command on your machine, which should provide you with filter definitions both for the `next` and `list` reports:

```
$ task show | grep -P 'report.(next|list).filter'
report.list.filter                 status:pending
report.next.filter                 status:pending limit:page
```

You'll notice that `next` has `limit:page` set as default in the filter definition, while `list` has no restriction to the amount of output produced.

**Comment by smemsh** [comment]
Thanks for explaining, I had read the NEWS fragment, but thought "in the report filter"  meant "in the report filter specified on the command line," I didn't realize that rc var `report.foo.filter` even existed.  Ok, RTFM.  I confirmed that it does work in the persistent filter definition and I have now learned a new cool feature of taskwarrior! Thanks.

The only caveat is, if I want to add `limit:0` to every filter, I have to redefine every one of them, and have them all in my config file (the whole definition, since there's no way to make it additive).  Perhaps adding it via context is better for that purpose though:

> any report command will have its result affected by the current active context

although that requires always using a context, and adding it to every context.  Which is probably easier than redefining all reports.

**Comment by tbabej** [comment]
The default limit should be "unlimited", so there is no need to explicitly specify `limit:0` eveywhere. Instead, you only need to remove the `limit:` clauses from filter definitions in reports that include that as the default. Looking into the filter definitions on the most recent release:

```
task show | grep -P 'report[^\s]+filter'
report.active.filter               status:pending and +ACTIVE
report.blocked.filter              status:pending +BLOCKED
report.blocking.filter             status:pending +BLOCKING
report.completed.filter            status:completed
report.list.filter                 status:pending
report.long.filter                 status:pending
report.ls.filter                   status:pending
report.minimal.filter              status:pending or status:waiting
report.newest.filter               status:pending or status:waiting
report.next.filter                 status:pending limit:page
report.oldest.filter               status:pending or status:waiting
report.overdue.filter              (status:pending or status:waiting) and +OVERDUE
report.ready.filter                +READY
report.recurring.filter            (status:pending or status:waiting) and (+PARENT or +CHILD)
report.timesheet.filter            (+PENDING and start.after:now-4wks) or (+COMPLETED and end.after:now-4wks)
report.unblocked.filter            status:pending -BLOCKED
report.waiting.filter              +WAITING
```

you can see that the only report that limits the amount of output is the default `next` report which does so via `limit:page` setting. So the only change you need to do is to run:

```
$ task config report.next.filter "status:pending"
Are you sure you want to change the value of 'report.next.filter' from 'status:pending limit:page' to 'status:pending'? (yes/no) yes
```

There should be no need to redefine all reports or set `limit:0` in the context filter.

**Comment by smemsh** [comment]
> you only need to remove the limit: clauses from filter definitions in reports that include that as the default

indeed, that's even easier, great!

P.S. I found that you can provide a substring to `task show` and it searches for all keys with that substring:

```
 $ task show filter | grep limit:
report.next.filter       status:pending limit:page
```

**Comment by tbabej** [comment]
Ah, true, good find! I completely forgot about that! :sweat_smile:
