### ISSUE TITLE
Support exporting given report as JSON, including sort order

### ISSUE THREAD

**Issue by kdheepak** [GothenburgBitFactory/taskwarrior#2575]
#### To report a bug...

* What command(s) did you run?

```
$ task rc.json.array=on rc.confirmation=off export status:pending -private limit:4
[
{"id":1,"description":"Move between tasks using 'j' and 'k'","entry":"20201021T065209Z","estimate":"30","modified":"20210214T151429Z","priority":"H","status":"pending","uuid":"0b11967d-9dae-4333-a137-c3b1e8a641d3","urgency":6},
{"id":2,"description":"Edit task in editor using 'e'","due":"20210213T070000Z","entry":"20201021T065230Z","estimate":"30","modified":"20210215T003558Z","priority":"L","status":"pending","uuid":"f5a18641-dc38-4ae1-80f0-588166a2aa44","urgency":12},
{"id":3,"description":"Filter tasks using '\/'","entry":"20201021T065245Z","estimate":"30","modified":"20201021T065245Z","status":"pending","uuid":"b3f9e124-64c2-4dc0-8351-9b2200e2863e","urgency":1.8},
{"id":4,"description":"Undo last action using u","entry":"20201021T065314Z","estimate":"30","modified":"20210214T231631Z","project":"wth","status":"pending","tags":["test","anothertag"],"uuid":"62c386dc-4403-4756-a56a-becad2538e77","urgency":2.8}
]
```

```
$ task status:pending -private limit:4
ID Age   P Project   Tag   Due   Description                                Urg
10 10mo    colortask COLOR -6mo  Support color for tasks based on yo... [2] 14.8
 7 10mo                    -6mo  Log tasks using 'l'                        13.8
 2 10mo  L                 -6mo  Edit task in editor using 'e'                12
 8 10mo                          Run custom shell command using '!'          9.8

26 tasks, 4 shown
```

I'm using the following data:

https://github.com/kdheepak/taskwarrior-testdata/blob/5eb138dd6ccba4934be8fe9098dfc64b7b1a5766/export.json

```
$ task import export.json
```

You can use the above command to replicate the issue.

* What did you expect to happen?

I expect the output of `task export $filter` to always mirror the output of `task $filter` in the order. Or at the very least, provide an option to run something like `task export-in-order $filter` to always mirror the output of `task $filter` in order.

* What actually happened?

Currently `export` always returns the tasks in order of their ID. `limit:4` returns the first 4 tasks in that order, i.e. task ids 1, 2, 3 and 4. This is not particularly useful.

* Paste the output of the ```task diag``` command.

```
task 2.5.3
   Platform: Darwin

Compiler
    Version: 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.59)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      Built: Feb 14 2021 10:37:05
      CMake: 3.19.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.15
 Build type: Release

Configuration
       File: /Users/USER/gitrepos/taskwarrior-tui/tests/data/.taskrc (found), 2604 bytes, mode 100644
       Data: /Users/USER/gitrepos/taskwarrior-tui/tests/data/.task (found), dir, mode 40755
     TASKRC: /Users/USER/gitrepos/taskwarrior-tui/tests/data/.taskrc
   TASKDATA: /Users/USER/gitrepos/taskwarrior-tui/tests/data/.task
    Locking: Enabled
         GC: Enabled
    $VISUAL: nvim
     Server:
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /Users/USER/gitrepos/taskwarrior-tui/tests/data/.task/hooks
             (-none-)

Tests
   Terminal: 120x30
       Dups: Scanned 33 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 33 tasks for broken references:
             Task be9c4324-bf96-4f15-904a-4bb8098500fe has nonexistent recurrence template f144d2ed-bb19-4b0e-90d3-cdc7dda44af1
```

#### To request a feature

* Clearly describe the feature.

It would be nice if `task export` resulted in the same list as the order specified by the report. Currently, `task export` returns a JSON list that is ordered based on the ID. For [`taskwarrior-tui`](https://github.com/kdheepak/taskwarrior-tui), I'm manually sorting that JSON list based on Urgency. However, users may want to use the sort defined in their report and it would be nice for `taskwarrior-tui` to leverage `taskwarrior`'s built in capability to sort the task list.

**Comment by kdheepak** [comment]
Even better would be the functionality to export a report. Currently, `task export` returns all tasks. It would be nice to have `task completed export` or `task next export` or any custom user report to be exportable as json.

**Comment by tbabej** [comment]
You could leverage a clever DOM query in order to get the same set of tasks exported, for example, for the next report:

```
task $(task _get rc.report.next.filter) export
```

however, this will not respect the sort order for the given report, as you correctly point out in this feature request.

**Comment by kdheepak** [comment]
Thanks for the suggestion that is a neat trick. 

For this feature, it appears that something like what is in `CmdCustom.cpp`:

https://github.com/GothenburgBitFactory/taskwarrior/blob/2.6.0/src/commands/CmdCustom.cpp#L63-L237

will need to be ported to `CmdExport.cpp`:

https://github.com/GothenburgBitFactory/taskwarrior/blob/2.6.0/src/commands/CmdExport.cpp#L50-L104

Is this something you'd be open to accepting a PR for? 

Some things are unclear to me though. For example, if someone does want to use `task export reportname`, and `reportname` contains `reportname.columns=...`, should the exported json only contain those `columns`? I imagine yes, however that would make JSON schema for exports non standard.

The only change I particularly would like right now is the sorting. Having additional information in the JSON is not a problem. For sorting, just the following needs to be ported to the `CmdExport.cpp`:

https://github.com/GothenburgBitFactory/taskwarrior/blob/2.6.0/src/commands/CmdCustom.cpp#L97-L120

Thoughts? I could also manually reimplement the sorting on my end but that seems less than ideal.

**Comment by tbabej** [comment]
For now, I'd ignore the `columns` setting. One of the reasons for that is the fact that columns can actually have different display formats, such as `scheduled.countdown` or `recur.indicator`. Also, while some attributes might not show up in the column output, they might still influence the task (for example, is the task waiting?) or its urgency.

Hence my vote goes to always exporting valid, full task JSON objects.

Now the UI implementation. There are couple of options in front of us:
1. Make `task export` behave more like a report, in particular implement the `export.filter` and `export.sort` options. This would allow one to mimic a project-specific report using DOM manipulation as:

```
task rc.export.filter=rc.report.next.filter rc.export.sort=rc.report.next.sort export
```

However, having `rc.export.filter` configuration variable seems dangerous, because it could affect how other third-party software sees TW database (i.e. if `export.filter` is set in the `.taskrc` documentation).

2. Support `task <filter> export [<report>]` syntax (the option that you're proposing). I think while being a bit less consistent, this is more readable and user friendly. I would accept PR that implements this option.

**Comment by kdheepak** [comment]
> However, having rc.export.filter configuration variable seems dangerous, because it could affect how other third-party software sees TW database (i.e. if export.filter is set in the .taskrc documentation).

Even if `export.filter` is set in `.taskrc`, if the third party software use `task rc.export.filter=...`, the command line option should override the option in `.taskrc`, correct? If that case I don't see it being particularly dangerous. Just my 2 cents. 

I'll start working on this and open a PR. We can iron out details in the PR too.

**Comment by kdheepak** [comment]
@tbabej I made a draft PR. What do you think about this implementation / user interface?
