### ISSUE TITLE
How to exclude blocked tasks from the report?

### ISSUE THREAD

**Issue by mrossinek** [GothenburgBitFactory/taskwarrior#2578]
I often find myself having multiple tasks which depend on each other. I can easily track this using the `depends:<task ID>` modifier.
However, I feel that the blocked task(s) often clutter my `next` report unnecessarily. Thus, I would like to suggest some sort of mechanism to specifies a task is _waiting_ on another task. I am not sure whether the `wait:` modifier should be overloaded but assuming that for the following example, this could look like this:
```
% task add "Task 1"
Created task 1.

% task add "Dependent task" depends:1
Created task 2.

% task next
ID Age   Deps Description    Urg
 1  1min      Task 1            8
 2 19s   1    Dependent task   -5

% task modify 2 wait:1
Modified task 2.

% task next
ID Age   Deps Description    Urg
 1  1min      Task 1            8
```

**Comment by tbabej** [comment]
Hey Max, nice to see you around!

You can actually achieve this by excluding blocked tasks from the report, i.e. by putting `-BLOCKED` into the filter definition of the report (or into your context).

**Comment by mrossinek** [comment]
Hi Thomas! Yes, it's been a while. I'm very busy lately :sweat_smile: 

Hm I had not thought of that :thinking: Is there a way to extend an existing report? E.g. add `-BLOCKED` to the `next` report? Or would I have to set up a custom report (e.g. `my_next`) and specify that under `default.command`?

**Comment by tbabej** [comment]
The built-in reports are defined in a very same way as the custom reports are, namely, you can modify their `columns`, `filter`, `labels` and `sort` order through configuration variables. For example, I modified my `report.next.filter` to be:

```
$ task show report.next.filter

Config Variable    Value                                
report.next.filter +PENDING -BLOCKING -WAITING type:task limit:20
  Default value    status:pending -WAITING limit:page   

Some of your .taskrc variables differ from the default values.
  These are highlighted in color above.
```

Which accidentally already includes the `-BLOCKING` we are talking about here :slightly_smiling_face:

**Comment by mrossinek** [comment]
Thanks! I guess this can be closed then :+1: 

(Although shouldn't that be `-BLOCKED` and not `-BLOCKING`? :thinking:)

**Comment by tbabej** [comment]
Ooops, good catch!
