### ISSUE TITLE
Importing malformed JSON task crashes TW

### ISSUE THREAD

**Issue by bharatvaj** [GothenburgBitFactory/taskwarrior#2580]
I was trying to import a json file into taskwarrior with `annotations` as string value.
```
~ $ cat heollo.json
{"status": "pending", "description": "Add RAWG watermark in flutter", "entry": "20200525T141441Z", "tags": ["thingstodo"], "uuid": "9d6b7b1b-e978-4ef9-9848-a55a0c223d7e", "annotations": "Google can you add **Made with \u2764 using RAWG** somewhere in the app. The API license mentions this", "project": "heollo"}
```
It would be better if it showed an error message instead of segfaulting
```sh
~ $ task import heollo.json
Importing 'heollo.json'
Segmentation fault: 11
```
Tried with the 2.6.0

**Comment by tbabej** [comment]
Nice reproducer! @bharatvaj is this something perhaps you'd like to contribute? I think this should be a relatively nice, self-contained fix.

**Comment by bharatvaj** [comment]
Sure! I'll give it a try

**Comment by tbabej** [comment]
Thanks for implementing this. You've been added to the AUTHORS file in 3471e1cdaa726edd7d8c4ca267036c2ad8ea2d81.
