### ISSUE TITLE
How to prevent task IDs from changing?

### ISSUE THREAD

**Issue by bashbunni** [GothenburgBitFactory/taskwarrior#2592]
### Description
I would like if the task IDs could be static. Currently when an item is completed or deleted, all of the items shift down to fill the space that was created. For example I have a list of five items, when item with ID=3 is removed then the item that had ID=4 now has ID=3 and the item at ID=5 is now at ID=4. 

### Use Case
This is not ideal because it means I need to list all tasks again after I complete or delete a task. It's time consuming.

**Comment by tbabej** [comment]
Hi @bashbunni,

if you really want to prevent task IDs from changing, you could set `gc=0` setting in your `~/.taskrc`. Note that this will disable the cleanup mechanism and thus your completed and deleted tasks will remain in the `pending.data` file. You could then force the cleanup manually by running `task rc.gc=1`

Another way would be to use (short) UUIDs instead of IDs - you can add a UUID column into your report, you can add `uuid.short` into your desired report's columns.

**Comment by djmitche** [comment]
Note that the renumbering only occurs when the list is performed.  For example, if `task list` shows tasks 3,4, and 5, and you run `task 3 done` then `task 5 done`, it will do what you want.

**Comment by jaker-dotcom** [comment]
I specify the rc.gc=0 for an updating list that doesn't change the ids. It runs whenever a task changes.

```alias entrtasknext="ls .task/pending.data | entr -c task  rc.gc=0 2>~/.task/taskerrormessages.txt"```

When I run a report somewhere else I have garbage collection run since gc=0 isn't defined in the taskrc. Having garbage collection every once and a while sure is a nice thing!

**Comment by smemsh** [comment]
I run with `rc.gc=off` also, then choose when to run GC, with a shell function:
```bash
taskgc ()
{
        (($(task +DELETED _unique uuid | wc -l))) &&
                task rc.bulk=0 +DELETED purge
        task rc.gc=on rc.verbose=nothing // list >/dev/null
}
```
(As said in earlier comments, only certain commands like running reports (ala `list`) will provoke garbage collection.)

It's a little strange there's no taskwarrior command to initiate GC, but the normal usage is to leave GC automatic, so this is not the target use case.  Personally I don't like the ID numbers changing except when I explicitly "know" it happened, by manually invoking GC.

(And for the deleted-purge, not everyone will like that part, YMMV.)

**Comment by bashbunni** [comment]
Thank you! You can close this issue if you'd like :)
