### ISSUE TITLE
Record start and stop times for tasks

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#2596]
Currently, when a task starts we add a `start: <timestamp>` property.  When the task stops, we delete the property.

One disadvantage of that approach is that the start and stop time is not preserved.  This makes time-tracking (how much time was spent on a task) difficult.

An alternative is to store each "start" as `start_<start_time>: "x"`, and mark the corresponding stop by updating it to `start_<start_time>: <stop_time>`.

This could be done compatibly, much like how we did dependencies and tags.

If we do this, it'd be great to get it done before https://github.com/GothenburgBitFactory/tw.org/issues/212 so that it can become the documented task-storage format.

WDYT?

**Comment by djmitche** [comment]
When we shift to an operations-based model for task storage, I'd like to avoid having to store operations after they have been sync'd to the server.  That means that functionality currently using the undo log needs to either go away or be implemented another way.

The `task undo` command obviously uses this functionality, but there are plans to implement that as a part of locally-stored operations.

The other major piece using the undo log is `task info`, which shows a task's modification history:
```
Date                Modification
2021-08-03 16:44:23 Priority changed from 'M' to 'L'.
2021-08-09 16:22:51 Start set to '2021-08-09 16:22:51'.
2021-08-09 16:39:03 Start deleted (duration: 0:16:12).
                    Tags set to 'inprogress'.
```

The proposal in this issue would allow us to continue calculating those durations without the undo log.  What to do about the remainder of the history is a different question.

**Comment by jaker-dotcom** [comment]
I don't seem to understand the problem. I mean it's pretty easy to get the total time from the "Start deleted (duration ...)" part and there even is a script for that on the taskwarrior page. Also you could use timewarrior which integrates neatly afaik. 
Only advantage I can see is that you could modify these times in retrospect which I think isn't possible now.

**Comment by djmitche** [comment]
That information comes from the undo log.  #2507 will entail removing the undo log, meaning that such information will no longer be available. So the idea here is to continue to provide that functionality.

**Comment by sebu06** [comment]
I understand the wish to have the time spent recorded, but maybe it would be an option for you to use timewarrior for that - you can simply link those two using a hook.

**Comment by djmitche** [comment]
I apologize if the context of this issue wasn't clear: in #2507, I'm proposing changing the entire sync backend.  A consequence of doing so would be the loss of the undo information, on which the durations are based.  This issue is proposing an alternative way to store that information.

**Comment by tbabej** [comment]
What I was thinking we could do is to replace both `backlog.data` and `undo.data` with an append-only Operations log, where operations have, alongside the regular content (modification, uuid and such) two additional attributes:
* the "action uuid", where operations generated by the same user action (i.e. bulk modification) would share an identifier
* the "synced" flag which would separate synced (sent to the server) operations from the unsynced

Then the following properties should hold:
* User should be able to `undo` unsynced user actions by simply removing all the operations belonging to that user action from the log
* `undo` for synced operations would not be supported

A constant size requirement could be achieved by trimming the synced parts of the operations log, per user settings (i.e. operations older than a year).

This means that the operations log could be used as a source of history of modifications as well, serving the need that the `undo.data` serves currently.

**Comment by djmitche** [comment]
That sounds great, and in line with what we've discussed in [taskchampion](https://github.com/taskchampion/taskchampion/issues/92).

Given that, it seems we don't need to make the change proposed in this issue -- is that your view too?

**Comment by tbabej** [comment]
I would agree. I'll add the above as a comment to the Operations RFC!
