### ISSUE TITLE
[EX-28] movie.method plug-in

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#26]
_David Patrick on 2013-01-09T03:32:18Z says:_ 

 This is an idea for a specialized use of taskwarrior, in the scheduling of movie production, scene-by-scene, tracking locations, characters, props, etc, which is really just a gigantic task-list.
The traditional tool, used since the days of Cecil B. DeMille, was and is a "stripboard".

![Imported image](http://taskwarrior.org/attachments/download/582/stripboard.jpg)

see: http://en.wikipedia.org/wiki/Production_strip
or http://www.homefilmschool.com/2008/10/shooting-schedule.html
in-depth: http://www.solutioneers.net/cinema/preproduction.htm 

With a great-big set of UDAs, using established color-rules, a set of custom reports, taskwarrior would make an excellent production-scheduling tool, fast and flexible. Task management, movie-style.
It would be an excellent example of the versatility of UDAs, plug-in.method architecture, virtual-tags, and task syncing capabilities. 

any programmer/ filmmakers out there? I think so too.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-01-09T03:32:18Z
Modified: 2014-02-09T02:43:23Z
```

**Comment by pbeckingham** [comment]
No plans to implement.
