### ISSUE TITLE
"task <IDs of several tasks> modify priority:L" doesn't work with just [Enter] instead of typing "yes"

### ISSUE THREAD

**Issue by yavnest** [GothenburgBitFactory/taskwarrior#2605]
As the titles says, "task <IDs of several tasks> modify priority:L" won't work with just [Enter] instead of typing "yes", 
even though (I think) it's supposed to. It says it will perform the requested modification to the task, but doesn't go forward to the next one, instead it just repeats the confirmation request ad infinitum!

```
$ task 5 8 9 10 modify priority:L
  - Priority will be set to 'L'.
Modify task 5 'Find Python exercises'? (yes/no/all/quit)   [[just pressing Enter here]]
  - Priority will be set to 'L'.
Modify task 5 'Find Python exercises'? (yes/no/all/quit)    [[just pressing Enter here]]
  - Priority will be set to 'L'.
Modify task 5 'Find Python exercises'? (yes/no/all/quit)    [[just pressing Enter here]]
  - Priority will be set to 'L'.
Modify task 5 'Find Python exercises'? (yes/no/all/quit)    [[just pressing Enter here]]
  - Priority will be set to 'L'.
Modify task 5 'Find Python exercises'? (yes/no/all/quit)    [[just pressing Enter here]]
  - Priority will be set to 'L'.
Modify task 5 'Find Python exercises'? (yes/no/all/quit) y
Modifying task 5 'Find Python exercises'.
Modify task 8 'My second task'? (yes/no/all/quit) yes
Modifying task 8 'My second task'.

  - Priority will be set to 'L'.
Modify task 9 'My third task'? (yes/no/all/quit) yes
Modifying task 9 'My third task'.

  - Priority will be set to 'L'.

(... etc ...)

```
If you do just the pressing Enter thing several times, and then write "quit", NOTHING will have changed at all, even though it said it'd change the priority.

-----------------------------------

```
$ task diag

task 2.5.3
   Platform: Linux

Compiler
    Version: 10.2.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      Built: Feb  2 2021 23:45:39
      CMake: 3.19.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.7.0
 Build type: 

Configuration
       File: /home/acer/.taskrc (found), 1411 bytes, mode 100644
       Data: /home/acer/Dropbox/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $VISUAL: vim
     Server: 
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/acer/Dropbox/.task/hooks
             (-none-)

Tests
   Terminal: 210x42
       Dups: Scanned 67 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 67 tasks for broken references:
             No broken references found
```

**Comment by TuringZauber** [comment]
You need to type `yes/no/all/quit`. Not performing mass-edits and allowing via the return key is the intended way. More people press return by accident then typing `all` by accident.

**Comment by linuxcaffe** [comment]
I've always preferred confirmation prompts with a default, on hitting ENTER, as in
`Should we consider prompt defaults? Y/n` or for the example above
`Yes/no/all/quit`
and prompts with more sweeping consequences should default to `y/N`

**Comment by jaker-dotcom** [comment]
> It says it will perform the requested modification to the task
I think you misinterpret the line `- Priority will be set to 'L'.` as to be a confirmation that follows your "confirmation" via enter key. But really it is just re-posing the question since your input is considered invalid.
