### ISSUE TITLE
Env variables not expanding in taskrc with xonsh shell

### ISSUE THREAD

**Issue by diego-rapoport** [GothenburgBitFactory/taskwarrior#2618]
My taskrc does not expand the environment variable $XDG_CONFIG_HOME. You can see it in the Hooks part of my diagnostics, which is written `hooks.location=$XDG_CONFIG_HOME/task/hooks/` in my taskrc.

And that's the output from my terminal:
```
@ echo $XDG_CONFIG_HOME
/home/dinhego/.config
```
`task diag`
```
task 2.6.0
   Platform: Linux

Compiler
    Version: 11.1.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.21.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.7.2
 Build type:

Configuration
       File: /home/dinhego/.config/task/taskrc (found), 2066 bytes, mode 100644
       Data: /home/dinhego/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $VISUAL: nvim
     Server: freecinc.com:53589
         CA: /home/dinhego/.task/freecinc_b802ac1b.ca.pem, readable, 3755 bytes
Certificate: /home/dinhego/.task/freecinc_b802ac1b.cert.pem, readable, 3502 bytes
        Key: /home/dinhego/.task/freecinc_b802ac1b.key.pem, readable, 17743 bytes
      Trust: strict
    Ciphers: NORMAL
      Creds: FreeCinc/freecinc_b802ac1b/************************************

Hooks
     System: Enabled
   Location: /task/hooks/
             (-none-)

Tests
   Terminal: 71x41
       Dups: Scanned 138 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 138 tasks for broken references:
             No broken references found
```

**Comment by tbabej** [comment]
Can we get the output of `task _get rc.hooks.location`, `task show hooks.location` and `cat /home/dinhego/.config/task/taskrc | grep hooks.location`?

**Comment by diego-rapoport** [comment]
```
@ task _get rc.hooks.location
/task/hooks/
```
```
@ task show hooks.location

Config Variable Value
hooks.location  /task/hooks/

Your .taskrc file contains these unrecognized variables:
  hooks.location

These are highlighted in color above.
```
```
@ cat /home/dinhego/.config/task/taskrc | grep hooks.location
hooks.location=$XDG_CONFIG_HOME/task/hooks/
```

**Comment by tbabej** [comment]
That looks all correct. This is a weird stretch, but can we check if `task` actually gets this as an environment variable? We could run a long-running task command, i.e. `task +LATEST edit` and then:

```
$ ps -aux | grep "task +LATEST edit"
tbabej   2945326  0.0  0.0  20984 13940 pts/1    S+   16:19   0:00 task +LATEST edit
tbabej   2995096  0.0  0.0 221528   852 pts/6    R+   16:22   0:00 grep --color=auto task +LATEST edit
$ cat /proc/2945326/environ | tr '\0' '\n' | grep XDG
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_CONFIG_HOME=/home/tbabej/.config
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=i3
XDG_SESSION_TYPE=x11
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/tbabej
XDG_CURRENT_DESKTOP=i3
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_VTNR=1
XDG_SESSION_ID=2
XDG_RUNTIME_DIR=/run/user/1000
XDG_DATA_DIRS=/home/tbabej/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
```

**Comment by diego-rapoport** [comment]
It seems I don't have the process itself. Not at least as it shows on yours.
I also tried to reboot, but nothing has changed.

```
@ ps -aux | grep "task +LATEST edit"
dinhego     5315  0.0  0.0   6528  2332 pts/1    S+   18:11   0:00 grep --color=auto task +LATEST edit

@ cat /proc/5315/environ | tr '\0' '\n' | grep XDG
cat: No such file or directory: /proc/5315/environ
```

**Comment by tbabej** [comment]
Do you keep `task +LATEST edit` running in a different terminal while executing the commands above? My instruction were not the clearest, so just making sure :sweat_smile:

To recap, this is what needs to be done for us to diagnose what is the content of the environment the `task` process gets:
1. Open a terminal and run `task +LATEST edit`, keep the editor window open (do _not_ finish editing the task)
2. Open a new terminal and run the `ps` and `cat` commands above with the PID of the running task process

**Comment by diego-rapoport** [comment]
Now that's make a lot more sense lol 😆.
Yeah, the env variables aren't there and this is the output:
```
@ cat /proc/13852/environ | tr '\0' '\n' | grep XDG
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_TYPE=x11
XDG_VTNR=2
```

**Comment by tbabej** [comment]
Okay, so there's the problem. I'm not sure why `task` is not getting these environment variables, but at this point we have determined this is setup-dependent (if I try the same exact settings, the expansion works as expected).

What happens if you run some of the following?
1. `env | grep XDG`
2. `bash -c 'echo $XDG_CONFIG_HOME'` (single quotes)
3. `echo $XDG_CONFIG_HOME`

**Comment by diego-rapoport** [comment]
Only the first option doesn't get the variable.
Perhaps it's something about me using xonsh instead of bash itself? Because inside bash I don't have `$XDG_CONFIG_HOME` set, at least it doesn't show me anything with `echo` neither `env | grep XDG`. But if I run the second command inside xonsh it does have it.

**Comment by tbabej** [comment]
Does everything work as expected, if you run `bash` instead of `xonsh`?

```
@ bash
$ export XDG_CONFIG_HOME=/home/dinhego/.config
$ task diag
```

and if you omit the explicit export?

```
@ bash
$ task diag
```

**Comment by diego-rapoport** [comment]
Omitting the export doesn't work, but the other way does.
Even if I use the export in bash and get back to xonsh I still don't have the right location for hooks.

**Comment by tbabej** [comment]
Understood. Well, at this point we have determined this is a `xonsh` issue, as this works in a different shell just fine :crying_cat_face:  As this is not taskwarrior specific, I'd suggest trying to get support with the folks at `xonsh`?

**Comment by diego-rapoport** [comment]
Yeah, sure!
Thanks for your time and great support helping me with this!
