### ISSUE TITLE
'stable' tag shadows 'stable' branch

### ISSUE THREAD

**Issue by smemsh** [GothenburgBitFactory/taskwarrior#2621]
now that 2.6.0 has been promoted and we have changed branch names to `stable` and `develop`, it seems that there's also a stable tag which shadows the stable branch:

```
 $ git tag -l | grep stable
stable

 $ git checkout stable
HEAD is now at db76a15ba changelog: mark 2.6.0 as current release

 $ git rev-parse --symbolic-full-name stable
refs/tags/stable

 $ git branch -a | grep stable
* (HEAD detached at stable)
  remotes/origin/stable
```
guessing we want to delete the tag? right now they are pointing to the same commit:
```
 $ for ref in remotes/origin/stable refs/tags/stable
   do git log --oneline -1 $ref; done
db76a15ba changelog: mark 2.6.0 as current release
db76a15ba changelog: mark 2.6.0 as current release
```

**Comment by tbabej** [comment]
Good catch! I really am unsure how it got pushed, but I removed it now.

**Comment by smemsh** [comment]
one problem is, people who already pulled will have to delete the tag manually from their checkout, as server-side tag deletes are not propagated on pull... not sure of a good solution here.

**Comment by smemsh** [comment]
Perhaps, nothing can be done about people that pulled already.   Can confirm that tag is removed upstream:

```
 $ git ls-remote https://github.com/GothenburgBitFactory/taskwarrior | grep stable
db76a15ba5d109080b9cfd2dfbf3c160ab4145cc        refs/heads/stable
```

**Comment by tbabej** [comment]
Just for the record, if you've cloned before this was fixed, there are two options:
1. recloning from scratch
2. running `git tag -d stable`

**Comment by lauft** [comment]
Git has the option to prune tags:
````
git fetch --prune --prune-tags origin 
````
However, this will also delete all local tags not found on the remote. 

👉 https://git-scm.com/docs/git-fetch#_pruning

**Comment by tbabej** [comment]
Thanks for reminding me of that @lauft :100:

That definitely cleaned quite a few old feature branches I should have removed long time ago :slightly_smiling_face:

**Comment by tbabej** [comment]
For the record, @lauft 's solution is the best for people that have cloned the repo in the past (i.e. more than a year ago), since a lot of old tags and branches were cleaned up on the remote. Currently the list of tags is very consistent, and tags are only used to denote commit hashes of the released versions:

```
$ git tag
v0.9.4
v0.9.7
v0.9.8
v0.9.9
v1.0.0
v1.0.1
v1.1.0
v1.2.0
v1.3.0
v1.3.1
v1.4.0
v1.4.1
v1.4.2
v1.4.3
v1.5.0
v1.6.0
v1.6.1
v1.7.0
v1.7.1
v1.8.0
v1.8.1
v1.8.2
v1.8.3
v1.8.4
v1.8.5
v1.9.0
v1.9.1
v1.9.2
v1.9.3
v1.9.4
v2.0.0
v2.1.0
v2.1.1
v2.1.2
v2.2.0
v2.3.0
v2.4.0
v2.4.1
v2.4.2
v2.4.3
v2.4.4
v2.5.0
v2.5.1
v2.5.2
v2.5.3
v2.6.0
```
