### ISSUE TITLE
Tags and dependencies appear as orphaned UDAs

### ISSUE THREAD

**Issue by smemsh** [GothenburgBitFactory/taskwarrior#2622]
After upgrade from a July-ish `2.6.0` branch to the new `stable` (ie 2.6.0 release), all my tasks that have tags or dependencies are now +ORPHAN, this probably has to do with #2553.  I've noticed that all my `pending.data` lines that had
```
depends:uuid1,uuid2
```
are now *also* written as
```
dep_uuid1:"x"
dep_uuid2:"x"
```
and same for tags which are now `tags_<tagname>:"x"` in addition to the old `tags:<tagname1>,<tagname2>`.

`task udas` shows every `tag_foo` and `dep_bar` as an Orphan UDA, and all issues that had tags or dependencies are +ORPHAN.

Was this a failed conversion? Was the old encoding method supposed to be erased when the new one was put in place? I tried doing this manually, but the tasks were still seen as +ORPHAN.  For now I have removed these new encodings manually in text editor and reverted to my older 2.6 version of `taskwarrior`.

**Comment by tbabej** [comment]
For the current release, both versions of encodings are supposed to be present as a transition period - we will remove the older one in 3.0. Hence you don't need to modify the data files to remove one of them -  in fact, if you do any task modification to any of the tasks, the `dep_<uuid>` and `tag_<name>` attributes should be regenerated again.

That said, it's definitely a bug that we're putting `+ORPHAN` virtual tag and that these attributes are not recognized as internal in the output of `task udas`.
