### ISSUE TITLE
new 2.6.0 release breaks taskw python lib after apparent change in cli parsing semantics

### ISSUE THREAD

**Issue by smemsh** [GothenburgBitFactory/taskwarrior#2623]
Seems to be a change in 2.6.0 since mid-July (specifically 607baa081..stable), which breaks [taskw](https://github.com/ralphbean/taskw) library.  This comes down to change in behavior for the following:
```
 $ task id:1 export | jq '.[]["id"]'
1

 $ task export id:1 | jq '.[]["id"]'
Unable to find report that matches 'id:1'.
```
old one worked both ways.  When taskw library constructs command line for 'export' command to interface with taskwarrior, it ends up with this execution:
```
-> raise TaskwarriorError(command, stderr, stdout, proc.returncode)
(Pdb) pp command
[b'task',
 b'rc.verbose=new-uuid',
 b'rc.json.array=TRUE',
 b'rc.confirmation=no',
 b'rc.dependency.confirmation=no',
 b'rc.recurrence.confirmation=no',
 b'export',
 b'id:1']
 (Pdb) p proc.returncode
2
(Pdb) p stderr
b"Unable to find report that matches 'id:1'."
```
if this is a bug in taskw lib, I'll make an issue over there, but CLI semantics have changed.

**Comment by tbabej** [comment]
The report is on spot with respect to the cause. Technically, filters should always precede the command, but I knew taskw was relying on this behaviour and attempted to pre-emptively fix this, but unfortunately `taskw` is not being maintained actively enough for the PR to be merged prior to 2.6.0.

See https://github.com/ralphbean/taskw/pull/152 for the fix, or just install from my branch using: `pip3 install -U git+git://github.com/tbabej/taskw@develop`

Ultimately I'd recommend switching to `tasklib` which is now under the umbrella of GothenburgBitFactory if possible, maintaining two Python libraries seems like a bit of too much overhead for the community.

**Comment by smemsh** [comment]
Thanks, looks like ralphbean has merged it just now, I'll use taskw devel branch for the moment then.

I was not aware of tasklib, probably because taskw shows up so much higher in pypi search results for 'taskwarrior'.  Good to know, thanks for the tip, I will check it out instead.

**Comment by tbabej** [comment]
Yep, spoke to soon, ralphbean/taskw#152 is now merged thanks to @coddingtonbear !
