### ISSUE TITLE
How do I set a null write context definition?

### ISSUE THREAD

**Issue by dkasak** [GothenburgBitFactory/taskwarrior#2628]
2.6.0 added the concept of `write` contexts, which makes that context get added to tasks when they are created while the context is active. But for some contexts, I don't want anything added at all. How do I achieve this?

I tried unsetting `context.MYCONTEXT.write` using

    task config context.MYCONTEXT.write ""

But that just makes it copy `context.MYCONTEXT.read`, which isn't a valid modification.

**Comment by tbabej** [comment]
You want your `~/.taskrc` to look like this:

```
context.work.read=+work
context.work.write=
```

So editing the `~/.taskrc` file manually should work as well :slightly_smiling_face:

**Comment by dkasak** [comment]
Ah, it seems like I forgot to migrate that context to the new style so it looks liked this instead

    context.work=+work
    context.work.write=

I guess the migration process could've just converted

    context.work = DEFINITION

to

    context.work.read = DEFINITION
    context.work.write = DEFINITION

automatically, since this is what the effect of upgrading to the new version is anyway?

In any case, it works fine now.

**Comment by tbabej** [comment]
There is currently no automatic migration process that happens upon upgrade (we did not want to auto-modify the configuration files in general). However, if you were to re-define the context, the old-style would get removed:

```
[warrior@tw-v2.6.0 ~]$ task context list

Name Type  Definition Active
work read  +work      yes   
     write +work      yes

[warrior@tw-v2.6.0 ~]$ task context define work +work
Are you sure you want to add 'context.work.read' with a value of '+work'? (yes/no) yes
Are you sure you want to change the value of 'context.work.write' from '' to '+work'? (yes/no) no 
Context 'work' defined (read only). Use 'task context work' to activate.
[warrior@tw-v2.6.0 ~]$ task context list

Name Type  Definition Active
work read  +work      yes   
     write            yes
```

I think this does uncover a minor bug however, in your case with

```
context.work=+work
context.work.write=
```

in taskrc, the empty write context should override the "old-style derived write context". I'll spin up a separate issue for this.
