### ISSUE TITLE
Cannot build on Cygwin

### ISSUE THREAD

**Issue by esemplare** [GothenburgBitFactory/taskwarrior#2632]
Not sure if Cygwin is still supported... I noticed that the `-std=gnu++0x` was removed some time ago. Below are the changes required for me to build.

#### Build Environment:

        libgc1                   8.0.4-1
        libltdl7                 2.4.6-7
        libunbound-common        1.6.2-1
        libgnutlsxx28            3.6.9-1
        libisl23                 0.24-2
        libmpc3                  1.2.1-2
        binutils                 2.37-2
        cygwin-devel             3.2.0-1
        libatomic1               11.2.0-1
        libgomp1                 11.2.0-1
        libquadmath0             11.2.0-1
        w32api-headers           9.0.0-1
        windows-default-manifest 6.4-1
        libjsoncpp24             1.9.4-1
        librhash0                1.4.1-1
        libuv1                   1.41.0-1
        libgmpxx4                6.2.1-2
        libssl1.0                1.0.2t-1
        liblzo2_2                2.10-2
        libpkgconf3              1.6.3-1
        libguile2.2_1            2.2.7-1
        w32api-runtime           9.0.0-1
        libevent2.0_5            2.0.22-1
        libarchive13             3.5.2-1
        pkgconf                  1.6.3-1
        make                     4.3-1
        gcc-core                 11.2.0-1
        libunbound2              1.6.2-1
        cmake                    3.20.0-1
        pkg-config               1.6.3-1
        gcc-g++                  11.2.0-1
        libgnutls-dane0          3.6.9-1
        libgmp-devel             6.2.1-2
        libtasn1-devel           4.14-1
        libp11-kit-devel         0.23.20-1
        libuuid-devel            2.33.1-2
        libnettle-devel          3.4.1-1
        libgnutls-devel          3.6.9-1

* What command(s) did you run?

      $ git clone --recursive -b 2.6.0 https://github.com/GothenburgBitFactory/taskwarrior.git
      $ cd taskwarrior
      $ cmake -DCMAKE_BUILD_TYPE=release .
      $ make
* What did you expect to happen? Taskwarrior to successfully compile
* What actually happened? Compilation failed.

        [ 27%] Building CXX object src/CMakeFiles/libshared.dir/libshared/src/FS.cpp.o
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp: In member function ‘std::string Path::realpath() const’:
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp:160:22: error: ‘::realpath’ has not been declared
          160 |   char *result_c = ::realpath (_data.c_str(), NULL);
              |                      ^~~~~~~~
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp: In member function ‘bool File::open()’:
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp:473:14: error: ‘fileno’ was not declared in this scope; did you mean ‘d_fileno’?
          473 |         _h = fileno (_fh);
              |              ^~~~~~
              |              d_fileno
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp: In member function ‘void File::close()’:
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp:507:18: error: ‘fileno’ was not declared in this scope; did you mean ‘d_fileno’?
          507 |       if (fsync (fileno (_fh)))
              |                  ^~~~~~
              |                  d_fileno
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp: In member function ‘void File::truncate()’:
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp:673:9: error: ‘ftruncate’ was not declared in this scope; did you mean ‘truncate’?
          673 |     if (ftruncate (_h, 0))
              |         ^~~~~~~~~
              |         truncate
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp: In member function ‘bool Directory::remove_directory(const string&) const’:
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp:974:25: error: ‘DT_UNKNOWN’ was not declared in this scope
          974 |       if (de->d_type == DT_UNKNOWN)
              |                         ^~~~~~~~~~
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp:981:24: error: ‘DT_DIR’ was not declared in this scope
          981 |           de->d_type = DT_DIR;
              |                        ^~~~~~
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp:983:25: error: ‘DT_DIR’ was not declared in this scope
          983 |       if (de->d_type == DT_DIR)
              |                         ^~~~~~
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp: In static member function ‘static std::string Directory::cwd()’:
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp:1016:15: error: ‘get_current_dir_name’ was not declared in this scope
         1016 |   char *buf = get_current_dir_name ();
              |               ^~~~~~~~~~~~~~~~~~~~
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp: In member function ‘void Directory::list(const string&, std::vector<std::basic_string<char> >&, bool)’:
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp:1082:38: error: ‘DT_UNKNOWN’ was not declared in this scope
         1082 |       if (recursive && de->d_type == DT_UNKNOWN)
              |                                      ^~~~~~~~~~
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp:1089:24: error: ‘DT_DIR’ was not declared in this scope
         1089 |           de->d_type = DT_DIR;
              |                        ^~~~~~
        [REDACTED]/taskwarrior/src/libshared/src/FS.cpp:1091:38: error: ‘DT_DIR’ was not declared in this scope
         1091 |       if (recursive && de->d_type == DT_DIR)
              |                                      ^~~~~~
        make[2]: *** [src/CMakeFiles/libshared.dir/build.make:132: src/CMakeFiles/libshared.dir/libshared/src/FS.cpp.o] Error 1
        make[1]: *** [CMakeFiles/Makefile2:409: src/CMakeFiles/libshared.dir/all] Error 2
        make: *** [Makefile:156: all] Error 2

* Steps to Resolve:
  * Force compiler standard to gnu++[17|0x]

        diff --git a/cmake/CXXSniffer.cmake b/cmake/CXXSniffer.cmake
        index a2d0ba222..07c06cdae 100644
        --- a/cmake/CXXSniffer.cmake
        +++ b/cmake/CXXSniffer.cmake
        @@ -32,6 +32,7 @@ elseif (${CMAKE_SYSTEM_NAME} STREQUAL "GNU")
           set (GNUHURD true)
         elseif (${CMAKE_SYSTEM_NAME} STREQUAL "CYGWIN")
           set (CYGWIN true)
        +  set (_CXX14_FLAGS "-std=gnu++17")
         else (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
           set (UNKNOWN true)
         endif (${CMAKE_SYSTEM_NAME} MATCHES "Linux")

  * Patch libshared FS.cpp to define `_GNU_SOURCE` since `get_current_dir_name` is conditional based on `#if __GNU_VISIBLE` in `/usr/include/sys/unistd.h`. The `get_current_dir_name` function is found by CMake so it gets defined during the `check_function_exists` call (note documentation mentions check_function_exists only verifies linking, not that the function is declared in the headers. I suppose this could be changed to `check_symbol_exists` if you are against adding the _GNU_SOURCE definition.

        diff --git a/src/FS.cpp b/src/FS.cpp
        index d9bb1a5..201e6bc 100644
        --- a/src/FS.cpp
        +++ b/src/FS.cpp
        @@ -25,6 +25,9 @@
         ////////////////////////////////////////////////////////////////////////////////

         #include <cmake.h>
        +#if defined CYGWIN
        +#define _GNU_SOURCE
        +#endif
         #include <FS.h>
         #include <fstream>
         #include <glob.h>

**Comment by tbabej** [comment]
@esemplare Thanks for contributing this! We are definitely trying to support cygwin if possible, unfortunately it's not one of the platforms we have the ability to run our test suite as part of the CI, so this bug report is very much welcome :slightly_smiling_face: 

Would you like to convert the suggestions above to a pull request?
