### ISSUE TITLE
[BUG] rc.exit.on.missing.db=1 discards rc.verbose override effect

### ISSUE THREAD

**Issue by Zebradil** [GothenburgBitFactory/taskwarrior#2633]
## Reproduction log

<details>
  <summary>Prepare database for tests</summary>
  
```
root@712ae0789d7c:/app# task version
A configuration file could not be found in

Would you like a sample /root/.taskrc created, so Taskwarrior can proceed? (yes/no) yes

task 2.5.3 built for Linux
Copyright (C) 2006 - 2021 P. Beckingham, F. Hernandez.

Taskwarrior may be copied only under the terms of the MIT license, which may be found in the Taskwarrior source kit.

Documentation for Taskwarrior can be found using 'man task', 'man taskrc', 'man task-color', 'man task-sync' or at http://taskwarrior.org

root@712ae0789d7c:/app# task add First test task
Created task 1.
root@712ae0789d7c:/app# task next

ID Age  Description     Urg
 1 6s   First test task    0

1 task
```
</details>

### Expected behavior
```
root@712ae0789d7c:/app# task rc.verbose: rc.hooks:off rc.report.next.columns:id,description rc.report.next.labels:1,2 limit:1 next
1 First test task
```

### Actual behavior
```
root@712ae0789d7c:/app# task rc.exit.on.missing.db=1 rc.verbose: rc.hooks:off rc.report.next.columns:id,description rc.report.next.labels:1,2 limit:1 next

1 2
1 First test task

1 task
Configuration override rc.exit.on.missing.db:1
Configuration override rc.verbose:nothing
Configuration override rc.hooks:off
Configuration override rc.report.next.columns:id,description
Configuration override rc.report.next.labels:1,2
```  

As you can see, adding `rc.exit.on.missing.db=1` to the command discards effect of `rc.verbose: `: additional info is still printed out despite disabled verbosity. I expect `rc.exit.on.missing.db=1` to not change the output of commands if database files exist.

<details>
  <summary>task diag</summary>
```
task 2.5.3
   Platform: Linux

Compiler
    Version: 10.2.1 20210110
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.18.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.7.1
 Build type: None

Configuration
       File: /root/.taskrc (found), 1382 bytes, mode 100644
       Data: /root/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server:
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /root/.task/hooks
             (-none-)

Tests
   Terminal: 215x35
       Dups: Scanned 1 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 1 tasks for broken references:
             No broken references found
```
</details>

**Comment by tbabej** [comment]
Thanks for the clear bug report! I was able to reproduce on 2.5.3:

```
[warrior@tw-v2.5.3 ~]$ task rc.exit.on.missing.db=1 rc.verbose: rc.hooks:off rc.report.next.columns:id,description rc.report.next.labels:1,2 limit:1 next

1 2              
1 First test task

1 task
Configuration override rc.exit.on.missing.db:1
Configuration override rc.verbose:
Configuration override rc.hooks:off
Configuration override rc.report.next.columns:id,description
Configuration override rc.report.next.labels:1,2
```

The good news is that this problems is already fixed on our newest [release 2.6.0](https://github.com/GothenburgBitFactory/taskwarrior/releases/tag/v2.6.0) (released 11 days ago):
```
[warrior@tw-v2.6.0 ~]$ task rc.exit.on.missing.db=1 rc.verbose: rc.hooks:off rc.report.next.columns:id,description rc.report.next.labels:1,2 limit:1 next
1 First test task
[warrior@tw-v2.6.0 ~]$
```

I believe this is the same mechanism as #2247 (or #2161). We have recently included this problem in the test suite to avoid further regression (see #2552) :slightly_smiling_face:

**Comment by Zebradil** [comment]
Sorry, I was trying to find if it's mentioned in the changelog, but somehow missed it. I didn't think that the problem is caused by the position of the `rc.verbose` override. Tests were done in docker containers with ubuntu, where taskwarrior is installed from official repos and is quite outdated. On my personal machine I already have 2.6.0, but I mistakenly decided that the bug is also reproduced with the new version. 

If this bug is fixed in 2.6.0, should this issue be closed? I will just ensure that `rc.verbose` goes first in my scripts.

By the way, is there an option similar to `exit.on.missing.db`? I was told about a use case when a user uses different taskrc files depending on CWD and in some cases there is no taskrc at all. `taskwarrior` is invoked inside a shell prompt plugin automatically and it would have made the plugin's code more neat if I could just invoke `taskwarrior` in "non-interactive" mode. Otherwise, it waits for user input and blocking shell prompt. I worked this around with sending empty input to it's stdin, but it feels a bit hacky. (Sorry for introducing another topic here, can move to a separate issue if you think it'll be better).

**Comment by tbabej** [comment]
> Sorry, I was trying to find if it's mentioned in the changelog, but somehow missed it. I didn't think that the problem is caused by the position of the rc.verbose override.
...

Indeed, this bug is quite subtle!

> By the way, is there an option similar to exit.on.missing.db?

Perhaps you're looking for `confirmation=off`? That will prevent the prompt for confirming the creation of taskrc

```
# Base case first
[warrior@tw-v2.6.0 ~]$ rm -rf ~/.task
[warrior@tw-v2.6.0 ~]$ task
A configuration file could not be found in /home/warrior

Would you like a sample /home/warrior/.taskrc created, so Taskwarrior can proceed? (yes/no) no
Cannot proceed without rc file.

# Now with rc.confirmation=off
[warrior@tw-v2.6.0 ~]$ rm -rf ~/.task
[warrior@tw-v2.6.0 ~]$ rm -f ~/.taskrc
[warrior@tw-v2.6.0 ~]$ task rc.confirmation:off
Configuration override rc.confirmation:off
No matches.

[warrior@tw-v2.6.0 ~]$ ls ~/.taskrc
/home/warrior/.taskrc
```

Note however, as last line suggests, that confirmation=off will assume positive response, so the default taskrc will be generated in the folder.

**Comment by Zebradil** [comment]
Alright, thank you for the information!

In this case the workaround I mentioned before is good enough for the situation when creating a new config file is undesirable.

I assume that this issue can be safely closed.
