### ISSUE TITLE
After update to 2.6.0 some fish completions throws an error

### ISSUE THREAD

**Issue by angelus2014** [GothenburgBitFactory/taskwarrior#2643]
* What command(s) did you run?
task -compl <TAB>
* What did you expect to happen?
As before, I expected it to expand to task -COMPLETED
* What actually happened?
» task -complstring match: Unknown option '-compl'

/opt/homebrew/share/fish/vendor_completions.d/task.fish (line 110):
  string match -q "*:*" "$cmd[-1]"
  ^
in function '__fish.task.need_to_complete.attr_value'
        called on line 1 of file /opt/homebrew/share/fish/vendor_completions.d/task.fish
in function '__fish.task.partial' with arguments 'need_to_complete attr_value'
        called on line 147 of file /opt/homebrew/share/fish/vendor_completions.d/task.fish
in function '__fish.task.need_to_complete' with arguments 'attr_value'
in command substitution

(Type 'help string' for related documentation)
» task -COMPLETED all
* Paste the output of the ```task diag``` command.
» task diag

task 2.6.0
   Platform: Darwin

Compiler
    Version: Apple LLVM 13.0.0 (clang-1300.0.29.3)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.21.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.16
 Build type: Release

Configuration
       File: /Users/angelo/.taskrc (found), 3004 bytes, mode 100644
       Data: /Users/angelo/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server:
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /Users/angelo/.task/hooks
             (-none-)

Tests
   Terminal: 321x116
       Dups: Scanned 928 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 928 tasks for broken references:
             No broken references found

This didn't happen in 2.5.3, and I've seen this error with other completions as well. Fish hasn't been updated since July.

---
With regards,

Angelo Machils

**Comment by tbabej** [comment]
Hi @angelus2014, thanks for the bug report! I believe this _might_ be the same issue as #2619 - which has been just released as part of 2.6.1 release. Could you try if upgrading fixes the problem?

Alternatively you can try to apply [the fix for the completion](https://github.com/GothenburgBitFactory/taskwarrior/commit/d4a9ce614bfe770d3c168a0e3f094f3c1d56a4e2.patch) directly, it's quite short :slightly_smiling_face:

**Comment by angelus2014** [comment]
Hello @tbabej, thank you. Applying that patch seems to fix the issue.


---
With regards,

Angelo Machils
