### ISSUE TITLE
`brew install task` depends on an old theme, that is not installed

### ISSUE THREAD

**Issue by tGrottker** [GothenburgBitFactory/taskwarrior#2644]
##### What command(s) did you run?

```shell
$ brew install task
$ task
```

##### What did you expect to happen?

I expected taskwarrior to start.

##### What actually happened?

Taskwarrior did not start. Instead I received the same error as pasted below.

##### Paste the output of the ```task diag``` command.

```shell
Could not read include file '/usr/local/Cellar/task/2.5.1/share/doc/task/rc/light-16.theme'.
```

This actually surprised me, because I have installed version 2.6.0.

```shell
$ ls /usr/local/Cellar/task/
2.6.0
```

**Comment by tbabej** [comment]
Is it possible you started using TW the first time in 2.5.1 and ported your confiuration over? In that case the `~/.taskrc` file would contain this line:

```
include /usr/local/Cellar/task/2.5.1/share/doc/task/rc/light-16.theme
```

which would need to be changed by editing the ~/.taskrc file to:

```
include /usr/local/Cellar/task/2.6.0/share/doc/task/rc/light-16.theme
```

In the past, you'd have to do this on every upgrade (if your package manager ships the themes in a subfolder that contains the TW version). We don't package TW for homebrew, and as such have no control over this.

That said, starting in 2.6.0, we support relative paths for `include` statements and the default configuration dirs are one of the folders searched by default by relative includes, so the following should work now:

```
include light-16.theme
```

and would be hopefully resistant to future upgrades :slightly_smiling_face:

**Comment by tGrottker** [comment]
Thank you, this was the cause and its fix.
