### ISSUE TITLE
After update to 2.6.0, quite a few tasks now have 'ORPHAN' virtual tag

### ISSUE THREAD

**Issue by angelus2014** [GothenburgBitFactory/taskwarrior#2646]
* What command(s) did you run?
task 100
* What did you expect to happen?
Show me the full contents of the task
* What actually happened?
Full contents of the task is present/showing, but it now has an 'ORPHAN' tag. Using task edit shows: # User Defined Attributes  UDA priority: 
But after that, it seems there are a number of spaces. Removing them doesn't solve it and after saving and editing it again shows the spaces. In my taskrc I have the following (which before wasn't a problem):
urgency.uda.priority..coefficient=2.5
uda.priority.values=H,M,,L
Commenting them out doesn't fix it.
* Paste the output of the ```task diag``` command.
```
task 2.6.0
   Platform: Darwin

Compiler
    Version: Apple LLVM 13.0.0 (clang-1300.0.29.3)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.21.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.16
 Build type: Release

Configuration
       File: /Users/angelo/.taskrc (found), 3004 bytes, mode 100644
       Data: /Users/angelo/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server:
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /Users/angelo/.task/hooks
             (-none-)

Tests
   Terminal: 357x131
       Dups: Scanned 966 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 966 tasks for broken references:
             No broken references found
```

**Comment by tbabej** [comment]
This is a real bug - nothing wrong with your UDA :slightly_smiling_face:  good news is that I believe we already got fixed in the `2.6.1` bugfix release. I'll follow up later with references.

**Comment by tbabej** [comment]
I looked into this and I believe this is the same issue as #2622, which was fixed with https://github.com/GothenburgBitFactory/taskwarrior/pull/2637 and was released as part of 2.6.1. Keeping this open for angelus2014 to confirm :slightly_smiling_face:

**Comment by angelus2014** [comment]
I saw #2622, but I didn't realise that it was the same issue :) As soon as 2.6.1 hits Homebrew, I will test and post the results here.

---
Angelo

**Comment by angelus2014** [comment]
Just upgraded to 2.6.1 and the issue does indeed seem to be solved. Thank you!
