### ISSUE TITLE
xdg-open is not available on Mac OS-X

### ISSUE THREAD

**Issue by chapterjason** [GothenburgBitFactory/taskwarrior#2648]
Short and tight:

```
$ task news
[...]
Would you like to open Taskwarrior 2021 fundraising campaign to read more? (YES/no) yes
sh: xdg-open: command not found
```

`xdg-open` is not available on Mac.

https://github.com/GothenburgBitFactory/taskwarrior/blob/072b38d326997f603348fd15b925c04cc8450d23/src/commands/CmdNews.cpp#L619

**Comment by tbabej** [comment]
Ah, yes, that is definitely too broad of an assumption :slightly_smiling_face: @chapterjason I assume `open` would work on Mac OS-X as a substitute?

**Comment by chapterjason** [comment]
@tbabej Yes. :)
