### ISSUE TITLE
mod depends: does not remove the dependency

### ISSUE THREAD

**Issue by angelus2014** [GothenburgBitFactory/taskwarrior#2655]
* What command(s) did you run?
task some_project mod depends: (but also with task 100 mod depends:)
* What did you expect to happen?
To remove the dependency/dependencies
* What actually happened?
First I see a message 'no changes will be made' and then a list of 'modifying', but nothing actually is being modified.

Not sure if this is actually a bug or not implemented. I've tried to search here for a similar report, but couldn't find any.

---
With regards,

Angelo Machils

**Comment by smemsh** [comment]
as a data point, this worked correctly with july 22nd 2.6.0 branch (607baa0), but did not with 2.6.1

**Comment by tbabej** [comment]
I can confrim this is a problem, and since this is a regression, we will try to (promptly) fix this and release 2.6.2.
