### ISSUE TITLE
shell alias

### ISSUE THREAD

**Issue by jaker-dotcom** [GothenburgBitFactory/taskwarrior#2660]
Hey there! 

I have this alias in my .profile which I use to quickly postpone tasks:

taskwaitfunction () {
		task ${@:1:$#-1} +PENDING modify wait:${@: -1}
}
alias tw=taskwaitfunction

it seemed to have ceased working with the new release. Though now I noticed that it only doesn't work with named dates no more. That is

`tw 81 2d` works but
`tw 81 sun`doesn't

I am open for alternative ways to abbreviate the clumsy `task 81 modify wait:sun`. 

Thanks

PS: manually typing `task 81 +PENDING modify wait:sun` still works so this might aswell be a zsh problem. Would be great to get an answer nonetheless!

**Comment by gunnarx** [comment]
> PS: manually typing task 81 +PENDING modify wait:sun still works so this might aswell be a zsh problem. Would be great to get an answer nonetheless!

But that clearly suggests the problem is in your shell command, so the question shouldn't be asked here, right?  (But I am not a project maintainer here, so it's up to them, really)   

Let's see.  Use **echo** to see what happens with your variable expression:

In bash:
```bash
bash > taskwaitfunction () { echo task ${@:1:$#-1} +PENDING modify wait:${@: -1}; }
bash > taskwaitfunction 81 sun
task 81 +PENDING modify wait:sun
```
^^^ result is what you wanted

In zsh:
```zsh
zsh > taskwaitfunction () { echo task ${@:1:$#-1} +PENDING modify wait:${@: -1}; }
zsh > taskwaitfunction 81 sun
task 81 sun +PENDING modify wait:sun
```
^^^ result seems wrong.

**Comment by jaker-dotcom** [comment]
You're right. Thanks for answering anyways. Now that I have a trace I'll sure be able to track it down!
It's weird whatsoever that it worked before 2.6. Maybe though I just didn't notice that named dates stopped working when I switched to zsh couple of months ago. I feel like I use them all the time though.

**Comment by jaker-dotcom** [comment]
an extra space between the $# and the -1 in the first parameter expansion make it so that the date doesn't appear twice. Thus for zsh it should be:

`taskwaitfunction () {
		task ${@:1:$# -1} +PENDING modify wait:${@: -1}
}
`
