### ISSUE TITLE
RFE: make start / stop times persistent as annotations

### ISSUE THREAD

**Issue by linuxcaffe** [GothenburgBitFactory/taskwarrior#2665]
as mentioned in #2654, having a persistent record of when a task is stopped and started is as simple as writing annotations
```
2021-10-23 11:23:14 -- Started
2021-10-23 11:25:16 -- Stopped (duration 00:02:02)
```
Nothing else about the start/ stop behavior would need to change, and external code would at least have a access to the data.

**Comment by tbabej** [comment]
We might add a feature to have persistent list of start/stops for the given task, but I don't think the annotations are the right place for this.

For what it's worth David, this could be currently achieved with a hook :slightly_smiling_face:

**Comment by linuxcaffe** [comment]
I'm closing this and adopting hledger as my time-tracking (time-accounting) solution, using this hook; https://github.com/linuxcaffe/task-timeclock-hook
