### ISSUE TITLE
The value of soww named date is incorrect

### ISSUE THREAD

**Issue by kiil** [GothenburgBitFactory/taskwarrior#2671]
Bug

* What command(s) did you run?

[I] pi ) task calc now
2021-11-08T11:12:59 <- correct

[I] pi ) task calc sopww
2021-11-01T00:00:00 <- correct

[I] pi ) task calc sonww
2021-11-15T00:00:00 <- correct

[I] pi ) task calc soww
2021-11-15T00:00:00  <- incorrect

* What did you expect to happen?

[I] pi ) task calc soww
2021-11-08T00:00:00

* What actually happened?

[I] pi ) task calc soww
2021-11-15T00:00:00

NOTE 1: It does not matter whether the "workweek" starts on Sunday or Monday, soww is wrong in either case.

NOTE 2: FWIIW task calc eopww, task calc eonww and task calc eoww all give the correct result.

* Paste the output of the ```task diag``` command.

task 2.6.1
   Platform: Linux

Compiler
    Version: 8.3.0
       Caps: +stdc +stdc_hosted +c8 +i32 +l32 +vp32 +time_t32
 Compliance: C++17

Build Features
     Commit: e0f598f91
      CMake: 3.16.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: n/a
 Build type: release

Configuration
       File: /home/pi/.config/task/taskrc (found), 1622 bytes, mode 100644
       Data: /home/pi/.local/share/task/ (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
  rc.editor: vim
     Server: 
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/pi/.config/task/hooks/
     Active: on-modify.timewarrior (executable)
   Inactive: 

Tests
   Terminal: 210x40
       Dups: Scanned 275 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 275 tasks for broken references:
             No broken references found

**Comment by tbabej** [comment]
Good catch! I can confirm that `soww` is not behaving as expected.
