### ISSUE TITLE
Can't get rc.dateformat working

### ISSUE THREAD

**Issue by ksandvik** [GothenburgBitFactory/taskwarrior#2680]
#### To report a bug...

* What command(s) did you run?
Edit .taskrc
rc.dateformat=y-M-D

Relaunch shell.

* What did you expect to happen?
output in forms of y-M-D,  21-11-12

* What actually happened?
Still using default Y-M-D: 2021-11-12

Also:
~> task _get rc.dateformat
Y-M-D

Either the documentation should point out how to edit this, or then the fish shell sits between, or then there's a but to use the lower case y for year in combination with M and D.

* Paste the output of the ```task diag``` command.

#### To request a feature...
 ~> task diag

task 2.6.1
   Platform: Darwin

Compiler
    Version: Apple LLVM 13.0.0 (clang-1300.0.29.3)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.21.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.16
 Build type: Release

Configuration
       File: /Users/ksandvik/.taskrc (found), 1435 bytes, mode 100644
       Data: /Users/ksandvik/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: code
     Server:
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /Users/ksandvik/.task/hooks
     Active:
   Inactive: on-modify.timewarrior (not executable)

Tests
   Terminal: 166x36
       Dups: Scanned 124 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 124 tasks for broken references:
             No broken references found

**Comment by ksandvik** [comment]
Also 
~> task rc.dateformat y-M-D
Configuration override rc.dateformat
~> task _get rc.dateformat
Y-M-D

**Comment by ksandvik** [comment]
Well, the setting is dateformat in .taskrc that overrides any local scope I could get this to work, but still confused about setting this value.

**Comment by tbabej** [comment]
Hi @ksandvik, I can see where the confusion came from! The `rc.dateformat=y-M-D` approach is not used for permanently configure settings, but rather to temporarily override the setting value for that single task command. In other words, the following works as expected:

```
$ task rc.dateformat=y-M-D _get rc.dateformat
y-M-D
```

If you want to permanently set the configuration value, you either need to edit the taskrc (as you discovered), or use the `config` command, like this:

```
$ task config dateformat y-M-D
Are you sure you want to add 'dateformat' with a value of 'y-M-D'? (yes/no) yes
Config file /home/tbabej/.taskrc modified.

$ task _get rc.dateformat
y-M-D
```

Hope this helps!

**Comment by ksandvik** [comment]
Yes, that was it. Maybe documentation about this could be helpful. If the task config is the best approach, then that could be flagged in documentation.

**Comment by joeldcanfield** [comment]
For those who come after me and still aren't clear:

To change the date format in a text editor:

1. open .taskrc
2. add the line `dateformat='[your format here]`
3. save .taskrc

For example:
`dateformat='YMDHN'`
will use the format _4-digit year 2-digit month 2-digit date 2-digit hour (24 hour clock) 2-digit minute_, eg. at the moment I'm typing this 202212111635 as in 4:35pm December 11th, 2022
