### ISSUE TITLE
version.t tests fail when rebasing

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#2682]
I typically check that tests still pass in a series of commits with an interactive rebase something like

```
pick aaaaaa
x make test
pick bbbbbb
x make test
pick cccccc
x make test
```

and in this case, the `version.t` test "_version and diagnostics output expected version and syntax" fails, I think because the git version is encoded into the source in such a way that it's not rebuilt every time HEAD changes (which makes sense!)

Could we scale that test back to just check for a hash, without verifying *which* hash?  Would that miss any common conditions that should be caught in CI or devs' `make test` runs?

**Comment by tbabej** [comment]
Yeah, this is a common problem. As far as I understand, the purpose of thay test is to ensure that you're testing against the version in your repo, but with dirty diffs, even thay is not guaranteed.

Hence I think relaxing this is the right way to go. Perhaps this should be part of the release checklist.

**Comment by djmitche** [comment]
The release shouldn't include a git version, right?  So, probably nothing to do?
