### ISSUE TITLE
Declare `contextTask` in one place

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#2683]
A number of column type implementations have `extern Task& contextTask`.  In general, this seems to be a poorly-guarded global variable that is declared and referred to in a number of places.

Let's clean that up:
 * declare it in one place
 * gate access to it through a function, in some way that it is reset to NULL at an appropriate time to avoid dangling references

**Comment by djmitche** [comment]
This is even a little worse: `contextTask` is set in column modify methods, but those methods are also called for `task add`.

**Comment by tbabej** [comment]
It looks the reason the `contextTask` is being set there is for resolution of DOM references, like this:

```
task add due:2.due This task should be done by the same time as task 2
```

so this is not being set every time when `task add` is called, only when a DOM reference is detected :thinking:

**Comment by djmitche** [comment]
@tbabej mentioned that this value should probably be a Context attribute.  That makes a lot of sense!

And, I think we can move the setting of contextTask out of the column methods and into the commands.  So CmdAdd wouldn't set it, but CmdModify (and anything else that modifies) would.

**Comment by tbabej** [comment]
> And, I think we can move the setting of contextTask out of the column methods and into the commands. So CmdAdd wouldn't set it, but CmdModify (and anything else that modifies) would.

I think there's one potential problem with that, which is that the fact that column methods use context task to resolve DOM references that might refer to other tasks than the one being modified (as I tried to point out in the comment above). Which means a command like this:

```
task add test due:today
task 5 modify priority:3.priority project:4.project scheduled:due
```

will use the task ID 3 when evaluating the `priority` column as its contextTask, and task ID 4 when evaluating `project` column. and task ID 5 otherwise (for the `scheduled` column). This will set:
* priority of task 5 to the same value as task 3
* project of task 5 to the same value as task 4
* scheduled to the same value as due

**Comment by djmitche** [comment]
DOM references are still possible if contextTask is NULL -- they just can't refer to "this" task.  So
```
task add scheduled:due
```
isn't supported, since that makes no sense[1].  But
```
task modify scheduled:due
```
is supported, as is
```
task add scheduled:4.due
```

For the first of those supported options (modify), we'll set contextTask.  For the second, contextTask is NULL but because the DOM reference identifies another task, it still works.

[1] In fact, that's what the unit test checks: `task add proj:due-b` should evaluate to project "due-b", while `task 1 modify proj:due-b` will resolve to project "-b" or, if the task is due, project "2021-12-23T21:16:44-b"

**Comment by djmitche** [comment]
(that things parse differently in these two situations is surprising to the user, and has tripped me up before!)

**Comment by djmitche** [comment]
Huh, apparently that _is_ legal

One of the tests runs `['/home/dustin/p/taskwarrior/src/task', 'add', 'three', 'due:20110901', 'wait:due', '+tag1', '+tag2']`

**Comment by djmitche** [comment]
OK, I'm legit confused about the intent here.

dom2.t calls `add three due:20110901 wait:due +tag1 +tag2` and expects `wait:due` to refer to the `due` value set earlier on the command line.  OK, cool, I can make that work by setting the contextTask to be the newly created task in CmdAdd.cpp, so that DOM references search the values already set on the task as the command line is processed.

..but in that case, "project.t: 1900: Project name can contain dashes" checks `task add foo project:due-b` expects project to be `due-b`, but since there's a context task it substitutes the empty string for the `due` DOM reference and gets `-b` instead.

In 2.6.1:
```
cleave ~ $ task add foo proj:due-b
Created task 166.
The project 'due-b' has changed.  Project 'due-b' is 0% complete (1 task remaining).
cleave ~ $ task add foo wait:2d proj:due-b
Created task 167.
The project '-b' has changed.  Project '-b' is 0% complete (1 task remaining).
```
so it seems that DOM references are only left un-parsed in `task add` if they are in the first non-description attribute (so basically, they're always empty).

In 2.5.1:
```
dorp ~ $ task add foo proj:due-b
Cannot subtract strings
```

and in 2.6.1, on a task with a `due` property:
```
cleave ~ $ task 117 modify proj:due-b
Cannot subtract strings
```
but
```
cleave ~ $ task 117 modify proj:due
Modifying task 117 '...'.
Modified 1 task.
The project '2021-12-16T23:00:00' has changed.  Project '2021-12-16T23:00:00' is 0% complete (1 task remaining).
```

So, this is new behavior, and wildly inconsistent.  I think the test checking `proj:due-b` is incidentally asserting something about DOM references that is not intentional and only *happens* to work, in some versions, in some situations.  So I'm going to change the test to `proj:doo-bee`, which still has the dash named in the test description.
