### ISSUE TITLE
after upgrade to 2.6.1 start/end dates not a valid date fedora

### ISSUE THREAD

**Issue by felixschurk** [GothenburgBitFactory/taskwarrior#2685]
When I run `task timesheet`, or any other filter which refers to a start or end date,  like `task start.after:2021-11-01 completed` I get the following error.
`'start' is not a valid date in the 'Y-M-D' format.`

My output from `task show dateformat` look like this and I never changed something in the dateformats. 
```
Config Variable       Value      
dateformat            Y-M-D      
dateformat.annotation
dateformat.edit       Y-M-D H:N:S
dateformat.holiday    YMD
dateformat.info       Y-M-D H:N:S
dateformat.report
```

The output from a task looks like this, and for me the end date looks like every other dates.
```
Name          Value                               
ID            -                                   
Description   testtask
Status        Completed                           
Project       inbox
Entered       2021-11-17 10:41:15 (23h)           
End           2021-11-17 16:35:03
Last modified 2021-11-17 16:35:03 (17h)           
Virtual tags  COMPLETED PROJECT UNBLOCKED
UUID          e8b57adc-bd11-4caf-b538-02708aceedbe
Urgency          1

    project      1 *    1 =      1
                            ------
                                 1

Date                Modification                                 
2021-11-17 16:33:46 Start set to '2021-11-17 16:33:46'.          
2021-11-17 16:35:03 Start deleted (duration: 0:01:17).
                    End set to '2021-11-17 16:35:03'.
                    Status changed from 'pending' to 'completed'.
```
I would expect that the `task timesheet` command would work like bevor, and under my other machine the timesheet command runs, so I don't get whats the problem.

**Comment by tbabej** [comment]
I was not able to reproduce this on 2.6.1.

Could you perhaps try to see if this occurs if you temporarily use a new data.location directory? I suspect the problem is data dependant, and to proceed forward we need to figure out how to get there 🤔

**Comment by felixschurk** [comment]
Yes you are right, by a new data.location I can show my reports without problems.
I think I can solve it by deleting my current data.location, and resync it from the server.

But I am a bit curious, how and which data got broken.
