### ISSUE TITLE
Taskserver error: Name or service not known

### ISSUE THREAD

**Issue by sourav-majumdar-math** [GothenburgBitFactory/taskwarrior#2694]
I am trying to setup taskserver on my VPS, but after completing the setup procedure and running `task sync init`  I get the following error message,

```
Name or service not known
Sync failed.  Could not connect to the Taskserver.
```

I followed the troubleshooting guide but I could not resolve my issue. Can someone please guide me on how to solve this?

`task diagnostics` output on the client,

```
task 2.5.1
   Platform: Linux

Compiler
    Version: 9.2.1 20200306
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.16.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.11
 Build type: None

Configuration
       File: /home/sourav/.taskrc (found), 1674 bytes, mode 100664
       Data: /home/sourav/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: localhost.xxxx.yyyy.zzzz.yzyz:53589
         CA: /home/sourav/.task/ca.cert.pem, readable, 3765 bytes
      Trust: strict
Certificate: /home/sourav/.task/Sourav_Majumdar.cert.pem, readable, 3751 bytes
        Key: /home/sourav/.task/Sourav_Majumdar.key.pem, readable, 24754 bytes
    Ciphers: NORMAL
      Creds: PUBLIC/Sourav Majumdar/************************************

Hooks
     System: Enabled
   Location: /home/sourav/.task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (175x42)
       Dups: Scanned 83 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 83 tasks for broken references:
             No broken references found
```

Here xxxx.yyyy.zzzz.yzyz is the IP address of my server. `taskd diagnostics` output on the server,

```
taskd 1.1.0
    Platform: Linux
    Hostname: privserver

Compiler
     Version: 9.3.0
        Caps: +stdc +stdc_hosted +200809 +200809 +LP64 +c8 +i32 +l64 +vp64 +time_t64
  Compliance: C++11

Build Features
       Built: Nov 29 2021 07:15:35
       CMake: 3.16.3
     libuuid: libuuid + uuid_unparse_lower
   libgnutls: 3.6.13
  Build type: release

Configuration
   TASKDDATA:
        root: /home/taskwarrior/taskdata (readable)
      config: /home/taskwarrior/taskdata/config (readable)
          CA: /home/taskwarrior/taskdata/cert/ca.cert.pem (readable)
 Certificate: /home/taskwarrior/taskdata/cert/server.cert.pem (readable)
         Key: /home/taskwarrior/taskdata/cert/server.key.pem (readable)
         CRL: /home/taskwarrior/taskdata/cert/server.crl.pem (readable)
         Log: /home/taskwarrior/taskdata/log/taskd.log (found)
    PID File: /home/taskwarrior/taskdata/run/taskd.pid (found)
      Server: localhost:53589
 Max Request: 10485760 bytes
     Ciphers: NORMAL
       Trust: strict
```

**Comment by bradyt** [comment]
I've never seen an example like `taskd.server=localhost.xxxx.yyyy.zzzz.yzyz:53589`, where "`xxxx.yyyy.zzzz.yzyz` is the IP address". Maybe you can clarify for me how that should work.

How about something like the following:

```ini
# TASKDDATA

# server = localhost:53589
server = $ip_address_1:53589
```
```ini
# TASKRC

# taskd.server = localhost.xxxx.yyyy.zzzz.yzyz:53589
taskd.server = $ip_address_2:53589
taskd.trust  = ignore hostname
```

The Taskserver troubleshooting guide may clarify what to use for `ip_address_1` and `ip_address_2`.

I got that to work for me here. However, I usually use a domain name for `taskd.server`, and `taskd.trust=strict`.

If you have more trouble, can you clarify if `xxxx.yyyy.zzzz.yzyz` matches some troubleshooting command in the Taskserver troubleshooting guide, and which one?

**Comment by bradyt** [comment]
> If you have more trouble, can you clarify if xxxx.yyyy.zzzz.yzyz matches some troubleshooting command in the Taskserver troubleshooting guide, and which one?

On a reread, that was a bit vague. I mean at <https://gothenburgbitfactory.github.io/taskserver-troubleshooting/>, I see examples like the following:

- `ifconfig -a`
- `ip addr list`

Do you see `xxxx.yyyy.zzzz.yzyz` from one of those?

Or maybe a command from the section on "CLIENT TOOLS"?

**Comment by bradyt** [comment]
Regarding <https://gothenburgbitfactory.github.io/taskserver-troubleshooting/>, you may want to set `$TASKDDATA/server`, or `ip_address_1`, to something found in the "SERVER TOOLS" section, and `$TASKRC/taskd.server`, or `ip_address_2`, to something found in the "CLIENT TOOLS" section. You could potentially end up with two different ip addresses to get things working.

**Comment by djmitche** [comment]
Closed because taskserver/taskd is no longer supported.
