### ISSUE TITLE
'done' tasks in burndowns overpower pending/started tasks

### ISSUE THREAD

**Issue by QuantumBJump** [GothenburgBitFactory/taskwarrior#2695]
When I run the `burndown.daily`, `burndown.weekly` and `burndown.monthly` commands, it shows all tasks in my entire history of using taskwarrior, no matter how old. This is desired behaviour for pending and started tasks, but when applied to done tasks, it means that the number of tasks marked done quickly overwhelms the pending/started tasks, rendering the graph almost useless, as the percentage of tasks which aren't marked 'done' becomes vanishingly small: 
![image](https://user-images.githubusercontent.com/8631107/144056196-d60e7da4-63a1-4f55-baa7-35b1f733492a.png)

Note that at the time I generated this graph, I had 2 started and 4 pending tasks, but they're completely invisible because of the 100+ tasks I've marked completed since I started using taskwarrior at the start of 2021. Ideally taskwarrior would somehow prune the 'done' tasks based on when they were marked as done, or include a configuration to ignore done tasks when generating the graph, and only print pending or started tasks.

**Comment by tbabej** [comment]
Hi @QuinnStevens, assuming you're on the latest release, does setting `burndown.cumulative=0` in the `~/.taskrc` get your desired behaviour?

**Comment by QuantumBJump** [comment]
Ah, I had thought I was on the latest version, as I'd run `apt-get upgrade taskwarrior`, but it turns out that wasn't upgrading past 2.5.3, and I needed to build from the tar. Now it works fine, thank you!
