### ISSUE TITLE
Crash if data.location refers to an unexisting and unwritable path

### ISSUE THREAD

**Issue by wavexx** [GothenburgBitFactory/taskwarrior#2708]
task 2.6.1 (package with debian unstable). Start with a taskrc containing a single line:

````
data.location=/heyyy/
````

Get a segmentation fault when running:

````
% task next
segmentation fault
````

as task is attempting to create a directory where it has no right (infinitely, when looking at the stack trace?).

task should exit with an error message in such case. ``task diag`` will fail as well.

**Comment by Necior** [comment]
Seems to be fixed in newer versions.

I reproduced the segfault in 2.6.2:

```
$ TASKDATA=/foo/bar/baz task
Segmentation fault (core dumped)
```

but not in 3.0.2:

```
$ TASKDATA=/foo/bar/baz task
TASKDATA override: /foo/bar/baz
Could not create replica at /foo/bar/baz: Permission denied (os error 13)
```

or 3.2.0:

```
$ TASKDATA=/foo/bar/baz task
TASKDATA override: /foo/bar/baz
Permission denied (os error 13)
```

**Comment by djmitche** [comment]
No need to keep this issue open until [that one](https://github.com/GothenburgBitFactory/taskchampion/pull/486) is closed.
