### ISSUE TITLE
Feature request to add date option to annotate 

### ISSUE THREAD

**Issue by kwoot** [GothenburgBitFactory/taskwarrior#2713]
Hi!

As a user I would like to be able to add a date to the annotate command because I use annotations to create a form of history of a task.

Something like: task annotate date:<date>  <annotation text>

p.s. still a very happy taskwarrior user!

Greets,
Jeroen Baten

**Comment by smemsh** [comment]
the annotations already have a date and time, right? you could fudge them with `task edit`, if you wanted to make them different than the entry time.  is that what you're asking to do?

**Comment by kwoot** [comment]
Yes, it took me some time to understand how this works. Sorry, will close.
