### ISSUE TITLE
How to colorize tasks per project?

### ISSUE THREAD

**Issue by pythops** [GothenburgBitFactory/taskwarrior#2715]
When I run `task  list` I want to show the tasks that belong to the same project having the same color

Thanks

Task version: task 2.6.1 built for Linux

**Comment by tbabej** [comment]
Hi @pythops,

the following configuration setting should help you achieve your goal:

       color.project.X=on green
              Colors any task assigned to project X.

Check `COLOR CONTROLS` section in the man page for more info :slightly_smiling_face:

**Comment by pythops** [comment]
Is it possible to let taskwarrior automatically assign  a color to each project I add without editing the configuration file ?

**Comment by tbabej** [comment]
That is unfortunately not possible currently. But it is an interesting feature suggestion!

**Comment by pythops** [comment]
Would be great to add it :)
Thanks
