### ISSUE TITLE
Inherited urgency calculated incorrectly with custom project/tag urgency coefficients

### ISSUE THREAD

**Issue by Cephian** [GothenburgBitFactory/taskwarrior#2732]
**What command(s) did you run?**
Starting from a clean slate:
1. Add lines to .taskrc:
```
urgency.inherit=1
urgency.user.project.MyProject.coefficient = -100
```
2. `task add project:MyProject "Do first task"`
3. `task add project:MyProject "Do second task" depends:1`
4. `task next`

This bug shows up exactly the same way using tags and tag urgency coefficients instead of projects.

**What did you expect to happen?**
Both tasks 1 and 2 should have extremely low urgency, around -100

**What actually happened?**
Task 2 (the task with a dependency) has an extremely low urgency as expected. But task 1 has an urgency of 0.01, even though the urgency coefficient of its project should make it much lower.

```
ID Age   Deps Project   Description    Urg
-- ----- ---- --------- -------------- ----
 1 32min      MyProject Do first task  0.01
 2 32min 1    MyProject Do second task -104
```

**Paste the output of the ```task diag``` command.**
```
task 2.6.1
   Platform: Linux

Compiler
    Version: 11.1.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.21.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.7.2
 Build type: 

Configuration
       File: altrc (found), 132 bytes, mode 100644
       Data: /home/jack/altdir (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $VISUAL: nvim
     Server: 
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/jack/altdir/hooks
             (-none-)

Tests
   Terminal: 120x30
       Dups: Scanned 2 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 2 tasks for broken references:
             No broken references found
```

**Comment by smemsh** [comment]
For the first task, the urgency calc looks like this:
```
    PROJECT test      1 * -1e+02 =   -100
                                   ------
                                     0.01
```
for the second (dependent) task:
```
    PROJECT test      1 * -1e+02 =   -100
                                   ------
                                     -100
```
the code for urgency inheritance does this:
```c++
  if (is_blocking && Context::getContext ().config.getBoolean ("urgency.inherit"))
  {
    float prev = value;
    value = std::max (value, urgency_inherit ());

    // This is a hackish way of making sure parent tasks are sorted above
    // child tasks.  For reports that hide blocked tasks, this is not needed.
    if (prev < value)
      value += 0.01;
  }
```
probably the bug is with the `max()` calculation.  `urgency_inherit()` is doing:
```c++
float v = FLT_MIN;
for (auto& task : getBlockedTasks ())
{
  // Find highest urgency in all blocked tasks.
  v = std::max (v, task.urgency ());
} 
```
my float.h says FLT_MIN is:
```
/* Minimum normalized positive floating-point number, b**(emin - 1).  */
```
Note the "positive."  So maybe it's returning FLT_MIN -- perhaps very close to zero, but still positive, and effectively zero to the significance used -- as the max value of the dependent tasks (new "value").  Then `prev < value` is true, so it adds 0.01 to FLT_MIN, result is ~0.01

Just a guess, I didn't look that closely and probably missed something.

**Comment by smemsh** [comment]
P.S. I find the `value += 0.01` hack annoying in the first place, leaving this random 0.01 litter around on the tasks (I use inherit also), but I considered before how easy it would be to fix this and couldn't come up with an easy way, so I thought ok, fair enough... ;-)
