### ISSUE TITLE
Move development-focused documentation into this repo

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#2741]
Currently, development documentation is on tw.org.  That's a bit problematic:
 * It's in HTML right now, making it difficult to edit and maintain (and it very much [is not maintained](https://github.com/GothenburgBitFactory/tw.org/issues/61)).  The [project to convert to markdown](https://github.com/GothenburgBitFactory/tw.org/pull/303) is rather bogged down and has quite a ways to go.
 * It's versioned separately from development, so it's difficult to find docs for older versions or correlate docs and code changes.
 * There's a lot of automated GH activity on the tw.org repo which makes it pretty hard to find changes.

I'd like to move the design documents, as well as the coding style, into this repo, either as markdown for viewing in GitHub, or as a simple "GitHub Pages" branch appearing at https://gothenburgbitfactory.github.io/taskwarrior (which would be labeled clearly with links to taskwarrior.org for user docs).

Followups would include
 * writing up the RFC process as it is
 * writing a new RFC for the Sync Overhaul project
 * documenting the current data model

Before I get started: @tbabej @lauft what do you think?

**Comment by gour** [comment]
Whatever brings this project to a better shape, is very much welcome! I finally gave up on Emacs/org-mode and would like Taskwarrior to thrive.

**Comment by lauft** [comment]
I would strongly advocate for simple markdown for viewing in GitHub.

It is sufficient for developers (judging from me 😬) and keeps maintenance at a minimum.

**Comment by djmitche** [comment]
@lauft do you want to comment on the PR?
