### ISSUE TITLE
recurring report does not include parent tasks anymore

### ISSUE THREAD

**Issue by mowgli** [GothenburgBitFactory/taskwarrior#2748]
`task recurring` should display all recurring tasks including the parent. (There is no other report that is displaying the parent tasks.)

But the filter is wron. It should be:
```
report.recurring.filter=(status:pending and +CHILD) or (status:recurring and +PARENT)
```

Or something like this. The reason is, that recurring master tasks are not status pending anymore.

With that, the columns could be adjusted to display if a task is parent or child.

**Comment by bradyt** [comment]
I don't know when this ever worked, I tried checking out v2.5.3, stable, and develop. But the inclusion of `+PARENT` suggests your expectations are correct, that `task recurring` should show parent tasks. Besides changing the filter, one quick hack to review parents is `task all +PARENT`.

**Comment by tbabej** [comment]
Klaus, thanks for the report. I think your analysis is spot-on here. I added a PR to fix the issue - will merge once it passes the test suite.

This should be part of our next release, in the meantime, the suggestions by Brady are an excellent workaround.
