### ISSUE TITLE
[task show] hooks.location is an unrecognized variable

### ISSUE THREAD

**Issue by rollniak** [GothenburgBitFactory/taskwarrior#2763]
Hello,

I just installed TaskWarrior on my machine and try to configure it.
I have an issue with an unrecognized `hooks.location` variables.

## Step to reproduce

The first attempt to set it up was on the first initialisation:

```
task rc:~/.config/task/taskrc rc.data.location:~/.local/share/task rc.hooks.location:~/.config/task/hooks
```
I (wrongly?) expected to see the configuration file fill up with the previous setting during the initialisation.
Unfortunately when I checked my _$HOME/.config/task/taskrc_, only **data.location** was present.
So I uncommented manually the **hook.location** line:

_$HOME/.config/task/taskrc_:

```
# Files
data.location=$HOME/.local/share/task
hooks.location=$HOME/.config/task/hooks
```

And get this error:

```
$task show hooks.location

Config Variable Value
--------------- ---------------------------------
hooks.location  /home/rollniak/.config/task/hooks

Your .taskrc file contains these unrecognized variables:
  hooks.location

```

## Context

Operating system:

```
$ uname -v
FreeBSD 13.0-RELEASE-p8 #0: Tue Mar 15 09:36:28 UTC 2022     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC
```

Taskwarrior:

```
$ task diag

task 2.6.2
   Platform: FreeBSD

Compiler
    Version: FreeBSD Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.22.2
    libuuid: libuuid, no uuid_unparse_lower
  libgnutls: 3.6.16
 Build type: Release

Configuration
       File: /home/rollniak/.config/task/taskrc (found), 1224 bytes, mode 100644
       Data: /home/rollniak/.local/share/task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server:
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /home/rollniak/.config/task/hooks
             (-none-)

Tests
   Terminal: 120x30
       Dups: Scanned 18 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 18 tasks for broken references:
             No broken references found
```

If I set **rc.hooks.location:~/.config/task/hooks**, the variable should or shouldn't be written in the _taskrc_ file during the first initialisation ?

I am a little bit lost. If I follow `task show` something is wrong. If I read `task diag` the vairiables **hooks.location** seems to be OK.
Which one is telling the truth ?

Thanks all for your work, I really appreciate it !
Have a nice day,
rollniak

**Comment by sec65** [comment]
Made a pull request (#2839) to fix the hooks.location in the show command.

For the first initialisation: Afaik only the data dir location could be passed that way. The hooks location has to be added to the config file afterwards.
