### ISSUE TITLE
Sync troubleshooting - inaccurate information

### ISSUE THREAD

**Issue by jose1711** [GothenburgBitFactory/taskwarrior#2776]
At https://taskwarrior.org/docs/taskserver/troubleshooting-sync.html the following is stated:
> When you generated certificates, you modified a vars file, in particular the CN=<name> setting. That name must match the output of $ hostname -f on the server for the certificate to validate. 

Actually, the "must" is apparently way too strong. My server gives `foo` (not `foo.domain`) on `hostname -f` but I have `CN=foo.domain` in `vars` and yet everything is working fine (all security settings are set to strict defaults). This is on Debian 11 (bullseye) so perhaps this section should be revised somehow.

**Comment by djmitche** [comment]
Closed because taskserver/taskd is no longer supported.
