### ISSUE TITLE
[TW-235] Persistent task, recurring task based on time since last completed

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#278]
_Hessian Nerd on 2012-05-04T01:59:15Z says:_ 

 I think the general use for this type of task would be being able to set a task that reoccurs a defined time after last instance was completed.  
e.g. 'stretch your legs' recur.after:2hrs , 'change oil' recur.after:6months , 're-roof' recur.after:10years

It would be nice to be able to set a wait time for these tasks based on time till due 
e.g. wait:due-1month , wait:due-5min

An alternative would be a persistent task with no due date that reoccurs always until deleted.  This would allow the user to have a persistent reminder and be able to log completions of something they do constantly without having a pile up of incomplete tasks
e.g. 'learn something new' recur:persistent
no due date would be set for this type of task

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-05-04T01:59:15Z
Modified: 2017-01-08T20:42:33Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-07T22:38:06Z says:_ 

 Thanks.  This will be addressed with the Great Recurring Task rewrite of 201X, whenever that is.

**Comment by taskwarrior** [comment]
_Michele Santullo on 2013-10-02T19:49:50Z says:_ 

 I vote for this feature. One real-life example is: go get a haircut recur:5weeks
If for some reason I can't go on the designated weekend (recurring happens on Friday), I'm forced to go on the next weekend, that is, I can't go on Sunday nor anytime until the next Friday. So for some reason this task was done 6 weeks after the previous time, but I still want to be reminded that the next time is 5 weeks later from that point, not just 4.

**Comment by taskwarrior** [comment]
_Dimitar on 2017-01-08T17:18:53Z says:_ 

 +1 This would be very useful feature.

Example use: I want to go to the gym every other day. Some day I might miss to go however, so this task cannot be regularly recurring. The best way to support this use case would be to reschedule the task to within two days from the point it's been marked done.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-08T20:42:33Z says:_ 

 This issue is closed as a duplicate.  You might want to look at the open linked issue.

**Comment by crocket** [comment]
@torotil https://github.com/GothenburgBitFactory/taskwarrior/issues/203
