### ISSUE TITLE
`task _tags` shows tags with no associated tasks - different behavior to `task tags`

### ISSUE THREAD

**Issue by bergercookie** [GothenburgBitFactory/taskwarrior#2823]
I'm running the `task  _tags` command. I notice that there are some duplicate tags, e.g., `+travelling` and `+travel`.

I then modify all the `+travel` tasks so that they have the right tag instead:

```
task +travel mod +travelling -travel
```

After this I would expect `task _tags` to list only the `+travelling` tag and not the `+travel` one. However it still lists both. On the other hand, `task tags` lists only the `travelling` tag and skips any tags that don't have any associated tasks.

This is a bit annoying because for my shell, `fish` the autocompletion on `task +<cursosr here>` works by showing the results of `task _tags` and this still lists the old tags

Any suggestions? Would you list this behavior of `task _tags` as a bug?

### `task diag`

```
task diag

task 2.6.2
   Platform: Linux

Compiler
    Version: 9.4.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
     Commit: 0a558ef7c
      CMake: 3.23.0-rc2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.6.13
 Build type:

Configuration
       File: /home/berger/.taskrc (found), 3971 bytes, mode 100664
       Data: /home/berger/.task (found), dir, mode 40775
    Locking: Enabled
         GC: Enabled
    $EDITOR: nvim
     Server:
         CA: not found
Certificate: not found
        Key: not found
      Trust: strict
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /home/berger/.task/hooks
             (-none-)

Tests
   Terminal: 421x103
       Dups: Scanned 10479 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 10479 tasks for broken references:
             No broken references found
```

**Comment by tbabej** [comment]
Your analysis seems correct, `_tags` should no longer return `+travel`after running the mod command, unless you have an active write context.

What does `task +travel count` return? We can also have a look at the underlying data using `cat ~/.task/{pending,completed}.data | grep -P 'travel[",]'`

**Comment by bergercookie** [comment]
> What does task +travel count return?

It returns 0.

> We can also have a look at the underlying data using cat ~/.task/{pending,completed}.data | grep -P 'travel[",]'

Same thing. This doesn't return any matches for `travel` and does return matches for `travelling`

**Comment by bergercookie** [comment]
@tbabej , how would you go about solving this? What files should I look into, etc.?

**Comment by bergercookie** [comment]
I think #2826  closes this.

btw, is there any documentation regarding the recent addition of rust code in this repo?

How/why is it used?
What functionality is handled by rust code and what by C++ code?
