### ISSUE TITLE
unsetting context mangles taskrc

### ISSUE THREAD

**Issue by jaker-dotcom** [GothenburgBitFactory/taskwarrior#2829]
#### To report a bug...
I ran 

```
t context study
t 
t context unset
t ebay
Malformed entry '' in config file.
t due:tomorrow all
Malformed entry '' in config file.
```

It should have reverted to no context and working as usual. But instead it wrecked the taskrc file. It is now just a blob of data. 
I fear I don't have my latest changes backed up. How should I try get it back? Btw I did nothing inbetween, it was one rush of commands.

```
task diag
Malformed entry '' in config file.
```

Thanks for any help or pointers to help!
Jaker

**Comment by jaker-dotcom** [comment]
Mhm. I started off with a new one, preserving the blob as a meaningless copy. As soon as I changed the data location to ~/local/share via ```task config data.location ~/local/share/task``` it destroyed the taskrc file again. Probably something to do with my system then, as there hasn't been no update that could cause such major breaks.

**Comment by smemsh** [comment]
I think also the manual says to use "none" rather than "unset" for this:

> To unset any context, use the 'none' subcommand.
