### ISSUE TITLE
Address RUSTSEC-2021-0124

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#2830]
This is a vulnerability in tokio, which is required by Actix-web.  For the moment, let's ignore it, and then decide whether to upgrade actix to suit, or switch to a different (simpler) web server package.

**Comment by djmitche** [comment]
It looks like the [audit-check action does not support `--ignore`](https://github.com/actions-rs/audit-check/issues/223), so for the moment it might be best to just disable this check.  We can re-enable it either when this advisory is addressed (by actix-web) or after switching to another web framework.

**Comment by djmitche** [comment]
Hm, audit-check appears unmaintained.  I've pinged the maintainer, but if no response then we might need to fork that action.

**Comment by djmitche** [comment]
@tbabej ok if I fork that to the `GothenburgBitFactory` org or should I do it to `djmitche`?

**Comment by tbabej** [comment]
Forking under the org is fine with me!

**Comment by pinkforest** [comment]
Hi lovelies, feel free to PR link to the fork here: https://github.com/rust-secure-code/projects :purple_heart: 

Or.. maybe we could adopt it under rust-secure-code / rustsec ? - 

I've asked others whether this is something we could do: https://github.com/rust-secure-code/wg/issues/46

**Comment by djmitche** [comment]
I just noted in https://github.com/GothenburgBitFactory/taskwarrior/pull/2903 that the fork doesn't actually add any value over upstream.  But this does seem to be a fairly "important" rust-security-related action, so I'd vote to include it in a collective org like rust-secure-code.

**Comment by pinkforest** [comment]
Cool. There is also cargo-deny alternatively e.g.:
https://github.com/libp2p/rust-libp2p/pull/2803

But I'll see the feasibility of whether we can adopt this in the meantime

**Comment by djmitche** [comment]
This has been resolved in other repos.
