### ISSUE TITLE
Directory of theme files  in .taskrc file is wrong. It has to be /2.6.2/.

### ISSUE THREAD

**Issue by Constantin1489** [GothenburgBitFactory/taskwarrior#2834]
#### To report a bug...

Directory of theme files  in .taskrc file is wrong. It has to be /2.6.2/.

`
cat ~/.taskrc
`

`
#include /usr/local/Cellar/task/2.5.3_1/share/doc/task/rc/light-16.theme
#include /usr/local/Cellar/task/2.5.3_1/share/doc/task/rc/light-256.theme
#include /usr/local/Cellar/task/2.5.3_1/share/doc/task/rc/dark-16.theme
#include /usr/local/Cellar/task/2.5.3_1/share/doc/task/rc/dark-256.theme
`

#### To request a feature...

`
#include /usr/local/Cellar/task/2.6.2/share/doc/task/rc/light-16.theme
#include /usr/local/Cellar/task/2.6.2/share/doc/task/rc/light-256.theme
#include /usr/local/Cellar/task/2.6.2/share/doc/task/rc/dark-16.theme
#include /usr/local/Cellar/task/2.6.2/share/doc/task/rc/dark-256.theme
`

**Comment by smemsh** [comment]
probably a packaging thing, my system installed them in `/usr/local/share/doc/task/rc/` using an ordinary build
