### ISSUE TITLE
Strange error - can't add tasks

### ISSUE THREAD

**Issue by mroberts1** [GothenburgBitFactory/taskwarrior#2838]
I've installed taskwarrior on MacOS Monterey via Homebrew, but keep getting a weird error message when I try to add a task.

For example, <task add Buy milk> generates this output:

Could not read include file '/usr/local/Cellar/task/2.5.3/share/doc/task/rc/solarized-dark-256.theme'.

What's weird is that this directory doesn't even exist in my filesystem. It seems to be a vestige of an install of a much older task (2.5.3). I've tried uninstalling and reinstalling the app a few times but keep getting the same error. Any idea what the issue might be?

**Comment by sec65** [comment]
In your config file of Taskwarrior (usually located in `~/.taskrc` or `~/.config/task/taskrc`) there seems to be an include statement for a color theme (see https://taskwarrior.org/docs/themes.html) of an older version. To fix it edit the config file and either comment the line or adapt it to an existent theme (if Homebrew has the newest version of Taskwarrior, it might just be a change from 2.5.3 to 2.6.2 ... sorry, I don't have a Mac to check).
