### ISSUE TITLE
Waiting tasks not showing up anywhere

### ISSUE THREAD

**Issue by linnabraham** [GothenburgBitFactory/taskwarrior#2843]
#### To report a bug...

* What command(s) did you run?
* `task add "my imaginary task due:2weeks wait:due-2days`
* What did you expect to happen?
To be able to see the task using virtual tags like +WAITING or +MONTH or anywhere .
Or status:waiting
* What actually happened?
Cant see the task anywhere except for in `task all` and in `task calendar`
* Paste the output of the ```task diag``` command.

```
task 2.6.2
   Platform: Linux

Compiler
    Version: 11.2.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.22.3
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.7.3
 Build type:

Configuration
       File: /home/linn/.config/task/taskrc (found), 4020 bytes, mode 100644
       Data: /home/linn/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: /usr/bin/vim
     Server:
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /home/linn/.task/hooks
             (-none-)

Tests
   Terminal: 256x54
       Dups: Scanned 1 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 1 tasks for broken references:
             No broken references found
```

**Comment by sebu06** [comment]
You should be able to see the report by executing 

```task all +WAITING```

Since the task is not included in the default report, it can also not be output by applying the filter, since the filter of the report will be added as well (which is per default "status:pending -WAITING limit:page")

**Comment by pkazmier** [comment]
@linnabraham here is a passage from this docs relevant to your issue: https://taskwarrior.org/docs/using_dates.html

---
You can view all the hidden waiting tasks using the waiting report:

$ task waiting
...
There is a WAITING virtual tag to select these tasks, but note that you have to use the all report with it, otherwise you get conflicts with the other reports that specify a 'pending' status, because a waiting task is not pending.
