### ISSUE TITLE
tag filters not working when using multiple tags v2.4.4

### ISSUE THREAD

**Issue by tobiasdroessler** [GothenburgBitFactory/taskwarrior#2852]
following case ...  (may is already fixed, then please close this issue)

may i understand this feature wrong, after reading the man page this should work. 
i running taskwarrior on cygwin.

create a task with two tags _foo_ and _bar_
```
 $ task add A item +foo +bar 
Created task 7. 
```

filter for first tag (_foo_) mentioned in creation, works fine ..
```
$ task tag=foo list
[task next tag = foo]
ID Age Tag     Description Urg
 7 6s  bar foo A item       0.9
1 task
```

 **filter for second tag ( _bar_ )  mentioned in creation, works NOT**
```
$ task tag=bar list
[task next tag = bar]
No matches.
```

<details>
<summary>task diag</summary>

```
$ task diag

task 2.4.4
   Platform: Cygwin

Compiler
    Version: 4.8.3
       Caps: +stdc +stdc_hosted +200112 +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: May 11 2015 20:55:58
      CMake: 2.8.11.2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.2.0
 Build type: RelWithDebInfo

Configuration
       File: /cygdrive/c/Users/DRT/.taskrc (found), 1381 bytes, mode 100644
       Data: /cygdrive/c/Users/DRT/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server:
      Trust: strict
Certificate:  (not readable)
        Key:  (not readable)
    Ciphers: NORMAL
      Creds:

Hooks
    Scripts: Enabled
             (-none-)

Tests
      $TERM: xterm (120x61)
       Dups: Scanned 19 tasks for duplicate UUIDs:
             No duplicates found

```
</details>

**Comment by bradyt** [comment]
Where do you see the `tag=foo` notation documented? I installed Cygwin and its task 2.4.4-1, and I didn't see it in the man page.

**Comment by tobiasdroessler** [comment]
There is a section in the man page ...
```
EXPRESSIONS AND OPERATORS
       You can use the following operators in filter expressions:

         and  or  xor            Logical operators
         <  <=  =  !=  >=  >     Relational operators
         (  )                    Precedence

       For example:

         task due.before:eom priority.not:L list
         task '( due < eom or priority != L )'  list
```
Do I use it wrong to filter for tags?
Or is it not supported to use multiple tags on a task object?

even if is use a colon (`tag:bar`)  or `tag is bar` it will not work as i aspect.

**Comment by bradyt** [comment]
I'll leave it for others to comment on whether to expect this behavior in Taskwarrior. If you're just wondering how most people filter by tag, you can try `task +foo` and `task +bar`.

**Comment by tobiasdroessler** [comment]
ahh 🤣 . now i understand. 👍 🧠 
Its is a strange syntax for me.  The `+` seems to me like a *modifier*, a write operation. Like "add there a tag" or "remove a tag" when minus (`-`) is used. This works i note here. But i will mention, that not intuitive in my thoughts. I am not sure if its explicit noted in the docs/man. 

@bradyt Thanks a lot for explanation, feel free to close this issue.

**Comment by angelus2014** [comment]
They are modifiers, in relation to the command you're giving the task command. The `+` adds the requested tag to the list/overview/report that you want to generate. The `-` removes that tag.

**Comment by bradyt** [comment]
I think I figured out why the notation you expected, did not work.

Note that, while `task tag:bar` does not work, `task tag.has:bar` does. As well as `task tag:foo,bar`, and `task ta.has:b` and `task tags:foo,bar`. The attribute `tags` has a list value. But it can be abbreviated as `tag` or `ta`.

In newer Taskwarrior, you can do `task tag ~ bar`, or even `task ta ~ b`. See https://taskwarrior.org/support/faq.html#q14.

> I am not sure if its explicit noted in the docs/man.

There's an example early in the man page with a `+weekend` filter. And the man page links to <https://taskwarrior.org>, where tag filters are mentioned, for example at <https://taskwarrior.org/docs/syntax.html>.

**Comment by smemsh** [comment]
i'm using `tags.word:<tag>` and `tags.noword:<tag>` as filters for export, to mean closest thing to tag membership, but maybe `has` is doing something special when it's a list type and is a better choice

**Comment by bradyt** [comment]
I think `task tags.word:<tag>` may not work with Cygwin's Taskwarrior 2.4.4-1.

You might be able to build current stable Taskwarrior on Cygwin. I think the last time I did that, it was 2.5.3. Current is 2.6.2.

**Comment by tobiasdroessler** [comment]
I think this topic can be closed..  was some kind of misunderstanding the CLI argument syntax.
