### ISSUE TITLE
Clean up dev documentation

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#2868]
I merged some development docs into this repo, but as a "forklift import" -- they now need some more detailed attention:
 * We have `doc` and `docs`; let's just use `doc` since it was here already
 * `./README.md` and `docs/contrib/branching.md` specify different branching models
 * `./docs/index.md` should be `README.md` so GitHub shows it, and should contain a nice, navigable index of the directory
 * `./taskchampion/docs` should be moved to `doc` and generally joined in there.  And the `mdbook` support removed.
 * Generally let's make this more concise and approachable.

**Comment by djmitche** [comment]
In progress :)

**Comment by ryneeverett** [comment]
I think this should be reopened because it isn't complete yet. Remaining are:

- [ ] `git mv taskchampion/docs/src doc/devel/taskchampion`
- [ ] Implement mdbook over the entire `doc/` directory (and enable github pages on this repo so it is actually useful).

**Comment by djmitche** [comment]
Agreed, thanks!

**Comment by ryneeverett** [comment]
Reading through recent discussion in #3209, I think there's a bit of tension between the two motives -- release of 3.0 and separation of taskchampion into a separate repo. My thinking behind adding this to the 3.0 milestone is that a major release often attracts new contributors...if they can figure out how. Right now I don't think it's at all easy for somebody to land on the github page and figure out how to hack on the rust portion of the project. We need a unified developer story that guides people in the right direction. Continuing down this road of unification though might be counterproductive if we're going to separate them again but I suppose a heavy interlinking between taskwarrior/taskchampion developer docs would be ideal even if they are in separate repos.
