### ISSUE TITLE
[taskchampion] Support setting aribtrary k/v's in a task

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#2875]
(see https://github.com/taskchampion/taskchampion/issues/348)

**Comment by djmitche** [comment]
@mx-psi FYI (I forgot issues can't be transferred between orgs, so a link is the best I've got)

**Comment by mx-psi** [comment]
> @mx-psi FYI (I forgot issues can't be transferred between orgs, so a link is the best I've got)

Works for me :) Can you assign this to me?

**Comment by djmitche** [comment]
done :)
