### ISSUE TITLE
[taskchampion] Implement due dates

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#2879]
See https://github.com/taskchampion/taskchampion/issues/82

In the context of Taskwarrior, this only entails adding due-date-related methods to Task and TaskMut.

**Comment by Treenhan** [comment]
Hi @djmitche can I work on this one?

**Comment by djmitche** [comment]
Yes you can!

**Comment by Treenhan** [comment]
Hi @djmitche I created a PR, could you take a look? https://github.com/GothenburgBitFactory/taskwarrior/pull/3145
