### ISSUE TITLE
[TW-247] recur tasks design problem with merge

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#290]
_Zed Jorarard on 2013-12-09T16:46:41Z says:_ 

 what we see in this testcase is:

i create a recurring task, and use libfaketime to see how it evolves over days with 2 machines involved. each recurrence gets created twice, naturally i would expect to have only one occurrence of each recurrence of the task. i dont know if this doesnt happen with taskd or if this is fixable if ssh merge is used.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-12-09T16:46:41Z
Modified: 2014-02-09T18:45:39Z
```

**Comment by taskwarrior** [comment]
_Zed Jorarard on 2013-12-09T16:48:00Z says:_ 

 i forgot... taskwarrior 2.2.0

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-08T04:20:03Z says:_ 

 The merge command is deprecated, and will be removed in a future release.  There is no longer anyone supporting this part of the code.

Your expectation is correct - there should be only one recurring task created per day (in this case).  I suspect that recurrence does not properly update the undo.data file for the template task, when a new recurring task is created.

Moved to 2.4.0 where it should be addressed.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-02-09T18:45:39Z says:_ 

 The 'merge' command is gone in 2.4.0.

**Comment by pbeckingham** [comment]
[TW-247_testcase-1468.sh.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755565/TW-247_testcase-1468.sh.txt)
