### ISSUE TITLE
ISO week starts on wrong day in task calc output

### ISSUE THREAD

**Issue by smemsh** [GothenburgBitFactory/taskwarrior#2922]
ISO weeks always start on Monday.  This date is wrong (2.6.2):

```
$ task calc 2022-W32
2022-08-07T00:00:00
```
the date should be the 8th, not the 7th.  the 7th is a Sunday:
```
$ ncal 8 2022
    August 2022       
Mo  1  8 15 22 29   
Tu  2  9 16 23 30   
We  3 10 17 24 31   
Th  4 11 18 25      
Fr  5 12 19 26      
Sa  6 13 20 27      
Su  7 14 21 28      
   31 32 33 34 35   
```
we can see the correct crossover point here:
```
$ date -d 2022-08-07T00:00:00 +%V
31

$ date -d 2022-08-07T23:59:59 +%V
31

$ date -d 2022-08-08T00:00:00 +%V
32
```

So, the week is starting on the wrong day, it should be Monday 
https://en.wikipedia.org/wiki/ISO_week_date

**Comment by tbabej** [comment]
Thanks for the bug report. Looks like the underlying problem is that this date format respects the setting of the `rc.weekstart` when it should not:

```
$ task rc.weekstart=Monday calc 2022-W32
2022-08-07T00:00:00
Configuration override rc.weekstart=Monday
```

EDIT: No, the answer is still incorrect (and same as without the override). My eyes deceived me.

**Comment by smemsh** [comment]
right, not sure it's the right code, but I just found this:
``` cpp
int Datetime::week () const
{
  struct tm* t = localtime (&_date);

  char weekStr[3];
  if (Datetime::weekstart == 0)
    strftime (weekStr, sizeof (weekStr), "%U", t);
  else if (Datetime::weekstart == 1)
    strftime (weekStr, sizeof (weekStr), "%V", t);
  else
    throw std::string ("The week may only start on a Sunday or Monday.");

  int weekNumber = strtol (weekStr, nullptr, 10);
  if (weekstart == 0)
    weekNumber += 1;

  return weekNumber;
}
```
and I do have `weekstart=monday` set btw,`task show` confirms it.  Still gives the incorrect date as you pointed out.  It should switch depending on weekstart though according to above code in libshared (i'm at 072e0e0 libshared which is the one pegged from stable), hmm.

**Comment by smemsh** [comment]
Possibly related issue GothenburgBitFactory/timewarrior#595
