### ISSUE TITLE
Missing audit rust dependancies. It might be a security issue in my forked repo

### ISSUE THREAD

**Issue by mapalochibwe** [GothenburgBitFactory/taskwarrior#2947]
#### To report a bug...

* Run a pull request and requested a merge
* A successful merge to update commits 
* Gave the error
* ```security all jobs have failed``` 

#### To request a feature...

* Clearly describe the feature.
* Clearly state the use case. We are only interested in use cases, do not waste time with implementation details or suggested syntax.
* Please see our notes on [How to request a feature](https://taskwarrior.org/docs/features.html)

**Comment by djmitche** [comment]
I think we figured out that this was an issue with running CI on a forked copy of the repo, with issues disabled.

**Comment by mapalochibwe** [comment]
Noted thanks.
