### ISSUE TITLE
[TW-253] Unrecognized taskwarrior file format. in /Users/user/Dropbox/.task/completed.data at line 1

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#296]
_Kosta Harlan on 2013-06-20T15:58:50Z says:_ 

 I've been getting this error off and on over the last few months.

I wish I could say I knew how to reproduce the problem but I don't. pending.data and undo.data don't get corrupted, just completed.data. It occurs seemingly at random when I complete a task, and probably happens 1-4 times a week.

Do you have any ideas on how to debug this? Could it be related to Dropbox? I hesitate to test that theory because restoring from previous versions via Dropbox has saved me every time.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-06-20T15:58:50Z
Modified: 2016-02-28T11:02:08Z
```

**Comment by taskwarrior** [comment]
_Kosta Harlan on 2013-06-20T16:02:54Z says:_ 

 I should also note that I use bugwarrior (https://github.com/ralphbean/bugwarrior), which interacts with TW data by calling TW via subprocess calls. At one point I thought it might be an issue with rapid, successive CRUD operations (sometimes 4-5 tasks get added or deleted at once) but after adjusting the code to add a .2 second delay in-between CRUD calls to TW, I'm still seeing the problem.

**Comment by taskwarrior** [comment]
_Kosta Harlan on 2013-06-20T16:08:54Z says:_ 

 Here are the first few lines of a corrupt completed.data file (I added the line breaks in between lines for readability):
<pre>

**Comment by taskwarrior** [comment]
_Kosta Harlan on 2013-06-20T16:10:27Z says:_ 

 Here are the first few lines of a corrupt completed.data file (line breaks added by me for readability):

**Comment by taskwarrior** [comment]
_Kosta Harlan on 2013-06-20T16:12:14Z says:_ 

 Sorry for the multiple posts. Here's a file since I can't get the text to post on the issue.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-09-29T18:14:04Z says:_ 

 I hesitate to blame dropbox, but I have never seen this before.  I believe that bugwarrior is doing everything properly.

**Comment by taskwarrior** [comment]
_Kosta Harlan on 2013-10-04T15:48:38Z says:_ 

 About a month ago I stopped using Dropbox for syncing my task data and haven't encountered this problem again.

**Comment by taskwarrior** [comment]
_Kosta Harlan on 2014-04-23T00:57:53Z says:_ 

 With this patch, I can find problem rows in my task data, for example with `task sync rc.debug=1`. Without this patch, I only get an error of "Unrecognized taskwarrior file format".

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-05-13T04:37:05Z says:_ 

 Thanks Kosta.

**Comment by taskwarrior** [comment]
_Konstantin on 2016-02-28T11:02:08Z says:_ 

 Have similar problem with task 2.5.1, taskd 1.2.0 (snapshot)

Today, I've played with tasks with multiple annotations and experienced same problem multiple times. completed.data got line looking like:

{code}
[]
{code}

after sync of pending task with few annotations.

**Comment by pbeckingham** [comment]
[TW-253_corrupted-completed.data.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755567/TW-253_corrupted-completed.data.txt)
[TW-253_unrecognized-file-format-debug.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755568/TW-253_unrecognized-file-format-debug.patch.txt)
