### ISSUE TITLE
[Question] To contribute, are pull requests allowed?

### ISSUE THREAD

**Issue by pianocomposer321** [GothenburgBitFactory/taskwarrior#2991]
The contributing instructions still says to submit patches via email...now that the project is on github, is forking and PR-ing ok?

**Comment by tbabej** [comment]
Hi @pianocomposer321, PRs are definitely allowed and encouraged :slightly_smiling_face:

**Comment by djmitche** [comment]
A PR to fix that instruction would be useful, too!
