### ISSUE TITLE
Modifying the context should modify all tasks matching the context

### ISSUE THREAD

**Issue by sofomryu** [GothenburgBitFactory/taskwarrior#3022]
I set a context with a project and a tag.
I hope to modify the project's name and the tag of the context, but 'task mod project:"newer name" ' creates another task which is not included in the context.
Adding a task still shows older project name in the context.
How can I change properties of a project and a tag in the context?

I also tried edit ~/.taskrc file. it can change the project and tag name of a context, however the changed context doesn't include tasks that were included before the change.

**Comment by tbabej** [comment]
Hi @sofomryu, I'm having trouble following the sequence of events here. Could you please provide a more detailed reproduction script, ideally with the bash commands and (un)expected output? :pray:

**Comment by sofomryu** [comment]
> Hi @sofomryu, I'm having trouble following the sequence of events here. Could you please provide a more detailed reproduction script, ideally with the bash commands and (un)expected output? 🙏

1. Define context 
`task context define example_context proj:example_project +example_tag`

2. Set the context
`task context example_context`

3. Add a task
`task add example_task`

4. Modify the project name and tag name of the context
`task context define example_context proj:modified_proj +modified_tag`
or
`task context example_context mod proj:modified_proj +modified_tag`

Expected result:
`task`
Project: modified_project Tag: modified_tag Description: example_task
(so, I want to change project and tag properties conserving the tasks in the example_context)

What I get instead:
`task`
There is no task in the example_context with proj:modified_project tag:modified_tag.
If I set `task context none`
Project: example_project Tag: example_tag Description: example_task

**Comment by dathanb** [comment]
So the expectation is that modifying the tags and/or project on a context propagates the same modification to all tasks that match the original context's filter?

**Comment by sofomryu** [comment]
> So the expectation is that modifying the tags and/or project on a context propagates the same modification to all tasks that match the original context's filter?

yes, exactly

**Comment by tbabej** [comment]
Context is a temporary filter applied to all queries. If you want to modify all tasks in a given context, you can just do:
```
task mod proj:modified_project -example_tag +modified_tag
```

followed by redefining the context:
```
task context example_context mod proj:modified_proj +modified_tag
```

I would argue this is relatively concise as is, and more importantly explicit. Merging the two behaviors together could confuse users. What if I errorneously define a context that matches a lot of my tasks and then I change it? I would unintentionally modify a lot the tasks in my database.

I will close this for now, but if people feel differently about this proposal, please keep the discussion flowing and we can always re-open :slightly_smiling_face:
