### ISSUE TITLE
Context define requires manual confirmation

### ISSUE THREAD

**Issue by dbv-rl** [GothenburgBitFactory/taskwarrior#3037]
#### To request a feature...

- When adding/changing a context, the CLI asks for confirmation:

```bash
$ task context define testing +test
Are you sure you want to add 'context.testing.read' with a value of '+test'? (yes/no) y
Are you sure you want to add 'context.testing.write' with a value of '+test'? (yes/no) y
Context 'testing' defined (read, write). Use 'task context testing' to activate.
```

- I'd like to request a way of skipping that interactive part in order to be able to use the commands in scripts/automation.
- The current workaround for me is to edit the `.taskrc` file directly.
- This example command (not working!) should help to clarify the intention.

```bash
$ task context define --assume-yes testing +test
```

- If this is already in place, please point me to the right place in the documentation. I wasn't able to find it.

**Comment by dathanb** [comment]
I'm pretty sure `context define` respects the `confirmation` setting. So you can specify it on the command line to override per invocation. e.g.:
```
$ task rc.confirmation=0 context define testing +test
Context 'testing' defined (read, write). Use 'task context testing' to activate.
Configuration override rc.confirmation=0
```

And now the context is set in my .taskrc, and I didn't have to do any manual confirmation:
```
$ cat ~/.taskrc
...
context.testing.read=+test
context.testing.write=+test
```

**Comment by dbv-rl** [comment]
Yes, Thank you, that works as described.
