### ISSUE TITLE
Since fish v.3.6.0 TW completions only work partially

### ISSUE THREAD

**Issue by angelus2014** [GothenburgBitFactory/taskwarrior#3048]
Hello,

I've noticed that since fish v.3.6.0 the TaskWarrior completions only work once.

* What command(s) did you run?
task add test pro<TAB>
task mod pro<TAB>(then it completes) +soft<TAB>(now I expected it to complete to software, but it doesn't)
any task command actually
* What did you expect to happen?
To properly complete as it used to before version 3.6.0 of fish
* What actually happened?
Only the first complete seems to work, none of the following
* Paste the output of the ```task diag``` command.
❯ task diag

task 2.6.2
   Platform: Darwin

Compiler
    Version: Apple LLVM 13.1.6 (clang-1316.0.21.2.5)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.24.1
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.7.7
 Build type: Release

Configuration
       File: /Users/angelo/.taskrc (found), 2307 bytes, mode 100644
       Data: /Users/angelo/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
  rc.editor: hx
     Server:
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /Users/angelo/.task/hooks
             (-none-)

Tests
   Terminal: 247x72
       Dups: Scanned 497 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 497 tasks for broken references:
             No broken references found

I have not noticed problems with completions for other applications, only TaskWarrior.

---
With regards,

Angelo Machils

**Comment by hdak1945git** [comment]
Sadly, I can only confirm a similar issue on Arch Linux (task 2.6.2-1 and fish 3.6.0-1).

I did compile 3.5.1 from the fish-shell repository--and I can confirm that version still works properly with taskwarrior's completion script.

Below are a few notable scenarios:

* `task +`, `task +O` and `task +OV` does not provide the expected `+OVERDUE` completion on 3.6.0
* `task project:` lists available projects names, as expected.
* `task add project:` differs between 3.5.1 and 3.6.0 -- in 3.6.0, instead of available project names, the name of every file in the current working directory are shown instead (with `project:` prefixes).

**Comment by angelus2014** [comment]
Interesting, I copied the task.fish file from this Gist:https://gist.github.com/tgray/5632282 to .config/fish/completions and it's working correctly again. If I try this with the 'official' task.fish, it doesn't.......

[edit] Well, not all completions work properly all the time, but at least it's better than with the 'official' task.fish.

**Comment by with9** [comment]
change `printf  -- '+%s\n' $tags` to `printf  '+%s\n' -- $tags` may partially solve the problem

**Comment by hdak1945git** [comment]
I've tried @with9's suggestion, and (unwittingly) produced an identical solution to @Werkov's pull request -- I can happily report that auto-completion works again under fish 3.6.0 with these changes.

**Comment by angelus2014** [comment]
It only 'fixes' things partially. For example `task add 'Test' pro` and then 'TAB' doesn't call any completions. If I add the 'Test' task without any information and then 'mod' the task, then the completions work.
With the old completions file from Mick Koch, it works as expected......

If I download the whole file from that pull request, then it also works. It seems that the "--" shouldn't be used anymore, at all, so the change from `printf  -- '+%s\n' $tags` to `printf  '+%s\n' -- $tags` won't work. It should be changed to `printf  '+%s\n' $tags`. There are several places in the current completion file where things have to change.

[EDIT] Spoke too soon, the first completion now works, but a second doesn't. So for example: `task add 'Test' pro TAB` works and gives me a list of the possible projects. But if I also want to add more (let's say tags), it doesn't work..... And again, if I revert to the old completions file from Mick Koch, it works as expected.


---
With regards,

Angelo Machils
