### ISSUE TITLE
Taskserver docs

### ISSUE THREAD

**Issue by fecet** [GothenburgBitFactory/taskwarrior#3067]
Where to find all docs under https://taskwarrior.org/docs/taskserver/ like https://taskwarrior.org/docs/taskserver/configure/ ? I found they are more useful and easy to read than the slide in main docs.

**Comment by dathanb** [comment]
I think they're at the [tw.org](https://github.com/GothenburgBitFactory/tw.org) repo. In particular, the content for https://taskwarrior.org/docs/taskserver/configure/ looks like it's at https://github.com/GothenburgBitFactory/tw.org/blob/master/content/docs/taskserver/configure.md

**Comment by fecet** [comment]
Thank you!
