### ISSUE TITLE
ArchLinux taskwarrior package didn't install the tw color themes. Made a repo for it.

### ISSUE THREAD

**Issue by jrcharney** [GothenburgBitFactory/taskwarrior#3069]
I've been really enjoying taskwarrior lately to organize my work, but I noticed one feature that didn't get included with the `task` package with my Linux repo.  Since it is Arch Linux, I checked the AUR and didn't find any separate package.  I couldn't find a `/usr/share/task` or `/usr/share/taskwarrior` directory.  And I checked `~/.task` if there was a `theme` directory.  I didn't find anything.

The good news is that I found a copy of the standard color themes that `man task-color` mentioned.

I decided to make my own repo for these color themes. Eventually, I'd like to add my own themes. (I'm quite partial to the dark-violets-256 theme, though I might want to modify it to still use the standard priority colors.)  I'm also thinking about writing a script to colorize tags as well as write something that would take in some color swatch and generate a theme from like four or five colors.

At any rate, if anyone else has this problem where they can't find the themes, feel free to clone [this repo](https://github.com/jrcharney/taskwarrior-themes).

**Comment by skbolton** [comment]
The themes show up at /usr/share/doc/task/rc/ if I recall correctly

**Comment by tbabej** [comment]
Hi @jrcharney, thanks for reporting this! The sources for the themes can be generally [found here](https://github.com/GothenburgBitFactory/taskwarrior/tree/develop/doc/rc), however, whether the Arch Linux package ships them or not is outside of our control. The TW team currently does not package the software directly, this is done by community volunteers (which differ from distro to distro).

Looking at the details of the [`task` package for Arch](https://archlinux.org/packages/community/x86_64/task/), it indeed does look like @skbolton is correct - if you expand the "Package Contents" section, you can see that themes should be shipped with a `usr/share/doc/task/rc/` prefix.
