### ISSUE TITLE
There is a typo on the official examples: `tsk` -> `task`

### ISSUE THREAD

**Issue by hakan-demirli** [GothenburgBitFactory/taskwarrior#3079]
There is a typo on the official examples page.

Page: https://taskwarrior.org/docs/examples/
Typo:

* **Show tasks in This project or That project.**
    * ```$ tsk project:This or project:That list```
   
It should have been ```task``` not ```tsk```

There is also an unnecessary space:
* **What are all the tags I have ever u sed?**
    * ```$ task rc.list.all.tags=1 tags```

``` u sed``` -> ```used```

**Comment by dathanb** [comment]
I've submitted a PR to fix both: https://github.com/GothenburgBitFactory/tw.org/pull/494

**Comment by dathanb** [comment]
That PR has been merged, so I think this issue can be closed.
