### ISSUE TITLE
how to remove a task from taskwarrior's record

### ISSUE THREAD

**Issue by wensdong** [GothenburgBitFactory/taskwarrior#3093]
#### To report a bug...

* What command(s) did you run?
* What did you expect to happen?
* What actually happened?
* Paste the output of the ```task diag``` command.

#### To request a feature...

* Clearly describe the feature.
* Clearly state the use case. We are only interested in use cases, do not waste time with implementation details or suggested syntax.
* Please see our notes on [How to request a feature](https://taskwarrior.org/docs/features.html)

**Comment by tbabej** [comment]
Hi @wensdong, you can use `task purge` to permanently remove a task. Note that task must be deleted first.

**Comment by KingJulianS** [comment]
Hi, i added a task, added 3 annotations, then denotated 1, eventually deleted the task, then purged the task, but I see the annotation details are still in the data files. How do I completely get rid of this data ? I assumed that purge will actually delete and remove all the associated data?

**Comment by djmitche** [comment]
See also #3399.
