### ISSUE TITLE
taskd package missing in Debian bullseye (current stable)

### ISSUE THREAD

**Issue by dniku** [GothenburgBitFactory/taskwarrior#3100]
`taskd` is [available](https://packages.debian.org/search?keywords=taskd) in `buster` (oldstable), `bookworm` (testing), and `sid` (unstable), but not in `bullseye` (stable). Would it be possible to provide `taskd` for `bullseye`?

**Comment by djmitche** [comment]
I believe that is up to the Debian package maintainers, rather than the Taskwarrior authors. I see some likely names [here](https://metadata.ftp-master.debian.org/changelogs//main/t/taskd/taskd_1.1.0+dfsg-3_changelog), but perhaps filing an issue on the Debian bug tracker is the right first step?

**Comment by djmitche** [comment]
Taskd is deprecated at this point (#3293).
