### ISSUE TITLE
Segfault when `data.location` set to inaccessible path

### ISSUE THREAD

**Issue by eddsalkield** [GothenburgBitFactory/taskwarrior#3103]
#### To report a bug...

* What command(s) did you run?
`task list`

* What did you expect to happen?
Listing the tasks

* What actually happened?
`Segmentation fault`

* Paste the output of the ```task diag``` command.
```
edd@henleybeach:~$ task diag
Segmentation fault
```

This occurs when the following is set in the config file:

```
data.location=/task/
```

When this directory does not exist

**Comment by dathanb** [comment]
I can't reproduce this on the latest `develop` branch on Mac OS:
```
$ echo "data.location=/task/" > bad-taskrc
$ cmake-build-debug/src/task rc:bad-taskrc list
TASKRC override: bad-taskrc
Could not create replica at /task/: Read-only file system (os error 30)
$ echo "data.location=~/no-such-dir" > bad-taskrc
$ cmake-build-debug/src/task rc:bad-taskrc list
TASKRC override: bad-taskrc
No matches.
Recently upgraded to 2.6.0. Please run 'task news' to read highlights about the new release.
$ ls ~/no-such-dir
taskchampion.sqlite3
```

**Comment by eddsalkield** [comment]
Thanks for looking into this. I also can no longer reproduce the issue. I'll close it for now, and if someone comes across it again they can reopen it.
