### ISSUE TITLE
Most strings including Scandinavian letters fail - while some are accepted

### ISSUE THREAD

**Issue by kobolttti** [GothenburgBitFactory/taskwarrior#3113]
Most tasks and annotations including Scandinavian letters "ä" (a with two dots) and "ö" (o with two dots) are failing:

$ task add ä
Unknown error. Please report.
$ task add Longer description with ä letter
Unknown error. Please report.
$ task add Wondering if this will work aÄa
Created task 24.
$ task add Ä
Unknown error. Please report.
$ task anno 24 Same Ä problem here
Unknown error. Please report.
$ task anno 24 aÄ
Unknown error. Please report.
$ task anno 24 aÄa
Annotating task 24 'Wondering if this will work aÄa'.
Annotated 1 task.

Error is not random but depends on the string used.

Same errors with Ubuntu 22.04.2 LTS distributed task 2.6.1 and locally compiled task 2.6.2:

$ task diag

task 2.6.1
   Platform: Linux

Compiler
    Version: 11.2.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.18.4
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.7.1
 Build type: None

$ ./task diag

task 2.6.2
   Platform: Linux

Compiler
    Version: 11.3.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.22.1
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: n/a
 Build type: release

Does not seem to be dependent on localization settings. Tested with LC_ALL="en_US.ISO-8859-15" and LC_ALL="en_US.UTF-8".

**Comment by djmitche** [comment]
Huh, I can't reproduce.

That message is coming from the final `catch` in `src/main.cpp`. Could you try just removing that clause? Maybe you'll get a better error message.

**Comment by kobolttti** [comment]
It's actually first hitting Context.cpp line 677 (where there is also a typo on ver 2.6.2):
    error ("knknown error. Please report.");

Commenting both that and main.cpp catch out I'm getting:

$ ./task add ä
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 3) > this->size() (which is 1)
Aborted

**Comment by kobolttti** [comment]
Compiled task 2.6.2 on another Ubuntu server. Issue reproduces there with no existing configuration file and directory.

**Comment by djmitche** [comment]
Hm, that helps a bit - I bet with both `catch ( ... )` in place, the first one triggers, and then because that doesn't do an early return, something in the following `if (rc) { .. }` throws another exception. So after removing both, the exception you've shown is the "original" exception.

Two things to try:
 - add some `count << "GOT HERE 1\n";` in `src/Context.cpp` to figure out where it's failing. I would guess somewhere in [this range](https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/src/Context.cpp#L620-L649).
 - restore the `catch` in `src/Context.cpp` and enable the configs that would cause it to show debug/verbose output. I think that's `debug 1` and `verbose affected,blank,context,edit,header,footnote,label,new-id,project,special,sync,override,recur`. The results might give a clue.

**Comment by kobolttti** [comment]
I have followed this all the way to bool Lexer::token (std::string& token, Lexer::Type& type) in Lexer.cpp.

It fails within the isXxxx checks in this if: https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/src/Lexer.cpp#L75-L92. I still need to add some more debug outputs to find out which check is the failing one. I'll get back on this soon.

**Comment by kobolttti** [comment]
Issue lies at Lexer.cpp line 493 (https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/src/Lexer.cpp#L493):

"if (iso.parse (_text.substr (_cursor), iso_i, Lexer::dateFormat))"
and more specifically in 
"_text.substr (_cursor)" where
_text = ä
_cursor = 3
-> obviously substr will fail.

Furthermore:
- For "task add ä" _cursor = 3
- For "task anno 1 ä" _cursor = 4
- For "task testing ä" _cursor = 7

So it seems _cursor is not set correctly for the length of "ä" but has the length of the previous string.

Now where this should be fixed?

**Comment by djmitche** [comment]
Nice work!!

I once tried to figure out the command-line parsing stuff and got pretty lost, so I'm no expert. But, I suspect `cursor` in this case is the part that's been parsed so far, as `s.substr(x)` with one argument takes the string beginning at position `x` (similar to Python's `s[x:]`. But it looks like in this case the prefix has already been removed from `_text`.

I still wonder why I can't reproduce this!

```
✖ sofia ~
⸩  task add testing ä
Created task 87.
✖ sofia ~
⸩  task add ä
Created task 88.
```

**Comment by kobolttti** [comment]
What are your LC/localization settings?

**Comment by djmitche** [comment]
```
⸩ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by kobolttti** [comment]
Same issue even with your localization settings. I'm also puzzled what is the difference here.

**Comment by djmitche** [comment]
I wonder if this has to do with the normalization form? But it seems not:
```
✖ sofia ~/p/taskwarrior ⸨working-branch⸩
⸩ ./src/task add $(python -c 'print("\u00e4")')
Created task 4.
✖ sofia ~/p/taskwarrior ⸨working-branch⸩
⸩ ./src/task add $(python -c 'print("\u0061\u0308")')
Created task 5.
```

**Comment by djmitche** [comment]
@kobolttti I copy-pasted your text, which may have changed the unicode form. Just to be sure we're passing exactly the same input to `task`, can you type (not copy/past):

```
echo ä | xxd
```

I get 
```
⸩ echo ä | xxd
00000000: c3a4 0a                                  ...
```
which decodes from utf-8 as the single character U+00E4; the `0a` is a newline

**Comment by kobolttti** [comment]
@djmitche that could very well explain!
```
$ echo -n ä | xxd
00000000: e4                                       .
```

Furthermore:
```
$ export LC_ALL=en_US.ISO-8859-15
$ task add ä
Unknown error. Please report.
$ echo -n ä | xxd
00000000: e4                                       .
$ task add $(python3 -c 'print("\xe4")')
Unknown error. Please report.
$ echo $(python3 -c 'print("\xe4")') | xxd
00000000: e40a                                     ..
$ task add $(python3 -c 'print("\u00e4")')
Unknown error. Please report.
$ echo $(python3 -c 'print("\u00e4")') | xxd
00000000: e40a                                     ..

$ export LC_ALL=en_US.UTF-8
$ task add ä
Unknown error. Please report.
$ echo -n ä | xxd
00000000: e4                                       .
$ task add $(python3 -c 'print("\xe4")')
Created task 25.
$ echo $(python3 -c 'print("\xe4")') | xxd
00000000: c3a4 0a 
$ task add $(python3 -c 'print("\u00e4")')
Created task 26.
$ echo $(python3 -c 'print("\u00e4")') | xxd
00000000: c3a4 0a                                  ...
```

So it has to do a bit with localization after all. But extended ASCII chars are causing the failure?

**Comment by djmitche** [comment]
Ah, that makes some sense. I don't understand locale settings too well on Linux, so I apologize!

Judging by the source linked earlier (https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/src/Lexer.cpp#L493) it seems like Taskwarrior is assuming that the command-line is in UTF-8. I'm not sure if that's legitimate? Or easy to fix?

**Comment by kobolttti** [comment]
If by easy to fix you mean I should finally move to Unicode, then you're right! :)

And no worries, my understanding of locale settings / character encoding was also stuck to late 90s. At that time ISO-8859-15 was the encoding with least problems on Linux systems with Scandinavian character maps. As I had no problems with it until now I had never reconsidered UTF-8. Also, I have quite a few files that are ISO-8859 encoded that I now need to convert while moving to UTF-8.

The reason why I had the issue also with UTF-8 locale settings is that my (SSH) terminal was still set to ISO-8859-15. Changing both the terminal character set and the system locale to UTF-8 fixed the issue.

I guess that in Taskwarrior my old settings were working until versions 2.4.x as the Unicode parser was released in version 2.5.0.

Many thanks for helping me out!

**Comment by kobolttti** [comment]
Taskwarrior uses Unicode: https://taskwarrior.org/docs/unicode/

Locale (and terminal) settings needs to be set to UTF-8 for non-ASCII characters to work properly.

**Comment by djmitche** [comment]
FWIW "easy fix" didn't mean to suggest you change your usage, although if that gets Taskwarrior working for you again, great!

It seems that Taskwarrior's parser is "hand built" and doesn't use any pre-existing libraries that could be configured to consume ISO-8859-15 instead of UTF-8.
