### ISSUE TITLE
Automate synchronization of MSRV

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3142]
We've already got a number of places we specify the minimum supported Rust version (MSRV), and will probably add a few more.

Let's add a function to `cargo xtask` to update the MSRV everywhere it appears, and run that in CI with a `diff` to ensure it's up-to-date. We already do something similar to generate and diff `taskwarrior.h`, so follow that pattern.

**Comment by iwyatt** [comment]
Hi Dustin! I saw you are working on integrating TaskChampion into TaskWarrior and its also developed in Rust! I'm interested in all those things and as I'm learning Rust, might want to lend a hand if able (I'm not a professional programmer but eager to cut my teeth on "intern-level" type work).

I hope to replace my current task manager someday and I see a lot of potential in the TaskWarrior/Champion ecosystem. 

I wouldn't want to be a burden to anyone (I realize I might need some guidance), but am curious if you think this would be a good issue for me to lend a hand?

**Comment by ryneeverett** [comment]
FWIW I also took a look at this and determined it's not a sufficiently entry-level task for me. Seems like either it's mislabeled (as "good first issue") or more elaboration is needed.

**Comment by djmitche** [comment]
Sure, and I'm happy to provide guidance :)

There's a nice readme at [cargo-xtask](https://github.com/matklad/cargo-xtask) that describes how this fits together. Briefly:
 * The `cargo` command looks in [`.cargo/config`](https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/.cargo/config) for aliases for subcommands. In this repo, `cargo xtask ...` is translated to `cargo run --package xtask -- ...`
 * This runs the crate in this repo called `xtask` (https://github.com/GothenburgBitFactory/taskwarrior/tree/develop/taskchampion/xtask).
 * The `xtask` crate just has a `main.rs` which is a regular command-line program. It's very short and hopefully pretty easy to understand. Right now, it has a single subcommand `codegen` (so, `cargo xtask codegen`) which results in a call to the `codegen` method.

The goal for this issue would be to add code to that `main.rs` to support another subcommand, `cargo xtask msrv X.Y` which updates all of the places in the repo where the MSRV occurs (`git grep MSRV` will show you where those are) to contain `X.Y`. This will require
 * A little bit more command-line parsing. What exists right now is done by hand, but `clap` is a popular CLI crate that could be used for this purpose.
 * Some filesystem and string-related work to substitute the new MSRV into the relevant text files.  The standard library should suffice here, but it's fine to add other dependent crates if they're useful. I think it will be fine to hard-code the list of files that need to be changed, rather than scanning all files in the repo.

If you want to get a start by making a PR that adds a new `msrv` subcommand which just prints "Hello World", that might be a nice first step to get any `xtask`-related complexity out of the way. Once that's done, we can work on the filesystem and string stuff. Or, if you'd like to get the whole thing done in one go, that's fine too!

**Comment by djmitche** [comment]
(and while we're at it, https://rust-lang.github.io/rfcs/2495-min-rust-version.html means the MSRV can now be in Cargo.toml's, too)

**Comment by iwyatt** [comment]
Thanks for breaking it down, @djmitche - will take a look this upcoming week.

**Comment by ryneeverett** [comment]
For the record, I'm fairly bogged down at the moment and happy to let @iwyatt tackle this.

However, I wanted to clarify whether the MSRV referenced in `src/lib.rs` is necessary and idiomatic:

```rs
/* ...
# Minimum Supported Rust Version (MSRV)
 
This crate supports Rust version 1.64 and higher.

*/
```

Is string interpolation in the docs the normal way to communicate MSRV in rust? Is it really necessary or is it documented elsewhere? Wouldn't it be more typical for developers to look to the source of truth -- `Cargo.toml`?

**Comment by iwyatt** [comment]
Oh hey @ryneeverett - sorry if I stepped on your toes or "cut in line" here. I'm new to collaborating on bugs on open source projects, so may have missed some rules or expectations. Please (definitely!) feel free to offer corrective guidance and explain things to me like a I'm a know-nothing intern. 🤪

Also, I joined the Taskwarrior discord if you need to message me about anything. :)

**Comment by ryneeverett** [comment]
@iwyatt Not at all. By and large I think you'll find that people are thrilled if you "steal" work from them.

**Comment by djmitche** [comment]
MSRV has been a bit of an evolving thing -- it's only recently that the option actually became available in Cargo. So for a while it was more of a general concept, and including it in the docs made sense. I think it's still worth including there, especially if updating it is just a single command.

**Comment by iwyatt** [comment]
Hi @djmitche  - I added the `hello world` example as suggested and submitted a [draft PR](https://github.com/GothenburgBitFactory/taskwarrior/pull/3189). Let me know if my github workflow needs improving (again, this is the first time I've collaborated on an open source project). 

[edited]
[2023-10-10 19:42 UTC-8] I updated my pull request to handle a variety of CLI argument lengths, graceful exits, and fix formatting.

~~I was a little uncertain about :~~
~~1) the best way to parse arg1 and arg2 in a fault tolerant way, so I chose to be consistent by using the args().nth() function on line 12 of main.rs. I realize that I'll have to add a check to make sure unwrap() actually has a value in the next iteration and to gracefully handle errors.~~
~~2) whether to use borrowing (`&String` ) vs passing ownership. I don't think the args need modifying for this job, so passing ownership seems unnecessary, but explicitly borrowing might imply a need for main() to retain ownership for some reason. Might be splitting hairs for this kind of program, but wanted to let you know I thought about it and am open to guidance / best practices here.~~

Thanks for letting me contribute and taking the time to break down the task for me. 

Please let me know the next step you'd like me to take.

**Comment by iwyatt** [comment]
Played around a bit with parsing yml files using serde and serde_yaml to get the MSRV field/value from [the files with `MSRV`](https://github.com/search?q=repo%3AGothenburgBitFactory%2Ftaskwarrior+msrv&type=code), but didn't get to a workable solution yet. Trying to get key 'rust' without building structs for every parent in the yml tree, so will look at serde_yaml::Value() tomorrow. 

Did a cursory look at `clap` and seems better at preventing bad inputs than simply iterating over `Vec<String>`. Probably save this work for until after I figure out the parsing and updating of the yml files.

**Comment by djmitche** [comment]
Oops, sorry, I didn't see this before replying on the PR.

Parsing the YAML is a bit tricky, as you've seen, and modifying it and writing it back out correctly is even harder. Also, not all of the files that need modification are YAML. So for this task, it's probably best to just treat the files as text, and use comments to help figure out which part to edit.

**Comment by iwyatt** [comment]
No problem, and thanks for the guidance! I'll post future discussion to the [pr](https://github.com/GothenburgBitFactory/taskwarrior/pull/3189#pullrequestreview-1672792706) instead of here.

**Comment by iwyatt** [comment]
Q: Do I need to assign this issue to me and close it out now that the pr has been merged?

**Comment by djmitche** [comment]
Thanks for the reminder -- done!
