### ISSUE TITLE
Task warrior stops working after deleting all entries from completed.data

### ISSUE THREAD

**Issue by bjt-user** [GothenburgBitFactory/taskwarrior#3147]
```
task --version
2.6.2
```

```
$ cat /etc/os-release 
NAME="Arch Linux"
```

* What command(s) did you run?
```
echo "" > ~/.task/completed.data
```

* What did you expect to happen?
* 
Completely remove completed tasks, because `task completed purge` does not work.

* What actually happened?
Using the task command results in an error:
```
$ task
/usr/include/c++/13.1.1/bits/basic_string.h:1239: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)
```

* Paste the output of the ```task diag``` command.
```
$ task diag
/usr/include/c++/13.1.1/bits/basic_string.h:1239: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)
```

I think there should be a way to completely remove completed or cancelled tasks, so that you have a clean output when doing a `task all` command to also see "waiting" tasks.
Also it clutters up your system if you can't delete completed tasks.

**Comment by djmitche** [comment]
If you just delete the file, it will work. The blank long you are inserting
is invalid, causing the error.

**Comment by bjt-user** [comment]
Thank you @djmitche . That worked, great answer!

**Comment by djmitche** [comment]
BTW, the upcoming sync overhaul in 3.0 will eliminate these `.data` files. The new implementation of the task store automatically expires deleted tasks after they are unmodified for a while. So to get a similar effect you'd do something like `task delete status:done modified.before:-6m`
