### ISSUE TITLE
Disable sync / sync reminders

### ISSUE THREAD

**Issue by hawkins** [GothenburgBitFactory/taskwarrior#3149]
Hi all, I recently moved from one version of task warrior to another by compiling from source, and I found that my previous tasks in ~/.task were not found anymore. However, I saw the files were present, so I ran`task import ~/.task` to import the tasks. I now have the tasks present like I expected, but I also get a warning that my task sync is out of date and that sync is required:

```
$ task
< omitted >
8 tasks
There are 3975 local changes.  Sync required.
```

Trouble is, I don't sync these tasks, I don't have a server and don't need one. I don't have any sync related configuration in my ~/.taskrc, all it has is some UDA definitions and coefficients and a report config to show those UDAs.

How can I disable the warning to sync, or disable sync altogether, since I do not ever sync?

**Comment by djmitche** [comment]
FYI, it looks like you're using an unreleased version of Taskwarrior, and the schema by which the tasks are stored might change before the release (which can probably be worked around with `task export` / upgrade / `task import`).

I think removing `sync` from the `verbose` config will make that note go away. It's not new, but it counts a more fine-grained set of changes now so the number may be surprisingly large.

**Comment by hawkins** [comment]
Great shout, I probably forgot to check out a tag before compiling. I'll correct that while I'm at it, thank you!

I don't remember seeing the note at all before using this build, and I didn't know `verbose` was even a config setting either. I found setting it to either `no` or `report` gives me the behavior I want, but I don't see `report` listed on the [docs page for verbosity](https://taskwarrior.org/docs/verbosity/), so I don't know if that value means anything or not anyway. Thanks for your help!
