### ISSUE TITLE
Task diag mentions broken refs to nonexisten task, but it seems to exist. Weird

### ISSUE THREAD

**Issue by kwoot** [GothenburgBitFactory/taskwarrior#3151]
* What command(s) did you run?

Task diag mentions:

Broken ref: Scanned 1515 tasks for broken references:
             Task 0b5bcf14-fc3d-4a7f-b9e3-e23add088c15 depends on nonexistent task: [\"2ff29155-823c-4fb3-8c48-5874abe8201f\"]

$ task 2ff29155-823c-4fb3-8c48-5874abe8201f

Name          Value                               
ID            -                                   
Description   secret description 1
Status        Completed                           
Project       LPI
Entered       2021-03-31 13:52:01 (2.4y)          
Due           2021-04-07 13:52:16
End           2021-05-20 11:19:31                 
Last modified 2021-05-20 11:19:31 (2.2y)
Virtual tags  COMPLETED PROJECT UNBLOCKED         
UUID          2ff29155-823c-4fb3-8c48-5874abe8201f
Urgency         15                                

    project      1 *    1 =      1
    due          1 *   12 =     12
    age          1 *    2 =      2
                            ------
                                15

$ task 0b5bcf14-fc3d-4a7f-b9e3-e23add088c15

Name          Value                               
ID            21                                  
Description   secret description 2
Status        Pending                             
Project       LPI
Entered       2020-08-03 09:00:46 (3.0y)          
Last modified 2023-01-05 20:13:06 (7mo)
Virtual tags  PENDING PROJECT READY UDA UNBLOCKED 
UUID          0b5bcf14-fc3d-4a7f-b9e3-e23add088c15
Urgency          3                                
Reviewed      2020-10-05 09:04:07

    project      1 *    1 =      1
    age          1 *    2 =      2
                            ------
                                 3

Date                Modification                                                     
2023-01-09 14:37:12 Dependency on '2ff29155-823c-4fb3-8c48-5874abe8201f' deleted.    
                    Due deleted.                                                     
                    Dependency on '[\"2ff29155-823c-4fb3-8c48-5874abe8201f\"]' added.

* What did you expect to happen?

I do not understand why this is an error. Everything seems fine to me.

**Comment by djmitche** [comment]
This was a bug in how tasks were stored. The dependency was on `["2ff29155-823c-4fb3-8c48-5874abe8201f"]` (including the `[".."]`, and that's not a valid UUID. The newer versions of Taskwarrior (3.0+) do not have this issue.
