### ISSUE TITLE
Error code 34304 when editing in Vim

### ISSUE THREAD

**Issue by manoelpqueiroz** [GothenburgBitFactory/taskwarrior#3152]
Hi guys, I don't know when exactly this started and the outputs I get from Taskwarrior are preventing me to ascertain if this is a Taskwarrior issue or perhaps something I'm configuring wrong in my machine, but here it goes:

* What command(s) did you run?
  * `task <number> edit` to open external editor and add an annotation
* What did you expect to happen?
  * When exiting Neovim with `:x`, changes are updated and saved
* What actually happened?
  * Got the message `Editing failed with exit code 34304.`
  * Tried using `:wq` instead to close, still the same error
* Paste the output of the ```task diag``` command.

```
task 2.6.2
Platform: Linux

Compiler
Version: 13.1.1 20230429
Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
Compliance: C++17

Build Features
CMake: 3.26.3
libuuid: libuuid + uuid_unparse_lower
libgnutls: 3.8.0
Build type:

Configuration
File: /home/myuser/.taskrc (found), 6409 bytes, mode 100755
Data: /home/myuser/.task (found), dir, mode 40755
Locking: Enabled
GC: Enabled
$EDITOR: /usr/bin/nvim
Server:
CA: -
Certificate: -
Key: -
Trust: strict
Ciphers: NORMAL
Creds:

Hooks
System: Enabled
Location: /home/myuser/.task/hooks
(-none-)

Tests
Terminal: 141x71
Dups: Scanned 848 tasks for duplicate UUIDs:
No duplicates found
Broken ref: Scanned 848 tasks for broken references:
No broken references found
```

If there is a way to get a more verbose output, please let me know so I can run it. I couldn't find any reference in the documentation for this.

**Comment by djmitche** [comment]
34304 corresponds to an exit status of 134, suggesting the child process (the editor) was killed by SIGABRT. Although I'm not 100% sure there -- `WIFEXITED(34304)` is true, but `WIFSIGNALED(34304)` is false.

Anwway, it suggests there's something funky with how your $EDITOR is configured. What happens if you run

```
echo $EDITOR
$EDITOR tempfile; echo $?
```

**Comment by manoelpqueiroz** [comment]
Hi @djmitche, `echo $EDITOR` outputs to `/usr/bin/nvim` (Neovim as intended)

The second command does output 134 when exiting Neovim. I have removed `init.vim` and `.vimrc` configuration files and when dealing with Neovim "barebones", the command outputs 0. So in the end it's something in my configuration file that is giving it trouble.

Thanks for the help and I apologise for the inconveniece.
