### ISSUE TITLE
Email to "support@gothenburgbitfactory.org" is bouncing

### ISSUE THREAD

**Issue by rjray** [GothenburgBitFactory/taskwarrior#3153]
(Unable to send email, I couldn't find any other way to report this.)

My attempts to send email to the support address have bounced due to "550 authentication required". I have tried this from two different email addresses, one of which was a Gmail address.

**Comment by djmitche** [comment]
Hm, I have no idea who runs that, if anyone -- @lauft do you know?

@rjray at any rate, I think the current best support option is issues and discussions here on GitHub.

**Comment by lauft** [comment]
@djmitche I will try to investigate... 🤔

**Comment by lauft** [comment]
Late update, but the email to support@gothenburgbitfactory.org should be running again.

Currently (2024-11-23) it will forward to gothenburgbitfactory@gmail.com, which will reply with an automatic message that this account is only read occasionally and recommend GitHub discussions and the Discord server.
