### ISSUE TITLE
Unable to Sync with Server - "Neither sync.server nor sync.local are configured"

### ISSUE THREAD

**Issue by cgumb** [GothenburgBitFactory/taskwarrior#3154]
### Description:

I've been trying to set up synchronization between Taskwarrior and inthe.am, but despite correct configurations, I consistently encounter the error message: "Neither sync.server nor sync.local are configured".

### Environment:

> Taskwarrior version: 2.6.2
> OS: Arch Linux (BTW)

Steps to Reproduce:

> Configured `~/.config/task/taskrc` with the appropriate taskd [settings for inthe.am](https://inthe.am/getting-started) .
> Ran `task sync init`.

### Expected Behavior:
Taskwarrior should recognize the server settings and initialize synchronization.

### Actual Behavior:
Received the error: "Neither sync.server nor sync.local are configured".

### Diagnostic Steps Taken:

- Checked the diagnostics using `task diagnostics` which confirmed the configuration file is found.
- Explicitly referenced the configuration file during sync initialization.
- Created a minimal configuration file as an alternative.
- Increased Taskwarrior's log level to rc.debug=2, but no additional useful information was provided (not sure this is a legit thing).
- Also tried overriding configuration on the command line, including the two variables mentioned in the error.

### Configuration Snippet:

```
data.location=$XDG_DATA_HOME/task
taskd.certificate=$XDG_DATA_HOME/task/private.certificate.pem
taskd.key=$XDG_DATA_HOME/task/private.key.pem
taskd.ca=$XDG_DATA_HOME/task/ca.cert.pem
taskd.server=https://inthe.am:53589
taskd.credentials=inthe_am/[username]/[uuid]
taskd.trust=strict
```

Any help would be greatly appreciated, as I am currently unable to use the sync functionality of Taskwarrior due to this issue. I'm most perplexed by the fact that config overrides in the cli command still result in reports that these variables are not configured

**Comment by djmitche** [comment]
It sounds like you're building directly from the `develop` branch, which has a completely replaced sync system that won't work with inthe.am.

Use the latest released version, and you should be OK.

**Comment by cgumb** [comment]
Ah, I used `pacman -S task-git` which appears to build from the `develop` branch.
Of course, if taskwarrior's sync system will soon not be compatible with inthe.am then perhaps I shouldn't invest any time in trying to configure and learn such a setup :smiling_face_with_tear: 

I'll have have to explore to see what sorts of alternatives people are working with these days.
Thanks!
