### ISSUE TITLE
[TW-277] Complex filters can skip infix term expansion

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#317]
_Paul Beckingham on 2013-11-02T16:42:38Z says:_ 

 The 'ready' report has this filter:

<pre>
status:pending limit:page -WAITING '(scheduled.none: or scheduled.before:now )'
</pre>

When a filter term such as a keyword search is added like this:

<pre>
$ task foo ready
</pre>

The filter expression is not fully expanded.  Here are examples using a simple filter, and a complex filter (attached).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-11-02T16:42:38Z
Modified: 2014-05-31T14:35:02Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-11-02T16:42:38Z says:_ 

 Attachment simple.png has been added with description: Simple filter

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-11-02T16:42:38Z says:_ 

 Attachment complex.png has been added with description: Complex filter

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-08T04:08:54Z says:_ 

 Needs 2.4.0 expression evaluation to be properly solved.

**Comment by pbeckingham** [comment]
<img width="946" alt="tw-277_complex" src="https://user-images.githubusercontent.com/7963/36637202-d6312396-19a4-11e8-950d-fa7230fce9cb.png">
<img width="426" alt="tw-277_simple" src="https://user-images.githubusercontent.com/7963/36637203-d648a390-19a4-11e8-828d-5753dd48e605.png">
