### ISSUE TITLE
Cloud-Storage Backend

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3185]
Taskchampion supports pluggability for the server implementation, and currently has two:
 - Local (just sync to a file on disk)
 - Server (sync to `taskchampion-sync-server`)

Let's consider adding a third option: sync to a cloud-storage service like Amazon S3, Google Cloud Storage, or Azure Blob Store. If we could figure out how to implement this in each of the cloud-storage services, then casual users could simply configure their Taskwarrior's with some cloud credentials and an encryption key, and be on their way.

Some quick and probably incomplete thinking on the topic:

The server API is basically reading existing versions and  writing a versions, where each version is contrent-addressible: its "name" is based on its hash. Storage APIs support GET and PUT! The tricky bit is that there must be exactly one "latest" version, so the PUT operation must be a kind of compare-and-swap of the "latest version". 

Do any/all of the cloud storage providers have a mechanism to support this? Either directly in the storage service, or in another service on the same cloud provider?

**Comment by djmitche** [comment]
@ryneeverett ^^ I'd be curious for your thoughts here

**Comment by dathanb** [comment]
Which part would need to be compared-and-swapped? If each version is content-addressable, then collisions only happen if the two writes are actually the same, which is fine, right? So is there an index that points to all the latest versions that needs mutual exclusion during updates?

If that's the case, this should be doable on Amazon S3. All versions can be written without checks (based on the above reasoning about uniqueness), and the new index would be written by calling `CopyObject` on the old index and specifying the `x-amz-copy-source-if-match` predicate identifying the version of the index you intend to replace. There would just need to be a one-time bootstrapping operation where the initial index file is written using `PutObject`, which doesn't support any sort of checks or mutual exclusion.

**Comment by djmitche** [comment]
The part requiring CAS is setting the (single) latest version. We want to build a chain of versions, so the upload of a new version is fine and doesn't conflict, but that must only become the "latest" version if its parent version is the current "latest" version. Thus compare (latest == new version's parent) and swap (swap in new version). If that operation fails, then the client needs to "rebase" onto the new latest version and try again.

CopyObject's conditional functionality sounds useful! I guess that the add-new-version process would go like this:
* Get `latest`, with the content (a hash) going to LATEST, and the object's ETag going to LATEST_ETAG
* Create a new version with hash HASH and based on version LATEST
* Upload it as `versions/HASH`
* Create an object containing HASH at `hashes/HASH`
* CopyObject from `hashes/HASH` to `latest` with `x-amx-copy-source-if-match` set to LATEST_ETAG
* If the CopyObject operation fails with 412 PRECONDITION FAILED, delete `versions/HASH` and `hashes/HASH` and go back to the first step.

Does that match your understanding? Any interest in implementing this?

**Comment by dathanb** [comment]
That's more detail than I knew, but consistent with what I was thinking, yeah.

I'm pretty swamped right now and don't have the bandwidth to contribute, but would love to work on it if things clear up in ~1 month or so.

**Comment by ryneeverett** [comment]
> @ryneeverett ^^ I'd be curious for your thoughts here

I don't have much experience using cloud storage so I don't have much to say other than :+1: to more storage backend options.

**Comment by iwyatt** [comment]
This is a bit off topic to the main question, but I found [this article](https://bricolage.io/some-notes-on-local-first-development/) interesting wrt "local first" with implications on sync. It feels relevant to the conversation but I'm not quite 100% sure exactly which parts are most relevant. Thought it might be relevant for those of you more familiar with sync'ing tech. I'm unsure exactly how sync conflicts are handled in this style of development, though.

**Comment by djmitche** [comment]
Yeah, local-first is basically how the Taskwarrior sync model works (both the old and new models, in fact). It's also the idea behind Git, as compared to Subversion for example.And, you're right that conflict resolution is the tricky bit in most cases. Luckily the way Taskwarrior is used makes this easier than other situations -- tasks are mostly independent of one another, and there's typically only one person modifying tasks at a time.

**Comment by ryneeverett** [comment]
Thinking a bit more about this today, I think @djmitche and @dathanb have identified two requirements of a cloud provider for a "serverless" backend:

1. mutable state - pure content-addressed storage wont work without pointers
2. conditional updates - in order to avoid race conditions, we must be able to atomically ensure that the latest version is as expected before overwriting

Fortunately, (2) seems to be commonly implemented with etag matching by cloud providers:

- https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html
- https://azure.microsoft.com/en-us/blog/managing-concurrency-in-microsoft-azure-storage-2/
- https://cloud.google.com/storage/docs/request-preconditions

**Comment by djmitche** [comment]
Thinking a bit about how I'd like to implement this:
 - Support for each cloud backend should be controlled by a feature
 - Build shared code to manage the mapping from server protocol to objects, with a `CloudService` trait that can implement the object operations, including a compare-and-swap operation.

**Comment by djmitche** [comment]
Looking at AWS S3, `CopyObject`'s `x-amx-if-*` headers apply to the ETag of the _source_ of the copy, not the _destination_. It appears S3 has no support for any kind of read-modify-write. The docs support that, and a number of issues for other apps that interface with S3 confirm it.

Azure and GCP do appear to support read-modify-write, based on the docs linked above.

**Comment by djmitche** [comment]
(We might be able to support this with DynamoDB, though!)

**Comment by djmitche** [comment]
WIP at https://github.com/GothenburgBitFactory/taskwarrior/compare/develop...djmitche:issue3185

**Comment by djmitche** [comment]
TFW you spend a long time getting something written and getting it to compile (and, admittedly, writing unit tests). Then you run it and it works the first time.
```
⸩ task sync
TASKRC override: /home/dustin/p/taskwarrior/.taskrc
Syncing with GCP bucket djmitche-taskwarrior-devel
```
![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/28673/10b0edc0-0f00-4194-a02a-5945624f69e3)
