### ISSUE TITLE
Support for escape characters in task files

### ISSUE THREAD

**Issue by vanya-robertson** [GothenburgBitFactory/taskwarrior#3190]
Hello, there.

I have escape characters in my annotations as I put terminal commands there that I run periodically for updates:
```
  Annotation:        2023-09-27 11:26:27 -- pip3 list -o | cut -f1 -d' ' | tr " " "\n" | awk '{if(NR>=3)print}' | cut -d' ' -f1 | xargs -n1 pip3 install -U
```
In new instances of a repeating task, this inserts the newline character:
```
  Annotation:        2023-09-27 11:26:27 -- pip3 list -o | cut -f1 -d' ' | tr " " "
" | awk '{if(NR>=3)print}' | cut -d' ' -f1 | xargs -n1 pip3 install -U
```

Would it be possible to fix this behaviour?

Thank you very much,
Vanya

**Comment by djmitche** [comment]
I think this is due to an asymmetric escaping/un-escaping when storing the tasks in the task files, as your issue title suggests.

This appears to be fixed with the switch to Taskchampion, in my testing. So, the 3.0 release should fix this!
