### ISSUE TITLE
Refer to the relative current date of a task

### ISSUE THREAD

**Issue by aisneto** [GothenburgBitFactory/taskwarrior#3203]
Hello! I need some help regarding the due dates for a task. Recently, I found out that I can specify the due hour to be at the end of the day with the "]" modifier. As that is my preferred method of dealing with my tasks, I would like to set this modifier for all active tasks (that is, make them due at the end of their currently specified day). Intuitively, this could be done with "task mod due:due]," however, the mod command does not recognize "due" as a relative date referring to the current set day for that task. How could I achieve what I'm looking for?

**Comment by felixschurk** [comment]
It sounds like you are searching for https://github.com/tbabej/task.default-date-time.

This hook allows to set the default due time to any time you would like it so in your case:
```py
DEFAULT_TIME = time(23,59,59)  # Your wanted default time
```

**Comment by aisneto** [comment]
That seems exactly what I was looking for, thanks!

Do you have any idea how to update all my tasks after installing this hook? Like applying a modifier that would make them the same, but would trigger the on-modify hook.

**Comment by felixschurk** [comment]
I do think what you want is easier to achieve with a "normal" modification of the current due time using a filter before. 

How many tasks do you want to modify? If there might only be a few, I would do it manually. 

For updating all the due dates, you might want to use something as described here, https://taskwarrior.org/docs/using_dates/. 

So first getting a list of all pending tasks, which have a due date over
```sh
task due.any: +PENDING ids
```
And then you can update the due time according to the current due time and the amount of time you would like to add, see also https://taskwarrior.org/docs/durations/, eg.
```sh
task <ids-from-command-before> mod due:due+<time-to-add>
```

**Comment by felixschurk** [comment]
@aisneto When the above resolved your problem, I guess this issue can be closed.
