### ISSUE TITLE
data.location can not contain whitespaces

### ISSUE THREAD

**Issue by Andersounds** [GothenburgBitFactory/taskwarrior#3212]
A correctly specified data.location row may look like this:
`data.location=/home/fredrik/work/taskwarrior`
but by wrapping it in quotes like below, it is not intepreted correctly and e.g. `task list` command only yield the response `No matches.`
`data.location="/home/fredrik/work/taskwarrior"`

The reason for highlighting this is that it may be necessary to specify a path that contains whitespaces.
None of the below rows can be interpreted correctly
`data.location=/home/fredrik/work/te\ st/taskwarrior`
`data.location="/home/fredrik/work/te st/taskwarrior"`

Is this known? Is there another way to specify a path containing whitespaces?

**Comment by djmitche** [comment]
Does
```
 data.location=/home/fredrik/work/te st/taskwarrior
```
not work? Other configuration arguments include spaces without any quotes or escaping.

**Comment by Andersounds** [comment]
Im unsure how I managed to not verify this before opening the issue. Yes it works. Many thanks!
Also, thanks for a great piece of software!
