### ISSUE TITLE
Linking issues, cannot change compiler

### ISSUE THREAD

**Issue by aktaboot** [GothenburgBitFactory/taskwarrior#3236]
#### To report a bug...

* What command(s) did you run?
Followed the documented build instructions in `doc/devel/contrid/development.md`
* What did you expect to happen?
* What actually happened?
Taskwarrior did not successfully build

Encountered a lot of undefined references to std functions

More info:
- OS: Debian 12
- GCC version 12.2
- Clang version 14.0.6

Tried compiling with  g++ instead of clang, but clang kept getting called

Setting CXX or CMAKE_CXX_COMPILER has no effect

[output.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/13805032/out.txt)

**Comment by djmitche** [comment]
I don't know enough about CMake to help much with this, but I suspect that it would be useful to start with a clean checkout and show the commands you invoked to get there?

**Comment by aktaboot** [comment]
No problem, I have a problem understanding CMake aswell

It seems exporting CXX or CMAKE_CXX_COMPILER does not affect the build but passing `-DCMAKE_CXX_COMPILER=/usr/bin/g++` to the cmake command did the trick.

For some reason the linker was not happy with clang

**Comment by felixschurk** [comment]
Hei, 
I tried it out by myself locally.
I am having `cmake v. 3.27.7`, `clang v. 17.0.6` available.

I did not adhere directly to the [documentation from taskwarrior](https://github.com/GothenburgBitFactory/taskwarrior/blob/34c0e67469365eec4168b62035c657097a6e370c/doc/devel/contrib/development.md), however when running according to newer cmake documentation it does work for myself to compile and link with clang.

# Steps to reproduce/build
```sh
cmake -S . -B build-clang\
 -DCMAKE_BUILD_TYPE=RelWithDebInfo\
 -DCMAKE_C_COMPILER=clang\
 -DCMAKE_CXX_COMPILER=clang++
 
cmake --build build-clang -j 4
```
Maybe short break down:
`-S .` specifies that the source is in the current folder
`-B build-clang` specified to build in the folder `build-clang` having an out of source build
The last two flags then specify the corresponding compiler one wants, if none is provided (at least on Fedora) it defaults to gcc.

The second command then does invoke the corresponding build tool, for my case `GNU Make`.

@djmitche @aktaboot 
If you could verify that it is working, I would open a PR update the build instructions accordingly.

**Comment by djmitche** [comment]
Yes, those steps work for me.  Please open a PR?

**Comment by aktaboot** [comment]
Can also attest these work for me aswell, thanks :)
