### ISSUE TITLE
Update docs to explain difference from todo.sh?

### ISSUE THREAD

**Issue by githorse** [GothenburgBitFactory/taskwarrior#3237]
I've used [todotxt](http://todotxt.org/) in the past and thought it was pretty good. This project appears to be a competitor, but they look similar -- I wondered if maybe TaskWarrior was built on top of the `todotxt` format, but it doesn't look like it (though it appears it can [import from it](https://github.com/GothenburgBitFactory/taskwarrior/issues/628)).

Could you add some documentation about why they can't share a format and why I should choose TaskWarrior over TodoTxt?

**Comment by djmitche** [comment]
In my experience, OSS projects comparing themselves to one another can generate controversy, especially when done without familiarity with both tools. For example, if I described some TW feature that I didn't see in todotxt, maybe that feature actually does exist in todotxt and I've unintentionally undermined that project. Or maybe a later release adds that feature but TW's comparison isn't updated to match.

It's also not especially feasible to compare N-to-N projects -- there are lots of todo-list apps out there!

If you're familiar with both, then this might make a good reddit post, blog post, mastodon toot, etc. -- but I don't think it's a good thing to include in TW docs.
