### ISSUE TITLE
Segfault when importing data containing spurious newlines

### ISSUE THREAD

**Issue by OptimisticLock** [GothenburgBitFactory/taskwarrior#3240]
#### To report a bug...

* What command(s) did you run?
```
$ cat > import.json << 'EOF'
[{"description":"AAA","project":"Self","tags":[],"annotations":[],"id":24,"entry":"20240113T062723Z","modified":"20240113T173234Z","reviewed":"20240113T173234Z","status":"pending","uuid":"e5139954-71ee-417a-ac17-de801
f2d2454","urgency":0}]
EOF

$ task import < import.json
Importing 'STDIN'
Segmentation fault
```
Interestingly, this works:

```
task import <<< '[{"description":"AAA","project":"Self","tags":[],"annotations":[],"id":24,"entry":"20240113T062723Z","modified":"20240113T173234Z","r
eviewed":"20240113T173234Z","status":"pending","uuid":"e5139954-71ee-417a-ac17-de801
```

* Paste the output of the ```task diag``` command.
```
Unrecognized Taskwarrior file format or blank line in data. in /home/ira/.task/pending.data at line 70
```

Lines 69 and 70 from pending.data:
```
[description:"AAA" entry:"1705127243" modified:"1705204925" project:"Self" r
eviewed:"20240113T173234Z" status:"pending" uuid:"e5139954-71ee-417a-ac17-de801\nf2d2454"]
```
So, there is a stray  `\n` at line 69:  `r\neviewed`.

This happens on win10 wsl, on both 2.5.1 and 2.6.2

**Comment by djmitche** [comment]
It looks like both of the inputs you're trying to import have newlines in unexpected places? Still, that should not crash, and should give a helpful error message instead.

**Comment by OptimisticLock** [comment]
Oh, I see! LOL. 

It should give a helpful error message and it shouldn't write `\n` to `pending.data`, unless it can subsequently read it. Which it can't. Now I need to edit the file.

**Comment by djmitche** [comment]
I suspect the second issue won't be a problem anymore, as we don't store data in `.data` files anymore. But yes to the first part!

**Comment by OptimisticLock** [comment]
BTW, now it's giving me a meaningful error message. Not sure what changed. 
```
$ /usr/bin/task
[/usr/bin/task next]
Unrecognized Taskwarrior file format or blank line in data. in /home/ira/.task/pending.data at line 70
```

**Comment by OptimisticLock** [comment]
When did that happen? I see task 2.6.2 still uses it?

**Comment by djmitche** [comment]
That's better, but really it should have caught that at `task import`

The new data storage format is as-yet unreleased.

**Comment by OptimisticLock** [comment]
Good thing I coded to spec then, lol! Curious to know more.

**Comment by djmitche** [comment]
At a guess, the import in the first code sample failed because the `uuid` field was not a valid uuid. That should be pretty easy to check for.
