### ISSUE TITLE
taskchampion: get_tags() not fetching user tags

### ISSUE THREAD

**Issue by aktaboot** [GothenburgBitFactory/taskwarrior#3254]
#### To report a bug...

get_tags() seems to not fetch user tags

After creating a task with a tag, I fetch all the tags using the Rust API
Sample code:
```
fn main() -> Result<(), taskchampion::Error> {
    let storage = Box::new(SqliteStorage::new(SQLITE_DB, false)?);
    let mut replica = Replica::new(storage);

    let tasks = replica.all_tasks()?;
    for (u, t) in tasks.clone() {
            for tag in t.get_tags(){
                println!("tag:{}", tag);
            }
        dbg!(t);
    }

    Ok(())
}
```
Result:
```
tag:PENDING
tag:UNBLOCKED
[src/main.rs:14:9] t = Task {
    uuid: 16d379dc-ae97-4e53-8b0e-5637c49a59ed,
    taskmap: {
        "description": "task with a tag",
        "tags": "test",
        "status": "pending",
        "entry": "1705876311",
        "tags_test": "x",
        "modified": "1705876311",
    },
    depmap: DependencyMap {
        edges: [],
    },
}
```

- Built and tested on  develop branch rev 6f1c16fecda2c47683b5a07dca4975e1bd40742d

**Comment by djmitche** [comment]
I think you want `tag_test` instead of `tags_test`.

**Comment by aktaboot** [comment]
I am not sure I understand very well, for clarification I created this task with the task cli command: `task add +test task with a tag`  before trying to fetch it from the DB

**Comment by djmitche** [comment]
Ah, that's a bug! I see `src/Tasks.cpp` uses `tags_` and not `tag_` :(

**Comment by djmitche** [comment]
I was about to fix this by changing `Task.cpp` to use `tags_` but that's in a released version of Taskwarrior so would be a breaking change. I think Taskchampion needs to change (including its docs).

@aktaboot I'm out of time for the moment. Do you want to make a PR to make Taskchampion use `tags_..`?

**Comment by ryneeverett** [comment]
> I was about to fix this by changing Task.cpp to use tags_ but that's in a released version of Taskwarrior so would be a breaking change.

Late to the party but seems like 3.0 would be a good time to fix confusingly named properties like this. And I'm not sure if it's really a breaking change since AFAIK it wouldn't break anything that isn't already going to be broken. Is `tags_` exposed in taskwarrior-2x in any way other than the json database?

**Comment by djmitche** [comment]
Good point -- `tags_` appears in the `pending.data` but not in the output of `task export`. And users will need to `task export` and `task import` to upgrade to 3.0!
