### ISSUE TITLE
[TW-290] task help [regex]

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#327]
_David Patrick on 2012-08-14T23:11:33Z says:_ 

 _NOTE: rethink as of comment # 7, feel free to jump over the rest_

The quality of taskwarriors help files is one of its claims to fame. Fredde and Paul have done a truly amazing job of man pages, tutorials, videos. There's still a lot to be documented, too, so if you feel like helping out the project and you are sort of familiar with documentation, take a look at http://taskwarrior.org/projects/taskwarrior/wiki/Features#Not-Yet-Documented, and dig in!

and on to the feature request!

right now *task help* gives an excellent reference, with the essential commands and pointers to the complete set of man pages. It's great, and I think it could be enhanced. If the headers of each paragraph in all 5(?) man pages was indexed for keywords, and the help command was extended with *help [keyword]*, and the output was an aggregate of all paragraphs with matching keywords from all man pages including the help page, then THAT would be.. helpful.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-08-14T23:11:33Z
Modified: 2015-03-14T17:09:00Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2012-08-14T23:49:33Z says:_ 

 I tried an imaginary run of this command by thinking "task help tag" and then opening each man page, one after another, and searching for /tag. Wow! If you took every paragraph that had the word "tag" in it's header, from all manpages, in one place.. very simply, you'd have everything you'd ever need to know about tags.

**Comment by taskwarrior** [comment]
_David Patrick on 2012-08-15T01:34:16Z says:_ 

 no, seriously, check it out

 % tw help tag   (not real command)

<pre>
task help tag

       task <filter> tags                 Shows a list of all tags used
       task <filter> _tags                Shows only a list of all tags used,
 +tag       The + means add the tag
* tag       The - means remove the tag

man task
 task <filter> tags
              Show a list of all tags used.  Any special tags used are highlighted.
 task <filter> _tags
              Shows only a list of all tags used, for autocompletion purposes.
  ATTRIBUTES AND METADATA
 +tag|-tag
              Tags are arbitrary words associated with a task. Use + to add a tag and - to remove a tag
              from a task. A task can have any quantity of tags.

              Certain tags (called 'special tags'), can be used to affect the way tasks are treated.  
              For example, if a task has  the  special tag 'nocolor', then it is exempt from all color
              rules.  The supported special tags are:

                  +nocolor     Disable color rules processing for this task
                  +nonag       Completion of this task suppresses all nag messages
                  +nocal       This task will not appear on the calendar
                  +next        Elevates task so it appears on 'next' report

man raskrc
 complete.all.tags=yes
              May be yes or no, and determines whether the tab completion scripts consider all the tag 
              names you have used, or just  the  ones used in active tasks.  The default value is "no".
 list.all.tags=yes
              May  be  yes  or  no,  and determines whether the 'tags' command lists all the tag names 
              you have used, or just the ones used in active tasks.  The default value is "no".
 tag.indicator=+
              The character or string to show in the tag.indicator column.  Defaults to +.
  COLOR CONTROLS
              color.tag.none Task has no tags.
              color.tagged Task has at least one tag.
              color.tag.X=yellow Colors any task that has the tag X.
 rule.precedence.color=due.today,active,blocking,blocked,overdue,due,scheduled,keyword.,project.,tag.
              ,recurring,pri,tagged,com‐leted,deleted. This setting specifies the precedence of the color 
              rules, from highest to lowest.  Note that the prefix 'color.' is omitted (for brevity), 
              and that any wildcard value (color.tag.XXX) is shortened to 'tag.', which places all 
              specific tag rules  at  the  same precedence, again for brevity.
 urgency.tags.coefficient=1.0
              Urgency coefficient for tags
 urgency.user.tag.<tag>.coefficient=...
              Specific tag coefficient.

man task-tutorial
TAGS
       A task may only have one project, but it may have any number of tags, which are just single words 
       associated with the task.  I  can  go to the print shop at the mall, and do all the invitation 
       tasks, so let's tag them all.

              $ task 3,5,6 modify +mall

              Task 3 modify "Mail invitations"
*  tags will be set to 'mall'.
              Proceed with change? (Yes/no/All/quit) A

              Modified 3 tasks.

       The long report shows tags, too,

              $ task long

              ID Project Pri Added      Started Due Recur Countdown Age     Deps Tags Description
* - ------- --- ---------- ------- --- ----- --------- ------- ---- ---- ---------------------------------
               1 party   H   10/16/2010                             27 mins           Select a free weekend in November
               2 party   H   10/16/2010                             26 mins           Select and book a venue
               5 party   H   10/16/2010                             23 mins      mall Design invitations
               7 home        10/16/2010                             14 mins           Pay the rent on the 31st
               3 party       10/16/2010                             25 mins      mall Mail invitations
               4 party       10/16/2010                             25 mins           Select a caterer
               6 party       10/16/2010                             23 mins      mall Print invitations

              7 tasks

       and I can use tags as a filter to any report too.

              $ task +mall list

              ID Project Pri Due Active Age     Description
* - ------- --- --- ------ ------- ------------------
               5 party   H              24 mins Design invitations
               3 party                  26 mins Mail invitations
               6 party                  24 mins Print invitations

              3 tasks

       I made a mistake - I can't mail out the invitations at the mall, so let's remove that tag.

              $ task 3 modify -mall
              Modified 1 task.

SPECIAL TAGS
       You've seen tags, but there are also 'special tags' that have effects on individual tasks.  
       The 'nocolor' special tag causes the  color rules to be bypassed.

              $ task 6 modify +nocolor
              Modified 1 task.

       Special tags are highlighted by the 'tags' command.

              $ task tags

              Tag     Count
* ------ -----
              mall        2
              nocolor     1

              2 tags (9 tasks)

       There  are  others - the 'nonag' special tag prevents the generation of nag messages when you work 
       on low priority tasks when there are more important ones.

              $ task 6 modify -nocolor
              Modified 1 task.

       The 'nocal' special tag will prevent a task from appearing on the calendar.

**Comment by taskwarrior** [comment]
_David Patrick on 2012-08-15T03:44:38Z says:_ 

 and somehow *task show* output should be part of it

<pre>
djp(at)lemur ~ $ task show tag


Config Variable          Value   
color.tag.none
color.tagged             color246
complete.all.tags        no
list.all.tags            no
tag.indicator            +
urgency.tags.coefficient 1.0
</pre>

**Comment by taskwarrior** [comment]
_Penelope Fudd on 2012-08-15T21:25:09Z says:_ 

 I've been independently thinking about 'task help' as well, and as a brand new user, I have to say that 'task help' is not as helpful as its name would suggest.

Here is a patch that changes 'task help' to take an optional parameter: 'task help all'.  Without the 'all', it prints only the most common commands; with the 'all', it prints what it printed before.  I'd like to see something like what's described above, but as a new user, I just had to get help on the simple stuff or else I'd have stopped using taskwarrior.

See attached patch (git diff against task 2.1.1 from git) for changes.  It should probably be rewritten, as I'm not a C++ programmer.

Thanks!

**Comment by taskwarrior** [comment]
_Penelope Fudd on 2012-08-15T21:25:09Z says:_ 

 Attachment a has been added with description: git diff of CmdHelp.cpp changes

**Comment by taskwarrior** [comment]
_Penelope Fudd on 2012-08-15T21:26:32Z says:_ 

 Here's the output of 'task help' with the patch:

<pre>
Usage: task                               Runs rc.default.command, if specified.

       Common tasks:
       task add < mods >                      Adds a new task
       task < filter > annotate < mods >      Adds an annotation to an existing task
       task < filter > list                   Lists all pending tasks
       task < filter > next                   Lists the most urgent tasks
       task < filter > start < mods >         Marks specified task as started
       task < filter > done < mods >          Marks the specified task as completed
       task < filter > modify due:< date >    Set the task due date
       task < filter > modify recur:< period >           Set the task recurrence
       task < filter > modify until:< date >  Set recurrence endpoint
       task < filter > modify depends:< id1,id2,... >    Set dependencies 
       
       task help [all]                    List [all] commands
</pre>

**Comment by taskwarrior** [comment]
_David Patrick on 2012-08-15T23:24:50Z says:_ 

 very cool Penelope! and a patch!

it's sort of the opposite outcome from the feature request above, but a really good idea. Hey, I have been musing on something similar, a new help command *task reference*, that would put up some very minimal help cues, almost like the related parts of the .pdf refcard. I realized that even boiled down to a single line of text might be helpful, for example

<pre>
% task ref write-commands

add,annotate,append,delete,done,denotate,duplicate,edit,log,modify,prepend,start,stop,undo
</pre> 

taking up as little screen realestate as possible, just enough to remind you of the options you have to deal with tasks. similar reference for

 % task ref attributes
% task ref file-operations
% task ref reports
% task ref modifiers

etc.
a mini help system that could even be configured to appear regularly, in context.

quite the opposite of *task help [index]* though ;-)

ps, I took the liberty of adding erroneous spaces to your previous post, so our wiki could parse it.

**Comment by taskwarrior** [comment]
_David Patrick on 2013-08-19T16:56:39Z says:_ 

 Extended help is a good idea, task comes with a stack of manpages, and it's not always obvious which manpage might have what you are looking for, 
SO, here's another spin on this feature request; Use grep!

   $ task help |grep tag

or

   $ man task |grep tag

does a fine job of pulling out any matching lines. What if there were some way where 

   $ task help tag (really, task help regex) 

performed the man-grepping above, and iterated through the existing help-text and each tw-related manpage to do it?

   $ task help < term > 

could trigger an external script (twhelp.sh) provide every bit of help available on <term>.
 ..and the help-files don't need "indexing" to do it!

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-03-14T17:09:00Z says:_ 

 There are fewer manpages now, somewhat better docs online.  I'm reluctant to build in a maintenance burden.

**Comment by pbeckingham** [comment]
[TW-290_a.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755571/TW-290_a.txt)
