### ISSUE TITLE
Should `m` be interpreted as "month" in UDA duration?

### ISSUE THREAD

**Issue by allgreed** [GothenburgBitFactory/taskwarrior#3284]
```
task add tost estimate:15m
```

I've expected the estimate to be 15 minutes, it was 15 **months** (450 = 15 * 30 days to be precise).

I'm aware that the docs state that this is the case.

I can make an argument for why UDA duration is different than wait / schedule date offset and that `m` would make more sense to mean "minute" here. I can see someone making an argument to the contrary as well. Maybe it'd make sense for this to be more configurable?

Also: I couldn't quite find the place in code where it's being handled.

**Comment by djmitche** [comment]
I agree that `m` is ambiguous and I've gotten caught thinking it was minutes many times with `wait`. However, if it meant minute then likely a different group of people would be confused. And moreso if we _change_ the meaning. I also think it'd be super-confusing if it meant month in some contexts and minutes in other contexts!

So, I think "m is months" is a design choice we're pretty much stuck with.

**Comment by allgreed** [comment]
@djmitche yeah, 100% agree - with `wait` I actually prefer `m` to mean months, as I'd rather wait things for month than minutes.

What are your thoughts on the "configurable" part?
Also: I'm still having trouble finding the place where parsing aka `5m` becomes a structure corresponding to `5 months`. If you have a few spare cycles I'd greatly appreciate a little pointer as to which file should I look at ;) Nix makes it quite pleasant to use patched software, so maybe I'd just have a try hard-coding it to be the other way around and see if I even like it

**Comment by djmitche** [comment]
I'm not sure I'm qualified to have an opinion on the configuration question -- I think Taskwarrior is "opinionated" which means it tries to not have all sorts of configuration knobs to change its behavior. But, it has a _lot_ of configuration knobs!

I think the parsing is in [`libshared`](https://github.com/GothenburgBitFactory/libshared/blob/35e6ec09595c80bc744a27eda50e4dd34d6c7303/src/Duration.h#L60), which is brought in as a submodule.

**Comment by allgreed** [comment]
Thanks!
Oof, TIL: `wait:2m` doesn't wait for 2 months, it waits for 2 * 30 days.
edit: which is good enough approximation, leaving for posterity

**Comment by smemsh** [comment]
see also #2898
