### ISSUE TITLE
Deprecate taskd/taskserver

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3293]
Let's keep it around, in case people are still using it, but be clear that it's not going to see further development.

* On tw.org
  * Releases & projects
  * Docs
* [Repo](https://github.com/gothenburgBitFactory/taskserver)
  * Put up an announcement
  * Archive

**Comment by vwheezy** [comment]
Any reason for this besides lack of development? I use it pretty frequently, the only issue was finding a good client on iOS but other than that it keeps my tasks synced very well!

**Comment by vwheezy** [comment]
Found https://github.com/GothenburgBitFactory/taskserver/issues/196 for anyone else digging. Are there any plans for another sync server? 

@djmitche Do you use a sync server and if so what?

EDIT:
Sorry, I really need to read. Just saw the new release!

**Comment by djmitche** [comment]
Yeah, that is one of many reasons. In fact, a new sync system is the main change in Taskwarrior 3.0.

There is a sync server (`taskchampion-sync-server`) although it is not a whole lot easier to set up than `taskserver` was. You can find some other folks setting it up in https://github.com/GothenburgBitFactory/taskchampion-sync-server/issues/2.

**Comment by djmitche** [comment]
I opened PRs in tw.org and taskserver. I don't have write permissions to the latter, though, so I can't flag anyone for review, nor archive the repo.

**Comment by djmitche** [comment]
OK, _now_ this is completed :)
