### ISSUE TITLE
Codespell report for "Taskwarrior" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [GothenburgBitFactory/taskwarrior#3295]
The FOSS server [fossies.org](https://fossies.org) - supporting also the [Taskwarrior](https://fossies.org/linux/task) project - offers among others a feature named "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have just created such a [codespell](https://github.com/codespell-project/codespell) based analysis for the "Taskwarrior" GitHub development version:

&nbsp;https://fossies.org/linux/test/taskwarrior-develop.tar.gz/codespell.html

That URL should redirect always to the report for the latest version identified by the short GitHub commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The data are residing within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines. The report should be available at least for some weeks and is continuously updated (currently with a half-hourly refresh rate).

By the way, the context type of the spelling errors and typos are marked by a single character (within the sortable column "T"): The less interesting, probably not user visible ones (in "comments") are greyed, while the probably more interesting ones are black-colored. Especially interesting may be unassigned errors marked by a "?" since they may be contained in the source code itself. Some more according information is offered by a tooltip if the mouse is over the string "error context type character" above the table, over the "T" in the table header or over such a context character itself within the table. If JavaScript is enabled all table columns are sortable.

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can exclude them if applicable. So for example, the spelling errors found in the ChangeLog file - if they cannot be corrected - could be excluded.

Just for information there are also three supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/test/taskwarrior-develop.tar.gz/codespell_conf.html), all obvious [false positives](https://fossies.org/linux/test/taskwarrior-develop.tar.gz/codespell_fps.html) and a [misspelling history](https://fossies.org/linux/test/taskwarrior-develop.tar.gz/codespell_hist.html) (log).

Ok, no severe errors in the code itself were found and some of the misspellings are only in comments or test directories. But although spelling corrections have certainly a low priority, they can still contribute to the overall quality of a software project. So I hope that the report can nevertheless be a little bit useful.

Off topic P.S.: While building taskwarrior 3.0.0 I found also the error #3294. As a workaround  I (as a layman) simply removed the  according line 7 of the file `Cargo.toml`. Additionally I found  that some roughly ten years old and forgotten `tasks` entries are now no longer working with the new compiled `task` binary. Ok, after founding https://taskwarrior.org/docs/upgrade-3/ I was able to restore the old `task` binary and could export and re-import that old test tasks. Maybe it would be a good idea to output some according information within the build process if old tasks are found locally. Additionally the cmake option `-DENABLE_SYNC=OFF` is no longer supported and the new `task` command outputs always `"There are XX local changes.  Sync required."`. Probably I had to read more documentation how to use `task` only locally ;-) And last but not least: At the bottom of the page https://taskwarrior.org/download/ under `Disclaimer:` is still the `master` branch (instead of the `develop` branch?) mentioned as representing the latest stable release.

**Comment by djmitche** [comment]
Thanks for the codespell! Is there a way to plug that into GitHub workflows so we could get alerts for PRs adding new spelling errors? And, would you like to put together a PR that fixes some or all of those?

Thanks for the note on #3294.

I'm not sure what you mean by "not working with the new compiled task binary" - if you had not done the export/import, then surely _none_ of those tasks were visible in the new task binary.

I've added #3296 for the issue with `-DENABLE_SYNC=OFF` and #3297 for the "sync required".

As for the branches: I'm unclear why we have a stable branch and a develop branch, but you're right that there's no master branch. https://github.com/GothenburgBitFactory/tw.org/issues/788

**Comment by jschleus** [comment]
@djmitche Thanks for your fast response.
> Thanks for the codespell! Is there a way to plug that into GitHub workflows so we could get alerts for PRs adding new spelling errors?

I'm not an expert on this topic but some solutionss may be found in the short Fossies codespell usage hints (mentioned below).

Just to mention the possibility: If the Fossies codespell report described above continues to run, you can in principle also be notified of new spelling errors if you specify one or more e-mail addresses.

> And, would you like to put together a PR that fixes some or all of those?

This is an understandable but unfortunately not realizable suggestion, for the main reason I quote the following excerpt from the above mentioned short documentation:

>>   A note: Fossies provides as an information only the source code spelling check reports with the special option to inspect the context of the probably misspelled words in a fast and comfortable way. However Fossies doesn't create for e.g. "diff"-like files usable by the "patch" command or even GitHub pull requests (PRs) since the risk is too high that something would be wrongly corrected (but here you may find some small [codespell usage hints](https://fossies.org/codespell_usage_hints.html)).

In some cases also the in the misspelling report mentioned  list of the found errors given in the original text format (linked via the word "list" above the full spelling errors table) can be helpful if using some scripting.

> I'm not sure what you mean by "not working with the new compiled task binary" - if you had not done the export/import, then surely none of those tasks were visible in the new task binary.

Exactly. I found - surprisingly for me - a `task` binary that I had compiled some time ago, opened it out of curiosity and actually got to see some nicely formatted old events set up for test purposes. Since the `task` functionality far exceeds that of my own little appointment script, as a stupid user I simply tried to compile and install the current release (3.0.0), whereby the old version - that had not been directly saved before - was overwritten. Unfortunately, the new binary no longer displayed any dates. After subsequently reading some of the relevant documentation, it was of course too late for the export/import. Ok, it's my own fault (but fortunately I found an old backup of the previous `task` binary).

So I just wanted to point out with my comment that some real users might have a similar problem if they don't do the export or save the old binary beforehand.

**Comment by djmitche** [comment]
> This is an understandable but unfortunately not realizable suggestion, for the main reason I quote the following excerpt from the above mentioned short documentation:

Got it, thanks -- I'm pretty busy working on fixes for the 3.0 release, and spelling errors are pretty low priority, so absent any automation I think we'll just let these spelling errors continue to exist.

The suggestion to print a warning during build if existing task data is present is an interesting one, but I'm wary of it for a few reasons:
 * I suspect the bulk of Taskwarrior users will install from a package, and not run the build process directly. The people who have used it in the last few weeks are, I think, the exception to this rule!
 * It's a little sketchy for a build process to go poking around in $HOME. Perhaps a little less weird for `make install`? Downloading and building source code is an exercise in trust that the developer, so even the appearance of impropriety is probably best avoided.
 * I don't know how to do that with CMake :)

However, it might make sense for `task` itself to indicate, on startup, that `.data` files still exist and suggest an export/import. Maybe that's too late to rescue the old version of `task`, but the same would be true if the warning was issued in `make install`.

**Comment by djmitche** [comment]
I think all of the issues raised here have been addressed (most by opening new issues).

**Comment by jschleus** [comment]
@djmitche 

> Got it, thanks -- I'm pretty busy working on fixes for the 3.0 release, and spelling errors are pretty low priority, so absent any automation I think we'll just let these spelling errors continue to exist.

Ok, I understand. Maybe sometime later. or not at all ...
