### ISSUE TITLE
3.x always warns that sync is required

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3297]
From @jschleus in #3295:
> the new task command outputs always "There are XX local changes.  Sync required.".

**Comment by djmitche** [comment]
I think the old version only did this when sync config options were set, but we now support local sync by default.

We could
 * Make this appear only on remote sync
 * Make this "nag" disabled by default, if it is indeed one of the "nag" options
 * Suggest setting up regular sync, even locally, in the upgrading guide

**Comment by ryneeverett** [comment]
I like the idea of eventually making this a default nag but I don't think the sync story is strong enough to justify it yet.

**Comment by djmitche** [comment]
I was thinking that "nags" were a general mechanism for the various reminders, but it turns out that it only refers to the "You have more urgent tasks" message. Rather, the `sync` verbose flag controls this output. So, let's set that to disabled by default.
