### ISSUE TITLE
[EX-37] productivity rewards

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#33]
_David Patrick on 2009-12-04T07:52:13Z says:_ 

 Task will already nag; "Is that all ya got ?" (or whatever you chooses to prod yourself with) but in the same spirit, task could be taught to let you give yourself rewards for certain arbitrary levels of productivity.

Let's say you decide that you want to complete at least ten tasks a day, and that at least four of those have to be High priority.

If you could define your goals in the .taskrc, something like

 .### daily productivity rewards
 reward.day.4=pri:h
 reward.day.6=pri.any:
 reward.day.message=Congratulations! You've reached todays productivity targets! Play 1/2 hour of video games guilt-free!
 reward.week.12=pri:h
 reward.week.20=pri.any:
 reward.week.6=proj:baz
 reward.week.message=You are a mighty Taskwarrior! Make reservations for 2 at Chez Louis!

you could goad yourself to greatness.

**Comment by taskwarrior** [comment]
_t charles yun on 2009-12-08T18:22:09Z says:_ 

 i want to chime in that this is a great idea; i like it; i want it.  my question is how milestones are visualized during a simple `task list` scenario.  

specifically, what happens when one has tasks with different: due dates, project names, etc.

it is too late in the evening for me to come up with decent examples, but I think that there are some details here worth hashing out.
*  tcy

**Comment by taskwarrior** [comment]
_David Patrick on 2009-12-09T08:58:20Z says:_ 

 tcharles yun wrote:
> i want to chime in that this is a great idea; i like it; i want it.
and eventually, you shall have it!

  my question is how milestones are visualized during a simple `task list` scenario.  

There are two distinct things hinted at; rewards and milestones.
Rewards are designed to encourage a _rate_ of task completion, and Milestones are to indicate an important step in a specific project. The suggested mechanisms for both are very similar, and _neither_ would appear in a typical listing, but instead, would pop-up a message when a pre-specified set of tasks, or number of tasks, has been completed.

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-05-30T22:50:58Z says:_ 

 not really ready for 2.0.0

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-17T02:37:23Z says:_ 

 When subtasks are implemented, the parent will be the milestone, and the subtasks, when all completed will be the "reward".

**Comment by pbeckingham** [comment]
No plans to implement.
