### ISSUE TITLE
Warn if `.data` files exist

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3303]
..it might make sense for `task` itself to indicate, on startup, that `.data` files still exist and suggest an export/import. Maybe that's too late to rescue the old version of `task`, but the same would be true if the warning was issued in `make install`.

_Originally posted by @djmitche in https://github.com/GothenburgBitFactory/taskwarrior/issues/3295#issuecomment-2024124391_

**Comment by felixschurk** [comment]
We could check by creation of the build files if there is a directly existing which has the task files (at least for the default location `~/.task` and in ~/.config/task).
I do not know if that is the proper location if one is following the XDG guides.

An output of CMake would then look like:
```sh
❯ cmake -S . -B build-test --fresh
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring C++17
-- System: Linux
-- Performing Test _HAS_CXX17
-- Performing Test _HAS_CXX17 - Success
CMake Warning at CMakeLists.txt:16 (message):
  -- Found existing taskwarrior data files in /home/felix/.task or
  /home/felix/.config/task.

    With this version of taskwarrior the storage backend has changed please see the release notes for details.
    https://github.com/GothenburgBitFactory/taskwarrior/releases

  

    Please also read the documentation for migrating from task 2.6 to task 3.0
    https://taskwarrior.org/docs/upgrade-3/


-- Looking for libshared
-- Found libshared
-- Looking for SHA1 references
-- Found SHA1 reference: 3e41fb604
-- Looking for timegm
-- Looking for timegm - found
-- Looking for get_current_dir_name
-- Looking for get_current_dir_name - found
-- Looking for wordexp
-- Looking for wordexp - found
-- Performing Test HAVE_TM_GMTOFF
-- Performing Test HAVE_TM_GMTOFF - Success
-- Performing Test HAVE_ST_BIRTHTIME
-- Performing Test HAVE_ST_BIRTHTIME - Failed
-- Looking for libuuid
-- Looking for uuid_unparse_lower
-- Looking for uuid_unparse_lower - found
-- Found libuuid
-- Configuring cmake.h
-- Rust Toolchain: stable-x86_64-unknown-linux-gnu
-- Rust Target: x86_64-unknown-linux-gnu
-- Determining required link libraries for target x86_64-unknown-linux-gnu
-- Required static libs for target x86_64-unknown-linux-gnu: gcc_s;util;rt;pthread;m;dl;c
-- Found Rust: /home/felix/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc (found version "1.77.0") 
-- Using Corrosion as a subdirectory
-- Configuring man pages
-- Configuring done (2.1s)
-- Generating done (0.1s)
-- Build files have been written to: /home/felix/data/taskwarrior/build-test
```

The message for sure can be changed etc.
This step is even before a user/developer would run the compilation of the files - so no harm yet done.

**Comment by djmitche** [comment]
From what we've seen over the last few days, I think most users of TW install from a package, so checking during build would not warn them. I mentioned in #3295 that doing unusual things like reading files in $HOME during the build process is probably going to alarm people -- the [xz vulnerability](https://blog.qualys.com/vulnerabilities-threat-research/2024/03/29/xz-utils-sshd-backdoor) just announced only reinforces that.

But, the same warning printed by `task` at startup would be great, and give users a chance to perform the upgrade.
