### ISSUE TITLE
[TW-294] Display UUID of task created by add

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#331]
_John West on 2013-11-16T13:44:32Z says:_ 

 I'd like to be able to get the UUID of the task I've just created with 'task add'.  I would use this primarily for scripting.  An untested example:

@
$ bash <<EOF
1.  Create a task and capture the UUID.
uuid=`task rc.verbose=new-uuid add proj:TwoStepProject Step one of project`
1.  The next task depends on the previous task.
task add proj:TwoStepProject dep:$uuid Step two of project

EOF
@

Forgive me any typos, but hopefully the above is reasonable.  The second line, adding the dependency by UUID works in 2.2.0, happily.

I have a handful of complex tasks that have multiple steps and are recurring, but are not necessarily on time-based triggers.  I've set up scripts to add the tasks for me when I need them added based on external triggers, but I haven't discovered a built-in mechanism for setting up the dependencies in a reliable way.

I could use rc.verbose=new-id to get the id as it was when I added the record, but this is subject to race conditions if more than one script executes simultaneously, or if I happen to manually be manipulating tasks at the same time.  I can work around this by using external lock files, but having direct access to the UUID of the newly created task would cut down on the number of moving parts and might be a boon for others, too.

Thank you!

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-11-16T13:44:32Z
Modified: 2014-07-04T13:21:38Z
```

**Comment by taskwarrior** [comment]
_John West on 2013-11-16T13:48:20Z says:_ 

 My apologies that the script example is wonky.  The inline code button didn't work the way I expected it to.

<pre>
$ bash <<EOF
1.  Create a task and capture the UUID.
uuid=`task rc.verbose=new-uuid add proj:TwoStepProject Step one of project`
1.  The next task depends on the previous task.
task add proj:TwoStepProject dep:$uuid Step two of project

EOF
</pre>

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-07-04T13:21:38Z says:_ 

 Added support for 'new-uuid' verbosity token, which works just like 'new-id'.

**Comment by sampablokuper** [comment]
Please can this issue be reopened?

As of 2.5.1 (I haven't checked other versions of TaskWarrior), the `new-uuid` verbosity setting does not seem to take effect unless the `new-id` verbosity setting is disabled. This is presumably a regression.

**With** `new-id` enabled:
```
$ task _get rc.verbose
blank,header,footnote,label,new-id,new-uuid,affected,edit,special,project,sync,unwait,recur
$ task add foo
Created task 106.
```
I would have expected the above to output *both* the ID and the UUID, since both are enabled. Something like: `Created task 106 (a3208e1b-b8cb-4370-b017-402a2224ca05).`

**Without** `new-id` enabled, `new-uuid` works as expected:
```
$ task _get rc.verbose
blank,header,footnote,label,new-uuid,affected,edit,special,project,sync,unwait,recur
$ task add foo
Created task a3208e1b-b8cb-4370-b017-402a2224ca05.
```

Version info:
```
$ task _get rc.verbose
task 2.5.1
   Platform: Linux

Compiler
    Version: 6.3.0 20170516
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Nov 28 2018 20:17:42
     Commit: 493bbadb1
      CMake: 3.7.2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: n/a
 Build type: 

Configuration
       File: /home/sampablokuper/.taskrc (found), 4511 bytes, mode 100644
       Data: /home/sampablokuper/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/sampablokuper/.task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (251x54)
       Dups: Scanned 1210 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 1210 tasks for broken references:
             No broken references found
```

**Comment by pbeckingham** [comment]
new-id and new-uuid should be unrelated, but only one will be in effect at a time.  Please create a new issue for this.

**Comment by sampablokuper** [comment]
@pbeckingham wrote:
> Please create a new issue for this.

Done: https://github.com/GothenburgBitFactory/taskwarrior/issues/2085

**Comment by corbolais** [comment]
Is there any documentation on `new-id` and `new-uuid` to be found?

What is the raitionale for being `new-id` and `new-uuid` being mutually exclusive?
