### ISSUE TITLE
Publish taskchampion docs

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3311]
### Discussed in https://github.com/GothenburgBitFactory/taskwarrior/discussions/3309

<div type='discussions-op-text'>

<sup>Originally posted by **RedEtherbloom** March 28, 2024</sup>
Is there currently a way to access the taskchampion documentation online?

The [link](https://gothenburgbitfactory.github.io/taskwarrior/taskchampion/) in the README.md atm 404s.
Is it being served under some different path?

I'll open it up locally otherwise.</div>

**Comment by ryneeverett** [comment]
Any update on this?

**Comment by djmitche** [comment]
I think this will be part of #3209.

**Comment by djmitche** [comment]
TC docs are now at https://gothenburgbitfactory.org/taskchampion/ (neat!!)
