### ISSUE TITLE
version 3.0.0 : "Clear working set query" and slow queries

### ISSUE THREAD

**Issue by pglaser-engineer** [GothenburgBitFactory/taskwarrior#3323]
Greetings,

I upgraded to version 3.0.0 following the required procedure (exported from the previous version and imported into the new). Generally things work like they did before, and I am grateful to you all for creating, maintaining, and improving a tool that has become an essential part of my daily workflow.

That said, I've run into some issues, and am hoping you all might have some suggestions.

# commands used

## add + query

``add <task properties>`` followed by arbitrary queries, such as:
```
   task abbv_stsk.not:uspc due:tod +PENDING
```
where ``abbv_stsk`` is a uda.

### expected behavior

That the query should return an accurate result in a reasonable amount of time.

### actual behavior

Intermittently, this message appears: ``Clear working set query``.

Typically, the second query succeeds. 

### the general case: quries

As a general matter queries are slower than they were in the previous version. 
I don't have specific numbers, but subjectively there is a very noticeable delay (I would guess 500 ms or so).

### the stressed case: serial dup commands

I have a shell function that creates clones of a given set of template tasks, each of which has a particular uda value. The function gets the uuids of the template tasks and then uses the ``dup`` command to instantiate them. There are about 5-7 template tasks per uda value, and four uda values. In other words, four sets of 5-7 templates.  In the previous version, this process went reasonably quickly (well under a few  seconds per set of dups). 

In the new version, it is painfully slow to wait for it to create each set. Here is the code that creates the duplicates:

```
   "$(echo 'all' | task ${template_stsk_ids} dup -tmpl due:${clone_due_date}+18h wait:${clone_due_date} until:${clone_due_date}+23.95h)"
```

This takes about 10 seconds per invocation. 

## the case that probably breaks the rules

For the previous version, I was using the following command to display a report persistently, such that when I added or modified the task, I got immediate feedback without having to re-run the report manually:

```
  cmnd="fswatch --one-per-batch --event Updated --event IsFile ${TASKDATA}/taskchampion.sqlite3 |  xargs -n1 -I{} task ${report_name_and_args}"
```

This system worked surprisingly well. And ``git``, where I was keeping my task data (this is another story), had no problem with the files being under the watchful eye of ``fswatch``.

Now, in the new version, it seemed like I was getting more of the "Clear working set query"  errors, and so switched to something I had been planning on for some time anyway: I have layout of panels using the rich library, and there is a while loop that periodically runs the queries of interest to me each int its own panel. 

I am pretty sure that when that loop is running, I get many more of the "Clear working set query." To be clear, I still get the "Clear working set query" even without the loop. But with the loop there are many more of them, usually when I run a query in a plain terminal. 

As an aside: git does not like other processes competing with it for a read handle on a binary file, and so it rejects any attempt to add it to a commit.

I saw discussions about others trying to achieve the same effect in various ways in the previous version, and the answer was that task is not designed for concurrent access to its data. My ``fswatch`` trick seemed to get away with this, but I think I might have reached the end of the line with what I am trying to achieve with task. 

Please advise.

# diag output

```
task 3.0.0
   Platform: Linux

Compiler
    Version: 13.2.1 20230801
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
     Commit: 3e41fb604
      CMake: 3.29.0
    libuuid: libuuid + uuid_unparse_lower
 Build type: 

Configuration
       File: /home/xxxxx/.taskrc (found), 18373 bytes, mode 100644
       Data: /home/xxxxx/data-xxxx/code/pjct/time/tskw (found), dir, mode 40755
   TASKDATA: /home/xxxxx/data-xxxx/code/pjct/time/tskw
    Locking: Enabled
         GC: Enabled
    $VISUAL: vim
Hooks
     System: Enabled
   Location: /home/xxxxx/data-xxxx/code/pjct/time/tskw/hooks
             (-none-)

Tests
   Terminal: 164x62
       Dups: Scanned 9966 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 9966 tasks for broken references:
             No broken references found

```

# diag output

```
task 3.0.0
   Platform: Linux

Compiler
    Version: 13.2.1 20230801
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
     Commit: 3e41fb604
      CMake: 3.29.0
    libuuid: libuuid + uuid_unparse_lower
 Build type: 

Configuration
       File: /home/xxxxx/.taskrc (found), 18373 bytes, mode 100644
       Data: /home/xxxxx/data-xxxx/code/pjct/time/tskw (found), dir, mode 40755
   TASKDATA: /home/xxxxx/data-xxxx/code/pjct/time/tskw
    Locking: Enabled
         GC: Enabled
    $VISUAL: vim
Hooks
     System: Enabled
   Location: /home/xxxxx/data-xxxx/code/pjct/time/tskw/hooks
             (-none-)

Tests
   Terminal: 164x62
       Dups: Scanned 9966 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 9966 tasks for broken references:
             No broken references found

```

**Comment by djmitche** [comment]
## Errors around working set

Regarding "Clear working set query", that is context for an error from the operation to clear the working set:
https://github.com/GothenburgBitFactory/taskwarrior/blob/5a56cff88ba679629050d05376efb362db5d4bd2/taskchampion/taskchampion/src/storage/sqlite.rs#L353-L358

In theory, that should come with an error message -- context just adds more information to the actual error. Is there more output you could share? I would guess that there is some conflict in the DB causing this issue, but that shouldn't happen, so would warrant further investigation.

The [working set](https://docs.rs/taskchampion/latest/taskchampion/struct.WorkingSet.html) is what maps task ID's to UUIDs, It gets rebuilt during "gc" operations, when task IDs might get reassigned (this is not new behavior with 3.0.0, just a new implementation). In the process of performing such an operation, the working set is cleared and then rewritten. This is pretty slow -- clearing and re-writing a full (if small) SQL table, and it sounds like the commands you're running are doing so frequently, such as in response to the fswatch changes. One tweak that may help is to add `rc.gc=no` to the commands that are showing reports but which should not renumber the working set. In fact, I have a similar setup to yours that updates a query when things change -- the scripts are [here](https://gist.github.com/djmitche/e93ec66372271e08f7f3818ce95e7b92) if you'd like to take a look. I've been rocking this with the devel branch for months now without any trouble.

## Performance adding tasks

Adding tasks is slow. This is apparent when running `task import` for a new 3.0 install. Part of the reason for this is that each _field_ of each task is added in its own `Update` operation, which involves two insertions into the DB and committing the resulting transaction. Instead, we should be batching those up at least into one transaction per task. GothenburgBitFactory/taskchampion#372 would address this issue.

Regarding performance in general, yes -- there's lots of room to do better here. I think such optimization is compatible with current designs and APIs, it just needs the work done.

**Comment by pglaser-engineer** [comment]
Thank you @djmitche so much for this information -- it is very helpful. 

I did think of the ``rc.gc=no`` option but wasn't sure exactly when to use this. 

What I read (and this may have been from tw2) is that garbage collection happens the next time you do a query after a write operation. I was concerned about orchestrating things in such a way that I don't end up with stale ids in my report results. 

But perhaps this assumption is incorrect. Do write operations also trigger a gc? Or is there some other way to explicitly trigger a gc before I run the other queries with ``rc.gc=no``?

As for additional error information: I am not seeing any. All I see is the "clear working set" message.  The fact that I get the message even when I am not running the panel queries in a loop concerns me. The ``diagnostic`` command reports that the state of the data is ok. But does that really look at the sqllite db? And/or is there any other recommended way of validating the db's integrity? 

As an aside, I am increasingly uncofmortable with running a loop or using ``fswatch`` to trigger the query refresh. This is either creating unnecessary query thrashing or keeping an open handle on the sql file, which intuitively doesn't seem like a good idea. My thought process now is to put my rich panels under the control of a lightweight http server: I would post to the server in a taskwarrior hook whenever there is an add or update, and the server would in turn cause the queries to be re-run. 

Thanks!
--Phil

**Comment by pglaser-engineer** [comment]
Oh wait, jk, I think I found it: 

``task >/dev/null 2>/dev/null``

So before running the queries that I want, I would run ``task >/dev/null 2>/dev/null`` and then use ``rc.gc=no`` for the queries I care about? 

Thanks. 
--Phil

**Comment by djmitche** [comment]
Personally, I _want_ my panels to show "stale" IDs because I might be remembering the ID for a task. For example, if the panel says
```
13 Prune roses
19 Sow snap peas
20 Cover rhubarb
```
and I finish task 19, the very next command I type might refer to `20`, and if the display update automatically renumbers tasks, then 20 won't be "Cover rhubarb" anymore.

But, if you want your IDs to change more quickly, then your command is a good technique.

**Comment by djmitche** [comment]
I've filed a new issue for the working-set error. I think the performance is too broad a project to track in a GitHub issue. Is there anything else needed in this issue?

**Comment by pglaser-engineer** [comment]
Yeah GothenburgBitFactory/taskwarrior#3325 looks just right. Thanks for capturing that. 
Agree that the performance issue is a broader architectural thing. 
Cannot think of anything else for the issue. 

Oh and interesting point about allowing "stale" ids. 

Thanks!
--Phil
