### ISSUE TITLE
Invalid UUID given for `sync.server.client_id` results in unhelpful error

### ISSUE THREAD

**Issue by Taomach** [GothenburgBitFactory/taskwarrior#3326]
I am trying to setup the synchronization on the 3.0 version of taskwarrior. I don't want to rely on Google services for this and prefer the self-hosted solution. `man 5 task-sync` mentioned that I can use taskchampion sync server for this, so I set it up on my machine (version 0.4.1).

I have the following lines in my .taskrc:
```
sync.server.origin="http://$MYHOSTNAME"
sync.server.client_id="$MYUUID"
sync.encryption_secret="$MYSECRET"
```
However, when I run `task sync`, all I get is this: `Unknown error. Please report.`

`task diag` output:
```
task 3.0.0
   Platform: Linux

Compiler
    Version: 13.2.1 20230801
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
     Commit: 3e41fb604
      CMake: 3.29.0
    libuuid: libuuid + uuid_unparse_lower
 Build type: 

Configuration
       File: /home/sergey/.taskrc (found), 2449 bytes, mode 100644
       Data: /home/sergey/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
  rc.editor: nvim
Hooks
     System: Enabled
   Location: /home/sergey/.task/hooks
     Active: on-modify.timewarrior (executable)
   Inactive: 

Tests
   Terminal: 120x30
       Dups: Scanned 1723 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 1723 tasks for broken references:
...
```

**Comment by pglaser-engineer** [comment]
You are not the first user to raise this question.  Have a look at [3299](https://github.com/GothenburgBitFactory/taskchampion-sync-server/issues/2)

**Comment by djmitche** [comment]
Well, this is the first issue to identify a bug in the sync-server support. so thanks for filing!

The error message is the most generic "something unanticipated went wrong!" error - basically, an error occurred that isn't a string that `task` can print to the console. So all you see is this not-very-useful message.

I managed to make a lucky guess as to what causes the error: if the client ID is not a valid UUID. Is that correct? If so, hopefully that gets you on your way -- but please leave this open so I can improve the error message.

**Comment by Taomach** [comment]
> I managed to make a lucky guess as to what causes the error: if the client ID is not a valid UUID. Is that correct?

No, I used uuidgen to generate it, as suggested by the man page. Currently, the line looks like this: `sync.server.client_id="12f24983-2e75-4ef9-a81a-a37bf93f6baf"` (I don't think this is sensitive information, I will change the UUID later anyway).

**Comment by Taomach** [comment]
I've managed to get it to work! The problem was with the quotes in my  .taskrc. I've removed the quotes, and it synced!

**Comment by djmitche** [comment]
Thanks! I've updated the issue title.

**Comment by djmitche** [comment]
Maybe related to GothenburgBitFactory/taskwarrior#3332, but I think figuring out why this error isn't even a `std::string` is a different task than writing better error messages.
