### ISSUE TITLE
on-exit  has no input?

### ISSUE THREAD

**Issue by pglaser-engineer** [GothenburgBitFactory/taskwarrior#3327]
Greetings,

It appears to be that the on-exit event does not behave as documented:  the input for add and modify tasks is not passed along to the script.

# test procedure

* copied the [on-exit](https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/scripts/hooks/on-exit) example script to my ``hooks`` directory
* added a task

# expected behavior

That the number of tasks added (in this case 1) would be echoed to ``stdout``

# actual behavior

The number of tasks was reported as 0: ``on-exit: Counted 0 added/modified tasks.``

I tried this in python trying to get the input as ``input_tasks: str = sys.stdin.readline()``
and as ``input_tasks = Task.from_input()``. These too resulted in an empty string.

# output of task diag

```
task 3.0.0
   Platform: Linux

Compiler
    Version: 13.2.1 20230801
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
     Commit: 3e41fb604
      CMake: 3.29.0
    libuuid: libuuid + uuid_unparse_lower
 Build type: 

Configuration
       File: /home/*****/.taskrc (found), 18373 bytes, mode 100644
       Data: /home/*****/data-****/code/pjct/time/tskw (found), dir, mode 40755
   TASKDATA: /home/*****/data-****/code/pjct/time/tskw
    Locking: Enabled
         GC: Enabled
    vim: vim
Hooks
     System: Enabled
   Location: /home/*****/data-****/code/pjct/time/tskw/hooks
     Active: on-exit-example.sh (executable)
             on-exit.py         (executable)
   Inactive: 

Tests
   Terminal: 177x36
       Dups: Scanned 10444 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 10444 tasks for broken references:
             No broken references found

on-exit: Counted 0 added/modified tasks.
INPUT TASKS: 
 ~  
```

Many thanks for your help.
--Phil

**Comment by djmitche** [comment]
Hm, that corresponds to this TODO:
https://github.com/GothenburgBitFactory/taskwarrior/blob/8a0a98d3efd58dc3354bc0b26a1bfc2b9ba9a843/src/TDB2.cpp#L209-L214

**Comment by djmitche** [comment]
Maybe a quick way to address this is just to keep a list of modified tasks in the TDB2 instance?
