### ISSUE TITLE
Cannot synchronize properly

### ISSUE THREAD

**Issue by Just-here-to-copy-ur-code** [GothenburgBitFactory/taskwarrior#3340]
I am using taskwarrior on Arch Linux. I automatically output my tasks by running the command "task list" from my .zshrc.
This works fine and I can add remove and see my settings. However I am getting an error below the tasks.

There are 69 local changes.  Sync required.

Upon running "task synchronize", I get the error 

No sync.* settings are configured.

task diag:

task 3.0.0
   Platform: Linux

Compiler
    Version: 13.2.1 20230801
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
     Commit: 3e41fb604
      CMake: 3.29.0
    libuuid: libuuid + uuid_unparse_lower
 Build type:

Configuration
       File: /home/arjan/.taskrc (found), 1380 bytes, mode 100644
       Data: /home/arjan/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
Hooks
     System: Enabled
   Location: /home/arjan/.task/hooks
             (-none-)

Tests
   Terminal: 165x66
       Dups: Scanned 13 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 13 tasks for broken references:
             No broken references found

![Image of Note from task list](https://github.com/GothenburgBitFactory/taskwarrior/assets/113679903/294fdc55-0912-4dd5-9dee-1ddf2461ec51)

![task sync](https://github.com/GothenburgBitFactory/taskwarrior/assets/113679903/905fd450-4d89-4794-b19e-9ea3000e967e)

**Comment by djmitche** [comment]
The `task-sync(5)` manpage has information on setting up synchronization. If you only use one system, then a local sync is an option. We are also working on disabling the "Sync required" message in #3297 .

**Comment by Just-here-to-copy-ur-code** [comment]
> The `task-sync(5)` manpage has information on setting up synchronization. If you only use one system, then a local sync is an option. We are also working on disabling the "Sync required" message in #3297 .

I looked up the manpage and configured a local sync. 

This issue can be closed now.
