### ISSUE TITLE
Which sync server should I use for v3.0.0?

### ISSUE THREAD

**Issue by Mebus** [GothenburgBitFactory/taskwarrior#3345]
Hallo,

I am trying to use the sync-server from https://github.com/taskchampion/taskchampion with taskwarrior 3.0.0. Am I supposed to do that or is there a server in taskwarrior 3.0.0 that I am supposed to use?

I get this error on the server side, when I try to sync:

```
[2024-04-06T22:05:42Z DEBUG actix_web::middleware::logger] Error in response: "bad x-client-id"
```

Mebus

**Comment by djmitche** [comment]
There's one in the Taskwarrior repo. See GothenburgBitFactory/taskchampion-sync-server#2.

**Comment by Mebus** [comment]
Hey,

nice. I built this dockerized version of the server:

https://github.com/Mebus/taskwarrior-server-dockerized

Unfortunately now I keep getting this error on the server, when I try to sync two clients:

```
taskwarriorsyncserver  | [2024-04-06T23:38:55Z DEBUG actix_web::middleware::logger] Error in response: "no such version"
taskwarriorsyncserver  | [2024-04-06T23:38:55Z INFO  actix_web::middleware::logger] 172.19.0.1 "GET /v1/client/get-child-version/97a5d72-8703-4c33-a747-c1f539fb7bc4 HTTP/1.1" 404 15 "
```

Why is that happening?

Mebus

**Comment by Mebus** [comment]
It seems that the synchronization works despite the error message. 🤔

**Comment by djmitche** [comment]
Hm, that's a poor choice of logging phraseology. It's basically Actix responding with a 404 in an expected circumstance (it's been asked if there are versions after the latest one on the client).
