### ISSUE TITLE
Question regarding sync status on v3.0

### ISSUE THREAD

**Issue by manoelpqueiroz** [GothenburgBitFactory/taskwarrior#3346]
Hi guys, congratulations on the release of v3! I've been using Taskwarrior since 2018 (back then on a Cygwin installation) and I say without a doubt this is the most influential software of my life: it got me both into Linux and the GTD method later, huge things I can't live without now. So thank you for all the continuous development over the years!

I have one question: before v3, the `There are n local changes.  Sync required.` message would only appear if you set the credentials on `.taskrc`. However, I have yet to set up a new server after the latest version, yet even if my credentials are no longer defined in the config file, I get the sync message anyway.

I attempted looking at `man task-sync`, but there is not mention on how to list or remove any credentials potentially stored in Taskwarrior. And I get the following output for this command:

```
$ task sync --help
No sync.* settings are configured.
```

I have also removed any `*.pem` and `*.data` files from `/.task`. So starting from v3, will the sync message be displayed by default?

**Comment by djmitche** [comment]
That will be fixed in the next release - see #3297.

Aside from your `.taskrc`, credentials are not stored anywhere.

**Comment by djmitche** [comment]
Also, thanks for the compliment! Taskwarrior is, I think, a very squarely "unix" kind of utility.
