### ISSUE TITLE
task 3.0.0 and taskchampion-sync-server on localhost/oracle fails to sync

### ISSUE THREAD

**Issue by marekjg** [GothenburgBitFactory/taskwarrior#3349]
#### To report a bug...

I've built task 3.0.0 and taskchampion-sync-server from release tarball. I've opened 8443 port on my localhost and oracle machine (I was testing both options). I've set taskrc:
```
sync.server.origin=localhost:8443
sync.server.client_id=4b21ecf6-520b-4b16-b265-4853b400f4ed
sync.encryption_secret=blabla
```
and built and run taskchampion-sync-server (with and w/o release flag - the result was the same):
```
cargo build -p taskchampion-sync-server --release
./target/release/taskchampion-sync-server --port 8443 --data-dir ./data
```
When I run `task sync` I get this error `Failed to synchronize with server`

Output from task diag:
```
task 3.0.0
   Platform: Linux

Compiler
    Version: 9.4.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.29.1
    libuuid: libuuid + uuid_unparse_lower
 Build type: release

Configuration
       File: /home/marek/.taskrc (found), 1551 bytes, mode 100664
       Data: /home/marek/.task (found), dir, mode 40775
    Locking: Enabled
         GC: Enabled
Hooks
     System: Enabled
   Location: /home/marek/.task/hooks
             (-none-)

Tests
   Terminal: 120x30
       Dups: Scanned 0 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 0 tasks for broken references:
             No broken references found
```

What am I doing wrong? I've searched other issues related to taskwarrior 3.0 and taskchampion-sync-server and couldn't find solution.

**Comment by djmitche** [comment]
The origin might need `http://` -- I'm not sure if that is defaulted.

Is the server logging anything?

**Comment by felixschurk** [comment]
I had a the same issue and the `http://` prefix solved it.

I think we should definitely add that to the documentation in https://github.com/GothenburgBitFactory/taskchampion-sync-server/issues/2.

**Comment by djmitche** [comment]
That's more of a client-side configuration issue, so let's document it there. I think that means both the `taskrc(5)` and `task-sync(5)` manpages.

**Comment by marekjg** [comment]
Great, adding http helped! Thanks, I've spent too much time trying to figure it out myself

**Comment by djmitche** [comment]
I'll keep this open to update the docs.
