### ISSUE TITLE
task command outputs "No matches." after upgrading (2.6.2-2 -> 3.0.0-2)

### ISSUE THREAD

**Issue by bjt-user** [GothenburgBitFactory/taskwarrior#3350]
#### No matches after upgrade to 3.0.0

Hello.

Operating system: "Arch Linux"

The `task` command does not show my tasks anymore.\
Instead it prints "No matches."

I tried using `task all` or `task list`, but that prints the same line.

This is the version that I am currently running:
```
$ task --version
3.0.0
```

I just upgraded from 2.6.2-2 to 3.0.0-2 this morning.\
The same thing happened on a different machine, so it is unlikely that I accidently deleted tasks.

I couldn't find anything in the release notes when typing `task news`.\
There were just changes documented that came with 2.6.0.

**Comment by ryneeverett** [comment]
See https://github.com/GothenburgBitFactory/taskwarrior/releases.

Updating the news is in progress: https://github.com/GothenburgBitFactory/taskwarrior/pull/3342.

**Comment by djmitche** [comment]
I didn't realize `task news` existed until after the release. This was my first release, but I see that 2.6.1 and 2.6.2 also didn't have news. Sorry about that! I've now added it to the (newly documented) release steps.
