### ISSUE TITLE
Remove top-level `NEWS`

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3353]
The `NEWS` file appears to have been added in 2.6.0, at the same time as the `task news` command, and has similar information, This seems a bit redundant to the ChangeLog and `task news`, so let's remove it.

@tbabej, what do you think?

**Comment by tbabej** [comment]
I agree that `task news` is likely sufficient, I don't remember why I thought to add the NEWS file as well. Less places to maintain in sync the better!

**Comment by felixschurk** [comment]
@djmitche 

I think this `NEWS` link got overlooked, just realized it to late.

https://github.com/GothenburgBitFactory/taskwarrior/blob/7c465ceb8fd58e8eb7b9ff3aedd94deb691a9cf3/CMakeLists.txt#L153

**Comment by djmitche** [comment]
Hah, oops. I figured "how could removing a text file make CI fail?!" and I was wrong.
