### ISSUE TITLE
count reports the wrong output

### ISSUE THREAD

**Issue by adriangalilea** [GothenburgBitFactory/taskwarrior#3368]
When I ask for a `list`
```
❯ task due.before:now+1hour -notified list

ID Age   P Project      Tags Sch  Due        Description                        Urg 
 9 14h   H finances.car next      2024-04-15 put up for sale on milanuncios     36.8
```

It works

But when I ask for a `count`
```
❯ task due.before:now+1hour -notified count
7
```
It doesn't

**Comment by djmitche** [comment]
More experienced filter-ers can correct me here, but I think this is because `list` implies a filter which, among other things
```
report.list.filter=status:pending -WAITING
```
if you use `task <filter> all` I think you'll see seven results.

Hopefully that helps -- please comment if not and I will re-open.
