### ISSUE TITLE
wait:soww not working

### ISSUE THREAD

**Issue by adriangalilea** [GothenburgBitFactory/taskwarrior#3375]
As per https://taskwarrior.org/docs/named_dates/
`soww, eoww - Start of the next work week. End of the work week. Time is 0:00:00 local.`

soww should push the wait until the start of the next work week, but it doesn't.

edit: in genera I found several inconsistent behaviour between what is expected to happen and documented and what it happens.

How do I wait a task till next monday?

**Comment by felixschurk** [comment]
If the task should wait until the next monday you could simply use
```sh
task <id> wait:monday
```

I think this issue goes into a similar direction as #3275, so lets link them together.

**Comment by felixschurk** [comment]
However, I can not fully understand your description. 
If you add a task today and run `wait:soww` which date will get created?

On my setup it sets it to the current start of the working week, where `wait:monday` sets waiting to the next upcoming Monday.

**Comment by adriangalilea** [comment]
If I do `wait:soww` I get `Wait until:        2024-04-15 00:00:00`
which contradicts my expectation from reading the docs `Start of the next work week.` that should be `2024-04-22 00:00:00`

I'll use monday in the meantime, thanks :)
