### ISSUE TITLE
Legibility and color contrast on the default theme

### ISSUE THREAD

**Issue by adriangalilea** [GothenburgBitFactory/taskwarrior#3376]
Hello,

The themes on taskwarrior make it very hard to read certain tasks

<img width="1162" alt="image" src="https://github.com/GothenburgBitFactory/taskwarrior/assets/90320947/19a68471-9671-469f-be1c-a79aca66e7f2">

I tried a few different of the other themes, and have problems one way or another, I think this should be fixed, at the very least on the default theme.

Thanks.

**Comment by djmitche** [comment]
I think at least some of the themes were designed for a white background. I too have a dark background and I recall adjusting the color scheme pretty soon after starting to use TW.

It would be interesting to do some analysis of color schemes from an a18y and UX perspective and select good default themes for both dark and light backgrounds. I don't think there's any way to tell what the default background is for a terminal, so that would probably have to be in taskrc. I suspect different terminals look quite different, too, so that would take some comparison across the typical terminals on each platform.

If you'd be interested in doing that kind of analysis and developing a better color scheme, please do!

**Comment by adriangalilea** [comment]
> If you'd be interested in doing that kind of analysis and developing a better color scheme, please do!

As for documentation all I see is [this docs](https://taskwarrior.org/docs/themes/) which isn't very helpful. I'm digging in the code and learned about `task color`, will be taking a look at it.

As for the light/dark is there any way I can create a theme that's responsive in that regard?

> I think at least some of the themes were designed for a white background.

This contradicts the docs:

> By default, without any selected theme, Taskwarrior uses a simple dark theme (dark-16.theme or dark-256.theme depending on your system). This means there is the assumption of a dark-background in your terminal. If you use a light background this will look bad, and you should select a light theme instead.

![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/90320947/2a7cdf67-0124-4244-a6a9-c250cfce8e48)

I tried `kitty` `terminal` and `warp` they all looked different than this screenshot.

So... do other people see the default theme different than me perhaps?

EDIT: is there a way to define opacity/alpha I use it heavily when designing UI

**Comment by adriangalilea** [comment]
```
 ID:                28
# UUID:              8909fb3d-f713-4650-88fe-3119e0ab6962
# Status:            Pending
# Mask:              
# iMask:             
  Project:           self_fm.dev
# Separate the tags with spaces, like this: tag1 tag2
  Tags:              todo
  Description:       146: try catch site and username creation in case username is taken
  Created:           2024-04-17 12:26:37
  Started:           
  Ended:             
  Scheduled:         
  Due:               
  Until:             
  Recur:             
  Wait until:        
# Modified:          2024-04-17 23:01:38
  Parent:            
# Annotations look like this: <date> -- <text> and there can be any number of them.
# The ' -- ' separator between the date and text field should not be removed.
# Multiline annotations need to be indented up to <date> (21 spaces).
# A "blank slot" for adding an annotation follows for your convenience.
  Annotation:        2024-04-19 09:57:35 -- 
# Dependencies should be a comma-separated list of task IDs/UUIDs or ID ranges, with no spaces.
  Dependencies:      
# User Defined Attributes
  UDA priority:      L


```

I'm not seeing why tasks like this are shown with color
<img width="682" alt="image" src="https://github.com/GothenburgBitFactory/taskwarrior/assets/90320947/0212f955-8d2c-434f-bcbb-f01c21176a82">

in a theme like this
```
# General decoration
color.label=
color.label.sort=
color.alternate=on gray2
color.header=rgb013
color.footnote=rgb013
color.warning=orange
color.error=red
color.debug=blue

# Task state
color.completed=
color.deleted=
color.active=rgb555 on rgb303
color.recurring=rgb115
color.scheduled=white on rgb113
color.until=
color.blocked=gray10
color.blocking=white on rgb202

# Project
color.project.none=

# Priority
color.uda.priority.H=rgb404
color.uda.priority.L=gray15

# Tags
color.tag.next=
color.tag.none=
color.tagged=

# Due
color.due=rgb015
color.due.today=rgb125
color.overdue=color5

# Report: burndown
color.burndown.pending=on rgb103
color.burndown.started=on rgb214
color.burndown.done=on gray4

# Report: history
color.history.add=color0 on rgb105
color.history.done=color0 on rgb205
color.history.delete=color0 on rgb305

# Report: summary
color.summary.bar=white on rgb104
color.summary.background=white on rgb001

# Command: calendar
color.calendar.due=color0 on rgb325
color.calendar.due.today=color0 on rgb404
color.calendar.holiday=color15 on rgb102
color.calendar.overdue=color0 on color5
color.calendar.today=color15 on rgb103
color.calendar.weekend=gray12 on gray3
color.calendar.weeknumber=rgb104

# Command: sync
color.sync.added=gray4
color.sync.changed=rgb214
color.sync.rejected=rgb103

# Command: undo
color.undo.before=rgb103
color.undo.after=rgb305

```

**Comment by adriangalilea** [comment]
I think something's odd, all the screenshots on the color themes page show better contrast and legibility than what I experience.

In the meantime, I'll be using this theme, which is not something I like, but at least fixes my issues with every other theme I tested.

<img width="1135" alt="image" src="https://github.com/GothenburgBitFactory/taskwarrior/assets/90320947/1eb754d6-bc73-4d95-b30a-32aaa1be5cd3">

https://gist.github.com/adriangalilea/c0756755d364e87ccca186b1e0361d3d

I would love to have more colors and control somehow.

**Comment by djmitche** [comment]
Terminals are several decades older than I am, and have the layers of cruft to prove it.  The bit that Taskwarrior control involves sending byte sequences to the terminal to request specific colors, and those vary from terminal to terminal. Different terminal apps all make slightly different choices, whether that's in how they interpret the "standard" colors, the fonts they use, or how they render those fonts. Many terminals now support 256-color mode, which I expect offers a bit more control, but probably still differs from place to place. To my knowledge, there are no escape codes to control alpha. The terminals that do support alpha-blending are making their own determination of what to blend -- whether that's just the black background, all character backgrounds, or the entire window, or something else.

All of which is to say - there's lots of variability here, and I don't know how readily we could find a "good" general theme. But I'm glad you found something that works for you!

**Comment by adriangalilea** [comment]
Thanks, forgetting about transparency then.

What still bugs me is how different the screenshots look from what I see in 3 different terminals on mac,

Are the screenshots on the theme docs a good representation of how they really look like nowadays?

**Comment by djmitche** [comment]
I don't know what terminal was used to make those screenshots, but I would guess it's a good representation of how they look _on that terminal_, with the same fonts, etc.

**Comment by adriangalilea** [comment]
> I don't know what terminal was used to make those screenshots, but I would guess it's a good representation of how they look _on that terminal_, with the same fonts, etc.

I ask because I tried 3 different terminals, with different fonts, `warp`, `terminal` and `kitty` and in all of them there are items that can't be read with certain combinations.

Do you have items with poor legibility like I shown in the first pic on the default theme? @djmitche

**Comment by djmitche** [comment]
If I remove all of the colors from my .taskrc, this is what it looks like:
![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/28673/a4bd7c3a-6d12-434f-98ef-2f221bd06364)
I'm using urxvt256c on Linux with
```
  URxvt*foreground: White
  URxvt*background: Black
  URxvt*font: xft:Terminal-8                                                                                                                                                                                                                                                                                                   
  URxvt.letterSpace: -1
  URxvt.color12:      #1070ff                                                                                                                                                                                                                                                                                                  
  URxvt*color1:  #d83030                                                                                                                                                                                                                                                                                                       
  URxvt*color8:  #909090                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                               
  ! Xft                                                                                                                                                                                                                                                                                                                        
  Xft.dpi: 96.0                                                                                                                                                                                                                                                                                                                
  Xft.antialias: true                                                                                                                                                                                                                                                                                                          
  Xft.hinting: true                                                                                                                                                                                                                                                                                                            
  Xft.hintstyle: hintfull                                                                                                                                                                                                                                                                                                      
```
Those `URxvt*color..`options adjust some of the "standard" terminal colors, so maybe that helps with the appearance? I believe (it was a long time ago!) I made those adjustments because things like `ls` were showing blue text on a black background and it was very difficult to see. I think the Xft changes made the fonts anti-alias a bit better and thus look better at smaller sizes?

**Comment by adriangalilea** [comment]
Thank you,  (love the gardening stuff :P)

It seems to be similar to mine, I'm guessing if you have a yellow text task with white bg you have the exact same issue I was referring to.

But that doesn't seem to occur on the [screenshots in the docs](https://taskwarrior.org/docs/themes/) not sure what could have happened but all themes there look better than what I get in any terminal.

I can try to create a theme that solves the legibility issues and be as nice as possible. Is there any way I could reasonably access to more colors? If not I will see what I can do.

**Comment by djmitche** [comment]
If your terminal [supports 256 colors](https://www.robmeerman.co.uk/unix/256colours) then yes! I'm not sure there are any terminals that support more than 256..

**Comment by adriangalilea** [comment]
> If your terminal [supports 256 colors](https://www.robmeerman.co.uk/unix/256colours) then yes! I'm not sure there are any terminals that support more than 256..

Oh yeah, that's how I see the output of `task color` :) I meant more than that but I guess the limiting factor is the terminal then, alright, will investigate, many thanks!

**Comment by adriangalilea** [comment]
@djmitche I landed at this theme:

<img width="955" alt="image" src="https://github.com/GothenburgBitFactory/taskwarrior/assets/90320947/e4fff7e0-4a0e-4d25-9355-1f623415aa2a">

I have no legibility issues and I think it's pleasing enough.

One of the keys was using `inverse` in order to preserve legibility on some complex tasks like overdue, scheduled and next all at the same time.

Do I PR?

**Comment by djmitche** [comment]
I don't see any reason not to add another theme - a PR would be great!

**Comment by adriangalilea** [comment]
Let me know what you think  @djmitche

**Comment by djmitche** [comment]
Awesome, thank you so much!

**Comment by adriangalilea** [comment]
@djmitche Anything I should do to in order to add it on the site theme docs?

**Comment by djmitche** [comment]
Assuming you mean https://taskwarrior.org/docs/themes/, that would be a change in https://github.com/GothenburgBitFactory/tw.org

**Comment by adriangalilea** [comment]
@djmitche there you go!

**Comment by thomascharbonnel** [comment]
Strangely, the colors appear the same way as OP on my setup, not at all like in the screenshots.
Taskwarrior 3.4.1, kitty (same using foot), zsh, Sway/wayland, Fedora Sericea.
