### ISSUE TITLE
Quick question about the `backlog.data` file in v2

### ISSUE THREAD

**Issue by benelan** [GothenburgBitFactory/taskwarrior#3377]
I sync my tasks via git and I've been committing changes to `backlog.data`, which is where most of my merge conflicts occur.

I checked the doc but couldn't find anything about `backlog.data` (it's not even listed in the man page's FILES section). After looking through existing issues, it seems like the backlog is used for syncing via taskserver. 

Is `backlog.data` safe to gitignore and even occasionally prune if you don't use taskserver, or is it required for other functionality as well?

Thanks!

**Comment by djmitche** [comment]
Yeah, `backlog.data` is just the un-synced tasks, so if you're using Git you shouldn't need it.
