### ISSUE TITLE
When Un-Completing a Task, the ID Disappears

### ISSUE THREAD

**Issue by leohner** [GothenburgBitFactory/taskwarrior#3385]
Completing a task visually removes the `id` field when running the `task completed`. 

**Steps to Reproduce**
1. Create a task.
2. Run `task <task_id> done` to complete the task.
3. Run `task completed` to show the completed tasks. It shows the just deleted task as expected. However, it does not list the `id` of the task, only the `UUID`.
4. Assume that completing the task was done accidentally and it needs to be sent back into the main flow.
5. Run `task <task_uuid> start` to send it back into the main flow.
6. Run `task` to show the list of tasks. The returned task no longer has an `id` displayed.
7. Run `task <task_uuid> edit` to show the task details; it still has an `id`.
8. Exit the details page. Run `task` again. Now the `id` number shows correctly.

**Why this is an issue**
Unless you remember the UUID or the task id, you have no way of identifying and specifying that task.

Here is a list of images that show what's happening:

![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/17093330/7b5ba3f3-0341-4f81-9bdb-fb359a382d51)

![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/17093330/9c3ee4f6-466a-4ee9-a6e6-ee82fcd57ad2)

![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/17093330/4fd033e4-9fc6-4f4e-84a1-034261bf51d8)

![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/17093330/7f0f9c82-3049-48c3-ab15-78eafcf64236)

![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/17093330/d9490399-465d-4220-b8f6-bdbefba18455)

![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/17093330/e93dd739-3623-466b-943c-e789b220aee3)

![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/17093330/ea080fca-728a-4fac-b1c1-9c01b93f47ee)

* What did you expect to happen?

I would have expected to have continued to see the `id` number related to the task so I could reference it in future commands.

* What actually happened?

See steps to reproduce.

* Paste the output of the ```task diag``` command.

```
task 2.6.2
   Platform: Darwin

Compiler
    Version: Apple LLVM 15.0.0 (clang-1500.0.40.1)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.27.6
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.8.1
 Build type: Release

Configuration
       File: /Users/eric/.taskrc (found), 1398 bytes, mode 100644
       Data: /Users/eric/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
     Server:
         CA: -
Certificate: -
        Key: -
      Trust: strict
    Ciphers: NORMAL
      Creds:

Hooks
     System: Enabled
   Location: /Users/eric/.task/hooks
             (-none-)

Tests
   Terminal: 265x110
       Dups: Scanned 19 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 19 tasks for broken references:
             No broken references found
```
---

###### Addendum

ℹ️ I am new to taskwarrior, but I am really enjoying it so far. If this is, in fact, a bug, I would gladly dig into it. I'd love to help support the community. Thank you!

**Comment by felixschurk** [comment]
Hei, as far as I am aware, this is the intended behaviour of taskwarrior. As after completion of a task the IDs are getting updated. This behaviour is also a bit described in the documentation [1], however I am not completely sure how much it would change when you would upgrade to taskwarrior 3.0.1 [2] as there the storage backend is different.

However in your case if it was done by accident you can run `task undo` to have the last action undone, which would bring in this case the task back to the pending set. 

[1]: https://taskwarrior.org/docs/ids/
[2]: https://github.com/GothenburgBitFactory/taskwarrior/releases

**Comment by leohner** [comment]
Thank you for the quick reply! In my case, I didn't realize I marked the wrong task as `done` until a bit later, so `task undo` wouldn't have helped in my situation. 

In reading about the ID field, I would have expected some ID to be displayed:

> One downside is that ID numbers change occasionally, although in a predictable way.

I will upgrade to 3.0.1 and test it out there. I appreciate your help!

**Comment by felixschurk** [comment]
> I will upgrade to 3.0.1 and test it out there. I appreciate your help!

Be aware that due to the upgrade you would need to export and reimport the existing tasks as described [here](https://taskwarrior.org/docs/upgrade-3/).

If you are now starting to use taskwarrior and dont have any tasks pending or yet existing, you do not need to think about that.

**Comment by leohner** [comment]
Just tried on 3.0.1 and it seems to be resolved. Going to close this. Thank you!
