### ISSUE TITLE
Version prepended to task lists

### ISSUE THREAD

**Issue by Bckempa** [GothenburgBitFactory/taskwarrior#3386]
All commands that return a list of tasks prefix the output with the version number, so example the output of `task reports` is unchanged, but `task ls` now begins like this:

```
❯ task ls
3.0.1
ID D Project              Tags Due   Description
```

I noticed it starting in version 3.0.1 because it breaks the [shell integration](https://github.com/romkatv/powerlevel10k/issues/2648) I use, but I couldn't find mention of it in the release notes. Is this an intentional change?

I did a quick skim of the [release deltas](https://github.com/GothenburgBitFactory/taskwarrior/compare/v3.0.0...v3.0.1) but the location of the output didn't jump out at me immediately.

**Comment by djmitche** [comment]
Uh-oh - that looks like a stray debug print!

**Comment by Bckempa** [comment]
That makes sense, I was investigating some unexpected behavior in the news function and saw it pop up there as well. Presumable somewhere in the new Version class?

**Comment by feekApp** [comment]
Thx for fixing, noticed also some scripts were broken also in [PowerLevel10k](https://github.com/romkatv/powerlevel10k)

**Comment by djmitche** [comment]
Sorry, that was definitely a stupid mistake on my part :(

**Comment by feekApp** [comment]
no problem!
