### ISSUE TITLE
Update Fedora Docker Container from 38 to 40

### ISSUE THREAD

**Issue by felixschurk** [GothenburgBitFactory/taskwarrior#3390]
Currently, there are both 38 and 39 images for the test runs available. 
Fedora 38, will reach EOL at 2024-05-14 [0]. 

We could update the 38 image to the latest 40 release of Fedora and have then 39 and 40 available.

[0]: https://fedorapeople.org/groups/schedule/f-38/f-38-key-tasks.html

**Comment by djmitche** [comment]
Sounds like a good plan. I did a similar thing in #3248.
