### ISSUE TITLE
News does not remember last viewed version without undocumented option

### ISSUE THREAD

**Issue by Bckempa** [GothenburgBitFactory/taskwarrior#3391]
Running taskwarrior 3.0 and 3.0.1 I've been getting random reminders to read the version news, despite having read both `task news` and `task news 3.0.1 minor`. I would expect that to satisfy the automatic news version tracking.

Checking with `task show | grep version` I noticed that the `news.version` variable had not been updated. I had to check the [`CmdNews`](https://github.com/GothenburgBitFactory/taskwarrior/blob/a9995808eca56e87841f153c82694c142a83fd6f/src/commands/CmdNews.cpp#L653) source to discover that the saved "read version" is only updated when `task news all` is run, but the "all" specifier doesn't seem to be documented anywhere?

Logically something seems off, it only reverts the signal handler and asks for donations if the "all" command is used?

Not sure exactly what the intended behavior is and if that ending if case needs to be rescoped but I think at minimum reading the news should update the config flag. As a minimal change, maybe the "all" setting that updates the config flag should be the default?

I am willing to contribute a PR for this if given guidance on the preferred behavior.

**Comment by djmitche** [comment]
Thanks! @tbabej, I think you originated the `task news` support -- how do you think we should handle this?

**Comment by Bckempa** [comment]
Oh, and another interesting bit of behavior, I'm now getting news reminders for 3.0.2 because my config news version is 3.0.1, even though there aren't any unread news items, so a reasonable user could see this:

```
Recently upgraded to 3.0.2. Please run 'task news' to read highlights about the new release.
❯ task news
You are up to date!
```

Which in turn will continue to pop-up occasionally because of all the logic for marking new versions as read.

**Comment by tbabej** [comment]
The original intent of the `task news` command was to only display the footnote if the notes for the given version were not displayed yet. If the prompt to display news is shown in a repeated manner, I would definitely consider that a bug.

Similarly, displaying the major items should be sufficient. Using `minor` or `all` should not be required.

**Comment by tbabej** [comment]
Can't dive deeper right now but my suspicion would be that the bug revolves around the fact that in `CmdNews.cpp` now we [require `full_summary` flag to be on](https://github.com/GothenburgBitFactory/taskwarrior/blame/bc86a1e53f641e38d66df40c1a085830ea876d47/src/commands/CmdNews.cpp#L653) in order to set the config variable recording the last displayed news version, possibly recently introduced in #3342.

@Bckempa if you have capacity to double check and produce a PR with a fix, that would be highly appreciated!

**Comment by djmitche** [comment]
Maybe it's best to get rid of the minor/major distinction and just include major, then?

**Comment by Bckempa** [comment]
> @Bckempa if you have capacity to double check and produce a PR with a fix, that would be highly appreciated!

Might take me a few days to find the cycles, but I'm happy to take swing at this.

**Comment by djmitche** [comment]
@Bckempa did you get a chance to take a look?

**Comment by Bckempa** [comment]
Sorry I haven't, and I won't be able to until mid-July. I'm still happy to take a shot at it then, but no hard feelings if someone else wants to take it on sooner.

**Comment by djmitche** [comment]
OK, we'll see how it works out. I think this will be good to fix in the next release, so I might steal it. Anyone else is welcome to do so as well :)
