### ISSUE TITLE
Test for exact output from a simple report

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3393]
#3389 removes an accidentally-merged debug print that @Bckempa noticed made it all the way to the 3.0.1 release.

As @ryneeverett suggests, this wasn't caught in tests because they all check that the output contains some particular string -- if there's extra stuff that doesn't cause the test to fail. In general, that's good, but we should probably also have some tests that assert that _exactly_ the expected output is present, for some simple kinds of output.

Maybe a good one of those would be `task ls` for an empty task database, along with the necessary `rc.foo=..` to silence things that might change like `task news` output.

**Comment by felixschurk** [comment]
This is only half true, some tests especially the python tests would have caught that e.g.
```sh
70: # FAIL: AssertionError on file /usr/lib64/python3.12/unittest/case.py line 58 in testPartExecutor: 'yield':
70: #       '1' unexpectedly found in '3.0.1'
```
however as noted in #3388 the tests were not run...

But I guess its still a valid test case.

**Comment by djmitche** [comment]
Ah, good to know this would have been caught!

I think those test cases will have broader applicability -- and be less fragile -- than the one suggested here. So I'll close this issue.
