### ISSUE TITLE
task 3 start/end times not saved to task

### ISSUE THREAD

**Issue by elig0n** [GothenburgBitFactory/taskwarrior#3397]
I just upgraded to version 3.0 from Manjaro linux and finished the import to run task start which added the virtual tag ACTIVE and the Start: field to that task info but afterwards I ran task stop and then task info didn't show the summary of work time like it used show on previous version.

**Comment by djmitche** [comment]
This information was gleaned from the undo history of a task, looking for the timestamps where the `start` time was set and then un-set. That information is not captured in the new model (see #3060), so the summary is no longer shown. https://github.com/GothenburgBitFactory/taskchampion/issues/373 will restore a form of that information, and should allow display of such info again.

Let's leave this open, depending on that issue, to mark this missing functionality. (I thought we had an issue for that purpose but can't find it)
