### ISSUE TITLE
Restore `task purge` support

### ISSUE THREAD

**Issue by huantrinh1802** [GothenburgBitFactory/taskwarrior#3399]
* What command(s) did you run? 
`task status:deleted purge`
* What did you expect to happen? 
In v2.x, it works. In v3, it prints out
```As of version 3.0, this command has no effect.
Deleted tasks are removed from the task list automatically after they expire
```
* Why I need this?

  - I am writing a neovim plugin for interacting with Taskwarrior so I often create dummy tasks to test. 
  - Often I make a mistake, I will delete the task then reuse the previous command with correct info
  - It would be great to not see the deleted ones when running `all` report :)

**Comment by djmitche** [comment]
At the moment, expiration occurs [automatically at 180 days after the last modification of a task](https://github.com/GothenburgBitFactory/taskchampion/pull/341). 

Deletion is a little bit risky from the perspective of the sync model -- if there's another replica out there with changes to the deleted task, the task will end up out-of-sync between the two replicas -- but that's a tolerable risk when testing, for example. So, maybe we can add that support with that caveat documented somewhere.

**Comment by djmitche** [comment]
This will require https://github.com/GothenburgBitFactory/taskchampion/issues/383

**Comment by CorentinJ** [comment]
In testing some scripts I generated over 1,000 tasks. I deleted them, but they still clutter the database and make debugging harder. I would love to have a command to effectively remove them entirely.
