### ISSUE TITLE
[EX-38] import/ export .iCal

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#34]
_David Patrick on 2009-05-29T19:39:35Z says:_ 

 events and contacts

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-05-29T19:39:35Z
Modified: 2017-09-14T18:03:18Z
```

**Comment by taskwarrior** [comment]
_Pedram H on 2011-06-02T14:11:04Z says:_ 

 thumbs up for this to be implemented soon. It makes *migrating* from other task organizers easier especially with ability to *import ical* files. currently I almost manually extract and imported my 61 task. CSV file import is quite time consuming since different task organizers uses different heading and values.

**Comment by taskwarrior** [comment]
_Eric Fluger on 2011-06-03T00:10:43Z says:_ 

 Just a vocabulary note re ical vs icalendar: 

strictly speaking, ical and icalendar are not the same thing. 

as i recall ical was a standard developed by the internet mail consortium along with vcard.  both standards were handed off to the IETF.  the vcard standard has been revised but is still basically the same and is still called vcard.  the calendar format has evolved more and the current standard is called "iCalendar".  IIRC iCalendar supercedes iCal, which is obsolete, or at least depreciated.  the term "ical" makes a nice short hand for "icalendar" and i have no objections to using it that way as long as we're clear on which standard we really want supported.  (presumably the current one.)

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-06-03T00:27:55Z says:_ 

 The plan regarding import and export is to move these features out of the core.  There will be an _import and _export command that imports and exports only JSON.  Other formats will be supported by writing external scripts that convert to and from JSON, in any language.  There are already several export examples, and import sample will be completed soon.

This will allow anyone to implement the import and/or export format of their choice, and upload it to the site as an add-on script.

**Comment by taskwarrior** [comment]
_Eric Fluger on 2011-06-03T14:22:50Z says:_ 

 forgot to mention that the common filename extenstion for icalendar ".ics"

**Comment by taskwarrior** [comment]
_Romain Giot on 2017-09-14T18:03:18Z says:_ 

 Indeed, I'm using timewarrior with other tool and such kind of import would perfectly fits my need.

 timew import <filename> [<interval>]

would perfectly do the job.

This issue is old, but since the latest comments, only the export  command seems available, not the import one

**Comment by pbeckingham** [comment]
JSON is the only necessary export format.  No plans to implement.
