### ISSUE TITLE
Upgrade v3

### ISSUE THREAD

**Issue by christian43** [GothenburgBitFactory/taskwarrior#3401]
#### To report a bug...

unfortunately i upgrade taskwarrior 2.6.0 > 3.0.2 before exporting my database. 
Now the `task export` command does not work. Do you can help me please.
How can i fix my taskwarrior now?

**Comment by djmitche** [comment]
Sorry about that! You will need to install Taskwarrior-2.6.0 to run `task export`, and then re-import those tasks into 3.0.  Depending on your pacakage manager, the steps to install Taskwarrior 2.6.0 to do so differ. You may alternatively be able to just install it temporarily (such as building from source).

**Comment by christian43** [comment]
Okay, thank you for your response. I have installed task with brew, where no older version exists anymore. So where I can get the older version?

**Comment by djmitche** [comment]
I don't use Homebrew, so I don't know the answer to that -- I'm surprised it provides no way to downgrade, though! It looks like [this blog post](https://nelson.cloud/how-to-install-older-versions-of-homebrew-packages/) might have some hints..

**Comment by djmitche** [comment]
Oh, [this comment](https://github.com/GothenburgBitFactory/taskwarrior/discussions/3291#discussioncomment-9174123) has good information for you!

**Comment by christian43** [comment]
Thank you all for your help. Finally I found the version [https://github.com/GothenburgBitFactory/taskwarrior/releases/tag/v2.6.0](url) and installed it. After deleting and upgrading via brew to v3.0 I imported the json file. All works fine now and i continue to Taskwarrior.
