### ISSUE TITLE
Cleanup of old tasks from v3 sqlite database

### ISSUE THREAD

**Issue by svenXY** [GothenburgBitFactory/taskwarrior#3405]
Hi.

After having migrated to v3, the sqlite file is >3M. Most of the tasks have long been completed, so I'd like to get rid of them somehow.

Looking inside the database reveals that the tassk are stored as json-data, making it rather difficult to select those that have been completed long ago.

Do you have a possible solution or would it be feasible to provide something like a cleanup command to do that?

**Comment by djmitche** [comment]
Thanks for the issue. I think #3399 will be precisely what you want!
