### ISSUE TITLE
v3.0 autocompletion doesn't work in fish

### ISSUE THREAD

**Issue by chenyuntc** [GothenburgBitFactory/taskwarrior#3410]
I just upgraded to v3.0 and the autocompletion by fish doesn't work any work (tab doesn't complete)

**Comment by chenyuntc** [comment]
Somewhat works now by install an older version and install the latest one again

**Comment by djmitche** [comment]
Thanks for the report -- not much has changed with command-line completion, so I'm glad it got fixed up with a reinstall..
