### ISSUE TITLE
Coverage data in GH Actions

### ISSUE THREAD

**Issue by felixschurk** [GothenburgBitFactory/taskwarrior#3413]
When looking, what accidentally happened in #3271, e.g. kicking out the python tests, I guess it would make sense to have some coverage data available in the repository, automatically build by GH Actions on every PR. To provide a broad overview and an easy to see metric for incoming PRs.

As I can see, this was available in #1984, but probably got lost when transitioning to GitHub.
Maybe it can also be used when new functionality is added to have some feedback if it is tested or not. 

I guess a starting point would be to use [Code Coverage Summary](https://github.com/marketplace/actions/code-coverage-summary) actions and instrument the code accordingly and collecting the data over [gcovr](https://github.com/gcovr/gcovr).
In order not to blow the complete GH Actions maybe it would make sense to run it only after the test were successful and maybe also only in one image (Debian, Ubuntu or Fedora) as the coverage should not change depending on the OS.

**Comment by djmitche** [comment]
I think that makes a lot of sense, and particularly the intent to have it wait for successful tests. Noticing when coverage drops dramatically would be very useful.

**Comment by felixschurk** [comment]
I will work on it :)

**Comment by felixschurk** [comment]
I think we would need to enable a separate Actions workflow, as the communication over the docker environment makes the actions itself quite complicated. 

With the current build time of 5 min I think that is an acceptable choice.

**Comment by djmitche** [comment]
That seems fine. The docker environments are useful for ensuring distro compatibility, but less so for determining coverage.
