### ISSUE TITLE
How do I upgrade JSON file after it's too late (taskwarrior 3)?

### ISSUE THREAD

**Issue by faxotherapy** [GothenburgBitFactory/taskwarrior#3417]
Hi, mi tk is part of a package manager. This is convenient, because after issuing something like `apt upgrade`, everything is upgraded. Apparently, I learnt that it's not a good idea with tk, because after upgrading to tk 3.0, I had the following message:
```
tk
Found existing '.data' files in /Users/Nathalie/.task
  Taskwarrior's storage format changed in 3.0, requiring a manual migration.
  See https://github.com/GothenburgBitFactory/taskwarrior/releases.
3.0.1No matches.
```

I thought tk 3.0 would have taken care of upgrading previous JSON, but it did not. So, I have to do it manually. I learnt that we have to export the JSON file before upgrading to 3.0, but I could not do this, since tk is part of my package manager. I was not aware of the need to upgrade the JSON file before I run my package manager.

I tried to follow this guide: https://taskwarrior.org/docs/upgrade-3/
But, doesn't seem to be useful for users issuing upgrade commands on their system.

#### To report a bug...

* What command(s) did you run? `task list`
* What did you expect to happen? To have the list of my task.
* What actually happened?
```
tk
Found existing '.data' files in /Users/Nathalie/.task
  Taskwarrior's storage format changed in 3.0, requiring a manual migration.
  See https://github.com/GothenburgBitFactory/taskwarrior/releases.
3.0.1No matches.
```

* Paste the output of the ```task diag``` command.
```
% task diagnostics
Found existing '.data' files in /Users/Nathalie/.task
  Taskwarrior's storage format changed in 3.0, requiring a manual migration.
  See https://github.com/GothenburgBitFactory/taskwarrior/releases.

task 3.0.1
   Platform: Darwin

Compiler
    Version: Apple LLVM 14.0.0 (clang-1400.0.29.202)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.29.2
    libuuid: libuuid + uuid_unparse_lower
 Build type: Release

Configuration
       File: /Users/Nathalie/.taskrc (found), 1419 bytes, mode 100640
       Data: /Users/Nathalie/.task (found), dir, mode 40750
    Locking: Enabled
         GC: Enabled
    $VISUAL: /usr/local/bin/vim
Hooks
     System: Enabled
   Location: /Users/Nathalie/.task/hooks
             (-none-)

Tests
   Terminal: 210x35
       Dups: Scanned 0 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 0 tasks for broken references:
             No broken references found
```
#### To request a feature...

* Clearly describe the feature.
I wish future mega version of TK include a way to make our life easier when upgrading JSON file. Example: why not using tk 3 to detect old JSON file and upgrade it to the new version, instead of doing some kind of precognition telling us “no, no, no, you have to upgrade JSON database BEFORE running your `brew upgrade` command”

**Comment by ryneeverett** [comment]
If you haven't navigated the upgrade yet, tips on getting taskwarrior-2 to do the migration seem to be collecting [here](https://github.com/GothenburgBitFactory/taskwarrior/discussions/3291#discussioncomment-9170444).

>       I wish future mega version of TK include a way to make our life easier when upgrading JSON file. Example: why not using tk 3 to detect old JSON file and upgrade it to the new version, instead of doing some kind of precognition telling us “no, no, no, you have to upgrade JSON database BEFORE running your `brew upgrade` command”

As for the feature request, there is no expectation that this kind of manual migration will be necessary in future major taskwarrior releases. I think I can speak for the team when I say that the taskwarrior developers also wish the migration to taskwarrior-3 were easier but nobody volunteered to do the work to make that happen.

**Comment by faxotherapy** [comment]
OK, managed to revert back to tk 2, followed the guide to upgrade JSON. Now, I have the following error:
```
% tk list
Found existing '.data' files in /Users/Nathalie/.task
  Taskwarrior's storage format changed in 3.0, requiring a manual migration.
  See https://github.com/GothenburgBitFactory/taskwarrior/releases.
3.0.1
ID Age  P Project     Tags               Description                                                Urg
 1 7mo  H Clips       Browser CLI Linux  Process videos in Downloads folder                         9.21
```

It shows my tasks, but keep showing the `Found existing '.data' files in /Users/Nathalie/.task`. How do I get rid of this message. Should I simply trask that file?

Thank  you for your help.
