### ISSUE TITLE
Warnings leak into bash auto-completion

### ISSUE THREAD

**Issue by belkka** [GothenburgBitFactory/taskwarrior#3419]
`task --version` is 3.0.2

I type `task new` with intention to run `task news` command ~and read the news about my tasks have been annihilated~. After typing `w` I get tired of typing, so, as hackers usually do in these situations, press "tab" to trigger bash auto-completion. I expect last argument to be completed to "news", but instead I see a multi-line warning duplicated several times

![task export shall not restore your data, give up hope](https://github.com/GothenburgBitFactory/taskwarrior/assets/16609579/93693d6e-a467-4609-ba71-7d0c22290585)

I believe **auto-completion** is not supposed to trigger these or any kind of warnings at all, because that leads to poor UI. It may be worth to review and rework the "warnings" mechanism to exclude them from auto-completion output.

**UPD** A more realistic example: I was doing instructions from https://taskwarrior.org/docs/upgrade-3/, i. e. downgraded taskwarrior, exported my tasks into ~/tasks.json, upgraded back to the future, typed `task import rc.hooks=0 tas`... and pressed `<Tab>` to autocomplete the file name... which filled my screen with warnings

**Comment by djmitche** [comment]
Hm, that's definitely a bug. I don't know much about completions, but I guess it involves running `task` somehow.  Maybe we should move this warning to only occur on reports (so in `src/commands/CmdCustom.cpp`)?
