### ISSUE TITLE
how do I re-install 2.6.2?

### ISSUE THREAD

**Issue by recursivelycurious** [GothenburgBitFactory/taskwarrior#3435]
brew upgraded this by accident and now all of my data, and my integration with Timewarrior is broken.

There is no homebrew formula for 2.6.2.

Can someone point me in the right direction to get and install an older tar manually or to directly invoke/force an older version from brew?

**Comment by ryneeverett** [comment]
See this thread: https://github.com/GothenburgBitFactory/taskwarrior/discussions/3291#discussioncomment-9174123

**Comment by recursivelycurious** [comment]
Thanks @ryneeverett - that thread was helpful.
