### ISSUE TITLE
Remove F4 support from src/Task.cpp

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3436]
In particular, `void Task::parse (const std::string& input)` and `std::string Task::composeF4 ()`, but there may be more.

There are some tests in `test/t.test.cpp` that can also be removed.

**Comment by ryneeverett** [comment]
I've never heard of F4 and now I'm curious. Was this an alternative storage backend at one point?

**Comment by djmitche** [comment]
It was the storage used in 2.x! I dont know what FF1..3 were
