### ISSUE TITLE
Feature request : option to return GUID for task add command 

### ISSUE THREAD

**Issue by KingJulianS** [GothenburgBitFactory/taskwarrior#3459]
#### To request a feature...

* could we add an option so that task add returns the actual GUID or atleast that portion of the GUID that can be used for all other operations i.e. Task GUID info, task GUID edit etc. 

* when using the GUID in automation, it does not create a broken link as the task ID does. For example, when automating I get task ID returned from the task add command, and if I store that it leads to problems later as tasks get completed and Id's go out of synch and are reallocated etc. Thus when the automation looks at task ID 2 later, it may have changed and therefore not so suitable for automation when linking a task reference say in a other document. However, the GUID remains the same which is a better way of keeping links in other docs. 

* Therefore, it will be much appreciated if there is atleast an option on receiving the immutable GUID back from a task add event as opposed to only the auto mutable task ID.

**Comment by maertsen** [comment]
I believe you may be able to use an on-add hook for this purpose. Perhaps have a look at the example hook in https://taskwarrior.org/docs/hooks_guide/.

**Comment by KingJulianS** [comment]
Thanks, I will have to park it for now then, because I do not have suitable knowledge as yet to write something like this.

I'm the interim, I will continue not to close the tasks to ensure the numbers don't change. Will just move all that's supposed to be closed to a certain date or something like 2099/12/31

**Comment by KingJulianS** [comment]
Closing it off from here, Thanks again for the response and link.

**Comment by dathanb** [comment]
If your use case is automation, you can exchange the id for the uuid right after adding with something like
```
shortId=(add task and extract the short id)
taskGuid="$(task ${shortId} export | jq -r '.[] | .uuid')"
```

**Comment by KingJulianS** [comment]
Hi @dathanb, thanks for the info, push and encouragement, I managed to hack something together, maybe not the nicest of things, but it works for my use case. 

So now, while editing a file in vim, I can select a few words, yank them, and simply type my key map `< leader>ta`. This will extract part of my buffers' file name, based on some naming convention I've been using for my notes, and use that as project and tag to create a new task with the yanked words.  Post this help, it will then insert the GUID at the beginning of my line that my cursor was on, like so `:TASK: guid `. I use Asciidoc for my writing, so now I will just have to learn to create an admonition for the `:TASK:`  identifier in Asciidoc. Next, is to just do a few mappings in vim so that when I rest my cursor on the GUID, it will show the task info. Then another few maps for GUID under cursor, one to annotate the task, to edit, close, and read the task info to insert it into my buffer.  I'm feeling good this Friday.
