### ISSUE TITLE
Clarify, in the tools list, the status of Inthe.am sync tool, as the server is now defunct 

### ISSUE THREAD

**Issue by samusz** [GothenburgBitFactory/taskwarrior#3469]
As stated in [this issue](https://github.com/coddingtonbear/inthe.am/discussions/427) Inthe.am service is no more. 

This (sad, but true) fact needs to be labelled as such in the [tools ](https://taskwarrior.org/tools/) page, to avoid false hopes.

Thank you all for your great work!

**Comment by djmitche** [comment]
See https://github.com/GothenburgBitFactory/tw.org/issues/770 -- if @coddingtonbear archives the repo, it will disappear.

@lauft, maybe this particular approach to automation isn't the best. Should we add some kind of option to override the github search?

**Comment by lauft** [comment]
@djmitche I will put it on the blacklist, then it will be gone. We could add it manually, marked archived.
On the other hand, with the deprecation of Taskserver, we should maybe remove the Taskserver tools from the list all together.
