### ISSUE TITLE
SIGABRT in coverage runs

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3507]
Hm, I'm seeing the SIGABRT in https://github.com/GothenburgBitFactory/taskwarrior/actions/runs/9613757645/job/26517145647?pr=3494

In wonder if that's due to the `-j8` in the `ctest` invocation? I was about to make a PR to _add_ `-j8` for the build, so I can try that.

_Originally posted by @djmitche in https://github.com/GothenburgBitFactory/taskwarrior/issues/3483#issuecomment-2182689611_

**Comment by djmitche** [comment]
@felixschurk we can continue the conversation from #3483 here (since that PR is closed and can't be re-opened).

**Comment by felixschurk** [comment]
I do think it has to be with the GitHub Ubuntu image, but I do not know yet how to debug it. I think maybe pulling the GitHub image locally and running in it the tests leads to some insights?

I assume it does not has to do anything directly with the parallel flags from `ctest` as locally, as well as in all the distro tests, the tests are run in parallel and we never saw such an error. 

For the time being, as a workaround, one can just rerun the failing CI runs... and hope it will work the next time.

**Comment by felixschurk** [comment]
When looking over the failed test runs [first], [second] and [third] all of them fail on some `task config ...` invocation.

[first]: https://github.com/GothenburgBitFactory/taskwarrior/actions/runs/9629105362/job/26558080511
[second]: https://github.com/GothenburgBitFactory/taskwarrior/actions/runs/9629096449/job/26558063202
[third]: https://github.com/GothenburgBitFactory/taskwarrior/actions/runs/9620433739/job/26538608969

**Comment by djmitche** [comment]
So another hypothesis I had was that the timeout logic was just waiting for a signal, and failing to retry on things like EINTR. But `wait_process` and `wait_condition` actually poll for `kill(pid, 0)` to return an error. It _looks_ pretty solid, but maybe there's some other weird dependency on kernel behavior there?

**Comment by djmitche** [comment]
Hm, I added some `print` calls in `wait_process` and `wait_condition` -- and now it won't fail.

**Comment by djmitche** [comment]
Ah, I spoke too soon - it fails!

```
ok 3 - bash_completion.test.py: no gc coming from bash completion
Mon Jun 24 01:28:04 2024 wait_process(6246, None)
Mon Jun 24 01:28:04 2024 wait_condition tries=100 timeout=1 sleeptime=0.01
Mon Jun 24 01:28:05 2024 stopped after 99 iterations
Mon Jun 24 01:28:05 2024 wait_process(6246, None)
Mon Jun 24 01:28:05 2024 wait_condition tries=100 timeout=1 sleeptime=0.01
Mon Jun 24 01:28:06 2024 stopped after 50 iterations
not ok 4 - bash_completion.test.py: project: should be expanded and dependent on abbreviation minimum
# ERROR: CommandError on file /usr/lib/python3.10/unittest/case.py line 59 in testPartExecutor: 'yield':
#        Command '('/home/runner/work/taskwarrior/taskwarrior/build/src/task', 'config', '--', 'alias.samplealias', 'long')' was SIGABRT'ed. SIGABRT usually means task timed out.
```

**Comment by djmitche** [comment]
So that waited for 1s, then killed the process and waited another 500ms.

**Comment by felixschurk** [comment]
Should we maybe check if it's the Runner image? 
I mean switching to either Ubuntu 20.04 or the Beta of Ubuntu 24.04. If it still occurs, we need to see how we can find a workaround.

**Comment by djmitche** [comment]
Sounds good - I made that change in my test PR.

**Comment by djmitche** [comment]
Still failed with 24.04:
```
1719253004.249394 got pid 7733
1719253004.249415 communicating
1719253004.249518 wait_process(7733, None)
1719253004.2495265 wait_condition tries=100 timeout=1 sleeptime=0.01
1719253005.257414 stopped after 99 iterations
1719253005.2574394 wait_process(7733, None)
1719253005.2574472 wait_condition tries=100 timeout=1 sleeptime=0.01
1719253006.265429 stopped after 99 iterations
1719253006.265457 wait_process(7733, None)
1719253006.2654681 wait_condition tries=100 timeout=1 sleeptime=0.01
1719253006.7978966 communicated
1719253006.806385 stopped after 53 iterations
not ok 6 - bash_completion.test.py: project: fails if shorter than rc.abbreviation.minimum
# ERROR: CommandError on file /usr/lib/python3.12/unittest/case.py line 58 in testPartExecutor: 'yield':
#        Command '('/home/runner/work/taskwarrior/taskwarrior/build/src/task', 'config', '--', 'alias.samplealias', 'long')' was SIGABRT'ed. SIGABRT usually means task timed out.
```

**Comment by djmitche** [comment]
(the more detailed logging confirms it's really sleeping for >1s. It's hard to imagine `task config` taking that long, but I'll try again with a longer timeout. CI machines are shared, so maybe??

**Comment by felixschurk** [comment]
Hm, seams that it helped the run. At least https://github.com/GothenburgBitFactory/taskwarrior/pull/3512/checks run without any problems. 

So if I see it right we can set the timeout for the Python tests in the script itself?

**Comment by djmitche** [comment]
I think the number I changed from 1 to 10 is the default, so that might be overridden by some scripts.

Let's run it a few times and see that it's still "fixed"
