### ISSUE TITLE
color doesn't change on arch wezterm

### ISSUE THREAD

**Issue by igorcalvo** [GothenburgBitFactory/taskwarrior#3508]
* What command(s) did you run?
taskwarrior-tui

* What did you expect to happen?
display green theme

* What actually happened?
default gray theme

* Paste the output of the ```task diag``` command.

```
task 3.0.2
   Platform: Linux

Compiler
    Version: 13.2.1 20230801
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
     Commit: bc86a1e53
      CMake: 3.29.2
    libuuid: libuuid + uuid_unparse_lower
 Build type:

Configuration
       File: /home/calvo/.taskrc (found), 1534 bytes, mode 100644
       Data: /home/calvo/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
  rc.editor: nvim
Hooks
     System: Enabled
   Location: /home/calvo/.task/hooks
             (-none-)

Tests
   Terminal: 276x53
       Dups: Scanned 1 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 1 tasks for broken references:
             No broken references found
```

Some additional information:
Running wezterm on arch and freshly installed both task and taskwarrior-tui via pacman

No theme seems to be loading despite following [this answer](https://github.com/GothenburgBitFactory/taskwarrior/issues/3461#issuecomment-2119314017 ) and not having changed the config file location.

Also tested on tilix to verify whether it was strictly a wezterm issue but the outcome is the same - no theme was changed.

`task color` is looking good too

![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/89422197/0cea338b-7c03-4297-bb2a-f4cc53a2d357)

.taskrc file after copying the theme from /usr/share/doc/task/rc/dark-green-256.theme to ~/.task/themes

![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/89422197/67781120-39b5-48db-b783-dcba2b16776b)

I'd like to see changes when either the theme file is referenced on .taskrc or its line is uncommented

Instead, I'm seeing grays:

![image](https://github.com/GothenburgBitFactory/taskwarrior/assets/89422197/4850eea8-dd3e-4680-819d-a362b286c54d)

**Comment by djmitche** [comment]
I didn't notice that this was `taskwarrior-tui` on first read. Does Taskwarrior itself not display themes? For example, `task next`? If so then this issue might be better in https://github.com/kdheepak/taskwarrior-tui.

**Comment by igorcalvo** [comment]
You're right! Thank you
