### ISSUE TITLE
Restore support for the journal in `task info`

### ISSUE THREAD

**Issue by sebastiancarlos** [GothenburgBitFactory/taskwarrior#3528]
Per taskrc(5):

```
       journal.info=1
              When  enabled,  this setting causes a change log of each task to be dis‐
              played by the ’info’ command. Default value is "1".
```

However, doing this doesn't show any change log:
```
$ task add test
$ task <id> modify new description
$ task <id> info
```

**Comment by djmitche** [comment]
Yes, #3060 removed that support. Once https://github.com/GothenburgBitFactory/taskchampion/issues/373 is done, we can re-add this support (by examining the operations for this task).
