### ISSUE TITLE
Error in parsing due date

### ISSUE THREAD

**Issue by snaka224** [GothenburgBitFactory/taskwarrior#3530]
* What command(s) did you run?

```
$ task add due:35 Bad task
Created task 10.
$ task
'35' is not a valid date in the '' format.
```

* What did you expect to happen?

Better syntax check due date and zero impact this error on the operation of other tasks.

* What actually happened?

The program `task` stopped working

* Paste the output of the ```task diag``` command.

```
$ task diag

task 3.0.2
   Platform: Linux

Compiler
    Version: 13.2.1 20230801
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
     Commit: bc86a1e53
      CMake: 3.29.2
    libuuid: libuuid + uuid_unparse_lower
 Build type: 

Configuration
       File: /home/vlad/.taskrc (found), 1378 bytes, mode 100644
       Data: /home/vlad/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
Hooks
     System: Enabled
   Location: /home/vlad/.task/hooks
             (-none-)

Tests
   Terminal: 215x35
       Dups: Scanned 15 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 15 tasks for broken references:
             No broken references found
```

PS. I can repair program by delete my last task like `task del 10`. But this can be done if I remember bad task number. Otherwise, I had to delete the last entry from the sqlite table.

**Comment by djmitche** [comment]
I think this is the same as #3444.

> PS. I can repair program by delete my last task like `task del 10`. But this can be done if I remember bad task number. Otherwise, I had to delete the last entry from the sqlite table.

This concerns me a little! Unless you also added a delete operation to the `operations` table, that will leave your tasks and your operations representing different values, and that could lead to divergence on sync. I think that would be limited to issues with this particular task, which is probably not a big deal. But, if you `sync` you will find that your deletion does not sync to the other replicas, so they will come to the same error.

Probably the better fix would have been `task purge` but that's not currently working - #3399. That would both delete the task from the tasks array (not just mark it as deleted) and also add a Delete operation to cause the same on other replicas.

Anyway, you didn't do anything wrong, but I'm sure others will be tempted to fiddle in the sqlite file and we should probably make sure we're resilient to that - https://github.com/GothenburgBitFactory/taskchampion/issues/410.

**Comment by djmitche** [comment]
(closing as a duplicate)
