### ISSUE TITLE
task-sync(5) claims sync occurs on every working-set rebuild

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3534]
```
Taskwarrior can perform a sync operation at every garbage collection (gc) run.
This is the default, and is appropriate for local synchronization.
```

..and this just isn't true.

@ryneeverett we had a good bit of discussion about this manpage in #3223 but I don't see anything about this in that PR. Do you remember anything specific there? My inclination is to "fix" this issue by just updating the docs to remove these sentences.

**Comment by ryneeverett** [comment]
This text was added during the ill-fated automated `gc.sync` experiment in #3118 and we missed it when that feature was reverted. Your "fix" sounds right to me.

**Comment by djmitche** [comment]
Ah, good memory - thanks!
