### ISSUE TITLE
Remove duplicate-task check from `task diag`

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3539]
TaskChampion stores tasks in a DB keyed by UUID, so barring a serious bug in SQLite, it's impossible for two tasks to have the same UUID. This was not the case with the old storage (TDB2), so `task diag` scans tasks for duplicate IDs. Let's remove that check.

**Comment by koleesch** [comment]
Hello @djmitche,

I can look for this bug. In which file should I look?

**Comment by koleesch** [comment]
When is the status changed?

https://github.com/GothenburgBitFactory/taskwarrior/pull/3545

**Comment by djmitche** [comment]
Oh, that only happens if you "link" the PR to the issue with a comment like "Fixes #3539".  I'll close it now :)

What kind of thing would you like to work on next?

**Comment by koleesch** [comment]
That's a good question. I want to learn rust. Is something that i can do in rust? 
Maybe i can take some "good first issues".

**Comment by djmitche** [comment]
Sure! Most of the Rust is in Taskchampion. The current good-first-issue there is https://github.com/GothenburgBitFactory/taskchampion/issues/410.

**Comment by felixschurk** [comment]
> TaskChampion stores tasks in a DB keyed by UUID, so barring a serious bug in SQLite, it's impossible for two tasks to have the same UUID. This was not the case with the old storage (TDB2), so `task diag` scans tasks for duplicate IDs. Let's remove that check.

Do we have a unit test that verifies that we cannot import two tasks having the same UUID's?

I need some deeper investigation, but when I am not mistaken I am currently able to create a unit test, where one wants to import two tasks having same UUIDs and this at least is not failing. 

This could then lead to some problems when users import a "corrupted" database or so.

```python
class TestImportDuplicatedIds(TestCase):
    def setUp(self):
        self.t = Task()

    def test_duplicated_import(self):
        """ if duplicated ids in import should fail """
        old_pending = "a1111111-a111-a111-a111-a11111111111"
        task_data = f"""[
    {{"uuid":"{old_pending}","status":"pending","description":"x", "entry":"20151018T144200"}},
    {{"uuid":"{old_pending}","status":"completed","description":"x"}}
]
"""

        code, out, err = self.t("import -", input=task_data)
```
I mean here are no assertions, however I would assume that `task import` should be failing.

**Comment by djmitche** [comment]
That'd be a good test to have. The `import` process has some support for de-duplication, allowing running it multiple times. I believe it skips already-existing tasks (at least, it said "skip" a lot when I ran import a second time).

**Comment by koleesch** [comment]
I understand that point. The code for importing tasks with uuid uses a HashMap. For me it is looking ok. So, is it possible from the user view to import tasks by the import with uuids?

**Comment by felixschurk** [comment]
Okay, a small test showed that if there would be same uuids in the import e.g.
```json
[
  {{"uuid":"a1111111-a111-a111-a111-a11111111111","status":"pending","description":"x", "entry":"20151018T144200"}},
  {{"uuid":"a1111111-a111-a111-a111-a11111111111","status":"completed","description":"x 2"}}
]
```
It would first import it the first time, and then apply the changes as modifications.
```sh
❯ task import test.json
Importing 'test.json'
 add  a1111111-a111-a111-a111-a11111111111 x
Modifying task a1111111 'x 2'.
 mod  a1111111-a111-a111-a111-a11111111111 x 2
Imported 2 tasks.
```
So later there is a task, which is already completed in the DB.
Similar for a second invocation of `task import`:
```sh
❯ task import test.json
Importing 'test.json'
Modifying task a1111111 'x'.
 mod  a1111111-a111-a111-a111-a11111111111 x
Modifying task a1111111 'x 2'.
 mod  a1111111-a111-a111-a111-a11111111111 x 2
Imported 2 tasks.
```

That's somehow good, in a sense that taskwarrior is not breaking or doing something weird, however when a person has a corrupt database (multiple duplicated uuids) which seams to be easily possible with task < 3, then they might "loose" some tasks while upgrading and importing to taskwarrior 3.0. 

A bit irritating is the `Imported 2 tasks` notification, as in the end it only imported one task, and then modified that one.

**Comment by djmitche** [comment]
That's a good point. Maybe the failure (or warning, at least) should be when the import itself contains the same uuid twice (as distinguished from a uuid in the input already existing in the taskdb). #3548.
