### ISSUE TITLE
Recurrence Generation Broken

### ISSUE THREAD

**Issue by felixschurk** [GothenburgBitFactory/taskwarrior#3551]
Can it be that we broke with #3542 the generation of recurring tasks?

I noticed that with the latest develop, a new recurring task is not created automatically.

Bellow unit test can be added to both `develop` as well as e.g. `d1a3573c5` (Commit before merge). 

```python
class TestCreationOfRecurringTaskIsDone(TestCase):
    def setUp(self):
        """Executed before each test in the class"""
        self.t = Task()

        # Create a task which should recur daily, due towards eod
        self.t("add foo due:eod recur:daily")
        self.t("add some_dummy_task") # only in to prevent empty database which also leads to an error

    def test_output(self):
        """Are Recurring Tasks Properly created?"""

        # get list for working tasks
        code, out, err = self.t()
        print("Output after creation")
        print(out)

        # after 2h, complete the task
        self.t.faketime("+2h")
        code, out, err = self.t("3 done")
        print("Output after done")
        print(out)

        # only for debug (check parent task output)
        code, out, err = self.t("1")
        print("Recurrence task")
        print(out)

        # code, out,err = self.t()
        # print("Output after done")
        self.t.faketime("+1d")
        code, out,err = self.t()
        print("Output after first on the next day")
        print(out)

        self.t.faketime("+1h")
        code, out,err = self.t()
        print("Output after next day plus some more time")
        print(out)

        code, out, err = self.t("1")
        print("Recurrence task")
        print(out)
```

Two things I noticed.
## "Empty" DB leads to stderr
When run under the current develop, the test is failing if there is not the `some_dummy_task` inside, as the recurring task is not created.
```sh
#        Command '['/usr/bin/faketime', '-f', '+1d', '/home/felix/data/taskwarrior/cmake-build-debug/src/task']' finished with unexpected exit code '1'.
#        
#        *** Start STDOUT ***
#        
#        *** End STDOUT ***
#        
#        *** Start STDERR ***
#        TASKRC override: /tmp/task_v_c7rl9h/test.rc
#        TASKDATA override: /tmp/task_v_c7rl9h
#        No matches.
#        
#        *** End STDERR ***
```

## No recurring task is created
The mask of the parent template is not updated, even after one full day (where the task should be pending again)
This behavior (as expected) is present in `d1a3573c5`.

I would expect that the above unit test also works under develop and create a new task for the new day.

**Comment by djmitche** [comment]
Oh, indeed, the mask is indexed by number of events since task creation. #3542 was definitely a mistake, and I'll revert it shortly.

**Comment by djmitche** [comment]
I can't quite figure out what's up with the creation of the dummy task -- but creating a recurring task means the DB isn't "empty" so I don't think that's the explanation.

Worth noting, `faketime` is not cumulative, so
```
self.t.faketime("+1d")
self.t.faketime("+1h")
```
is actually running time backward.
