### ISSUE TITLE
Case insensitive key words on commandline

### ISSUE THREAD

**Issue by gpaulsen** [GothenburgBitFactory/taskwarrior#3552]
#### To report a bug...

* What command(s) did you run?
`task add Project:myProj My New Task`

* What did you expect to happen?
I expected that taskwarrior would parse the "Project" the same as "project" since the word "Project" is capitalized in the template if I do a `task edit <TaskID>`.  This would have put the new task "My New Task"
in the myProj project.

* What actually happened?
Taskwarrior added the words "Project:myProj" to the begining of the description instead.

* Paste the output of the ```task diag``` command.
```
> $ task diag                                                                                                                                                 [±develop ✓]

task 3.0.2
   Platform: Darwin

Compiler
    Version: Apple LLVM 15.0.0 (clang-1500.3.9.4)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.29.2
    libuuid: libuuid + uuid_unparse_lower
 Build type: Release

Configuration
       File: /Users/gpaulsen/.taskrc (found), 1714 bytes, mode 100644
       Data: /Users/gpaulsen/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: vim
Hooks
     System: Enabled
   Location: /Users/gpaulsen/.task/hooks
             (-none-)

Tests
   Terminal: 253x62
       Dups: Scanned 67 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 67 tasks for broken references:
             No broken references found
```

**Comment by djmitche** [comment]
I think this is working as expected. Like most things on the command line, Taskwarrior is case-sensitive.

The headings in `task edit` are the "titles" for those fields, e.g. `Wait until`.

**Comment by djmitche** [comment]
Whoops linked that PR to the wrong issue.
