### ISSUE TITLE
Github.  The link to "How to request a feature" in the Issue Template is broken.

### ISSUE THREAD

**Issue by gpaulsen** [GothenburgBitFactory/taskwarrior#3553]
#### To report a bug...

* What command(s) did you run?
In [Github](https://github.com/GothenburgBitFactory/taskwarrior/issues/new) when adding a new issue, Github populates the issue with a new Issue Template.
At the bottom of that template, there is some text about how to request a feature.
The very last bullet is:
```
Please see our notes on [How to request a feature](https://taskwarrior.org/docs/features.html)
```

Unfortunately that URL returns a 404.  I assume that document has been moved or removed.

* What did you expect to happen?
I expected a document with additional information about how to request a feature in taskwarrior

* What actually happened?
404 error.

**Comment by djmitche** [comment]
Thanks! Fixed ..
