### ISSUE TITLE
Documentation doesn't match actual behaviour on `socm` and `som`

### ISSUE THREAD

**Issue by allgreed** [GothenburgBitFactory/taskwarrior#3559]
https://taskwarrior.org/docs/dates/#synonyms-hahahugoshortcode17s0hbhb

> som - Local date for the 1st day of the **next** month, with time 00:00:00.
> socm - Local date for the 1st day of the current month, with time 00:00:00.

```
~ >_ task --version
3.0.2
~ >_ date
Fri 19 Jul 15:29:34 CEST 2024
~ >_ task calc som
2024-07-01T00:00:00
~ >_ task calc socm
socm
~ >_ task calc socm+1d
socmP1D
```

Also happens on `2.6.x`

**Comment by smemsh** [comment]
this is likely a libshared issue, no? I have to say, 'som' meaning the next month is rather non-intuitive.  it would make more sense as 'som' = start of current month, 'sonm' = start of next month.

libshared/src/Datetime.cpp shows it as such.  I think the docs are wrong...
```
 $ task calc som
2024-07-01T00:00:00

 $ task calc sonm
2024-08-01T00:00:00
```
