### ISSUE TITLE
Modifying the end property silently fails

### ISSUE THREAD

**Issue by Necior** [GothenburgBitFactory/taskwarrior#3584]
```
$ task add smile
Created task 1.

$ task
ID Age  Description Urg
 1 1s   smile          0

$ task 1 mod end:-7d
Modifying task 1 'smile'.
Modified 1 task.

$ task
ID Age   Description Urg
 1 18s   smile          0
```

I expected that modifying the end property will succeed. Or, alternatively, that it will fail with some explanation and non-zero exit code.

I observed this behavior in both 2.6.2 and 3.0.2.

**Comment by djmitche** [comment]
Looking at the operations in the DB, this literally produces no change. My expectation was that this was a way to mark a task as "done" at a time different from right now.

**Comment by felixschurk** [comment]
Could it be that there is the problem with then the `end` property would be before the `add` time?

In general there exists the `task log` command, for tracking tasks https://taskwarrior.org/docs/commands/log/.
Probably has to do with the `Status` property and the allowed values. When one tries to manually edit the task following warning comes:
```sh
❯ task 71 edit
Launching 'nvim "task.be85a0d7.task"' now...
Editing complete.
Edits were detected.
Error: Cannot set a done date on a pending task.
```

## Solution
Setting a task as `done` and then modifying the `end` property such as `task 1 done end:-1d`.

Here the [En Passant](https://taskwarrior.org/docs/commands/done/) is used.

**Comment by djmitche** [comment]
Oh, nice find!

I wonder if `task 1 mod end:yesterday` should give the "Cannot set a done date on a pending task" error?

**Comment by felixschurk** [comment]
I think it would make sense, as internally its handled like that - just not communicated to the outside.

**Comment by gagankonana** [comment]
@djmitche I am wondering if trying to set an end date for a pending task should give a warning or throw an error.
