### ISSUE TITLE
task context delete [<name>]

### ISSUE THREAD

**Issue by westurner** [GothenburgBitFactory/taskwarrior#3600]
There's not yet a way to delete a context AFAICT without even looking at the source tbh; `task help | grep -i context`

### Feature
```sh
$ task context delete [<name>]
task context delete exampleA  # prompt
task context delete           # prompt for yes/no/all/q
```

### Workarounds
- Here's a shell script that runs `sed /expr/d` on ~/.taskrc:
  https://gist.github.com/westurner/dacddb317bb99cfd8b19a3407d675044 ;
```sh
set -x

task help | grep -i context

task context list
task _context
    
taskw_context_delete() {
   ## taskw_context_rm -- TASKRC=$HOME/.taskrc; (sed -i '/^context\..*\.read=/d' "${TASKRC}" && \
   #    sed -i '/^context\..*\.write=/d' "${TASKRC}")
   contextname=$1
   TASKRC="${TASKRC:-"$HOME/.taskrc"}"
   if [ -z "${contextname}" ]; then
       sed -i '/^context\..*\.read=/d' "${TASKRC}"
       sed -i '/^context\..*\.write=/d' "${TASKRC}"
   else
       sed -i "/^context\.${contextname}\.read=/d" "${TASKRC}"
       sed -i "/^context\.${contextname}\.write=/d" "${TASKRC}"
   fi

}

taskw_context_delete projectA
taskw_context_delete

task context list
task _context
```

**Comment by felixschurk** [comment]
Hei, there is the `task config` command which can be used to remove a context using following syntax:
```sh
task config context.<context-name>.read
task config context.<context-name>.write
```
This would ask you in a prompt if you really want to remove it.

But I would say that is not a really nice way of doing it, so in order to nicely remove it (and keeping consistency with the default way of removing configs with `task config` we could add a function which would run `task config context.<context-name> and would then remove the corresponding two lines in the `taskrc`.
Personally, I modify the `.taskrc` file usually manually with the editor, so never used that feature.

Would this go in the direction how you imagined it?

**Comment by westurner** [comment]
That's surprising that `task config {str}`  mutates the data? I would
expect that to display the value, and `delete` to delete.

I read the docs and still didn't realize this when writing a shell script
to demo taskwarrior that reset all state at the end of the test

I also just modify the taskrc

**Comment by djmitche** [comment]
That is surprising -- perhaps it warrants an update to the manpages or docs?

**Comment by tbabej** [comment]
This command already exists, in the exact form as requested by this feature request. For example, if I define a test context:
```
$ task context define test project:Test
Are you sure you want to add 'context.test.read' with a value of 'project:Test'? (yes/no) yes
Are you sure you want to add 'context.test.write' with a value of 'project:Test'? (yes/no) yes
Context 'test' defined (read, write). Use 'task context test' to activate.
$ tail -n 3 ~/.taskrc
context.work.write=project:PQ
context.test.read=project:Test
context.test.write=project:Test
```

I can subsequently delete it via `task context delete`:
```
$ task context delete test
Do you want to delete context 'test'? (yes/no) yes
Context 'test' deleted.
$ tail -n 2 ~/.taskrc
context.work.read=project:PQ
context.work.write=project:PQ
```

It is also documented, see `man taskrc`, in the "MISCELLANEOUS SUBCOMMANDS" section:
```
task context delete <name>
       Deletes the context with the name <name>. If the context being deleted is currently set as active, it will be unset.
       Example:
           task context delete work
```

the "CONTEXT" section explaining the working mechanisms of context also contains the following example:
```
[...]
To remove the definition, use the 'delete' subcommand.

     $ task context delete home
     Are you sure you want to remove 'context.home.read'? (yes/no) yes
     Are you sure you want to remove 'context.home.write'? (yes/no) yes
       Context 'home' deleted.
[...]
```

If there are ideas how this can he highlighted / documented better, I am open to suggestions :sweat_smile:

**Comment by tbabej** [comment]
Closing as implemented.
