### ISSUE TITLE
`task info` shows `tag_..` properties

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3607]
Taskwarrior stores tags as `tag_<tagname>` properties with a nonempty value `x`. The `task info` command should filter those out and just show the tags, but it does not.

```
✺ sofia ~/p/taskwarrior ⸨issue3605⸩
⸩ task add task with a tag +thetagvalue
TASKRC override: /home/dustin/p/taskwarrior/.taskrc
Created task 6.
✺ sofia ~/p/taskwarrior ⸨issue3605⸩
⸩ task 6
TASKRC override: /home/dustin/p/taskwarrior/.taskrc

Name             Value                                 
ID               6                                     
Description      task with a tag                       
Status           Pending                               
Entered          2024-08-26 21:49:35 (2s)
Last modified    2024-08-26 21:49:35 (2s)              
Tags             thetagvalue
Virtual tags     LATEST PENDING READY TAGGED UNBLOCKED 
UUID             f06b2b7f-a80c-4b79-bf4c-58a0d43d80dc
Urgency          0.8                                   
[tag_thetagvalue x]

    tags    0.8 *    1 =    0.8
                         ------
                            0.8
```

The `[tag_thetagvalue x]` line is the one that shouldn't be there. Just omtting properties beginning with `tag_` should be sufficient to fix this issue.

**Comment by gagankonana** [comment]
@djmitche I raised a PR for this issue. Had a quick question, do we also want to omit properties beginning with "tags_"?

This is going to be my first-ever contribution to OSS!

**Comment by djmitche** [comment]
Oops, I just saw this question. My review on the PR answers it :)

**Comment by djmitche** [comment]
> This is going to be my first-ever contribution to OSS!

😍
