### ISSUE TITLE
Update libshared to get new weekstart

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3623]
From https://github.com/GothenburgBitFactory/libshared/pull/81

> The new ISO8601 behavior for Datetime::weekstart == 1 will be a breaking change for users relying on existing week date parsing. This is unavoidable for weekstart == 1. However if the user wants weekstart == 0, the old behavior is still possible if Taskwarrior/Timewarrior were modified to set Datetime::weekstart before libshared calls (which they currently do not). Taskwarrior could propagate its rc.weekstart value (used only for task calendar so far) and propagate this value to libshared, for example.

**Comment by smemsh** [comment]
@djmitche Thanks for picking this up, I was planning to make an issue to bump libshared in Taskwarrior, now that the weekstart change was merged.

Note that the libshared change only affects week number parsing, whereas sonw/sopw/etc should still use Monday regardless of `Datetime::weekstart` (as they did before).  I did not look into tackling that but it would be necessary to make those respect `Datetime::weekstart` as well in order for support to be truly complete.

It looks like all these functions would need changes for that:

- initializeSopw
- initializeSow
- initializeSonw
- initializeEopw
- initializeEow
- initializeEonw
- initializeSopww
- initializeSonww
- initializeSoww
- initializeEopww
- initializeEonww
- initializeEoww

When were you targeting 3.2 ? I might be able to look into doing this, depending on your timeline.

**Comment by djmitche** [comment]
Ah, that sounds like more work than I anticipated! If you can work on it, that would be great. I think it's fine for this to be "done when it's done" so don't rush to get it into 3.2.0.

**Comment by smemsh** [comment]
It's not strictly necessary to get those additional changes in.  Merely updating the libshared peg and propagating `rc.weekstart` to the library would still be a better situation than today, it just would leave the sonw/sopw/etc aliases hard-configured to Monday weeks, but they already are (so at least parsing weeks would be made better, currently they are hard-configured to Sunday weeks).

Let me look at how hard I think it would be to fix the aliases too and I'll get back to you on whether an intermediate release doing the more limited change is warranted in the meantime.  Give me a little bit, thanks.

**Comment by djmitche** [comment]
Sounds good, take your time :)

**Comment by elig0n** [comment]
Before `libshared` there was this code which took `weekstart` into consideration:
https://github.com/GothenburgBitFactory/taskwarrior/commit/903b5b34d41cecf1328c3270868f22a22e5e8827

Maybe it can assist any of you

**Comment by djmitche** [comment]
It looks like https://github.com/GothenburgBitFactory/libshared/pull/83 will need a libshared update as well. Do you want to do those updates separately or at the same time?

**Comment by smemsh** [comment]
Let's do the lesser for now, I'm changing continents at the moment.  I'll look at the rest later.

So to bump libshared and have least-surprise, I suggest we pass in the user's `rc.weekstart` as the value to initialize libshared's `Datetime::weekstart`.  Previous code always behaved as the new code does when weekstart=0, but now it would use the [previously not consulted] initialization at the top of Datetime.cpp (which is weekstart=1), so we should instead prime it from user config.

I think I have that working, but when I ran the TW tests, it revealed a bug in the new libshared code.  Could you merge GothenburgBitFactory/libshared#84 first (and also the GothenburgBitFactory/libshared#83 you mentioned, if you're planning on it)? And then I have a patch that passes down `rc.weekstart` to `Datetime::weekstart` as described, it seems to work.  I'll include the final libshared peg update in my PR.

**Comment by djmitche** [comment]
I've merged both of those PRs.

**Comment by smemsh** [comment]
Thanks @djmitche.  Take a look at #3654, which should bring in the libshared master branch tip, and close this one.  Then #3651 can proceed.
