### ISSUE TITLE
3.0.2 Build Process Returns Error: can't find -ltaskchampion-lib

### ISSUE THREAD

**Issue by acvgo** [GothenburgBitFactory/taskwarrior#3630]
* What command(s) did you run?

cmake --build build -v

* What did you expect to happen?

Build complete

* What actually happened?

system reports below error

> [ 97%] Linking CXX executable task
> cd /home/REDACT/task-3.0.2/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/task_executable.dir/link.txt --verbose=1
> /usr/bin/c++ -Wall -Wextra -Wsign-compare -Wreturn-type -std=c++17  -O3 -DNDEBUG CMakeFiles/task_executable.dir/main.cpp.o -o task  libtask.a tc/libtc.a commands/libcommands.a tc/libtc.a columns/libcolumns.a liblibshared.a libtask.a liblibshared.a -ldl -lpthread /usr/lib/x86_64-linux-gnu/libuuid.so -ltaskchampion-lib
> /usr/bin/ld: cannot find -ltaskchampion-lib: No such file or directory
> collect2: error: ld returned 1 exit status
> gmake[2]: *** [src/CMakeFiles/task_executable.dir/build.make:106: src/task] Error 1
> gmake[2]: Leaving directory '/home/REDACT/task-3.0.2/build'
> gmake[1]: *** [CMakeFiles/Makefile2:357: src/CMakeFiles/task_executable.dir/all] Error 2
> gmake[1]: Leaving directory '/home/REDACT/task-3.0.2/build'
> gmake: *** [Makefile:156: all] Error 2

* Paste the output of the ```task diag``` command.

task 3.0.2
   Platform: Linux

Compiler
    Version: 11.4.0
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.29.2
    libuuid: libuuid + uuid_unparse_lower
 Build type: Release

Configuration
       File: /home/REDACT/.taskrc (found), 1380 bytes, mode 100644
       Data: /home/REDACT/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
Hooks
     System: Enabled
   Location: /home/REDACT/.task/hooks
             (-none-)

Tests
   Terminal: 443x115
       Dups: Scanned 3 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 3 tasks for broken references:
             No broken references found

----Other Notes

rustc version 1.81.0  (eeb90cda1 2024-09-04)
cmake version 3.25.1
Python 3.11.2
gcc (Debian 12.2.0-14) 12.2.0
GNU Make 4.3

Possibly related to #3485

**Comment by felixschurk** [comment]
Hei, 
is there any specific reason why you would like to build the `3.0.2` version?
I think https://github.com/GothenburgBitFactory/taskwarrior/issues/3605 describes the same issue, and it is resolved with the `3.1.0` release of taskwarrior.

**Comment by acvgo** [comment]
Was latest release version on the website - I didn't even look at releases on github to see that it wasn't in sync.

**Comment by acvgo** [comment]
https://taskwarrior.org/
![image](https://github.com/user-attachments/assets/fb057c57-bb04-4aba-a87d-6faf297247bc)

https://taskwarrior.org/download/
![image](https://github.com/user-attachments/assets/e804483d-1519-4840-9a16-bf52f4def4ab)

**Comment by felixschurk** [comment]
Ah okay, yes this should get updated accordingly. 

I will close this one and create an Issue for updating the website.

**Comment by felixschurk** [comment]
https://github.com/GothenburgBitFactory/tw.org/issues/963

Should track the update.
