### ISSUE TITLE
Installing tw 3.0.2 from tarball is aborting

### ISSUE THREAD

**Issue by BernhardMB** [GothenburgBitFactory/taskwarrior#3656]
Hi, 
I am trying to install Taskwarrior under Ubuntu22.
Using apt install, I am installing Version 2.6
Maybe there is some repository I can use to get 3?

After I tried to install from the tarball, but I get stuck with cmake:
<img width="640" alt="Bildschirmfoto 2024-10-18 um 17 55 28" src="https://github.com/user-attachments/assets/26a40ae1-298c-4a86-9918-23874c81a512">
Looks like the taskchampon-lib didnt install.
somebody a hint ?
 Thanks,

Bernhard

**Comment by djmitche** [comment]
Also answered in Discord, but you'll want to use version 3.1.0. The build error is #3487.
