### ISSUE TITLE
Task waiting with simple time value also added

### ISSUE THREAD

**Issue by ksandvik** [GothenburgBitFactory/taskwarrior#3659]
#### To request a feature...

* Clearly describe the feature.

I would like to annotate a task wait: so in addition to the date it also has a time when it becomes active.

* Clearly state the use case. We are only interested in use cases, do not waste time with implementation details or suggested syntax.

It is hard to figure out all the ISO timestamp formats for most end users, and also ther could be issues with parsing such date format, such as with the fish shell.

Here are some concepts how it would work

task add foo wait:tomorrow 4pm
task add foo wait:friday 18:00

* Please see our notes on [How to request a feature](https://taskwarrior.org/docs/features/)

**Comment by ksandvik** [comment]
Just for fun, tested:
$ task add foo wait:tomorrow 5pm

$ task waiting
 9 11s   2024-10-27 00:00      6h   foo 5pm

**Comment by tbabej** [comment]
This is already possible to a large extent through use of time deltas:
```
[warrior@tw-v3.1.0 ~]$ task add foo wait:tomorrow+17h
Created task 1.
[warrior@tw-v3.1.0 ~]$ task waiting

ID Age  Wait       Remaining Description
 1 2s   2024-12-01      1d   foo

1 task
[warrior@tw-v3.1.0 ~]$ task _get 1.wait
2024-12-01T17:00:00
```
