### ISSUE TITLE
Concurrent reads cause "The database file is locked" error.

### ISSUE THREAD

**Issue by TimShilov** [GothenburgBitFactory/taskwarrior#3676]
I'm trying to add some counters to Tmux status line. For that I run a couple of `task <filter> count` commands.
Since Tmux runs them at the same time - they seem to conflict with each other.

I have seen #3325 but it talks about updates but I just have reads. Plus it is already marked as fixed, so I feel like those are different issues.

* What command(s) did you run?
I run two commands separately but for the sake of reproduceability here are the single command that reproduces the issue for me 100% of the time.
```sh
task jiraissuetype:HotFix +READY count & task jiraid +READY count
```
* What did you expect to happen?
I expect to get 2 numbers in the output.

* What actually happened?
One command succeeds and another one fails with an error.
```sh 
[1] 25597
Clear working set query: database is locked: Error code 5: The database file is locked
0
[1]  + done       task jiraissuetype:HotFix +READY count
```
* Paste the output of the ```task diag``` command.

```
task 3.1.0
   Platform: Darwin

Compiler
    Version: Clang 16.0.6
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
      CMake: 3.29.6
    libuuid: libuuid + uuid_unparse_lower
 Build type: Release

Configuration
       File: /Users/tim.shilov/.config/task/taskrc (found), 78 bytes, mode 100644
       Data: /Users/tim.shilov/.local/share/task (found), dir, mode 40755
         GC: Enabled
    $EDITOR: nvim
Hooks
     System: Enabled
   Location: /Users/tim.shilov/.local/share/task/hooks
             (-none-)

Tests
   Terminal: 120x30
 Broken ref: Scanned 146 tasks for broken references:
             No broken references found
```

**Comment by djmitche** [comment]
It turns out, that wasn't fixed in TW 3.1.0. It was fixed in TC 0.7.0, but TW 3.1.0 uses TC 0.6.0:
```
⸩ git show v3.1.0:Cargo.toml 
...
taskchampion = "0.6"
```
We have since updated to 0.9.0:
```
⸩ grep ^taskchampion src/taskchampion-cpp/Cargo.toml 
taskchampion = "0.9.0"
```
so this fix should be included. Are you able to build the current `main` from source and test that?

Sorry about the mix-up. GitHub's automatic-issue-closing worked too well!

**Comment by TimShilov** [comment]
@djmitche Sorry, I have tried building from source following [these instructions](https://github.com/GothenburgBitFactory/taskwarrior/blob/develop/doc/devel/contrib/development.md) and couldn't get it to build successfully. 😅

**Comment by djmitche** [comment]
Bummer!  Well, 3.2.0 will be out shortly and perhaps you can verify there?

**Comment by TimShilov** [comment]
Sure, will do!
Is there any ETA of when to expect 3.2.0?

Not trying to rush things by any stretch, just trying to understand if it would make sense for me to start looking for workarounds in the meantime as that error really breaks things for me.
I have also just realized that Bugwarrior (which I have running on cron) also fails quite often with the same error (probably tries to read/write in parallel with Tmux reads or just me working with taskwarrior directly) which results in big delays before I notice new tasks coming in. 😬

**Comment by djmitche** [comment]
I assume you're using `rc.gc=0`? That might help!

**Comment by djmitche** [comment]
3.2.0 should be out soon :)

**Comment by TimShilov** [comment]
> I assume you're using rc.gc=0? That might help!

Oooh, I actually wasn't using it. I was thinking that it only affects writes/updates. Why would TW perform garbage collection on reads? Not only that causes unnecessary conflicts but also slows down the reads. 🤔

Anyway, I have added it to all my read commands and now things work way better! Thanks for the note @djmitche! 🚀
I'm pretty sure there will still be some conflicts with Bugwarrior and Taskwarrior-TUI but that's not the end of the world and definitely can wait for the release!

**Comment by djmitche** [comment]
TW performs garbage collection before rendering any report, when rc.gc=1.

I'm glad that at least reduced the severity. Hopefully we'll have 3.2.0 out in a few days!

**Comment by djmitche** [comment]
https://github.com/GothenburgBitFactory/taskwarrior/releases/tag/v3.2.0 today!
