### ISSUE TITLE
Build of taskwarrior 3.1.0 fails on 32bit machines, presumably due to a `isize` mismatch.

### ISSUE THREAD

**Issue by dataCobra** [GothenburgBitFactory/taskwarrior#3678]
While trying to build the current release of taskwarrior on a 32bit machine I've got an error while rust/cargo tried to compile `taskchampion-lib`.

While reading the error and checking on the source file I assume there is a mismatch in found and expected size of the `isize` type.

operating system: Void Linux (glibc) 6.11.6
rust/cargo version: 1.82.0 (f6e511eec 2024-10-15)
cmake version: 3.30.1

Dependencies:
libuuid version: 2.40.2

cmake flags: `-DCMAKE_BUILD_TYPE=Release`

```
Compiling taskchampion-lib v0.1.0 (/builddir/task-3.1.0/src/tc/lib)
error[E0308]: mismatched types
  --> src/tc/lib/src/atomic.rs:25:39
   |
25 |             return Some(utc_timestamp(self));
   |                         ------------- ^^^^ expected `i64`, found `i32`
   |                         |
   |                         arguments to this function are incorrect
   |
note: function defined here
  --> /host/cargo/registry/src/index.crates.io-1cd66030c949c28d/taskchampion-0.6.0/src/task/time.rs:5:8
   |
5  | pub fn utc_timestamp(secs: i64) -> Timestamp {
   |        ^^^^^^^^^^^^^
help: you can convert an `i32` to an `i64`
   |
25 |             return Some(utc_timestamp(self.into()));
   |                                           +++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `taskchampion-lib` (lib) due to 1 previous error
```

**Comment by djmitche** [comment]
That code has been removed in 3.2.0, which should be out soon. If you can try building from the latest on `main` to verify, that would be helpful!

**Comment by dataCobra** [comment]
I've tested building on 32bit while using the `main` branch. Building now works as expected. :+1: 

Thank you. :slightly_smiling_face:
