### ISSUE TITLE
Bug Report: Weird Task Names When Changing Verbosity

### ISSUE THREAD

**Issue by galisma** [GothenburgBitFactory/taskwarrior#3700]
## Description

I have my configuration files in `.config/task`. To prevent the `TASKRC override` message, I added the following line to my `taskrc`:

```
verbose=blank,header,footnote,label,new-id,new-uuid,affected,edit,special,project,sync,filter,context
```

However, after making this change, adding a task shows a strange behavior with the task number.

### Steps to Reproduce

1. Add the configuration files to `.config/task`.
2. Add the line above to the `taskrc` file.
3. Observe the difference in task creation behavior before and after changing verbosity.

### Observed Behavior

**Before changing verbosity:**
```bash
$ task add hello world
TASKRC override: /home/ismael/.config/task/taskrc
TASKDATA override: /home/ismael/.config/task/
Created task 4.
```

**After changing verbosity:**
```bash
$ task add hello world
Created task ef9489de-55cb-40ac-8d3c-f3709a707264.
```

## Expected Behavior

Task creation should maintain the standard task numbering.

## Diagnostic Output

```plaintext
task 3.2.0
   Platform: Linux

Compiler
    Version: 14.2.1 20240910
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++17

Build Features
     Commit: 7a092bea0
      CMake: 3.31.0
    libuuid: libuuid + uuid_unparse_lower
 Build type: 

Configuration
       File: /home/ismael/.config/task/taskrc (found), 882 bytes, mode 100644
       Data: /home/ismael/.config/task/ (found), dir, mode 40755
     TASKRC: /home/ismael/.config/task/taskrc
   TASKDATA: /home/ismael/.config/task/
         GC: Enabled

Hooks
     System: Enabled
   Location: /home/ismael/.config/task/hooks
             (-none-)

Tests
   Terminal: 205x41
 Broken ref: Scanned 3 tasks for broken references:
             No broken references found
```

**Comment by felixschurk** [comment]
Hei,
Without being able to currently test it out I assume it comes from the setting of `new-uuid` as currently your output just gives the unique id and now the shortened id.

Maybe check it out if it still persists if you remove it or maybe reorder it such that `new-id` comes after wards.

**Comment by smemsh** [comment]
yeah, the manual says `new-uuid` overrides `new-id` so probably choose one or the other, not both

**Comment by galisma** [comment]
thanks, deleting new-uuid solved the problem :)
