### ISSUE TITLE
[TW-337] More readable "project changed" output

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#372]
_steve rader on 2010-12-30T11:01:15Z says:_ 

 Another line-wrap nit picked...
<pre>

$ task add proj:Personal_IT wait:01/15/2011 Check for Seamonkey 2.1final
Created task 102.
The project 'Personal_IT' has changed.
Project 'Personal_IT' is 0% complete.
(21 of 21 tasks remaining)

</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-12-30T11:01:15Z
Modified: 2014-02-09T00:50:20Z
```

**Comment by taskwarrior** [comment]
_steve rader on 2010-12-30T11:02:43Z says:_ 

 Somehow the patch didn't get attached?

**Comment by taskwarrior** [comment]
_steve rader on 2010-12-30T11:04:07Z says:_ 

 steve rader wrote:
> Somehow the patch didn't get attached?

No, fwiw, i saw a bug in Redmine.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-02-19T20:46:37Z says:_ 

 This is at odds with assorted other feedback.  Deferring until this is resolved.

I agree about the need for clear language, instead of a franken-sentence that is very hard to localize.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-07-04T22:07:51Z says:_ 

 Output volume has been reduced, and all elements are now switchable.  This is not needed.

**Comment by pbeckingham** [comment]
[TW-337_PATCH-proj-change.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755578/TW-337_PATCH-proj-change.txt)
