### ISSUE TITLE
Support automatically importing 2.x tasks

### ISSUE THREAD

**Issue by djmitche** [GothenburgBitFactory/taskwarrior#3720]
When a user upgrades from 2.x to 3.x, they are presented with:
```
$ task
Found existing '*.data' files in /home/$USER/.task
  Taskwarrior's storage format changed in 3.0, requiring a manual migration.
  See https://github.com/GothenburgBitFactory/taskwarrior/releases.
No matches.
```

A better link would be https://taskwarrior.org/docs/upgrade-3/, but that's not the point. These instructions require re-installing 2.x, running `task export`, then running `task import` with 3.x. That's pretty annoying!

We could potentially bring back the TF2 support (TF2 is the text-based task format) just for the purpose of importing. Then users could run something like `task import-task2` to import those tasks automatically.

**Comment by smemsh** [comment]
the real trick would be replaying the undo journal from the beginning, so history could be retained too
