### ISSUE TITLE
[TW-342] build failure with musl libc due to undefined GLOB_BRACE and GLOB_TILDE

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#377]
_Natanael Copa on 2014-01-27T11:02:33Z says:_ 

 <pre>
[  1%] Building CXX object src/CMakeFiles/task.dir/Path.cpp.o
/home/ncopa/src/task.git/src/Path.cpp: In static member function 'static std::vector<std::basic_string<char> > Path::glob(const string&)':
/home/ncopa/src/task.git/src/Path.cpp:273:45: error: 'GLOB_BRACE' was not declared in this scope
   if (!::glob (pattern.c_str (), GLOB_ERR | GLOB_BRACE | GLOB_TILDE, NULL, &g))
                                             ^
/home/ncopa/src/task.git/src/Path.cpp:273:58: error: 'GLOB_TILDE' was not declared in this scope
   if (!::glob (pattern.c_str (), GLOB_ERR | GLOB_BRACE | GLOB_TILDE, NULL, &g))
                                                          ^
src/CMakeFiles/task.dir/build.make:402: recipe for target 'src/CMakeFiles/task.dir/Path.cpp.o' failed
make[2]: *** [src/CMakeFiles/task.dir/Path.cpp.o] Error 1
CMakeFiles/Makefile2:80: recipe for target 'src/CMakeFiles/task.dir/all' failed
make[1]: *** [src/CMakeFiles/task.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-01-27T11:02:33Z
Modified: 2014-02-09T00:53:17Z
```

**Comment by taskwarrior** [comment]
_Natanael Copa on 2014-01-27T11:06:22Z says:_ 

 The attached patch should fix it.

**Comment by taskwarrior** [comment]
_Natanael Copa on 2014-01-27T13:25:02Z says:_ 

 after running 'make test': 
1.  16 passed, 0 failed, 0 skipped. 100% passed.
[100%] Built target test

**Comment by taskwarrior** [comment]
_Natanael Copa on 2014-01-27T13:30:06Z says:_ 

 More details:
<pre>
ncdev-edge-musl-x86:~/src/task.git$ make test | grep passed.
1.  8 passed, 0 failed, 0 skipped. 100% passed.
1.  1036 passed, 0 failed, 0 skipped. 100% passed.
1.  11 passed, 0 failed, 0 skipped. 100% passed.
1.  209 passed, 0 failed, 0 skipped. 100% passed.
1.  49 passed, 0 failed, 0 skipped. 100% passed.
1.  6 passed, 0 failed, 0 skipped. 100% passed.
1.  646 passed, 0 failed, 0 skipped. 100% passed.
1.  27 passed, 0 failed, 0 skipped. 100% passed.
1.  11 passed, 0 failed, 0 skipped. 100% passed.
1.  38 passed, 0 failed, 0 skipped. 100% passed.
1.  24 passed, 0 failed, 0 skipped. 100% passed.
1.  12 passed, 0 failed, 0 skipped. 100% passed.
1.  402 passed, 0 failed, 0 skipped. 100% passed.
1.  32 passed, 0 failed, 0 skipped. 100% passed.
1.  23 passed, 0 failed, 0 skipped. 100% passed.
1.  30 passed, 0 failed, 0 skipped. 100% passed.
1.  18 passed, 0 failed, 0 skipped. 100% passed.
1.  9 passed, 0 failed, 0 skipped. 100% passed.
1.  16 passed, 0 failed, 0 skipped. 100% passed.
1.  12 passed, 0 failed, 0 skipped. 100% passed.
1.  264 passed, 0 failed, 0 skipped. 100% passed.
1.  54 passed, 0 failed, 0 skipped. 100% passed.
1.  17 passed, 0 failed, 0 skipped. 100% passed.
1.  40 passed, 0 failed, 0 skipped. 100% passed.
1.  16 passed, 0 failed, 0 skipped. 100% passed.
1.  16 passed, 0 failed, 0 skipped. 100% passed.
ncdev-edge-musl-x86:~/src/task.git$ 
</pre>

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-31T13:48:47Z says:_ 

 Thanks for the patch.

**Comment by pbeckingham** [comment]
[TW-342_0001-Fix-build-with-musl-libc.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755579/TW-342_0001-Fix-build-with-musl-libc.patch.txt)
