### ISSUE TITLE
[TW-344] `tasksh` segmentation fault

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#379]
_Hector Arciga on 2014-01-20T15:32:58Z says:_ 

 task terminates with a segmentation fault when invoked as `tasksh` and input '\<CR>'

**Comment by taskwarrior** [comment]
_Hector Arciga on 2014-01-20T15:32:58Z says:_ 

 Attachment Screen_Shot_2014-01-20_at_9.28.31_AM.png has been added with description: screenshot

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-20T16:00:18Z says:_ 

 Thank you for reporting this!

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-20T16:13:41Z says:_ 

 The '\' was not in the list of characters that need to be escaped.

**Comment by pbeckingham** [comment]
![tw-344_screen_shot_2014-01-20_at_9 28 31_am](https://user-images.githubusercontent.com/7963/36637223-6440ecac-19a5-11e8-8e56-ef7272187b8c.png)
