### ISSUE TITLE
[EX-42] Implement Pareto Principle 20/80

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#38]
_Benjamin Weber on 2012-12-19T14:48:55Z says:_ 

 This option forces you to decide what goes for your 20% and more importantly what not.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-12-19T14:48:55Z
Modified: 2017-01-17T02:53:00Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-12-22T15:15:05Z says:_ 

 Can you elaborate on this please?

I don't understand how this could apply to taskwarrior, so it's on the fast track to rejection unless it can be mapped into some user benefit and feature augmentation.

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2013-03-06T18:00:13Z says:_ 

 ## What?
"The 80/20 Principle asserts that when two sets of data, relating to causes and results, can be examined and analysed, the most likely result is that there will be a pattern of
The imbalance may be 65/35, 70/30, 75/25, 80/20, 95/5, or 99.9/0.1, or any set of numbers in between. […]
For example, the 80/20 Principle asserts that 20 per cent of products, or customers or employees, are really responsible for about 80 per cent of profits.
The implication is that 80 per cent of products, or customers or employees, are only contributing 20 per cent of profits. That there is great waste.
[…]
80/20 wisdom is to choose a basket carefully, load all your eggs into it, and then watch it like a hawk.
"
_Richard Koch: The 80/20 Principle: The Secret of Achieving More with Less_
## Why?

Task management should assist me finding the right answer of which energy to allocate to which tasks. Is my goal to complete everything? Or is my goal to concentrate on the 20% of tasks responsible for 80% of results?
For me a task management should enable me to (1) identify the right 20% and (2) completing them by getting 80% of results. 
## How?
"80/20 Analysis examines the relationship between two sets of comparable data. One set of data is always a universe of people or objects, usually a large number of 100 or more, that can be turned into a percentage. The other set of data relates to some interesting characteristic of the people or objects, that can be measured and also turned into a percentage. […]
Traditionally, the 80/20 Principle has required 80/20 Analysis, a quantitative method to establish the precise relationship between causes/input/effort and results/outputs/rewards. This method uses thepossible existence of the 80/20 relationship as a hypothesis and then gathers the facts so that the true relationship is revealed. This is an empirical procedure which may lead to any result ranging from 50/50 to 99.9/0.1. If the result does demonstrate a marked imbalance between inputs and outputs (say a 65/35 relationship or an even more unbalanced one), then normally action is taken as a result 
"
_Ibid._

_Reference exerpt attached._

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2013-03-06T18:00:13Z says:_ 

 Attachment tw2.pdf has been added with description: Pareto Principle

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-07T03:07:33Z says:_ 

 The tw2.pdf attachment discusses the 80/20 Principle, but only in the sense that it is a post-facto observation, and not a tool for identifying *which* 20%.  It contains no definition and no mathematics.

Is there a practical use?  How would you envision this being used?

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2013-03-07T05:50:16Z says:_ 

 Just some thoughts:

A neat way to implement a pareto-like behaviour in taskwarrior might be to take the completed percentage of a project into account for calculating the urgency of the project's tasks. This could be a simple urgency bonus for projects with less than 20% completion or even a gradually increasing penalty.

**Comment by taskwarrior** [comment]
_Dirk Deimeke on 2013-03-07T06:53:11Z says:_ 

 Managing percentages with tasks is in general very difficult.

For managing urgency Taskwarrior needs to know contents of your work and how you rate it. Which part of the work is 80%? Or do you think Taswarrior should make tasks more urgend which are less than 80% completeted? Pareto says 80% of the work are done in 20% of the time and you need 80% of the time to complete the remaining 20%.

To illustrate why percentages might not be the right way to measure completeness. As example, you have to migrate 100 servers to a new hardware platform. The usual approach is to say one completet server means one percent of the work done. Your customer agrees for *most* of the servers and you get 90% of the work done in two weeks, but you get no approval for the remaining ten servers for half a year. Even though you did 90% of the work, you can not estimate the time you need for the remaining ten. Ok, that's a sort of Pareto. Now turn the example upside down. The ten servers are (for any reason) the first ones that need to be migrated ...

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-17T02:53:00Z says:_ 

 Don't know what it is.

**Comment by pbeckingham** [comment]
[EX-42_tw2.pdf.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755300/EX-42_tw2.pdf.txt)
