### ISSUE TITLE
[TW-346] truncated sentence in task-sync(5) manpage

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#381]
_Jakub Wilk on 2014-01-19T21:36:18Z says:_ 

 The single quote is a controlling character when it appears at the beginning of a line. As a consequence, one of the task-sync(5) sentences was rendered like this:

<pre>
You can even do this using shell scripts so  that  every  task
command is preceded by a ’pull’ and followed by a
</pre>

The attached patches fixes this bug.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-01-19T21:36:18Z
Modified: 2014-02-09T00:53:17Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-20T14:52:58Z says:_ 

 Thank you.

**Comment by pbeckingham** [comment]
[TW-346_doc-man-task-sync.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755581/TW-346_doc-man-task-sync.diff.txt)
