### ISSUE TITLE
[TW-348] task show to display default values in a column

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#383]
_Renato Alves on 2014-01-22T18:48:48Z says:_ 

 Currently task show can be used to know the values for each config.
Additionally it uses color highlight to indicate that a value is different from the default value.
However one has to resort to the man page in order to figure out what is the default value.

I hereby propose that a 3rd column is added containing the default values.

An example output could be:

<pre>
task show alias

  Config Variable Value            Default
  alias._query    export           =
* alias.burndown  burndown.daily   burndown.weekly
* alias.ghistory  ghistory.weekly  ghistory.monthly
* alias.history   history.weekly   history.monthly
  alias.rm        delete           =
  alias.shell     exec tasksh      =

NOTE: I use * to represent colored lines/changed settings as I can't do colors here
</pre>

Optionally, if this makes the output too verbose with settings such as *rule.precedence.color* or if people rely on parsing the output of task show for other purposes, the behavior could be made optional:

<pre>
task show show

  Config Variable Value Default
* show.default    yes   no
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-01-22T18:48:48Z
Modified: 2014-02-09T00:53:17Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-25T22:36:52Z says:_ 

 While this looks great in your example, the reality of it is an unreadably wide table of data (see attached file).  Not sure what to do.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-26T17:49:48Z says:_ 

 I have another solution, which doesn't occupy horizontal space.  When a value differs from the default, and when that default has a non-trivial value (not blank) then an additional line is added to the output, indented and titled "Default value".  I think this implements the spirit of this feature without the terrible formatting consequences.

See the two attached images, showing both cases.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-26T17:49:48Z says:_ 

 Attachment with_default.png has been added with description: Configuration showing default value

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-26T17:49:48Z says:_ 

 Attachment without_default.png has been added with description: Configuration with no default value

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-26T17:54:18Z says:_ 

 Nice feature.  Thank you.  You are in the AUTHORS file.

**Comment by pbeckingham** [comment]
<img width="1057" alt="tw-348_show-wide" src="https://user-images.githubusercontent.com/7963/36637230-9c256666-19a5-11e8-8b6d-923842ad6a3d.png">
<img width="288" alt="tw-348_with_default" src="https://user-images.githubusercontent.com/7963/36637231-9c384164-19a5-11e8-861a-aa8376353cac.png">
<img width="258" alt="tw-348_without_default" src="https://user-images.githubusercontent.com/7963/36637232-9c4b9f70-19a5-11e8-8098-6e1b3cfa2987.png">
