### ISSUE TITLE
[TW-353] bug.annual.t failure

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#388]
_Jakub Wilk on 2014-01-08T11:23:05Z says:_ 

 I've seen this failure on a Debian autobuilder:
<pre>
1.  /build/task-3F3BcL/task-2.3.0~beta2/test/bug.annual.t
1..13
ok 1 - Created annual.rc
not ok 2 - synthetic 2 no creep
1.  Failed test 'synthetic 2 no creep'
1.  at /build/task-3F3BcL/task-2.3.0~beta2/test/bug.annual.t line 65.
1.  'Using alternate .taskrc file /build/task-3F3BcL/task-2.3.0~beta2/obj/test/annual.rc
1. 
1.  ID Due Age Description
1.  -- ---------- --- -----------
1.  4 1/1/2002 1s foo
1.  5 1/1/2003 1s foo
1.  6 1/1/2004 1s foo
1.  7 1/1/2005 1s foo
1.  8 1/1/2006 1s foo
1.  9 1/1/2007 1s foo
1.  10 1/1/2008 1s foo
1.  11 1/1/2009 1s foo
1.  12 1/1/2010 1s foo
1.  2 1/1/2000 1s foo
1.  3 1/1/2001 1s foo
1. 
1.  11 tasks
1.  '
1.  doesn't match '(?^:2s+1/1/2000s+(?:d+ssecs?s+)?foo)'
</pre>

The attached patch should hopefully fix the problem.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-01-08T11:23:05Z
Modified: 2014-02-09T01:36:03Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-08T11:54:57Z says:_ 

 Thank you.

**Comment by pbeckingham** [comment]
[TW-353_tests-fix-bug.annual.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755584/TW-353_tests-fix-bug.annual.diff.txt)
