### ISSUE TITLE
[EX-43] gtd, the daemon

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#39]
_David Patrick on 2012-09-02T16:25:35Z says:_ 

 NOTE: this is probably one of the most far-fetched, long-term loopy/ evil ideas I've posted yet. For your amusement :)

The name "gtd" _in this case_ is a recursive acronym that stands for GetThingsDone TM Daemon, and it's ultimate goal is to have an always-on process that manages taskd and cron and notifications and monitors system processes and resources.
As though you were combining David Allen(tm?)s brain with Steven Coveys, and that of a ZenHabits monk, it taking over your computer and driving you inexorably towards the very next most important step. 

Like a super-daemon, driven by a productivity algorithm (coined) that could compare a personal task-load (coined) with a computers resources, and when neither the user nor the CPU are "cranking widgets", then gtd (the GetThingsDone TM Daemon) will grab the system notification and tell you what you're doing next.. clock ticking.. let's GO!. 

To be expounded upon:

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-09-02T16:25:35Z
Modified: 2014-02-09T02:43:23Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2012-09-02T20:03:19Z says:_ 

 Task-doing becomes a function on a par with an OS system processes, the entire computer operating system is bent to your purpose, and tasks are subject to scheduling similar to that of the ruthlessly immediate linux kernel. 
The GetThingsDone TM Daemon might force you to assign a "productivity index" (coined) to your all of your running software.. spending cycles with vim? Good Boy! Using CAD? OK!, The browser? OOPS! too bad, system notification tells you that you have better things to do.. like THIS.. procrastinator interrupter extrordinaire, because if you're not "cranking widgets", what ARE you cranking?
 
This should make Personal Productivity pervs pant, 
give potential employees pause, 
and cause potential employers to begin tenting their fingers with a certain grin.. 

Define "productivity".. "widgets", you say? well get cranking! Mwuhoohahahaaaa

**Comment by pbeckingham** [comment]
No plans to implement.
