### ISSUE TITLE
Make better use of github code release page

### ISSUE THREAD

**Issue by pbeckingham** [GothenburgBitFactory/taskwarrior#4]
Github shows this list which it builds from tags:
https://github.com/GothenburgBitFactory/taskwarrior/releases

With some effort, and unknown benefits, we could adorn this list with other content.

Example of what could be done:
https://github.com/docker/compose/releases

Decide if this is something we want.

Suggested by: jrabbit

**Comment by svijee** [comment]
Steps to do:
- [ ] Tick the 'prerelease' button on all non-stable release tags
- [ ] Upload the tar.gz from all versions to the corresponding release tag to github

If anyone isn't against this, I would take care of that. It's just cleaner this way.

**Comment by recollir** [comment]
Good. I guess it would be good to even “hide” the older released versions. Otherwise those will be downloaded by mistake...

**Comment by svijee** [comment]
I've marked all non-release tags as "pre-release" which are now marked as pre-release. v2.5.1 is marked as the latest release. I did not upload the compiled tarballs.

The current disadvantage for us is, that the GitHub releases are tight to the tags and are somehow ordered. "stable" and "sRecurrence" are on the top of the list. I don't know what kind of tags these are.

It might be also good to add release notes to the GH release.

**Comment by pbeckingham** [comment]
This is useful, but only if we can keep old tarballs and old information in general hidden or missing.  I like the idea of v2.5.1 having perhaps the NEWS file (basically release notes) and linking off to https://taskwarrior.org/downloads/task-2.5.1.tar.gz, but older info is going to mislead.

So when 2.5.2 is released, I'm thinking we would need to remove the 2.5.1 info.
