### ISSUE TITLE
[EX-44] Dependency chains

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#40]
_Arkady Grudzinsky on 2012-05-08T00:27:13Z says:_ 

 I discussed this 6 months ago here

http://taskwarrior.org/boards/6/topics/1910#message-1918

Seemed to get some positive feedback.  Has this suggestion materialized?

To remind, the suggestion was to create a "chain" command to create dependency chains of existing tasks:

<pre>
$ task 100,101,102,103,104 chain
</pre>
would be an equivalent of issuing 4 commands:
<pre>
$ task 101 dep:100
$ task 102 dep:101
$ task 103 dep:102
$ task 104 dep:104
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-05-08T00:27:13Z
Modified: 2014-02-09T02:43:23Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-08T03:25:34Z says:_ 

 I like it.  Thanks for the reminder.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2012-08-05T22:07:12Z says:_ 

 This request is implemented in the attached external script, (at)taskchain@.
Make the script executable with:
<pre>
chmod +x taskchain
</pre>

You can then do:
<pre>
./taskchain 100 101 102 103 104
</pre>

If this request were implemented internally, would filters be allowed? How would
<pre>
task <filter> chain
</pre>
be treated? I guess it could order the tasks by ID or creation date.

Note that in addition to the thread referenced in the original post, there was another thread with a similar feature request:
http://taskwarrior.org/boards/6/topics/1569
An extrenal script could implement that request as well but would also need a way of getting the task number of the commands created. You would only need to get the task ID of the first add.
This could be a job for sed. The following will return the task ID of the add:
<pre>
task add first_description | sed -r 's/[^0-9]*([0-9]+)\./\1/'
</pre>

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2012-08-05T22:07:12Z says:_ 

 Attachment taskchain has been added with description: external bash script implementation

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2012-08-16T02:46:43Z says:_ 

 posted here:
http://taskwarrior.org/projects/taskwarrior/wiki/ExternalScripts

**Comment by pbeckingham** [comment]
[EX-44_taskchain.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755299/EX-44_taskchain.txt)

**Comment by sclee15** [comment]
```
#!/bin/bash
echo "$# arguments"
argv=("$@")

for (( i=$#-1; i > 0; i-- ))
do
  echo task ${argv[i]} modify depends:${argv[i-1]}
  task ${argv[i]} modify depends:${argv[i-1]}
done
```
