### ISSUE TITLE
[TW-367] "color.label" should work with "summary"

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#402]
_steve rader on 2013-04-03T12:41:20Z says:_ 

 <pre>
task 'rc.color.label=bold red' summary
</pre>
...does not work right.

see attached screenshot taken with the default ~/.taskrc

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-04-03T12:41:20Z
Modified: 2014-02-09T01:36:04Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-04-06T21:18:51Z says:_ 

 Thanks.

**Comment by pbeckingham** [comment]
![tw-367_tasksummarylabeleffectbug-2](https://user-images.githubusercontent.com/7963/36637236-d5dbf85c-19a5-11e8-8887-1a92da744205.gif)
