### ISSUE TITLE
[TW-368] Commit should be available from "git archive" tarballs as well

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#403]
_Ben Boeckel on 2013-07-11T03:11:04Z says:_ 

 The commit hash should be used even when not in a git repository using .gitattributes and the export-subst attribute. I can make a patch for this Sunday.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-07-11T03:11:04Z
Modified: 2014-02-09T01:36:04Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-07-11T11:13:37Z says:_ 

 I'm more interested in a justification for this, than a patch.

The Commit hash is for us to distinguish between dev builds.  For releases, there is the version number.

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2013-07-11T16:16:26Z says:_ 

 I ran "git archive" to package up taskd and task to move over to my server to compile and commit.h was neither found nor generated. It should also be generated at build time since the commit can change without cmake being rerun.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-07-11T17:13:15Z says:_ 

 Ben Boeckel wrote:
> I ran "git archive" to package up taskd and task to move over to my server to compile and commit.h was neither found nor generated. It should also be generated at build time since the commit can change without cmake being rerun.

The commit.h and cmake.h are both generated when you run "cmake .", which is the first step of a build.

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2013-07-11T18:06:59Z says:_ 

 Paul Beckingham wrote:
> The commit.h and cmake.h are both generated when you run "cmake .", which is the first step of a build.

commit.h isn't generated if the .git directory doesn't exist (which isn't true for git archive tarballs).

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2013-07-11T18:08:13Z says:_ 

 Also, the build step can be "cmake ../src; make; edit stuff; commit; make" in which case, if the CMake wasn't touched, the commit hash is now out-of-date.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-07-11T18:16:02Z says:_ 

 Ben Boeckel wrote:
> Also, the build step can be "cmake ../src; make; edit stuff; commit; make" in which case, if the CMake wasn't touched, the commit hash is now out-of-date.

Just clone the repo, run cmake from the root, then make.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-07-11T18:16:46Z says:_ 

 Ben Boeckel wrote:
> Paul Beckingham wrote:
> > The commit.h and cmake.h are both generated when you run "cmake .", which is the first step of a build.
> 
> commit.h isn't generated if the .git directory doesn't exist (which isn't true for git archive tarballs).

I don't think the .git directory has anything to do with it.

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2013-07-11T18:23:00Z says:_ 

 Paul Beckingham wrote:
> Just clone the repo, run cmake from the root, then make.

I don't have git on the target machine and building it is unnecessary. I should be able to build from a "git archive" tarball.

> I don't think the .git directory has anything to do with it.

From CMakeLists.txt:

message ("-- Looking for SHA1 references")
if (EXISTS ${CMAKE_SOURCE_DIR}/.git/index)
  set (HAVE_COMMIT true)
  execute_process (COMMAND git log -1 --pretty=format:%h
                   WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
                   OUTPUT_VARIABLE COMMIT)
  configure_file ( ${CMAKE_SOURCE_DIR}/commit.h.in
                   ${CMAKE_SOURCE_DIR}/commit.h)
  message ("-- Found SHA1 reference: ${COMMIT}")
endif (EXISTS ${CMAKE_SOURCE_DIR}/.git/index)

Chasing down HAVE_COMMIT, it looks like src/commands/CmdVersion.cpp and src/commands/CmdDiagnostics.cpp are missing HAVE_COMMIT guards around the commit.h includes (and COMMIT usage is Diagnostics). I still think the git hash should be generated at build time rather than configure time so that it's never out of date anyways.

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2013-07-13T17:16:41Z says:_ 

 Patch to fix the core issue.

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2013-07-13T17:27:25Z says:_ 

 Attachment 0001-Check-for-HAVE_COMMIT-before-including-commit.h.patch has been added with description: taskd patch

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2013-07-13T17:27:26Z says:_ 

 Patch for taskd for the same issue.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-07-14T01:42:37Z says:_ 

 Patches applied.  Thank you!

**Comment by pbeckingham** [comment]
[TW-368_0001-Check-for-HAVE_COMMIT-before-including-commit.h.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755586/TW-368_0001-Check-for-HAVE_COMMIT-before-including-commit.h.patch.txt)
[TW-368_0001-Guard-COMMIT-and-commit.h-usage-behind-HAVE_COMMIT.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755587/TW-368_0001-Guard-COMMIT-and-commit.h-usage-behind-HAVE_COMMIT.patch.txt)
