### ISSUE TITLE
[TW-371] tasksh tests in shell.t only work if ~/.taskrc exists

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#406]
_Paul Beckingham on 2013-04-07T16:07:56Z says:_ 

 <pre>
1.  shell.t
1..5
ok 1 - Created shell.rc
not ok 2 - custom prompt is being used
1.  Failed test 'custom prompt is being used'
1.  at ./shell.t line 46.
1.  'A configuration file could not be found in /home/paul
1. 
1.  Would you like a sample /home/paul/.taskrc created, so taskwarrior can proceed? (yes/no) A configuration file could not be found in /home/paul
1. 
1.  Would you like a sample /home/paul/.taskrc created, so taskwarrior can proceed? (yes/no) Cannot proceed without rc file.
1.  task 2.3.0 shell
1. 
1.  Enter any task command (such as 'list'), or hit 'Enter'.
1.  There is no need to include the 'task' command itself.
1.  Enter 'quit' (or 'bye', 'exit') to end the session.
1. 
1.  '
1.  doesn't match '(?^:testprompt>)'
not ok 3 - add/info working
1.  Failed test 'add/info working'
1.  at ./shell.t line 51.
1.  'A configuration file could not be found in /home/paul
1. 
1.  Would you like a sample /home/paul/.taskrc created, so taskwarrior can proceed? (yes/no) A configuration file could not be found in /home/paul
1. 
1.  Would you like a sample /home/paul/.taskrc created, so taskwarrior can proceed? (yes/no) Cannot proceed without rc file.
1.  task 2.3.0 shell
1. 
1.  Enter any task command (such as 'list'), or hit 'Enter'.
1.  There is no need to include the 'task' command itself.
1.  Enter 'quit' (or 'bye', 'exit') to end the session.
1. 
1.  '
1.  doesn't match '(?^:Descriptions+foo)'
ok 4 - Removed shell.rc
ok 5 - Cleanup
1.  Looks like you failed 2 tests of 5.
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-04-07T16:07:56Z
Modified: 2014-02-09T01:36:04Z
```

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-04-29T02:15:05Z says:_ 

 Hi Paul,

Please find attached a patch that fixes this problem. Now tasksh works as expected in batch mode. Only in interactive mode that it won't start with no ~/.taskrc unless the user answers 'yes' to the question:

Would you like a sample ~/.taskrc created, so taskwarrior can proceed? (y/n)

In batch mode, if ~/.taskrc exists or if the rc:taskrc option is used, it works fine. Otherwise, it's assumed that user answered 'no' to the above question and no commands get executed.

Thanks,
Haitham

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-04-29T02:15:05Z says:_ 

 Attachment tasksh.patch has been added with description: [PATCH] Disallowing tasksh to start in interactive mode (not in  batch mode) if no ~/.taskrc exists.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-04-29T03:25:11Z says:_ 

 Nice patch Haitham, that fixes the problem, as can be seen here:

http://tasktools.org/tinderbox/taskwarrior-2.3.0.html

Patch applied and pushed.  Thank you!

**Comment by pbeckingham** [comment]
[TW-371_tasksh.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755588/TW-371_tasksh.patch.txt)
