### ISSUE TITLE
[TW-374] fails to build on Hurd: error: 'PATH_MAX' was not declared in this scope

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#409]
_Jakub Wilk on 2013-03-08T21:19:38Z says:_ 

 Taskwarrior 2.1.2 fails to build on GNU/Hurd:
<pre>
src/Directory.cpp:152:12: error: 'PATH_MAX' was not declared in this scope
</pre>
PATH_MAX is not defined on Hurd (as allowed by POSIX), because Hurd doesn't have any path limits.
Please also note that even on systems that define PATH_MAX, getcwd() _can_ return paths longer than PATH_MAX.

For the time being I'll be using the attached patch for Debian, which is unfortunately not portable either (get_current_dir_name is a GNU extensions). The only portable solution I know of is getcwd()+realloc() in a loop dance: http://pubs.opengroup.org/onlinepubs/9699919799/functions/getcwd.html#tag_16_190_06

Full build log:
https://buildd.debian.org/status/fetch.php?pkg=task&arch=hurd-i386&ver=2.1.2-1&stamp=1361988373

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-03-08T21:19:38Z
Modified: 2014-02-09T01:36:04Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-08T21:34:14Z says:_ 

 I'd prefer not to throw exceptions like that - I would like to control what gets reported to the user, so they don't get developer-style errors.  Instead they would get something clear and actionable.

**Comment by taskwarrior** [comment]
_Jakub Wilk on 2013-03-10T22:18:11Z says:_ 

 I subscribe to the idea that user should get understandable error messages.
However, in this case the patch doesn't make things worse than they already are: there are other pieces of code that (implicitly) throw std::bad_alloc, because this is the exception thrown by the "new" operator when it cannot allocate memory.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-12T02:31:22Z says:_ 

 Jakub Wilk wrote:
> However, in this case the patch doesn't make things worse than they already are: there are other pieces of code that (implicitly) throw std::bad_alloc, because this is the exception thrown by the "new" operator when it cannot allocate memory.

Yeah, you're right.  Okay, happy to include this, but the patch doesn't build on Darwin because of get_current_dir_name(), which is a Gnu extension.

**Comment by taskwarrior** [comment]
_Jakub Wilk on 2013-04-09T23:36:43Z says:_ 

 Okay, how about this patch?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-04-10T00:53:30Z says:_ 

 Nice patch, thank you.  Applied and pushed.

**Comment by taskwarrior** [comment]
_Jakub Wilk on 2014-01-07T20:40:28Z says:_ 

 Unfortunately, it's broken again 2.3.0.beta2. Please apply the attached patch.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-08T04:38:20Z says:_ 

 Thank you.  Applied and propagated.

**Comment by pbeckingham** [comment]
[TW-374_no-path-max-2.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755590/TW-374_no-path-max-2.diff.txt)
[TW-374_no-path-max.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755591/TW-374_no-path-max.diff.txt)
