### ISSUE TITLE
[TW-375] tasksh throws exception on Ctl-D

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#410]
_Paul Beckingham on 2013-03-10T19:22:17Z says:_ 

 Ctl-D in tasksh causes an exception that should be a simple exit.  The example below is OSX 10.8.2.

<pre>
$ tasksh
task 2.3.0 shell

Enter any task command (such as 'list'), or hit 'Enter'.
There is no need to include the 'task' command itself.
Enter 'quit' (or 'bye', 'exit') to end the session.

task> ^Dlibc++abi.dylib: terminate called throwing an exception
Abort trap: 6
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-03-10T19:22:17Z
Modified: 2014-02-09T01:36:04Z
```

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-03-17T19:11:56Z says:_ 

 Hi Paul,

Please find attached a patch that fixes this. The patch has the following changes:
*  Changed FindReadline.cmake to search for Readline in macports paths before system paths on OS X.
*  Fixed CTRL-D. Now it exits tasksh.
*  Fixed a crash when a task description had any special characters.

Thanks,
Haitham

**Comment by taskwarrior** [comment]
_Haitham Gad on 2013-03-24T23:21:34Z says:_ 

 I'm wondering if there's any issues with this patch that need to be fixed before pushing. Let me know if there's any problems.

Thanks,
Haitham

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-27T03:23:18Z says:_ 

 > I'm wondering if there's any issues with this patch that need to be fixed before pushing. Let me know if there's any problems.

Hi Gaitham,

No issues, the patch looks good.  I have just applied and pushed it.  Sorry for the delay - sometimes the day job expands to fill all available time, so this is just me getting behind on my task list.

**Comment by pbeckingham** [comment]
[TW-375_tasksh1197.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755592/TW-375_tasksh1197.patch.txt)
