### ISSUE TITLE
[TW-376] pri_sort.t failure

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#411]
_Jakub Wilk on 2014-01-08T10:48:24Z says:_ 

 I've seen this failure on a few Debian autobuilders:
<pre>
1.  /build/task-9AAHpc/task-2.3.0~beta2/test/pri_sort.t
1..34
ok 1 - Created pri.rc
not ok 2 - pri H !< H
1.  Failed test 'pri H !< H'
1.  at /build/task-9AAHpc/task-2.3.0~beta2/test/pri_sort.t line 52.
1.  'Using alternate .taskrc file /build/task-9AAHpc/task-2.3.0~beta2/obj/test/pri.rc
1. 
1.  ID Pri Description
1.  -- --- -----------
1.  2 M M
1.  3 L L
1.  4 _
1. 
1.  3 tasks
1.  '
1.  matches '(?^:H)'
</pre>

There's an unexpected match because the build directory name (which is included in the "Using alternate .taskrc file ..." message), contained the letter H. Please apply the attached patch to fix the failure.

**Comment by pbeckingham** [comment]
[TW-376_tests-fix-pri-sort.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755593/TW-376_tests-fix-pri-sort.diff.txt)
