### ISSUE TITLE
[TW-378] Directory doesn't handle d_type==DT_UNKNOWN

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#413]
_Jakub Wilk on 2013-03-13T18:35:26Z says:_ 

 readdir(3) manpage reads:
> Currently,  only  some file systems (among them: Btrfs, ext2, ext3, and ext4) have full support for returning the file type in d_type.  All applications must properly handle a return of DT_UNKNOWN.

However, Directory::remove_directory() and Directory::list() assume that if d_type != DT_DIR, then the file is not a directory.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-03-13T18:35:26Z
Modified: 2014-02-09T01:36:04Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-21T03:56:51Z says:_ 

 Thanks for reporting this.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-30T14:56:52Z says:_ 

 Thank you.

**Comment by taskwarrior** [comment]
_Jakub Wilk on 2013-04-10T19:43:42Z says:_ 

 I'm afraid this is not fixed correctly. If readdir() returns DT_UKNOWN, there's no way to tell whether is directory or not: you need to call lstat() to get that information. Please see the attached patch. (I didn't add any error handling, because the original code didn't have any either…)

**Comment by pbeckingham** [comment]
[TW-378_directory-handle-dt-unknown.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755594/TW-378_directory-handle-dt-unknown.diff.txt)
