### ISSUE TITLE
[TW-386] recognize Hurd and kFreeBSD

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#421]
_Jakub Wilk on 2013-04-10T19:50:31Z says:_ 

 Please accept the attached patches, which make taskwarrior recognize two non-Linux Debian ports: GNU/Hurd and GNU/kFreeBSD.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-04-10T19:50:31Z
Modified: 2014-02-09T01:36:04Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-04-13T18:52:27Z says:_ 

 Thank you.  Patch modified to use $(CMAKE_SYSTEM_NAME}.

**Comment by taskwarrior** [comment]
_Jakub Wilk on 2014-01-07T20:47:51Z says:_ 

 Unfortunately, GNU/Hurd and GNU/kFreeBSD detection doesn't work correctly in 2.3.0.beta2, for the following reasons:

1) CMAKE_SYSTEM_NAME on GNU/kFreeBSD is just "kFreeBSD" (without "GNU/" prefix; don't ask me why).
2) "kFreeBSD" needs to be tested before "FreeBSD".
3) CMAKE_SYSTEM_NAME on GNU/Hurd is just "GNU" (without "/Hurd" suffix; again, don't ask me why).

Please apply the attached patch to fix these problems.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2014-01-08T04:46:44Z says:_ 

 Thank you.  Applied.

**Comment by pbeckingham** [comment]
[TW-386_system-detection.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755596/TW-386_system-detection.diff.txt)
[TW-386_system-hurd.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755597/TW-386_system-hurd.diff.txt)
[TW-386_system-kfreebsd.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755598/TW-386_system-kfreebsd.diff.txt)
