### ISSUE TITLE
[TW-390] French localization

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#425]
_YBSA R on 2013-04-06T16:20:42Z says:_ 

 Request for a French localization.

There already exists a Spanish localization, which "is a major effort, requiring the translation of almost 700 phrases and fragments, many of which are complex and contextual".  See the announcement http://taskwarrior.org/news/158 and the file "(at)src/es-ES.h@".

This is an attempt to coordinate (or at least to avoid duplicated vain) effort at translating Taskwarrior into French.  For now, I only wrote the "(at)i18n/tips.fr-FR.h@" file.  The file "(at)src/fr-FR.h@" still has to be written, not only by translating it line per line, but also by making global choices, IMHO.  Feel free to contribute the way you prefer, this is just a place to discuss it if necessary.

_Keywords: French, internationalization, i18n, localization, l10n, translation, t9n._

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-04-06T16:20:42Z
Modified: 2014-02-09T01:36:05Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-04-06T18:02:23Z says:_ 

 I have assigned this to the 2.3.0 schedule, which keeps it in view.  It may not be completed in time for 2.3.0, but that's not important.

Thank you Y R for getting this started.  I think sharing the workload is a good idea.

As of writing, we are about to release 2.2.0, which contains the es-ES.h translation.  On release, the 2.2.0 changes will be merged to the 2.3.0 branch, and that is our first opportunity to start work on fr-FR.h.  So I propose the following approach:
1.  I will create a fr-FR.h UTF-8 encoded file in the 2.3.0 branch, after 2.2.0 is released, and it will contain 100% English strings.  This will be in a few days.
1.  As development proceeds on 2.3.0, the localized strings will change.  When new strings are added, they are added in English to the Spanish and French translations.  This means the translation effort consists of finding English in fr-FR.h and changing it.  If a string is modified in English, the translations will be flagged by comments indicating the need for review.
1.  I will create a utility to verify consistency among the translations.  This means checking that they all contain the same string identifiers.  We cannot release if we have different quantities of strings because it may not compile.
1.  I will extend the test suite in a way that allows us to run test builds in all languages.
1.  Any changes to the fr-FR.h file should result in patch submissions that modify that file.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-04-13T15:42:43Z says:_ 

 The fr-FR.h file is ready for translation.

**Comment by taskwarrior** [comment]
_YBSA R on 2013-04-17T14:16:25Z says:_ 

 Thanks, I started by translating date-related things, which seemed to be the easiest part, because it is almost context-free.  The patch is attached.

Note: I first translated short months and short days into French standard abbreviations.  For instannce, "juin" is usually not abbreviated, "juillet" can be abbreviated as "juil.".  Then I found that Taskwarrior expect a 3-letters wide string in Date and Nibbler classes, so I complied with it.  Can it be documented somewhere (either above affected strings in localization files or at any other suitable place for translation guidelines)?

**Comment by taskwarrior** [comment]
_YBSA R on 2013-04-17T14:16:25Z says:_ 

 Attachment 0001-Translated-date-related-strings-into-French.patch has been added with description: [PATCH] Translated date-related strings into French.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-06-09T20:05:48Z says:_ 

 This will not be ready in time for 2.3.0.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-09-07T16:40:04Z says:_ 

 Closing this issue because the work listed has been done, although the translation is nowhere near complete.  This is typically hte case with translations - it is a continuing work in progress.

**Comment by pbeckingham** [comment]
[TW-390_0001-Translated-date-related-strings-into-French.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755601/TW-390_0001-Translated-date-related-strings-into-French.patch.txt)
