### ISSUE TITLE
[TW-394] out-of-tree tests

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#429]
_Jakub Wilk on 2013-04-10T21:22:50Z says:_ 

 Please accept the attach patched, which allows building and running tests out-of-tree.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-04-10T21:22:50Z
Modified: 2014-02-09T01:36:05Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-04-13T19:05:09Z says:_ 

 Thank you.

**Comment by pbeckingham** [comment]
[TW-394_tests-out-of-tree.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755602/TW-394_tests-out-of-tree.diff.txt)
