### ISSUE TITLE
[EX-47] API for OTRS

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#43]
_Benjamin Weber on 2014-03-03T20:00:14Z says:_ 

 What [1] is for JIRA, Taskwarrior could orchestrate with Taskserver for OTRS [2]: a CLI for an existing web service. The user can adopt UDAs [3] and urgency coefficients [4].

A command line interface for a non-command line enterprise system.

Confer attached illustration.

[1] http://qissuescli.com
[2] http://www.otrs.com/solutions/integrate-otrs/
[3] http://taskwarrior.org/docs/udas.html
[4] http://taskwarrior.org/docs/best-practices.html#how

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-03-03T20:00:14Z
Modified: 2014-03-09T13:31:50Z
```

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2014-03-03T20:03:37Z says:_ 

 e977c7154068469f6f03690e843edaf3f4d1f178

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2014-03-09T13:28:42Z says:_ 

 There is bugwarrior, which integrates taskwarrior to 3rd party bug/issue tracking systems. Please look at https://pypi.python.org/pypi/bugwarrior and https://github.com/ralphbean/bugwarrior

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2014-03-09T13:31:50Z says:_ 

 bugwarrior is the better place to solve this feature request.

**Comment by pbeckingham** [comment]
[EX-47_otrs.pdf.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755298/EX-47_otrs.pdf.txt)
