### ISSUE TITLE
[EX-48] task extras [ update | list | install | uninstall | search | show | upgrade ]

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#44]
_David Patrick on 2012-07-24T21:54:54Z says:_ 

 Taskwarrior has an ever expanding set of add-ons and external script goodness, it's almost hard to keep track. Some are more mature than others, and a few could be considered "must-haves", for some users. 

We're maintaining a dedicated page to list them (see the External Scripts tab above ?) but many taskwarrior users are not going to even try them, as each one has to be researched and installed and used in a different way. 

So here's an idea; for those scripts we know and like and trust, maybe we maintain a debian repo and piggyback some dpkg wizardry (we're all using debian variants, right?) or even just proper use of makefiles, to make discovering, installing and removing some of these extras, easier.

the first thing would be local and repository list management, without re-inventing it. then,

 % tw extras

would list the associated extensions that were installed, with descriptions.

 % tw extras update

would query the repo and download version info updates to a local list.

 % tw extras list

would display a list of all available extensions, with installed extras and version gaps highlighted.

 % tw extras install < extension >

would do just that, and 

 % tw extras uninstall < extension >

would do the opposite, 

 % tw extras search < term >

like apt-cache search, searches full index of titles, descriptions and notes, and lists matching extensions.

 % tw extras show < extension >

like apt-cache show, displays version, description and notes for < extension >

 % tw extras upgrade [extension] 

upgrades the extension to the current version, 
or if run without [extension], upgrades all installed extensions, and tw itself, to the current version.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-07-24T21:54:54Z
Modified: 2014-04-13T15:37:00Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2012-07-24T21:58:40Z says:_ 

 this could be used to add and remove theme-sets, maybe even methodology templates (coined) too!

**Comment by taskwarrior** [comment]
_David Patrick on 2012-08-07T17:36:18Z says:_ 

 what would be the best way to formally recognise a taskwarrior "extra"? I mean besides posting links at http://taskwarrior.org/projects/taskwarrior/wiki/ExternalScripts ?

I was sort of thinking of an official repository, debian, git or whatever, maintaining code and make scripts, at something like https://tasktools.org/extras/tasknc/ for example. 

I'd like to see the installed extras listed in "task diag", but there would have to be an official online list to compare against. 

This would be the first step, and then, one-by-one, we could test the install/uninstall makefiles, and *task extras list* would have something to list

**Comment by pbeckingham** [comment]
No plans to implement.
