### ISSUE TITLE
[TW-405] task inserts space into description after opening parenthesis

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#440]
_Rainer Müller on 2013-03-14T14:26:20Z says:_ 

 When adding a task, a space is inserted into the description after an opening parenthesis. The same happens when trying to fix the description using the modify command.

<pre>
$ task add 'Foo (bar)'
Created task 27.
$ task 27 minimal
ID Project Description
* - ------- -----------
27         Foo ( bar)

1 task
</pre>

<pre>
$ task 27 mod 'Qux (bar)'
*  Description will be changed from 'Foo ( bar)' to 'Qux ( bar)'.
Modify task 27 'Qux ( bar)'?
</pre>

This must be a bug in the parsing of the command line as I can fix this problem using (at)task edit@. I reproduced the problem with both task 2.1.2 and 2.2.0.beta1.

As a workaround, the following works correctly:

<pre>
$ task add -- 'Foo (bar)'
Created task 28.
$ task 28 minimal

ID Description
* - -----------
28 Foo (bar)

1 task
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-03-14T14:26:20Z
Modified: 2014-02-09T01:43:27Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2013-03-14T16:15:40Z says:_ 

 you've been bitten by bug #819!

**Comment by taskwarrior** [comment]
_Rainer Müller on 2013-03-14T16:48:24Z says:_ 

 Oh well, apparently I am too dumb to use the search interface in the correct way. Now that I searched again I found at least #819, #854, #983, and #1139.

Sorry for the noise and the duplicate entry!

**Comment by pawamoy** [comment]
Sorry but the issue references seem wrong. Also I still experience this bug with version 2.5.1. Was this bug fixed?
