### ISSUE TITLE
[TW-411] broken xterm colorization escape sequence when stdout and stderr are merged

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#446]
_steve rader on 2012-11-24T17:17:19Z says:_ 

 It appears under at least one very specific set of circumstances, task 2.1.2
incorrect omits a broken xterm colorization escape sequence.  [Or rather,
task writes a line to stderr in the middle of writing an xterm colorization
escape sequence to stdout?]

The following output popped up in Vit, which is unexpected...
<pre>
;237m  9d  0.0493 Operation drawing look boil
</pre>
The expected output is...
<pre>
29                     9d  0.0493 Operation drawing look boil
</pre>

Here's proof this is not a Vit problem; it's a task problem...
<pre>
$ task rc.defaultheight=999 2>&1 | grep -B2 -A2 "Operation drawing"
26                    10d  0.0548 Abide by the current fear island
29                   Configuration override rc.defaultheight:999
;237m  9d  0.0493 Operation drawing look boil
30                     9d  0.0493 Knee tired bite sleep ink sad
31                     1d 0.00548 Copy the thunder at the brake limit!
</pre>

Here's proof that this is caused by merging stdout and stderr...
<pre>
$ task rc.defaultheight=999 | grep -B2 -A2 "Operation drawing"
TASKDATA override: /home/rader/.task-vit
[task next rc.defaultheight=999]
Configuration override rc.defaultheight:999
24 ear                2wk    1.11 Oven take believe cheese need
26                    10d  0.0548 Abide by the current fear island
29                     9d  0.0493 Operation drawing look boil
30                     9d  0.0493 Knee tired bite sleep ink sad
31                     1d 0.00548 Copy the thunder at the brake limit!
</pre>

Sorry.

I'll try to provide more information when I get to figuring out a workaround
for this bug in Vit.

steve
* -

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-11-24T17:17:19Z
Modified: 2014-02-09T01:47:39Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-11-24T17:28:45Z says:_ 

 I see you are not separating the stdout/stderr streams (2>&1).  You might want to use Perl's (at)IPC::open3@.  Note that the taskwarrior test suite is now required to do that.

**Comment by taskwarrior** [comment]
_steve rader on 2012-11-24T18:03:46Z says:_ 

 Paul Beckingham wrote:
> I see you are not separating the stdout/stderr streams (2>&1).  You might want to use Perl's (at)IPC::open3@.  Note that the taskwarrior test suite is now required to do that.

the workaround i just implemented was 2> /dev/null.
glancing at the Source, it doesn't seem entirely insane.
?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-12-06T22:55:34Z says:_ 

 Rejecting, as it's not really a bug.  When streams are combined, there is no telling how that will be done.  Keeping them separate is the only way to guarantee consistency.

**Comment by pbeckingham** [comment]
[TW-411_colorization-problem-dot-task.tar.gz](https://github.com/GothenburgBitFactory/taskwarrior/files/1756110/TW-411_colorization-problem-dot-task.tar.gz)
