### ISSUE TITLE
[TW-413] Task scheduled date is after due date

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#448]
_Jostein Berntsen on 2012-11-12T16:45:22Z says:_ 

 If I enter this
<pre>
task add scheduled:10th due:20th Visit the museum
</pre> 

I get:

<pre>
Warning: You have specified that the 'scheduled' date is after the 'due' date.
Warning: You have specified that the 'scheduled' date is after the 'end' date.
</pre>

Is this right?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-11-12T16:45:22Z
Modified: 2014-02-09T01:49:40Z
```

**Comment by taskwarrior** [comment]
_Zed Jorarard on 2012-11-12T23:53:32Z says:_ 

 yep, it is. today is the the 13.11. scheduled will be the 10.12. because it uses the next 10th and due will be 20.11.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-11-13T01:23:10Z says:_ 

 Not a bug.  Spot on, Zed.

**Comment by arkenoi** [comment]
I think it is not a bug, but "fixing" it would make a nice feature! The current behavior is technically correct, but it would be nice if taskwarrior could act somewhat smarter here.

**Comment by tbabej** [comment]
Do I understand correctly here that the line of thinking is "if both due data and scheduled date use imprecise date specifications, and scheduled date is evaluated to be later than due date, then the normal interpretation of the imprecise date should be changed to allow dates in the past"?
