### ISSUE TITLE
[TW-417] JSON export has extra commas (on 2.1.1)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#452]
_Thomas Sullivan on 2012-07-31T13:03:33Z says:_ 

 Searching has shown only the changelog (http://taskwarrior.org/projects/taskwarrior/wiki/Changelog) stating a bug was fixed regarding misplaced commas in the JSON exports. (However no ID number of the bug is given.)

I have updated to version 2.1.1, and attached is my task diag output as well as some of the sample JSON that is given after an export.

That fails, I believe due to the misplaced commas, I believe. You can see the if you open the file in an editor, they look like: ,,,, or the commas at the end of each line. Regardless, the attached JSON export output fails jsonlint.com as well.

Thanks for any thoughts or insight.

On deeper insight, it would seem that maybe this has to do with missing or "orphaned/abandoned" UDAs.  Going to try this with the UDAs that are no longer used in that task, but have them in the .taskrc again anyway.

See also: http://taskwarrior.org/boards/1/topics/2460
My task diag output: http://taskwarrior.org/attachments/530/task.diag.txt

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-07-31T13:03:33Z
Modified: 2014-02-09T01:54:30Z
```

**Comment by taskwarrior** [comment]
_Thomas Sullivan on 2012-07-31T13:03:33Z says:_ 

 Attachment comp.txt has been added with description: completed.data

**Comment by taskwarrior** [comment]
_Thomas Sullivan on 2012-07-31T13:03:33Z says:_ 

 Attachment w.json has been added with description: json output

**Comment by taskwarrior** [comment]
_Thomas Sullivan on 2012-07-31T13:07:25Z says:_ 

 Added the old/unused UDAs again and the command still exports with the ",,,," between two attributes.  

<pre>
{"id":0,"actual":"1.0",,,,"description":"look into missing lang and sex col values or swapping of th.......
</pre>

(I shortened it, but the commas are after "actual")

**Comment by taskwarrior** [comment]
_Thomas Sullivan on 2012-07-31T13:11:26Z says:_ 

 As an aside, what I did end up doing was rewriting the example add-on ruby JSON parser to take note of this fact and "ignore" it, to speak, with some gsub regex goodness, as I needed to output things in CSV anyway.

<pre>
File.readlines(ARGV[0]).each do |line|
  line.gsub!(/[,]$/,'')
  line.gsub!(/[,]{2,}/,',')
  data = JSON.parse(line)
</pre>

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-08-02T03:39:47Z says:_ 

 Looks like UDA orphans misbehave in the export command.  Thanks Thomas.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-02-11T03:38:46Z says:_ 

 I am not able to replicate this in version 2.2.0, leading me to believe it is fixed.  I used this script:

<pre>
1.  Create 2 UDAs.
echo 'data.location=.'                        > x
echo 'uda.foo.type=string'                   >> x
echo 'uda.foo.label=FOO'                     >> x
echo 'uda.bar.type=string'                   >> x
echo 'uda.bar.label=BAR'                     >> x
1.  Add a task that uses foo, but not bar.
../task rc:x add one foo:value
../task rc:x 1 info
../task rc:x export
1.  Make 'foo' an orphan, and 'bar' unused.
echo 'data.location=.'                        > x
echo 'uda.bar.type=string'                   >> x
echo 'uda.bar.label=BAR'                     >> x

../task rc:x 1 info
../task rc:x export
</pre>

And got this result:

<pre>
Using alternate .taskrc file x
Created task 1.
Using alternate .taskrc file x

Name        Value                               
ID          1
Description one
Status      Pending
UUID        76d6e4bd-4aee-4879-9b6d-3dfeae5780ab
Entered     2/10/2013 22:34:07 (-)
Urgency     0
FOO         value

Using alternate .taskrc file x
{"id":1,"description":"one","entry":"20130211T033407Z","foo":"value","status":"pending","uuid":"76d6e4bd-4aee-4879-9b6d-3dfeae5780ab","urgency":"0"}
Using alternate .taskrc file x

Name        Value                               
ID          1
Description one
Status      Pending
UUID        76d6e4bd-4aee-4879-9b6d-3dfeae5780ab
Entered     2/10/2013 22:34:07 (-)
Urgency     0
[foo        value]

Using alternate .taskrc file x
{"id":1,"description":"one","entry":"20130211T033407Z","foo":"value","status":"pending","uuid":"76d6e4bd-4aee-4879-9b6d-3dfeae5780ab","urgency":"0"}
</pre>

**Comment by pbeckingham** [comment]
[TW-417_comp.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756111/TW-417_comp.txt)
[TW-417_w.json.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756112/TW-417_w.json.txt)
