### ISSUE TITLE
[TW-419] formatting error in manpage

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#454]
_Jakub Wilk on 2013-02-26T14:13:43Z says:_ 

 The attached patch fixes a formatting error in the manpage, section CONFIGURATION FILE AND OVERRIDE OPTIONS.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-02-26T14:13:43Z
Modified: 2014-02-09T01:54:30Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-02-26T21:38:41Z says:_ 

 Fixed.  Thank you.

**Comment by pbeckingham** [comment]
[TW-419_fix-manpage-formatting.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756113/TW-419_fix-manpage-formatting.diff.txt)
