### ISSUE TITLE
[TW-420] undo's thrown error not caught in right place

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#455]
_Scott Kostyshak on 2012-08-11T04:19:55Z says:_ 

 The error thrown by task undo when an argument is given is not caught in the right place because the thrown type is char const* and the only non-default catch is of type std::string. This gives:
<pre>
$ task undo 1
Unknown error.
</pre>

This is fixed in the attached patch, which yields:
<pre>
$ task undo 1
The undo command does not allow further task modification.
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-08-11T04:19:55Z
Modified: 2014-02-09T01:54:30Z
```

**Comment by pbeckingham** [comment]
[TW-420_0001-Bug.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756114/TW-420_0001-Bug.patch.txt)
