### ISSUE TITLE
[TW-424] doesn't honour HOME environment variable

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#459]
_Jakub Wilk on 2013-03-08T19:29:47Z says:_ 

 When taskwarrior expands ~, it only looks into the passwd database for the home directory.
This is unlike what POSIX shells do[0]: they use the HOME environment variable, possibly falling back on the passwd database only if the variable is unset.
The attached patches makes taskwarrior mimic shells' behavior. The patch was tested with v2.1.2.

[0] Reference:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-03-08T19:29:47Z
Modified: 2014-02-09T01:54:30Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-09T22:37:50Z says:_ 

 Thank you - modified patch applied.

Note: could not apply attached patch - it appears to be against 2.1.2, which at this point is 6 months and 120 commits out of date.

**Comment by pbeckingham** [comment]
[TW-424_home-env-var.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756115/TW-424_home-env-var.diff.txt)
