### ISSUE TITLE
[TW-426] 'task projects' considers newly deleted tasks and provides an incorrect summary

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#461]
_Louis-Claude Canon on 2012-07-27T09:35:32Z says:_ 

 Newly deleted tasks are considered by the projects report. Additionally, all the tasks are considered for the final summary:

<pre>
$ task add project:A 1
$ task add project:B 2
$ task add project:B 3
$ task 3 delete
$ task project:B projects
Project Tasks Pri:None Pri:L Pri:M Pri:H
* ------ ----- -------- ----- ----- -----
A           1        1     0     0     0
B           2        2     0     0     0

3 projects (3 tasks)
</pre>

I would have excepted:

<pre>
Project Tasks Pri:None Pri:L Pri:M Pri:H
* ------ ----- -------- ----- ----- -----
B           1        1     0     0     0

1 project (1 task)
</pre>

The proposed patch solves both issues.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-07-27T09:35:32Z
Modified: 2014-02-09T01:54:30Z
```

**Comment by taskwarrior** [comment]
_Aikido Guy on 2012-07-27T23:30:41Z says:_ 

 Please consider the possible addition of a Deleted column...
<pre>$ task project:B projects
Project Tasks Pri:None Pri:L Pri:M Pri:H Deleted
* ------ ----- -------- ----- ----- ----- -------
B           1        1     0     0     0       1</pre>

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-07-31T17:45:22Z says:_ 

 The report may even break the tasks based on their status ('pending', 'completed', 'waiting', 'recurring' and 'deleted') rather than on priority (especially if priority becomes UDA).

**Comment by pbeckingham** [comment]
[TW-426_0001-Bug-1044.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756116/TW-426_0001-Bug-1044.patch.txt)
