### ISSUE TITLE
[TW-428] annotations cause incorrect description line wrap

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#463]
_steve rader on 2012-12-01T23:52:50Z says:_ 

 When I have tasks with annotations, their descriptions are, ahem, often
incorrectly displayed on two lines with the last word of the description
on the second line... for example... this was done in a terminal with
100 columns....
<pre>
$ task add Process letter brush sit come disease bucket
Created task 296.
$ task 296 ls

ID  Proj Prio Age Description                                 
296            3s Process letter brush sit come disease bucket

1 task
$ task 296 anno Ear join low
Annotating task 296 'Process letter brush sit come disease bucket'.
Annotated 1 task.
$ task 296 ls 

ID  Proj Prio Age Description                                 
296           28s Process letter brush sit come disease
                  bucket
                    12/1/2012 Ear join low

1 task
$ task 296 deno Ear
Found annotation 'Ear join low' and deleted it.
Denotated 1 task.
$ task 296 ls

ID  Proj Prio Age Description                                 
296            1m Process letter brush sit come disease bucket

1 task
</pre>
My apologies if this is a dup.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-12-01T23:52:50Z
Modified: 2014-02-09T01:54:30Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-12-02T00:11:49Z says:_ 

 Not a dup at all, in fact the first bug of its kind.  Thanks Steve.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-02-10T21:10:12Z says:_ 

 Required a rewrite of the line extraction code.  The result makes fewer copies of strings, so should help performance.

**Comment by pbeckingham** [comment]
![tw-428_borked](https://user-images.githubusercontent.com/7963/36642525-7ca96936-1a0e-11e8-9063-cb4943f3ade0.png)
