### ISSUE TITLE
[TW-430] Blank lines when confirming bulk changes

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#465]
_Louis-Claude Canon on 2012-07-24T15:49:55Z says:_ 

 Blank lines when confirming bulk changes are printed after each confirmation even when the verbose option does not contain 'blank'. Also, the blank lines do not separate clearly each changes:

<pre>
$ task rc:bug.rc mod pri:L
This command has no filter, and will modify all tasks.  Are you sure? (yes/no) y
*  Priority will be set to 'L'.
Modify task 1 '1'? (yes/no/all/quit) y

Modifying task 1 '1'.
*  Priority will be set to 'L'.
Modify task 2 '2'? (yes/no/all/quit) y

Modifying task 2 '2'.
*  Priority will be set to 'L'.
Modify task 3 '3'? (yes/no/all/quit) y

Modifying task 3 '3'.
Modified 3 tasks.
Using alternate .taskrc file bug.rc
</pre>

I propose the following patch, which moves the blank lines two lines above:
<pre>
$ task rc:bug.rc mod pri:L
This command has no filter, and will modify all tasks.  Are you sure? (yes/no) y
*  Priority will be set to 'L'.
Modify task 1 '1'? (yes/no/all/quit) y
Modifying task 1 '1'.
*  Priority will be set to 'L'.
Modify task 2 '2'? (yes/no/all/quit) y
Modifying task 2 '2'.
*  Priority will be set to 'L'.
Modify task 3 '3'? (yes/no/all/quit) y
Modifying task 3 '3'.
Modified 3 tasks.
Using alternate .taskrc file bug.rc
</pre>

The default is that the first blank line is useless.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-07-24T15:49:55Z
Modified: 2014-02-09T01:54:30Z
```

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-07-24T16:20:34Z says:_ 

 Another solution is to print the blank line after each change, which would give the following output:
<pre>
$ task rc:bug.rc mod pri:L
This command has no filter, and will modify all tasks.  Are you sure? (yes/no) y
*  Priority will be set to 'L'.
Modify task 1 '1'? (yes/no/all/quit) y
Modifying task 1 '1'.
*  Priority will be set to 'L'.
Modify task 2 '2'? (yes/no/all/quit) y
Modifying task 2 '2'.
*  Priority will be set to 'L'.
Modify task 3 '3'? (yes/no/all/quit) y
Modifying task 3 '3'.

Modified 3 tasks.
</pre>

I favour this solution actually as I think the output is superior even though it leads to code duplication (see the patch).

The other patch cleans one message for bulk denotations.

**Comment by pbeckingham** [comment]
[TW-430_0001-Bug-1038.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756117/TW-430_0001-Bug-1038.patch.txt)
[TW-430_0002-Code-Cleanup.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756118/TW-430_0002-Code-Cleanup.patch.txt)
