### ISSUE TITLE
[TW-433] please include tests in source tarball

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#468]
_Jakub Wilk on 2013-02-26T18:14:20Z says:_ 

 I see that the test/ directory is available in the git repository, but it's not included in the source tarball.
Could you please include it by the next release? Thanks for considering!

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-02-26T18:14:20Z
Modified: 2015-10-23T15:29:49Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-02T23:20:43Z says:_ 

 The tests are in the code repository, but have additional dependencies, namely Perl and the JSON module.  I'm not sure anyone outside development needs them.  Can you elaborate on why this is a good idea?

**Comment by taskwarrior** [comment]
_Jakub Wilk on 2013-03-08T17:50:19Z says:_ 

 Well, it should be in your best interest that as many users as possible run the tests on their machines, possibly discovering latent bugs that didn't trigger on your ones. Users are not going to do this if the test suite is "hidden" from them in the VCS.

Personally, I wanted to run tests for Debian packages, as part of build process. (I will still do that, even you decide not to include the test/ directory, it'll be just extra hassle for me.)

Anyway, I attached patch (tested with 2.1.2) that should allow tests succeed when run against a released version.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-09T22:15:20Z says:_ 

 Patch applied - thank you, that's a good improvement.

As for the tests, I prefer the continuous integration approach where we build and test every commit against 8 platforms.  See this:

http://tasktools.org/tinderbox/taskwarrior-2.2.0.html

We didn't exactly hide the unit tests by putting them in a public repository, but you're right, they are missing from the tarball.  Probably because in 6 years, only one person asked for that.  :)

**Comment by taskwarrior** [comment]
_Heiko Becker on 2015-10-23T15:29:49Z says:_ 

 > We didn't exactly hide the unit tests by putting them in a public repository, but you're right, they are missing from the tarball.
> Probably because in 6 years, only one person asked for that. 

I'd also like that. As a source based distro (http://www.exherbo.org/) we build everything anyway and running (meaningful) tests fits quite naturally to this and is actually an encouraged policy.

**Comment by pbeckingham** [comment]
[TW-433_tests-for-released-version.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756119/TW-433_tests-for-released-version.diff.txt)
