### ISSUE TITLE
[TW-439] East Asian character width is not treated correctly when printed out

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#474]
_Roy Zuo on 2013-03-02T14:40:56Z says:_ 

 ![Imported image](http://i.imm.io/XW1t.png)

My task version is 2.1.2. Below are part of my pending.data.

<pre>
[description:"验光" entry:"1361886557" status:"pending" toodleid:"50143713" uuid:"583e3f39-a4fa-4a35-80bb-8bfe8d735f88"]
[description:"买钱包" entry:"1361886557" status:"pending" toodleid:"53722531" uuid:"c3ad4e52-4d72-498d-babb-d34f3022a53b"]
[description:"重新设计向上向下箭头" entry:"1361886557" project:"dooloo" status:"pending" toodleid:"61212918" uuid:"19b842ee-592c-4f25-a4a3-a275a9f352bb"]
[description:"更改bootstrap变量，改变各种颜色" entry:"1361886557" project:"dooloo" status:"pending" toodleid:"61212922" uuid:"75e882a8-8c18-419b-b604-7cfd9d8ca13d"]
[description:"买timbuk2 q背包" entry:"1361886557" status:"pending" toodleid:"62800331" uuid:"f9ed2b0d-e4de-4a1e-a033-74d3da5b5bf4"]
[description:"帖子页面直接看视频和图" entry:"1361886557" project:"dooloo" status:"pending" toodleid:"71647286" uuid:"4652de06-c190-4a4f-ba1a-3b5c28d3c67e"]
[description:"列表页面直接发表回复" entry:"1361886557" project:"dooloo" status:"pending" toodleid:"71647288" uuid:"e767c72d-2942-4147-904e-04ce0e697a91"]
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-03-02T14:40:56Z
Modified: 2014-02-09T01:54:31Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-02T23:11:03Z says:_ 

 Excellent catch, Roy.  Thank you.

Using your data, I found that taskwarrior was not calculating widths, but was just calculating character counts - a silly and widespread error.

**Comment by pbeckingham** [comment]
![tw-439_width](https://user-images.githubusercontent.com/7963/36642536-a493df3a-1a0e-11e8-8247-dfb8279f4dfd.png)
