### ISSUE TITLE
[TW-443] Recurrence.indicator column too wide

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#478]
_Max Muller on 2013-02-24T17:03:39Z says:_ 

 When displayed in task reports, the recurrence.indicator column should only be a single character wide (that is, assuming that the recurrence.indicator parameter is set to the default of R, and the corresponding label is also set to R (which both of mine are).

In practice, however, the column appears in variable widths, the logic of which I can't figure out. In the picture I've attached, to demonstrate the problem, the column appears to be 3-4 characters wide, wasting valuable horizontal space. I've also noticed that this doesn't seem to happen as much (or at all?) with narrow reports that down't take up the whole screen width--in those cases the column appears correctly, one character wide.

I believe this to be a bug in taskwarrior report rendering and it only seems to affect the recurrence.indicator column.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-02-24T17:03:39Z
Modified: 2014-02-09T01:54:31Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-02-24T17:08:45Z says:_ 

 Good catch, thank you.

**Comment by pbeckingham** [comment]
![tw-443_recurrence_column_too_wide](https://user-images.githubusercontent.com/7963/36642548-c0d8d79a-1a0e-11e8-811f-caded406187d.png)
