### ISSUE TITLE
[TW-444] task - modify segfaults

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#479]
_Bryce Harrington on 2012-08-01T01:24:59Z says:_ 

 $ ./src/task - modify
Segmentation fault (core dumped)
$ git status
1.  On branch master

Found this purely on accident while testing taskhelm.  I don't expect this command to actually work.

This crash also occurs in task 2.0 from Ubuntu.
1. 0  0x00007f0d26f99f88 in std::string::assign(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
1. 1  0x0000000000483311 in operator= (__str=..., this=0x7fff7d77ea10) at /usr/include/c++/4.6/bits/basic_string.h:542
No locals.
1. 2  Arg::Arg (this=0x7fff7d77ea10, other=...) at /build/buildd/task-2.0.0.release/src/Arg.cpp:79
No locals.
1. 3  0x0000000000527971 in E9::eval (this=0x7fff7d77ec20, task=..., value_stack=...) at /build/buildd/task-2.0.0.release/src/E9.cpp:122
        right = {_value = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x774cf8 ""`, _raw = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x774cf8 ""`, _type = 2, _category = 0}
        result = {_value = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x774cf8 ""`, _raw = {static npos = <optimized out>, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x774cf8 ""`, _type = Arg::type_none, _category = Arg::cat_none}
        case_sensitive = true
        arg = {_M_current = 0x19658f0}

Full stacktrace attached.

**Comment by taskwarrior** [comment]
_Štěpán Henek on 2012-08-01T18:49:31Z says:_ 

 It seems that function (at)E9::eval@ doesn't consider that the vector (at)value_stack@ cat be empty.
See the attached patch.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-08-02T03:38:21Z says:_ 

 Thank you Bryce, Štěpán.  Good catch, good fix.

**Comment by pbeckingham** [comment]
[TW-444_bug1048.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756121/TW-444_bug1048.patch.txt)
[TW-444_task.trace.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756122/TW-444_task.trace.txt)
