### ISSUE TITLE
[TW-454] duplicated undo.data entries in 2.1.2

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#489]
_Zed Jorarard on 2012-10-31T23:34:01Z says:_ 

 i use 2 machines with tw and merge+autopush them to a ssh directory
both are version 2.1.2
upon merging i got many "found remote change to" msgs

i got duplicated undo.data entries, completed and pending seem ok

grep "time" undo.data | wc -l
3262

grep "time" undo.data | uniq | wc -l
186

entries are for example:

time 1351073134
old [description:"foo2" entry:"1350516803" status:"pending" uuid:"82612eb8-7e29-42a2-902b-6b98492da2b3"]
new [description:"foo2" entry:"1350516803" scheduled:"1350864000" status:"pending" uuid:"82612eb8-7e29-42a2-902b-6b98492da2b3"]

or 

time 1351149907
old [description:"bar1" entry:"1351149848" status:"pending" tags:"cal" uuid:"61e1ce51-68e1-4538-870d-42fed095a368"]
new [description:"bar1" due:"1351525500" entry:"1351149848" recur:"weekly" status:"recurring" tags:"cal" uuid:"61e1ce51-68e1-4538-870d-42fed095a368"]

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-10-31T23:34:01Z
Modified: 2014-02-09T01:54:31Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-11-17T15:03:08Z says:_ 

 Hi Zed,

Thanks for reporting this.  We haven't seen any duplicate problems with 2.1.2, but there were problems in the past.  It seems likely that you have residual duplicate entries, but new ones are not being created.

Could you try the following, then monitor it for new duplicates?
1.  Make a backup copy of your undo.data file
1.  Truncate your undo.data file so that there is one transaction (the most recent)
1.  Copy that undo.data file to all your machines, so they have a common branch point

**Comment by taskwarrior** [comment]
_Zed Jorarard on 2012-11-20T01:31:09Z says:_ 

 i made a testcase, hope this helps

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2012-11-22T00:37:55Z says:_ 

 Hi Zed,

thanks for the testcase. I'm not sure if this shows the ultimate cause of your duplicates, but it clarifies that the algorithm fails in a particular case of empty databases. Nonetheless, we are working on that.

**Comment by pbeckingham** [comment]
[TW-454_testcase-1117.sh.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756125/TW-454_testcase-1117.sh.txt)
