### ISSUE TITLE
[TW-459] CmdShow issues messages in incorrect situations.

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#494]
_Scott Kostyshak on 2012-08-12T19:43:35Z says:_ 

 (at)task show@ appends to the output (at)STRING_CMD_SHOW_DIFFER@ if there are recognized variables with values that are different from the default and shows (at)STRING_CMD_SHOW_UNREC@ if there are variables that are not recognized. However, these messages are issued regardless of the pattern that might be passed to (at)task show@ as an argument, which restricts the results to a set that the messages might not apply to.

For example, the following creates an unrecognized variable and then uses a pattern that is probably unmatched by anything. Although there are no results, both messages are still issued (note that I have a changed variable that triggers (at)STRING_CMD_SHOW_DIFFER@):
<pre>
$ task show zzAAzz rc.IamUnrecognized:1

Config Variable Value
No matching configuration variables.

Some of your .taskrc variables differ from the default values.  These are highlighted in color above.

Your .taskrc file contains these unrecognized variables:
  IamUnrecognized

  These are highlighted in color above.

Configuration override rc.IamUnrecognized:1
</pre>

The attached patch results in (at)task show@ only showing (at)STRING_CMD_SHOW_UNREC@ if there are unrecognized variables in the output and only showing (at)STRING_CMD_SHOW_DIFFER@ if there are recognized variables with values different from the defaults in the results.

An alternative to part of this patch would be to show (at)STRING_CMD_SHOW_UNREC@ even if there is not an unrecognized variable in the results (however (at)STRING_CMD_SHOW_DIFFER_COLOR@ should still not be shown). Would this be preferred?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-08-12T19:43:35Z
Modified: 2014-02-09T01:54:31Z
```

**Comment by taskwarrior** [comment]
_Filip Chabik on 2013-02-15T10:11:04Z says:_ 

 The bug is back it seems. During compilation on Debian box, I'm hitting following issue:

<pre>
[ 70%] Building CXX object src/commands/CMakeFiles/commands.dir/CmdDenotate.cpp.o
[ 70%] Building CXX object src/commands/CMakeFiles/commands.dir/CmdDiagnostics.cpp.o
/home/hadret/Repository/build/task-2be52e1/src/commands/CmdDiagnostics.cpp:40:20: fatal error: commit.h: No such file or directory
compilation terminated.
make[2]: *** [src/commands/CMakeFiles/commands.dir/CmdDiagnostics.cpp.o] Error 1
make[1]: *** [src/commands/CMakeFiles/commands.dir/all] Error 2
make: *** [all] Error 2
</pre>

I am using latest snapshot of 2.2.0 branch:

<pre>
curl -O http://tasktools.org/gitweb/\?p\=task.git\;a\=snapshot\;h\=2be52e1be2a8e579b1e4ef6c52260775de4e1b44\;sf\=tgz
</pre>

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-02-15T12:21:13Z says:_ 

 Filip Chabik wrote:
> The bug is back it seems. During compilation on Debian box, I'm hitting following issue:

You're seeing a compilation error, not a bug.  Clone the repo and follow the instructions in the INSTALL file.

**Comment by taskwarrior** [comment]
_Filip Chabik on 2013-02-15T14:23:53Z says:_ 

 Paul Beckingham wrote:
> You're seeing a compilation error, not a bug.  Clone the repo and follow the instructions in the INSTALL file.

Thank you for pointing this out -- seems that lack of the .git folder prevents taskwarrior to be properly build from the sources. To reproduce, try to build task-2.2.0 with .git folder present and without it. Should I create new bug report for this one?

**Comment by pbeckingham** [comment]
[TW-459_0001-Bug-1065.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756126/TW-459_0001-Bug-1065.patch.txt)
