### ISSUE TITLE
[TW-461] status column on a custom report with Spanish localization leads to 8GB increase in RAM and 100% CPU

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#496]
_Scott Kostyshak on 2013-03-21T03:01:32Z says:_ 

 I have been testing the Spanish localization on current 2.2.0 branch and came across a problem that I do not see with the English localization.
To reproduce, build and install with Spanish as the language. Then run the following two commands (be warned of your computer potentially locking up):

<pre>
task add sample description rc.data.location:/tmp/tempTasksDir
task tempreport rc.data.location:/tmp/tempTasksDir rc.report.tempreport.columns=id,status
</pre>

CPU spikes to 100% and RAM increases by 8GB. This lasts for 30 seconds. I do eventually get the correct output:

<pre>
ID Estatus
 1 Pendientes

1 tarea
Sobrescritura de configuración rc.data.location:/tmp/tempTasksDir
Sobrescritura de configuración rc.report.tempreport.columns:id,status
</pre>

Note that the following works fine (removing the status column):
<pre>
task tempreport rc.data.location:/tmp/tempTasksDir rc.report.tempreport.columns=id
</pre>

I can reproduce this on two different computers with Ubuntu 12.04, 64-bit, with the difference being that on the one with only 4GB of RAM it just freezes.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-03-21T03:01:32Z
Modified: 2014-02-09T01:54:32Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-21T03:44:35Z says:_ 

 My goodness.  Let's fix this one.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2013-03-26T23:39:49Z says:_ 

 Attached is a patch. All tests pass for me (when set to English). I'm not sure that I updated the changelog correctly.

Scott

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-03-27T02:39:26Z says:_ 

 > All tests pass for me (when set to English). I'm not sure that I updated the changelog correctly.

Looks goot to me.  I modified the ChangeLog, the "beta1" in there will either morph into "beta2" or "2.2.0".  Thanks Scott.  I think we can close this one now.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2013-03-27T03:22:50Z says:_ 

 Paul Beckingham wrote:
> Looks goot to me.  I modified the ChangeLog, the "beta1" in there will either morph into "beta2" or "2.2.0".  Thanks Scott.  I think we can close this one now.

Sounds good. Thanks.

**Comment by pbeckingham** [comment]
[TW-461_0001-Bug-1210.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756127/TW-461_0001-Bug-1210.patch.txt)
