### ISSUE TITLE
[TW-466] Allow user to specify a due date with a 2 digit year

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#501]
_Eli Lev on 2012-02-25T06:47:56Z says:_ 

 Hello,

This may be a stupid nitpicky thing but I find myself doing this usage error all of the time (I'm using task 2 beta 4):
task 2 mod due:3/1/12
instead of
task 2 mod due:3/1/2012

Would it be possible to allow for a 2 digit year?  We're past y2k so assuming a 20xx year should be ok for a long while.  Alternatively, an option could allow such prefix like (default perhaps):
2digitprefix = 2000
so taskwarrior would take the 2 digit year and just add the prefix if it's given and if it is not specified then only accept a 4 digit year.

Small item but a constant tiny little burr productivity wise.

Eli

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-02-25T06:47:56Z
Modified: 2014-02-09T01:54:32Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-02-25T15:11:43Z says:_ 

 Eli, thanks for writing this up.  It's a good suggestion, and one that we should support.  I will see if this can be added without much impact.

But I want to be open about what is happening with dates.  We are developing a date library, which supports all the taskwarrior forms, as well as full ISO-8601:2004 compliance.  This is the international standard for date representation, and none of those have a two-digit year.

No promises.

**Comment by taskwarrior** [comment]
_Eli Lev on 2012-02-25T22:52:38Z says:_ 

 Paul,

You're right.  In light of the focus of making core much more cleaner and dates being somewhat of a pain - perhaps this is not a good idea.

How about this behavior:
If a user does:
task 3 due 3/1
then the date defaults to current year (2012) and this only works with forward moving dates (i.e. today's date or any dates up to 12/31/current_year.

This might be an option to turn on in .taskrc rather than a default (like a 'dateshortcut' variable or something like that).

Anyway - just a thought.

Eli

**Comment by taskwarrior** [comment]
_Joon Ro on 2012-08-01T18:16:01Z says:_ 

 I +1 this. (The second sugesstion of Eli). 

Since a lot of times people will be entering tasks due within the same year, it would be great to be able to skip the year - 5 less characters to type.

**Comment by taskwarrior** [comment]
_Joon Ro on 2012-08-01T18:16:11Z says:_ 

 Joon Ro wrote:
> I +1 this. (The second suggestion of Eli). 
> 
> Since a lot of times people will be entering tasks due within the same year, it would be great to be able to skip the year - 5 less characters to type.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-08-01T19:10:45Z says:_ 

 As a workaround for the initial issue, couldn't you use the dateformat m/d/y (instead of m/d/Y) to use two-digit years?
<pre>
task rc.dateformat="m/d/y" add foo 8/1/12
</pre>

Regarding the last comments, I hope the provided patch makes the date parsing mechanism more robust with default values (if year is not defined, it is the current one and if month is also not included, it is also the current one, ...).

**Comment by pbeckingham** [comment]
[TW-466_0001-Enhancement.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756130/TW-466_0001-Enhancement.patch.txt)
