### ISSUE TITLE
[TW-470] Start of Current Month (Similar to Start of Work Week)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#505]
_Thomas Sullivan on 2012-07-24T21:10:02Z says:_ 

 I have a need for searching for tasks that have *end.after:socm* or in some similar fashion, a due date with that "Start of Current Month" value, etc.  I noticed the existence of "Start of Work Week" and could not find a similar functionality for the month value.  

Would it be possible to add that functionality via another "else if" in Date much like the block of code that processes "socw"?  

Also, the WIKI page: http://taskwarrior.org/projects/taskwarrior/wiki/Ck5 mentions the various date options, and I found that helpful as well.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-07-24T21:10:02Z
Modified: 2014-02-09T01:54:32Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-07-24T21:15:13Z says:_ 

 Yes, that's a simple addition.  Thank you.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-07-25T15:49:48Z says:_ 

 While looking for this, I notice that 'socw' is actually for 'start of calendar week'. Therefore, there is no corresponding 'start of the current week'. New notations should thus be introduced for this feature. I propose some improvements of the documentation in this patch (I updated the wiki page).

To start with this, I wonder what is the motivation for having both 'eow' and 'eoww' as they seems to be implemented the same way (same question with 'sow' and 'soww').

**Comment by taskwarrior** [comment]
_Thomas Sullivan on 2012-07-25T16:27:59Z says:_ 

 I do know that I've used 'eow' and not 'eoww' but maybe it relates to people working odd week start/stop dates.  One of our corporation's sub-entities actually begins the work week on Monday at 11am and then *ends* the work week on Monday at 10:59.  (I work in a department that writes software for payroll, GL, AP, interfaces, and non-medical related interfaces and it's a PITA with the odd start/stops sometimes...)

I had a patch ready to submit related to the actual code, and was able to make it on my machine however, I am unable to checkout the git repo hosted on taskwarrior as I can't hit it via the git ports behind my firewall at work.  So when I get home, I'll ready a patch later, if I can remember to.  It's just a few lines of code anyway.  

Would be happy to modify the wiki page I mentioned (CK5), though I don't believe I have wiki rights as of yet.  Which is fine, I'm still a FNG. :P

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2012-07-25T16:52:11Z says:_ 

 eow and eoww are the same for historical reasons. In the future they should return different days, of course. And be configurable. Don't be surprised to see that task in the beginning didn't know about European date standards. 

But most, if not all, date handling will move out of task into a separate library which we call libkronisk to do more sophisticated date math. What about being able to do

<pre>
* tomorrow in one year
* (next/this) wednesday
* last/past wdnesday
* next week
* next month
* next year
* in two weeks
* 2 weeks from now
* 2 weeks ago tuesday
* thursday in 2 weeks
* friday last week
* last day next month
* 10 days from today
* thursday before last weekend in may
* friday last full week in may
* 3rd wednesday this month
* 3 weeks after 2nd tuesday next month
* 100 days from the beginning of the month
* 10 days after last monday
* sunday in the evening
* in 6 hours
* 6 in the morning
* kl 18
* feb 11
* 2011-02-08
* 11/19/2011
* 14:00
* 2 o'clock
* 2pm
* this weekend
* next weekend
* last weekend
* next business day
* new moon
* full moon
* in 28 days
* 3rd quarter
* week 23
* {number} {unit}
* - {number} {unit}
* {ordinal} {unit} in {larger-unit}
</pre>

**Comment by taskwarrior** [comment]
_Thomas Sullivan on 2012-07-25T16:55:30Z says:_ 

 That would be fantastic - and I would be happy to help that along whenever/wherever I can.  Reminds me of the first time I realized I could type "the day after yesterday" into an Outlook appointment date/time and it actually worked.  This would be a great addition to Task.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-07-26T09:38:49Z says:_ 

 Should it be targeted to 2.x then (in wait for libkronisk) or should a temporary solution be found (adding new keywords like "sopw" for start of present week)?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-07-26T12:14:50Z says:_ 

 I think a fix would be good, and that fix will migrate over to libkronisk.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-07-26T13:02:13Z says:_ 

 The solution I add in mind was to let the user defines its own shortcuts based on the capability of kronisk (with an alias to "first day current month" in this case) and to provide a sub-set of them only by default (sow could be included by default, while soww and socw would be up to the user to define for example). But as long as kronisk is not ready, this is inapplicable.

An immediate solution is to add new hard-coded shortcuts, but it seems to me that the start of the current week (day, month, quarter, year) is a rather specific use-case.

**Comment by taskwarrior** [comment]
_Thomas Sullivan on 2012-07-26T13:45:45Z says:_ 

 Louis-Claude Canon wrote:
> The solution I add in mind was to let the user defines its own shortcuts based on the capability of kronisk (with an alias to "first day current month" in this case) and to provide a sub-set of them only by default (sow could be included by default, while soww and socw would be up to the user to define for example). But as long as kronisk is not ready, this is inapplicable.
> 
> An immediate solution is to add new hard-coded shortcuts, but it seems to me that the start of the current week (day, month, quarter, year) is a rather specific use-case.

Indeed, "current or present" could be defined many ways, similar to the way "year" could be defined - calendar/fiscal, etc.  An interesting thought.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-12-01T19:21:57Z says:_ 

 Thanks Thomas and Louis-Claude.  Thomas, you are listed in the AUTHORS file.

**Comment by pbeckingham** [comment]
[TW-470_0001-Documentation.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756131/TW-470_0001-Documentation.patch.txt)
