### ISSUE TITLE
[TW-478] A clearer error if UDA misspelled

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#513]
_Scott Kostyshak on 2012-08-15T18:21:00Z says:_ 

 If a UDA's type variable is not set but another variable for that UDA name is set, an error is thrown but it is an error that doesn't apply to that situation. I propose a new error. Why would you not set a type? I see two reasons:
(1) you mistype a name
(2) you're still learning about UDAs.

I think the new error is clearer in both cases.

Currently:
<pre>
$ task show uda rc.uda.customname.type:string rc.uda.custonmame.label:anything
Configuration override rc.uda.customname.type:string
Configuration override rc.uda.custonmame.label:anything
User defined attributes may only be of type 'string', 'date', 'duration' or 'numeric'.
</pre>

After applying attached patch:
<pre>
$ task rc.uda.customname.type:string rc.uda.custonmame.label:anything
Configuration override rc.uda.customname.type:string
Configuration override rc.uda.custonmame.label:anything
uda.custonmame.type not found. The UDA 'custonmame' must have a type specified.
</pre>

Comments?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-08-15T18:21:00Z
Modified: 2014-02-09T01:54:32Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-08-16T01:42:32Z says:_ 

 Error is much better.  Patch is good - applied and pushed.  Issue can be closed, but we need a ChangeLog patch.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2012-08-16T02:24:02Z says:_ 

 ChangeLog patch is attached.

**Comment by pbeckingham** [comment]
[TW-478_0001-Documentation.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756133/TW-478_0001-Documentation.patch.txt)
[TW-478_0001-Feature-1069.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756134/TW-478_0001-Feature-1069.patch.txt)
