### ISSUE TITLE
[TW-482] Display duration of each activity session

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#517]
_Justin Forest on 2012-12-17T12:39:07Z says:_ 

 This patch makes "task N info" display duration with each "Start deleted" message.  Duration is calculated from the last "Start added" message.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-12-17T12:39:07Z
Modified: 2014-02-09T01:54:32Z
```

**Comment by taskwarrior** [comment]
_Justin Forest on 2012-12-17T12:54:12Z says:_ 

 Attachment 0002-Display-duration-of-each-activity-session.patch has been added with description: updated patch

**Comment by taskwarrior** [comment]
_Justin Forest on 2012-12-17T13:10:28Z says:_ 

 Fixed a problem with intermediate modifications resetting the duration (e.g., start / add annotation / stop, duration was calculated from annotation to stop).

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-12-22T14:30:13Z says:_ 

 Thank you.  Looking at the patch now.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-12-22T15:11:31Z says:_ 

 Patch applied.  Thank you for the feature request and the patch.  There were some minor changes made in a subsequent patch to correct:
*  Style: cuddled braces
*  Style: one declaration per line
*  Omission: ChangeLog not updated
*  Omission: AUTHORS not updated
*  Omission: en-US.h change not propagated to es-ES.h (translation sent for edits)

**Comment by pbeckingham** [comment]
[TW-482_0001-Display-duration-of-each-activity-session.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756135/TW-482_0001-Display-duration-of-each-activity-session.patch.txt)
[TW-482_0002-Display-duration-of-each-activity-session.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756136/TW-482_0002-Display-duration-of-each-activity-session.patch.txt)
[TW-482_0003-Display-duration-of-each-activity-session.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756137/TW-482_0003-Display-duration-of-each-activity-session.patch.txt)
