### ISSUE TITLE
[TW-505] aliases are not listed in _commands or _zshcommands

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#540]
_Scott Kostyshak on 2012-07-26T22:01:58Z says:_ 

 These commands are used for tab-completion, among other things. Attached is a patch and two unit tests.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-07-26T22:01:58Z
Modified: 2014-02-09T01:56:51Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-07-26T22:08:48Z says:_ 

 This assumes that aliases are equivalent to commands, and they are not.  They are simply tokens expanded on the command line, and not necessarily commands.  See the output from '(at)task help@', after the commands for a list of aliases.

It is possible to create an alias that is just a filter, or perhaps some standard boilerplate text, and so on.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2012-07-26T22:19:01Z says:_ 

 Good point!

What is the best way to get tab-completion working with aliases then? Could there be a command _aliases that scripts/bash/task.sh could use? Or is it better not to worry about this?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-07-26T22:26:47Z says:_ 

 Scott Kostyshak wrote:
> Good point!
> 
> What is the best way to get tab-completion working with aliases then? Could there be a command _aliases that scripts/bash/task.sh could use? Or is it better not to worry about this?

Exactly - a new @_aliases@ command would do the trick.  No need for an (at)aliases@ command also, just @_aliases@.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2012-07-26T22:30:15Z says:_ 

 Paul Beckingham wrote:
> Exactly - a new @_aliases@ command would do the trick.  No need for an (at)aliases@ command also, just @_aliases@.

ok, I'll look into making an @_aliases@ command later. Thanks.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2012-07-27T19:23:18Z says:_ 

 Attached is a patch that implements @_aliases@. An (at)aliases@ command is not included because if someone wants to know what an alias is defined as they can see this in (at)task help@.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2012-07-27T19:26:17Z says:_ 

 However, there is still the question of where completion scripts should list aliases because they do not know if an alias is a command, a project, a filter, or something else. task could help out on this because it does know if an alias is a command. For example, task could add an alias to the commands vector returned by (at)commands@ if that alias points to a command. For example:

<pre>
  // Now add aliases that expand to commands.
  std::map <std::string, std::string>::iterator it;
  for (it = context.aliases.begin (); it != context.aliases.end (); ++it) {
    if (context.commands[context.aliases[it->first]])
      commands.push_back (it->first);
  }
</pre>

This is done in the attached patch for commands. However, if I understand Paul correctly, you don't want an alias to show up in a command even if it points to a command because an alias is still just a token. Is that correct?

**Comment by taskwarrior** [comment]
_David Patrick on 2012-07-27T19:45:58Z says:_ 

 Scott Kostyshak wrote:
>  However, if I understand Paul correctly, you don't want an alias to show up in a command even if it points to a command because an alias is still just a token. Is that correct?

From here I think it would make sense to see aliases commands listed with the native ones. especially if there were some *alias* indication. 

or, maybe the proposed *_aliases* helper command is all that's missing

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2012-07-28T19:56:37Z says:_ 

 Before, aliases could only be commands so it would have made sense to merge the output on taskwarrior's end. Now an alias can be almost anything. My suggested fix above would not account for the possibility that an alias could expand to, for example
<pre>
alias.rm=rc.confirmation:off delete
</pre>
A new @_aliases@ command was committed, and the bash completion script now merges @_aliases@ and @_commands@ and sorts the result. I will open a new ticket for fixing autocompletion of aliases in fish and a new one for fixing autocompletion of aliases in zsh.

**Comment by pbeckingham** [comment]
[TW-505_bug.1043.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755651/TW-505_bug.1043.t.txt)
[TW-505_CmdAliases.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755652/TW-505_CmdAliases.diff.txt)
[TW-505_CmdCommands_patch.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755653/TW-505_CmdCommands_patch.diff.txt)
[TW-505_patch_bug1043.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755654/TW-505_patch_bug1043.diff.txt)
