### ISSUE TITLE
[TW-510] JSON export broken with two or more tasks

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#545]
_Nicholas E. Rabenau on 2012-06-08T18:56:28Z says:_ 

 Exporting one is fine, but for two or more tasks the square brackets are missing. Testcase attached.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-06-08T18:56:28Z
Modified: 2014-02-09T02:00:40Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-06-08T20:49:28Z says:_ 

 Not a bug.  Try this:

<pre>
$ task show json
...
</pre>

Then change that setting, which controls the presence/absence of the square brackets.

**Comment by taskwarrior** [comment]
_Nicholas E. Rabenau on 2012-06-09T18:17:57Z says:_ 

 Thanks, adding (at)rc.json.array=on@ to the command line options fixed it (attaching the updated test script that proves it).

I wonder why this is not on by default. Always producing valid JSON should be desirable, shouldn't it?

**Comment by pbeckingham** [comment]
[TW-510_twbug_json_export.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756147/TW-510_twbug_json_export.txt)
