### ISSUE TITLE
[TW-513] Issue with the 'until' attribute

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#548]
_stéphane pezennec on 2012-07-24T08:48:14Z says:_ 

 I cannot manage to use the new (at)until@ attribute (taskwarrior-2.1.0).

First, the (at)until@ attribute cannot be set for an existing non-recurring task:

<pre>
	> TASKDATA=tmptask task add test
	TASKDATA override: tmptask
	Created task 1.

	> TASKDATA=tmptask task 1 modify until:7/25/2012
	TASKDATA override: tmptask
	You cannot specify an until date for a non-recurring task.
</pre>

Still, it seems possible to modify the (at)until@ date using (at)task edit@, and filtering e.g. with (at)ready@ works as expected, but then any other modification seems blocked:

<pre>
	> TASKDATA=tmptask task 1 edit
	Launching 'vi "task.9088.1.task"' now...
	Editing complete.
	Edits were detected.
	TASKDATA override: tmptask
	Until date modified.

	> TASKDATA=tmptask task 1 modify /te/Te/
	TASKDATA override: tmptask
	You cannot specify an until date for a non-recurring task.
</pre>

It is possible to create a new task with an (at)until@ date with the same command, but the new task does not allow modification (at least of its description):

<pre>
	> TASKDATA=tmptask task add test two until:7/25/2012
	TASKDATA override: tmptask
	Created task 2.
	
	> TASKDATA=tmptask task 2 modify /two/Two/
	TASKDATA override: tmptask
	You cannot specify an until date for a non-recurring task.
</pre>

(All those tests were performed with the default taskrc file created by task itself of the first invocation.)

Here is the output of the (at)task diag@ command (the program was compiled an installed using the (at)checkinstall@ program on a Debian/stable platform):

<pre>
	> TASKDATA=tmptask task diag
	TASKDATA override: tmptask

	task 2.1.0
	  Platform: Linux

	Compiler
	   Version: 4.4.5
	      Caps: +stdc +stdc_hosted +200809 +c1 +i4 +l4 +vp4

	Libraries
	       Lua: Lua 5.1.4

	Build Features
	     Built: Jul 24 2012 09:31:30
	    Commit: a413331
	     CMake: 2.8.2
	      Caps: -pthreads +srandom +random -uuid

	Configuration
	      File: /home/xxxx/.taskrc (found), 1259 bytes, mode 100644
	      Data: tmptask (found), dir, mode 40755
	    Server: 
	   Locking: Enabled

	External Utilities
	       scp: (found)
	     rsync: version 3.0.7
	      curl: curl 7.21.0

	Tests
	  UUID gen: 1000 unique UUIDs generated.
	     $TERM: screen (264x41)
	      Dups: Scanned 2 tasks for duplicate UUIDs:
		    No duplicates found

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-07-24T08:48:14Z
Modified: 2014-02-09T02:02:50Z
```

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-07-24T09:36:25Z says:_ 

 Thank you for the report. The following patch solves the issue.

**Comment by pbeckingham** [comment]
[TW-513_0001-Bug-1036.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756148/TW-513_0001-Bug-1036.patch.txt)
