### ISSUE TITLE
[TW-515] Providing updated us holidays

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#550]
_Eli Lev on 2012-01-13T00:28:05Z says:_ 

 Hi,

This is for 1.9.4.  Not really a bug.

This is not really a bug but I updated the US holiday file based on http://www.opm.gov/operating_status_schedules/fedhol/2012.asp.

Cheers.

Eli

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-01-13T00:28:05Z
Modified: 2014-02-09T02:03:27Z
```

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2012-01-15T00:44:25Z says:_ 

 Thanks Eli. Pretty soon Taskwarrior will pull holiday data from http://holidata.net and manual updates will be a thing of the past. That's the plan, anyway!

**Comment by pbeckingham** [comment]
[TW-515_holidays-US.rc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756150/TW-515_holidays-US.rc.txt)
