### ISSUE TITLE
[TW-524] Color rules not obeying precedence

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#559]
_Paul Beckingham on 2012-04-23T21:53:47Z says:_ 

 A task with both priority:L and a tag is colored as though rc.color.tagged were higher precedence than rc.color.pri.L, which it is not.

Reported by Jeff Schroeder.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-04-23T21:53:47Z
Modified: 2014-02-09T02:04:40Z
```

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-05-28T12:00:33Z says:_ 

 Workaround: addind a dot after 'tag' in the option rule.precedence
task rc.rule.precedence.color:due.today,active,blocked,overdue,due,scheduled,keyword,project,tag.,recurring,pri,tagged,completed,deleted all

This prevents 'tag' to be automatically completed as 'tagged' (the only other option starting with 'color.tag' with the default settings).

The first patch makes the non-trivial colour check more consistent. The second requires wildcards to finish with a dot.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-05-28T14:36:59Z says:_ 

 Patch applied.

**Comment by pbeckingham** [comment]
[TW-524_0001-Code-Cleanup.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756152/TW-524_0001-Code-Cleanup.patch.txt)
[TW-524_0002-Bug-990.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756153/TW-524_0002-Bug-990.patch.txt)
