### ISSUE TITLE
[TW-526] "task show" warns about a deprecated variable I'm no longer using

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#561]
_Casey Jones on 2012-05-18T00:41:45Z says:_ 

 I've recently upgraded to 2.0.

"task show" complains that I use a deprecated config variable, although I do not.

<pre>
$ task show

Config Variable                 Value
* snip-
annotations                     full
* snip-
Your .taskrc file contains these unrecognized variables:
  annotations

  These are highlighted in color above.

Your .taskrc file contains variables that are deprecated:
annotations
</pre>

My .taskrc does not contain the text 'annotations' (though it did used to).

Trying to delete this phantom variable fails:
<pre>
$ task config annotations
No entry named 'annotations' found.
</pre>

Am I missing something obvious, or is this a bug?

Let me know if you need more info.  Cheers.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-05-18T00:41:45Z
Modified: 2014-02-09T02:04:40Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-18T01:00:43Z says:_ 

 Already fixed.  Thanks for the report.

**Comment by pbeckingham** [comment]
[TW-526_.taskrc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756154/TW-526_.taskrc.txt)
