### ISSUE TITLE
[TW-528] task crashed with SIGSEGV in Context::dispatch()

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#563]
_Bryce Harrington on 2012-05-01T21:53:18Z says:_ 

 Forwarding bug from Ubuntu reporter James Troup:
  https://bugs.launchpad.net/ubuntu/+source/task/+bug/980093

"""
How to reproduce:

| james(at)ornery:$ mkdir /tmp/x; cd /tmp/x
| james(at)ornery:/tmp/x$ echo "data.location=/tmp/x/.task" > .taskrc
| james(at)ornery:/tmp/x$ task rc:.taskrc shell
| task 2.0.0 shell
|
| Enter any task command (such as 'list'), or hit 'Enter'.
| There is no need to include the 'task' command itself.
| Enter 'quit' (or 'bye', 'exit') to end the session.
|
| task> add foo
| Using alternate .taskrc file .taskrc
| Created task 1.
| task> 1 edit

[ just quit the editor at this point ]

| Editing complete.
| No edits were detected.
| Using alternate .taskrc file .taskrc
| task> next
| A configuration file could not be found in .
|
| Would you like a sample .taskrc created, so taskwarrior can proceed? (yes/no) no
| Using alternate .taskrc file .taskrc
| Cannot proceed without rc file.
| Segmentation fault (core dumped)

Using a fully qualified path as the argument to 'rc' works around this
crash but breaks my use case, i.e. being able to cd into an arbitrary
directory and run a 't' alias which is 'task rc:.taskrc'.
"""

SegvAnalysis:
 Segfault happened at: 0x4256ff <_ZN7Context8dispatchERSs+575>: mov (%rdi),%rax
 PC (0x004256ff) ok
 source "(%rdi)" (0x00000000) not located in a known VMA region (needed readable region)!
 destination "%rax" ok
SegvReason: reading NULL VMA
Signal: 11
SourcePackage: task
StacktraceTop:
 Context::dispatch(std::string&) ()
 Context::run() ()
 CmdShell::execute(std::string&) ()
 Context::dispatch(std::string&) ()
 Context::run() ()

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-05-01T21:53:18Z
Modified: 2014-02-09T02:04:40Z
```

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2012-05-01T21:54:44Z says:_ 

 I reproduced this on both Ubuntu's task 2.0.0.release, and also in the current task git tree on the 2.0.1 branch.

Attached is a more complete backtrace gathered while running on task.git.

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2012-05-01T21:56:28Z says:_ 

 Here's a patch that worked to stop the segfault.  It checks that the "help" command is registered before executing it.  Seems to work.

However I'm uncertain what return code should be done in this case.  Guessed -1 as something typical.

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2012-05-01T21:58:19Z says:_ 

 Here is the output when running with this fix:

task> 1 edit
Launching 'emacs -nw "task.31547.1.task"' now...
Editing complete.
No edits were detected.
Using alternate .taskrc file .taskrc
task> next
A configuration file could not be found in .

Would you like a sample .taskrc created, so taskwarrior can proceed? (yes/no) no
Using alternate .taskrc file .taskrc
Cannot proceed without rc file.
Using alternate .taskrc file .taskrc
Cannot proceed without rc file.
task> ls
A configuration file could not be found in .

Would you like a sample .taskrc created, so taskwarrior can proceed? (yes/no) no
Using alternate .taskrc file .taskrc
Cannot proceed without rc file.
Using alternate .taskrc file .taskrc
Cannot proceed without rc file.
task> 1
A configuration file could not be found in .

Would you like a sample .taskrc created, so taskwarrior can proceed? (yes/no) no
Using alternate .taskrc file .taskrc
Cannot proceed without rc file.
Using alternate .taskrc file .taskrc
Cannot proceed without rc file.
task> 


It appears something is still not quite right in this usage mode.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-14T03:59:57Z says:_ 

 Note sure if this is good news or bad.  I cannot replicate this on OSX or Ubuntu 11.10.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-06-10T20:48:29Z says:_ 

 Patch applied.  Thanks Bryce.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-07-01T18:52:27Z says:_ 

 The patch proposed by Bryce allows the shell to keep running, but it does not solve the bug.

Actually, the "edit" function changes directory at some point and does not restore the previous working directory at the end. This is fine when calling "edit" once, but it is a problem in shell mode.

Edit: there is a typo in the patch, I am sending the correct one on the support mailing list in order to avoid additional noise on this ticket.

**Comment by pbeckingham** [comment]
[TW-528_0001-Bug-1001.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755627/TW-528_0001-Bug-1001.patch.txt)
[TW-528_0001-Check-that-help-command-is-available-before-executin.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755628/TW-528_0001-Check-that-help-command-is-available-before-executin.patch.txt)
[TW-528_backtrace.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755629/TW-528_backtrace.txt)
[TW-528_ThreadStacktrace.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755630/TW-528_ThreadStacktrace.txt)
