### ISSUE TITLE
[TW-529] Sorting of holiday dates

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#564]
_Dirk Deimeke on 2012-02-06T13:15:18Z says:_ 

 Maybe it is a feature request, I don't know.

I set (at)calendar.holidays@ to (at)full@ and I would expect the Holiday dates to be sorted chronologically, when I do a (at)task cal@.

But the dates are sorted in order of occurence in the config file.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-02-06T13:15:18Z
Modified: 2014-02-09T02:04:40Z
```

**Comment by taskwarrior** [comment]
_Jörg Plate on 2012-05-23T12:15:01Z says:_ 

 This is a quick implementation of sorting the holidays before printing them.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-24T04:53:56Z says:_ 

 Patch applied.  Nice work.  Thanks Jörg.

**Comment by taskwarrior** [comment]
_Jörg Plate on 2012-05-26T14:41:41Z says:_ 

 Not nice enough. If you use multiple holiday sources sometimes the same day appears twice (or more :)

**Comment by taskwarrior** [comment]
_Jörg Plate on 2012-05-26T14:41:41Z says:_ 

 Attachment sort_holidays_2nd.patch has been added with description: Support multiple holidays for the same day.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-26T15:00:33Z says:_ 

 Jörg, Trailing whitespace problem, and it doesn't apply:

<pre>
$ git apply sort_holidays.patch
sort_holidays.patch:47: trailing whitespace.
      
error: patch failed: src/commands/CmdCalendar.cpp:361
error: src/commands/CmdCalendar.cpp: patch does not apply
</pre>

**Comment by taskwarrior** [comment]
_Jörg Plate on 2012-05-26T15:14:27Z says:_ 

 You have to reverse the first patch, my patches are relative to 2.0.0
(well, the current git version b19229b272c3bc6f14adf14515685be220725855)

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-26T16:35:31Z says:_ 

 Ah, I understand - all work is currently done on the 2.0.1 branch, which is why I can't apply it.

**Comment by taskwarrior** [comment]
_Jörg Plate on 2012-05-26T17:15:36Z says:_ 

 Switched to 2.0.1 and applied changes. Hopefully this will apply cleanly (it's the output of "git diff -u").

**Comment by taskwarrior** [comment]
_Jörg Plate on 2012-05-26T17:15:36Z says:_ 

 Attachment sort_holidays_4th.patch has been added with description: Multiple holidays per day.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-26T17:31:25Z says:_ 

 Perfect!  Patch applied cleanly.  Thanks Jörg.

**Comment by pbeckingham** [comment]
[TW-529_sort_holidays_2nd.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755631/TW-529_sort_holidays_2nd.patch.txt)
[TW-529_sort_holidays_3rd.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755632/TW-529_sort_holidays_3rd.patch.txt)
[TW-529_sort_holidays_4th.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755633/TW-529_sort_holidays_4th.patch.txt)
[TW-529_sort_holidays.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755634/TW-529_sort_holidays.patch.txt)
