### ISSUE TITLE
[TW-531] Dates in 'task information' are not formatted using dateformat.report

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#566]
_Louis-Claude Canon on 2012-04-21T15:46:26Z says:_ 

 The manual page indicates that dateformat.report formats the due date both in reports and "task info".

However, it appears that task info use dateformat (see Entered field and the journal entries):

<pre>
$ task add Task
$ task 1 info rc.dateformat.report:M/Y rc.dateformat:M

Name        Value                               
ID          1
Description Test                               
Status      Pending
Start       04                                  
UUID        11a8e1e2-dbe8-4bfc-ab1a-fbbe62f3408f
Entered     04 (3 mins)                         
Urgency     4

Date              Modification      
04                Start set to
                  '04'.
Total active time 0:02:53           

Configuration override rc.dateformat.report:M/Y
Configuration override rc.dateformat:M
</pre>

Obtained with the package task_2.0.0-0ubuntu2~oneiric2_i386.deb on Ubuntu 11.10.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-04-21T15:46:26Z
Modified: 2014-02-09T02:04:40Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-04-21T16:16:25Z says:_ 

 This should be a hierarchy:
1.  report.info.dateformat
1.  dateformat.report
1.  dateformat

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-04-21T17:03:48Z says:_ 

 Fixed.  Merci beaucoup Louis-Claude.  Your name is now in the AUTHORS file.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-04-28T15:48:35Z says:_ 

 Some possible improvements in the manual page.

For clarity, shouldn't report.info.dateformat be changed into dateformat.info as there is no other report.info.X variable (dateformat.report having then no impact on 'task info')?

Also, the date in journal entries when a task is started or stopped is only formatted by dateformat (for instance, when the entry is "Start set to '<date>').

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-04-28T22:11:49Z says:_ 

 Patch applied.  Thank you.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-04-30T07:19:13Z says:_ 

 I propose the following patch for the last mentioned issue about some date that are not formatted correctly. Unit tests are also added.

Regarding the suggestion about replacing the effect of report.info.X and of dateformat.report on the command 'info' by dateformat.info only, let me known your thought and I will propose patch(es).

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-04-30T12:56:57Z says:_ 

 I'm not sure about dateformat.info - take a look at what I did there, it might be adequate.  I am in favor of fewer special cases.

**Comment by pbeckingham** [comment]
[TW-531_0001-Update-man-page-relatively-to-the-fix-of-bug-986.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756158/TW-531_0001-Update-man-page-relatively-to-the-fix-of-bug-986.patch.txt)
[TW-531_0007-Bug-986.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756159/TW-531_0007-Bug-986.patch.txt)
