### ISSUE TITLE
[TW-533] Line breaking is strange with Chinese (double width) characters

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#568]
_Victor Roetman on 2012-04-10T08:55:55Z says:_ 

 I am running TaskWarrior 2.0.1 commit dd989be887a24d8ff059e429898bd296daff53e6 on Ubuntu 11.10 in gnome-terminal.
I have the following test data in task (please note that some entries have tags):
<pre>
$ task long

ID Project Pri Added    Started Due Recur Countdown Age Deps Tags      Description                                                               
 5             4/9/2012                 -           22h                five
 4             4/9/2012                 -           22h      something four                                                                      
 1             4/9/2012                 -           22h                one
 6             4/9/2012                 -           22h                six
16             4/9/2012                 -           22h                this is a longer one ???????? and another
20             4/9/2012                 -            1d                this is a longer one ???????? and another even
17             4/9/2012                 -           22h      work      this is a longer one ???????? and another longer with tags                
18             4/9/2012                 -           22h      work      this is a longer one ???????? and another longer with tags                
19             4/9/2012                 -           22h      work      this is a longer one ???????? and another longer with tags                
 3             4/9/2012                 -           22h                three
 2             4/9/2012                 -           22h                two
 7             4/9/2012                 -           22h                ??
 8             4/9/2012                 -           22h                ??
 9             4/9/2012                 -           22h                ??
14             4/9/2012                 -           22h                ?? five
13             4/9/2012                 -           22h      job       ?? four                                                                   
10             4/9/2012                 -           22h                ?? one
15             4/9/2012                 -           22h                ?? six
12             4/9/2012                 -           22h      work      ?? three                                                                  
11             4/9/2012                 -           22h                ?? two

20 tasks

</pre>

The problem happens when the window becomes narrower. Then the simple command task wraps the lines too early (because it adds a bunch of spaces at the end of the entries that have tags):
<pre>
$ task
[/home/vic/bin/task/bin/task next]

ID Project Pri Due A Age Urgency Description                                                               
 4                   22h     0.8 four                                                                      
17                   22h     0.8 this is a longer one ???????? and another longer with tags                

18                   22h     0.8 this is a longer one ???????? and another longer with tags                

19                   22h     0.8 this is a longer one ???????? and another longer with tags                

13                   22h     0.8 ?? four                                                                   

12                   22h     0.8 ?? three                                                                  

20                    1d 0.00548 this is a longer one ???????? and another even
 5                   22h       0 five
 1                   22h       0 one
 6                   22h       0 six
16                   22h       0 this is a longer one ???????? and another
 3                   22h       0 three
 2                   22h       0 two
 7                   22h       0 ??
 8                   22h       0 ??
 9                   22h       0 ??
14                   22h       0 ?? five
10                   22h       0 ?? one
15                   22h       0 ?? six
11                   22h       0 ?? two

20 tasks
</pre>

In an even narrower window, then it gets really messy, and the headers flow out of the window:

<pre>
                                 longer with tags                             
19                   22h     0.8 this is a longer one ???????? and ano
ther    
                                 longer with tags                             
13                   22h     0.8 ?? four                                      

12                   22h     0.8 ?? three                                     

20                    1d 0.00548 this is a longer one ???????? and ano
ther
                                 even
 5                   22h       0 five
 1                   22h       0 one
 6                   22h       0 six
16                   22h       0 this is a longer one ???????? and ano
ther
 3                   22h       0 three
 2                   22h       0 two
 7                   22h       0 ??
 8                   22h       0 ??
 9                   22h       0 ??
14                   22h       0 ?? five
10                   22h       0 ?? one

20 tasks
</pre>

Item 20 does not have a tag (so no spaces at the end of the line) but does not wrap properly.

In my terminal each Chinese character takes the space of two roman characters, so I am sure that is part of why the line breaking calculations are off. With Chinese characters at least, lines are not broken on spaces because they don't separate words, but the line can be broken in the middle of the string of characters when they fill up the line. Japanese and Korean usually work the same way. There are other Unicode Characters (such as diacritics) that take no space that might also affect the line length calculations.

I found the following stackoverflow question that may be helpful: [[http://stackoverflow.com/questions/3634627/how-to-know-the-preferred-display-width-of-unicode-characters]].

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-04-10T08:55:55Z
Modified: 2014-02-09T02:04:40Z
```

**Comment by taskwarrior** [comment]
_Victor Roetman on 2012-04-10T09:03:56Z says:_ 

 The preview worked fine when I typed all this in (meaning it all worked within the browser). But when I viewed it after it was saved, all the Chinese characters became question marks which indicates an encoding problem, probably translating the Unicode to something like Latin-1.  What kind of bug system are you using that it isn't storing Unicode in the database? This is already 2012, and it's a global world. We should be using Full Unicode in everything by now.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-04-14T19:58:59Z says:_ 

 Could be deferred to 2.1.0 if it proves problematic, but I would like to try and fix it soon.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-28T17:34:19Z says:_ 

 The Markus Kuhn code has the right license, so we'll try and adapt it.

**Comment by taskwarrior** [comment]
_Jörg Plate on 2012-05-28T23:37:59Z says:_ 

 This is a patched version of wcwidth.c. It's now with unicode 6.1 data instead 5.0.
(I'm reasonably sure that it's correct... handle with care)

**Comment by taskwarrior** [comment]
_Jörg Plate on 2012-05-28T23:37:59Z says:_ 

 Attachment wcwidth6.c has been added with description: Updated to Unicode 6.1.0

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-07-15T04:16:50Z says:_ 

 Fixed.  Thanks for the bug Victor, and for the updated code Jörg.

**Comment by pbeckingham** [comment]
[TW-533_wcwidth6.c.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756160/TW-533_wcwidth6.c.txt)
