### ISSUE TITLE
[TW-537] dateformat and dateformat.annotation must be the same when editing annotations

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#572]
_Louis-Claude Canon on 2012-04-21T15:34:54Z says:_ 

 Setting distinct strings for dateformat and dateformat.annotation prevents from changing the annotation with an editor:

<pre>
$ task add Test
Created task 1.
</pre>

<pre>
$ task 1 annotate Example
Annotating task 1 'Test'.
Annotated 1 task.
</pre>

<pre>
$ task rc.dateformat:d/m rc.dateformat.annotation:d/m/Y 1 edit # Change "Example" into "Test"
Launching 'vi "task.9696.1.task"' now...
Editing complete.
Edits were detected.
Error: '21/4' is not a valid date in the 'd/m/Y' format.
Taskwarrior couldn't handle your edits.  Would you like to try again? (yes/no)
</pre>

Obtained with the package task_2.0.0-0ubuntu2~oneiric2_i386.deb on Ubuntu 11.10.

**Comment by pbeckingham** [comment]
[TW-537_0005-Bug-985.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756161/TW-537_0005-Bug-985.patch.txt)
