### ISSUE TITLE
[TW-538] Automatic completion of 'des' in description and annotation

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#573]
_Louis-Claude Canon on 2012-05-05T16:47:06Z says:_ 

 The string 'des' gets automatically replaced by 'description' in descriptions and annotations with the following (obtained with the latest git revision):
<pre>
$ task add des
$ task 1 annotate des
</pre>

It appears that the problem is solved when DOM identification is deactivated when extracting the modifiers (see the proposed patch). As my understanding of the complete parsing mechanism is rather limited, I could not come with a correct solution. I made however a list of observations that could be useful:
* The code with variable 'downgrade' seems to be never used (this code is marked in the patch). The provided example does not lead to the expected behaviour.
* when calling 'tokenize' in 'extract_modifiers', the second character '1' is parsed as cat_id in the command 'task 1 mod 1' (but it changes the description of task 1 as '1'), whereas the last id is parsed as a cat_literal in 'task 1 mod 1 test 1'.

I provide some tests that are supposed to pass.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-05-05T16:47:06Z
Modified: 2014-02-09T02:04:40Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-05T18:15:56Z says:_ 

 I renamed bug.completion.t to bug.1006.t and committed.

Regarding the 'des' expansion patch, I don't want to achieve this by disabling DOM expansion, so I'm holding off on the patch for now, while I think about it.

Thank you!

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-05-05T19:05:42Z says:_ 

 You are welcome. I forgot to mention the context: 'des' is a common French determiner (equivalent to 'the').

The patch provides indeed merely a hint for identifying the problem. However, I was not able to characterise a test case that is disabled by the proposed patch (all tests are passing with it).

**Comment by taskwarrior** [comment]
_Bruno Bigras on 2012-05-08T14:18:26Z says:_ 

 This problem also arise with 'un' (equivalent to 'one') which get auto completed to 'until'.

And with 'entrée' (equivalent to 'entry') which get translated to 'entry ée'.

**Comment by taskwarrior** [comment]
_Richard Boß on 2012-05-31T13:23:32Z says:_ 

 In general every short word could be bitten by this bug - if a column word starts with the same letters. As a native German speaker I see this effect predominantly with two words: 'des' and 'im'. The word 'des' is an article in the genitive form: "the eye of the tiger" = "das Auge des(cription) Tigers". The word 'im' is a widely used praeposition: "milk is in the fridge" = "die Milch steht im(ask) Kühlschrank".

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-07-04T20:09:06Z says:_ 

 Code was also supposed to transmute 'des:' --> 'description:', not 'des' --> 'description'.

**Comment by pbeckingham** [comment]
[TW-538_0001-Disable-tokenizing-DOM-when-extracting-the-modifiers.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756162/TW-538_0001-Disable-tokenizing-DOM-when-extracting-the-modifiers.patch.txt)
[TW-538_bug.completion.t.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756163/TW-538_bug.completion.t.txt)
