### ISSUE TITLE
[TW-544] Stop increasing 'Total active time' when a task is done

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#579]
_Louis-Claude Canon on 2012-04-22T09:57:18Z says:_ 

 The value 'Total active time' returned by 'task info' continues to increase when a task have been done without being stopped:

<pre>
$ task add Test
Created task 41.
$ task 1 start
Starting task 1 'Test'.
Started 1 task.
$ task 1 done
Completed task 41 'Test'.
Completed 1 task.
$ task 9c47cff1 info | grep "Total active time"
Total active time 0:00:19
$ task 9c47cff1 info | grep "Total active time"
Total active time 0:00:21
</pre>

It would be nice if 'task done' automatically call 'task stop' before, or if the computation of 'Total active time' considers the duration between 'start' and ('stop' or 'done'). This could be useful for statistical reports for instance.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-04-22T09:57:18Z
Modified: 2014-02-09T02:04:41Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-04-22T12:34:10Z says:_ 

 Good find.  Thank you.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-04-24T09:51:43Z says:_ 

 The patch counts between start and either stop or completion.

I guess the tests should make sure that the Total active time is a relevant value (close to zero) and a constant one in the following situations:
* task <id> start; task <id> done
* task <id> start; task <id> stop; task <id> done
* task <id> done; task <id> start (shouldn't this be forbidden?, the current fix does not work in this situation)
* task <id> done; task <id> stop

The counter must be equal to zero for 'task <id> done (no start)' and the counter must be running when the task is active and not completed ('task <id> start').

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-04-24T09:59:44Z says:_ 

 Oups, parenthesis problem. Sorry for the noise.

**Comment by pbeckingham** [comment]
[TW-544_0001-Fixed-bug-987.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756164/TW-544_0001-Fixed-bug-987.patch.txt)
[TW-544_0003-Fixed-bug-987.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756165/TW-544_0003-Fixed-bug-987.patch.txt)
