### ISSUE TITLE
[EX-64] rename UDA

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#58]
_Aikido Guy on 2012-08-04T22:21:14Z says:_ 

 Similar to _rename project_ (http://taskwarrior.org/projects/taskwarrior/wiki/Ck3), I would like to be able to rename my own user defined attribute (UDA) and have taskwarrior do all of the right things (change .taskrc etc)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-08-04T22:21:14Z
Modified: 2015-03-14T15:49:25Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-08-17T03:18:43Z says:_ 

 So this would involve search & replace on ~/.taskrc and ~/{pending,completed}.data?

<pre>
perl -p -i -e 's/uda\.foo/uda\.bar/' ~/.taskrc
perl -p -i -e 's/ foo:"/ bar:"/' ~/.task/{pending,completed}.data
</pre>

If it is just two lines it seems like an ideal external script candidate.

**Comment by pbeckingham** [comment]
No plans to implement.
