### ISSUE TITLE
[TW-553] ChangeLog typos

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#588]
_Bryce Harrington on 2012-05-01T21:42:39Z says:_ 

 Two minor misspellings in ChangeLog.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-05-01T21:42:39Z
Modified: 2014-02-09T02:04:41Z
```

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2012-05-01T22:11:23Z says:_ 

 Thanks.

**Comment by pbeckingham** [comment]
[TW-553_0001-A-couple-minor-typo-fixes-to-ChangeLog.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756168/TW-553_0001-A-couple-minor-typo-fixes-to-ChangeLog.patch.txt)
