### ISSUE TITLE
[TW-557] recurrent weekly task got replicated thousands of times

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#592]
_Stanley G on 2012-06-11T20:22:48Z says:_ 

 I have TaskWarrior v2.0.0 running on Fedora15 Linux OS. I had a recurring task scheduled to recur weekly on Fridays. When I ran "task list" command today I saw it flooding my screen with thousands of entries of this task and I had to break out with CTRL+C (see bug-01.jpg attached screenshot). This would freeze up even the other task commands due to too many entries to process and there was a lot of lag running TaskWarrior overall. It was task ID #56 (the lowest ID #) called "clarity" so I ran "task 56 info" command (screenshot is called bug-02.jpg). I also ran "cat pending.data" and this file was huge as a result flooded with this task replicated many times (screenshot is calleed bug-03.jpg). Now I ran "task 56 delete" then said "yes" to delete all recurring tasks like this one and as it was deleting it got from ID #56 to ID #15173 and at this point my shell and OS froze and I was running it as a virtual machine using VMWare Workstation (screenshot bug-04.jpg). I rebooted the OS and now I see that none of these tasks got deleted at all. I see that this task ID range is from #56 through #60749 with "task list" command which doesn't freeze the OS for me but shows all its output even though pretty lengthy. I tried the "task 56 delete" again and my OS froze at ID#15234 I made a backup of pending.data, completed.data, undo.data, and .taskrc files in case you need them just email me.

I just found a workaround for this issue to cleanup the TaskWarrior not to lose any of my regular non-recurring data. I used "vi pending.data" and deleted all these 60,000+ replicated flooding tasks manually there inside this file (it was easy as they were at the end of the file pretty much with a few other recurring tasks in between). Then to be on the safe side I also deleted all my other recurring events from TaskWarrior at least until this bug is fixed. I also did "> undo.data" to null this file as it was like 40MB and that would be inefficient for my periodic backups. TaskWarrior is fast again, all recurring tasks are gone, and everything looks good again.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-06-11T20:22:48Z
Modified: 2014-02-09T02:04:41Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-06-11T21:00:15Z says:_ 

 This is a duplicate of #972

Stanley, thank you for the report, and apologies for the inconvenience caused by this bug.  The problem (from looking at your screen shots) is probably this:

You created a recurring task with a recurrence of "5", which translates into "5 seconds".  You probably meant days ("5days").  The corrective measures you took were perfect.  This will be addressed in the (coming soon) 2.0.1 release.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-07-08T18:25:41Z says:_ 

 A recurrence without units is now an error.

**Comment by pbeckingham** [comment]
![tw-557_bug-01](https://user-images.githubusercontent.com/7963/36637297-6d83e484-19a7-11e8-91f8-b2ecfe1366df.png)
![tw-557_bug-02](https://user-images.githubusercontent.com/7963/36637298-6d98e91a-19a7-11e8-8929-0b7a16bfa3c9.png)
![tw-557_bug-03](https://user-images.githubusercontent.com/7963/36637299-6dab4b50-19a7-11e8-8d55-4fb573d8a75b.png)
![tw-557_bug-04](https://user-images.githubusercontent.com/7963/36637300-6dbb42b2-19a7-11e8-8053-1708308d1a06.png)
