### ISSUE TITLE
[TW-560] default dateformat means lost information in 'task edit'

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#595]
_Nicholas Lamb on 2012-03-31T20:50:16Z says:_ 

 By default dateformat seems to be m/d/Y, but this means that the task's created timestamp (which includes times not just dates) is damaged by re-reading the value after an edit even though the user didn't touch the created date when editing. So a task created just 15 seconds ago, and then briefly edited to fix a typo, is suddenly hours old (unless dateformat has been configured to include time).

Not quite sure what the best way to fix this is though.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-03-31T20:50:16Z
Modified: 2014-02-09T02:04:41Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-04-07T02:55:14Z says:_ 

 Workaround: Try changing your dateformat to include time.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-04-30T07:14:10Z says:_ 

 The following patch solves this bug but not Bug #705. Instead of checking if a date in its epoch representation has changed, 'task edit' checks if a date has changed in its 'dateformat' representation.

The drawback is that it is not possible to edit finely date if dateformat does not include seconds. As editing can be viewed as the tool for such fine modifications, I suggest the following feature (and I volunteer to propose patches, just let me know if this is what you want): adding a dateformat.edit (or edit.dateformat) variable, which would be set by default to 'm/d/Y H:N:S' so that the all the dates showed when editing are precise.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-04-30T12:13:34Z says:_ 

 Patch applied.

**Comment by pbeckingham** [comment]
[TW-560_0006-Bug-959.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756169/TW-560_0006-Bug-959.patch.txt)
