### ISSUE TITLE
[TW-562] Deprecated 'annotations' check

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#597]
_Louis-Claude Canon on 2012-04-24T09:36:07Z says:_ 

 The 'annotations' field is not set by default in the current revision, which makes the check fail with 'task show'. The check could be entirely removed. Note also that for each deprecated field, 'task show' reports that the variable and unrecognised and deprecated.

The test should probably check that the output of the following command in empty:

<pre>
task show | grep error
</pre>

Finally, the documentation seems to be incomplete on this:
* the tutorial man page propose to use 'task rc.annotations:full list'
* the taskrc man page does not mention annotations and the 'report.X.annotations' (as well as report.X.limit) is said to be deprecated without replacement suggestion (description.{default,desc,combined,online,count,truncated} for report.X.columns field)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-04-24T09:36:07Z
Modified: 2014-02-09T02:04:42Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-04-25T03:47:49Z says:_ 

 Skipping the tests, because I don't want to get in the habit of testing for the absence of features.

**Comment by pbeckingham** [comment]
[TW-562_0003-Allow-annotations-to-be-undefined-as-it-is-deprecate.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756171/TW-562_0003-Allow-annotations-to-be-undefined-as-it-is-deprecate.patch.txt)
