### ISSUE TITLE
The diag command crashes if a hook script is a broken symlink

### ISSUE THREAD

**Issue by pbeckingham** [GothenburgBitFactory/taskwarrior#6]
The diag command tries to determine execute permission on a broken symlink and this crashes.  This may require a libshared/src/FS.cpp change, or at a minimum just the diag command.

Reproduce with:

    $ cd ~/.task/hooks/
    $ ln -s /missing on-add.missing
    $ task diag

**Comment by mrossinek** [comment]
When I try to reproduce this issue in the fashion how @pbeckingham describes it, the `task diag` command does not crash. It rather reports:
```
Inactive: on-add.missing        (not executable) (symlink)
```
(Running task 2.5.1)

**Comment by felixschurk** [comment]
Also on the current taskwarrior release task 3.1.0 is is no longer crashing.

Therefore, I would close this issue as its not reproducible at the moment or working.
