### ISSUE TITLE
[EX-66] pass subject line of email to taskwarrior as command, receive taskwarrior output in reply

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#60]
_Steven Siebe on 2015-04-20T12:43:10Z says:_ 

 Being able to interact with Taskwarrior over email would be a huge benefit. I can’t install command line apps on every computer I use, or access a command line from my phone or tablet. However, pretty much every device I use has an email client. 

Currently if I’m in a meeting, or away from my desk, I email myself tasks to copy+paste into the command line when I get the opportunity. It’s not optimal. and it’s only a one-way communication. If I’m at the grocery store shopping, I can’t see what else is on my list unless I’ve written it down. If I could instead just email myself “task list pro:groceries” that would be infinitely more useful. I realize there are web-app clients. I’ve found them very limiting with needing to build a UI, and things not being arranged how I might expect, or not having fields I want to enter data into. 

Passing a command from the subject line of an email to taskwarrior, and getting a reply with the output from taskwarrior would be fantastic. Ideally, this would be a third party email account, somewhere like yahoo and gmail, leaving nothing new to be configured within taskwarrior other than the login/password information to be able to check that address. 

Not only could you send emails back and forth with taskwarrior, you could also get reminders emailed to you. This mode of interaction would also save people from needing to open a port in their firewall, if previously they only used SSH to get into their computer at home to utilize taskwarrior.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2015-04-20T12:43:10Z
Modified: 2015-05-02T17:26:21Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-04-21T10:53:39Z says:_ 

 I have moved this issue to the 'Extension' project, which simply acknowledges that this is not a Taskwarrior feature.

What you are describing here is a client-side mailbot.  Several mail clients have this ability built-in, to call out to external scripts when certain email message patterns were recognized, and this could be a solution, requiring a program to extract the information and enter it into taskwarrior.

A more general solution is as you describe, where a standalone service monitors all email for taskwarrior directives, then acts accordingly.  This would then be independent of the mail client.  I have a prototype for this, which may be worth revisiting.

**Comment by taskwarrior** [comment]
_Steven Siebe on 2015-04-21T11:32:59Z says:_ 

 I'm sorry I posted in the wrong section. 

And yes, you're right. It does seem kind of like a mailbot. Several of the extensions I looked at perform the function of turning a message into a new task (inthe.am, TaskWarriorMail, mail2taskwarrior), but those are all one-directional as far as I can tell. Taskjabb bi-directional, and is almost what I'm after but after trying it for a few days wasn't reliable and had to be restarted constantly, along with that, the code doesn't seem to be maintained. If it only looked for mail from a whitelisted address, you wouldn't have to worry about parsing the inbox for emails with tw commands. Maybe this could fit alongside tw sync? It might also work as a cron job. I already run 'task sync' every hour to make sure my daily recurring tasks get synced back into mirakel. Not optimal, but it works. If it was a called in a similar way (could be scheduled by the user for every 30 seconds for example), instead of being service that was always running, that might work as well.

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-05-02T17:26:21Z says:_ 

 Since you mentioned taskjabb, have you given https://gist.github.com/wbsch/4109562 a try? Seemed to be pretty reliable back when I tried it, but I haven't used it since writing it. It might make for a nice base to build on though.

**Comment by pbeckingham** [comment]
No plans to implement.
