### ISSUE TITLE
[TW-570] [RFE PATCH] Add deferred priority

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#605]
_Jeff Schroeder on 2012-04-25T17:17:52Z says:_ 

 In my own task management style, I have tasks with these priorities:
*  High
*  Medium
*  Low
*  Deferred

Speaking with Paul on IRC, he mentioned that I could delete and annotate a task that I'm not doing now, but might do in the future. This sort of works in that I can cd into ~/.task and revive it, but is suboptimal. I also understand that "sort of high" and "sort of low" are also valid tasks. Taskwarrior isn't meant to be infinitely flexible or configurable, but I see "Deferred" as a top level priority vs an "in-between" one such as "sort of high".

Often times at work, I'll be working on a project and then it will block on someone else for a month or two. That project is in a deferred state. Note that this patch might be wrong as I've not written a single line of anything in C++ in the past 11 years, but it works for me. The error message, priority, sorting, and coloring was correct. In my colorscheme theme file (/usr/share/doc/task/rc/dark-blue-256.theme) I added color.pri.D=rgb012 Screenshot:
http://www.digitalprognosis.com/pics/taskwarrior.png

So... thusfar, this has been a great community, and one that I look forward to helping contribute to in the future. I hope this measly feature was integrated correctly and to the tw team's standards. Note that it is also available for the 'master' and '2.0.1' branches on my github: https://github.com/SEJeff/task

Same patch applies cleanly to both. If this patch is integrated, I'll send more for the theme files.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-04-25T17:17:52Z
Modified: 2014-02-09T02:04:42Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-04-27T04:08:40Z says:_ 

 As discussed.

**Comment by pbeckingham** [comment]
[TW-570_0001-Add-D-for-a-deferred-priority.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756172/TW-570_0001-Add-D-for-a-deferred-priority.patch.txt)
