### ISSUE TITLE
[TW-573] task effort

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#608]
_Peter De Poorter on 2010-11-20T04:38:45Z says:_ 

 When the preparation of a project is made one frequently wants to know, in a very early stage, an answer
on the following questions:
*  what will be the total effort ?
*  what will be the cost ?
*  how long will it take ? What will be the duration ?

During the project one wants to be able to follow up the actual spended effort, duration and cost.

The goal of this feature request is to investigate how task can help answering these questions. 

For more info see the attached document

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-11-20T04:38:45Z
Modified: 2014-02-09T02:04:42Z
```

**Comment by taskwarrior** [comment]
_Peter De Poorter on 2010-11-20T04:38:45Z says:_ 

 Attachment rfc33-effort.txt has been added with description: rfc33-effort.txt

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-01-09T15:26:11Z says:_ 

 Might be related to user-defined attributes.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-08-24T03:39:11Z says:_ 

 This might be satisfied completely with http://tasktools.org/gitweb/gitweb.cgi?p=rfc.git;a=blob_plain;f=rfc34-uda.txt;hb=HEAD

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-09-14T05:14:32Z says:_ 

 Requires user defined attributes.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-13T22:54:45Z says:_ 

 This will be supported via UDAs.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-07-03T02:27:37Z says:_ 

 Supported by UDAs.  Documentation coming soon.

**Comment by pbeckingham** [comment]
[TW-573_rfc33-effort.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756173/TW-573_rfc33-effort.txt)
