### ISSUE TITLE
[EX-67] scheduled and until as filters in task list and calendar view

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#61]
_Marek Konopka on 2013-04-19T08:27:44Z says:_ 

 Scheduled and until are great additions but for now they useless. I'd like to filter task scheduled for a specific day or a range of days and also I'd like to see scheduled column in reports. The same with Until. Also it would be great if scheduled and until were present in the calendar view. It could be implemented the way that if until is set to the same day as scheduled then it has scheduled color and if until is set to later day then all days from scheduled to until are marked with color of until.
These features would make of taskwarrior a great planner and it would be then possible to create weekly or monthly view of tasks.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-04-19T08:27:44Z
Modified: 2015-09-01T23:28:27Z
```

**Comment by taskwarrior** [comment]
_Dirk Deimeke on 2013-04-19T08:57:47Z says:_ 

 You can do that on your own with a customized report:

Add the follwing lines to your .taskrc
<pre>
report.xyz.columns=id,project,priority,description,scheduled,until
report.xyz.description=Minimal listing of all pending tasks with scheduled and until
report.xyz.filter=status:pending
report.xyz.labels=ID,Proj,Pri,Description,Scheduled,Until
report.xyz.sort=priority-,project+
</pre>

And call (at)task xyz@.

If you want to see tasks scheduled after a specific date, do "task xyz scheduled.after:DATE" (with DATE being the date as in your date format).

**Comment by taskwarrior** [comment]
_Marek Konopka on 2013-04-19T13:10:01Z says:_ 

 You're right, my bad and thanks. What's left is indication of scheduled and until on calendar view. Also if it's possible to change until's default behavior to set task as done and not delete it.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-09-01T23:28:27Z says:_ 

 This is an ideal extension script feature - a planner report.

**Comment by pbeckingham** [comment]
Extensions are not our business.
