### ISSUE TITLE
[TW-582] Suppress multiple occurences of same holiday

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#617]
_Jörg Plate on 2012-05-04T18:47:58Z says:_ 

 1> task rc.calendar.holidays=full cal
[..]
6/7/2012  Fronleichnam
6/7/2012  Fronleichnam
6/7/2012  Fronleichnam
[..]

(it's a region based holiday)

This output is ugly, therefore I made a q'n'd patch for "update-holidays.pl"

Apply the patch, run "scripts/add-ons/update-holidays.pl --locale de-DE --file holidays.de-DE.rc"
(no idea if other calendars have the same feature).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-05-04T18:47:58Z
Modified: 2014-02-09T02:04:43Z
```

**Comment by taskwarrior** [comment]
_Jörg Plate on 2012-05-04T18:47:58Z says:_ 

 Attachment update-holidays.patch has been added with description: add description/date to content only once

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-07T22:40:43Z says:_ 

 Thank you Jörg!

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-05-07T22:45:11Z says:_ 

 Patch applied.  Thank you.

**Comment by pbeckingham** [comment]
[TW-582_update-holidays.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756174/TW-582_update-holidays.patch.txt)
