### ISSUE TITLE
[EX-68] import-todo.sh.pl forgets , between entities / breaks json format

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#62]
_xkbc on 2016-03-28T14:53:47Z says:_ 

 import-todo.sh.pl forgets , between entities / breaks json format, so that task cant import the broken json file. Task answers with a not really fitting message: 

      Error: missing ']' at position 1

Dirty workaround:

Change line 123 to (just add the missing comma):

     $json .= ",\"description\":\"${description}\"},";

and then remove via editor manually the last comma before the last closing ]. After that task can import.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2016-03-28T14:53:47Z
Modified: 2016-03-28T14:53:47Z
```

**Comment by pbeckingham** [comment]
No plans to implement.
