### ISSUE TITLE
[TW-585] bold only respects "named" colors

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#620]
_Stefan Keel on 2011-05-02T21:56:36Z says:_ 

 Found in v1.9.4 while tweaking colors:

color.tagged=bold color12 will change the color to color12, but won't be bold.
color.tagged=bold rgb123 has same affect as colorN.
color.tagged=bold blue will both change the color to "blue" and make it bold.

This only seems to affect the bold setting.

color.tagged=underline color12 has the expected results.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-05-02T21:56:36Z
Modified: 2014-02-09T02:05:27Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-02T22:45:30Z says:_ 

 Take a look at "man task-color".  "Bold" is only meaningful with 16 colors.  Once you start using 256, bold becomes meaningless.

**Comment by Rahlir** [comment]
I am not sure what is the current status and usage of `libshared` in taskwarrior with the taskchampion rewrite, however there seems to be no reason to have `bold` attribute apply only for 16 color space. It's perfectly valid to use bold with the 256 color escape codes (at least with modern terminals, maybe there is an exception for old `TERM`s?)

**Comment by djmitche** [comment]
`libshared` is still there, largely unchanged by the work to integrate taskchampion.
