### ISSUE TITLE
[TW-588] uuid_unparse_lower doesn't exist in Solaris uuid/uuid.h

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#623]
_Owen Clarke on 2011-06-28T02:38:39Z says:_ 

 libuuid is found by cmake and so HAVE_UUID is defined, but uuid_unparse_lower doesn't exist in the Solaris libuuid.
uuid/uuid.h does contain uuid_unparse, so I changed the implementation of uuid() in util.cpp to use uuid_unparse and convert to lower-case using std::transform if SOLARIS is defined.

I'm not sure if what I've done is correct or if CMake shouldn't set HAVE_UUID if libuuid is found but uuid_unparse_lower doesn't exist and thus use the built-in uuid implementation. It seems it assumes uuid_unparse_lower exists if libuuid exists.

I've patched util.cpp to ifdef SOLARIS and use my change, but it's possible uuid_unparse_lower could not exist on other platforms that have libuuid.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-06-28T02:38:39Z
Modified: 2014-02-09T02:06:29Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-06-28T03:01:08Z says:_ 

 Done, pushed.  Thanks.

**Comment by taskwarrior** [comment]
_Owen Clarke on 2011-06-28T03:12:43Z says:_ 

 Already closed, but I was thinking, looking at this forum post: http://taskwarrior.org/boards/1/topics/1412, that maybe it should be an "#ifndef DARWIN" instead of "#ifdef SOLARIS" if it's only available in OSX. I don't know what's available on other platforms like Linux, but I could try it out later today on Ubuntu and OSX.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-06-28T03:19:05Z says:_ 

 Good point.  I think you're right.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-06-28T03:19:25Z says:_ 

 Re-opening bug

**Comment by taskwarrior** [comment]
_Owen Clarke on 2011-06-29T13:48:15Z says:_ 

 So, in OS X, Apple includes libuuid as part of their libc and no includes or linking needs to be added. Other architectures have the uuid functions in the separate libuuid but some have older implementations that don't include uuid_unparse_lower, such as Solaris/OpenIndiana (and apparently CentOS 4.2).

I've added an extra define (HAVE_UUID_UNPARSE_LOWER) that util.h/util.cpp use to implement uuid_unparse_lower if it doesn't exist. CMakeLists.txt checks the system type earlier and uses this to test if the arch is Darwin when looking for libuuid. If it is Darwin, HAVE_UUID is set to true and uuid_unparse_lower is looked for. Otherwise libuuid and uuid_unparse_lower are looked for normally.

I've tested this patch ('cmake .', 'make') on:
*  OS X 10.6 (libuuid built-in)
*  Ubuntu 10.10 (libuuid with uuid_unparse_lower from libuuid1 and uuid-dev, as well as no libuuid by removing uuid-dev)
*  OpenIndiana b148 (libuuid without uuid_unparse_lower from SUNWcsl and SUNWhea).

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-06-30T02:42:22Z says:_ 

 Nice patch.  Thank you.

**Comment by pbeckingham** [comment]
[TW-588_task-uuid.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756175/TW-588_task-uuid.patch.txt)
[TW-588_util.cpp.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756176/TW-588_util.cpp.patch.txt)
