### ISSUE TITLE
[TW-589] There are some misprints in holidays-UK.rc

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#624]
_Alexei Romanoff on 2011-03-19T15:42:29Z says:_ 

 When I was creating holidays for my home country I noticed some strange behavior of task:
<pre>
$ task rc.calendar.holidays:full cal
Configuration override calendar.holidays:full
"" is not a valid date (Y).  Expected format 'YMD'
</pre>

After short analyzing I've discovered a little but in holidays-UK.rc. Some holiday dates were not set.
See the attached patch.

It is needed to set option `include /path/to/task/srcdir/doc/rc/holidays-UK.rc` in ~/.taskrc for reproducing this bug. 

I think task should print correct error message in this situation. Something like "holiday.eastermonday.date has invalid value '' in rc-file /path/to/task/srcdir/doc/rc/holidays-UK.rc". Is this possible?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-03-19T15:42:29Z
Modified: 2014-02-09T02:06:29Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-03-19T16:34:16Z says:_ 

 Thank you Alexei.

**Comment by pbeckingham** [comment]
[TW-589_0001-Fixed-misprints-in-UK-holidays.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756178/TW-589_0001-Fixed-misprints-in-UK-holidays.patch.txt)
