### ISSUE TITLE
[TW-595] task hangs with growing memory usage

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#630]
_Uli Martens on 2012-01-16T18:15:31Z says:_ 

 when trying to add a dependency to tasks, the programm hangs. I've not yet figured out when task falls into an seeminly endless loop, but it happens for some tasks but not for others. Sadly I can't provide neither a minimal example nor my task data as they contain private data, but perhaps the following is enough:

<pre>
youam(at)riona:~$ strace -f task 84 85 88 modify dep:289
[...]
read(5, "2570044\" project:\"freelance\" sta"..., 8191) = 8191
read(5, "mpleted\" uuid:\"713550de-5e06-47c"..., 8191) = 8191
read(5, "aca1b4ac\" recur:\"monthly\" status"..., 8191) = 8191
read(5, "57de-0254579b4ef2\" recur:\"monthl"..., 8191) = 2266
read(5, "", 8191)                       = 0
close(5)                                = 0
brk(0x1286000)                          = 0x1286000
brk(0x12a7000)                          = 0x12a7000
brk(0x12c8000)                          = 0x12c8000
brk(0x12e9000)                          = 0x12e9000
brk(0x130a000)                          = 0x130a000
brk(0x132b000)                          = 0x132b000
^C--- SIGINT (Interrupt) @ 0 (0) ---
1:youam(at)riona:~$ task add test1
Created task 290.
youam(at)riona:~$ task add 2
Created task 291.
youam(at)riona:~$ task 290 modify dep:291
Modifying task 290 'test1'.
Modified 1 task.
youam(at)riona:~$ 

</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-01-16T18:15:31Z
Modified: 2014-02-09T02:06:29Z
```

**Comment by taskwarrior** [comment]
_Uli Martens on 2012-01-16T18:18:44Z says:_ 

 d'oh. Just after commiting this bug report, I ran  (at)task info@ on the older tasks. All of them had a dependency on the invalid task "0". After editing all of my input tasks 84, 85, 88 and removing this invalid dependency (which was autogenerated somehow), I can add a new dependency on 289 without problems.

**Comment by taskwarrior** [comment]
_Uli Martens on 2012-01-22T20:31:35Z says:_ 

 I've found a way to trigger this bug (or one which is related to it).

Starting with an empty task database, import the following:
<pre>
{"due":"20111230T230000Z","entry":"20111206T122302Z","status":"pending","id":1,"description":"uuid 84aea9d9-2c64-4d5c-b4dc-13a45d198b61","uuid":"84aea9d9-2c64-4d5c-b4dc-13a45d198b61","depends":"23d2f2ca-2e63-45ae-8406-9cc698d329b2"},
{"entry":"20111206T123220Z","status":"pending","description":"uuid 23d2f2ca-2e63-45ae-8406-9cc698d329b2","uuid":"23d2f2ca-2e63-45ae-8406-9cc698d329b2","id":2,"depends":"39a04a66-b168-4f69-8a03-eedfd11940a5,ca528757-87f0-4f83-a782-9c035bb7c9c3"}
</pre>

then run (at)task 1 edit@, in the editor delete the due date, save & exit. task reports:
<pre>
Editing complete.
Edits were detected.
</pre>

and hangs. Editing the task on the command line seems to work fine some times, and not for other commands: (at)task 1 modify due:tomorrow@ works, (at)task add three ; task 3 modify dep:1@ hangs on the modify/. Removing the (unfullfilled) dependencies of task 2 also seems to make the bug disappear. Running a small check tool against my full task database tells me that this full database does NOT have dependencies on non-existant tasks, but it does hang on some actions.

**Comment by taskwarrior** [comment]
_Uli Martens on 2012-01-22T20:36:46Z says:_ 

 Btw, if you try to reproduce the above, kill the hanging process after a while or ulimit it to something. If you let it run unlimited, it will eat all your available memory (and then some more)

**Comment by taskwarrior** [comment]
_Uli Martens on 2012-01-23T09:34:27Z says:_ 

 got it. the problem was that the routine dependencyIsCircular() changed its behaviour in git revision 726fc33fe4ae26801b566fe85404935e7ee0529d, and the new version only checked tasks by id - but *all* completed/deleted tasks have the id0, which let to the problem. the fix is extremelly simple, just get the dependencies by uuid instead of by id. attached patch fixed the problem for me.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-01-23T11:27:38Z says:_ 

 Patch applied.  Thank Uli.

**Comment by pbeckingham** [comment]
[TW-595_task.905.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756181/TW-595_task.905.diff.txt)
