### ISSUE TITLE
[TW-597] Eliminate GCC 4.6.1 compilation warnings

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#632]
_Matt Kraai on 2011-07-25T12:54:16Z says:_ 

 When compiling the 2.0.0 branch of Taskwarrior with GCC 4.6.1, the compiler generates a number of warnings:

<pre>
/home/kraai/src/task/src/A3.cpp:628:8: warning: variable found_non_sequence set but not used [-Wunused-but-set-variable]
/home/kraai/src/task/src/Arguments.cpp:287:8: warning: variable found_non_sequence set but not used [-Wunused-but-set-variable]
/home/kraai/src/task/src/Arguments.cpp:290:7: warning: variable command_pos set but not used [-Wunused-but-set-variable]
/home/kraai/src/task/src/Nibbler.cpp:241:8: warning: variable previous set but not used [-Wunused-but-set-variable]
/home/kraai/src/task/src/helpers.cpp:139:78: warning: passing NULL to non-pointer argument 1 of std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type, const value_type&, const allocator_type&) [with _Tp = Task, _Alloc = std::allocator<Task>, std::vector<_Tp, _Alloc>::size_type = long unsigned int, std::vector<_Tp, _Alloc>::value_type = Task, std::vector<_Tp, _Alloc>::allocator_type = std::allocator<Task>] [-Wconversion-null]
/home/kraai/src/task/src/utf8.cpp:90:31: warning: operation on i may be undefined [-Wsequence-point]
/home/kraai/src/task/src/utf8.cpp:96:31: warning: operation on i may be undefined [-Wsequence-point]
/home/kraai/src/task/src/utf8.cpp:96:31: warning: operation on i may be undefined [-Wsequence-point]
/home/kraai/src/task/src/utf8.cpp:103:31: warning: operation on i may be undefined [-Wsequence-point]
/home/kraai/src/task/src/utf8.cpp:103:31: warning: operation on i may be undefined [-Wsequence-point]
/home/kraai/src/task/src/utf8.cpp:103:31: warning: operation on i may be undefined [-Wsequence-point]
</pre>

The attached patch eliminates these warnings.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-07-25T12:54:16Z
Modified: 2014-02-09T02:06:29Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-07-26T03:23:19Z says:_ 

 Patch applied.  Nice work.  Thank you.

**Comment by pbeckingham** [comment]
[TW-597_0001-Clean-Build.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756185/TW-597_0001-Clean-Build.patch.txt)
