### ISSUE TITLE
[TW-608] Compile warnings on Solaris with GCC 3.4.6

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#643]
_Owen Clarke on 2012-02-24T00:17:44Z says:_ 

 I've been getting the following compiler warnings:
<pre>
/projects/base/owen/src/task-8521e6d/src/JSON.cpp: In static member function `static bool json::object::parse_pair(Nibbler&, std::string&, json::value*&)':
/projects/base/owen/src/task-8521e6d/src/JSON.cpp:331: warning: converting to non-pointer type `bool' from NULL
</pre>
Changing return type to 'false' fixes this one.

<pre>
/projects/base/owen/src/task-8521e6d/src/Timer.cpp: In member function `void Timer::stop()':
/projects/base/owen/src/task-8521e6d/src/Timer.cpp:97: warning: converting to `long unsigned int' from `double'
</pre>
The multiplication by a double seems unnecessary, changing it to an int fixes this (1000000.0 -> 1000000).

<pre>
/projects/base/owen/src/task-8521e6d/src/commands/CmdUrgency.cpp: In member function `virtual int CmdUrgency::execute(std::string&)':
/projects/base/owen/src/task-8521e6d/src/commands/CmdUrgency.cpp:73: warning: passing `float' for converting 3 of `const std::string format(const std::string&, const std::string&, int)'
</pre>
I think this one's doing an implicit cast to int anyway?? Adding an explicit cast gets rid of the warning.

Patches attached.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-02-24T00:17:44Z
Modified: 2014-02-09T02:06:30Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-02-24T01:47:08Z says:_ 

 Applied patches, but not the CmdUrgency.cpp patch, because it changes the type.

Instead, have modified the source while retaining the floating point type.

**Comment by pbeckingham** [comment]
[TW-608_CmdUrgency.cpp.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756188/TW-608_CmdUrgency.cpp.patch.txt)
[TW-608_JSON.cpp.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756189/TW-608_JSON.cpp.patch.txt)
[TW-608_Timer.cpp.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756190/TW-608_Timer.cpp.patch.txt)
