### ISSUE TITLE
[TW-613] Extra blank lines appear when executing task color under cygwin

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#648]
_Cory Donnelly on 2010-10-22T12:27:38Z says:_ 

 Extra blank lines appear when executing task color under cygwin.  I experience this under 1.9.2 and 1.9.3.beta1.

See screenshot.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-10-22T12:27:38Z
Modified: 2014-02-09T02:06:30Z
```

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2010-10-22T13:41:24Z says:_ 

 Poor handling of color in cygwin term. That might not be possible to fix.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-10-23T10:16:00Z says:_ 

 Does this still happen if the window is made 1 column wider?  ie is this an edge case?

**Comment by taskwarrior** [comment]
_Jonathan Hankins on 2011-05-11T03:03:49Z says:_ 

 I believe that, if you make the cmd console width wider than your widest task description, the extra lines aren't there.  It seems that, when task reformats the task description to span multiple lines, and color is enabled, the extra line behavior surfaces.

It also does it in Console (console.sf.net) but not in cygwin xterm.  Changing TERM doesn't seem to matter.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-11T03:14:02Z says:_ 

 Here is what I think I need for this bug, because I can't reproduce it, although I don't use Cygwin much:

1. Find some report that exhibits this behavior.  Make the window just wide enough that this problem goes away.  At this width, run the report again with:
<pre>
task <some report> rc._forcecolor:on rc.defaultwidth:<good width of window>  > good.txt
</pre>
2. Make the window one character narrower, so that the problem is exhibited, and capture the output again:
<pre>
task <some report> rc._forcecolor:on rc.defaultwidth:<bad width of window>  > bad.txt
</pre>
3. Send me the files.

Any takers?

**Comment by taskwarrior** [comment]
_Jonathan Hankins on 2011-05-11T04:17:05Z says:_ 

 I'll play with it and try to get you something in the next couple of days.

Thanks!

**Comment by taskwarrior** [comment]
_Jonathan Hankins on 2011-05-11T21:18:45Z says:_ 

 OK, so I have a pending.data file with one entry.  When doing the "task list" report, the longest line of output is 129 characters.

If I set the width of the terminal to 129, there is no line-breaking, and no extra spaces.  The annotation ends with "Reminder set. " (note the space).  That is, after the period, there is one blank column before the right margin of the terminal.  The trailing space is not part of the entry in my data file, and indeed, if you pipe the output of "task list rc._forcecolor:on rc.defaultwidth:129" through "cat -A", there is no space character in the output after the "Reminder set." -- just terminal control sequences. This is in the attached good.txt.

If I set the width of the terminal to 128, there is no line-breaking, and the annotation ends with "Reminder set." (note no space).  That is, the period is in the very last column in the right margin of the terminal.

Interestingly, if I set the width of the terminal to 128, but drag the right-hand edge of the window so that it shrinks and a horizontal scrollbar appears, then re-run "task list rc._forcecolor:on rc.defaultwidth:128", the annotation is line-broken between "Reminder" and "set.", however, the extra lines do NOT appear in the output.

If I set the width of the terminal to less than 128 (e.g., 127) and there is no horizontal scrollbar, the annotation is line-broken appropriately, but the extra lines DO appear.

Value of COLUMNS, and running "reset" or "eval `resize`", unsetting COLUMNS, etc., don't appear to affect issue.  Changing TERM doesn't affect either.  Presence of absence of "cols" in "infocmp" output doesn't matter.  Turning color off DOES prevent the issue from occurring.

If I ssh from inside the cygwin terminal to a linux box and run "task", the same problem happens, but it does not happen locally on that linux box, or if I ssh into it from Putty, or a cygwin xterm.

If I run "screen" inside the cygwin terminal, task list doesn't exhibit the extra line behavior at any terminal width.

Sorry if that is confusing.

**Comment by taskwarrior** [comment]
_Jonathan Hankins on 2011-05-11T21:44:42Z says:_ 

 More info.

If I create a text file called "tempfile" with 2 lines, each containing "x" repeated 130 times, and set the terminal width to 130, then do "cat tempfile" (in Cygwin bash shell) or "type tempfile" (in cmd prompt), I see:

xxx[...]xxx
xxx[...]xxx

If I set the width to 129, I see:

xxx[...]xxx

xxx[...]xxx

If I set the width to 128, I see:

xxx[...]xx
x
xxx[...]xx
x

(note no extra blank lines)

This happens whether or not the lines in tempfile end in CRLF or just LF.

No color this time.

So I did some more poking with my original pending.data file from last post.

If I do "task list rc._forcecolor:on rc.defaultwidth:128 | cat -A" I see that, at the end of the description and first annotation lines, there are a lot of space characters padding those lines out to the same width as the last annotation (longest line), ending with a ^[[0m (reset sequence?).

If I rather do "task list rc.color:off rc.defaultwidth:128 | cat -A" the space character padding (and escape sequences) are not there.

I think we are hitting a behavior of the windows terminal driver where an extra LF or CR is added when the width of the line matches the width of the terminal exactly.

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2011-05-12T01:16:18Z says:_ 

 Jonathan Hankins wrote:
> I think we are hitting a behavior of the windows terminal driver where an extra LF or CR is added when the width of the line matches the width of the terminal exactly.

I think you're right on the money. I'm happy to close this as an environment issue -- thanks everyone for your diagnostic efforts. Any objections?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-12T01:39:59Z says:_ 

 I looked at the three files Jonathan provided - the taskwarrior output is identical, and renders as expected in xterm.  I agree, this must be a CR/LF line-end full-width kind of Cygwin problem.

Thank you Jonathan, for the help.  You are now in the 2.0 AUTHORS file by way of thanks.

**Comment by taskwarrior** [comment]
_Jonathan Hankins on 2011-05-12T01:42:48Z says:_ 

 I think it's an interaction between auto-margin or some other weird terminal baggage from the dark ages.  This looks like it might have some starting points if anyone were interested in working around it in taskwarrior code, but I spent about an hour searching and it may never pay off: http://www.mail-archive.com/debian-bugs-dist(at)lists.debian.org/msg107994.html

Running inside screen, or making the window big enough, or horizontally-scrollable, all work for me.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-12T01:59:37Z says:_ 

 I like Thomas Dickey's reference to:

    The avoid_last_column flag ...

We may have to implement this.  Let's not close this one just yet.

**Comment by taskwarrior** [comment]
_Jonathan Hankins on 2011-05-12T02:08:09Z says:_ 

 This was a really old bug that was fixed in procps way back when -- maybe looking at their changelog (the bug report tells which version fixed it) and their CVS/whatever diff will be useful?

My intuition tells me that the auto-margin/no auto-margin, plus the "eat newlink glitch" and some other warts that termcap(5) talks about are something that comes up rarely enough that curses programmers only work around it when they encounter it.  screen(1) talks about a compensation it does for terminals based on the auto-margin stuff, and they had to fix it in procps.  Cygwin basically layers POSIX termios on top of whatever cmd.exe implements, which makes me cringe thinking back to ANSI.SYS and all the gory bits that surely lurk inside the Win{NT,2000,XP,Vista,7} terminal driver.

It also tells me that making the cmd.exe window have a horizontal scroll bar (windows width less than terminal width) disables auto-margin, and that's why I get the results I get in my horiz.txt test.

I was surprised that Console (console.sf.net) had the same issue -- but maybe they were following Microsoft's implementation details.

For those using Cygwin who don't want to run X to get xterm or rxvt, search for running rxvt without X -- there is a hack to make rxvt the terminal emulator for your Cygwin Bash Shell icon, without loading the X server up.

**Comment by taskwarrior** [comment]
_Jonathan Hankins on 2011-05-12T02:08:53Z says:_ 

 Err, that's the "eat newline glitch".  Nom nom nom.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-30T14:19:13Z says:_ 

 Taskwarrior now support rc.avoidlastcolumn (default: off) which prevents color codes being placed in the last column of the display.

**Comment by pbeckingham** [comment]
![tw-613_20101022_bash_task_colours](https://user-images.githubusercontent.com/7963/36637388-efb6740c-19a8-11e8-9c1b-94b38dc6c0bd.png)
[TW-613_bad.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755647/TW-613_bad.txt)
[TW-613_good.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755648/TW-613_good.txt)
[TW-613_horiz.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755649/TW-613_horiz.txt)
