### ISSUE TITLE
[TW-4] lack of a tty + defaultwidth breaks task burndown

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#67]
_steve rader on 2011-01-19T23:25:39Z says:_ 

 I'm seeing the lack of a tty influence task burndown!
I get the expected results inspecting the output.  
But wrong results when it gets piped to grep...
<pre>
$ for w in `seq 40 10 120`; do
> echo -e "$w\t\c" ; task rc.defaultwidth=$w burndown.daily  | grep Estimated
> done
40           Find rate: 2.7/d        Estimated completion: No convergence
50           Find rate: 3.9/d        Estimated completion: 2/15/2011 (3 wks).7/d
60           Find rate: 3.6/d        Estimated completion: 2/21/2011 (4 wks)x rate:  7.4/d
70           Find rate: 3.0/d        Estimated completion: 3/7/2011 (6 wks)
80          Find rate: 3.4/d        Estimated completion: 4/7/2011 (11 wks)
90          Find rate: 3.9/d        Estimated completion: 5/10/2011 (3 mths)
100         Find rate: 3.5/d        Estimated completion: 6/4/2011 (4 mths)
110         Find rate: 5.8/d        Estimated completion: 6/3/2011 (4 mths)
120         Find rate: 6.3/d        Estimated completion: 7/11/2011 (5 mths)
</pre>
The expected results is...
<pre>
    Find rate: 6.4/d        Estimated completion: 10/21/2015 (4.8 yrs)
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-01-19T23:25:39Z
Modified: 2015-03-14T15:33:51Z
```

**Comment by taskwarrior** [comment]
_steve rader on 2011-01-19T23:29:09Z says:_ 

 Attached is a more colorful example of this bug.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-02-19T20:42:28Z says:_ 

 This is because the estimate is based on pre-computed graph bars.  This is not right.  It need to be replaced, but that is significant work, and so is deferred.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-12-01T21:05:20Z says:_ 

 I want to replace this calculation with Evidence-Based Scheduling.  Deferring for now.

http://www.joelonsoftware.com/items/2007/10/26.html

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2015-03-14T15:33:51Z says:_ 

 Closing because "lack of a tty" is not something that really needs to be supported.

**Comment by pbeckingham** [comment]
![tw-4_nutty-task-burndown-results](https://user-images.githubusercontent.com/7963/36637151-86c0cb46-19a3-11e8-9108-e8b5fb0225c0.gif)
