### ISSUE TITLE
[TW-635] Syntax errors in DOM.cpp and Directory.cpp in 2.0.0

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#670]
_Owen Clarke on 2011-06-28T02:22:32Z says:_ 

 Minor syntax errors in DOM.cpp and Directory.cpp in 2.0.0 branch that I ran into when SOLARIS and UNKNOWN were defined.
Missing semi-colon in DOM.cpp and a typo in Directory.cpp in a call to dirent.d_name

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-06-28T02:22:32Z
Modified: 2014-02-09T02:06:31Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-06-28T02:29:11Z says:_ 

 Applying now...

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-06-28T02:43:43Z says:_ 

 Done, pushed.  Thanks.

**Comment by pbeckingham** [comment]
[TW-635_Directory.cpp.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756191/TW-635_Directory.cpp.patch.txt)
[TW-635_DOM.cpp.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756192/TW-635_DOM.cpp.patch.txt)
