### ISSUE TITLE
[TW-636] Tests that remove directories fail on Solaris, regression of bug 889?

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#671]
_Owen Clarke on 2012-02-24T00:12:20Z says:_ 

 I thought this was already fixed with bug 889, but I can't seem to a commit that contained the fix.
stat() is not being passed the full path to stat and fails.
Patch attached.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-02-24T00:12:20Z
Modified: 2014-02-09T02:06:31Z
```

**Comment by pbeckingham** [comment]
[TW-636_Directory.cpp.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756193/TW-636_Directory.cpp.patch.txt)
