### ISSUE TITLE
[TW-637] Compile error if HAVE_SRANDOM is not defined

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#672]
_Owen Clarke on 2011-07-01T00:53:21Z says:_ 

 The struct timeval tv in main.cpp is declared within the '#ifdef HAVE_SRANDOM' block and so the 'srand (tv.tv_usec)' in the #else causes the compile to fail.
Just had to move the variable declaration out of the #ifdef. Patch attached.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-07-01T00:53:21Z
Modified: 2014-02-09T02:06:31Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-07-01T13:09:42Z says:_ 

 Patch applied and pushed.  Thank you.

**Comment by pbeckingham** [comment]
[TW-637_main.cpp.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756194/TW-637_main.cpp.patch.txt)
