### ISSUE TITLE
[TW-638] Can't bypass confirmation for deleting recurring tasks

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#673]
_Bryce Harrington on 2011-07-22T03:53:38Z says:_ 

 I have a recurring task, of which task 75 is one instance.  I want to delete just that one instance without disturbing other instances, and don't want to be prompted about it.

As per the man page, I *think* rc.confirmation=no (or off) ought to do it, but doesn't:

 $ task rc.confirmation=off delete 75
 This is a recurring task.  Do you want to delete all pending recurrences of this same task? (y/n) ^C

(The reason I need this is for wrappering task in a higher level bit of code.)

task 1.9.4
  Platform: Linux

Compiler
   Version: 4.5.2
      Caps: +stdc +stdc_hosted +200809 +c1 +i4 +l4 +vp4

Libraries
  Readline: n/a
       Lua: n/a

Build Features
     Built: Jun 23 2011 18:09:33
      Caps: +pthreads +srandom +random -uuid

Configuration
      File: /home/bryce/.taskrc (found), 12684 bytes, mode 100644
      Data: /home/bryce/.task (found), dir, mode 40755
   Locking: Enabled
     Regex: Disabled

External Utilities
       scp: found
     rsync: 3.0.7
      curl: 7.21.3

Tests
  UUID gen: 1000 unique UUIDs generated.
     $TERM: xterm-256color (224x44)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-07-22T03:53:38Z
Modified: 2014-02-09T02:06:31Z
```

**Comment by taskwarrior** [comment]
_Matt Kraai on 2011-07-25T00:26:57Z says:_ 

 Attachment do-not-delete-parent-if-rc.confirmation-is-false has been added with description: Patch

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-07-25T01:48:41Z says:_ 

 Thank you Matt.  Patch applied, but to the new 2.0 src/commands/CmdDelete.cpp file instead - otherwise unchanged.

**Comment by pbeckingham** [comment]
[TW-638_do-not-delete-parent-if-rc.confirmation-is-false.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756195/TW-638_do-not-delete-parent-if-rc.confirmation-is-false.txt)
