### ISSUE TITLE
[TW-645] ghistory legend shows wrong colors

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#680]
_Uli Martens on 2011-10-06T08:54:47Z says:_ 

 In my "ghistory" output, the different task types are shown in three different shades of blue. In the legend, the same color is shown for all three types "Added", "Completed", "Deleted".

I'm using the latest git snapshot of the 2.0 devel branch.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-10-06T08:54:47Z
Modified: 2014-02-09T02:06:31Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-10-06T12:50:16Z says:_ 

 Good catch.  Thanks.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-10-07T03:10:18Z says:_ 

 Thanks Uli.

**Comment by pbeckingham** [comment]
![tw-645_screenshot-terminal](https://user-images.githubusercontent.com/7963/36642822-10bc6390-1a13-11e8-8d18-d2bc5ade3599.png)
