### ISSUE TITLE
[TW-654] timegm doesn't exist in Solaris' time.h

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#689]
_Owen Clarke on 2011-06-28T02:08:49Z says:_ 

 From the 2.0.0 branch:
The timegm function used in Nibbler.cpp doesn't exist in the Solaris version of time.h.

Wikipedia advises against its use as it is not always implemented on different architectures. The Linux man pages for timegm suggests an alternative, setting the timezone to UTC and using mktime.
See: http://www.kernel.org/doc/man-pages/online/pages/man3/timegm.3.html
See: http://en.wikipedia.org/wiki/Time.h

I've just patched Nibbler.cpp based on the timegm man page example to make it compile on Solaris.
It compiles, but is untested as I'm not sure how to do that within taskwarrior...

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-06-28T02:08:49Z
Modified: 2014-02-09T02:06:32Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-06-28T02:52:30Z says:_ 

 Done, pushed.  Thanks.

FYI, under normal circumstances (ie not this week) the way to test is this:

<pre>
$ cd task.git
$ git checkout 2.0.0
$ cmake .
$ make
$ make test
</pre>

This builds and runs the test suite.  Ideally you would get no errors (ha!).  If you were to modify functionality, tests would need to be added or modified.  In this case, task.git/src/nibbler.t.cpp compiles to nibbler.t, which can just be run.  The output is TAP.

**Comment by pbeckingham** [comment]
[TW-654_Nibbler.cpp.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756198/TW-654_Nibbler.cpp.patch.txt)
