### ISSUE TITLE
[TW-655] Problems with error processing in "burndown" subcommand

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#690]
_Alexei Romanoff on 2011-03-24T11:01:21Z says:_ 

 I tried to use (at)burndown@ subcommand in task, but it made me unhappy:
<pre>
$ task burndown
"" is not a valid date (m).  Expected format 'm/d/Y'
</pre>

All burndown variants(daily, monthly, weekly) printed the same error message.

I made a little research and discovered a strange piece of data in my ~/.task/completed.data file:
<pre>
[annotation_1300530386:"Ann1" annotation_1300534480:"Started task" annotation_1300552431:"AnnF" annotation_1300552436:"Stopped task" description:"broken task" entry:"1300349994" priority:"H" project:"git" start:"1300534480" status:"completed" uuid:"27e92610-bb69-91e5-5b84-1c114cba33b6"]
</pre>

This completed task doesn't have (at)end:@ field by some reason, I don't know why.
Removing of this weird task made me happy again:).

I suppose, (at)task burndown@ should handle this case, like other task subcommands e.g. (at)timesheet@, (at)completed@

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-03-24T11:01:21Z
Modified: 2014-02-09T02:06:32Z
```

**Comment by taskwarrior** [comment]
_Alexei Romanoff on 2011-03-24T11:01:21Z says:_ 

 Attachment diagnostic.log has been added with description: $task diag > diagnostic.log

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-03-24T21:29:12Z says:_ 

 Alexei, thanks for the report, and figuring out what it was too.  If this happens again, please let us know, it could be a serious problem.  Bear in mind though, that you are running a development build, which reduces the severity of this.

**Comment by pbeckingham** [comment]
[TW-655_diagnostic.log.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756200/TW-655_diagnostic.log.txt)
