### ISSUE TITLE
[EX-1] Geo fencing

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#7]
_Benjamin Weber on 2012-12-19T15:07:21Z says:_ 

 Geo fencing uses the proximity to the location where you are to let you know which actions can only be done in this context.
It is in dev for the app Things (Mac).
According to GTD "four-criteria model for choosing actions in the moment" (cf. [1]) context is much more important than priority. Following this, why tw offers a property for prio with an extensive algorithm - which in fact makes only sense from the user's perspective if she knows how it works - and not a property of context.

Yes, the tagging would work for basic geo fencing. But real geofencing should deploy the device's locating capabilites (cf. [2]).
I am thinking of a command (at)here@ which tells me what to do in a range up to 3 km, ordered by proximity.

[1] http://pespmc1.vub.ac.be/Papers/GTD-cognition.pdf
[2] http://apple.stackexchange.com/questions/60152/is-there-a-way-to-access-a-macs-geolocation-from-terminal

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-12-19T15:07:21Z
Modified: 2017-01-17T03:00:39Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-12-22T15:27:12Z says:_ 

 Is this what you are suggesting?
*  Allow a task to be given a preferred location
*  Allow distance between the machines location and the task location to affect urgency

This makes a lot of sense for a mobile client, and for someone using the GTD methodology.

**Comment by taskwarrior** [comment]
_David Patrick on 2012-12-22T20:31:20Z says:_ 

 Paul Beckingham wrote:
> This makes a lot of sense for a mobile client, and for someone using the GTD methodology.

"geo-fencing" is closely related to context. In many instances "exact location" and "context" are synonymous, but not ALWAYS.. as an example, people can be contexts. If you have a task to discuss something with Bill, the "Bill" is the context and the task is actionable when you and Bill connect, regardless of physical location. 

Geo-fencing is NOT a substitute for conventional, GTDish context management, for such simple things as work, office.printing, office.meeting, Bill, home, garden, garage, etc

That said, geo-fencing would be a good feature, and could be used to answer "the salesmans dilemma" (http://en.wikipedia.org/wiki/Travelling_salesman_problem) where tasks are scattered all over town, and you want the computer to sort out the optimum order of execution. Caveat; order-by-geo-tag would only be valid if ALL tasks had geo-co-ordinates. 

* note: previous terrible "salesman problem" example link has been replaced with much better one; wikipedia

I suppose that if every simple context (work.office, garage, home.yard, home.office, shop.baker, shop.butcher, shop.hardware) could have a geo-tag (that you could set using your smart-phone, while you were there) that taskwarrior could literally point you to your next most important context, containing your next most important tasks, like a "wrong-place at the wrong-time" alarm! 
Productivity THAT WAY -->

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2013-01-13T22:53:59Z says:_ 

 > - Allow a task to be given a preferred location

Preferred ≠ conditional
Reading a book is anywhere possible. But buying this tape only at five shops in the city. Passing by your old friend is only possible at his home. Collecting a unique item is only possible at a certain location. For the latter one the idea would only work out. The others will drive complexity to +∞.

> - Allow distance between the machines location and the task location to affect urgency

Not my thought but an interesting one. I would prefer to exclude it from urgency. Urgency is for me function based on time. My location changes over time. But introducing a relationship will end up in a user not understanding what affects how the urgency. He should be able to understand the urgency algorithm basically enabling him to act accordingly.

It should not be a hard thing to prototype a branch with a geotag option? Entering a city results in a lookup at OpenstreetMap yielding the lat/long numbers. Based on the geotagged items the proximity of each other in relation to each other are calculated, density matters here. tw should be able to have a dynamic mechanism understanding what is 'near' from a user's perspective. That would be the most crucial part. If it's working that would put tw to another level.

I agree to David that it should be questioned whether it is a context or a new vector. Time and location are two factors applicable to any task (applicable means they can be unspecified, too).
An idea would be an event which triggers on a location change the items related to the location as a review. If I check a nearby task, I get other to the location related ones as a reminder.
I love the idea of implementing a linear optimizer into tw to solve the Travelling salesman problem. That's really something only a software can do.

Initially, the problem to be addressed should be understood properly. It is helpful to gather datasets of gps loggers of daily / weekly activity of some people. There are usually only a few changes of location a day besides the state of commuting. I feel http://code.google.com/p/gource/ would be helpful to understand the nature the problem. You visit certain locations regularly, discover new ones and leave others forever.

Thinking even further would mean implementing a weather forecasting system (sunny/rain). That initiates change of location mostly, at least in my perception. Test data for verification needed.

**Comment by taskwarrior** [comment]
_David Patrick on 2013-01-14T05:56:45Z says:_ 

 Benjamin Weber wrote:
> I agree to David that it should be questioned whether it is a context or a new vector.

Location is just one of several aspects (vectors?) of context, and geo-tagging is arguably the most complex way to go about it, with a comparatively low payoff (from my perspective) unless you regularly need google-maps to tell you where the hardware store is, or where you play hockey, pr how to get home. 
If we were discussing geo-tagging to enhance a fully-working context scheme, that would be neat, but I wouldn't want to see geo-co-ordinates used in an attempts to replace simpler context things like work.printer or school.chemlab or home.garage, and they can't replace location-independent tasks like phone, read, research or Amanda.

**Comment by taskwarrior** [comment]
_Benjamin Weber on 2013-03-06T18:03:44Z says:_ 

 It's a basic feature considering Apple's approach.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-17T03:00:39Z says:_ 

 This is a mobile feature.

**Comment by pbeckingham** [comment]
![ex-1_screen_shot_2013-03-06_at_19 02 00](https://user-images.githubusercontent.com/7963/36635358-61ad9f7c-1981-11e8-9551-3414973f49cb.png)
