### ISSUE TITLE
[TW-668] cmake libuuid detection doesn't work [patch]

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#703]
_Christopher J. Pilkington on 2011-05-06T15:58:37Z says:_ 

 The detection of the uuid library doesn't work correctly under some linuxes and cygwin, but it works under OS X.

Correct CMakeLists.txt to check first for the function, and if not there, attempt to detect and include the headers/library.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-05-06T15:58:37Z
Modified: 2014-02-09T02:06:32Z
```

**Comment by taskwarrior** [comment]
_Christopher J. Pilkington on 2011-05-06T16:00:13Z says:_ 

 oops, previous patch is fubar, ignore that one

**Comment by taskwarrior** [comment]
_Christopher J. Pilkington on 2011-05-06T16:00:13Z says:_ 

 Attachment task-1.9.4-libuuid-detection.patch has been added with description: this patch actually should work

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-07T03:00:22Z says:_ 

 Nice patch.  Thank you.

**Comment by pbeckingham** [comment]
[TW-668_task-1.9.4-libuuid-detection.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756201/TW-668_task-1.9.4-libuuid-detection.patch.txt)
