### ISSUE TITLE
[TW-671] Adding task with number followed by period appends 0s to word

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#706]
_Matt Kraai on 2011-09-15T02:27:35Z says:_ 

 If I add a task that contains a number followed by a period (e.g., "task add 0."), 0s are appended after the period (e.g., the description of the task added by the previous command would be "0.000000").

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-09-15T02:27:35Z
Modified: 2014-02-09T02:06:32Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-09-15T03:07:19Z says:_ 

 Thanks.

**Comment by taskwarrior** [comment]
_Matt Kraai on 2011-11-13T13:39:05Z says:_ 

 Here's a patch that fixes this issue for me by making A3 use the same representation that was specified by the user.

**Comment by taskwarrior** [comment]
_Matt Kraai on 2011-11-13T13:39:05Z says:_ 

 Attachment 0001-Bug.patch has been added with description: Patch

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-11-15T04:47:32Z says:_ 

 Thank you Matt, nice patch.

**Comment by pbeckingham** [comment]
[TW-671_0001-Bug.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756202/TW-671_0001-Bug.patch.txt)
