### ISSUE TITLE
[TW-673] Allow setting wait time after due date (or, at least, equal to)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#708]
_Arkady Grudzinsky on 2011-04-11T04:56:35Z says:_ 

 Here is the log I have trouble with:
<pre>
$ task add due:today asdf
Created task 160.

$ task list asdf

ID  Project Pri Due       Active Age    Description
159             4/10/2011        6 secs asdf       

1 task
$ task 159 wait:1h
A 'wait' date must be before a 'due' date.
</pre>

The program should allow setting wait date, at least, equal to the due date.  "Wait" date is not "start" date.  It is used simply to hide tasks for a while.  There is nothing wrong with hiding overdue tasks.  A confirmation request should be displayed if wait time is set after the due time.  This was discussed in the forum.  Not sure if there is an issue request for this.

And, by the way, for some reason, the program reported creating task #160, but the listing shows that the created task has ID 159...

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-04-11T04:56:35Z
Modified: 2014-02-09T02:06:33Z
```

**Comment by taskwarrior** [comment]
_Matt Kraai on 2011-07-25T02:25:28Z says:_ 

 Here's a patch to make Taskwarrior allow the wait attribute to be set to after the due attribute if the user confirms the change or has disabled confirmations.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-08-24T01:40:16Z says:_ 

 Now allows this, but provides a warning.

**Comment by pbeckingham** [comment]
[TW-673_allow-waits-after-dues.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756204/TW-673_allow-waits-after-dues.txt)
