### ISSUE TITLE
[TW-676] Burndown report week numbering issue

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#711]
_Cory Donnelly on 2011-05-16T18:35:01Z says:_ 

 My first thought was that this was a simple off-by-one bug, but it's entirely possible I simply don't understand what's going on and it's a user issue.

* The 2.0.0 task burndown report shows a column for week 53 in 2010. It's my understanding that 2010 did not have a week 53. 
* The 2.0.0 task burndown report fails to present a column for week 01 in 2011.
* The 2.0.0 task burndown report shows find/fix data for week 21. The report was generated at the start of week 20.  

See below:

<pre>
$ uname -a
CYGWIN_NT-5.1 CAPITAL-ED167CB 1.7.9(0.237/5/3) 2011-03-29 10:10 i686 Cygwin
$ task _version
2.0.0
$ date +'%Y-%m-%d Week: %U'
2011-05-16 Week: 20
$ task burndown
                                                                   Weekly Burndown
80 |
   |
   |
   |
   |
   |
   |
   |
   |
   |
   |                                                                                                                                          Done
   |                                                                                                                                          Started
40 |                                                                                                                                          Pending
   |
   |
   |
   |
   |
   |
   |
   |
   |
   |
   |
   |
 0 +-------------------------------------------------------------------------------------------------------------------------------------
     30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21
     2010                                                                    2011

</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-05-16T18:35:01Z
Modified: 2014-02-09T02:06:33Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-16T21:30:35Z says:_ 

 To quote the man page for strftime:

<pre>
%U    is replaced by the week number of the year (Sunday as the first day
      of the week) as a decimal number (00-53).
%V    is replaced by the week number of the year (Monday as the first day
      of the week) as a decimal number (01-53).  If the week containing January
      1 has four or more days in the new year, then it is week 1; otherwise it is
      the last week of the previous year, and the next week is week 1.
</pre>

So a week can be 0 or 53.  But I don't think that explains what you are seeing.  Well spotted.

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2011-05-20T19:14:12Z says:_ 

 You missed one that shows up in man strftime under cygwin:

<pre>
%W    The week number, where weeks start on Monday, week 1 contains the
      first Monday in a year, and earlier days are in week 0.  Formatted
      with two digits (from ``00'' to ``53''). [tm_wday, tm_yday]
</pre>

I had no idea there were three conflicting definitions for 'week number.' Hmm. As of now, they all return the same results:

<pre>
$ date +'%Y-%m-%d WeekU: %U WeekV: %V WeekW: %W'
2011-05-20 WeekU: 20 WeekV: 20 WeekW: 20
</pre>

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-21T14:30:29Z says:_ 

 Three definitions.  That means we are simultaneously right and wrong.  I suppose we just close the bug and walk away.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-10-02T20:08:48Z says:_ 

 I'm closing this one.  The code uses strftime %U and %V, which is ISO compliant.  I don't think supporting multiple means of determining week number is a good thing.

**Comment by marcusatiliusregulus** [comment]
this issue still exists in 2.5.1
is this considered a bug or not? i cant imagine that this is expected by any user, thus imo it should be treated as a bug...
please make week 1 the default behaviour
