### ISSUE TITLE
[TW-689] Out-of-source build broken

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#724]
_Ben Boeckel on 2011-07-01T03:55:54Z says:_ 

 Patches attached for some minor CMake fixes to support out-of-source builds.

If you'd like CTest integration done as well, I can work on that. Also available, I also have a set of macros that will add targets for running valgrind and callgrind over the tests.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-07-01T03:55:54Z
Modified: 2014-02-09T02:06:33Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-07-01T13:26:42Z says:_ 

 Patches applied.  Thank you Ben.  Your name is now in the AUTHORS file.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-07-01T21:38:09Z says:_ 

 Thanks Ben.  CTest we don't want, but callgrind and valgrind woudl be realyl nice!  Thank you!

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-07-02T13:24:20Z says:_ 

 Why not CTest? If it doesn't do something that you want, it might be possible.

Currently my script works by adding a function which:

 * Adds a test, running the program
 * Adds a target for valgrind and callgrind running over the test
 * Adds targets for groups of tests

A new variant which doesn't add valgrind targets would have to be used for the perl-based tests.

A list of example targets with tests (at)include_a@ and (at)include_b@ grouped together would have:

 * (at)test@ --- runs all tests (the real CTest target)
 * (at)test-include@ --- runs all include tests
 * (at)test-include_a@ --- runs the (at)include_a@ test
 * (at)test-include_b@ --- runs the (at)include_b@ test
 * (at)valgrind@ --- runs all tests through valgrind
 * (at)valgrind-include@ --- runs all include tests through valgrind
 * (at)valgrind-include_a@ --- runs the (at)include_a@ test through valgrind
 * (at)valgrind-include_b@ --- runs the (at)include_b@ test through valgrind
 * (at)callgrind@ --- runs all tests through callgrind
 * (at)callgrind-include@ --- runs all include tests through callgrind
 * (at)callgrind-include_a@ --- runs the (at)include_a@ test through callgrind
 * (at)callgrind-include_b@ --- runs the (at)include_b@ test through callgrind

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-07-03T22:54:38Z says:_ 

 > Why not CTest? If it doesn't do something that you want, it might be possible.

We already have a test suite written using several languages, that uses TAP, and does everything we want.

**Comment by pbeckingham** [comment]
[TW-689_0001-Support-out-of-source-builds.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756205/TW-689_0001-Support-out-of-source-builds.patch.txt)
[TW-689_0002-Check-the-source-directory-for-the-test-directory.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756206/TW-689_0002-Check-the-source-directory-for-the-test-directory.patch.txt)
