### ISSUE TITLE
[TW-691] task ghistory has broken linefeeds

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#726]
_Uli Martens on 2012-01-18T09:47:06Z says:_ 

 The current task ghistory command produces broken output for me, see the two attached PNGs for screenshots.

The bug first occured in commit 36ed70ad93d37b952e1876b62ad4d16711f5f88a and seems to be caused by the rewritten break point detection. This adds linefeeds into the table output, where they're not wanted.

This can be fixed by marking the respective tables as nonbreakable, as done in the attached patch.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-01-18T09:47:06Z
Modified: 2014-02-09T02:06:33Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-01-18T12:31:24Z says:_ 

 Good work, nice patch.  Thank you.

**Comment by pbeckingham** [comment]
![tw-691_ghistory-clear](https://user-images.githubusercontent.com/7963/36642891-7ab90c9e-1a13-11e8-9a4b-1a5f7cd81b2e.png)
![tw-691_ghistory-notfirstline](https://user-images.githubusercontent.com/7963/36642892-7ace9708-1a13-11e8-9b48-feb796ba404c.png)
[TW-691_task.ghistory.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756207/TW-691_task.ghistory.diff.txt)
