### ISSUE TITLE
[TW-693] task burndown doesn't honor _forcecolor=off

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#728]
_steve rader on 2011-01-16T09:03:52Z says:_ 

 it'd be a lot cooler if it did

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-01-16T09:03:52Z
Modified: 2014-02-09T02:06:33Z
```

**Comment by taskwarrior** [comment]
_Uli Martens on 2012-02-12T09:46:49Z says:_ 

 AIUI <notextile>_forcecolor</notextile> can only be used to force task to _use_ color when it wouldn't do so automatically (eg for redirects). This can be seen when running

<pre>
$ task rc._forcecolor:off list         # colors: colors turned on automatically, not forced on
$ task rc.color:off list               # no colors: colors turned off
$ task rc.color:off rc._forcecolor:on  # colors: colors turned off, but forced on again
</pre>

that said, this bug is still valid, as you can't turn colors off for burndown by running (at)task rc.color:off burndown@

**Comment by taskwarrior** [comment]
_Uli Martens on 2012-02-12T17:38:23Z says:_ 

 I'll create a patch in the next few days.

Proposed characters for the graph:

@.@ - done
@+@ - started
@-@ - pending

**Comment by taskwarrior** [comment]
_Uli Martens on 2012-02-13T07:59:02Z says:_ 

 fixed in attached patch

**Comment by taskwarrior** [comment]
_Uli Martens on 2012-02-13T08:01:22Z says:_ 

 and this one even has the correct characters in the comment.

@.@ and @-@ did not look different enough in the graph, so use ./+/X for done/started/pending

**Comment by pbeckingham** [comment]
[TW-693_burndown-nocolor.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756208/TW-693_burndown-nocolor.diff.txt)
