### ISSUE TITLE
[TW-695] Task 2.0.0 beta 3: Using rc.verbose=no Kills Report Labels

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#730]
_Michelle Crane on 2011-10-07T04:10:50Z says:_ 

 My default task command is to show me the upcoming calendar.  When I found that I was missing some overdue tasks because they fell in *last* month, I discovered that it's possible to combine the cal and due commands (see http://taskwarrior.org/issues/show/567).

So, my default command is (at)task cal due@.

But because I have a lot of colouring, I decided to shut down the colouring for this particular command - after all, I'm obviously looking at due tasks; I don't need them colour coded for that either.

So, I added in an override to the colour to get (at)task rc.color.due= cal due@.

Then, The little message popping up at the bottom of the output, telling me that I was using an override on the colour got annoying, so I tucked in a rc.verbose=no.  

So my final command is (at)task rc.color.due= rc.verbose=no cal due@.

This worked fine for me in 1.9.4.  But I noticed something funny when I ran it with task 2.0.0 beta 3.  It took me a few days to pinpoint the problem - the labels were missing.

It seems that in 2.0.0, as soon as I include the (at)rc.verbose=no@, not only do I lose the verbose messages (good), but I also lose the labels (bad).  See attached good.png and bad.png.

Same thing happens with other reports.

I looked through the site, but I don't see anything that discusses changes to the verbose attribute - maybe it's supposed to kill the labels, but it seems a little over-kill to me.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-10-07T04:10:50Z
Modified: 2014-02-09T02:06:33Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-10-16T03:42:30Z says:_ 

 Oops.

**Comment by pbeckingham** [comment]
![tw-695_bad](https://user-images.githubusercontent.com/7963/36642925-97b52aa8-1a13-11e8-8805-525189413073.png)
![tw-695_good](https://user-images.githubusercontent.com/7963/36642926-97c1ae90-1a13-11e8-84cc-2d4f5a068fd7.png)
