### ISSUE TITLE
[TW-705] default configuration file doesn not contain any configuration

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#740]
_Uli Martens on 2011-04-22T09:27:29Z says:_ 

 The default configuration file created with task from the 2.0.0 branch looks like this (full paste, no edits):

<pre>
1.  [Created by task 2.0.0 4/22/2011 11:23:00]
1.  Taskwarrior program configuration file.
1.  For more documentation, see http://taskwarrior.org or try 'man task', 'man task-faq',
1.  'man task-tutorial', 'man task-color', 'man task-sync' or 'man taskrc'
1.  Here is an example of entries that use the default, override and blank values
1.    variable=foo   -- By specifying a value, this overrides the default
1.    variable=      -- By specifying no value, this means no default
1.    #variable=foo  -- By commenting out the line, or deleting it, this uses the default
1.  Use the command 'task show' to see all defaults and overrides
1.  Files
data.location=/home/youam/.task
1.  Color theme (uncomment one to use)
1. include /usr/local/share/doc/task/rc/light-16.theme
1. include /usr/local/share/doc/task/rc/light-256.theme
1. include /usr/local/share/doc/task/rc/dark-16.theme
1. include /usr/local/share/doc/task/rc/dark-256.theme
1. include /usr/local/share/doc/task/rc/dark-red-256.theme
1. include /usr/local/share/doc/task/rc/dark-green-256.theme
1. include /usr/local/share/doc/task/rc/dark-blue-256.theme
1. include /usr/local/share/doc/task/rc/dark-violets-256.theme
1. include /usr/local/share/doc/task/rc/dark-yellow-green.theme

</pre>

That is, all actual configuration settings are omitted in this file. I think this is a bug, [[Upgrade_the_~taskrc_file]] sounds like this, too. the attached patch puts all default configuration values back into the default ~/.taskrc.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-04-22T09:27:29Z
Modified: 2014-02-09T02:06:34Z
```

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-04-22T13:38:56Z says:_ 

 Thank you Uli,

though it is not a bug, but we do this on purpose as it

* makes the configuration file smaller, one just will have configuration settings there that are different from the default settings.
* with less variables in the file it is easier to see what has changed
* less variables in the file is also less intimidating for new users to do changes and configure task to their needs.

You can always see all the current configuration settings by running (at)task show@.

We will not change the behaviour for the time being.

**Comment by pbeckingham** [comment]
[TW-705_default.taskrc.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756228/TW-705_default.taskrc.diff.txt)
