### ISSUE TITLE
[TW-709] 'task recurring' not listing all recurring tasks

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#744]
_John Florian on 2009-07-13T14:21:18Z says:_ 

 <pre>
$ task long                                                                                                                                                                                

ID Project       Pri Added     Started   Due       Recur     Age     Tags         Description                                                                                                        
 2 aos.deploy    M    6/8/2009 6/29/2009 7/15/2009        1w   5 wks              task A                                                           
43               M   6/15/2009           7/24/2009       biw   4 wks              task B                                                                                         
42               M   6/15/2009           10/1/2009 quarterly   3 wks admin bacula task C
<snip>
$ task recurring

ID Project Pri Due       Recur     Active Age   Description
43         M   7/24/2009       biw        4 wks task B
42         M   10/1/2009 quarterly        3 wks task C

2 tasks
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2009-07-13T14:21:18Z
Modified: 2014-02-09T02:06:34Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2009-07-18T20:40:22Z says:_ 

 Cannot replicate.  Hopefully we'll get a reproducible case.

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2009-11-15T22:30:29Z says:_ 

 I'm currently experiencing this issue under v1.8.3.  See the attached database. 

<pre>
$ t long work

ID Project                                 Pri Added      Started Due        Recur    Age   Tags             Description           
40 Recurring_Verify_NYSP_SendXML_transfers     2009-11-14         2009-11-20 biweekly 1 day work-server      sanitized doesn't work
79 Recurring_Pay_bills                         2009-11-14         2010-12-30  monthly 1 day home-online home sanitized works       
</pre>

<pre>
$ t recurring

ID Project             Pri Due        Recur   Active Age   Description    
79 Recurring_Pay_bills     2010-12-30 monthly        1 day sanitized works
</pre>

Note task 40 doesn't appear in the second list.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2009-11-16T22:27:30Z says:_ 

 Cory's sample pending.data file does indeed exhibit the bug.  Task 40 in the sample file does not have the parent:xxxx attribute, and as such doesn't qualify as a recurring task.  Whether or not the filtering logic for selecting recurring tasks is correct, this task once had a parent:xxxx attribute and now does not.

So now we know the symptoms, but still need to determine the cause.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-10-16T03:58:51Z says:_ 

 Fixed, I believe.

This is fixed in beta4, as part of the 40-commit bonanza that focused on conformation and recurring task handling consistency.  There were several cases where recurring tasks were mishandled, which have now been addressed.

**Comment by pbeckingham** [comment]
[TW-709_pending.data.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756230/TW-709_pending.data.txt)
