### ISSUE TITLE
[TW-712] Weird line wrapping in reports

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#747]
_Johannes Schlatow on 2011-01-27T07:52:36Z says:_ 

 When you look at a report on a small terminal window you will notice that the description column will be wrapped to fit the output into the window, but the tag column won't. This looks kind of weird.
I can't see a reason why the tag column shouldn't be line wrapped as well in order to get more space for the description. I guess the patch is fairly simple (see attached file).

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-01-27T07:52:36Z
Modified: 2014-02-09T02:06:34Z
```

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2011-01-27T07:52:36Z says:_ 

 Attachment custom_report_wrap.patch has been added with description: Enable line-wrapping for the tag column

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-01-27T10:46:53Z says:_ 

 I wish it were that simple.  When a report has two Table::flexible columns, it divides up the remaining column space equally, and there's the problem.  That makes tags and description columns equal width, and description is almost always bigger, so it looks odd.

This is a feature request (#25), and is waiting for the new View to replace the limited Table object.  The new algorithm in View will need to balance column widths and lines after wrapping, so that the space occupied by tags and descriptions (in fact all ::flexible fields) has the same number of lines used.  It will need to take input like this:

tags:one two three
description: this is a test of a long description that will need to be wrapped in 80 columns

and instead of generating output like this:

<pre>
| one two three | this is a test of a long description that will need |
|               | to be wrapped in 80 columns                         |
</pre>

will generate the much better:

<pre>
| one two | this is a test of a long description that will need to be |
| three   | wrapped in 80 columns                                     |
</pre>

It involves asking a complicated question: what is the best use of limited horizontal space, allowing for unlimited vertical space, while desiring "nicely" composed output?

I think this is a linear programming problem, in the mathematical sense.  But perhaps an incremental approach would work, for example, each column needs to be asked: What is the minimum horizontal space do you need, for one line of output?  Then that should be repeated for 2, 3 etc lines, and the chosen number of lines would be the one where the sum of all the column widths is under the terminal width, but closest to it.

In the example above, the answers would be:

_tags_
|1 line|14 width|
|2 lines|8 width|
|3 lines|6 width|

_description_
|1 line|80 width|
|2 lines|~40 width|
|3 lines|~27 width|
|4 lines|~20 width|

_combined_
|1 line|14 + 80 = 94|
|2 lines|8 + 40 = 48|
|3 lines|6 + 27 = 33|
|4 lines|6 + 20 = 26|

Now if the terminal is 60 characters wide, the best choice is 2 lines, requiring a minimum of 48 characters, but with the extra 12 characters probably always given to the description.  If the terminal is 94 or wider, then one line is used.

I'm not sure this algorithm is the way to do it though, because I think it doesn't handle this case well:

<pre>
| one two three four five six seven eight nine ten | Fix the thing                                         |
| one                                              | Find a better way to address the problem in the thing |
</pre>

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2011-01-27T13:16:55Z says:_ 

 Okay..I see.

Your algorithm focuses on calculating the optimum between width and height. That's a good and generic strategy when you want to divide the space between multiple flexible columns. But for the tags thing we might consider a different approach because I think the requirements are different:

I assume the user would expect the tag column to wrap if the terminal width is very limited. In other words, the output looks odd if there is a column that is wider than the description. In this case we want to borrow space from this column to beautify the report.
Maybe this can be achieved by defining that this column must not exceed e.g. 70% of the width which is available for flexible fields. Otherwise the cells will be wrapped until they fulfill this rule.

Of course this approach requires a new sizing policy in addition to _minimum_ and _flexible_.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-04-29T06:19:50Z says:_ 

 The new View can handle this.

**Comment by pbeckingham** [comment]
[TW-712_custom_report_wrap.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756231/TW-712_custom_report_wrap.patch.txt)
