### ISSUE TITLE
[TW-716] man page references 404 wiki page in 1.9.4

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#751]
_Bryce Harrington on 2011-07-06T20:38:19Z says:_ 

 The man page links to http://taskwarrior.org/wiki/taskwarrior/Simple but that page appears not to exist in the website.

EXAMPLES
       For examples please see the task tutorial man page at

              man task-tutorial

       or the online documentation starting at

              <http://taskwarrior.org/wiki/taskwarrior/Simple>

Perhaps it should be linking to http://taskwarrior.org/projects/taskwarrior/wiki?

task 1.9.4
  Platform: Linux

Compiler
   Version: 4.5.2
      Caps: +stdc +stdc_hosted +200809 +c1 +i4 +l4 +vp4

Libraries
  Readline: n/a
       Lua: n/a

Build Features
     Built: Jun 23 2011 18:09:33
      Caps: +pthreads +srandom +random -uuid

Configuration
      File: /home/bryce/.taskrc (found), 12523 bytes, mode 100644
      Data: /home/bryce/.task (found), dir, mode 40755
   Locking: Enabled
     Regex: Disabled

External Utilities
       scp: found
     rsync: 3.0.7
      curl: 7.21.3

Tests
  UUID gen: 1000 unique UUIDs generated.
     $TERM: xterm-256color (100x55)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-07-06T20:38:19Z
Modified: 2014-02-09T02:06:34Z
```

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2011-07-06T20:42:51Z says:_ 

 Attachment 0001-Fix-link-in-man-page-to-the-wiki.patch has been added with description: proposed fix

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-07-06T22:45:59Z says:_ 

 Thanks Bryce.  I promoted you to better seating in the AUTHORS file.

**Comment by pbeckingham** [comment]
[TW-716_0001-Fix-link-in-man-page-to-the-wiki.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756232/TW-716_0001-Fix-link-in-man-page-to-the-wiki.patch.txt)
