### ISSUE TITLE
[TW-16] Default column labels

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#78]
_Frédéric Mangano on 2013-06-08T09:34:05Z says:_ 

 The default configuration contains English user-visible strings for column labels. Since translations provide translations for these, I think they should be left empty in the configuration.

The attached patch illustrates a way to preserve undefined labels and provide relevant and localized labels in that case.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-06-08T09:34:05Z
Modified: 2015-05-02T20:54:34Z
```

**Comment by taskwarrior** [comment]
_Frédéric Mangano on 2013-06-08T09:39:03Z says:_ 

 Just noticed this was reported a month ago : http://taskwarrior.org/issues/1261

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-06-08T21:54:56Z says:_ 

 Missing unit tests.

**Comment by taskwarrior** [comment]
_Wim Schuermann on 2015-05-02T20:54:34Z says:_ 

 No reply from author.

**Comment by pbeckingham** [comment]
[TW-16_0032-default-column-label-sample.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755545/TW-16_0032-default-column-label-sample.patch.txt)
