### ISSUE TITLE
[TW-755] holiday handling

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#790]
_Daniel Kullmann on 2011-07-27T09:36:16Z says:_ 

 I just looked at the holiday rc files, and I'm astonished to see that holidays are only defined for a single year. It's probably not that important for people organizing their current work, but wouldn't it be nice to have holiday information for more than the next half year or so?

Right now, the holiday files in my installed version of task on Ubuntu (1.9.3) have holiday information from end-2010 to mid-2011, e.g. the latest entry for US holidays is July 4th, which has already passed.

Would it be possible to set a list of dates, instead of a single date, in the holiday settings?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-07-27T09:36:16Z
Modified: 2014-02-09T02:06:36Z
```

**Comment by taskwarrior** [comment]
_Daniel Kullmann on 2011-07-27T09:38:02Z says:_ 

 Sorry, it's a feature request, not a bug. But I don't know how to change that.

**Comment by taskwarrior** [comment]
_Daniel Kullmann on 2011-07-27T10:04:12Z says:_ 

 Made a patch implementing that feature. dates are separated by comma.c

**Comment by taskwarrior** [comment]
_Daniel Kullmann on 2011-07-27T10:04:12Z says:_ 

 Attachment multiple-holidays.patch has been added with description: Patch

**Comment by taskwarrior** [comment]
_Daniel Kullmann on 2011-07-27T10:06:15Z says:_ 

 And a test file with Danish holidays for the next three years.
This is *not* the holidays-DK.rc file that is provided with taskwarrior;
I had already created my own before realizing that a new version of 
taskwarrior includes one now.

**Comment by taskwarrior** [comment]
_Daniel Kullmann on 2011-07-27T10:06:15Z says:_ 

 Attachment holidays-DK.rc has been added with description: File with test data

**Comment by taskwarrior** [comment]
_Daniel Kullmann on 2011-07-27T10:50:04Z says:_ 

 New version of patch, supporting calendar.holidays=full

**Comment by taskwarrior** [comment]
_Daniel Kullmann on 2011-07-27T10:50:04Z says:_ 

 Attachment multiple-holidays.patch has been added with description: Version 1.1 of patch

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-07-27T11:46:47Z says:_ 

 Daniel, thank you.  I will look at the patches later.

In the meantime, for 2.0 we have an automated holiday file update script which accesses http://holidata.net and downloads a year of data.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-07-28T02:57:03Z says:_ 

 Daniel,

Thank you for the contribution.  You have been added to the AUTHORS file by way of thanks.

But I cannot apply the patches.  This is because we are changing the way holiday info is provided.  We have created [[http://holidata.net]]t to provide holiday data in a variety of useful machine formats, for anyone that needs it, because we have discovered that accurate holiday data is hard to find.  The sites that provide it are also just riddled with ads and junk.  In conjunction with this, we have a script that will be released very soon, that can refresh taskwarrior holiday files from [[http://holidata.net]].  This allows us to provide corrections and additional regional data, as well as provide a means to update the holiday data without the need for a taskwarrior release.

So while your solution is clever, concise, and very nicely implemented, it does diverge from our plans, and so I must reject the feature.

(Aside: the patches are against the master branch, and we never touch the master branch - we only merge to it upon release.  All development is done on version-specific branches, so right now we are working on the 2.0.0 branch)

**Comment by pbeckingham** [comment]
[TW-755_holidays-DK.rc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756246/TW-755_holidays-DK.rc.txt)
[TW-755_multiple-holidays.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756247/TW-755_multiple-holidays.patch.txt)
