### ISSUE TITLE
[TW-756] task environment variables: TASKRC and TASKDATA

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#791]
_steve rader on 2011-01-12T19:30:23Z says:_ 

 For what it's worth, here's a little patch I'm using to "point" various windows/terminals
at other .taskrc files and/or .task data stores.  It's pretty useful for me.  Maybe
the FAQ should be updated so more folks might make use of this.

It provides be a simple way to accomplish what's discussed here...

http://taskwarrior.org/issues/show/617#change-1908

...by way of...

<pre>
export TASKDATA=./.task
</pre>

...which is specific to sh/ksh/bash shells.

(Although I personally use absolute paths so as to not accidentally "litter" .task 
directories all around!)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-01-12T19:30:23Z
Modified: 2014-02-09T02:06:36Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-02-12T02:01:06Z says:_ 

 Also needs to modify the default entries in Config.cpp.

**Comment by taskwarrior** [comment]
_steve rader on 2011-02-12T09:48:56Z says:_ 

 
> Also needs to modify the default entries in Config.cpp.

I'd be happy to help--but I'm sorry--I don't understand what this comment really means.
The only vaguely relevant source  I see in Config.ccp is Config::defaults
"data.location=~/.task\n" in Config::defaults and I don't think that should be twiddled by
$TASKDATA.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-02-12T10:27:55Z says:_ 

 That was just a note to the future me.

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-07-29T22:39:19Z says:_ 

 Attached are two patches. The first should resolve the issue, the other is a fix for a bug I saw while there. I don't think anything else needs to be changed...not 100% sure though.

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-07-29T22:39:19Z says:_ 

 Attachment 0001-Add-environment-variables-to-override-defaults.patch has been added with description: Add support for TASKRC and TASKDATA envvars

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-07-29T22:39:19Z says:_ 

 Attachment 0002-Pass-the-data-directory-not-the-conf-path.patch has been added with description: Pass the datadir, not the rc path again

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-07-29T22:40:45Z says:_ 

 Ack, didn't see that there was already a patch. Sorry about that.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-07-30T02:59:28Z says:_ 

 > PATCH-task-env-vars

Needs unit tests, but does address code & documentation.

> 0001-Add-environment-variables-to-override-defaults.patch

Needs unit tests and documentation updates.

>0002-Pass-the-data-directory-not-the-conf-path.patch

I don't think this is a bug.

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-07-30T16:24:37Z says:_ 

 Paul Beckingham wrote:
> > PATCH-task-env-vars
> 
> Needs unit tests, but does address code & documentation.

Are both needed or is one sufficient? If both, this should patch should be changed to use the static variables defined in the 0001 patch.

> > 0001-Add-environment-variables-to-override-defaults.patch
> 
> Needs unit tests and documentation updates.

Will do.

> >0002-Pass-the-data-directory-not-the-conf-path.patch
> 
> I don't think this is a bug.

Oops, yeah. I got the createDefaultRC and formatted string things confused.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-07-30T16:31:06Z says:_ 

 > Are both needed or is one sufficient? If both, this should patch should be changed to use the static variables defined in the 0001 patch.

Don't need both.  But between the two, we need code, docs & tests.  We can Frankenstein one complete patch out of several incomplete patches if necessary.  It's all good stuff.

**Comment by taskwarrior** [comment]
_steve rader on 2011-08-02T15:09:19Z says:_ 

 
> > Needs unit tests, but does address code & documentation.
> 
> Are both needed or is one sufficient? If both, this should patch should be changed to use the static variables defined in the 0001 patch.

"both"... like both TASKRC and TASKDATA? 
i think they both have uniquely useable functionality.
(e.g. i use TASKDATA and if there's only TASKRC i'd have
to maintain multiple .taskrc files.  if there's only TASKDATA
then people couldn't have wholly different configurations
for various task data stores.)

> > > 0001-Add-environment-variables-to-override-defaults.patch
> > 
> > Needs unit tests and documentation updates.
> 
> Will do.

I am counting on you Ben, because I use TASKDATA a lot.
If you can't get er done sometime before the 2.0 release
then let me know and i'll do it.  thanks.

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-08-03T01:23:08Z says:_ 

 steve rader wrote:
> > Are both needed or is one sufficient? If both, this should patch should be changed to use the static variables defined in the 0001 patch.
> 
> "both"... like both TASKRC and TASKDATA? 

No, both patches.

> > Will do.
> 
> I am counting on you Ben, because I use TASKDATA a lot.
> If you can't get er done sometime before the 2.0 release
> then let me know and i'll do it.  thanks.

New patches attached. Other places needed to be updated to get the data directory to properly override (built-in -> config -> envvar -> CLI arg).

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-08-03T01:23:08Z says:_ 

 Attachment 0002-Add-environment-variables-to-override-defaults.patch has been added with description: Core changes

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-08-03T01:23:08Z says:_ 

 Attachment 0003-Properly-override-the-data-directory.patch has been added with description: Override the directory path more intelligently

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-08-03T01:23:08Z says:_ 

 Attachment 0004-Add-documentation-for-environment-variables.patch has been added with description: Documentation

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-08-03T01:23:08Z says:_ 

 Attachment 0005-Add-testcase-for-feature-632.patch has been added with description: Testcase

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-08-03T21:48:30Z says:_ 

 Patches break 600+ unit tests.
Patch 0005.... doesn't compile.

**Comment by taskwarrior** [comment]
_Ben Boeckel on 2011-08-04T02:30:14Z says:_ 

 Paul Beckingham wrote:
> Patches break 600+ unit tests.
> Patch 0005.... doesn't compile.

Oops. Fixing tonight, should have patches tomorrow. (perl-Test-More isn't in Fedora, I have a package of it sitting around somewhere...). In the meantime, how's the approach look?

**Comment by taskwarrior** [comment]
_steve rader on 2011-08-04T14:30:57Z says:_ 

 
> Patches break 600+ unit tests.

PATCH-task-env-vars applied against the most recent git source 
at the time (Jan 25 2011) passes all unit tests, fwiw.

try appling it, only?

**Comment by pbeckingham** [comment]
[TW-756_0001-Add-environment-variables-to-override-defaults.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755348/TW-756_0001-Add-environment-variables-to-override-defaults.patch.txt)
[TW-756_0002-Add-environment-variables-to-override-defaults.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755349/TW-756_0002-Add-environment-variables-to-override-defaults.patch.txt)
[TW-756_0002-Pass-the-data-directory-not-the-conf-path.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755350/TW-756_0002-Pass-the-data-directory-not-the-conf-path.patch.txt)
[TW-756_0003-Properly-override-the-data-directory.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755351/TW-756_0003-Properly-override-the-data-directory.patch.txt)
[TW-756_0004-Add-documentation-for-environment-variables.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755352/TW-756_0004-Add-documentation-for-environment-variables.patch.txt)
[TW-756_0005-Add-testcase-for-feature-632.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755353/TW-756_0005-Add-testcase-for-feature-632.patch.txt)
