### ISSUE TITLE
[EX-3] Forked and updated graphdeps.py

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#8]
_John Brickley on 2013-04-17T21:29:47Z says:_ 

 I found mono_1's graphdeps.py script very helpful, but was bothered by a few things about it, so forked it and put up a repository at http://github.com/shushcat/taskgv 

Changes which others may find useful include display of visually distinct tag and project nodes along with corrected arrow directions to better indicate dependency direction and inclusion.

If anyone would like to contribute, I'd be happy to work with you on making this tool more widely useful.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2013-04-17T21:29:47Z
Modified: 2014-02-09T02:43:21Z
```

**Comment by taskwarrior** [comment]
_Aikido Guy on 2013-04-17T23:05:46Z says:_ 

 Interesting! Any chance you could put a little tutorial or a few simple examples to help people understand why they might like to see their tasks as a graph? Maybe... why it might be a helpful way that gives a new point of view somehow?

**Comment by taskwarrior** [comment]
_David Patrick on 2013-04-24T14:47:00Z says:_ 

 Graphviz offers many different types of output, different styles and different formats (HTML, PNG, even text, etc.) Is it easy to change those options?

**Comment by taskwarrior** [comment]
_David Patrick on 2013-04-27T04:32:39Z says:_ 

 Just spitballing here, imagining a way to integrate taskgv into taskwarrior workflow, and still leave room for a crazy amount of graphviz options. What I'm thinking is to use taskgv as a command alias, to get filters from the preceding arguments, and to allow trailing native graphviz options. As an example, imagine a command something like

 $ task proj:foo due.before:eom taskgv neato -Tps -o foo-deps.ps

best of both worlds?

**Comment by pbeckingham** [comment]
No action required.
