### ISSUE TITLE
[TW-19] no maximum recur leads to an infinite loop in gc from overflow of int

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#81]
_Scott Kostyshak on 2012-09-01T23:17:31Z says:_ 

 To reproduce:

1. task add brush my teeth recur:70years due:today
2. task

(2) puts me into an infinite loop in generateDueDates.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-09-01T23:17:31Z
Modified: 2017-01-16T14:52:22Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-09-16T18:46:24Z says:_ 

 Recurrence periods should be validated.  Anything where now + recurrence > 2038 should be rejected.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-12-01T21:01:22Z says:_ 

 Will be addressed by kronisk.  I wonder if 64-bit time support would just make this go away.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2017-01-16T14:52:22Z says:_ 

 There should be a reasonable upper bound on recurrence period (P5Y?), and there should be a check that a projected date does not exceed max `time_t` depending on `sizeof time_t`.

**Comment by tbabej** [comment]
Reproduced on 2.6.0.

**Comment by Necior** [comment]
Version 3.2.0 exhibits the same bug.

**Comment by Necior** [comment]
[This](https://github.com/GothenburgBitFactory/taskwarrior/blob/0b286460b69042b1ed409b981e42ea34c6172574/src/recur.cpp#L316C1-L320C33) is the problematic part:

```cpp
Datetime getNextRecurrence(Datetime& current, std::string& period) {
  // [a lot of code handling other cases omitted for brevity]
  // (…)

  Duration p;
  if (!p.parse(period, idx))
    throw std::string(format("The recurrence value '{1}' is not valid.", period));

  return current + p.toTime_t();
}
```

The above function is called in a loop by `generateDueDates`. In the first iteration, `current` is the base date (e.g. 2024-11-27). `p` represents 2207520000 seconds (~70 years).

The problem is that `2024-11-27 + 2207520000 seconds` evaluates to `1958-10-04`. Next iterations of the loop further decrease the date.

**Comment by Necior** [comment]
I let `task` run for ~50 minutes and it eventually segfaulted while executing `getNextRecurrence` for the date `-2147481715-5-27`.

**Comment by djmitche** [comment]
The Datetime type is from libshared. Paul's suggestions above seem reasonable!

**Comment by djmitche** [comment]
https://github.com/GothenburgBitFactory/libshared/issues/88

**Comment by djmitche** [comment]
Limiting recurrence to 5y can be done on this issue.

**Comment by djmitche** [comment]
This appears to be a problem only on 32-bit systems, at least with the single addition operation. That is, 2024+70y = 2094 can be represented by Datetime on a 64-bit system.

**Comment by djmitche** [comment]
Ah, I was mistaken. The operator+ is defined as `Datetime Datetime::operator+ (const int delta)` which is to say it takes an integer delta, while `toTime_t` returns a `time_t`. So `current + p.toTime_t()` is implicitly casting `(time_t)2207520000` to `int`, which is `-2087447296`. Just the usual C++ footgun! There doesn't seem to be a way to comprehensively prevent this kind of error, but in this specific case we can make a range check before adding.

**Comment by djmitche** [comment]
At a quick look, I don't see a good way to limit recurrence to 5y -- what would we do with values over that amount? Surely not recur every 5 years, but if we just don't generate recurrences then the parent tasks will be reaped.

**Comment by djmitche** [comment]
Hm, checking the additions for overflow doesn't really help either:
```
⸩ t add foo recur:70y due:today
Created task 1 (recurrence template).
⸩ task list
Duration 2207520000s is too large to add to Datetime
```
which is to say, the error is thrown when listing tasks, effectively breaking the user's task list. I'm unsure how best to fix this!

**Comment by Necior** [comment]
> (…) the error is thrown when listing tasks, effectively breaking the user's task list. I'm unsure how best to fix this!

IMO this as part of a bigger discussion around allowed values in Taskwarrior and I created https://github.com/GothenburgBitFactory/taskwarrior/issues/3710 to discuss this.

In this specific case, as a user, I'd be okay with having a warning as long as it doesn't break listing the tasks (or other Taskwarrior commands).
