### ISSUE TITLE
[TW-778] add Czech holidays

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#813]
_Tomáš Čech on 2011-04-06T08:45:36Z says:_ 

 I would like to include czech holidays file for next release. It seems to work for me, but check please if syntax is correct. Thanks.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-04-06T08:45:36Z
Modified: 2014-02-09T02:06:37Z
```

**Comment by taskwarrior** [comment]
_Tomáš Čech on 2011-04-06T08:45:36Z says:_ 

 Attachment holidays-CZ.rc has been added with description: holidays-CZ.rc

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-04-06T11:07:58Z says:_ 

 Thank you Tomas for the file with the additional new locale. We will put it into the new development version.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-04-06T11:36:26Z says:_ 

 Thanks Tomas.

**Comment by pbeckingham** [comment]
[TW-778_holidays-CZ.rc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756248/TW-778_holidays-CZ.rc.txt)
