### ISSUE TITLE
[TW-780] Add support for eoq (end of quarter)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#815]
_Dave French on 2011-08-04T15:18:49Z says:_ 

 Add eoq standing for End Of Quarter
This fits with eow,eom,qoy for end of week/month/year.

quarterly is already supported as a frequency so this abbreviation
fills out an obvious gap.

Quarters are a very common period of time in many corporate environments
and align with the calendar year
1st quarter  is Jan,feb,mar
2nd = apr,may,jun
3rd = jul,aug,sep
4th = oct,nov,dec

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-08-04T15:18:49Z
Modified: 2014-02-09T02:06:37Z
```

**Comment by taskwarrior** [comment]
_Paulo Almeida on 2011-08-10T11:34:18Z says:_ 

 Something like this in Date.cpp should do the trick:

int eoq_month = today.month () + 2 - (today.month () - 1) % 3;

**Comment by taskwarrior** [comment]
_Eric Fluger on 2011-08-10T19:20:26Z says:_ 

 * - quarters are already supported as frequencies for recurring tasks.  the current definintion seems to be a period of three months starting now rather than calendar quarters as described above.  
* - presumably implementing this suggestion would involve redefining task's notion of what a quarter is and applying that in the addtional context of setting due dates, etc.  
* - each time period that has "end of" notation also has "start of" notation (ie, eow,sow, for end of week and start of week respectively) and this should probably apply to quarters as well.

**Comment by taskwarrior** [comment]
_Eric Fluger on 2011-08-10T19:21:59Z says:_ 

 AFAIK task's time and date notation is getting an overhaul soon.  Anybody know if something like this is already in the pipeline?

**Comment by taskwarrior** [comment]
_Eric Fluger on 2011-08-10T19:41:28Z says:_ 

 Along similar lines, I'd appreciate start and end of day and work day.

**Comment by taskwarrior** [comment]
_Paulo Almeida on 2011-08-10T23:12:11Z says:_ 

 For start of quarter, the attached diff should do it.

Eric, what do you mean by start of day? Would you have to define a start time
for the working day?

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-08-11T07:48:07Z says:_ 

 Thanks Paulo for the 2 patches.

We already had implemented eoq and soq but have not closed this feature request as it didn't existed then. Anyway your implementation is nicer.

Please keep in mind to provide unit tests in the future for patches as well.

eod, sod, eowd and sowd will be tackled later on as we plan to rewrite the entire date handling library for 2.1. So we will delay those as it would also require a configuration of the corresponding times.

**Comment by taskwarrior** [comment]
_Paulo Almeida on 2011-08-11T09:02:08Z says:_ 

 Federico,

I did think of providing tests, but I looked at date.t.cpp and was a bit
overwhelmed, because I have virtually no C++ experience. Coding the patches was
easier because I tested the logic in Python and then just implemented it in C++
by copying from eoy and eom. Anyway, the whole reason I looked into the
taskwarrior code was because I wanted to learn something other than Python, so
I'll definitely want to learn more about unit tests and do them in the future.

All that said, how would you go about testing soq and eoq (and how did you do
it in your implementation?) I think it would be good to test every month. The
code is more complex than eoy and eom, so it's not so obvious that it is doing
the right thing. For instance, my first attempt in Python yielded correct
results for January and February but failed if my current date was in March. I
noticed that most other relative date tests (eom, eoy, etc) use "now". "later"
is different, but I didn't quite understand its code. Also, when I ran "make
test" I got 3 failures, but I couldn't figure out what they were and where to
look to investigate them. So I'll need to learn more about those things before
I can start writing useful tests.

**Comment by taskwarrior** [comment]
_Eric Fluger on 2011-08-11T14:24:34Z says:_ 

 Paulo Almeida: 

What I had in mind was 00:01 for Start Of Day.

Ideally Start Of Work Day would be preset but redefinable by the user.  If that was pose implementation problems I suppose a general assumption as reflected by the current EOWW would be servicable in a pinch. 

There are two ways to think about these things: 
* - As way of asigning a particular time.  
* - As a convenient way to get tasks to list in a reasonable order when the particular time is not critical and there are no dependencies.  If I wanted to make sure a task is at the top of a listing I could set it's time to SOD even though I don't really intend to do it at 00:01. Used this way SOD really means "first thing I do" and "SOWD" means "first I do after I get to work".  EOWD would be good for after work activities which include work stuff like off hours changes, or personal stuff.  EOD would be good for moving things to the end of a listing, like picking up milk on the way home from such activities.  Essentially this stuff would provide a way of implicitly carving up a day into "before work", "during work","after work".  If used this way teh exact times might not matter much.

It might also be possible to use the "before" and "after" modifiers used in filters in a similar way.  Stricly speaking they are too ambiguous for value asignment, but they could be treated as "one minute before <evaluated argument>".  So in an add or modify context "due.before:tomorrow" might evaluate to 11:59 today same as EOD would.  The tricky bit here is that currently "tomorrow" evaluates to tomorrow at 00:00 so "after tomorrow" would evaluate to tomorrow at 00:001, which is not what we usually mean by "after tomorrow".  AFAICT in order for "after" to work as expected "tomorrow" would need to represent a range from 00:00 to 11:59. But I digress. 

Probably best to see what's in 2.0 before getting to wrapped up in this.

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-08-12T11:59:25Z says:_ 

 Paulo,

> I did think of providing tests, but I looked at date.t.cpp and was a bit
> ...
> I'll definitely want to learn more about unit tests and do them in the future.

Great. Coming up and providing unit tests is not easy. So no problem if you missed them this time. ;-)

> All that said, how would you go about testing soq and eoq (and how did you do
> it in your implementation?) I think it would be good to test every month.

<pre>
    Date soq ("soq");
    Date eoq ("eoq");
    t.is (soq.day (),  1,      "soq is the first day of a month");
    t.is (eoq.day () % 10,  3, "eoq is the 30th or 31th of a month");
    t.is (soq.month () % 3, 1, "soq month is 1, 4, 7 or 10");
    t.is (eoq.month () % 3, 0, "eoq month is 3, 6, 9 or 12");
    t.ok (soq.sameYear (now),  "soq is in same year as now");
    t.ok (eoq.sameYear (now),  "eoq is in same year as now");
</pre>

The test creates 2 variables for soq and eoq. Then tests "common" things like soq and eoq having the same year as the current date and so on. soq and eoq in the unit test depend on the day and month when the unit test is run. So they actually don't test every month during one run. Eventually we are going to use the "fakedate" library together with the unit tests to "simulate" different dates and times to them and task.

**Comment by taskwarrior** [comment]
_Paulo Almeida on 2011-08-12T17:48:44Z says:_ 

 Thanks for the test examples, they are helpful. And I didn't know about "fakedate" solutions. I tested my code for each month by changing the system date, which kept firing up the screensaver and left me with files modified in the future. Now I noticed there's a datefudge package available in Debian Linux and other systems, so I'll see how that works.

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-08-12T20:25:01Z says:_ 

 We have made good experience with libfaketime.

<pre>
$ aptitude show faketime
Package: faketime
State: installed
Automatically installed: no
Version: 0.8-1
Priority: extra
Section: universe/utils
Maintainer: Ubuntu MOTU Developers <ubuntu-motu(at)lists.ubuntu.com>
Uncompressed Size: 111k
Depends: libc6 (>= 2.4)
Description: report faked system time to programs
 The Fake Time Preload Library (FTPL, a.k.a. libfaketime) intercepts various system
 calls which programs use to retrieve the current date and time. It can then report
 faked dates and times (as specified by you, the user) to these programs. This means
 you can modify the system time a program sees without having to change the time
 system-wide. FTPL allows you to specify both absolute dates (e.g., 2004-01-01) and
 relative dates (e.g., 10 days ago).
Homepage: http://www.code-wizards.com/projects/libfaketime
</pre>

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2011-08-16T11:33:45Z says:_ 

 It's been a while since I tried libfaketime under osx -- I'll give it another shot.

**Comment by pbeckingham** [comment]
[TW-780_Date.cpp.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756250/TW-780_Date.cpp.diff.txt)
