### ISSUE TITLE
[TW-791] "indent" feature

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#826]
_steve rader on 2011-01-01T12:21:22Z says:_ 

 As per http://taskwarrior.com/boards/3/topics/show/1019
attached please find a patch for indenting most (table) output.

I kinda wonder, now, if this should really be margin.left and 
there should also be margin.right

Note one caveat: this feature probably won't colorize right under
the following set of conditions:
* margin is set to > 0 (obviously)
* _forcecolor is set to on
* line wrap occurs
* output is piped to "less" (e.g. task ls | less -FrX)

I believe this problem cannot be fixed: it's created by "less",
not task.  (Much like "more"'s colorization problem recently
discussed here http://taskwarrior.org/boards/1/topics/show/1013)

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-01-01T12:21:22Z
Modified: 2014-02-09T02:06:37Z
```

**Comment by taskwarrior** [comment]
_steve rader on 2011-01-02T09:48:11Z says:_ 

 The patch http://taskwarrior.org/attachments/237/PATCH-indent isn't perfect:
because column widths are calculated even when all the lines fit in the
terminal, it causes lines with the max width of all output (e.g. usually
just one) to be wrapped.

Here's one that does it right.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-01-02T11:23:57Z says:_ 

 Thanks Steve.

Patch on hold until unit tests are back online.

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-01-25T04:02:16Z says:_ 

 1.9.4 needs to focus on the remaining bugs to get released.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-05-14T04:22:04Z says:_ 

 Patches not applied, because the whole view/composition code was replaced.  This now supports a generalized left margin indent, and the ability to further indent annotations.

**Comment by pbeckingham** [comment]
[TW-791_PATCH-indent-2.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756252/TW-791_PATCH-indent-2.txt)
[TW-791_PATCH-indent.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756253/TW-791_PATCH-indent.txt)
