### ISSUE TITLE
[TW-823] task-anon.sh

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#858]
_David Patrick on 2010-11-09T11:22:30Z says:_ 

 A suggestion for a small shell script to anonymize task.data files. As we continue to expand the range and power of task, bug-hunting will get that much more "interesting". When asking for a sample of a users data file, instead of suggesting that they censure, or obfuscate sensitive data, wouldn't it be easier to suggest that they run

 % task-annon > nancy_bug123.data

with no arguments, that could replace every letter in every "word" in desc, annotation, tag with "x", for example, and it could change every number to "0". The script shouldn't touch any special character, or whitespace, or date or time, as those may be related to the problem. This would have the added benefit of making the files way easier to parse visually, too. 
The script would act on the default pending.data file, but could be used with any task.data file by supplying the target. Precautions should be made not to overwrite actual data files.

 % task-anon ~/otherdir/otherfile.data > thisdontparse.data

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-11-09T11:22:30Z
Modified: 2014-02-09T02:06:39Z
```

**Comment by taskwarrior** [comment]
_David Patrick on 2010-11-09T11:39:03Z says:_ 

 and taking that one step crazier, isn't it conceivable that such an anonymized .data file could be submitted for bug hunting by subsequently using a "push" subcommand to a taskwarrior.com or tasktools.org site ?

 % task rc:nancy_bug123.data push rsync://user(at)tasktools.org[:port]/path/to/*.data

If task shipped with the task-anon script, it could also ship with an alias that redacts the content, prepends "version" output as in-line comments, and submits the file with

 % task send-debug descriptive_output_filename

**Comment by taskwarrior** [comment]
_David Patrick on 2010-11-09T11:49:34Z says:_ 

 and to cap the madness, data so submitted could be automatically run through the barrage of unit tests, back at the mother ship.

if the data was submitted with a valid username, the result of the unit tests could be automatically emailed back to the user.. 
all before even asking PB or Fredde "why won't this parse ?". 
It's like granting users self-serve access to the test suite.

**Comment by taskwarrior** [comment]
_David Patrick on 2010-11-09T12:56:30Z says:_ 

 ..just dawning on me now that a data file full of "x" and "0" might render most queries meaningless.. but perhaps there's still some merit in the idea.. or another obfuscating algorythm that would render contents meaningless but testable.

**Comment by taskwarrior** [comment]
_t charles yun on 2010-11-09T16:05:31Z says:_ 

 I was just pondering a similar blanking tool, but was wondering if it might actually hide a class of potential problems that occured in the description fields.

never underestimate the power of rot-13 ?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-11-09T16:13:25Z says:_ 

 Instead of the xxxxxx, maybe if the description and annotations were all md5/sha1 hashed?  That way the tasks would be uniquely described/annotated, but identical original tasks would yield identical hashed tasks.

It would hide a certain class of bugs, mostly ones that are pertinent to the description and annotation fields, but that has to be a tiny minority.

Using rot-13 wouldn't preserve privacy.  It's about as effective as rot-26.  What we would want is a way to completely anonymize the data while preserving problems and relationships between tasks.

I think would make a good tool to have downloadable on the site.

**Comment by taskwarrior** [comment]
_John Florian on 2010-11-09T18:54:12Z says:_ 

 Paul Beckingham wrote:
> Instead of the xxxxxx, maybe if the description and annotations were all md5/sha1 hashed?  That way the tasks would be uniquely described/annotated, but identical original tasks would yield identical hashed tasks.

Good idea.

> Using rot-13 wouldn't preserve privacy.  It's about as effective as rot-26.

Umm, I want to say it would be about half as effective, but actually I think it's twice as effective, which is not to say that it would be effective.  <me ducks>

**Comment by taskwarrior** [comment]
_David Patrick on 2010-11-09T22:55:35Z says:_ 

 John Florian wrote:
> Umm, I want to say it would be about half as effective, but actually I think it's twice as effective, which is not to say that it would be effective.  <me ducks>

have we considered igpay atinlay ?
they'll NEVER figger that out!

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-01-09T15:10:26Z says:_ 

 This is simple a process that reads a file, and writes out the same info, but with descriptions and annotations run through MD5.  Should be a 5-line perl script.

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2011-01-17T16:07:07Z says:_ 

 Attached is a seven line perl script (what can I say, my my perl-fu isn't as strong as Paul's :)).

It anonymizes project names, task descriptions, and annotations with md5 hashes that include a salt to provide a modicum of security. Tags are not anonymized (how would users indicate the problem tasks otherwise?)

To use the script: 

@$ task export.yaml | task-anon.pl > output.yml@

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-06-08T03:21:20Z says:_ 

 I think we have two of these scripts now, with Cory's available as an external script.

**Comment by pbeckingham** [comment]
[TW-823_task-anon.pl.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756255/TW-823_task-anon.pl.txt)
