### ISSUE TITLE
[TW-834] holidays-JP.rc

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#869]
_Takanobu Watanabe on 2011-07-30T05:37:31Z says:_ 

 Hello,

I made holidays-JP.rc for 2011, even July already and soon August.
If it will be acceptable, please use it.
And if there is some problems in that rc file, Please tell me it.
I will fix it.
Also if need update it for 2012,2013... I can make it.

Regard,

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-07-30T05:37:31Z
Modified: 2014-02-09T02:06:39Z
```

**Comment by taskwarrior** [comment]
_Takanobu Watanabe on 2011-07-30T05:37:31Z says:_ 

 Attachment holidays-JP.rc has been added with description: holidays JP for 2011

**Comment by taskwarrior** [comment]
_Takanobu Watanabe on 2011-07-30T06:13:21Z says:_ 

 update holidays-JP.rc
add 2012,2013

**Comment by taskwarrior** [comment]
_Takanobu Watanabe on 2011-07-30T06:13:21Z says:_ 

 Attachment holidays-JP.rc has been added with description: holidays JP 2011-2013

**Comment by pbeckingham** [comment]
[TW-834_holidays-JP.rc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756256/TW-834_holidays-JP.rc.txt)
