### ISSUE TITLE
[TW-860] chained modifiers, set complement

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#895]
_Dan White on 2011-03-15T18:48:18Z says:_ 

 Wanted:
<pre>
task list project.not:foo
</pre>
to match the complement of
<pre>
task list project:foo
</pre>

This is currently not possible due to the (good) default project attribute modifier of ".startswith".  Chained modifiers would accomplish this by allowing:
<pre>
task list project.not.startswith:foo
</pre>
a satisfactory solution.

At the moment I can't think of a use of chained modifiers not involving a complement of an existing filter.  Some of these already exist as "is/isnt", "has/hasnt", and "word/noword".

Possible solutions:
1.  Implement arbitrary modifier chains.  This would need a data structure change.
1.  Fill out the allowed modifiers with e.g. "startswith/notstartswith" and "endswith/notendswith"
1.  Implement a modifier prefix to replace/supplement the negative filter forms:
    *  "is" and "!is" replacing "isnt"
    *  "startswith" and "!startswith"

I'm partial to the last one because it's how I think and consistent with usage in a shell.  It may be implemented by adding an attribute variable att.mSense = "positive" or "negative" as already partially done.  The prefix character ("!") can then be chomped at parse time and Filter.pass can return based on the logic "sense" in effect.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-03-15T18:48:18Z
Modified: 2014-02-09T02:06:40Z
```

**Comment by taskwarrior** [comment]
_Dan White on 2011-03-15T23:50:03Z says:_ 

 Well, the "!" character isn't kosher without escaping even within a string with bash apparently.  How about "~" as the negation prefix, bash only expands it if it starts a word.

The attached patch 1 implements solution 3, leaving the "*nt" forms in place for fun like
<pre>
task list pro.~isnt:foo
</pre>

Attached patch 2 keeps the intuitive behavior of "projects match leftmost" when using a bare "not" modifier
<pre>
task list pro.not:foo
</pre>
yields the same result as
<pre>
task list pro.~startswith:foo
</pre>
instead of the unexpected (for me) equivalent exact match
<pre>
task list pro.isnt:foo
</pre>

The patches seem to work fine for attributes other than "description".

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-03-16T00:01:43Z says:_ 

 Dan, how's your Perl?  (Because the next question is about unit tests).

**Comment by taskwarrior** [comment]
_Dan White on 2011-03-17T23:51:20Z says:_ 

 Ya, Perl and I don't get together too often, but I can copy-paste with the best of 'em.

> The patches seem to work fine for attributes other than "description".

Not when the test suite is run...

The attached patch series does this right and:
* Adds this feature with the '~' prefix for all attributes/modifiers including 'description'
* Makes pro.not:foo anti-match leftmost by default to mirror pro:foo
* Adds tests for the new filter feature, and
* Documents the change in NEWS, ChangeLog, and the task.1 man page.

This series is based on the current '2.0.0' branch because I finally read [[What makes a good patch]].

All tests including the new ones pass.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-03-19T01:03:26Z says:_ 

 Nice work Dan.  Good patches.

**Comment by pbeckingham** [comment]
[TW-860_0001-Add-attribute-modifier-prefix-for-negation.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755613/TW-860_0001-Add-attribute-modifier-prefix-for-negation.patch.txt)
[TW-860_0002-pro.not-foo-defaults-to-complement-of-pro-foo.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755614/TW-860_0002-pro.not-foo-defaults-to-complement-of-pro-foo.patch.txt)
[TW-860_0003-Add-modifier-negation-prefix-testing.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755615/TW-860_0003-Add-modifier-negation-prefix-testing.patch.txt)
[TW-860_0004-Documentation-for-Feature-710.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755616/TW-860_0004-Documentation-for-Feature-710.patch.txt)
