### ISSUE TITLE
[TW-862] core dump?

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#897]
_Aikido Guy on 2011-09-03T16:28:44Z says:_ 

 Not sure what has happened, but I've just updated my cygwin and now
<pre>$ task cal
Aborted (core dumped)
$ task
Aborted (core dumped)</pre>

Any thoughts? A problem with cygwin? I'm using 1.9.4

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-09-03T16:28:44Z
Modified: 2014-02-09T02:09:27Z
```

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-09-03T16:33:11Z says:_ 

 What did you update? Do you remember? Libraries, etc.?

**Comment by taskwarrior** [comment]
_Aikido Guy on 2011-09-03T16:40:02Z says:_ 

 yikes... hhmm... I let cygwin update all installed packages and I believe mintty was updated. I also added a couple of new packages 'inetutils', 'gnugo' and 'gnugp'...

**Comment by taskwarrior** [comment]
_Aikido Guy on 2011-09-03T16:41:18Z says:_ 

 also gcc4 was updated...

**Comment by taskwarrior** [comment]
_Aikido Guy on 2011-09-03T16:42:59Z says:_ 

 lua is currently 5.1.4-11... not sure if that is different than my previous version

**Comment by taskwarrior** [comment]
_Aikido Guy on 2011-09-03T16:44:23Z says:_ 

 'gnugp' is a typo... should be 'gnupg' and it is version 1.4.9-2

**Comment by taskwarrior** [comment]
_Aikido Guy on 2011-09-03T16:45:12Z says:_ 

 'mintty' is version 1.0.1-1 on my machine

**Comment by taskwarrior** [comment]
_Aikido Guy on 2011-09-03T16:49:09Z says:_ 

 I have a 'task.exe.stackdump*' file... if that helps?

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-09-03T17:06:22Z says:_ 

 The gcc update could have changed some of the underlying libraries. Time to start the VM and do a fresh cygwin install. How large is the stackdump?

**Comment by taskwarrior** [comment]
_Aikido Guy on 2011-09-03T17:11:07Z says:_ 

 stackdump is 1086 bytes

Also, I tried running gdb (I'm not that familiar with it) and get the following output:

<pre>$ gdb task
GNU gdb (GDB) 7.3.50.20110821-cvs (cygwin-special)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-cygwin".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/task...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/task
[New Thread 5824.0x10c8]
[New Thread 5824.0x1530]

Program received signal SIGABRT, Aborted.
0x7c90e514 in ntdll!LdrAccessResource () from /cygdrive/c/WINDOWS/system32/ntdll.dll</pre>

What does "Time to start the VM and do a fresh cygwin install mean"?

**Comment by taskwarrior** [comment]
_Aikido Guy on 2011-09-03T17:21:43Z says:_ 

 <pre>$ cygcheck -c gcc4 task
Cygwin Package Information
Package              Version        Status
gcc4                 4.5.3-2        OK
task                 1.9.4-1        OK</pre>

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-09-03T17:23:34Z says:_ 

 Thanks for the stackdump. 

VM = Virtual Machine

Both Paul and I don't have Windows machines around. We do the development on another OS. The only way for us to run Windows is in a virtual machine.

I will now do a fresh install of cygwin and see how the task package behaves.

Did you install task from the cygwin package or did you compile it yourself? A workaround would be to (re)compile task (again) with the current gcc and underlying libraries. These might have changed and are causing now the coredump. Are you familiar with compiling software?

**Comment by taskwarrior** [comment]
_Aikido Guy on 2011-09-03T17:41:14Z says:_ 

 I just reinstalled cygwin core and utilities including reinstalling task gcc and lua. However, I still have a problem:
<pre>$ cygcheck -c gcc4 task lua
Cygwin Package Information
Package              Version        Status
gcc4                 4.5.3-2        OK
lua                  5.1.4-11       OK
task                 1.9.4-1        OK

$ task
Aborted (core dumped)</pre>

I only installed task from within cygwin... I didn't compile it myself.

sigh... yes, I'm rather familiar with compiling software, so I could do that if necessary :)

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-09-03T18:30:18Z says:_ 

 We are checking on our side. Please be aware that it will take between one to three days for a new package to appear in their mirrors once we upload a new package after fixing the problem. In this case you might really want to compile task yourself.

**Comment by taskwarrior** [comment]
_Aikido Guy on 2011-09-03T19:24:56Z says:_ 

 ok... I used git to download and compile TaskWarrior. I also uninstalled the cygwin version.

All seems to now be ok on my machine.

<pre>$ task version

task 1.9.4 built for cygwin-lua
Copyright (C) 2006 - 2011 P. Beckingham, F. Hernandez.
Portions of this software Copyright (C) 1994  2008 Lua.org, PUC-Rio.

Taskwarrior may be copied only under the terms of the GNU General Public License, which may be found
in the taskwarrior source kit.

Documentation for taskwarrior can be found using 'man task', 'man taskrc', 'man task-tutorial', 'man
task-color', 'man task-sync', 'man task-faq' or at http://taskwarrior.org

$ which task
/usr/local/bin/task</pre>

I'll install the cygwin version when that becomes available.

Thanks!

**Comment by taskwarrior** [comment]
_Aikido Guy on 2011-09-03T19:26:15Z says:_ 

 And to confirm... the cygwin package is not installed.

<pre>$ cygcheck -c gcc4 task lua
Cygwin Package Information
Package              Version        Status
gcc4                 4.5.3-2        OK
lua                  5.1.4-11       OK</pre>

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-09-03T20:07:00Z says:_ 

 A simple recompile of task with the current compiler and libraries solves the problem. No more coredumps.

We are going to submit an updated package. But it will take some time for it to propagate in the repositories.

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-09-03T21:21:55Z says:_ 

 A new package has been submitted to the repositories.

http://www.cygwin.com/ml/cygwin-apps/2011-09/msg00019.html

**Comment by pbeckingham** [comment]
[TW-862_task.exe.stackdump.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756257/TW-862_task.exe.stackdump.txt)
