### ISSUE TITLE
[TW-863] incorrect project counts

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#898]
_steve rader on 2011-02-19T10:26:23Z says:_ 

 Enclosed please find a task data store where project counts are incorrectly
reported by "task projects" and/or "task count" (assuming the count from
"task ls" is canonical.)  The problem exists in 1.9.3 and 1.9.4-beta1.
I tried to distill this down to a simple case but failed: the cause of the
problem is not immediately obvious to me.  The bug(s) does/do not seem to
be related to project names or task descriptions.  Anyway, here's an example
and then a full run-down demonstrating multiple instances of the problem...

<pre>
  $ task projects | grep walk | awk '{print $2}'
  12
  $ task ls project:walk | tail -1
  8 tasks
  $ task count project:walk
  13
  $ task projects | egrep '^[a-z]' | while read l ; do
  >  p=`echo $l | awk '{print $1}'`
  >  pc=`echo $l | awk '{print $2}'`
  >  lsc=`task ls project:$p | tail -1 | awk '{print $1}'`
  >  cc=`task count project:$p`
  >  if [ $pc != $lsc ] || [ $pc != $cc ] || [ $lsc != $cc ]; then
  >    echo "oops: $p: $pc vs $lsc vs $cc"
  >  fi
  > done
  oops: choose: 5 vs 5 vs 12
  oops: curtain: 33 vs 32 vs 52
  oops: feather: 4 vs 3 vs 45
  oops: pipe: 1 vs 1 vs 6
  oops: walk: 12 vs 8 vs 13
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-02-19T10:26:23Z
Modified: 2014-02-09T02:09:56Z
```

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2011-02-19T15:33:24Z says:_ 

 Hey steve,

you have to consider that the _projects_ command does only count the pending tasks by default. Have you tried _list.all.projects=yes_? Whats your filter setting for the _ls_ report?

**Comment by taskwarrior** [comment]
_steve rader on 2011-02-20T09:24:51Z says:_ 

 
> you have to consider that the _projects_ command does only count the pending tasks by default. Have you tried _list.all.projects=yes_? Whats your filter setting for the _ls_ report?

My _ls_ report is the default one.  But you got me on the right track: The _task projects_
command reports _status.not:completed_.  The _task ls_ command reports _status:pending_ and
the _task count_ command reports _all_ tasks.  Given that information, there are no bugs,
only PEBKAC.  Thanks!

**Comment by pbeckingham** [comment]
[TW-863_dot-task-20797.tar.gz](https://github.com/GothenburgBitFactory/taskwarrior/files/1756258/TW-863_dot-task-20797.tar.gz)
