### ISSUE TITLE
[TW-28] Inserts spaces before punctuation characters

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#90]
_Matt Kraai on 2011-08-25T11:29:10Z says:_ 

 When I run "task add foo\'s bar." using the head of the 2.0.0 branch, the description of the new task is "foo 's bar .".

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-08-25T11:29:10Z
Modified: 2014-05-31T14:39:22Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-08-26T02:39:54Z says:_ 

 This is a side effect of the new parsing.  It needs to be fixed.

Please note that the 2.0.0 HEAD is development code, and not stable.  Until we release beta1, it is not advised that anyone use this without caution, thick skin and a full backup.

**Comment by taskwarrior** [comment]
_Matt Kraai on 2011-08-26T05:30:26Z says:_ 

 Here's a patch that fixes the problem for me.  Sorry, no test case.  :(

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-08-26T06:07:57Z says:_ 

 Nice patch Matt, thank you.  Quality of the fix compensates for the lack of unit tests.   I will add the tests.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-08-26T06:19:08Z says:_ 

 Unit tests added - bug.819.t

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2011-12-02T16:25:05Z says:_ 

 There is another case where additional spaces occur in the description. More precisely, a space will be inserted after a parenthesis with a preceding space O_o

E.g.

<pre>
$ task add foo \(bar\)
</pre>

will result in the description "foo ( bar)"

I added this test case to bug.819.t

**Comment by taskwarrior** [comment]
_Dirk Deimeke on 2011-12-02T16:45:28Z says:_ 

 Johannes Schlatow wrote:
> There is another case where additional spaces occur in the description. More precisely, a space will be inserted after a parenthesis with a preceding space O_o

Same root-cause? http://taskwarrior.org/issues/884

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-02-26T19:12:27Z says:_ 

 Workaround:

<pre>
task add \'foo \(bar\)\'
</pre>

It's ugly, but this is a fundamental parser issue that means this will likely be deferred.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-02-26T22:47:47Z says:_ 

 Deferring.

This is a consequence of moving towards being able to perform math, such as "due:today + 3".  Now it should be possible to have the parser decide it is not math, and revert to other interpretations, but that isn't possible yet.  There are several parser-related issues that cannot be addressed yet.

Recategorized to 'parser'.

**Comment by pbeckingham** [comment]
[TW-28_0001-Bug-819.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755546/TW-28_0001-Bug-819.patch.txt)
