### ISSUE TITLE
[TW-866] crush after adding cygwinports

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#901]
_Levent Dane on 2011-03-08T14:57:39Z says:_ 

 After adding cygwinports repository, task started crush. I think cygwinports install different gcc and standart libraries.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-03-08T14:57:39Z
Modified: 2014-02-09T02:10:54Z
```

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2011-03-08T15:30:55Z says:_ 

 Hi Levant, would you please provide a log showing what you experience? Thanks!

**Comment by taskwarrior** [comment]
_Levent Dane on 2011-03-08T15:52:05Z says:_ 

 Cory Donnelly wrote:
> Hi Levant, would you please provide a log showing what you experience? Thanks!

I added task.exe.stackdump. If you need another log, could you tell me how can i take?

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-03-08T16:34:07Z says:_ 

 Yes. The corresponding libraries (plus compiler) in cygwinports are much newer than in cygwin.

Workaround is to compile the task cygwin source package with the compiler and libraries from cygwinports installed following the instructions from the task cygwin source package:

<pre>
Build instructions:
  unpack task-1.9.4-1-src.tar.bz2
  if you use setup to install this src package, it will be
  unpacked under /usr/src automatically
    cd /usr/src
    cygport task-1.9.4-1 all

This will create:
  /usr/src/task-1.9.4-1.tar.bz2
  /usr/src/task-1.9.4-1-src.tar.bz2

Or use 'cygport task-1.9.4-1 prep' to get a patched source directory
</pre>

For the time being we will only support a standard cygwin installation.

**Comment by pbeckingham** [comment]
[TW-866_task.exe.stackdump.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756259/TW-866_task.exe.stackdump.txt)
