### ISSUE TITLE
[TW-872] Merge problem with /bin/dash shell (Ubuntu)

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#907]
_Irfan Siddiqui on 2010-12-13T18:35:49Z says:_ 

 Problem: task merge fails with the error:

<pre>
/home/irfan/.task/{pending,undo,completed}.data: No such file or directory
Could not run scp.  Is it installed, and available in $PATH?
</pre>

scp is installed (/usr/bin/scp), and available in $PATH. The directory ~/.task exists, and all three of {pending,undo,completed}.data exist and contain data.

Workaround: Symlinking /bin/sh to /bin/bash under Ubuntu:

<pre>sudo ln -sf /bin/bash /bin/sh</pre>

My initial findings: Ubuntu uses dash as its default sh shell (since Ubuntu 6.10), and has /bin/sh symlinked to /bin/dash, where other distributions usually has it symlinked to /bin/bash. Obviously there is some difference here. I took a quick look at the code in Transport.cpp, and it seems that it could be due to dash not expanding {pending,undo,completed}.data properly.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-12-13T18:35:49Z
Modified: 2014-02-09T02:11:49Z
```

**Comment by taskwarrior** [comment]
_Irfan Siddiqui on 2010-12-14T03:29:22Z says:_ 

 It looks like brace expansions over strings is a bashism, and is therefore not supported by dash as it isn't a POSIX requirement:

<pre>
https://wiki.ubuntu.com/DashAsBinSh#{
</pre>

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2010-12-14T04:41:57Z says:_ 

 Thanks Irfan, this is quite an issue.

Brace expansion is very useful e.g. because curl accepts this in the -T argument.
Since bash is a quasi-standard on linux workstations, i.e. it is installed by default and often used as login shell, I think there shouldn't be any problem with calling (at)bash@ from taskwarrior instead of (at)sh@. For this purpose you can apply the attached patch.

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2010-12-14T04:41:57Z says:_ 

 Attachment 0001-Bug-570.patch has been added with description: call bash instead of sh

**Comment by taskwarrior** [comment]
_Irfan Siddiqui on 2010-12-15T13:22:54Z says:_ 

 Your patch doesn't work Johannes. But if I instead substitute the outer (at)sh@ with (at)bash@, then it works fine (see the attached patch). I have tested it successfully on Ubuntu 9.10 (Karmic Koala) and Ubuntu 10.10 (Maverick Meerkat).

**Comment by taskwarrior** [comment]
_Johannes Schlatow on 2010-12-16T16:39:25Z says:_ 

 Of course, I didn't remember that execvp takes the command twice therefore I fixed only the first occurence. Thank you Irfan.

**Comment by pbeckingham** [comment]
[TW-872_0001-Bug-570.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756260/TW-872_0001-Bug-570.patch.txt)
[TW-872_Bug-570.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756261/TW-872_Bug-570.patch.txt)
