### ISSUE TITLE
[TW-874] Hidden item in all color themes

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#909]
_John Florian on 2010-11-11T09:45:36Z says:_ 

 Again on F13 (the Florinator is back!)... I've tried
<pre>
task color legend
</pre> 

with each of the packaged themes and in every case, the example between color.recurring and color.summary.bar is invisible -- perhaps black on black.  Screen scrape attached; this particular one happens to be light-256.

I could probably figure out which via process of elimination, but a kind hint would be appreciated.  I don't think its one I'll hit often, but would like to customize the theme as a workaround just the same.

BTW, the legend rocks -- great idea!

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-11-11T09:45:36Z
Modified: 2014-02-09T02:11:50Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-11-11T14:45:59Z says:_ 

 The reason is that the colors for the two color.summary.* entries are simple "on xxx" with no foreground color.  Now fixed in all themes and defaults.

**Comment by taskwarrior** [comment]
_John Florian on 2010-11-11T15:29:45Z says:_ 

 Yup, that fixed it.  Thanks Paul!

**Comment by pbeckingham** [comment]
![tw-874_snapshot2](https://user-images.githubusercontent.com/7963/36643189-83f7f3bc-1a16-11e8-8829-df5f6fffa09d.png)
