### ISSUE TITLE
[TW-875] task projects project "none"

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#910]
_steve rader on 2011-01-03T18:07:04Z says:_ 

 "task projects" lists no project as blank.
"task summary" lists no project as "(none)".
Attached is a patch that makes the former read like the latter.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-01-03T18:07:04Z
Modified: 2014-02-09T02:11:50Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-01-03T18:15:15Z says:_ 

 Nice.

**Comment by pbeckingham** [comment]
[TW-875_PATCH-task-projects-none.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756263/TW-875_PATCH-task-projects-none.txt)
