### ISSUE TITLE
[TW-880] [PATCH] allow backslash in task descriptions & annotations

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#915]
_Itay Perl on 2010-12-22T05:09:55Z says:_ 

 Creating a task or annotation with a backslash in the description messes up the parsing in later runs.

The attached patch does the following:
*  Fix Nibbler::getQuoted to handle escapes correctly
*  Replace \ with \\ in Att::encode
*  Minor refactoring in Att.cpp

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-12-22T05:09:55Z
Modified: 2014-02-09T02:11:50Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-12-22T10:04:20Z says:_ 

 Pluses:
*  Refactoring in Att.cpp is nice

Minuses:
*  patch fails to apply to the current 1.9.4 branch
*  patch missing necessary updates to unit tests, implying unit tests were not run

I will manually apply the patch to the 1.9.4 branch, making the missing modifications.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-12-22T10:32:11Z says:_ 

 *  This patch changes the Nibbler::getQuoted interface.  While this is fine for task, it does not consider three unreleased products that share this code.  This is *not* the fault of the patch author, because these other uses of Nibbler are not yet released or known.
*  4 unit tests now fail.  2 of those should probably just be eliminated because of the simpler interface, but the unit tests were never modified, compiled or run.

Looking into whether I can redeem this patch to Nibbler.

The Att.cpp changes I am accepting independently (it could be argued that this is really two patches in one), because the refactoring is good.  I have added unit tests for this.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-12-23T23:17:50Z says:_ 

 I was wrong.  The patch is good (once converted to the 1.9.4 code base), and it is the unit tests that are wrong.

Thanks Itay Perl, you just got promoted in the AUTHORS file.

**Comment by pbeckingham** [comment]
[TW-880_task-1.9.3-backslashes.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756264/TW-880_task-1.9.3-backslashes.patch.txt)
