### ISSUE TITLE
[TW-889] Recurring Tasks Broken for My Date Format

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#924]
_Michelle Crane on 2010-08-14T11:46:24Z says:_ 

 Using the newest version, I've noticed a distressing tendency for my recurring tasks to fail.  By fail, I mean, I mark that task as done but the next one does not show up.

I wonder if it has something to do with my date format, with is currently set at:

datformat=Y-M-D.H:N

(This to avoid being told at 1 a.m. that I'm late for something.)  I've noticed elsewhere that this date format causes trouble (e.g., editing with the edit command), and I'm wondering if somehow the recurring flag doesn't play nicely in this case.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-08-14T11:46:24Z
Modified: 2014-02-09T02:11:50Z
```

**Comment by taskwarrior** [comment]
_Michelle Crane on 2010-08-16T08:32:27Z says:_ 

 I'm back at my normal computer, and tried changing my dateformat back to Y-M-D.  But I'm still having trouble with recurring tasks disappearing.  I'm attaching both my .taskrc config and a trace showing me creating a daily task, marking it done for today and tomorrow, and then having nothing for the next day.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-08-16T08:46:09Z says:_ 

 Thanks Michelle, for that trace.txt - it will help us reproduce this.

**Comment by taskwarrior** [comment]
_Michelle Crane on 2010-08-18T09:18:36Z says:_ 

 When I was testing this, I added a few new "testing" tasks, recurring daily.  When I couldn't get them to show up in the "recur" command, I would create another one.

Now, every morning I'm noticing a whack of "testing" tasks, so they seem to be in there somewhere.  I keep trying to delete them.  Today, I went into the pending file and don't see anything with testing. But I did notice something strange.

I have exactly two recurring tasks, but there are multiple lines in the pending file with recurrence on them:

<pre>
	Line 13: [description:"Save last months google calendar to pdf and import into EN (smaller/colour)" due:"1277960400" entry:"1275657708" mask:"++XX" recur:"monthly" status:"recurring" uuid:"85e21321-6761-9750-2b22-42c1b8b112ba"]
	Line 16: [description:"Weekly Status Report" due:"1280520000" entry:"1279412000" mask:"++++" priority:"H" recur:"weekly" status:"recurring" uuid:"228a2366-09b8-6bd5-55ca-fe6b85bfc8af"]
	Line 20: [description:"Weekly status report" due:"1281124800" entry:"1281124493" mask:"+++" priority:"H" recur:"weekly" status:"recurring" uuid:"f3e72b34-dc87-8561-3799-478ba5983582"]
	Line 21: [description:"Save last months google calendar to pdf and import into EN (smaller/colour)" due:"1283371200" entry:"1281124537" mask:"-" recur:"monthly" status:"recurring" uuid:"24c745aa-f8c9-586e-86fe-aa86d25bb7ed"]
	Line 22: [description:"Save last months google calendar to pdf and import into EN (smaller/colour)" due:"1283371200" entry:"1281124537" imask:"0" parent:"24c745aa-f8c9-586e-86fe-aa86d25bb7ed" recur:"monthly" status:"pending" uuid:"e2881956-6081-c549-1a5f-82af380a3651"]
	Line 26: [description:"Weekly Status Report" due:"1282334400" entry:"1281728300" mask:"-" recur:"weekly" status:"recurring" uuid:"d76c9850-98c4-b763-9c44-aef0bd3791f6"]
	Line 27: [description:"Weekly Status Report" due:"1282334400" entry:"1281961309" mask:"-" priority:"H" recur:"weekly" status:"recurring" uuid:"ae9fb46e-89d8-77b1-8eff-37da4e67daa7"]
	Line 28: [description:"Weekly Status Report" due:"1282334400" entry:"1281961309" imask:"0" parent:"ae9fb46e-89d8-77b1-8eff-37da4e67daa7" priority:"H" recur:"weekly" status:"pending" uuid:"7631d451-db8d-ad54-1e1f-955179f5c4f3"]
</pre>

But if I do the 'recur' command, there are only two tasks.

I wonder if it's not so much a problem of the recurrence on tasks not working, but rather, something to do with how the 'recur' command shows my tasks?  Sure, with this many entries in the pending file, shouldn't I have more than two entries with the 'recur' command?

I'm tempted to delete all of these lines and start over.  Maybe it's something to do with versions, i.e., the recurring tasks are the first ones that I create, so maybe they were created in an older version of Task and just didn't migrate properly?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-08-20T00:24:00Z says:_ 

 Michelle, we have had several bug reports of misbehaving recurring tasks, so something is clearly amiss under certain circumstances.  We even have a pending.data file that contains some kind of problem that causes this, but we've never been able to recreate this problem on demand, via unit tests.  It's our sasquatch.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-08-31T01:13:52Z says:_ 

 I've been looking at the recurrence code, and fixed one bug.  I don't think it is related to this though.  I also don't think your (unusual) date format is to blame.

I've also been looking closely at the data provided.  There are oddities.  First there are these two good records:

<pre>
    Line 21: [description:"Save last months google calendar to pdf and import into EN (smaller/colour)" due:"1283371200" entry:"1281124537" mask:"-" recur:"monthly" status:"recurring" uuid:"24c745aa-f8c9-586e-86fe-aa86d25bb7ed"]
    Line 22: [description:"Save last months google calendar to pdf and import into EN (smaller/colour)" due:"1283371200" entry:"1281124537" imask:"0" parent:"24c745aa-f8c9-586e-86fe-aa86d25bb7ed" recur:"monthly" status:"pending" uuid:"e2881956-6081-c549-1a5f-82af380a3651"]
</pre>

The first is the parent, and the second is the child.  The "mask" of the parent is "-", which means only one recurring task has been generated, and it is pending.  The second line is that recurring task.  Because there is only one "-" in the mask, we know this task was added less than a month ago.  Nothing wrong there.  Then we see these two good records:

<pre>
    Line 27: [description:"Weekly Status Report" due:"1282334400" entry:"1281961309" mask:"-" priority:"H" recur:"weekly" status:"recurring" uuid:"ae9fb46e-89d8-77b1-8eff-37da4e67daa7"]
    Line 28: [description:"Weekly Status Report" due:"1282334400" entry:"1281961309" imask:"0" parent:"ae9fb46e-89d8-77b1-8eff-37da4e67daa7" priority:"H" recur:"weekly" status:"pending" uuid:"7631d451-db8d-ad54-1e1f-955179f5c4f3"]
</pre>

Again, we see mask:"-", the first is the parent, the second is the recurring.  Nothing wrong here.  That leaves these odd ones:

<pre>
    Line 13: [description:"Save last months google calendar to pdf and import into EN (smaller/colour)" due:"1277960400" entry:"1275657708" mask:"++XX" recur:"monthly" status:"recurring" uuid:"85e21321-6761-9750-2b22-42c1b8b112ba"]
    Line 16: [description:"Weekly Status Report" due:"1280520000" entry:"1279412000" mask:"++++" priority:"H" recur:"weekly" status:"recurring" uuid:"228a2366-09b8-6bd5-55ca-fe6b85bfc8af"]
    Line 20: [description:"Weekly status report" due:"1281124800" entry:"1281124493" mask:"+++" priority:"H" recur:"weekly" status:"recurring" uuid:"f3e72b34-dc87-8561-3799-478ba5983582"]
    Line 26: [description:"Weekly Status Report" due:"1282334400" entry:"1281728300" mask:"-" recur:"weekly" status:"recurring" uuid:"d76c9850-98c4-b763-9c44-aef0bd3791f6"]
</pre>

These all are parent tasks, with no corresponding recurring tasks.  I have questions, which will hopefully eliminate some things:

Q1: If you were to run this:
<pre>
$ grep mask:\" pending.data
</pre>

Would it yield only those lines shown, or more?  This is because I think the data shown is incomplete.  If the dat ais complete, something odd is happening.

Q2: Is is possible that you added a recurring task, then because there were problems, added it again?  And again?

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-08-31T01:26:20Z says:_ 

 Regarding trace.txt, what you are seeing is correct behavior, if not expected behavior.

Taskwarrior tries to limit the amount of future recurring tasks it generates to all overdue tasks, and one task into the future.  This is controlled by rc.recurrence.limit, which defaults to 1, but can be raised.  So this means if you do this:

<pre>
$ task add foo due:today recur:daily
Created task 1.

$ task list
ID Project Pri Due       Active Age Description
 2             8/31/2010          - foo        
 3             9/1/2010           - foo        

2 tasks

$ task do 2
Completed 2 'foo'.
Marked 1 task as done.

$ task do 3
Completed 3 'foo'.
Marked 1 task as done.

$ task list
No matches.
</pre>

Tomorrow, that last command would return one more recurring task.

The reason for recurrence.limit is because the task shown above has no until:<date>, and is therefore open-ended.  This means an unlimited number (well, until the year 2038) of tasks would be generated - it has to be limited, and one future task is all it shows.

**Comment by taskwarrior** [comment]
_Michelle Crane on 2010-08-31T07:39:53Z says:_ 

 Paul, re your comment #5, here is what I see when I explore the pending.data file.  (I have tried not to delete or add any more recurring tasks, but I have marked at least one weekly status as done.)

<pre>
F:\Dropbox\My Dropbox\TextFiles\.task>findstr /n mask:\" pending.data

13:[description:"Save last months google calendar to pdf and import into EN (smaller/colour)" due:"1277960400" entry:"1275657708" mask:"++XX" recur:"monthly" status:"recurring" uuid:"85e21321-6761-9750-2b22-42c1b8b112ba"]
16:[description:"infor" due:"1280520000" entry:"1279412000" mask:"+++++-" priority:"H" recur:"weekly" status:"recurring" uuid:"228a2366-09b8-6bd5-55ca-fe6b85bfc8af"]
20:[description:"Save last months google calendar to pdf and import into EN (smaller/colour)" due:"1283371200" entry:"1281124537" mask:"-" recur:"monthly" status:"recurring" uuid:"24c745aa-f8c9-586e-86fe-aa86d25bb7ed"]
21:[description:"Save last months google calendar to pdf and import into EN (smaller/colour)" due:"1283371200" entry:"1281124537" imask:"0"
parent:"24c745aa-f8c9-586e-86fe-aa86d25bb7ed" recur:"monthly" status:"pending" uuid:"e2881956-6081-c549-1a5f-82af380a3651"]
37:[description:"Weekly Status Report" due:"1283544000" entry:"1279412000" imask:"5" mask:"+++++" parent:"228a2366-09b8-6bd5-55ca-fe6b85bfc8af" priority:"H" recur:"weekly" status:"pending" uuid:"384ca0ac-8eab-d24a-46b9-045312b207c4"]

F:\Dropbox\My Dropbox\TextFiles\.task>t recur
ID Project Pri Due      Countdown Recur   Active Age   Description
* - ------- --- -------- --------- ------- ------ ----- ---------------------------------------------------------------------------
21             9/1/2010    -1 day monthly        3 wks Save last months google calendar to pdf and import into EN (smaller/colour)
37         H   9/3/2010   -3 days  weekly        6 wks Weekly Status Report
2 tasks

F:\Dropbox\My Dropbox\TextFiles\.task>findstr /n Weekly pending.data
37:[description:"Weekly Status Report" due:"1283544000" entry:"1279412000" imask:"5" mask:"+++++" parent:"228a2366-09b8-6bd5-55ca-fe6b85bfc8af" priority:"H" recur:"weekly" status:"pending" uuid:"384ca0ac-8eab-d24a-46b9-045312b207c4"]

F:\Dropbox\My Dropbox\TextFiles\.task>findstr /n 228a2366-09b8-6bd5-55ca-fe6b85bfc8af pending.data
16:[description:"infor" due:"1280520000" entry:"1279412000" mask:"+++++-" priority:"H" recur:"weekly" status:"recurring" uuid:"228a2366-09b8-6bd5-55ca-fe6b85bfc8af"]
37:[description:"Weekly Status Report" due:"1283544000" entry:"1279412000" imask:"5" mask:"+++++" parent:"228a2366-09b8-6bd5-55ca-fe6b85bfc8af" priority:"H" recur:"weekly" status:"pending" uuid:"384ca0ac-8eab-d24a-46b9-045312b207c4"]
</pre>

As for your question about me adding multiple tasks because I thought something was wrong - yes.  I know I've done the following:
1.  mark weekly status as done
1.  immediately worry that the recurring task isn't working, so look at "task recur"
1.  notice that the next weekly status wasn't showing, so add it in again
1.  "task recur" now shows what I expect to see

I wonder if part of the issue is that I'm not waiting long enough, i.e., if I didn't do "task recur" until the next day, maybe my new task would show up?  That seems to be what your comment #6 is implying?  

I've just done a similar testing with a daily recurring task:

<pre>
F:\Dropbox\My Dropbox\TextFiles>t add testing due:today recur:daily
Created task 43

F:\Dropbox\My Dropbox\TextFiles>t recur
ID Project Pri Due       Countdown Recur   Active Age    Description
* - ------- --- --------- --------- ------- ------ ------ -------------------------------------------------------------------------
44             8/31/2010     7 hrs   daily        3 secs testing
45             9/1/2010    -16 hrs   daily        3 secs testing
21             9/1/2010     -1 day monthly         3 wks Save last months google calendar to pdf and import into EN
                                                         (smaller/colour)
37         H   9/3/2010    -3 days  weekly         6 wks Weekly Status Report
4 tasks

F:\Dropbox\My Dropbox\TextFiles>t ls testing
ID Project Pri Countdown * + R Description
* - ------- --- --------- - - - -----------
44                 7 hrs     R testing
45               -16 hrs     R testing
2 tasks

F:\Dropbox\My Dropbox\TextFiles>t do 44
Completed 44 'testing'
Marked 1 task as done

F:\Dropbox\My Dropbox\TextFiles>t ls testing
ID Project Pri Countdown * + R Description
* - ------- --- --------- - - - -----------
44               -16 hrs     R testing
1 task

F:\Dropbox\My Dropbox\TextFiles>t do 44
Completed 44 'testing'
Marked 1 task as done

F:\Dropbox\My Dropbox\TextFiles>t ls testing
No matches.

F:\Dropbox\My Dropbox\TextFiles>t recur
ID Project Pri Due      Countdown Recur   Active Age   Description
* - ------- --- -------- --------- ------- ------ ----- ---------------------------------------------------------------------------
21             9/1/2010    -1 day monthly        3 wks Save last months google calendar to pdf and import into EN (smaller/colour)
37         H   9/3/2010   -3 days  weekly        6 wks Weekly Status Report
</pre>

I see that after doing the two "testing" tasks that I can see, there is nothing listed when I run "task recur".  That's unexpected, and why I keep re-adding the tasks.

So, I'm thinking that the problem is that I thought the recurring tasks were broken and kept adding them in.  (I could have sworn that in an earlier version I could see my recurring weekly status task even after doing it, but maybe I had a higher recurrence limit set then.)

So maybe my question should be: why does "task recur" not show *all* recurring tasks?  Thanks!

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-08-31T09:10:04Z says:_ 

 Thanks for the additional data.  When I take the lines searched from your pending file, and put them in my own test file (line numbers removed), I get this:

<pre>
$ task rc:x 1-5 info

Name        Value
* ---------- --------------------------------------------------------------------
ID          1
Description Save last months google calendar to pdf and import into EN
            (smaller/colour)
Status      Recurring
Recurrence  monthly
Mask        ++XX
Mask Index
Due         7/1/2010
UUID        85e21321-6761-9750-2b22-42c1b8b112ba
Entered     6/4/2010 (2 mths)


Name        Value
* ---------- ------------------------------------
ID          2
Description infor
Status      Recurring
Priority    H
Recurrence  weekly
Mask        +++++-
Mask Index
Due         7/30/2010
UUID        228a2366-09b8-6bd5-55ca-fe6b85bfc8af
Entered     7/17/2010 (6 wks)


Name        Value
* ---------- --------------------------------------------------------------------
ID          3
Description Save last months google calendar to pdf and import into EN
            (smaller/colour)
Status      Recurring
Recurrence  monthly
Mask        -
Mask Index
Due         9/1/2010
UUID        24c745aa-f8c9-586e-86fe-aa86d25bb7ed
Entered     8/6/2010 (3 wks)


Name        Value
* ---------- --------------------------------------------------------------------
ID          4
Description Save last months google calendar to pdf and import into EN
            (smaller/colour)
Status      Pending
Recurrence  monthly
Parent task 24c745aa-f8c9-586e-86fe-aa86d25bb7ed
Mask Index  0
Due         9/1/2010
UUID        e2881956-6081-c549-1a5f-82af380a3651
Entered     8/6/2010 (3 wks)


Name        Value
* ---------- ------------------------------------
ID          5
Description Weekly Status Report
Status      Pending
Priority    H
Recurrence  weekly
Mask        +++++
Parent task 228a2366-09b8-6bd5-55ca-fe6b85bfc8af
Mask Index  5
Due         9/3/2010
UUID        384ca0ac-8eab-d24a-46b9-045312b207c4
Entered     7/17/2010 (6 wks)
</pre>

There is a lot of good info here, namely:
1.  Task 1 is a monthly recurring parent task, entered 6/4/2010.  The mask is + + X X, which mean the first two were completed and the next two were deleted.  This recurring task is not due to generate another recurring task for a while.  It has no child tasks.
1.  Task 2 is a weekly parent task, entered 7/17/2010, with a mask of + + + + + -, which means the first 5 were completed, and the sixth is still pending.  That's actually what task 5 is.
1.  Task 3 is a monthly parent task, with a mask of -, which means one outstanding pending task, which happens to be task 4.
1.  Task 5 has a mask + + + + + and shouldn't have any mask - that's the bug I fixed last night, and while a distraction, isn't causing any problems here.

In other words, this is all consistent.  I think we have three problems here:  you are taking corrective action when there isn't a need; you have multiple recurring tasks based on the corrective action; and finally there is a task bug regarding recurring tasks that we've never directly seen, but we know to exist.

My suggestion for you:
1.  Delete all your recurring tasks - this is important because you have duplicates in there, which is compounding the issue
1.  Check in your pending.data file for any mask:" lines, to see if you got them all
1.  Re-enter your two recurring tasks (status report and google calendar)
1.  Do this:  "task config recurrence.limit 2" which will make task look one step further into the future
1.  Then going forward, don't make any corrective actions if you see gaps - just wait for them to be filled.  Just remember, every time you run a report, task checks to see if there are any gaps that need to be filled *before* showing the report

My suggestion for me:
1.  Keep this bug open because there's just too much good stuff in it to close it, but move it to 1.9.4
1.  Boost the recurring task unit tests, because we need to close in on the bug.

**Comment by taskwarrior** [comment]
_Michelle Crane on 2010-08-31T10:46:06Z says:_ 

 Paul, excellent.  I shall follow your instructions, and stop re-creating my recurring tasks when I don't see them right away ;)

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-02-12T01:16:49Z says:_ 

 I believe this issue is closed.

**Comment by pbeckingham** [comment]
[TW-889_.taskrc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756265/TW-889_.taskrc.txt)
[TW-889_trace.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756266/TW-889_trace.txt)
