### ISSUE TITLE
[TW-890] Calendar error

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#925]
_Jostein Berntsen on 2010-11-10T14:23:57Z says:_ 

 I did not find the Norwegian holiday file in the new 1.9.3:

<pre>
ls /usr/local/share/doc/task/rc/
dark-16.theme   dark-blue-256.theme   dark-red-256.theme      dark-yellow-green.theme  holidays-DE.rc  holidays-FR.rc  holidays-SE.rc  holidays-US.rc  light-256.theme
dark-256.theme  dark-green-256.theme  dark-violets-256.theme  holidays-CA.rc           holidays-ES.rc  holidays-NL.rc  holidays-UK.rc  light-16.theme
</pre>

So I tried the Swedish and the US ones by including them in taskrc. I then got these errors:

Swedish:

<pre>
~> task cal
"20101106" is not a valid date (DEFAULT).
</pre>

US:

<pre>
~> task calendar
"20101106" is not a valid date (DEFAULT).
</pre>

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-11-10T14:23:57Z
Modified: 2014-02-09T02:11:50Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-11-10T17:44:37Z says:_ 

 The holidays-NO.rc file was omitted from the top-level makefile.  File is attached.

**Comment by taskwarrior** [comment]
_Jostein Berntsen on 2010-11-11T02:50:53Z says:_ 

 Thanks. I tested the NO file now, but get this same error:

 task cal
"20110602" is not a valid date (DEFAULT).

Do you know why I get this?

**Comment by taskwarrior** [comment]
_Jostein Berntsen on 2010-11-11T04:20:06Z says:_ 

 I changed the setting Y-m-d to "dateformat.holiday=Ymd" in taskrc and now it works. All holidays are displayed correctly. Thanks.

**Comment by pbeckingham** [comment]
[TW-890_holidays-NO.rc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756268/TW-890_holidays-NO.rc.txt)
