### ISSUE TITLE
[TW-902] Recurring task continually spawns new tasks

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#937]
_Bryce Harrington on 2011-01-23T15:36:48Z says:_ 

 Problem is that after adding a recurring task, extra copies of it get spawned each time task list is called.

Encountered this in the current git version of task (up to commit 5317703d).  Doesn't appear to be in 1.9.3.

Sample session reproducing the bug is attached.

I've experimented with different recur: and due: parameters but they don't seem to make much difference.

What I've found is if I edit the pending.data, there is an extra entry for the task which has neither a mask: or imask: for it.  If I delete that task and save pending.data, then task behaves properly again.

Since this is a regression in core functionality and so easily reproducible I'm setting the priority to High.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-01-23T15:36:48Z
Modified: 2014-02-09T02:11:51Z
```

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2011-01-23T15:55:32Z says:_ 

 Btw, also updated to today's current git (commit 2d50d1cb) and found the issue can still be reproduced after rebuilding and using ./src/task from git.

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2011-01-23T16:12:46Z says:_ 

 Re-confirmed that installing 1.9.4 from git master the issue goes away.

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2011-01-23T17:25:20Z says:_ 

 Good find, Bryce. I can reproduce.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-01-23T17:31:28Z says:_ 

 Bryce:  note that git master is a branch that has 1.9.3 merged to it.  1.9.4 is a separate, unmerged branch, because it hasn't been released yet.

**Comment by taskwarrior** [comment]
_Bryce Harrington on 2011-01-23T17:32:30Z says:_ 

 Right, sorry I meant to say "installing 1.9.3 from git master the issue goes away"

**Comment by pbeckingham** [comment]
[TW-902_sample.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756269/TW-902_sample.txt)
