### ISSUE TITLE
[TW-915] yes/no prompts aren't consistant

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#950]
_steve rader on 2010-12-30T09:04:19Z says:_ 

 i wanna always just type y or n.
("Yes" required, are you kidding me?!)
:)
in util.cpp confirm() et al aren't consistant.
so a patch is attached for your consideration.
it makes also makes the prompts all lowercase
but allows for Yes for backward compatability.
thanks,
steve
* -

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-12-30T09:04:19Z
Modified: 2014-02-09T02:11:51Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-12-30T21:15:07Z says:_ 

 Patch on hold because our unit tests are not building with cmake yet.

Problems:
* Patch omits necessary changes to task-tutorial.5
* Patch omits necessary changes to bug.bulk.t
* Problem with the implementation

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-01-03T23:14:52Z says:_ 

 Patch modified to match how autocomplete works.

**Comment by pbeckingham** [comment]
[TW-915_PATCH-yn.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756270/TW-915_PATCH-yn.txt)
