### ISSUE TITLE
[TW-919] "task edit" improvements

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#954]
_steve rader on 2011-01-05T07:57:12Z says:_ 

 As per email discussion with support(at)taskwarrior.org enclosed find a patch 
which improves "task edit" in two ways.

1) It makes the "task edit" file's comments re annotations read like so...
<pre>
1.  Annotations look like this: <date> -- <text> and there can be any number of them.
1.  The ' -- ' separator between the date and text field should not be removed.
1.  A "blank slot" for adding an annotation follows for your convenience.
</pre>

2) It allows for one to use...
<pre>
edit.verbose=no
</pre> 
...to get "task edit" files with *no* comments.

Keep in mind that "task edit"--especially with rc.edit.verbose=no set--is an 
expert-mode kind of command not ment for general use.  Please consider using more
gentle means for editing tasks.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-01-05T07:57:12Z
Modified: 2014-02-09T02:11:52Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2011-01-05T08:57:53Z says:_ 

 Patch accepted with modifications:
*  Inconsistent code indentation
*  No modification to documentation
*  Repeated access to the same config settings

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2011-01-22T19:47:21Z says:_ 

 I just wanted to comment that I love the edit.verbose=no feature.

**Comment by pbeckingham** [comment]
[TW-919_PATCH-edit-improvements.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756271/TW-919_PATCH-edit-improvements.txt)
