### ISSUE TITLE
[TW-942] New Zealand Holidays

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#977]
_Stephen Heywood on 2011-01-10T18:04:37Z says:_ 

 Created and attached a holiday file for New Zealand, with dates from late 2010 until 2013.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2011-01-10T18:04:37Z
Modified: 2014-02-09T02:11:53Z
```

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2011-01-10T18:28:05Z says:_ 

 Thank you Stephen. You are now mentioned in the AUTHORS file.

**Comment by pbeckingham** [comment]
[TW-942_holidays-NZ.rc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756272/TW-942_holidays-NZ.rc.txt)
