### ISSUE TITLE
[TW-944] xterm title output

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#979]
_David Patrick on 2009-11-07T16:06:19Z says:_ 

 if we're uxing task with an xterm window (and you know we are) I think it would be swell to have some data passed to the xterm window title (like vim does it) so that wherever you are in the data output, you could see the name of the application last used and the command just entered, like 

=====================================================
Xterm - list proj:foo date.not.due: - Taskwarrior 2.1
=====================================================
output
output
output
scrolling in a pager
output

Of course, this title will only apply to the very last task command issued, and clearing that xterm title text would be the polite thing to do.

**Comment by pbeckingham** [comment]
[TW-944_xtermtb.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756273/TW-944_xtermtb.txt)
