### ISSUE TITLE
[TW-36] Errors from system calls in perl unit tests are not caught

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#98]
_Scott Kostyshak on 2012-08-03T05:56:48Z says:_ 

 In the perl tests there are no checks that the system commands run were run without error. Although in some cases an error occurring in a system command would cause a test to fail (and thus we would be made aware), this is not always the case.
For example, take bug.1006.t (chosen at random). Consider the following negative test:

<pre>
1.  Check that the completion works when needed
$output = qx{../src/task rc:bug.rc des:des 2>&1};
unlike ($output, qr/No matches./ms, 'Task found using its description');
</pre>

Suppose the programmer had made a mistake and put <pre>./src/task</pre> instead of <pre>../src/task</pre>

The tests all pass:
<pre>
scott(at)pango:~/task.git/test$ ./bug.1006.t 
1..5
ok 1 - Created bug.rc
ok 2 - Attribute not completed in description
Use of uninitialized value $this in pattern match (m//) at ./bug.1006.t line 54.
ok 3 - Task found using its description
ok 4 - 'entrée' left intact
ok 5 - Cleanup
</pre>

Test 3 passes because the error string does not match the regex. `make test` will not indicate any error. One would have to read through all.log to know that something were amiss.

Such an uncaught error seems like a realistic possibility to me, especially for negative tests. There are other problems that could arrive, although these are more contrived (e.g. what if an error message matches a positive test?)

Possible solutions?

Here are a few ideas:
(a) Check the return code from qx manually for every qx call. This seems annoying, would take a while to convert the current qx's, and would complicate the readability of the code.

(b) Write a custom qx wrapper in perl that does the same as qx but checks the return code. Call this function "qxx"? Actually, we probably don't want the name to be similar to "qx" because we would want "qx" calls to stick out.

(c) Instead of qx, use backticks (the function of backticks is equivalent to qx) and then use the Backticks perl package, which allows for more control over system calls made using backticks, one of which allows you to have failed commands automatically "die" your Perl script:
$Backticks::autodie = 1;
Note that I have no experience using this package and it looks very new.

(d) Have an automated check of all.log. The following command gives some good info: `grep "^[^o#1]" all.log`. For example, we could assert that `grep "^[^o#1]" all.log | wc` stays constant (and whenever there is a valid exception just update the comparison array). Clearly we would want more structure on the grep regex given above.

(e) Ignore this potential problem. Am I making a big deal out of nothing here?

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2012-08-03T05:56:48Z
Modified: 2014-03-07T02:36:53Z
```

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-08-03T07:19:33Z says:_ 

 This seems important to me as it could improve the test strategy.

As 'like' statements may be more robust, another solution would be to precede each 'unlike' by a 'like'. 

The command:
<pre>
awk '/qx/ { like = "false" } /unlike/ { if (like != "true") { like = "true"; print "like needed first" } } /\<like/ { like = "true" }' *.t | wc -l
</pre>
shows that there is 215 places where it could be done.

Solution d could be a nice minimal addition but it would work only the first time a variable is not initialized ('output' tends to be reused quite a lot).

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2012-08-03T12:00:49Z says:_ 

 (f) A variant of d. Instead of checking all.log after the test run, there is a pre-test checking all unit tests for usage of '../src/task'. And stops the test run if it is failing.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2012-08-03T12:23:31Z says:_ 

 I like (a).  I think checking the return code is the right way.  Then we can apply it where we think it matters, and ignore it when we don't.  Like this:

<pre>
$output = qx{... 2>&1};
ok ($? == 0, 'Exit status check');
...
</pre>

although there are 215 potential uses, as Louis-Claude found, we may not need this for all of them, and it would be an identical test - it doesn't need an identifying description.  So it would be a copy/paste.

**Comment by taskwarrior** [comment]
_Louis-Claude Canon on 2012-08-03T21:08:42Z says:_ 

 There are finally around 60 files to checked and some of them are false positive.

<pre>
ls *.t | xargs -L 1 awk '/=[ ]*qx/ { if (like == "false") { result = "true" } like = "false" } /\<like\>/ { like = "true" } END { if (like == "false" || result == "true") print FILENAME }'
</pre>

I started to improve some of them (around 15) by adding like statements. While doing this, I found that some of the unlike statements would actually not activate if there was a bug. It may be a good opportunity to review some of the tests and maybe to propose guidelines to code tests (for example, using string in unlike statements only when they have been used in a previous like statement). I have taken some notes and I will propose something later, but maybe there are already existing conventions about this.

**Comment by taskwarrior** [comment]
_Federico Hernandez on 2012-08-03T21:20:55Z says:_ 

 I prefer Paul's (new) modified a. Easy to implement. Not disturbing the main test writing.

**Comment by taskwarrior** [comment]
_Cory Donnelly on 2012-08-06T16:32:21Z says:_ 

 Thanks for digging into older test cases, Louis-Claude -- we were definitely due.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2013-01-19T17:39:38Z says:_ 

 Applied Louis-Claude's patch, but needed to do a few manual edits, due to some tests having been updated in between.

The larger effort of checking all return codes is deferred, the plan being to add the following:

<pre>
$output = qx{... 2>&1};
ok ($? == 0, 'Exit status check');
...
</pre>

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2013-02-04T04:54:37Z says:_ 

 Paul Beckingham wrote:
> Applied Louis-Claude's patch, but needed to do a few manual edits, due to some tests having been updated in between.
> 
> The larger effort of checking all return codes is deferred, the plan being to add the following:
> 
> [...]

I'm wondering if a wrapper might be useful here. See the file qxE_example.diff for an example. The subroutine would be imported and not embedded as it is in the example. This might have the following advantages:
(1) this would encourage writers of tests to include exit status checks because it is just a few characters difference instead of a line difference.
(2) it reduces possible typos when writing the exit check (although with the template one would probably just copy/paste).

I'm not convinced this is good, but wanted to put it out there for comments. Note that if you wanted a custom message instead of "Exit status check" you could just have the subroutine take another parameter, but I think this complicates things.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2013-02-04T04:54:37Z says:_ 

 Attachment qxE_example.diff has been added with description: example of a wrapper that automatically does exit status check

**Comment by taskwarrior** [comment]
_Renato Alves on 2014-03-07T02:17:15Z says:_ 

 The new unittesting setup using python already implements this.

Migration of existing perl scripts is currently in progress.

**Comment by taskwarrior** [comment]
_Scott Kostyshak on 2014-03-07T02:36:53Z says:_ 

 Great! Good work, Renato.

**Comment by pbeckingham** [comment]
[TW-36_0001-Unit-Test.patch.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755547/TW-36_0001-Unit-Test.patch.txt)
[TW-36_qxE_example.diff.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1755548/TW-36_qxE_example.diff.txt)
