### ISSUE TITLE
[TW-948] Danish holidays

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskwarrior#983]
_Irfan Siddiqui on 2010-12-15T14:53:19Z says:_ 

 I think Taskwarrior needs danish holidays. I have therefore attached a (at)holidays-DK.rc@ file for the years 2010-2012.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2010-12-15T14:53:19Z
Modified: 2014-02-09T02:11:53Z
```

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-12-15T15:25:48Z says:_ 

 Thank you Irfan.

**Comment by taskwarrior** [comment]
_Paul Beckingham on 2010-12-15T15:29:39Z says:_ 

 Beautifully done.  It will be in 1.9.4, and your name in the AUTHORS file.  Thanks again.

**Comment by pbeckingham** [comment]
[TW-948_holidays-DK.rc.txt](https://github.com/GothenburgBitFactory/taskwarrior/files/1756274/TW-948_holidays-DK.rc.txt)
